{
 "title": "ETL - Очереди задач",
 "description": "Ответственный: Антипин Д. И. (Saby Trade)",
 "tags": [
  "scripts",
  "service",
  "tender"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "stand", "label": "Стенд", "query": "tag_values(contur)" }
  ]
 },
 "panels": [
  {
   "title": "planned_queue",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди отложенных задач в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=planned_queue', 'sub_metric=~(total|errors|ConnProblem)', 'interval=60s'), 'max'), 'sub_metric'), true, true)"
    }
   ]
  },
  {
   "title": "exec_queue",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди выполняемых задач в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=exec_queue'), 'max'), 'sub_metric'), true, true)"
    }
   ]
  },
  {
   "title": "high_importance_queue, priority: 200",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"высокой\" важности с приоритетом 200 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=high_importance_queue_200'), 'max'), 'sub_metric')"
    }
   ]
  },
  {
   "title": "normal_importance_queue, priority: 200",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"нормальной\" важности с приоритетом 200 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=normal_importance_queue_200'), 'max'), 'sub_metric')"
    }
   ]
  },
  {
   "title": "low_importance_queue, priority: 200",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"низкой\" важности с приоритетом 200 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=low_importance_queue_200'), 'max'), 'sub_metric')"
    }
   ]
  },
  {
   "title": "high_importance_queue, priority: 150",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"высокой\" важности с приоритетом 150 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=high_importance_queue_150'), 'max'), 'sub_metric')"
    }
   ]
  },
  {
   "title": "normal_importance_queue, priority: 150",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"нормальной\" важности с приоритетом 150 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=normal_importance_queue_150'), 'max'), 'sub_metric')"
    }
   ]
  },
  {
   "title": "low_importance_queue, priority: 150",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"низкой\" важности с приоритетом 150 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=low_importance_queue_150'), 'max'), 'sub_metric')"
    }
   ]
  },
  {
   "title": "high_importance_queue, priority: 100",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"высокой\" важности с приоритетом 100 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=high_importance_queue_100'), 'max'), 'sub_metric')"
    }
   ]
  },
  {
   "title": "normal_importance_queue, priority: 100",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"нормальной\" важности с приоритетом 100 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=normal_importance_queue_100'), 'max'), 'sub_metric')"
    }
   ]
  },
  {
   "title": "low_importance_queue, priority: 100",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"низкой\" важности с приоритетом 100 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=low_importance_queue_100'), 'max'), 'sub_metric')"
    }
   ]
  },
  {
   "title": "high_importance_queue, priority: 50",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"высокой\" важности с приоритетом 50 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=high_importance_queue_50'), 'max'), 'sub_metric')"
    }
   ]
  },
  {
   "title": "normal_importance_queue, priority: 50",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"нормальной\" важности с приоритетом 50 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=normal_importance_queue_50'), 'max'), 'sub_metric')"
    }
   ]
  },
  {
   "title": "low_importance_queue, priority: 50",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"низкой\" важности с приоритетом 50 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=low_importance_queue_50'), 'max'), 'sub_metric')"
    }
   ]
  },
  {
   "title": "high_importance_queue, priority: 0",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"высокой\" важности с приоритетом 0 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=high_importance_queue_0'), 'max'), 'sub_metric')"
    }
   ]
  },
  {
   "title": "normal_importance_queue, priority: 0",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"нормальной\" важности с приоритетом 0 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=normal_importance_queue_0'), 'max'), 'sub_metric')"
    }
   ]
  },
  {
   "title": "low_importance_queue, priority: 0",
   "type": "timeseries",
   "description": "Общий размер и количество ошибок в очереди активных задач \"низкой\" важности с приоритетом 0 в etl-queue",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=tender-robots.ETLQueueCount', 'contur=$stand', 'queue=low_importance_queue_0'), 'max'), 'sub_metric')"
    }
   ]
  }
 ]
}