{
 "title": "Online.tensor.ru, reg.tensor.ru - Валидность страницы index.html",
 "description": "Ответственный: Ледяев И.К. (Эксплуатация)",
 "tags": [
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Проверка страницы index.html online.sbis.ru",
   "type": "graph",
   "description": "Проверка корректности открытия страницы, показывает время ответа",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=response.time', 'type=page_validity', 'site=online.sbis.ru', 'script=ws_page_ok.py'), 'unit')"
    }
   ]
  },
  {
   "title": "Проверка страницы index.html reg.tensor.ru",
   "type": "graph",
   "description": "Проверка корректности открытия страницы, показывает время ответа",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=response.time', 'type=page_validity', 'site=reg.tensor.ru', 'script=ws_page_ok.py'), 'site')"
    }
   ]
  },
  {
   "title": "Проверка страницы wi.sbis.ru/api",
   "type": "graph",
   "description": "Проверка корректности открытия страницы, показывает время ответа",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('script=ws_page_ok.py', 'contur=prod', 'site=wi.sbis.ru/api/'), 'site')"
    }
   ]
  },
  {
   "title": "Проверка страницы my.sbis.ru/page/contacts",
   "type": "graph",
   "description": "Проверка корректности открытия страницы, показывает время ответа",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('script=msr_page_check.py', 'contur=prod', 'site=my.sbis.ru'), 'site')"
    }
   ]
  }
 ]
}