{
 "title": "SBIS Communication - Вебинары: Gateway",
 "description": "Ответственный: Никитин М.С. (Эксплуатация)",
 "tags": [
  "scripts",
  "service",
  "webinar"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "contur", "label": "контур", "query": "prod" },
   {
    "name": "webinar",
    "query": "tag_values(webinarId,contur=$contur)"
   }
  ]
 },
 "panels": [
  {
   "title": "Producer bitrate $webinar",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=webinar.webrtcgateway.m.bitrate', 'role=producer', 'webinarId=$webinar'),  'streamUUID', 'type')"
    }
   ]
  },
  {
   "title": "Consumer bitrate $webinar",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=webinar.webrtcgateway.m.bitrate', 'role=consumer', 'webinarId=$webinar'), 'streamUUID', 'type')"
    }
   ]
  },
  {
   "title": "Producer bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=webinar.webrtcgateway.m.byteCount', 'role=producer', 'contur=$contur', 'webinarId=$webinar'), 'streamUUID', 'type', 'role')"
    }
   ]
  },
  {
   "title": "Consumer bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=webinar.webrtcgateway.m.byteCount', 'role=consumer', 'webinarId=$webinar'), 'streamUUID', 'type', 'role')"
    }
   ]
  },
  {
   "title": "Nack count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=webinar.webrtcgateway.m.nackCount', 'contur=$contur', 'webinarId=$webinar'), 'webinarId', 'streamUUID', 'type', 'role', 'name'), '_._', '.'), 'webinar.webrtcgateway.m.', '')"
    }
   ]
  },
  {
   "title": "Nack packet count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=webinar.webrtcgateway.m.nackPacketCount', 'webinarId=$webinar'), 'streamUUID', 'type', 'role', 'name'), '_._', '.'), 'webinar.webrtcgateway.m.', '')"
    }
   ]
  },
  {
   "title": "Packet count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=webinar.webrtcgateway.m.packetCount', 'contur=$contur', 'webinarId=$webinar'), 'webinarId', 'streamUUID', 'type', 'role', 'name'), '_._', '.'), 'webinar.webrtcgateway.m.', '')"
    }
   ]
  },
  {
   "title": "Discarded/Lost packet count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=~webinar.webrtcgateway.m.packets(Discarded|Lost)', 'contur=$contur', 'webinarId=$webinar'), 'streamUUID', 'type', 'role', 'name'), '_._', '.'), 'webinar.webrtcgateway.m.', '')"
    }
   ]
  },
  {
   "title": "Repaired/Retransmitted packet count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=~webinar.webrtcgateway.m.packets(Repaired|Retransmitted)', 'contur=$contur', 'webinarId=$webinar'),'streamUUID', 'type', 'role', 'name'), '_._', '.'), 'webinar.webrtcgateway.m.', '')"
    }
   ]
  },
  {
   "title": "Fir/Pli count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=~webinar.webrtcgateway.m.(firCount|pliCount)', 'contur=$contur', 'webinarId=$webinar'), 'streamUUID', 'type', 'role', 'name'), '_._', '.'), 'webinar.webrtcgateway.m.', '')"
    }
   ]
  }
 ]
}