{
 "title": "SBIS Communications: vcall-recorder - использование системных ресурсов",
 "description": "Ответственный: Карпов С.В. (Эксплуатация)",
 "tags": [
  "service",
  "webinar",
  "scripts",
  "telegraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "contur", "label": "контур", "query": "prod" }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu=cpu-total', 'host=~csr-vcall-recorder-bl*'), 'host'), 0)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=${contur:regex}', 'host=~csr-vcall-recorder-bl*', 'name=system.mem.used_percent'), 'host')"
    }
   ]
  },
  { "title": "Disk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=${contur:regex}', 'host=~csr-vcall-recorder-bl*', 'name=system.disk.used_percent', 'path=-recordings'), 'host')"
    }
   ]
  }
 ]
}