{
 "title": "SBIS Communication - Videobridge",
 "description": "Vcall - основной сервис видеосвязи. Ответственный: Карпов С.В. (Эксплуатация), Батищев П.А. (Разработка)",
 "tags": [
  "service",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Статус сервисов", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Статус сервисов VCall",
   "type": "stat",
   "gridPos": { "h": 19, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-vcall-bl\\d.*', 'systemd_unit=~.*', 'name=~procstat.*running$'), 'host', 'systemd_unit'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Статус сервисов Jitsi-jvb",
   "type": "stat",
   "gridPos": { "h": 19, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d.*', 'systemd_unit=~jitsi-jvb.service', 'name=~procstat.*running$'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Статус сервиса videobridge",
   "type": "stat",
   "gridPos": { "h": 19, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d.*', 'name=~videobridge'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Статус сервиса vcall",
   "type": "stat",
   "gridPos": { "h": 19, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-vcall-bl\\d.*', 'name=~vcall'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "uptime контейнеров jitsi-jvb",
   "type": "stat",
   "gridPos": { "h": 19, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d.*', 'name=~docker_container_status.uptime_ns', 'container_name=jitsi-jvb'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Системные метрики БЛ сервиса vcall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~system.cpu.usage_active', 'cpu=cpu-total', 'host=~csr-vcall-bl\\d.*'), 'host')"
    }
   ]
  },
  {
   "title": "LA",
   "type": "graph",
   "description": "LA 1 5 15",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(aggregate(seriesByTag('name=system.system.n_cpus', 'host=~csr-vcall-bl\\d.*'), 'max'), 'CPU')"
    },
    {
     "target": "consolidateBy(aliasByTags(seriesByTag('name=system.system.load1', 'host=~csr-vcall-bl\\d.*'), 'host'), 'max')"
    }
   ]
  },
  {
   "title": "Memory - использование",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(seriesByTag('host=~csr-vcall-bl\\d.*', 'name=~system.mem.used_percent'), 'host'), 'max')"
    }
   ]
  },
  {
   "title": "root partition used",
   "type": "graph",
   "description": "Disk user procent",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~csr-vcall-bl\\d.*', 'name=system.disk.used_percent', 'path=-'), 'host')"
    }
   ]
  },
  {
   "title": "Системные метрики БЛ сервиса videobridge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "exclude(aliasByTags(seriesByTag('name=~system.cpu.usage_active', 'cpu=cpu-total', 'host=~csr-videobridge-bl\\d.*'), 'host'), 'idle')"
    }
   ]
  },
  {
   "title": "LA",
   "type": "graph",
   "description": "LA 1 5 15",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(aggregate(seriesByTag('name=system.system.n_cpus', 'host=~csr-videobridge-bl\\d.*'), 'max'), 'CPU')"
    },
    {
     "target": "consolidateBy(aliasByTags(seriesByTag('name=system.system.load1', 'host=~csr-videobridge-bl\\d.*'), 'host'), 'max')"
    }
   ]
  },
  {
   "title": "Memory - использование",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d.*', 'name=~system.mem.used_percent'), 'host'), 'max')"
    }
   ]
  },
  {
   "title": "root partition used",
   "type": "graph",
   "description": "Disk user procent",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d.*', 'name=system.disk.used_percent', 'path=-'), 'host')"
    }
   ]
  },
  { "title": "Сервисные метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d\\.*', 'url=http:--localhost:8080-colibri-stats', 'name=~http.threads'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Download bitrate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d\\.*', 'url=http:--localhost:8080-colibri-stats', 'name=~http.bit_rate_download'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Upload bitrate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d\\.*', 'url=http:--localhost:8080-colibri-stats', 'name=~http.bit_rate_upload'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Статус доступности страницы videobridge",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('server=~http:--csr-videobridge-bl\\d:8080-about-health', 'name=http_response.http_response_code'), 'server'), 'http:--', ''), ':8080-about-health', '')"
    }
   ]
  },
  {
   "title": "Download packetrate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d\\.*', 'url=http:--localhost:8080-colibri-stats', 'name=~http.packet_rate_download'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Upload packetrate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d\\.*', 'url=http:--localhost:8080-colibri-stats', 'name=~http.packet_rate_upload'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "RTT aggregate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d\\.*', 'url=http:--localhost:8080-colibri-stats', 'name=~http.rtt_aggregate'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Conferences",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d\\.*', 'url=http:--localhost:8080-colibri-stats', 'name=~http.conferences'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d\\.*', 'url=http:--localhost:8080-colibri-stats', 'name=~http.participants'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Jitter aggregate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d\\.*', 'url=http:--localhost:8080-colibri-stats', 'name=~http.jitter_aggregate'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Total conference seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d\\.*', 'url=http:--localhost:8080-colibri-stats', 'name=~http.total_conference_seconds'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Total failed conference seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-videobridge-bl\\d\\.*', 'url=http:--localhost:8080-colibri-stats', 'name=~http.total_failed_conferences'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  }
 ]
}