{
 "title": "SBIS Communication - Вебинары: качество вебинара",
 "description": "Ответственный: Никитин М.С. (Эксплуатация)",
 "tags": [
  "scripts",
  "service",
  "webinar"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "контур", "query": "prod" },
   { "name": "webinar", "query": "tag_values(webinarId)" }
  ]
 },
 "panels": [
  {
   "title": "Current online users amount",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(sumSeries(currentAbove(seriesByTag('name=webinar.usersAmountOnline', 'contur=~${contur:regex}'), 1)), 'webinarId')"
    }
   ]
  },
  {
   "title": "Current WS amount",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(aggregate(consolidateBy(seriesByTag('name=webinar.wscount', 'contur=~${contur:regex}'), 'maximum'), 'count'), 'count')"
    }
   ]
  },
  {
   "title": "Users total amount online",
   "type": "graph",
   "description": "Количество уникальных пользователей присутствующих на вебинаре в данный момент",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=webinar.usersAmountOnline', 'contur=${contur:regex}', 'interval=3s', 'webinarId=$webinar'), 'webinarId')"
    }
   ]
  },
  {
   "title": "Качество вебинара",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=webinar.qualityVote_0', 'webinarId=$webinar'), 'Не голосовал')"
    },
    {
     "target": "alias(seriesByTag('name=webinar.qualityVote_1', 'webinarId=$webinar'), 'Всё хорошо')"
    },
    {
     "target": "alias(seriesByTag('name=webinar.qualityVote_2', 'webinarId=$webinar'), 'Не вижу')"
    },
    {
     "target": "alias(seriesByTag('name=webinar.qualityVote_3', 'webinarId=$webinar'), 'Не слышу')"
    },
    {
     "target": "alias(seriesByTag('name=webinar.qualityVote_4', 'webinarId=$webinar'), 'Ой, всё')"
    }
   ]
  },
  {
   "title": "Connections state / Source changes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=webinar.successfulConnections', 'contur=~${contur:regex}', 'webinarId=$webinar'), 'successfull')"
    },
    {
     "target": "alias(seriesByTag('name=webinar.unsuccessfulConnections', 'webinarId=$webinar'), 'unsuccessfull')"
    },
    {
     "target": "alias(seriesByTag('name=webinar.mainSourceChanges', 'webinarId=$webinar'), 'main source changes')"
    },
    {
     "target": "alias(seriesByTag('name=webinar.reserveSourceChanges', 'webinarId=$webinar'), 'reserve source changes')"
    },
    {
     "target": "alias(seriesByTag('name=webinar.fallbackState', 'webinarId=$webinar'), 'fallback_state')"
    }
   ]
  },
  {
   "title": "Per second metrics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('name=webinar.mainSourceChanges', 'contur=~${contur:regex}', 'webinarId=$webinar')), 'main_source_changes_persec')"
    },
    {
     "target": "alias(perSecond(seriesByTag('name=webinar.unsuccessfulConnections', 'contur=~${contur:regex}', 'webinarId=$webinar')), 'unsuccessfull_conns_persec')"
    }
   ]
  },
  {
   "title": "Camera stream packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(groupByTags(seriesByTag('name=webinar.transcoding.stream.ffmpeg.packets.missed', 'webinarUUID=$webinar', 'streamId=cam_stream'), 'sum', 'streamUUID', 'host'), 'streamUUID', 'host'), '$', '.packets_missed')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=webinar.transcoding.stream.ffmpeg.packets.late', 'contur=~${contur:regex}', 'webinarUUID=$webinar', 'streamId=cam_stream'), 'streamUUID'), '$', '.packets_late')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=webinar.transcoding.stream.ffmpeg.failures', 'webinarUUID=$webinar', 'streamId=cam_stream'), 'streamUUID'), '$', '.packets_failures')"
    }
   ]
  },
  {
   "title": "Screen stream packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(groupByTags(seriesByTag('name=webinar.transcoding.stream.ffmpeg.packets.missed', 'webinarUUID=$webinar', 'streamId=screen_stream'), 'sum', 'streamUUID', 'host'), 'streamUUID', 'host'), '$', '.packets_missed')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=webinar.transcoding.stream.ffmpeg.packets.late', 'webinarUUID=$webinar', 'streamId=screen_stream'), 'streamUUID'), '$', '.packets_late')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=webinar.transcoding.stream.ffmpeg.failures', 'webinarUUID=$webinar', 'streamId=screen_stream'), 'streamUUID'), '$', '.packets_failures')"
    }
   ]
  },
  {
   "title": "Docs stream packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(groupByTags(seriesByTag('name=webinar.transcoding.stream.ffmpeg.packets.missed', 'webinarUUID=$webinar', 'streamId=doc_stream'), 'sum', 'streamUUID', 'host'), 'streamUUID', 'host'), '$', '.packets_missed')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=webinar.transcoding.stream.ffmpeg.packets.late', 'webinarUUID=$webinar', 'streamId=doc_stream'), 'streamUUID'), '$', '.packets_late')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=webinar.transcoding.stream.ffmpeg.failures', 'webinarUUID=$webinar', 'streamId=doc_stream'), 'streamUUID'), '$', '.packets_failures')"
    }
   ]
  },
  {
   "title": "Camera stream traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~webinar.transcoding.stream.input.megabytes', 'webinarUUID=$webinar', 'streamId=cam_stream')), 'streamUUID', 'host'), '.unix.tensor.ru', '.Incoming RTP')"
    },
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=webinar.transcoding.stream.recorder.megabytes', 'webinarUUID=$webinar', 'streamId=cam_stream')), 'streamUUID', 'host'), '.unix.tensor.ru,.Recorder', '')"
    }
   ]
  },
  {
   "title": "Screen stream traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~webinar.transcoding.stream.input.megabytes', 'webinarUUID=$webinar', 'streamId=screen_stream')), 'streamUUID', 'host'), '.unix.tensor.ru', '.Incoming RTP')"
    },
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=webinar.transcoding.stream.recorder.megabytes', 'webinarUUID=$webinar', 'streamId=screen_stream')), 'streamUUID', 'host'), '.unix.tensor.ru,.Recorder', '')"
    }
   ]
  },
  {
   "title": "Docs stream traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~webinar.transcoding.stream.input.megabytes', 'webinarUUID=$webinar', 'streamId=doc_stream')), 'streamUUID', 'host'), '.unix.tensor.ru', '.Incoming RTP')"
    },
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=webinar.transcoding.stream.recorder.megabytes', 'webinarUUID=$webinar', 'streamId=doc_stream')), 'streamUUID', 'host'), '.unix.tensor.ru', '.recorder')"
    }
   ]
  },
  {
   "title": "FFmpeg (uneven)",
   "type": "graph",
   "description": "MUST be +0\nBut, sometimes, audio and video streams get diverged which causes player issues.\n\nsum(chunkNo - min(chunkNo for all representations))",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~webinar.transcoding.stream.ffmpeg.chunks.uneven', 'contur=~${contur:regex}', 'webinarUUID=$webinar')), 'streamId', 'host', 'name'), '.unix.tensor.ru.webinar.transcoding.stream.ffmpeg.chunks.', ' ')"
    }
   ]
  },
  {
   "title": "Recorder (restarts)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=webinar.transcoding.stream.recorder.restarts', 'contur=~${contur:regex}', 'webinarUUID=$webinar')), 'streamId', 'streamUUID')"
    }
   ]
  },
  {
   "title": "FFmpeg (chunkbeat)",
   "type": "graph",
   "description": "Unlike the human ones, these should look pretty much like straight lines",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~webinar.transcoding.stream.ffmpeg.chunks.count', 'webinarUUID=$webinar')), 'streamId', 'host', 'name'), '.unix.tensor.ru.webinar.transcoding.stream.ffmpeg.chunks.', ' ')"
    }
   ]
  },
  {
   "title": "FFmpeg (chunk pace)",
   "type": "graph",
   "description": "Both jumps and backs should be 0.\nFluctuations should be +0",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~webinar.transcoding.stream.ffmpeg.chunks.(jumps|backs)', 'contur=~${contur:regex}', 'webinarUUID=$webinar')), 'streamId', 'host', 'name'), '.unix.tensor.ru.webinar.transcoding.stream.ffmpeg.chunks.', ' ')"
    },
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~webinar.transcoding.stream.ffmpeg.chunks.fluctuations', 'contur=~${contur:regex}', 'webinarUUID=$webinar')), 'streamId', 'host', 'name'), '.unix.tensor.ru.webinar.transcoding.stream.ffmpeg.chunks.', ' ')"
    }
   ]
  },
  {
   "title": "FFmpeg (representations)",
   "type": "graph",
   "description": "Almost each of them is an encoding video stream",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~webinar.transcoding.stream.ffmpeg.chunks.representations', 'contur=~${contur:regex}', 'webinarUUID=$webinar'), 'streamId', 'host', 'name'), '.unix.tensor.ru.webinar.transcoding.stream.ffmpeg.chunks.', ' ')"
    }
   ]
  }
 ]
}