{
 "title": "sbis3app",
 "description": "Ответственный: -",
 "tags": [
  "service",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.sbis3app.status.*"
   },
   { "name": "domain", "label": "Домен", "query": "*.tensor.ru" },
   {
    "name": "port",
    "label": "Порт",
    "query": "sbis3mon.$contur.sbis3app.status.$server.sbis3.*"
   },
   {
    "name": "service",
    "label": "Сервис",
    "query": "sbis3mon.$contur.sbis3app.$server.$domain.$port.*.aggr-$aggr.sbis3.svcdb.*"
   },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  {
   "title": "$server service (workers,  workers_pct)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "server"
  },
  {
   "title": "$server: service workers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sbis3mon.$contur.sbis3app.info_srv.$server.sbis3.$port.*.sbis3.service.workers.{avail,avail-max}.*.$aggr | aliasByNode(-3, -2) | aliasSub('_2F|_5F', ' ')"
    },
    {
     "target": "sbis3mon.$contur.sbis3app.info_srv.$server.sbis3.$port.*.sbis3.service.workers.{free,free-min}.*.$aggr | aliasByNode(-3, -2)  | aliasSub('_2F|_5F', ' ')"
    },
    {
     "target": "sbis3mon.$contur.sbis3app.info_srv.$server.sbis3.$port.*.sbis3.service.workers.{used,used-max}.*.$aggr | aliasByNode(-3, -2)  | aliasSub('_2F|_5F', ' ')"
    }
   ]
  },
  {
   "title": "$server: service workers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sbis3mon.$contur.sbis3app.info_srv.$server.sbis3.$port.*.sbis3.service.workers.avail.*.pct.$aggr | aliasByNode(-5, -4, -2, -1)"
    },
    {
     "target": "sbis3mon.$contur.sbis3app.info_srv.$server.sbis3.$port.*.sbis3.service.workers.free.*.pct.$aggr | aliasByNode(-5, -4, -2, -1)"
    },
    {
     "target": "sbis3mon.$contur.sbis3app.info_srv.$server.sbis3.$port.*.sbis3.service.workers.used.*.pct.$aggr | aliasByNode(-5, -4, -2, -1)"
    }
   ]
  },
  {
   "title": "$server service (request, ping)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "server"
  },
  {
   "title": "$server: service request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sbis3mon.$contur.sbis3app.info_srv.$server.sbis3.$port.*.sbis3.service.request.processed.*.$aggr | aliasByNode(-4, -2) | aliasSub('_2F|_5F', ' ')"
    },
    {
     "target": "sbis3mon.$contur.sbis3app.info_srv.$server.sbis3.$port.*.sbis3.service.request.error.*.$aggr | aliasByNode(-4, -2) | aliasSub('_2F|_5F', ' ')"
    },
    {
     "target": "sbis3mon.$contur.sbis3app.info_srv.$server.sbis3.$port.*.sbis3.service.request.queued.*.$aggr | aliasByNode(-4, -2) | aliasSub('_2F|_5F', ' ')"
    }
   ]
  },
  {
   "title": "$server: service ping",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "sbis3mon.$contur.sbis3app.info_srv.$server.sbis3.$port.*.sbis3.service.ping.*.load.raw | alias('ping load')"
    }
   ]
  },
  { "title": "$server svcdb (echo)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "server" },
  {
   "title": "$server: echo",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.testecho.$server.sbis3.$port.*.sbis3.svcdb.echo.*.raw, -2), '_2F', '')"
    }
   ]
  }
 ]
}