{
 "title": "SBIS Communications: Вебинары - использование системных ресурсов",
 "description": "Ответственный: Карпов С.В. (Эксплуатация)",
 "tags": [
  "service",
  "webinar",
  "scripts",
  "telegraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "contur", "label": "контур", "query": "prod" }
  ]
 },
 "panels": [
  {
   "title": "Количество вебинаров & users total amount online",
   "type": "graph",
   "description": "статистика во времени, сколько проходило вебинаров и общее количество пользователей онлайн",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(currentAbove(seriesByTag('name=webinar.usersAmountOnline', 'contur=~${contur:regex}'), 1)), 'Viewers')"
    },
    {
     "target": "alias(aggregate(consolidateBy(seriesByTag('name=webinar.wscount', 'contur=~${contur:regex}'), 'max'), 'count'), 'WS')"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Origins",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu=cpu-total', 'host=~csr-webinar-origin.*'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'contur=${contur:regex}', 'cpu=cpu-total', 'name=system.cpu.usage_active', 'host=~.*webinar.*'), 'host')"
    }
   ]
  },
  {
   "title": "БЛ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu=cpu-total', 'contur=${contur:regex}', 'servertype=webinar'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Core usage with maximum over 60%",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Origins",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasByTags(maximumAbove(consolidateBy(seriesByTag('name=system.cpu.usage_active', 'cpu!=cpu-total', 'host=~csr-webinar-origin.*'), 'maximum'), 60), 'host', 'cpu'), 0, -1)"
      }
     ]
    },
    {
     "title": "GPUs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "maximumAbove(aliasByTags(seriesByTag('servertype=gpu', 'contur=${contur:regex}', 'cpu!=cpu-total', 'name=system.cpu.usage_active', 'host=~.*webinar.*'), 'host', 'cpu'), 60)"
      }
     ]
    },
    {
     "title": "БЛ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "maximumAbove(aliasByNode(aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu!=cpu-total', 'contur=${contur:regex}', 'servertype=webinar'), 'host', 'cpu'), 0, -1), 60)"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Origins",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=${contur:regex}', 'host=~csr-webinar-origin.*', 'name=system.mem.active'), 'host')"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'contur=${contur:regex}', 'host=~.*webinar.*', 'name=system.mem.active'), 'host')"
    }
   ]
  },
  {
   "title": "БЛ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.mem.active', 'contur=${contur:regex}', 'servertype=webinar'), 'host'), 0)"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Origins",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=${contur:regex}', 'host=~csr-webinar-origin.*', 'name=system.netstat.tcp_established'), 'host')"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'contur=${contur:regex}', 'host=~.*webinar.*', 'name=system.netstat.tcp_established'), 'host')"
    }
   ]
  },
  {
   "title": "БЛ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.netstat.tcp_established', 'contur=${contur:regex}', 'servertype=webinar'), 'host'), 0)"
    }
   ]
  },
  { "title": "Additional GPU stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Nvidia GPU utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('servertype=gpu', 'name=nvidia_smi.utilization_gpu', 'contur=${contur:regex}', 'host=~.*webinar.*'), 'sum', 'host'), 'host')"
    }
   ]
  },
  {
   "title": "Nvidia encoder utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('servertype=gpu', 'name=nvidia_smi.utilization_encoder', 'contur=${contur:regex}', 'host=~.*webinar.*'), 'sum', 'host'), 'host')"
    }
   ]
  },
  {
   "title": "Nvidia decoder utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('servertype=gpu', 'name=nvidia_smi.utilization_decoder', 'contur=${contur:regex}', 'host=~.*webinar.*'), 'sum', 'host'), 'host')"
    }
   ]
  }
 ]
}