{
 "title": "SBIS Communication - Мониторинг сервисов webinar",
 "description": "Ответственный: Карпов С.В. (Эксплуатация)",
 "tags": [
  "exploitation",
  "telegraf",
  "service"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "tag_values(host, servertype=~webinar.*, contur=prod, name=~procstat.*running)"
   }
  ]
 },
 "panels": [
  {
   "title": "webinar_kms_js",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'servertype=webinar', 'systemd_unit=webinar_kms_js.service', 'name=procstat.webinar_kms_js.running', 'host=~${host:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "webinar_bussiness_logics",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=webinar', 'contur=prod', 'name=procstat.webinar_bussiness_logics.running', 'systemd_unit=webinar_bussiness_logics.service', 'host=~${host:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "webinars-ps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'servertype=webinar-static', 'systemd_unit=sbis-webinar_service-ps.service', 'name=procstat.sbis-webinar_service-ps.running', 'host=~${host:regex}'), 'host')"
    }
   ]
  }
 ]
}