{
 "title": "SBIS Communication - Вебинары Remaster",
 "description": "Ответственный: Никитин М.С. (Эксплуатация)",
 "tags": [
  "scripts",
  "service",
  "webinar"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "contur", "label": "контур", "query": "prod" },
   {
    "name": "webinar_id",
    "query": "tag_values(webinarId,contur=$contur)"
   }
  ]
 },
 "panels": [
  {
   "title": "RPS Status codes summary",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(consolidateBy(groupByTags(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.\\d'), 'sum', 'host'), 'maximum')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "NEW - RPS Status codes summary",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(groupByTags(seriesByTag('contur=${contur:regex}', 'name=~webinarorigin\\.rps_\\d'), 'sum', 'host')), 'host')"
    }
   ]
  },
  {
   "title": "RPS Status codes 2xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(perSecond(seriesByTag('contur=$contur', 'name=~webinar.streaming-origin.rps.2')), 'host', 'name'), 'maximum')"
    }
   ]
  },
  {
   "title": "RPS Status codes 3xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.3')), 'host', 'name'), 'maximum')"
    }
   ]
  },
  {
   "title": "NEW - RPS Status codes 2xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(consolidateBy(perSecond(seriesByTag('contur=$contur', 'name=~webinarorigin.rps_2')), 'maximum'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "NEW - RPS Status codes 3xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(consolidateBy(perSecond(seriesByTag('contur=$contur', 'name=~webinarorigin.rps_3')), 'maximum'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "RPS Status codes 4xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(perSecond(seriesByTag('contur=$contur', 'name=~webinar.streaming-origin.rps.4')), 'host', 'name'), 'maximum')"
    }
   ]
  },
  {
   "title": "RPS Status codes 5xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(perSecond(seriesByTag('contur=$contur','name=~webinar.streaming-origin.rps.5')), 'host', 'name'), 'maximum')"
    }
   ]
  },
  {
   "title": "NEW - RPS Status codes 4xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(consolidateBy(perSecond(seriesByTag('contur=$contur', 'name=~webinarorigin.rps_4')), 'maximum'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "NEW - RPS Status codes 5xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(consolidateBy(perSecond(seriesByTag('contur=$contur', 'name=~webinarorigin.rps_5')), 'maximum'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "RPS methods summary",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(groupByTags(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.(del|get|put)'), 'sum', 'host')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "NEW - RPS methods summary",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(groupByTags(seriesByTag('contur=${contur:regex}', 'name=~webinarorigin.rps_\\d'), 'sum', 'host')), 'host')"
    }
   ]
  },
  {
   "title": "RPS DEL method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.del')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "RPS GET method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.get')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "RPS PUT method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.put')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "NEW - RPS DEL method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinarorigin\\.rps_del')), 'host')"
    }
   ]
  },
  {
   "title": "NEW - RPS GET method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinarorigin\\.rps_get')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "NEW - RPS PUT method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinarorigin\\.rps_put')), 'host', 'name')"
    }
   ]
  }
 ]
}