{
 "title": "SBIS Communication - Вебинары: Origins",
 "description": "Ответственный: Никитин М.С. (Эксплуатация)",
 "tags": [
  "scripts",
  "service",
  "webinar"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "contur", "label": "контур", "query": "prod" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-webinar-origin-bl\\d.unix.tensor.ru', 'name=http_response.response_string_match'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Newtwork statistics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~csr-webinar-origin.*', 'name=system.netstat.tcp_listen'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Disk reads/writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('host=~csr-webinar-origin.*', 'name=system.diskio.reads', '_name=~sd\\w$')), '_name', 'name')"
    }
   ]
  },
  {
   "title": "CPU busy per server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu=cpu-total', 'host=~csr-webinar-origin.*'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Mem usage by servers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=${contur:regex}', 'host=~csr-webinar-origin.*', 'name=system.mem.active'), 'host')"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=${contur:regex}', 'host=~csr-webinar-origin.*', 'name=system.netstat.tcp_established'), 'host')"
    }
   ]
  },
  {
   "title": "FS (requests)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.fs.(requests|restarts|failures)')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "FS (handles)",
   "type": "graph",
   "description": "MUST NOT saturate",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "files" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.fs.(items|pending|opened)'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Top10 by host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(keepLastValue(highestMax(seriesByTag('contur=${contur:regex}', 'name=webinar.streaming-origin.getCount.count'), 10), 10), 'host')"
    }
   ]
  },
  {
   "title": "RPS Status codes summary",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(consolidateBy(groupByTags(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.\\d'), 'sum', 'host'), 'maximum')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "RPS Status codes 2xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(perSecond(seriesByTag('contur=$contur', 'name=~webinar.streaming-origin.rps.2')), 'host', 'name'), 'maximum')"
    }
   ]
  },
  {
   "title": "RPS Status codes 3xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.3')), 'host', 'name'), 'maximum')"
    }
   ]
  },
  {
   "title": "RPS Status codes 4xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(perSecond(seriesByTag('contur=$contur', 'name=~webinar.streaming-origin.rps.4')), 'host', 'name'), 'maximum')"
    }
   ]
  },
  {
   "title": "RPS Status codes 5xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(perSecond(seriesByTag('contur=$contur','name=~webinar.streaming-origin.rps.5')), 'host', 'name'), 'maximum')"
    }
   ]
  },
  {
   "title": "RPS methods summary",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(groupByTags(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.(del|get|put)'), 'sum', 'host')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "RPS DEL method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.del')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "RPS GET method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.get')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "RPS PUT method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.put')), 'host', 'name')"
    }
   ]
  }
 ]
}