{
 "title": "SBIS Communication - Вебинары",
 "description": "Сервис выполняет функцию проведения онлайн-встреч или презентаций через Интернет. Ответственный: Карпов С.В. (Эксплуатация), Чудинов Ф.Е. и Яковлев В.В. (Разработка)",
 "tags": [
  "scripts",
  "service",
  "webinar"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "контур", "query": "prod" }
  ]
 },
 "panels": [
  {
   "title": "Amount statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current online users amount",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByTags(sumSeries(currentAbove(seriesByTag('name=webinar.usersAmountOnline', 'contur=~${contur:regex}'), 1)), 'webinarId')"
      }
     ]
    },
    {
     "title": "Current WS amount",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias(aggregate(consolidateBy(seriesByTag('name=webinar.wscount', 'contur=~${contur:regex}'), 'maximum'), 'count'), 'count')"
      },
      {
       "target": "aliasByTags(aggregate(keepLastValue(currentAbove(seriesByTag('name=webinar.usersAmountOnline', 'contur=~${contur:regex}'), 0), 1), 'count'), 'webinarId')"
      }
     ]
    },
    {
     "title": "Status webinar",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "seriesByTag('name=status_webinar_OK', 'contur=${contur:regex}')"
      }
     ]
    },
    {
     "title": "Users total amount online",
     "type": "graph",
     "description": "Количество уникальных пользователей присутствующих на вебинаре в данный момент",
     "gridPos": { "h": 5, "w": 8, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=webinar.usersAmountOnline', 'contur=${contur:regex}', 'interval=3s'), 'webinarId')"
      }
     ]
    },
    {
     "title": "Количество вебинаров & общее количество пользователей онлайн",
     "type": "graph",
     "description": "статистика во времени, сколько проходило вебинаров и общее количество пользователей онлайн",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(transformNull(sumSeries(currentAbove(seriesByTag('name=webinar.usersAmountOnline', 'contur=~${contur:regex}'), 1)), 0), 'Viewers')"
      },
      {
       "target": "alias(transformNull(sumSeries(groupByTags(currentAbove(seriesByTag('name=webinar.usersAmountOnline', 'contur=~${contur:regex}'), 0), 'count', 'webinarId')), 0), 'WS')"
      }
     ]
    },
    {
     "title": "Peers total amount online",
     "type": "graph",
     "description": "Количество открытых вкладок с вебинаром в данный момент времени",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=webinar.viewersAmount', 'contur=~${contur:regex}', 'interval=3s'), 'webinarId')"
      }
     ]
    },
    {
     "title": "Users cumulative total",
     "type": "graph",
     "description": "Количество уникальных пользователей посетивших вебинар",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=webinar.usersAmount', 'contur=~${contur:regex}'), 'webinarId')"
      }
     ]
    }
   ]
  },
  { "title": "Streaming origin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-webinar-origin-bl\\d.unix.tensor.ru', 'name=http_response.response_string_match'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Newtwork statistics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~csr-webinar-origin.*', 'name=system.netstat.tcp_listen'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Disk reads/writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('host=~csr-webinar-origin.*', 'name=system.diskio.reads', '_name=~sd\\w$')), '_name', 'name')"
    }
   ]
  },
  {
   "title": "CPU busy per server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu=cpu-total', 'host=~csr-webinar-origin.*'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Mem usage by servers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=${contur:regex}', 'host=~csr-webinar-origin.*', 'name=system.mem.active'), 'host')"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=${contur:regex}', 'host=~csr-webinar-origin.*', 'name=system.netstat.tcp_established'), 'host')"
    }
   ]
  },
  {
   "title": "FS (requests)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.fs.(requests|failures)')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "FS (handles)",
   "type": "graph",
   "description": "MUST NOT saturate",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "files" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.fs.(reads|writes|pending|opened)'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Top10 by host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(keepLastValue(highestMax(seriesByTag('contur=${contur:regex}', 'name=webinar.streaming-origin.getCount.count'), 10), 10), 'host')"
    }
   ]
  },
  {
   "title": "RPS Status codes summary",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(consolidateBy(groupByTags(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.\\d'), 'sum', 'host'), 'maximum')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "RPS Status codes 2xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(perSecond(seriesByTag('contur=$contur', 'name=~webinar.streaming-origin.rps.2')), 'host', 'name'), 'maximum')"
    }
   ]
  },
  {
   "title": "RPS Status codes 3xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.3')), 'host', 'name'), 'maximum')"
    }
   ]
  },
  {
   "title": "RPS Status codes 4xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(perSecond(seriesByTag('contur=$contur', 'name=~webinar.streaming-origin.rps.4')), 'host', 'name'), 'maximum')"
    }
   ]
  },
  {
   "title": "RPS Status codes 5xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(perSecond(seriesByTag('contur=$contur','name=~webinar.streaming-origin.rps.5')), 'host', 'name'), 'maximum')"
    }
   ]
  },
  {
   "title": "RPS methods summary",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(groupByTags(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.(del|get|put)'), 'sum', 'host')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "RPS DEL method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.del')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "RPS GET method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.get')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "RPS PUT method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=${contur:regex}', 'name=~webinar.streaming-origin.rps.put')), 'host', 'name')"
    }
   ]
  },
  { "title": "Transcoders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Packets (missed)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=webinar.transcoding.stream.ffmpeg.packets.missed', 'contur=~${contur:regex}'), 'webinarUUID', 'streamId', 'cause', 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Packets (late)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=webinar.transcoding.stream.ffmpeg.packets.late', 'contur=~${contur:regex}'), 'webinarUUID', 'streamId', 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "farmes.dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "seriesByTag('name=webinar.transcoder.packets.frames.dropped')"
    }
   ]
  },
  {
   "title": "Recorder (traffic)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=webinar.transcoding.recorder.megabytes', 'contur=~${contur:regex}')), 'host')"
    },
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=webinar.transcoding.stream.recorder.megabytes', 'contur=~${contur:regex}')), 'webinarUUID', 'streamId', 'streamUUID')"
    }
   ]
  },
  {
   "title": "Recorder (restarts)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=webinar.transcoding.recorder.restarts', 'contur=~${contur:regex}')), 'host')"
    },
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=webinar.transcoding.stream.recorder.restarts', 'contur=~${contur:regex}')), 'webinarUUID', 'streamId', 'streamUUID')"
    }
   ]
  },
  {
   "title": "FFmpeg (failures)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByTags(seriesByTag('name=~webinar.transcoding.ffmpeg(.restarts|.failures)', 'contur=~${contur:regex}'), 'sum', 'host')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=webinar.transcoding.stream.ffmpeg.restarts', 'contur=~${contur:regex}'), 'webinarUUID', 'streamId', 'streamUUID'), '$', '.restarts')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=webinar.transcoding.stream.ffmpeg.failures', 'contur=~${contur:regex}'), 'webinarUUID', 'streamId', 'streamUUID'), '$', '.failures')"
    }
   ]
  },
  {
   "title": "FFmpeg (incoming RTP traffic)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~webinar.transcoding.stream.input.megabytes', 'contur=~${contur:regex}')), 'webinarUUID', 'streamId', 'host'), '.unix.tensor.ru', ' bytes')"
    },
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~webinar.transcoding.stream.input.packets', 'contur=~${contur:regex}')), 'webinarUUID', 'streamId', 'host'), '.unix.tensor.ru', ' packets')"
    }
   ]
  },
  {
   "title": "FFmpeg (chunk pace)",
   "type": "graph",
   "description": "Both jumps and backs should be 0.\nFluctuations should be +0",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~webinar.transcoding.stream.ffmpeg.chunks.(jumps|backs)', 'contur=~${contur:regex}')), 'webinarUUID', 'streamId', 'host', 'name'), '.unix.tensor.ru.webinar.transcoding.stream.ffmpeg.chunks.', ' ')"
    },
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~webinar.transcoding.stream.ffmpeg.chunks.fluctuations', 'contur=~${contur:regex}')), 'webinarUUID', 'streamId', 'host', 'name'), '.unix.tensor.ru.webinar.transcoding.stream.ffmpeg.chunks.', ' ')"
    }
   ]
  },
  {
   "title": "FFmpeg (chunkbeat)",
   "type": "graph",
   "description": "Unlike the human ones, these should look pretty much like straight lines",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~webinar.transcoding.stream.ffmpeg.chunks.count', 'contur=~${contur:regex}')), 'webinarUUID', 'streamId', 'host', 'name'), '.unix.tensor.ru.webinar.transcoding.stream.ffmpeg.chunks.', ' ')"
    }
   ]
  },
  {
   "title": "FFmpeg (uneven)",
   "type": "graph",
   "description": "MUST be +0\nBut, sometimes, audio and video streams get diverged which causes player issues.\n\nsum(chunkNo - min(chunkNo for all representations))",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~webinar.transcoding.stream.ffmpeg.chunks.uneven', 'contur=~${contur:regex}')), 'webinarUUID', 'streamId', 'host', 'name'), '.unix.tensor.ru.webinar.transcoding.stream.ffmpeg.chunks.', ' ')"
    }
   ]
  },
  {
   "title": "FFmpeg (representations)",
   "type": "graph",
   "description": "Almost each of them is an encoding video stream",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~webinar.transcoding.stream.ffmpeg.chunks.representations', 'contur=~${contur:regex}'), 'webinarUUID', 'streamId', 'host', 'name'), '.unix.tensor.ru.webinar.transcoding.stream.ffmpeg.chunks.', ' ')"
    }
   ]
  },
  { "title": "GPUs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-webinar-gpu\\d+.unix.tensor.ru', 'name=http_response.response_string_match'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "CPU busy per server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'contur=${contur:regex}', 'cpu=cpu-total', 'name=system.cpu.usage_active', 'host=~.*webinar.*'), 'host')"
    }
   ]
  },
  {
   "title": "Mem usage by servers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'contur=${contur:regex}', 'host=~.*webinar.*', 'name=system.mem.active'), 'host')"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'contur=${contur:regex}', 'host=~.*webinar.*', 'name=system.netstat.tcp_established'), 'host')"
    }
   ]
  },
  {
   "title": "Nvidia GPU utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('servertype=gpu', 'name=nvidia_smi.utilization_gpu', 'contur=${contur:regex}', 'host=~.*webinar.*'), 'sum', 'host'), 'host')"
    }
   ]
  },
  {
   "title": "Nvidia encoder utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('servertype=gpu', 'name=nvidia_smi.utilization_encoder', 'contur=${contur:regex}', 'host=~.*webinar.*'), 'sum', 'host'), 'host')"
    }
   ]
  },
  {
   "title": "Nvidia decoder utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('servertype=gpu', 'name=nvidia_smi.utilization_decoder', 'contur=${contur:regex}', 'host=~.*webinar.*'), 'sum', 'host'), 'host')"
    }
   ]
  },
  { "title": "БЛ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "CPU busy per server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu=cpu-total', 'contur=${contur:regex}', 'servertype=webinar'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Mem usage by servers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 88 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.mem.active', 'contur=${contur:regex}', 'servertype=webinar'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Connections by servers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.netstat.tcp_established', 'contur=${contur:regex}', 'servertype=webinar'), 'host'), 0)"
    }
   ]
  },
  { "title": "Repeaters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "CPU busy per server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.core.webinar-chunker-*.*.cpu.busy.max, 4)"
    }
   ]
  },
  {
   "title": "Mem usage by servers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 95 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.webinar-chunker-*.*.mem.ram.used.max, 4)"
    }
   ]
  },
  {
   "title": "Connections by servers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.netstat.webinar-chunker-*.*.net.total.connection.established.max, 4)"
    }
   ]
  },
  { "title": "Quality Votes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Not Voted",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=webinar.qualityVote_0', 'contur=~${contur:regex}'), 'webinarId')"
    }
   ]
  },
  {
   "title": "All right",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=webinar.qualityVote_1', 'contur=~${contur:regex}'), 'webinarId')"
    }
   ]
  },
  {
   "title": "Don't see",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=webinar.qualityVote_2', 'contur=~${contur:regex}'), 'webinarId')"
    }
   ]
  },
  {
   "title": "Don't hear",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=webinar.qualityVote_3', 'contur=~${contur:regex}'), 'webinarId')"
    }
   ]
  },
  {
   "title": "Shit happens",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=webinar.qualityVote_4', 'contur=~${contur:regex}'), 'webinarId')"
    }
   ]
  }
 ]
}