{
 "title": "SBIS Communication - message-service и message-service-demo",
 "description": "Реализация функций обмена сообщениями. Ответственный: Карпов С.В. (Эксплуатация), Мальцев И.С. (Разработка)",
 "tags": [
  "service",
  "telegraf",
  "sbis3mon"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "aggr", "label": "Аггрегация", "query": "max, avg, min" },
   {
    "name": "host",
    "label": "host",
    "query": "tag_values(host,host=~csr-msg.*,systemd_unit=~*)"
   },
   {
    "name": "systemd_unit",
    "query": "tag_values(systemd_unit,host=$host)"
   }
  ]
 },
 "panels": [
  { "title": "Процессы: $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Running",
   "type": "stat",
   "description": "Наличие процесса message-service и message-service-demo",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit\\.service', 'name=~.*$systemd_unit\\.running'), 'host', 'systemd_unit')"
    }
   ]
  },
  {
   "title": "Major faults",
   "type": "stat",
   "description": "Значительные отказы выделения памяти процессу",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.major_faults'))"
    }
   ]
  },
  {
   "title": "Minor faults",
   "type": "stat",
   "description": "Минорные отказы выделения памяти процессу",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.minor_faults'))"
    }
   ]
  },
  {
   "title": "Threads number",
   "type": "stat",
   "description": "Общее количество системных потоков",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.num_threads')"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "description": "CPU на БЛ сервиса",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(perSecond(aliasByTags(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.cpu_time.*'), 'name')), -1))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "MEM на БЛ сервиса",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(aliasByTags(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.memory.*'), 'name'), -1))"
    }
   ]
  },
  {
   "title": "Child major faults",
   "type": "stat",
   "description": "Отказы выделения памяти дочернему процессу",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.child_major_faults'))"
    }
   ]
  },
  {
   "title": "Child minor faults",
   "type": "stat",
   "description": "Отказы выделения памяти дочернему процессу",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.child_minor_faults'))"
    }
   ]
  },
  {
   "title": "PID count",
   "type": "stat",
   "description": "Количество PID",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.pid_count')"
    }
   ]
  },
  { "title": "Сервис сообщений", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Сервис сообщений  CPU",
   "type": "graph",
   "description": "Сервис сообщений ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.*.csr-msg-nodejs{1,2}.*.cpu.busy.$aggr, -5)"
    }
   ]
  },
  {
   "title": "Сервис сообщений LA",
   "type": "graph",
   "description": "Сервис сообщений",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.la.csr-msg-nodejs{1,2}.*.cpu.la.m01.$aggr, -6, -3, -2)"
    }
   ]
  },
  {
   "title": "Сервис сообщений RAM-used",
   "type": "graph",
   "description": "Сервис сообщений ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.memory.csr-msg-nodejs{1,2}.*.mem.ram.used.$aggr, -6, -2)"
    }
   ]
  },
  {
   "title": "Сервис сообщений RAM-free",
   "type": "graph",
   "description": "Сервис сообщений ",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.memory.csr-msg-nodejs{1,2}.*.mem.ram.free.$aggr, -6, -2)"
    }
   ]
  },
  {
   "title": "Объем раздела /opt/sbis ",
   "type": "graph",
   "description": "Сервис сообщений",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~csr-msg-nodejs[1-2]', 'path=-opt-sbis', 'name=system.disk.used'), 'host', 'path')"
    }
   ]
  },
  {
   "title": "Сервис сообщений - БД и шина событий",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Сервис сообщений - БД и шина событий CPU",
   "type": "graph",
   "description": "Сервис сообщений - БД и шина событий ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.*.csr-msg-bl{1,2}.*.cpu.busy.$aggr, -5)"
    }
   ]
  },
  {
   "title": "Сервис сообщений - БД и шина событий LA",
   "type": "graph",
   "description": "Сервис сообщений - БД и шина событий ",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.la.csr-msg-bl{1,2}.*.cpu.la.m01.$aggr, -6, -3, -2)"
    }
   ]
  },
  {
   "title": "Объем раздела /opt/sbis ",
   "type": "graph",
   "description": "Сервис сообщений - БД и шина событий ",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.prod.linux.partition.csr-msg-bl{1,2}.*.partition.volume._2Fopt_2Fsbis.used.raw, -7, -3), '_2F', '/')"
    }
   ]
  },
  {
   "title": "Сервис сообщений - БД и шина событий RAM-used",
   "type": "graph",
   "description": "Сервис сообщений - БД и шина событий ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.memory.csr-msg-bl{1,2}.*.mem.ram.used.$aggr, -6, -2)"
    }
   ]
  },
  {
   "title": "Сервис сообщений - БД и шина событий RAM-free",
   "type": "graph",
   "description": "Сервис сообщений - БД и шина событий ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.memory.csr-msg-bl{1,2}.*.mem.ram.free.$aggr, -6, -2)"
    }
   ]
  },
  { "title": "Демо Сервис сообщений", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Демо Сервис сообщений CPU",
   "type": "graph",
   "description": "Демо Сервис сообщений ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.*.csr-msg-demo-nodejs{1,2}.*.cpu.busy.$aggr, -5)"
    }
   ]
  },
  {
   "title": "Демо Сервис сообщений LA",
   "type": "graph",
   "description": "Демо Сервис сообщений ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.la.csr-msg-demo-nodejs{1,2}.*.cpu.la.m01.$aggr, -6, -3, -2)"
    }
   ]
  },
  {
   "title": "Основная очередь",
   "type": "table",
   "description": "Сервис сообщений - БД и шина событий",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=cloud.sbis.ru', 'name=queue.size', 'service=Сервис сообщений - БД и шина событий', 'host=~csr-msg-bl[1-2]', 'type=work'), 'host')"
    }
   ]
  },
  {
   "title": "Демо Сервис сообщений RAM-free",
   "type": "graph",
   "description": "Демо Сервис сообщений ",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 52 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.memory.csr-msg-demo-nodejs[1-2].*.mem.ram.free.$aggr, -6, -2)"
    }
   ]
  },
  {
   "title": "Демо Сервис сообщений RAM-used",
   "type": "graph",
   "description": "Демо Сервис сообщений ",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 52 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.memory.csr-msg-demo-nodejs{1,2}.*.mem.ram.used.$aggr, -6, -2)"
    }
   ]
  },
  {
   "title": "Служебная очередь",
   "type": "table",
   "description": "Сервис сообщений - БД и шина событий",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=cloud.sbis.ru', 'name=queue.size', 'service=Сервис сообщений - БД и шина событий', 'host=~csr-msg-bl[1-2]', 'type=special'), 'host')"
    }
   ]
  },
  {
   "title": "Демо Сервис сообщений - БД и шина событий",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Демо Сервис сообщений - БД и шина событий",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.*.csr-msg-demo-bl{1,2}.*.cpu.busy.$aggr, -5)"
    }
   ]
  },
  {
   "title": "LA",
   "type": "graph",
   "description": "Демо Сервис сообщений - БД и шина событий",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.la.csr-msg-demo-bl{1,2}.*.cpu.la.m01.$aggr, -6, -3, -2)"
    }
   ]
  },
  {
   "title": "Объем раздела /opt/sbis ",
   "type": "graph",
   "description": "Демо Сервис сообщений",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('path=-opt-sbis', 'host=~csr-msg-demo-nodejs[1-2]', 'name=system.disk.used'), 'host', 'path')"
    }
   ]
  },
  {
   "title": "Основная очередь",
   "type": "table",
   "description": "Демо Сервис сообщений - БД и шина событий",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=cloud.sbis.ru', 'name=queue.size', 'host=~csr-msg-demo-bl[1-2]', 'type=work', 'service=Демо Сервис сообщений - БД и шина событий'), 'host')"
    }
   ]
  },
  {
   "title": "RAM-used",
   "type": "graph",
   "description": "Демо Сервис сообщений - БД и шина событий",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.memory.csr-msg-demo-bl{1,2}.*.mem.ram.used.$aggr, -6, -2)"
    }
   ]
  },
  {
   "title": "RAM-free",
   "type": "graph",
   "description": "Демо Сервис сообщений - БД и шина событий",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.memory.csr-msg-demo-bl{1,2}.*.mem.ram.free.$aggr, -6, -2)"
    }
   ]
  },
  {
   "title": "Объем раздела /opt/sbis ",
   "type": "graph",
   "description": "Демо Сервис сообщений - БД и шина событий",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.prod.linux.partition.csr-msg-demo-bl{1,2}.*.partition.volume._2Fopt_2Fsbis.used.raw, -7, -3), '_2F', '/')"
    }
   ]
  },
  {
   "title": "БД csr-message-db1.unix.tensor.ru",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 }
  },
  {
   "title": "Служебная очередь",
   "type": "table",
   "description": "Демо Сервис сообщений - БД и шина событий",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=cloud.sbis.ru', 'name=queue.size', 'service=Демо Сервис сообщений - БД и шина событий', 'host=~csr-msg-demo-bl[1-2]', 'type=special'), 'host')"
    }
   ]
  },
  {
   "title": "Ping: csr-message-db1",
   "type": "graph",
   "description": "БД csr-message-db1.unix.tensor.ru",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 80 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.postgres.service-ping.csr-message-db1.pgsql.*.pgsql.ping.postgres, -6, -2)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "БД csr-message-db1.unix.tensor.ru",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.*.csr-message-db1.*.cpu.busy.$aggr, -5)"
    }
   ]
  },
  {
   "title": " LA",
   "type": "graph",
   "description": "БД csr-message-db1.unix.tensor.ru",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.la.csr-message-db1.*.cpu.la.m01.$aggr, -6, -3, -2)"
    }
   ]
  },
  {
   "title": "Объем раздела /var/lib/pgsql/9.6/data",
   "type": "graph",
   "description": "БД csr-message-db1.unix.tensor.ru",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(sbis3mon.prod.linux.partition.csr-message-db1.*.partition.volume._2Fvar_2Flib_2Fpgsql_2F9.6_2Fdata.used.raw, -8, -4, -3), '_2F', '/')"
    }
   ]
  },
  {
   "title": "RAM  used/free",
   "type": "graph",
   "description": "БД csr-message-db1.unix.tensor.ru",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.linux.memory.csr-message-db1.*.mem.ram.used.$aggr, -6, -2)"
    },
    {
     "target": "aliasByTags(sbis3mon.prod.linux.memory.csr-message-db1.*.mem.ram.free.$aggr, -6, -2)"
    }
   ]
  }
 ]
}