{
 "title": "SBIS Communication - Вебинары: Overview",
 "description": "Ответственный: Никитин М.С. (Эксплуатация)",
 "tags": [
  "scripts",
  "service",
  "webinar"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "contur", "label": "контур", "query": "prod" }
  ]
 },
 "panels": [
  {
   "title": "Пользователей online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(sumSeries(currentAbove(seriesByTag('name=webinar.usersAmountOnline', 'contur=~${contur:regex}'), 1)), 'webinarId')"
    }
   ]
  },
  {
   "title": "Вебинаров",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(aggregate(consolidateBy(seriesByTag('name=webinar.wscount', 'contur=~${contur:regex}'), 'maximum'), 'count'), 'count')"
    }
   ]
  },
  {
   "title": "Статус",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=status_webinar_OK', 'contur=${contur:regex}')"
    }
   ]
  },
  {
   "title": "Origins status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~csr-webinar-origin-bl\\d.unix.tensor.ru', 'name=http_response.response_string_match', 'contur=$contur'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Количество вебинаров & users total amount online",
   "type": "graph",
   "description": "статистика во времени, сколько проходило вебинаров и общее количество пользователей онлайн",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(currentAbove(seriesByTag('name=webinar.usersAmountOnline', 'contur=~${contur:regex}'), 1)), 'Viewers')"
    },
    {
     "target": "alias(transformNull(sumSeries(groupByTags(currentAbove(seriesByTag('name=webinar.usersAmountOnline', 'contur=~${contur:regex}'), 0), 'count', 'webinarId')), 0), 'WS')"
    }
   ]
  },
  {
   "title": "Вебинары за период",
   "type": "table",
   "gridPos": { "h": 15, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=webinar.usersAmountOnline', 'contur=${contur:regex}', 'interval=3s'), 'webinarId')"
    }
   ]
  },
  {
   "title": "Peers total amount online",
   "type": "graph",
   "description": "Количество открытых вкладок с вебинаром в данный момент времени",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=webinar.viewersAmount', 'contur=~${contur:regex}', 'interval=3s'), 'webinarId')"
    }
   ]
  },
  {
   "title": "Users total amount online",
   "type": "graph",
   "description": "Количество уникальных пользователей присутствующих на вебинаре в данный момент",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=webinar.usersAmountOnline', 'contur=${contur:regex}', 'interval=3s'), 'webinarId')"
    }
   ]
  },
  {
   "title": "Users cumulative total",
   "type": "graph",
   "description": "Количество уникальных пользователей посетивших вебинар",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=webinar.usersAmount', 'contur=~${contur:regex}'), 'webinarId')"
    }
   ]
  }
 ]
}