{
 "title": "Биллинг - reg.tensor.ru",
 "description": "Ответственный: Никитин М.С. (Эксплуатация)",
 "tags": [
  "reg",
  "billing",
  "service",
  "sbis3mon-kafka"
 ],
 "time": { "from": "2021-11-16T23:03:47.128Z", "to": "2021-11-17T11:03:47.128Z" },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.prod.linux.la.reg-db3.*.cpu.la.m{01,05}.max, 8), '(m)0?(\\d+)', 'LA $2 мин')"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.core.reg-db3.interval-28sec.cpu.busy.{max,avg}, -3,-1)"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.reg-db3.*.storage.io.bps.sdc.*.max, -3, -2)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "scale(time('', 1), 1000)" }
   ]
  },
  {
   "title": "reg-db3: LA",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.prod.linux.la.reg-db3.*.cpu.la.*.max, 8), '(m)0?(\\d+)', '$2 мин')"
    }
   ]
  },
  {
   "title": "reg-db3: Проц",
   "type": "graph",
   "description": "Загрузка ЦПУ",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.core.reg-db3.interval-28sec.cpu.busy.{max,avg}, -1)"
    }
   ]
  },
  {
   "title": "reg-db3: Диск",
   "type": "graph",
   "description": "Скорость доступа к данным на разделе БД",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "sbis3mon.prod.linux.storage.reg-db3.*.storage.io.bps.sdc.*.max"
    }
   ]
  },
  {
   "title": "Ошибки в логах",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=errors', 'subsystem=cloud.sbis.ru', 'source=cloud', 'service=~.*Биллинг'), 'service'), 'Биллинг', '')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=errors', 'subsystem=cloud.sbis.ru', 'source=cloud', 'service=~.*лицензирования'), 'service')"
    }
   ]
  },
  {
   "title": "csr-licenses-db1: LA",
   "type": "graph",
   "description": "Очередь процессорного времени на БД сервиса лицензий",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.prod.linux.la.csr-licenses-db1.*.cpu.la.*.max, 8), '(m)0?(\\d+)', '\\2 мин')"
    }
   ]
  },
  {
   "title": "csr-billing-bl (Регистрация)",
   "type": "graph",
   "description": "Загрузка CPU по отдельным узлам сервиса регистрации",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(sbis3mon.prod.linux.core.{csr-billing-bl*}.interval-28sec.cpu.busy.{max,avg}, -1, 4))"
    },
    {
     "target": "sbis3mon.prod.linux.la.csr-billing-bl*.interval-28sec.cpu.la.m01.max"
    }
   ]
  },
  {
   "title": "reg-bl (Основной сервис )",
   "type": "graph",
   "description": "Загрузка CPU по отдельным узлам основного сервиса",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(sbis3mon.prod.linux.core.csr-billing-main-bl*.interval-28sec.cpu.busy.{max,avg}, 4, -1))"
    },
    {
     "target": "sbis3mon.prod.linux.la.csr-billing-main-bl*.interval-28sec.cpu.la.m01.max"
    }
   ]
  },
  {
   "title": "Очереди",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=queue.size', 'subsystem=cloud.sbis.ru', 'host!=~.+', 'service=~.*Биллинг', 'type=work'), 'service'), 'Биллинг', ''), 'сервис', '')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=cloud.sbis.ru', 'host!=~.+', 'service=~.*лицензирования', 'type=work'), 'service')"
    },
    {
     "target": "aliasSub(aliasSub(aliasSub(aliasByTags(seriesByTag('name=async.queue.size', 'subsystem=cloud.sbis.ru', 'service=~.*Биллинг'), 'name', 'service'), 'Биллинг', ''), 'async.queue.size.', '[A] '), 'сервис', '')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=async.queue.size', 'subsystem=cloud.sbis.ru', 'service=~.*лицензирования'), 'name', 'service'), 'async.queue.size.', '')"
    }
   ]
  },
  {
   "title": "csr-licenses-db1: Проц",
   "type": "graph",
   "description": "Использование процессора на БД сервиса лицензий",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.core.csr-licenses-db1.interval-28sec.cpu.busy.{max,avg}, -1)"
    }
   ]
  },
  {
   "title": "Очереди на синхронизацию",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=rtr'), 'humanname')"
    }
   ]
  },
  {
   "title": "csr-reg-bl (Прочие сервисы)",
   "type": "graph",
   "description": "Использование процессора на серверах БЛ остальных сервисов приложения reg.tensor.ru",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(sbis3mon.prod.linux.core.csr-reg-bl*.interval-28sec.cpu.busy.{max,avg}, 4, -1))"
    },
    {
     "target": "sbis3mon.prod.linux.la.csr-reg-bl*.interval-28sec.cpu.la.m01.max"
    }
   ]
  },
  {
   "title": "csr-licenses-bl (Лицензирование)",
   "type": "graph",
   "description": "Кеширующий сервис лицензирования",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(sbis3mon.prod.linux.core.{csr-licenses-bl*}.interval-28sec.cpu.busy.{max,avg}, -1, 4))"
    },
    {
     "target": "sbis3mon.prod.linux.la.csr-licenses-bl*.interval-28sec.cpu.la.m01.max"
    }
   ]
  },
  {
   "title": "csr-licenses-db1: Диск",
   "type": "graph",
   "description": "Использование диска на БД сервиса лицензий",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.csr-licenses-db1.*.storage.io.bps.sdb.*.max, -3, -2)"
    }
   ]
  }
 ]
}