{
 "title": "Визуализация документов - Webapps",
 "description": "Ответственный: Баулин С.А. (Эксплуатация)",
 "tags": [
  "service",
  "webapps",
  "telegraf"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Использование CPU",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=win_cpu.Percent_Processor_Time', 'instance=_Total', 'servertype=webapps'), 'host')"
    }
   ]
  },
  {
   "title": "Доступная память (MBytes)",
   "type": "graph",
   "description": "Доступная память",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=win_mem.Available_Bytes', 'servertype=webapps'), 'host')"
    }
   ]
  },
  {
   "title": "Сеть (Пакетов/секунду - Всего)",
   "type": "graph",
   "description": "Количество получаемых пакетов в секунду",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=Network_Interface.Packets_Received_persec', 'instance=Сетевой_адаптер_Hyper-V__Майкрософт_', 'servertype=webapps'), 'host')"
    }
   ]
  },
  {
   "title": "IOPS (Read/Write)",
   "type": "graph",
   "description": "Количество операций ввода/вывода в секунду",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~win_diskio.Disk_(Read|Write)s_persec', 'servertype=webapps'), 'host', 'name'), 'win_diskio.Disk_', '')"
    }
   ]
  },
  {
   "title": "IO (Read/Write) ",
   "type": "graph",
   "description": "Чтение/запись в байтах в секунду",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~win_diskio.Disk_(Read|Write)_Bytes_persec', 'servertype=webapps'), 'host', 'name'), 'win_diskio.Disk_', '')"
    }
   ]
  },
  {
   "title": "Office Online - Storage : Wac Disk Cache Put/Read Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=~Office_Online_Storage.WacDiskCache(Put|Read)Rate$', 'servertype=webapps'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  { "title": "Web frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "WEB Fronted Post requests/sec",
   "type": "graph",
   "description": "Количество Post запросов в секунду",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=web.Post_Requests_persec', 'servertype=webapps'), 'host')"
    }
   ]
  },
  {
   "title": "WEB Fronted Current Connections",
   "type": "graph",
   "description": "Количество текущих подключений",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=web.Current_Connections', 'servertype=webapps'), 'host')"
    }
   ]
  },
  {
   "title": "ASP.NET Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "ASP.NET запросов в секунду",
     "type": "graph",
     "description": "Кол-во запросов в секунду",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=ASP.NET_NEW.Requests_persec', 'servertype=webapps'), 'host')"
      }
     ]
    },
    {
     "title": "ASP.NET время выполнения запроса",
     "type": "graph",
     "description": "Время выполнения запроса",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=ASP.NET_NEW.Request_Execution_Time', 'servertype=webapps'), 'host')"
      }
     ]
    },
    {
     "title": "ASP.NET Текущие запросы(Выполняются, В очереди, Ожидают записи)",
     "type": "graph",
     "description": "Текущее выполнение запросов",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=ASP.NET_NEW.Requests_Executing', 'servertype=webapps'), 'host')"
      }
     ]
    }
   ]
  },
  {
   "title": "Excel statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Excel Service (Web Front End) запросов в секунду",
     "type": "graph",
     "description": "Кол-во запросов в секунду",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=Excel_web_Front_End.EsProxyRequestsPerSecond', 'servertype=webapps'), 'host')"
      }
     ]
    },
    {
     "title": "Excel Service (Web Front End) время выполнения запроса",
     "type": "graph",
     "description": "Время выполнения запроса",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=Excel_web_Front_End.EsProxyAverageRequestTime', 'servertype=webapps'), 'host')"
      }
     ]
    },
    {
     "title": "Excel Service (Web Front End) Количество активных запросов",
     "type": "graph",
     "description": "Количество активных запросов",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=Excel_web_Front_End.EsProxyActiveRequests', 'servertype=webapps'), 'host')"
      }
     ]
    },
    {
     "title": "Excel Service (ASP.NET) запросов в секунду",
     "type": "graph",
     "description": "Кол-во запросов в секунду",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "port (-) 809 / (+) 80" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Requests_persec', 'instance=~_LM_W3SVC_(2_ROOT_x|1_ROOT_ecs)', 'servertype=webapps'), 'host', 'instance'), '_LM_W3SVC_2_ROOT_x', '80'), '_LM_W3SVC_1_ROOT_ecs', '809')"
      }
     ]
    },
    {
     "title": "Excel Service (ASP.NET) время выполнения запроса",
     "type": "graph",
     "description": "Время выполнения запроса",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "ms", "label": "port (-) 809 / (+) 80" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Request_Execution_Time', 'instance=~_LM_W3SVC_(2_ROOT_x|1_ROOT_ecs)', 'servertype=webapps'), 'host', 'instance'), '_LM_W3SVC_2_ROOT_x', '80'), '_LM_W3SVC_1_ROOT_ecs', '809')"
      }
     ]
    },
    {
     "title": "Excel Service (ASP.NET) - очередь",
     "type": "graph",
     "description": "Запросы в очереди приложений",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "port (-) 809 / (+) 80" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Requests_In_Application_Queue', 'instance=~_LM_W3SVC_(2_ROOT_x|1_ROOT_ecs)', 'servertype=webapps'), 'host', 'instance'), '_LM_W3SVC_2_ROOT_x', '80'), '_LM_W3SVC_1_ROOT_ecs', '809')"
      }
     ]
    }
   ]
  },
  {
   "title": "PowerPoint statisics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power Point Viewer (ASP.NET - 80 Port) запросов в секунду",
     "type": "graph",
     "description": "Кол-во запросов в секунд",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Requests_persec', 'instance=_LM_W3SVC_2_ROOT_p', 'servertype=webapps'), 'host')"
      }
     ]
    },
    {
     "title": "Power Point Viewer (ASP.NET - 80 Port) время выполнения запроса",
     "type": "graph",
     "description": "Время выполнения запроса",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Request_Execution_Time', 'instance=_LM_W3SVC_2_ROOT_p', 'servertype=webapps'), 'host')"
      }
     ]
    },
    {
     "title": "Power Point Viewer (ASP.NET - 80 Port) - очередь",
     "type": "graph",
     "description": "Запросы в очереди приложений",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Requests_In_Application_Queue', 'instance=_LM_W3SVC_2_ROOT_p', 'servertype=webapps'), 'host')"
      }
     ]
    },
    {
     "title": "PowerPoint (ASP.NET - 809 port) - запросов в секунду",
     "type": "graph",
     "description": "Кол-во запросов в секунд",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "(-) edit / (+) conversation" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Requests_persec', 'instance=~_LM_W3SVC_1_ROOT_ppt(c|e)', 'servertype=webapps'), 'host', 'instance'), '_LM_W3SVC_1_ROOT_pptc', 'conversation'), '_LM_W3SVC_1_ROOT_ppte', 'edit')"
      }
     ]
    },
    {
     "title": "PowerPoint (ASP.NET - 809 port) - время выполнения запроса",
     "type": "graph",
     "description": "Время выполнения запроса",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "ms", "label": "(-) edit / (+) conversation" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Request_Execution_Time', 'instance=~_LM_W3SVC_1_ROOT_ppt(c|e)', 'servertype=webapps'), 'host', 'instance'), '_LM_W3SVC_1_ROOT_pptc', 'conversation'), '_LM_W3SVC_1_ROOT_ppte', 'edit')"
      }
     ]
    },
    {
     "title": "PowerPoint (ASP.NET - 809 port) - очередь",
     "type": "graph",
     "description": "Запросы в очереди приложений",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "(-) edit / (+) conversation" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Requests_In_Application_Queue', 'instance=~_LM_W3SVC_1_ROOT_ppt(c|e)', 'servertype=webapps'), 'host', 'instance'), '_LM_W3SVC_1_ROOT_pptc', 'conversation'), '_LM_W3SVC_1_ROOT_ppte', 'edit')"
      }
     ]
    }
   ]
  },
  {
   "title": "Word Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Word (ASP.NET - 80 port) - запросов в секунду",
     "type": "graph",
     "description": "Кол-во запросов в секунд",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "(-) edit / (+) view" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Requests_persec', 'instance=~_LM_W3SVC_2_ROOT_w(v|e)', 'servertype=webapps'), 'host', 'instance'), '_LM_W3SVC_2_ROOT_wv', 'view'), '_LM_W3SVC_2_ROOT_we', 'edit')"
      }
     ]
    },
    {
     "title": "Word (ASP.NET - 80 port) - время выполнения запроса",
     "type": "graph",
     "description": "Время выполнения запроса",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "ms", "label": "(-) edit / (+) view" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Request_Execution_Time', 'instance=~_LM_W3SVC_2_ROOT_w(v|e)', 'servertype=webapps'), 'host', 'instance'), '_LM_W3SVC_2_ROOT_wv', 'view'), '_LM_W3SVC_2_ROOT_we', 'edit')"
      }
     ]
    },
    {
     "title": "Word (ASP.NET - 80 port) - очередь",
     "type": "graph",
     "description": "Запросы в очереди приложений",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "none", "label": "(-) edit / (+) view" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Requests_In_Application_Queue', 'instance=~_LM_W3SVC_2_ROOT_w(v|e)', 'servertype=webapps'), 'host', 'instance'), '_LM_W3SVC_2_ROOT_wv', 'view'), '_LM_W3SVC_2_ROOT_we', 'edit')"
      }
     ]
    },
    {
     "title": "Word (ASP.NET - 809 port) - запросов в секунду",
     "type": "graph",
     "description": "Кол-во запросов в секунд",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "(-) save / (+) session" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Requests_persec', 'instance=~_LM_W3SVC_1_ROOT_w(d|e)ss', 'servertype=webapps'), 'host', 'instance'), '_LM_W3SVC_1_ROOT_wdss', 'session'), '_LM_W3SVC_1_ROOT_wess', 'save')"
      }
     ]
    },
    {
     "title": "Word (ASP.NET - 809 port) - время выполнения запроса",
     "type": "graph",
     "description": "Время выполнения запроса",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "ms", "label": "(-) save / (+) session" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Request_Execution_Time', 'instance=~_LM_W3SVC_1_ROOT_w(d|e)ss', 'servertype=webapps'), 'host', 'instance'), '_LM_W3SVC_1_ROOT_wdss', 'session'), '_LM_W3SVC_1_ROOT_wess', 'save')"
      }
     ]
    },
    {
     "title": "Word (ASP.NET - 809 port) - очередь",
     "type": "graph",
     "description": "Запросы в очереди приложений",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "(-) save / (+) session" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=Office_Online_ASP.NET_Metrics.Requests_In_Application_Queue', 'instance=~_LM_W3SVC_1_ROOT_w(d|e)ss', 'servertype=webapps'), 'host', 'instance'), '_LM_W3SVC_1_ROOT_wdss', 'session'), '_LM_W3SVC_1_ROOT_wess', 'save')"
      }
     ]
    },
    {
     "title": "Word Online Viewing - Очереди Запросов Рендеринга",
     "type": "graph",
     "description": "\nПоказывает количество запросов на отрисовку, поставленных в очередь до тех пор, пока сервер приложений не сможет обслужить запрос.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=Word_Online_viewing.ConversionQueuedRequests', 'servertype=webapps'), 'host')"
      }
     ]
    },
    {
     "title": "Word Online Viewing - Время загрузки документов на сервер приложения.",
     "type": "graph",
     "description": "\nПоказывает продолжительность загрузки документов на сервер приложений из хранилища SQL Server, прежде чем они будут обработаны веб-приложением.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=Word_Online_viewing.ConversionRequestDownloadTime', 'servertype=webapps'), 'host')"
      }
     ]
    }
   ]
  }
 ]
}