{
 "title": "Видеонаблюдение - System_screen",
 "description": "Ответственный: Конюхов М.В. (Эксплуатация)",
 "tags": [
  "exploitation",
  "mv.konuhov",
  "service",
  "scripts",
  "видеонаблюдение",
  "onvif",
  "videostreaming",
  "videoregistration"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.sbis3app.info.*"
   },
   {
    "name": "port",
    "label": "Порт",
    "query": "sbis3mon.$contur.sbis3app.status.$server.sbis3.*"
   },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  {
   "title": "Videoregistration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Очереди videoregistration",
     "type": "graph",
     "description": "Очереди БЛ сервиса videoregistration",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('name=queue.size', 'service=~.*ideoregistration.*', 'host!=~.+', 'type=work'), 'service', 'type'), 'work', 'основная')"
      },
      {
       "target": "aliasSub(aliasByTags(seriesByTag('name=queue.size', 'service=~.*ideoregistration.*', 'host!=~.+', 'type=special'), 'service', 'type'), 'special', 'служебная')"
      }
     ]
    },
    {
     "title": "Использование воркеров /videoregistration/service/",
     "type": "graph",
     "description": "Использование воркеров /videoregistration/service/",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percent", "label": "max 100%" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info.*.sbis3.$port.*.sbis3.service.workers.used._2Fvideoregistration_2Fservice_2F.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
      },
      {
       "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info_srv.*.sbis3.$port.*.sbis3.service.workers.used._2Fvideoregistration_2Fservice_2F_5Fsrv.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
      }
     ]
    },
    {
     "title": "csr-videoregistration-db1 разделы",
     "type": "graph",
     "description": "Процент занятых дисковых разделов",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.partition.csr-videoregistration-db1.*.partition.volume.*.used.raw, 4, 7, 8), '_2F', '/')"
      }
     ]
    }
   ]
  },
  {
   "title": "Onvif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Статистика csr-vts-onvif1-platforma1 onvif.service_check.load",
     "type": "graph",
     "description": "onvif.service_check.load\nсобирается скриптом /?load ",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'script=onvif_service_check.py', 'metric_name!=~(NumberOfProcessedRequests|NumberOfErrors)', 'host=csr-vts-onvif1-platforma1.unix.tensor.ru', 'name=onvif.service_check.load'), 'metric_name', 'host', 'port')"
      },
      {
       "target": "aliasByTags(perSecond(seriesByTag('contur=prod', 'script=onvif_service_check.py', 'metric_name=~(NumberOfProcessedRequests|NumberOfErrors)', 'host=csr-vts-onvif1-platforma1.unix.tensor.ru', 'name=onvif.service_check.load')), 'metric_name', 'host', 'port')"
      }
     ]
    },
    {
     "title": "Работоспособность mqtt onvif.service_check.mqtt",
     "type": "graph",
     "description": "onvif.service_check.mqtt\n1 - работает\n0 - недоступен\n-1 - нет данных",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'script=onvif_service_check.py', 'name=onvif.service_check.mqtt'), 'host', 'port')"
      }
     ]
    },
    {
     "title": "Статус контейнера tensor_onvif_agent",
     "type": "graph",
     "description": "onvif.service_check.redis\nключ редис onvif:agent:alive",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'script=onvif_service_check.py', 'name=onvif.service_check.redis', 'key=onvif:agent:alive'), 'host')"
      }
     ]
    },
    {
     "title": "Статус контейнера tensor_onvif_subscriber",
     "type": "graph",
     "description": "onvif.service_check.redis\nключ редис onvif:subscriber:alive",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'script=onvif_service_check.py', 'name=onvif.service_check.redis', 'key=onvif:subscriber:alive'), 'host')"
      }
     ]
    },
    {
     "title": "Статус контейнера tensor_onvif_listener",
     "type": "graph",
     "description": "onvif.service_check.redis\nключ редис onvif:listener:alive",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'script=onvif_service_check.py', 'name=onvif.service_check.redis', 'key=onvif:listener:alive'), 'host')"
      }
     ]
    },
    {
     "title": "Статистика подключенных по onvif",
     "type": "graph",
     "description": "onvif.service_check.redis\nключ редиса\ncameras:onvif:success - количество подключенных по onvif\ncameras:onvif:failed - количество не подключенных cameras:onvif:total - всего для подключения (прошло валидацию конфига)",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'script=onvif_service_check.py', 'name=onvif.service_check.redis', 'key=cameras:onvif:success'), 'host', 'key')"
      },
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'script=onvif_service_check.py', 'name=onvif.service_check.redis', 'key=cameras:onvif:total'), 'host', 'key')"
      },
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'script=onvif_service_check.py', 'name=onvif.service_check.redis', 'key=cameras:onvif:failed'), 'host', 'key')"
      }
     ]
    },
    {
     "title": "Статистика подключенных камер",
     "type": "graph",
     "description": "onvif.service_check.redis\nключ редиса\ncameras:online - количество онлайн камер (у которых статус положительный)\ncameras:offline - количество оффлайн (которые не але по пингу) cameras:total - общее число камер из конфига",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'script=onvif_service_check.py', 'name=onvif.service_check.redis', 'key=cameras:online'), 'host', 'key')"
      },
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'script=onvif_service_check.py', 'name=onvif.service_check.redis', 'key=cameras:offline'), 'host', 'key')"
      },
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'script=onvif_service_check.py', 'name=onvif.service_check.redis', 'key=cameras:total'), 'host', 'key')"
      }
     ]
    },
    {
     "title": "Redis CPU и memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sbis3mon.$contur.linux.core.csr-vts-onvif1-platforma1*.*.cpu.busy.$aggr, 4, 6, 7)"
      },
      {
       "target": "aliasByNode(asPercent(sbis3mon.$contur.redis.info.csr-vts-onvif1-platforma*.redis.*.*.redis.system.memory.usage.used.$aggr, 2147483648), 4, 9, 11)"
      }
     ]
    },
    {
     "title": "Redis connections и db commands",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(keepLastValue(sbis3mon.prod.redis.info.csr-vts-onvif1-platforma*.redis.*.*.redis.db.clients.connected.$aggr, 1), 4, -2)"
      },
      {
       "target": "aliasByNode(keepLastValue(sbis3mon.prod.redis.info.csr-vts-onvif1-platforma*.redis.*.*.redis.db.stat.commandsprocessed.$aggr, 1), 4, -2)"
      }
     ]
    }
   ]
  },
  {
   "title": "Flussonic mediaserver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage ea1-vts-mediaserver1",
     "type": "graph",
     "description": "Использование CPU",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu!=cpu-total', 'servertype=videostreaming', 'host=ea1-vts-mediaserver1.unix.tensor.ru'), 'cpu')"
      }
     ]
    },
    {
     "title": "CPU usage ea1-vts-mediaserver2",
     "type": "graph",
     "description": "Использование CPU",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu!=cpu-total', 'servertype=videostreaming', 'host=ea1-vts-mediaserver2.unix.tensor.ru'), 'cpu')"
      }
     ]
    },
    {
     "title": "CPU usage ea1-vts-mediaserver3",
     "type": "graph",
     "description": "Использование CPU",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu!=cpu-total', 'servertype=videostreaming', 'host=ea1-vts-mediaserver3.unix.tensor.ru'), 'cpu')"
      }
     ]
    },
    {
     "title": "Flussonic Traffic OUT Summary",
     "type": "graph",
     "description": "Скрипт sbis_flussonic_traffic показывает сколько с нас качают",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('name=flussonic_traffic', 'servertype=videostreaming', 'contur=prod')), 'host')"
      }
     ]
    },
    {
     "title": "Flussonic Clients and Cameras Summary",
     "type": "graph",
     "description": "Скрипт sbis_flussonic_clients\nобщее количество подключенных клиентов\n\noid = 1.3.6.1.4.1.36342.1.1.1.0 - общее количество подключенных камер",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=flussonic_clients', 'servertype=videostreaming', 'contur=prod'), 'host', 'name')"
      },
      {
       "target": "aliasByTags(seriesByTag('name=flussonic_snmp.total_cameras_connected', 'servertype=videostreaming', 'contur=prod'), 'host', 'name')"
      },
      {
       "target": "alias(aggregate(seriesByTag('name=flussonic_snmp.total_cameras_connected', 'servertype=videostreaming', 'contur=prod'), 'sum'), 'Total cameras')"
      }
     ]
    },
    {
     "title": "CPU usage ea1-vts-watcher1",
     "type": "graph",
     "description": "Использование CPU",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu!=cpu-total', 'servertype=videostreaming', 'host=ea1-vts-watcher1.unix.tensor.ru'), 'cpu')"
      }
     ]
    },
    {
     "title": "Flussonic Clients connected by camera MAX TOP 10",
     "type": "graph",
     "description": "oid = \"1.3.6.1.4.1.36342.1.1.2.1.3\"",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "highestMax(aliasByTags(seriesByTag('name=flussonic_snmp.camera_clients_count', 'contur=prod'), 'host', 'camera_name'), 10)"
      }
     ]
    },
    {
     "title": "Flussonic Camera statuses (20 с проблемами)",
     "type": "graph",
     "description": "oid = \"1.3.6.1.4.1.36342.1.1.2.1.9\"\nactive = 1\nnotInService = 2\nnotReady = 3",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "maximumAbove(highestMax(aliasByTags(seriesByTag('name=flussonic_snmp.camera_status', 'interval=60s', 'contur=prod'), 'host', 'camera_name'), 20), 1)"
      }
     ]
    },
    {
     "title": "Flussonic License errors",
     "type": "graph",
     "description": "Скрипт sbis_flussonic_log\nанализирует ошибки лицензии в логах",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=flussonic_log', 'servertype=videostreaming', 'contur=prod'), 'host')"
      }
     ]
    },
    {
     "title": "Flussonic Camera bitrate MAX TOP 10",
     "type": "graph",
     "description": "oid = \"1.3.6.1.4.1.36342.1.1.2.1.6\"",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "target": "highestMax(aliasByTags(seriesByTag('name=flussonic_snmp.camera_bitrate', 'interval=60s', 'contur=prod'), 'host', 'camera_name'), 10)"
      }
     ]
    },
    {
     "title": "Flussonic Traffic IN by camera MAX TOP 10",
     "type": "graph",
     "description": "oid = \"1.3.6.1.4.1.36342.1.1.2.1.7\"",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "highestMax(aliasByTags(perSecond(seriesByTag('name=flussonic_snmp.camera_traffic_in', 'interval=60s', 'contur=prod')), 'host', 'camera_name'), 10)"
      }
     ]
    },
    {
     "title": "Flussonic HTTP response",
     "type": "graph",
     "description": "net_response 80й порт\nдоступность самого сервиса flussonic\n0 = нет данных, проблема доступа",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "target": "aliasByTags(transformNull(seriesByTag('name=flussonic_web.response_time', 'servertype=videostreaming', 'contur=prod'), 0), 'host')"
      }
     ]
    },
    {
     "title": "Flussonic занятость дисков",
     "type": "graph",
     "description": "Flussonic занятость дисков",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=system.disk.used_percent', 'contur=prod', 'servertype=videostreaming', 'host=~.*media.*'), 'host', 'path')"
      }
     ]
    },
    {
     "title": "Flussonic Traffic OUT by camera MAX TOP 10",
     "type": "graph",
     "description": "oid = \"1.3.6.1.4.1.36342.1.1.2.1.8\"",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "highestMax(aliasByTags(perSecond(seriesByTag('name=flussonic_snmp.camera_traffic_out', 'interval=60s', 'contur=prod')), 'host', 'camera_name'), 10)"
      }
     ]
    },
    {
     "title": "Flussonic Диски i/o",
     "type": "graph",
     "description": "system.diskio.io_time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByTags(perSecond(scale(seriesByTag('name=system.diskio.io_time', 'contur=prod', 'servertype=videostreaming', 'host=~.*media.*'), 0.1)), 'host', '_name')"
      }
     ]
    },
    {
     "title": "Flussonic Диски iops",
     "type": "graph",
     "description": "system.diskio.iops_in_progress",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=system.diskio.iops_in_progress', 'contur=prod', 'servertype=videostreaming', 'host=~.*media.*'), 'host', '_name')"
      }
     ]
    },
    {
     "title": "Flussonic LA ea1-vts-mediaserver1",
     "type": "graph",
     "description": "Flussonic LA ea1-vts-mediaserver1",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('name=system.system.n_cpus', 'servertype=videostreaming', 'host=ea1-vts-mediaserver1.unix.tensor.ru'), 'CPU Count')"
      },
      {
       "target": "alias(seriesByTag('name=system.system.load1', 'servertype=videostreaming', 'host=ea1-vts-mediaserver1.unix.tensor.ru'), 'LA1')"
      },
      {
       "target": "alias(seriesByTag('name=system.system.load5', 'servertype=videostreaming', 'host=ea1-vts-mediaserver1.unix.tensor.ru'), 'LA5')"
      },
      {
       "target": "alias(seriesByTag('name=system.system.load15', 'servertype=videostreaming', 'host=ea1-vts-mediaserver1.unix.tensor.ru'), 'LA15')"
      }
     ]
    },
    {
     "title": "Flussonic LA ea1-vts-mediaserver2",
     "type": "graph",
     "description": "Flussonic LA ea1-vts-mediaserver2",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('name=system.system.n_cpus', 'servertype=videostreaming', 'host=ea1-vts-mediaserver2.unix.tensor.ru'), 'CPU Count')"
      },
      {
       "target": "alias(seriesByTag('name=system.system.load1', 'servertype=videostreaming', 'host=ea1-vts-mediaserver2.unix.tensor.ru'), 'LA1')"
      },
      {
       "target": "alias(seriesByTag('name=system.system.load5', 'servertype=videostreaming', 'host=ea1-vts-mediaserver2.unix.tensor.ru'), 'LA5')"
      },
      {
       "target": "alias(seriesByTag('name=system.system.load15', 'servertype=videostreaming', 'host=ea1-vts-mediaserver2.unix.tensor.ru'), 'LA15')"
      }
     ]
    },
    {
     "title": "Flussonic LA ea1-vts-mediaserver3",
     "type": "graph",
     "description": "Flussonic LA ea1-vts-mediaserver3",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('name=system.system.n_cpus', 'servertype=videostreaming', 'host=~ea1-vts-mediaserver3.*'), 'CPU Count')"
      },
      {
       "target": "alias(seriesByTag('name=system.system.load1', 'servertype=videostreaming', 'host=~ea1-vts-mediaserver3.*'), 'LA1')"
      },
      {
       "target": "alias(seriesByTag('name=system.system.load5', 'servertype=videostreaming', 'host=~ea1-vts-mediaserver3.*'), 'LA5')"
      },
      {
       "target": "alias(seriesByTag('name=system.system.load15', 'servertype=videostreaming', 'host=ea1-vts-mediaserver1'), 'LA15')"
      }
     ]
    },
    {
     "title": "Flussonic LA ea1-vts-watcher1",
     "type": "graph",
     "description": "Flussonic LA ea1-vts-watcher1",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('name=system.system.n_cpus', 'servertype=videostreaming', 'host=ea1-vts-watcher1.unix.tensor.ru'), 'CPU Count')"
      },
      {
       "target": "alias(seriesByTag('name=system.system.load1', 'servertype=videostreaming', 'host=ea1-vts-watcher1.unix.tensor.ru'), 'LA1')"
      },
      {
       "target": "alias(seriesByTag('name=system.system.load5', 'servertype=videostreaming', 'host=ea1-vts-watcher1.unix.tensor.ru'), 'LA5')"
      },
      {
       "target": "alias(seriesByTag('name=system.system.load15', 'servertype=videostreaming', 'host=ea1-vts-watcher1.unix.tensor.ru'), 'LA15')"
      }
     ]
    }
   ]
  }
 ]
}