{
 "title": "Номенклатура и склад - статистика gis-service",
 "description": "Сервис используется как транспорт взаимодействия сервиса online государственных информационных систем маркировок продуктов. Ответственный: Смирнов К.В. (Эксплуатация)",
 "tags": [
  "exploitation",
  "scripts",
  "service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system",
    "query": "tag_values(system,script=gis_statistics.py)"
   }
  ]
 },
 "panels": [
  {
   "title": "Статистика по системе \"${system:regex}\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "system"
  },
  {
   "title": "Ошибки взаимодействия по \"${system:regex}\"",
   "type": "graph",
   "description": "Ошибки взаимодействия по системе",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=gis', 'script=gis_statistics.py', 'method=GISStatistics.GetErrorsCountGIS', 'system=${system:regex}'), 'name')"
    }
   ]
  },
  {
   "title": "Ошибки доставки в онлайн по \"${system:regex}\"",
   "type": "graph",
   "description": "Ошибки доставки в онлайн по системе",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=gis', 'script=gis_statistics.py', 'method=GISStatistics.GetErrorsCountOnline', 'system=${system:regex}'), 'name')"
    }
   ]
  },
  {
   "title": "Среднее время взаимодействия по \"${system:regex}\"",
   "type": "graph",
   "description": "Среднее время взаимодействия по системе",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=gis', 'script=gis_statistics.py', 'method=GISStatistics.GetTasksDurationGIS', 'system=${system:regex}'), 'name')"
    }
   ]
  },
  {
   "title": "Среднее время доставки результата в онлайн по \"${system:regex}\"",
   "type": "graph",
   "description": "Среднее время доставки результата в онлайн по системе",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=gis', 'script=gis_statistics.py', 'method=GISStatistics.GetOnlineTasksDuration', 'system=${system:regex}'), 'name')"
    }
   ]
  },
  { "title": "Общие показатели", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "Количество активных настроек",
   "type": "graph",
   "description": "Количество активных настроек систем",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=gis', 'script=gis_CountActiveSettings.py'), 'system')"
    }
   ]
  },
  {
   "title": "Дополнительные внутренние проверки сервиса",
   "type": "graph",
   "description": "Дополнительные внутренние проверки сервиса gis",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('service=gis', 'script=gis_CustomCheck.py'), 'CustomCheck', true)"
    }
   ]
  },
  {
   "title": "Количество задач в очереди",
   "type": "graph",
   "description": "Количество задач в очереди по системам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=gis', 'script=gis_GetQuantityDocs.py', 'key=ResultInQueue'), 'system')"
    }
   ]
  },
  {
   "title": "Количество задач переданных в доставку в DWC",
   "type": "graph",
   "description": "Количество задач переданных в доставку в DWC",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=gis', 'script=gis_GetQuantityDocs.py', 'key=ResultToProcess'), 'system')"
    }
   ]
  },
  {
   "title": "Количество задач в обработке в DWC",
   "type": "graph",
   "description": "Количество задач в обработке в DWC",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=gis', 'script=gis_GetQuantityDocs.py', 'key=TasksInDWC'), 'system')"
    }
   ]
  },
  {
   "title": "Пока пустой график",
   "type": "graph",
   "description": "Всемирная пустота",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Количество запросов общее",
   "type": "graph",
   "description": "Общее количество запросов по системам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=gis', 'script=gis_GetQuantityDocs.py', 'key=SystemInQueue'), 'system')"
    }
   ]
  },
  {
   "title": "Количество запросов готовых к обработке",
   "type": "graph",
   "description": "Количество запросов готовых к обработке",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=gis', 'script=gis_GetQuantityDocs.py', 'key=SystemToProcess'), 'system')"
    }
   ]
  },
  {
   "title": "Число проблем обработки задач/запросов (Карантин)",
   "type": "graph",
   "description": "Число проблем обработки задач/запросов (Карантин)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=gis', 'script=gis_QuarantineTasks.py'), 'name')"
    }
   ]
  },
  {
   "title": "Число ХС по которым отсутствуют площадки",
   "type": "graph",
   "description": "Число ХС по которым отсутствуют площадки (собирается раз в 3 часа)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=gis', 'script=gis_OrgsWithoutEnterprise.py'), 'name')"
    }
   ]
  }
 ]
}