{
 "title": "Оператор связи - Subsystem-FSS",
 "description": "Система доставки ФСС. Ответственный: Ледяев И.К. (Эксплуатация), Бронфельд В.С. (Разработка)",
 "tags": [
  "exploitation",
  "otr",
  "service",
  "scripts"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Очереди контейнеров из ФСС на порталы",
   "type": "graph",
   "description": "Число контейнеров готовых к передаче из Транспортного модуля ФСС на порталы",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=fss', 'queue=~Очередь.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров из ФСС на порталы (задержка)",
   "type": "graph",
   "description": "Задержка отправки контейнеров из Транспортного модуля ФСС на порталы",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=fss', 'queue=~Очередь.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров без ответа от портала",
   "type": "graph",
   "description": "Число контейнеров в Транспортном модуле ФСС, ожидающих ответа от портала",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=fss', 'queue=~Ожидают.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров без ответа от портала (задержка)",
   "type": "graph",
   "description": "Возраст контейнеров в Транспортном модуле ФСС, ожидающих ответа от портала",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=fss', 'queue=~Ожидают.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров из ФСС в ядро",
   "type": "graph",
   "description": "Число контейнеров готовых к передаче из Транспортного модуля ФСС в Ядро",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=fss', 'queue=fss_to_core'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров из ФСС в ядро (задержка)",
   "type": "graph",
   "description": "Задержка отправки контейнеров из Транспортного модуля ФСС в Ядро",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=fss', 'queue=fss_to_core'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди ФСС ЛК",
   "type": "graph",
   "description": "Число записей в таблицах",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=record.count', 'subsystem=fss'), 'table')"
    }
   ]
  }
 ]
}