{
 "title": "Оператор связи - Subsystem-RPN",
 "description": "РПН. Ответственный: Ледяев И.К. (Эксплуатация), Бронфельд В.С. (Разработка)",
 "tags": [
  "exploitation",
  "otr",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Очереди контейнеров из РПН на портал",
   "type": "graph",
   "description": "Число контейнеров готовых к передаче из Транспортного модуля РПН на портал",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=rpn', 'queue=rpn_to_portal'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров из РПН на портал (задержка)",
   "type": "graph",
   "description": "Задержка отправки контейнеров из Транспортного модуля РПН на портал",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=rpn', 'queue=rpn_to_portal'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров без ответа от портала",
   "type": "graph",
   "description": "Число контейнеров в Транспортном модуле РПН, ожидающих ответа от портала",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=rpn', 'queue=Ожидают ответа от портала РПН'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров без ответа от портала (задержка)",
   "type": "graph",
   "description": "Возраст контейнеров в Транспортном модуле РПН, ожидающих ответа от портала",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=rpn', 'queue=Ожидают ответа от портала РПН'), 'queue')"
    }
   ]
  }
 ]
}