{
 "title": "Оператор связи - Subsystem-Tdata",
 "description": "Транспортные данные. Ответственный: Ледяев И.К. (Эксплуатация), Бронфельд В.С.(Разработка)",
 "tags": [
  "exploitation",
  "otr",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  {
   "title": "Очереди Транспортных данных",
   "type": "graph",
   "description": "Различные очереди в Транспортных данных",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=data'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди Транспортных данных (задержка)",
   "type": "graph",
   "description": "Задержка очередей в Транспортных данных",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=data'), 'queue')"
    }
   ]
  },
  {
   "title": "Расхождение БД tdata-billing",
   "type": "graph",
   "description": "Число расхождений абонентов в БД Транспортных данных и Биллинга по типам",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=data', 'name=diff.count'), 'name', 'type')"
    }
   ]
  }
 ]
}