{
 "title": "Оператор связи - Subsystem-Mail",
 "description": "Система доставки \"Электронная почта\". Ответственный: Ледяев И.К. (Эксплуатация), Бронфельд В.С. (Разработка)",
 "tags": [
  "exploitation",
  "otr",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Очереди контейнеров из Почты в ящики",
   "type": "graph",
   "description": "Число контейнеров готовых к передаче из Транспортного модуля Почта на электронные ящики",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=mail', 'queue=~.*mailbox.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров из Почты в ящики (задержка)",
   "type": "graph",
   "description": "Задержка отправки контейнеров из Транспортного модуля Почта на электронные ящики",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=mail', 'queue=~.*mailbox.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров из Почты в ядро",
   "type": "graph",
   "description": "Число контейнеров готовых к передаче из Транспортного модуля Почта в Ядро",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=mail', 'queue=~mail\\d_to_core'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=mail', 'queue=~mail-\\d_to_core'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров из Почты в ядро (задержка)",
   "type": "graph",
   "description": "Задержка отправки контейнеров из Транспортного модуля Почта в Ядро",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=mail', 'queue=~mail\\d_to_core'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=mail', 'queue=~mail-\\d_to_core'), 'queue')"
    }
   ]
  }
 ]
}