{
 "title": "Оператор связи - Subsystem-Folders",
 "description": "Система доставки \"Каталоги\". Ответственный: Ледяев И.К. (Эксплуатация), Бронфельд В.С. (Разработка)",
 "tags": [
  "exploitation",
  "otr",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Очереди контейнеров из Каталогов в папки",
   "type": "graph",
   "description": "Число контейнеров готовых к передаче из Транспортного модуля Каталоги в папки деловой почты",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=fold', 'queue=~folders\\d_to_PF'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров из Каталогов в папки (задержка)",
   "type": "graph",
   "description": "Задержка отправки контейнеров из Транспортного модуля Каталоги в папки деловой почты",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=fold', 'queue=~folders\\d_to_PF'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров из Каталогов в ядро",
   "type": "graph",
   "description": "Число контейнеров готовых к передаче из Транспортного модуля Каталоги в Ядро",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=fold', 'queue=~folders\\d_to_core'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров из Каталогов в ядро (задержка)",
   "type": "graph",
   "description": "Задержка отправки контейнеров из Транспортного модуля Каталоги в Ядро",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=fold', 'queue=~folders\\d_to_core'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров из папок в vipnet",
   "type": "graph",
   "description": "Число контейнеров ожидающих обработки находящихся в каталогах Деловой почты",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=fold', 'queue=~folders\\d_to_vipnet'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров из папок в vipnet (задержка)",
   "type": "graph",
   "description": "Задержка обработки исходящих контейнеров находящихся в каталогах Деловой почты",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=fold', 'queue=~folders\\d_to_vipnet'), 'queue')"
    }
   ]
  }
 ]
}