{
 "title": "Оператор связи - Subsystem-Core",
 "description": "Ядро. Ответственный: Ледяев И.К. (Эксплуатация), Урываев Б.В. (Разработка)",
 "tags": [
  "exploitation",
  "otr",
  "service",
  "scripts"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Очереди контейнеров ЭЛО в облако",
   "type": "graph",
   "description": "Число контейнеров ЭЛО готовых к передаче в онлайн",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=queue.size', 'subsystem=~core-elo\\d', 'queue=core_to_cloud', 'unit!=~.*'), 'subsystem', 'queue'), 'core-', '')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров ЭЛО в облако (задержка)",
   "type": "graph",
   "description": "Задержка передачи контейнеров ЭЛО в онлайн",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=queue.lag', 'subsystem=~core-elo\\d', 'queue=core_to_cloud'), 'subsystem', 'queue'), 'core-', '')"
    }
   ]
  },
  {
   "title": "Очереди из ядра ЭЛО1 в юниты (top5)",
   "type": "table-old",
   "description": "Число контейнеров ЭЛО готовых к передаче в онлайн с разбивкой по юнитам",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "highestCurrent(aliasByTags(seriesByTag('name=queue.size', 'subsystem=core-elo1', 'unit=~.*'), 'unit'), 5)"
    }
   ]
  },
  {
   "title": "Очереди из ядра ЭЛО2 в юниты (top5)",
   "type": "table-old",
   "description": "Число контейнеров ЭЛО готовых к передаче в онлайн с разбивкой по юнитам",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "target": "highestCurrent(aliasByTags(seriesByTag('name=queue.size', 'subsystem=core-elo2', 'unit=~.*'), 'unit'), 5)"
    }
   ]
  },
  {
   "title": "Очереди из ядра ЭЛО3 в юниты (top5)",
   "type": "table-old",
   "description": "Число контейнеров ЭЛО готовых к передаче в онлайн с разбивкой по юнитам",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "highestCurrent(aliasByTags(seriesByTag('name=queue.size', 'subsystem=core-elo3', 'unit=~.*'), 'unit'), 5)"
    }
   ]
  },
  {
   "title": "Очереди из ядра ЭЛО4 в юниты (top5)",
   "type": "table-old",
   "description": "Число контейнеров ЭЛО готовых к передаче в онлайн с разбивкой по юнитам",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "target": "highestCurrent(aliasByTags(seriesByTag('name=queue.size', 'subsystem=core-elo4', 'unit=~.*'), 'unit'), 5)"
    }
   ]
  },
  {
   "title": "Очереди контейнеров ЭДО в облако",
   "type": "graph",
   "description": "Число контейнеров ЭДО готовых к передаче в онлайн",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=queue.size', 'subsystem=~core-edo\\d', 'queue=core_to_cloud', 'unit!=~.*'), 'subsystem', 'queue'), 'core-', '')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров ЭДО в облако (задержка)",
   "type": "graph",
   "description": "Задержка передачи контейнеров ЭДО в онлайн",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=queue.lag', 'subsystem=~core-edo\\d', 'queue=core_to_cloud'), 'subsystem', 'queue'), 'core-', '')"
    }
   ]
  },
  {
   "title": "Очереди из ядра ЭДО1 в юниты (top5)",
   "type": "table-old",
   "description": "Число контейнеров ЭДО готовых к передаче в онлайн с разбивкой по юнитам",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "target": "highestCurrent(aliasByTags(seriesByTag('name=queue.size', 'subsystem=core-edo1', 'unit=~.*'), 'unit'), 5)"
    }
   ]
  },
  {
   "title": "Очереди из ядра ЭДО2 в юниты (top5)",
   "type": "table-old",
   "description": "Число контейнеров ЭДО готовых к передаче в онлайн с разбивкой по юнитам",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "target": "highestCurrent(aliasByTags(seriesByTag('name=queue.size', 'subsystem=core-edo2', 'unit=~.*'), 'unit'), 5)"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в систему Почта",
   "type": "graph",
   "description": "Число контейнеров ЭЛО готовых к передаче Транспортный модуль Почта",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=mail', 'queue=~core_elo\\d_to_mail$'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в систему Почта (задержка)",
   "type": "graph",
   "description": "Задержка передачи контейнеров ЭЛО в Транспортный модуль Почта",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=mail', 'queue=~core_elo\\d_to_mail$'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в систему Каталоги",
   "type": "graph",
   "description": "Число контейнеров ЭЛО готовых к передаче Транспортный модуль Каталоги",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=fold', 'queue=~core_elo\\d_to_folders$'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в систему Каталоги (задержка)",
   "type": "graph",
   "description": "Задержка передачи контейнеров ЭЛО в Транспортный модуль Каталоги",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=fold', 'queue=~core_elo\\d_to_folders$'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в систему ФСС",
   "type": "graph",
   "description": "Число контейнеров ЭЛО готовых к передаче Транспортный модуль ФСС",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=fss', 'queue=~core_elo\\d_to_fss$'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в систему ФСС (задержка)",
   "type": "graph",
   "description": "Задержка передачи контейнеров ЭЛО в Транспортный модуль ФСС",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=fss', 'queue=~core_elo\\d_to_fss$'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в систему ФСРАР",
   "type": "graph",
   "description": "Число контейнеров ЭЛО готовых к передаче Транспортный модуль ФСРАР",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=fsrar', 'queue=~core_elo\\d_to_fsrar$'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в систему ФСРАР (задержка)",
   "type": "graph",
   "description": "Задержка передачи контейнеров ЭЛО в Транспортный модуль ФСРАР",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=fsrar', 'queue=~core_elo\\d_to_fsrar$'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в систему РПН",
   "type": "graph",
   "description": "Число контейнеров ЭЛО готовых к передаче Транспортный модуль РПН",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=rpn', 'queue=~core_elo\\d_to_rpn$'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в систему РПН (задержка)",
   "type": "graph",
   "description": "Задержка передачи контейнеров ЭЛО в Транспортный модуль РПН",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=rpn', 'queue=~core_elo\\d_to_rpn$'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в систему ЦБ",
   "type": "graph",
   "description": "Число контейнеров ЭЛО готовых к передаче Транспортный модуль ЦБ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=cb', 'queue=~core_elo\\d_to_cb$'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в систему ЦБ (задержка)",
   "type": "graph",
   "description": "Задержка передачи контейнеров ЭЛО в Транспортный модуль ЦБ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=cb', 'queue=~core_elo\\d_to_cb$'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в систему ПФ",
   "type": "graph",
   "description": "Число контейнеров ЭЛО готовых к передаче Транспортный модуль ПФ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=pf', 'queue=~core_elo\\d_to_pf$'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в систему ПФ (задержка)",
   "type": "graph",
   "description": "Задержка передачи контейнеров ЭЛО в Транспортный модуль ПФ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=pf', 'queue=~core_elo\\d_to_pf$'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров ЭЛО и ЭДО в облако с числом попыток больше 3",
   "type": "graph",
   "description": "Число контейнеров ЭЛО и ЭДО готовых к передаче в онлайн, у которых уже было больше 3х попыток передачи",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=queue.size', 'subsystem=~core-e[l,d]o\\d$', 'queue=~.*attempts$'), 'subsystem', 'queue'), 'core-', '')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в системы доставки с числом попыток больше 3",
   "type": "graph",
   "description": "Число контейнеров ЭЛО готовых к передаче в Транспортные модули, у которых уже было больше 3х попыток передачи",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=queue.size', 'subsystem!=~core-e[l,d]o\\d$', 'queue=~.*attempts$'), 'queue'), 'core-', '')"
    }
   ]
  },
  {
   "title": "Число необработанных записей в резервном ядре",
   "type": "graph",
   "description": "Число необработанных записей в резервном ядре, свидетельствует о включении резервного ядра в работу",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=record.count', 'subsystem=~res.+'), 'subsystem', 'table')"
    }
   ]
  }
 ]
}