{
 "title": "Оператор связи - Subsystem Analytics",
 "description": "Аналитика. Ответственный: Ледяев И.К. (Эксплуатация), Урываев Б.В. (Разработка)",
 "tags": [
  "exploitation",
  "otr",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Очередь репликации первичных документов",
   "type": "graph",
   "description": "Число первичных документов ожидающих репликации из ядра в хранилище",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=wh', 'queue=~Primary docs.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Очередь репликации первичных документов (задержка)",
   "type": "graph",
   "description": "Задержка репликации первичных документов из ядра в хранилище",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=wh', 'queue=~Primary docs.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Очередь репликации вторичных документов",
   "type": "graph",
   "description": "Число вторичных документов ожидающих репликации из ядра в хранилище",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=wh', 'queue=~Secondary docs.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Очередь репликации вторичных документов (задержка)",
   "type": "graph",
   "description": "Задержка репликации вторичных документов из ядра в хранилище",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=wh', 'queue=~Secondary docs.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Очередь репликации рассылок",
   "type": "graph",
   "description": "Число рассылок ожидающих репликации из ядра в хранилище",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=wh', 'queue=~Distribution.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди репликации рассылок (задержка)",
   "type": "graph",
   "description": "Задержка репликации рассылок из ядра в хранилище",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=wh', 'queue=~Distribution.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Очередь репликации из систем доставки",
   "type": "graph",
   "description": "Число документов ожидающих репликации из транспортных модулей в хранилище",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=~.*', 'queue=~.*to_wh'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди wh и analytics",
   "type": "graph",
   "description": "Различные внутренние очереди обработки в аналитике и хранилище",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=wh', 'queue=~Очередь.*'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=analytics', 'queue=~Очередь.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Отставание слэйвов",
   "type": "graph",
   "description": "Лаг репликации в слэйв аналитики",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.postgres.db-slave-replication-timelag.csr-oper-analytics-db2.pgsql.interval-30sec.pgsql.replication.time.avg,4,-3,-2)"
    }
   ]
  }
 ]
}