{
 "title": "Оператор связи - системный экран (OTR)",
 "description": "Число проходящих документов. Ответственный: Ледяев И.К. (Эксплуатация), Урываев Б.В. (Разработка)",
 "tags": [
  "exploitation",
  "otr",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Статистика по типам документообротов",
   "type": "graph",
   "description": "Число первичных документов полученных за текущий день",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=document.count', 'type=summary', 'source=database'), 'doctype', 'type')"
    }
   ]
  },
  {
   "title": "Количество принимаемых документов в час",
   "type": "graph",
   "description": "Расчетная скорость поступления первичных документов",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=document.count', 'type=speed', 'source=database'), 'doctype')"
    }
   ]
  },
  {
   "title": "Статистика по регламентам НИ",
   "type": "graph",
   "description": "Число полученных за текущий день документов налоговой, с разбивкой по регламентам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=document.count', 'type=detail', 'doctype=ni', 'interval=900s'), 'doctype', 'reglament')"
    }
   ]
  },
  {
   "title": "Статистика по регламентам ПФ",
   "type": "graph",
   "description": "Число полученных за текущий день документов ПФ, с разбивкой по регламентам",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=document.count', 'type=detail', 'doctype=pf'), 'doctype', 'reglament')"
    }
   ]
  },
  {
   "title": "Статистика по регламентам ТОГС",
   "type": "graph",
   "description": "Число полученных за текущий день документов ТОГС, с разбивкой по регламентам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=document.count', 'type=detail', 'doctype=togs'), 'doctype', 'reglament')"
    }
   ]
  },
  {
   "title": "Статистика по регламентам ФСРАР",
   "type": "graph",
   "description": "Число полученных за текущий день документов ФСРАР, с разбивкой по регламентам",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=document.count', 'type=detail', 'doctype=fsrar'), 'doctype', 'reglament')"
    }
   ]
  },
  {
   "title": "Статистика по регламентам ФСС",
   "type": "graph",
   "description": "Число полученных за текущий день документов ФСС, с разбивкой по регламентам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=document.count', 'type=detail', 'doctype=fss'), 'doctype', 'reglament')"
    }
   ]
  },
  {
   "title": "Статистика по регламентам РПН",
   "type": "graph",
   "description": "Число полученных за текущий день документов РПН, с разбивкой по регламентам",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=document.count', 'type=detail', 'doctype=rpn'), 'doctype', 'reglament')"
    }
   ]
  },
  {
   "title": "Статистика по регламентам ЭДО",
   "type": "graph",
   "description": "Число полученных за текущий день документов ЭДО, с разбивкой по регламентам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=document.count', 'type=detail', 'doctype=edo'), 'doctype', 'reglament')"
    }
   ]
  }
 ]
}