{
 "title": "ОФД - Очереди",
 "description": "Система отображения данных ОФД. Ответственный: Ледяев И.К. (Эксплуатация), Бронфельд В.С. (Разработка)",
 "tags": [
  "ofd",
  "exploitation",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Analytics Queues",
   "type": "graph",
   "description": "Очереди обработки документов в аналитике ОФД",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.size', 'unit!=~.*', 'queue=~analytics.+'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.size', 'unit!=~.*', 'queue=extra_processing_doc'), 'queue')"
    }
   ]
  },
  {
   "title": "Analytics Queues (lag)",
   "type": "graph",
   "description": "Задержка обработки документов в аналитике ОФД",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.lag', 'unit!=~.*', 'queue=~analytics.+'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.lag', 'unit!=~.*', 'queue=extra_processing_doc'), 'queue')"
    }
   ]
  },
  {
   "title": "Analytics Queues (suspended)",
   "type": "graph",
   "description": "Приостановленные документы в аналитике ОФД",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.suspended', 'unit!=~.*', 'queue=~analytics.+'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.suspended', 'unit!=~.*', 'queue=extra_processing_doc'), 'queue')"
    }
   ]
  },
  {
   "title": "Core Queues",
   "type": "graph",
   "description": "Очереди обработки документов в ядре ОФД",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.size', 'unit!=~.*', 'queue=~core.+'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.size', 'unit!=~.*', 'queue=duplicate_fd'), 'queue')"
    }
   ]
  },
  {
   "title": "Core Queues (lag)",
   "type": "graph",
   "description": "Задержка обработки документов в ядре ОФД",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.lag', 'unit!=~.*', 'queue=~core.+'), 'queue')"
    }
   ]
  },
  {
   "title": "Core Queues (suspended)",
   "type": "graph",
   "description": "Приостановленные документы в ядре ОФД",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.suspended', 'unit!=~.*', 'queue=~core.+'), 'queue')"
    }
   ]
  },
  {
   "title": "Registration Queues",
   "type": "graph",
   "description": "Очереди регистрации в ОФД",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.size', 'unit!=~.*', 'queue=~regkkt.+'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.size', 'unit!=~.*', 'queue=receive_from_fns'), 'queue')"
    }
   ]
  },
  {
   "title": "Registration Queues (lag)",
   "type": "graph",
   "description": "Задержка очередей регистрации в ОФД",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.lag', 'unit!=~.*', 'queue=~regkkt.+'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.lag', 'unit!=~.*', 'queue=receive_from_fns'), 'queue')"
    }
   ]
  },
  {
   "title": "Registration Queues (suspended)",
   "type": "graph",
   "description": "Приостановленные регистрации в ОФД",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.suspended', 'unit!=~.*', 'queue=receive_from_fns'), 'queue')"
    }
   ]
  },
  {
   "title": "FNS Queues",
   "type": "graph",
   "description": "Очереди модуля ФНС в ОФД",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.size', 'unit!=~.*', 'queue=~fiscalDocument.+'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.size', 'unit!=~.*', 'queue=~(aggregate_|check_|contract_|invalid_|get_).+'), 'queue')"
    }
   ]
  },
  {
   "title": "FNS Queues (lag)",
   "type": "graph",
   "description": "Задержка обработки очередей ФНС в ОФД",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.lag', 'unit!=~.*', 'queue=~fiscalDocument.+'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.lag', 'unit!=~.*', 'queue=~(aggregate_|check_|contract_|invalid_|get_).+'), 'queue')"
    }
   ]
  },
  {
   "title": "FNS Queues (suspended)",
   "type": "graph",
   "description": "Приостановленные документы ФНС в ОФД",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.suspended', 'unit!=~.*', 'queue=~fiscalDocument.+'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.suspended', 'unit!=~.*', 'queue=~(aggregate_|check_|contract_|invalid_|get_).+'), 'queue')"
    }
   ]
  },
  {
   "title": "ATDC Queues",
   "type": "graph",
   "description": "Очереди обработки по ЦРПТ в ОФД",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.size', 'unit!=~.*', 'queue=~.+atdc.+'), 'queue')"
    }
   ]
  },
  {
   "title": "ATDC Queues (lag)",
   "type": "graph",
   "description": "Задержка обработки очередей ЦРПТ в ОФД",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.lag', 'unit!=~.*', 'queue=~.+atdc.+'), 'queue')"
    }
   ]
  },
  {
   "title": "ATDC Queues (suspended)",
   "type": "graph",
   "description": "Приостановленные документы ЦРПТ в ОФД",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.suspended', 'unit!=~.*', 'queue=~.+atdc.+'), 'queue')"
    }
   ]
  },
  {
   "title": "Nomenclature analyze Queues",
   "type": "graph",
   "description": "Очередь обработки на сервисе nomenclature-analyzer",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.size', 'unit!=~.*', 'queue=analyze'), 'queue')"
    }
   ]
  },
  {
   "title": "Nomenclature analyze Queues (lag)",
   "type": "graph",
   "description": "Задержка обработки на сервисе nomenclature-analyzer",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.lag', 'unit!=~.*', 'queue=analyze'), 'queue')"
    }
   ]
  },
  {
   "title": "Nomenclature analyze Queues (suspended)",
   "type": "graph",
   "description": "Приостановленные документы на сервисе nomenclature-analyzer",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.suspended', 'unit!=~.*', 'queue=analyze'), 'queue')"
    }
   ]
  }
 ]
}