{
 "title": "ОФД - Бизнес логики",
 "description": "Система отображения данных ОФД. Ответственный: Ледяев И.К. (Эксплуатация), Бронфельд В.С. (Разработка)",
 "tags": [
  "ofd",
  "exploitation",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "total.srv.workers",
   "type": "graph",
   "description": "Суммарное число доступных\\свободных\\занятых процессов по сервису transport-ofd.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'bl=total', 'name=~srv.workers\\..*'), 'bl', 'name')"
    }
   ]
  },
  {
   "title": "total.srv.requests",
   "type": "graph",
   "description": "Суммарное число запросов обработанных\\ошибочных\\в очереди по сервису transport-ofd. Запросов в секунду.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'bl=total', 'name=~srv.request\\..*'), 'bl', 'name')"
    }
   ]
  },
  {
   "title": "ofd1-srv1.srv.workers",
   "type": "graph",
   "description": "Число доступных\\свободных\\занятых процессов по сервису transport-ofd на БЛ ofd1-srv1.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'bl=ofd1-srv1', 'name=~srv.workers\\..*'), 'bl', 'name')"
    }
   ]
  },
  {
   "title": "ofd1-srv1.srv.requests",
   "type": "graph",
   "description": "Число запросов обработанных\\ошибочных\\в очереди по сервису transport-ofd на БЛ ofd1-srv1. Запросов в секунду.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'bl=ofd1-srv1', 'name=~srv.request\\..*'), 'bl', 'name')"
    }
   ]
  },
  {
   "title": "ofd1-srv2.srv.workers",
   "type": "graph",
   "description": "Число доступных\\свободных\\занятых процессов по сервису transport-ofd на БЛ ofd1-srv2.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'bl=ofd1-srv2', 'name=~srv.workers\\..*'), 'bl', 'name')"
    }
   ]
  },
  {
   "title": "ofd1-srv2.srv.requests",
   "type": "graph",
   "description": "Число запросов обработанных\\ошибочных\\в очереди по сервису transport-ofd на БЛ ofd1-srv2. Запросов в секунду.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'bl=ofd1-srv2', 'name=~srv.request\\..*'), 'bl', 'name')"
    }
   ]
  }
 ]
}