{
 "title": "ОФД - Проверки",
 "description": "Система отображения данных ОФД. Ответственный: Ледяев И.К. (Эксплуатация), Бронфельд В.С. (Разработка)",
 "tags": [
  "ofd",
  "exploitation",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Проверка ОФД для кассы",
   "type": "graph",
   "description": "Время ответа БЛ transport-ofd порт 7777 через сайт kkt.sbis.ru изнутри и снаружи",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'bl=kkt.sbis.ru'), 'bl', 'method', 'route')"
    }
   ]
  },
  {
   "title": "Проверка ОФД для кассы (БЛ)",
   "type": "graph",
   "description": "Время ответа БЛ transport-ofd порт 7777 напрямую изнутри",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=response.time', 'bl=~ofd1-srv.*'), 'bl', 'method')"
    }
   ]
  },
  {
   "title": "Очереди систем ОФД",
   "type": "graph",
   "description": "Различные внутренние очереди БД в ОФД",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.size', 'unit!=~.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди систем ОФД (lag)",
   "type": "graph",
   "description": "Задержка обработки различных очередей в БД в ОФД ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.lag'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди систем ОФД (suspended)",
   "type": "graph",
   "description": "Различные приостановленные внутренние очереди БД в ОФД",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.suspended'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди из ОФД в юниты (top5)",
   "type": "table-old",
   "description": "Очередь фискальных документов из ОФД в юниты",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "target": "highestCurrent(aliasByTags(seriesByTag('subsystem=ofd', 'name=queue.size', 'unit=~.*'), 'unit'), 5)"
    }
   ]
  },
  {
   "title": "Проверка ПКЗ",
   "type": "graph",
   "description": "Время ответа ПКЗ на различные методы",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=pkz', 'name=response.time'), 'pkz', 'method')"
    }
   ]
  },
  {
   "title": "ОФД swift healthcheck",
   "type": "graph",
   "description": "ofd1-swift.unix.tensor.ru:8080/healthcheck",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=ofd', 'host=ofd1-swift'), 'host', 'method')"
    }
   ]
  },
  {
   "title": "PAK Success",
   "type": "graph",
   "description": "Число успешных обращений к ПАК",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(nonNegativeDerivative(seriesByTag('subsystem=pkz', 'name=requests.success', 'method=~.*wrap$')), 'pak', 'method')"
    }
   ]
  },
  {
   "title": "PAK Errors",
   "type": "graph",
   "description": "Ошибки ПАКов",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(nonNegativeDerivative(seriesByTag('subsystem=pkz', 'name=requests.error', 'method=~.*wrap$')), 'pak', 'method')"
    }
   ]
  },
  {
   "title": "Расхождение между ОФД и статистикой",
   "type": "graph",
   "description": "Расхождение между ОФД и статистикой",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~fiscaldocument\\..*', 'type=~.+'), 'type', 'name')"
    }
   ]
  },
  {
   "title": "Статус сервиса регистрации ККТ (сервис ФНС)",
   "type": "graph",
   "description": "Возвращаются следующие статусы:\n•    -1 - Ошибка от сервиса registration-kkt\n•    0 - Можно отправлять любые запросы\n•    1 - Нельзя отправлять никакие API запросы\n•    2 - Нельзя отправлять API запросы на регистрационные действия, а также проверять код ФИАС (метод 3.3)\n•    3 - Нельзя отправлять API запросы на регистрационные действия\n•    4 - Можно полноценно использовать API, но обработка заявлений может превышать SLA",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=response.status', 'subsystem=ofd', 'service=registration-kkt'), 'name')"
    },
    {
     "target": "alias(constantLine(-1), 'Ошибка от сервиса registration-kkt')"
    },
    {
     "target": "alias(constantLine(1), 'Нельзя отправлять никакие API запросы')"
    },
    {
     "target": "alias(constantLine(2), ' Нельзя отпр. API запросы на рег. действ., а также проверять код ФИАС (метод 3.3)')"
    },
    {
     "target": "alias(constantLine(3), 'Нельзя отправлять API запросы на регистрационные действия')"
    },
    {
     "target": "alias(constantLine(4), 'Можно полноценно исп. API, но обработка заявлений может превышать SLA')"
    }
   ]
  },
  {
   "title": "Время получения чека от ФНС",
   "type": "graph",
   "description": "Время получения чека от ФНС",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=fiscaldocument.get.time', 'contur=prod', 'service=purchases-internal'), 'name')"
    }
   ]
  },
  {
   "title": "Срок действия ключей\\лицензий",
   "type": "table-old",
   "description": "Число дней до окончания сроков сертификатов\\ключей\\лицензий",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "target": "currentBelow(aliasByTags(seriesByTag('name=days_left', 'key_type!=~(restart_pak|change_passwords)', 'type=~.+'), 'host', 'type', 'key_type'), 200)"
    }
   ]
  },
  {
   "title": "Состояние Касперского",
   "type": "graph",
   "description": "Состояния Касперского в контуре ОФД",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~kesl_.+', 'subsystem=ofd'), 'name', 'host')"
    }
   ]
  },
  {
   "title": "Состояние Ufix",
   "type": "graph",
   "description": "Состояние Ufix (контроль файлов) в контуре ОФД",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~ufix_control', 'subsystem=ofd'), 'host')"
    }
   ]
  }
 ]
}