{
 "title": "ОФД - Дионис",
 "description": "Система отображения данных ОФД. Ответственный: Ледяев И.К. (Эксплуатация), Бронфельд В.С. (Разработка)",
 "tags": [
  "ofd",
  "exploitation",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "description": "Загрузка CPU",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=~system.system.+'), 'name'), 2)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=system.cpu.usage_idle'), 'name'), 2)"
    }
   ]
  },
  {
   "title": "Context switches",
   "type": "graph",
   "description": "Context switches",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=system.kernel.context_switches'), 'name'), 2)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Использование памяти",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=~system.mem.+'), 'name'), 2)"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "description": "Загрузка диска",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=~system.diskio.+'), 'name'), 2)"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "description": "Прерывания",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=system.kernel.interrupts'), 'name'), 2)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "description": "Температура",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=system.temperature'), 'type')"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "description": "Сетевой трафик bits\\sec",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=system.net.rx.bps'), 'name', 'interface'), 2, 3, 4)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=system.net.tx.bps'), 'name', 'interface'), 2, 3, 4)"
    }
   ]
  },
  {
   "title": "Network traffic pps",
   "type": "graph",
   "description": "Сетевой трафик packets\\sec",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=system.net.rx.pps'), 'name', 'interface'), 2, 3, 4)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=system.net.tx.pps'), 'name', 'interface'), 2, 3, 4)"
    }
   ]
  },
  {
   "title": "Interface state",
   "type": "graph",
   "description": "Состояние сетевых интерфейсов",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=system.net.interface_state'), 'interface')"
    }
   ]
  },
  {
   "title": "Kernel packet drop",
   "type": "graph",
   "description": "Дропы пакетов ядром",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=system.net.kernel_packet_drop'), 'name')"
    }
   ]
  },
  {
   "title": "Network packets discard",
   "type": "graph",
   "description": "Дропы сетевых пакетов",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=system.net.rx.discard.pps'), 'name', 'interface'), 2, 3, 5)"
    }
   ]
  },
  {
   "title": "Network traffic error",
   "type": "graph",
   "description": "Ошибки сети",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=system.net.rx.errors.pps'), 'name', 'interface'), 2, 3, 5)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=system.net.tx.errors.pps'), 'name', 'interface'), 2, 3, 5)"
    }
   ]
  },
  {
   "title": "Total connections",
   "type": "graph",
   "description": "Суммарное число коннектов",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=ofd1-dionis1.corp.tensor.ru', 'name=system.net.connections_total'), 'name')"
    }
   ]
  }
 ]
}