{
 "title": "ОФД - Очереди PURCHASES",
 "description": "Система отображения данных ОФД. Ответственный: Ледяев И.К. (Эксплуатация), Бронфельд В.С. (Разработка)",
 "tags": [
  "ofd",
  "exploitation",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Очереди purchases",
   "type": "graph",
   "description": "Очереди обработки в системе purchases",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=purchases', 'name=queue.size'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди purchases (lag)",
   "type": "graph",
   "description": "Задержки обработки очередей в системе purchases",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=purchases', 'name=queue.lag'), 'queue')"
    }
   ]
  },
  {
   "title": "Очереди purchases (suspended)",
   "type": "graph",
   "description": "Приостановленные очереди обработки в системе purchases",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=purchases', 'name=queue.suspended'), 'queue')"
    }
   ]
  },
  {
   "title": "Очередь purchase_fns",
   "type": "graph",
   "description": "Задержка очереди purchases_fns",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=purchases', 'name=queue.avg'), 'queue', 'name')"
    }
   ]
  },
  {
   "title": "Очередь purchase_fns (avg_all)",
   "type": "graph",
   "description": "Задержка очереди purchases_fns (avg_all)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('subsystem=purchases', 'name=queue.avg_all'), 'queue', 'name')"
    }
   ]
  }
 ]
}