{
 "title": "СБИС Диск - Ceph OSD's latency",
 "description": "Обзор кластера Ceph. Ответственный: Грошев А.Н. (Разработка)",
 "tags": [
  "ceph",
  "telegraf",
  "service",
  "sbisdisk"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "tag_values(cluster,servertype=ceph)"
   },
   {
    "name": "device_class",
    "query": "tag_values(device_class,cluster=$cluster)"
   },
   {
    "name": "host",
    "query": "tag_values(host,cluster=$cluster)"
   }
  ]
 },
 "panels": [
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "description": "Распределение задержки по дискам (с учетом очередей)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "divideSeriesLists(#A,#B)",
     "targetFull": "divideSeriesLists(sortByName(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_latency', 'device_class=~${device_class:regex}', 'host=~${host:regex}')), true, false),sortByName(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op', 'device_class=~${device_class:regex}', 'host=~${host:regex}')), true, false))"
    }
   ]
  },
  {
   "title": "OSD apply latency (including queue time)",
   "type": "graph",
   "description": "Задержка дисков с учетом очередей",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(divideSeriesLists(#E, #A), 'host', 'ceph_daemon'), '.unix.tensor.ru.', '/')",
     "targetFull": "aliasSub(aliasByTags(divideSeriesLists(sortByName(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_latency', 'device_class=~${device_class:regex}', 'host=~${host:regex}')), true, false), sortByName(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op', 'device_class=~${device_class:regex}', 'host=~${host:regex}')), true, false)), 'host', 'ceph_daemon'), '.unix.tensor.ru.', '/')"
    }
   ]
  },
  {
   "title": "OSD Commit Latency Distribution",
   "type": "heatmap",
   "description": "Распределение задержки дисков (без учета очередей)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "divideSeriesLists(#A,#B)",
     "targetFull": "divideSeriesLists(sortByName(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_process_latency', 'device_class=~${device_class:regex}', 'host=~${host:regex}')), true, false),sortByName(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op', 'device_class=~${device_class:regex}', 'host=~${host:regex}')), true, false))"
    }
   ]
  },
  {
   "title": "OSD commit latency (excluding queue time)",
   "type": "graph",
   "description": "Задержка по дискам (без учета очередей)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(divideSeriesLists(#E, #A), 'host', 'ceph_daemon'), '.unix.tensor.ru.', '/')",
     "targetFull": "aliasSub(aliasByTags(divideSeriesLists(sortByName(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_process_latency', 'device_class=~${device_class:regex}', 'host=~${host:regex}')), true, false), sortByName(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op', 'device_class=~${device_class:regex}', 'host=~${host:regex}')), true, false)), 'host', 'ceph_daemon'), '.unix.tensor.ru.', '/')"
    }
   ]
  },
  {
   "title": "OSD Write Op Latency Distribution",
   "type": "heatmap",
   "description": "Распределение задержки по дискам при записи",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "divideSeriesLists(#A, #B)",
     "targetFull": "divideSeriesLists(sortByName(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_w_latency', 'device_class=~${device_class:regex}', 'host=~${host:regex}')), true, false), sortByName(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_w', 'device_class=~${device_class:regex}', 'host=~${host:regex}')), true, false))"
    }
   ]
  },
  {
   "title": "OSD Read Op Latency Distribution",
   "type": "heatmap",
   "description": "Распределение задержки по дискам при чтении",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "target": "sortByName(divideSeriesLists(#A, #B), true, false)",
     "targetFull": "sortByName(divideSeriesLists(sortByName(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_r_latency', 'device_class=~${device_class:regex}', 'host=~${host:regex}')), true, false), sortByName(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_r', 'device_class=~${device_class:regex}', 'host=~${host:regex}')), true, false)), true, false)"
    }
   ]
  }
 ]
}