{
 "title": "СБИС Диск - swift/ceph здоровье SSD v.2",
 "description": "Ответственный: Грошев А.Н. (Разработка)",
 "tags": [
  "sbisdisk",
  "ceph",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "tag_values(cluster,servertype=ceph)"
   },
   {
    "name": "host",
    "query": "tag_values(host,cluster=$cluster)"
   },
   {
    "name": "disk",
    "query": "tag_values(_name,host=$host,type=SSD)"
   }
  ]
 },
 "panels": [
  {
   "title": "Реаллоцировано блоков",
   "type": "yesoreyeram-boomtable-panel",
   "description": "* reallocated blocks - реаллоцировано блоков после не удачной попытки записи или проверки\n\nSMART ATTR 5 RAW VALUE",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=hdd_smart_realloc', 'host=~${host:regex}', 'cluster=$cluster', 'type=SSD', '_name=~${disk:regex}'), 'type', 'host', '_name', 'sn'), '.unix.tensor.ru', ''), '\\.', ' ')"
    }
   ]
  },
  {
   "title": "Осталось места для реаллокации в %",
   "type": "yesoreyeram-boomtable-panel",
   "description": "* reallocated blocks  - в value Intel показывает оставшеесяч место в %%\n\nSMART ATTR 170 current value",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=hdd_smart_reallocBlocksLeftPcnt', 'host=~${host:regex}', 'cluster=$cluster', 'type=SSD', '_name=~${disk:regex}'), 'type', 'host', '_name', 'sn'), '.unix.tensor.ru', ''), '\\.', ' ')"
    }
   ]
  },
  {
   "title": "Количество записанных данных (в секунду)",
   "type": "graph",
   "description": "* Total MiB Write - прирост суммарного количества мегабайт записанных на устройство за интервал 10 минут.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~hdd_smart_TotalMibWrite', 'host=~${host:regex}', 'cluster=$cluster', 'type=SSD', '_name=~${disk:regex}')), '_name', 'host', 'sn'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Число оставшихся резервных блоков",
   "type": "yesoreyeram-boomtable-panel",
   "description": "* AvailableReservdSpace - использование резервного пространства\n\nSMART Attr 232 Raw value",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=hdd_smart_AvailableReservdSpace', 'host=~${host:regex}', 'cluster=$cluster', 'type=SSD', '_name=~${disk:regex}'), 'type', 'host', '_name', 'sn'), '.unix.tensor.ru', ''), '\\.', ' ')"
    }
   ]
  },
  {
   "title": "Осталось жизни в %",
   "type": "yesoreyeram-boomtable-panel",
   "description": "* Total used reserved blocks - задействовано резервное место (не всегда правильно)\n\nSMART Attr 231 or 202 current value",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=hdd_smart_LifetimeRemaining', 'host=~${host:regex}', 'cluster=$cluster', 'type=SSD', '_name=~${disk:regex}'), 'type', 'host', '_name', 'sn'), '.unix.tensor.ru', ''), '\\.', ' ')"
    }
   ]
  },
  {
   "title": "Число CRC ошибок на интерфейсе",
   "type": "yesoreyeram-boomtable-panel",
   "description": "* UDMA_CRC_Error - Число ошибок передачи данных на внешнем интерфейсе выявленных с помощью CRC .\n\nSMART ATTR 199 (VALUE/RAW VALUE)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=hdd_smart_CRCError', 'host=~${host:regex}', 'cluster=$cluster', 'type=SSD', '_name=~${disk:regex}'), 'type', 'host', '_name', 'sn'), '.unix.tensor.ru', ''), '\\.', ' ')"
    }
   ]
  },
  {
   "title": "Число коррекции ошибок с помощью ECC",
   "type": "yesoreyeram-boomtable-panel",
   "description": "* Hardware ECC recovered - Число коррекции ошибок аппаратной частью диска (ошибок чтения, ошибок позиционирования, ошибок передачи по внешнему интерфейсу).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=hdd_smart_HardwareECCRecovered', 'host=~${host:regex}', 'cluster=$cluster', 'type=SSD', '_name=~${disk:regex}'), 'type', 'host', '_name', 'sn'), '.unix.tensor.ru', ''), '\\.', ' ')"
    }
   ]
  },
  {
   "title": "Равномерность износа ячеек.",
   "type": "yesoreyeram-boomtable-panel",
   "description": "* WearLevelingCount - равномерность износа ячеек.\nhttps://superuser.com/questions/1037644/samsung-ssd-wear-leveling-count-meaning\n\n_Kingston_ describe this SMART attribute as follows:\nNumber of erase/program cycles per block on average. This attribute is intended to be an indicator of imminent wear-out. Normalized Equation: 100 – ( 100 * Average Erase Count / NAND max rated number of erase cycles)\n\nIgnore the Raw Data in these instances (They can be manipulated by manufacturers to work in different ways), and look at the Current Value column.\n\nСреднее количество циклов стирания / программирования на один блок. Этот атрибут предназначен для индикации неизбежного износа. Нормализованное уравнение: 100 - (100 * Среднее число стирания / максимальное номинальное количество циклов стирания NAND)\n\nИгнорируйте необработанные данные в этих случаях (производители могут манипулировать ими для работы по-разному) и посмотрите на столбец «Текущее значение». \n\nThis source from _Anandtech_ gives us a good indication of how to use this figure:\n\nThe Wear Leveling Count (WLC) SMART value gives us all the data we need. The current value stands for the remaining endurance of the drive in percentage, meaning that it starts from 100 and decreases linearly as the drive is written to. \n\nThe raw WLC value counts the consumed P/E cycles, so if these two values are monitored while writing to the drive, sooner than later we will find the spot where the normalized value drops by one.\n\nЗначение SMART подсчета выравнивания износа (WLC) дает нам все необходимые данные. Текущее значение обозначает оставшийся ресурс диска в процентах, что означает, что он начинается со 100 и линейно уменьшается по мере записи в диск.\n\nНеобработанное значение WLC подсчитывает израсходованные циклы P / E, поэтому, если эти два значения отслеживаются во время записи на диск, рано или поздно мы найдем место, где нормализованное значение упадет на единицу. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=hdd_smart_WearLevelingCount', 'host=~${host:regex}', 'cluster=$cluster', 'type=SSD', '_name=~${disk:regex}'), 'type', 'host', '_name', 'sn'), '.unix.tensor.ru', ''), '\\.', ' ')"
    }
   ]
  },
  {
   "title": "Число перезапусков диска",
   "type": "yesoreyeram-boomtable-panel",
   "description": "SMART Attr 12 Power_Cycle_Count",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=hdd_smart_PowerCycleCount', 'host=~${host:regex}', 'cluster=$cluster', 'type=SSD', '_name=~${disk:regex}'), 'type', 'host', '_name', 'sn'), '.unix.tensor.ru', ''), '\\.', ' ')"
    }
   ]
  },
  {
   "title": "Количество таймаутов при выполнении команд",
   "type": "yesoreyeram-boomtable-panel",
   "description": "* Command timeout - Количество таймаутов при выполнении команд",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=hdd_smart_CommandTimeout', 'host=~${host:regex}', 'cluster=$cluster', 'type=SSD', '_name=~${disk:regex}'), 'type', 'host', '_name', 'sn'), '.unix.tensor.ru', ''), '\\.', ' ')"
    }
   ]
  }
 ]
}