{
 "title": "СБИС Диск - Ceph  tiering level",
 "description": "Ответственный: Грошев А.Н. (Разработка)",
 "tags": [
  "sbisdisk",
  "ceph",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "servertype", "query": "ceph" },
   { "name": "contur", "query": "prod" },
   {
    "name": "cluster",
    "query": "tag_values(cluster,servertype=$servertype,contur=$contur)"
   },
   {
    "name": "host",
    "query": "tag_values(host,servertype=$servertype,contur=$contur,cluster=$cluster)"
   },
   {
    "name": "device_class",
    "query": "tag_values(device_class,servertype=$servertype,contur=$contur,cluster=$cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Promoution/eviction/flushing объектов (шт. в секунду)",
   "type": "graph",
   "description": "Объем перемещения объектов из холодного хранения в кэш и обратно. ",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sum(perSecond(seriesByTag('servertype=ceph', 'cluster=ceph-1', 'name=ceph_caches_stats', 'cache_type=tier_promote'))), 'promote')"
    },
    {
     "target": "alias(sum(perSecond(seriesByTag('servertype=ceph', 'cluster=ceph-1', 'name=ceph_caches_stats', 'cache_type=tier_evict'))), 'evict')"
    },
    {
     "target": "alias(sum(perSecond(seriesByTag('servertype=ceph', 'cluster=ceph-1', 'name=ceph_caches_stats', 'cache_type=tier_flush'))), 'flush')"
    }
   ]
  },
  {
   "title": "Попадение в TIER кэш содержимого объета (шт. в секунду)",
   "type": "graph",
   "description": "Процент попадания запроса в кэш",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sum(perSecond(seriesByTag('servertype=ceph', 'cluster=ceph-1', 'name=ceph_caches_stats', 'cache_type=object_ctx_cache_hit'))), 'hit')"
    },
    {
     "target": "alias(sum(perSecond(seriesByTag('servertype=ceph', 'cluster=ceph-1', 'name=ceph_caches_stats', 'cache_type=object_ctx_cache_total'))), 'total')"
    }
   ]
  },
  {
   "title": "Tier pools used bytes",
   "type": "graph",
   "description": "Объем кэша занимаемые пулами в байтах",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster=$cluster', 'pool_name=~.*tier', 'type_instance=bytes_used'), 'pool_name')"
    }
   ]
  },
  {
   "title": "Objects total",
   "type": "graph",
   "description": "Количество объектов.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('cluster=$cluster', 'pool_name=~.*tier', 'type_instance=objects'), 'pool_name'), '$', '.(total)')"
    }
   ]
  },
  {
   "title": "Pool write bytes",
   "type": "graph",
   "description": "Объем записи в кэш по пулам",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(derivative(seriesByTag('cluster=$cluster', 'pool_name=~.*tier', 'type_instance=wr_bytes')), 'pool_name')"
    }
   ]
  },
  {
   "title": "Pool read bytes",
   "type": "graph",
   "description": "Объем чтения их кэша по пулам",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(derivative(seriesByTag('cluster=$cluster', 'pool_name=~.*tier', 'type_instance=rd_bytes')), 'pool_name')"
    }
   ]
  },
  {
   "title": "Dirty objects",
   "type": "graph",
   "description": "Количество объектов.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('cluster=$cluster', 'pool_name=~.*tier', 'type_instance=dirty'), 'pool_name'), '$', '.(dirty)')"
    }
   ]
  }
 ]
}