{
 "title": "СБИС Диск - Swift cluster state",
 "description": "Ответственный: Грошев А.Н. (Разработка)",
 "tags": [
  "telegraf",
  "service",
  "swift",
  "sbisdisk"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "cluster",
    "query": "tag_values(cluster,servertype=swift,contur=$contur)"
   }
  ]
 },
 "panels": [
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total RPS",
   "type": "graph",
   "description": "Общее количество запросов в кластер",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "alias(scale(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_PUT_\\d+_timing.count', 'cluster=$cluster')), 0.1), 'PUT')"
    },
    {
     "target": "alias(scale(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_GET_\\d+_timing.count', 'cluster=$cluster')), 0.1), 'GET')"
    },
    {
     "target": "alias(scale(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_HEAD_\\d+_timing.count', 'cluster=$cluster')), 0.1), 'HEAD')"
    },
    {
     "target": "alias(scale(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_POST_\\d+_timing.count', 'cluster=$cluster')), 0.1), 'POST')"
    },
    {
     "target": "alias(scale(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_DELETE_\\d+_timing.count', 'cluster=$cluster')), 0.1), 'DELETE')"
    }
   ]
  },
  {
   "title": "Codes",
   "type": "graph",
   "description": "Статистика по кодам состояния запросов (HTTP CODE)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(sumSeriesWithWildcards(aliasSub(aliasByTags(seriesByTag('servertype=swift', 'name=~proxy-server_object_[^_]*_\\d+_timing.count', 'cluster=$cluster', 'interval=10s'), 'name'), 'proxy-server_object_[^_]*_(\\d+)_timing.count', '\\1'), 1), '\\D+(\\d+)\\D+', '\\1')"
    }
   ]
  },
  {
   "title": "Download/upload bytes per second",
   "type": "graph",
   "description": "Скорость загрузки/выгрузки байт в секунду",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(scale(sumSeries(summarize(seriesByTag('servertype=swift', 'name=~proxy-server_object_GET_\\d+_xfer', 'cluster=$cluster'), '10s', 'sum', false)), 0.1), 'download')"
    },
    {
     "target": "alias(scale(sumSeries(summarize(seriesByTag('servertype=swift', 'name=~proxy-server_object_PUT_\\d+_xfer', 'cluster=$cluster'), '10s', 'sum', false)), 0.1), 'upload')"
    }
   ]
  },
  {
   "title": "Средняя занятость дисков",
   "type": "gauge",
   "description": "Плохо когда более 90%, но т.к. дисков много не критично, совсем плохо когда 97-98%. Аккаунты и контейнеры бывает хранятся в одних и тех же дисках.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(averageSeries(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'name=system.disk.used_percent', 'path=~-srv-.*data.*')), 'Data devices')"
    },
    {
     "target": "alias(averageSeries(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'name=system.disk.used_percent', 'path=~-srv-.*acc.*')), 'Account devices')"
    },
    {
     "target": "alias(averageSeries(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'name=system.disk.used_percent', 'path=~-srv-.*cont.*')), 'Container devices')"
    },
    {
     "target": "alias(averageSeries(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'name=system.disk.used_percent', 'path=~-srv-.*meta.*')), 'Meta devices')"
    }
   ]
  },
  {
   "title": "GET first byte (latency)",
   "type": "graph",
   "description": "Время после завершения запроса и началом отдачи полезных данных. Важная!!!",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_GET_\\d+_first-byte_timing.sum', 'cluster=$cluster')), #A), 'first byte')",
     "targetFull": "alias(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_GET_\\d+_first-byte_timing.sum', 'cluster=$cluster')), sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_GET_\\d+_first-byte_timing.count', 'cluster=$cluster'))), 'first byte')"
    }
   ]
  },
  {
   "title": "GET duration",
   "type": "graph",
   "description": "Средняя полная продолжительность GET запросов и её перцентили. Плохо когда есть \"полочка\" 5 сек, 10 сек и т.п.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(sumSeries(seriesByTag('name=~proxy-server_object_GET_\\d+_timing.sum', 'cluster=$cluster', 'servertype=swift')), #A), 'Avg GET, ms')",
     "targetFull": "alias(divideSeries(sumSeries(seriesByTag('name=~proxy-server_object_GET_\\d+_timing.sum', 'cluster=$cluster', 'servertype=swift')), sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_GET_\\d+_timing.count', 'cluster=$cluster'))), 'Avg GET, ms')"
    },
    {
     "refCount": 1,
     "target": "alias(maxSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_GET_\\d+_timing.upper', 'cluster=$cluster')), 'MAX')"
    },
    {
     "refCount": 1,
     "target": "alias(maxSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_GET_\\d+_timing.50_percentile', 'cluster=$cluster')), '50%')"
    },
    {
     "refCount": 1,
     "target": "alias(maxSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_GET_\\d+_timing.99_percentile', 'cluster=$cluster')), '99%')"
    }
   ]
  },
  {
   "title": "PUT duration",
   "type": "graph",
   "description": "Средняя полная продолжительность PUT запросов и её перцентили. Плохо когда есть \"полочка\" 5 сек, 10 сек и т.п.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(scale(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_PUT_\\d+_timing.sum', 'cluster=$cluster')), #A), 0.1), 'Avg PUT ms')",
     "targetFull": "alias(scale(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_PUT_\\d+_timing.sum', 'cluster=$cluster')), alias(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_PUT_\\d+_timing.count', 'cluster=$cluster')), 'COUNT')), 0.1), 'Avg PUT ms')"
    },
    {
     "refCount": 1,
     "target": "alias(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_PUT_\\d+_timing.50_percentile', 'cluster=$cluster')), #A), '50%')",
     "targetFull": "alias(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_PUT_\\d+_timing.50_percentile', 'cluster=$cluster')), alias(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_PUT_\\d+_timing.count', 'cluster=$cluster')), 'COUNT')), '50%')"
    },
    {
     "refCount": 1,
     "target": "alias(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_PUT_\\d+_timing.99_percentile', 'cluster=$cluster')), #A), '99%')",
     "targetFull": "alias(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_PUT_\\d+_timing.99_percentile', 'cluster=$cluster')), alias(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_PUT_\\d+_timing.count', 'cluster=$cluster')), 'COUNT')), '99%')"
    },
    {
     "refCount": 2,
     "target": "alias(maxSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_PUT_\\d+_timing.upper', 'cluster=$cluster')), 'MAX')"
    }
   ]
  },
  {
   "title": "HEAD, duration",
   "type": "graph",
   "description": "Средняя продолжительность HEAD запросов. Плохо если есть \"полочка\" 5 сек, 10 сек....",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_HEAD_\\d+_timing.sum', 'cluster=$cluster', 'interval=10s')), #A), 'duration')",
     "targetFull": "alias(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_HEAD_\\d+_timing.sum', 'cluster=$cluster', 'interval=10s')), sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_HEAD_\\d+_timing.count', 'cluster=$cluster', 'interval=10s'))), 'duration')"
    }
   ]
  },
  {
   "title": "DELETE, duration",
   "type": "graph",
   "description": "Средняя продолжительность DELETE запросов. Плохо если есть \"полочка\" 5 сек, 10 сек....",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_DELETE_\\d+_timing.sum', 'cluster=$cluster', 'interval=10s')), #A), 'duration')",
     "targetFull": "alias(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_DELETE_\\d+_timing.sum', 'cluster=$cluster', 'interval=10s')), sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_object_DELETE_\\d+_timing.count', 'cluster=$cluster', 'interval=10s'))), 'duration')"
    }
   ]
  },
  { "title": "ACCOUNTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Codes account operations",
   "type": "graph",
   "description": "Коды по операциям с аккаунтами",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(sumSeriesWithWildcards(aliasSub(aliasByTags(seriesByTag('servertype=swift', 'name=~proxy-server_account_[^_]*_\\d+_timing.count', 'cluster=$cluster', 'interval=10s'), 'name'), 'proxy-server_account_[^_]*_(\\d+)_timing.count', '\\1'), 1), '\\D+(\\d+)\\D+', '\\1')"
    }
   ]
  },
  {
   "title": "Account operations, duration",
   "type": "graph",
   "description": "Продолжительность операций с аккаунтами",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(scale(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_account_[^_]*_\\d+_timing.sum', 'cluster=$cluster', 'interval=10s')), #A), 0.1), 'AVG, duration')",
     "targetFull": "alias(scale(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_account_[^_]*_\\d+_timing.sum', 'cluster=$cluster', 'interval=10s')), sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_account_[^_]*_\\d+_timing.count', 'cluster=$cluster', 'interval=10s'))), 0.1), 'AVG, duration')"
    }
   ]
  },
  { "title": "CONTAINERS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Codes container operations",
   "type": "graph",
   "description": "Коды операций с контейнерами",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(sumSeriesWithWildcards(aliasSub(aliasByTags(seriesByTag('servertype=swift', 'name=~proxy-server_container_[^_]*_\\d+_timing.count', 'cluster=$cluster', 'interval=10s'), 'name'), 'proxy-server_container_[^_]*_(\\d+)_timing.count', '\\1'), 1), '\\D+(\\d+)\\D+', '\\1')"
    }
   ]
  },
  {
   "title": "Container operations, duration",
   "type": "graph",
   "description": "Продолжительность запросов операций с контейнерами",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(scale(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_container_[^_]*_\\d+_timing.sum', 'cluster=$cluster', 'interval=10s')), #B), 0.1), 'AVG, duration')",
     "targetFull": "alias(scale(divideSeries(sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_container_[^_]*_\\d+_timing.sum', 'cluster=$cluster', 'interval=10s')), sumSeries(seriesByTag('servertype=swift', 'name=~proxy-server_container_[^_]*_\\d+_timing.count', 'cluster=$cluster', 'interval=10s'))), 0.1), 'AVG, duration')"
    }
   ]
  }
 ]
}