{
 "title": "СБИС Диск - Ceph clusters state",
 "description": "Обзор кластера Ceph. Ответственный: Грошев А.Н. (Разработка)",
 "tags": [
  "ceph",
  "telegraf",
  "service",
  "sbisdisk"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "tag_values(cluster,servertype=ceph)"
   }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Здоровье кластера",
   "type": "stat",
   "description": "Уровень здоровья кластера. 0 хорошо, 1 WARNING если дольше 10 минут надо выяснить причину. 2 ошибка - зовите взрослых.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_health_status{cluster=\"$cluster\"}",
     "target": "groupByTags(seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=health', 'cluster=$cluster'), 'max', 'type_instance')"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "description": "Средняя скорость записи в секунду",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{cluster=\"$cluster\"}[5m]))",
     "target": "sumSeries(perSecond(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_daemon_stats', 'type_instance=osd.op_w_in_bytes')))"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "description": "Средняя скорость чтения в секунду",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{cluster=\"$cluster\"}[5m]))",
     "target": "alias(sumSeries(perSecond(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_daemon_stats', 'type_instance=osd.op_r_out_bytes'))), 'Read')"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "description": "Суммарный объем дисков в кластере",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{cluster=\"$cluster\"}",
     "target": "seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=bytes_total', 'cluster=$cluster')"
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "description": "Очень примерный процент оставшегося свободного места в кластере",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes{cluster=\"$cluster\"}-ceph_cluster_total_used_bytes{cluster=\"$cluster\"})/ceph_cluster_total_bytes{cluster=\"$cluster\"}",
     "target": "asPercent(seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=bytes_avail', 'cluster=$cluster'), #A)",
     "targetFull": "asPercent(seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=bytes_avail', 'cluster=$cluster'), seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=bytes_total', 'cluster=$cluster'))"
    }
   ]
  },
  {
   "title": "Pacemaker fencing",
   "type": "timeseries",
   "description": "Ok (1) означает, что демон фенсинга проверил жертву и она ответила. Если не 1 значит демон фенсинга попытался убить жертву (reboot/off/on)",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster=${cluster:regex}', 'name=fencing.action'), 'victim')"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "description": "Количество объектов хранимых в кластере",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_objects{cluster=\"$cluster\"}",
     "target": "seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=num_objects', 'cluster=$cluster')"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "description": "IOPS на запись",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{cluster=\"$cluster\"}[5m]))",
     "target": "sumSeries(perSecond(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_w')))"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "description": "IOPS на чтение",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r{cluster=\"$cluster\"}[5m]))",
     "target": "sumSeries(perSecond(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_r')))"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "description": "Занято \"сырого\" места",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{cluster=\"$cluster\"}",
     "target": "seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=bytes_used', 'cluster=$cluster')"
    }
   ]
  },
  {
   "title": "Avg apply Latency (with queue)",
   "type": "graph",
   "description": "Средняя задержка с учетом очереди",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{cluster=\"$cluster\"})",
     "target": "alias(divideSeries(sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_latency'))), #B), 'Latency')",
     "targetFull": "alias(divideSeries(sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_latency'))), sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op')))), 'Latency')"
    }
   ]
  },
  {
   "title": "Mon Session Num",
   "type": "stat",
   "description": "Количество клиентов (демонов) сервиса MON. (все OSD + все MGR + все RGW + ...)",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_mon_num_sessions{cluster='$cluster'})",
     "target": "sumSeries(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=mon.num_sessions'))"
    }
   ]
  },
  {
   "title": "MON latency",
   "type": "stat",
   "description": "ЗАдержка в сервисе мониторов. Если он втупит - втупит всё.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(#A,#B)",
     "targetFull": "divideSeries(sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=paxos.refresh_latency'))),sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=paxos.refresh'))))"
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "stat",
   "description": "Объем данных записанный на все OSD с момента их перезапуска на текущий момент",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_op_w_in_bytes{cluster=\"$cluster\"})",
     "target": "sumSeries(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'type_instance=osd.op_w_in_bytes', 'cluster=$cluster'))"
    }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "stat",
   "description": "Объем данных прочитанный со всех OSD с момента их перезапуска на текущий момент",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_op_r_out_bytes{cluster=\"$cluster\"})",
     "target": "sumSeries(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'type_instance=osd.op_r_out_bytes', 'cluster=$cluster'))"
    }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "description": "Количество мониторов в кворуме.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_mon_quorum_status{cluster=\"$cluster\"})",
     "target": "diffSeries(sortByMaxima(seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'cluster=$cluster', 'type_instance=~mon_(quorum|outside_quorum)')))"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "description": "Изменение количества объктов в кластере",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_objects{cluster=\"$cluster\"}",
     "target": "seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=num_objects', 'cluster=$cluster')"
    }
   ]
  },
  {
   "title": "Avg  ops r/w latency",
   "type": "graph",
   "description": "Средняя задержка перезаписи",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum{cluster=\"$cluster\"}[5m])/rate(ceph_osd_op_r_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "target": "divideSeries(sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_rw_latency'))), #B)",
     "targetFull": "divideSeries(sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_rw_latency'))), sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_rw'))))"
    }
   ]
  },
  {
   "title": "Avg commit latency (w/o queue)",
   "type": "graph",
   "description": "Средняя задержка без учета очереди",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{cluster=\"$cluster\"})",
     "target": "alias(divideSeries(sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_process_latency'))), #D), 'Latency')",
     "targetFull": "alias(divideSeries(sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_process_latency'))), sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op')))), 'Latency')"
    }
   ]
  },
  {
   "title": "здоровье",
   "type": "graph",
   "description": "Уровень здоровья кластера. 0 хорошо, 1 WARNING если дольше 10 минут надо выяснить причину. 2 ошибка - зовите взрослых.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ceph_health_status{cluster=\"$cluster\"}",
     "target": "groupByTags(seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=health', 'cluster=$cluster'), 'max', 'type_instance')"
    }
   ]
  },
  {
   "title": "Avg ops write latency",
   "type": "graph",
   "description": "Средняя задержка операций записи ",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum{cluster=\"$cluster\"}[5m]) / rate(ceph_osd_op_w_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "target": "divideSeries(sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_w_latency'))), #B)",
     "targetFull": "divideSeries(sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_w_latency'))), sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_w'))))"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "description": "Суммарный IOPS",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_bytes_used{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}}",
     "target": "alias(sumSeries(perSecond(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_daemon_stats', 'type_instance=osd.op_r'))), 'Read')"
    },
    {
     "expr": "(ceph_pool_bytes_used{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}}",
     "target": "alias(sumSeries(perSecond(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_daemon_stats', 'type_instance=osd.op_w'))), 'Write')"
    },
    {
     "expr": "(ceph_pool_bytes_used{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}}",
     "target": "alias(sumSeries(perSecond(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_daemon_stats', 'type_instance=osd.op_rw'))), 'ReWrite')"
    }
   ]
  },
  {
   "title": "Avg ops read latency",
   "type": "graph",
   "description": "Средняя задержка операций чтения",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum{cluster=\"$cluster\"}[5m]) / rate(ceph_osd_op_w_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "target": "divideSeries(sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_r_latency'))), #B)",
     "targetFull": "divideSeries(sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_r_latency'))), sumSeries(derivative(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.op_r'))))"
    }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "description": "Количество дисков вне кластера. Плохо если есть постоянно.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{cluster=\"$cluster\"}) - count(ceph_osd_in{cluster=\"$cluster\"})",
     "target": "diffSeries(seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=~(num_osd_up|num_osd_in)', 'cluster=$cluster'))"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "description": "Количество не запущенных демонов OSd. Плохо если есть постоянно.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{cluster=\"$cluster\"} == 0.0) OR vector(0)",
     "target": "diffSeries(seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=~(num_osd_up|num_osd_in)', 'cluster=$cluster'))"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "description": "Общее количество дисков в кластере. (Часть может быть OUT или IN)",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_up{cluster=\"$cluster\"})",
     "target": "seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=num_osd_up', 'cluster=$cluster')"
    }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "description": "Количество РАБОТАЮЩИХ дисков в кластере. Лучший вариант когда UP==IN",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_in{cluster=\"$cluster\"})",
     "target": "seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=num_osd_in', 'cluster=$cluster')"
    }
   ]
  },
  {
   "title": "Avg PGs",
   "type": "stat",
   "description": "Среднее количество Placement group на OSD. Плохо когда > 200",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_numpg{cluster=\"$cluster\"})",
     "target": "averageSeries(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'cluster=$cluster', 'type_instance=osd.numpg', 'ceph_daemon=~osd*'))"
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Capacity",
   "type": "graph",
   "description": "Занятое, ипользовано и  всего места",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_bytes_used{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}}",
     "target": "alias(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_cluster_stats', 'type_instance=bytes_total'), 'Total')"
    },
    {
     "expr": "(ceph_pool_bytes_used{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}}",
     "target": "alias(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_cluster_stats', 'type_instance=bytes_used'), 'Used')"
    },
    {
     "expr": "(ceph_pool_bytes_used{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}}",
     "target": "alias(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_cluster_stats', 'type_instance=bytes_avail'), 'Avail')"
    }
   ]
  },
  {
   "title": "Pool RAW Used Bytes",
   "type": "graph",
   "description": "Относительный размер пулов.",
   "gridPos": { "h": 20, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_raw_bytes_used{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}}",
     "target": "aliasByTags(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_pool_stats', 'type_instance=stored_raw'), 'pool_name')"
    }
   ]
  },
  {
   "title": "Throutput",
   "type": "graph",
   "description": "Нагрузка на кластер чтение/запись байтов в секунду",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_bytes_used{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}}",
     "target": "alias(sumSeries(perSecond(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_daemon_stats', 'type_instance=osd.op_r_out_bytes'))), 'Read')"
    },
    {
     "expr": "(ceph_pool_bytes_used{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}}",
     "target": "alias(sumSeries(perSecond(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_daemon_stats', 'type_instance=osd.op_w_in_bytes'))), 'Write')"
    }
   ]
  },
  {
   "title": "Pool Used Bytes",
   "type": "graph",
   "description": "Занимаемое пулами место в байтах. Пустые не показыны.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_bytes_used{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}}",
     "target": "aliasByTags(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_pool_stats', 'type_instance=bytes_used'), 'pool_name')"
    }
   ]
  },
  {
   "title": "Objects Per Pool",
   "type": "graph",
   "description": "Относительное количество байт в пулах",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_objects{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}}",
     "target": "aliasByTags(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_pool_stats', 'type_instance=objects'), 'pool_name')"
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "description": "Общее количество объектов в кластере",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_cluster_total_objects{cluster=\"$cluster\"}",
     "legendFormat": "Total",
     "target": "seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=num_objects', 'cluster=$cluster')"
    }
   ]
  },
  {
   "title": "Objects in the Cluster (derivative)",
   "type": "graph",
   "description": "Динамика количества объектов в кластере",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_cluster_total_objects{cluster=\"$cluster\"}",
     "legendFormat": "Total",
     "target": "derivative(seriesByTag('servertype=ceph', 'name=ceph_cluster_stats', 'type_instance=num_objects', 'cluster=$cluster'))"
    }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "graph",
   "description": "Количество \"плохих\" состояний Palcement group. Плохо если долго не убывают. ",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_pg_degraded{cluster=\"$cluster\"}",
     "legendFormat": "Degraded",
     "target": "aliasSub(aliasByTags(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_cluster_stats', 'type_instance=num_pgs_degraded'), 'type_instance'), 'num_pgs_', '')"
    },
    {
     "expr": "ceph_pg_stale{cluster=\"$cluster\"}",
     "legendFormat": "Stale",
     "target": "aliasSub(aliasByTags(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_cluster_stats', 'type_instance=num_pgs_stale'), 'type_instance'), 'num_pgs_', '')"
    },
    {
     "expr": "ceph_pg_undersized{cluster=\"$cluster\"}",
     "legendFormat": "Undersized",
     "target": "aliasSub(aliasByTags(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_cluster_stats', 'type_instance=num_pgs_undersized'), 'type_instance'), 'num_pgs_', '')"
    }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "graph",
   "description": "Количество операций восстановления данных. Плохо если много, постоянно и не заканчиваются.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops{cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "OPS",
     "target": "perSecond(sumSeries(seriesByTag('servertype=ceph', 'name=ceph_daemon_stats', 'type_instance=osd.recovery_ops', 'cluster=$cluster')))"
    }
   ]
  },
  {
   "title": "PGs State",
   "type": "graph",
   "description": "Состояние Placement group. Идеальный вариант когда все active+clean. Scrubing - проверка. Deep - глубокая проверка.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(groupByTags(seriesByTag('servertype=ceph', 'cluster=$cluster', 'name=ceph_cluster_stats', 'type_instance=~num_pgs_*'), 'max', 'type_instance'), 'ceph_cluster_stats;type_instance=num_pgs_', '')"
    }
   ]
  }
 ]
}