{
 "title": "СБИС Диск - Ceph caches",
 "description": "Ответственный: Грошев А.Н. (Разработка)",
 "tags": [
  "sbisdisk",
  "ceph",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "servertype", "query": "ceph" },
   { "name": "contur", "query": "prod" },
   {
    "name": "cluster",
    "query": "tag_values(cluster,servertype=$servertype,contur=$contur)"
   },
   {
    "name": "host",
    "query": "tag_values(host,servertype=$servertype,contur=$contur,cluster=$cluster)"
   },
   {
    "name": "device_class",
    "query": "tag_values(device_class,servertype=$servertype,contur=$contur,cluster=$cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "RGW caches hit",
   "type": "graph",
   "description": "Попадение в кэш Rados gateway. Спереди стоит haproxy с балансировкой по хэшу URL поэтому каждый одинаковый URL приходит на конкретный Rados Gateway.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(derivative(seriesByTag('cluster=$cluster', 'type_instance=rgw.cache_hit', 'host=~${host:regex}', 'interval=60s')), 'ceph_daemon')"
    }
   ]
  },
  {
   "title": "RGW caches miss",
   "type": "graph",
   "description": "Промахи кэша на уровне Rados gateway.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(derivative(seriesByTag('cluster=$cluster', 'type_instance=rgw.cache_miss', 'host=~${host:regex}')), 'ceph_daemon')"
    }
   ]
  },
  {
   "title": "Оbject context cache (hit, delta)",
   "type": "graph",
   "description": "Попадение и промахи кэша содержимого объекта на уровне BlueStore",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(groupByTags(derivative(seriesByTag('cluster=$cluster', 'cache_type=object_ctx_cache_hit', 'device_class=~${device_class:regex}', 'host=~${host:regex}')), 'sum', 'cache_type'), 'hit')"
    },
    {
     "target": "alias(groupByTags(derivative(seriesByTag('cluster=$cluster', 'cache_type=object_ctx_cache_total', 'device_class=~${device_class:regex}', 'host=~${host:regex}')), 'sum', 'cache_type'), 'total')"
    }
   ]
  },
  {
   "title": "Всего выделено под кэши",
   "type": "graph",
   "description": "Глобальные кучи кэшей.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(groupByTags(seriesByTag('cluster=$cluster', 'device_class=~${device_class:regex}', 'host=~${host:regex}', 'type_instance=~prioritycache:data.committed_bytes', 'contur=${contur:regex}', 'name=ceph_daemon_stats'), 'sum', 'type_instance'), 'data (Obj content)')"
    },
    {
     "target": "alias(groupByTags(seriesByTag('cluster=$cluster', 'device_class=~${device_class:regex}', 'host=~${host:regex}', 'type_instance=~prioritycache:meta.committed_bytes', 'contur=${contur:regex}', 'name=ceph_daemon_stats'), 'sum', 'type_instance'), 'metadata')"
    },
    {
     "target": "alias(groupByTags(seriesByTag('cluster=$cluster', 'device_class=~${device_class:regex}', 'host=~${host:regex}', 'type_instance=~prioritycache:kv.committed_bytes', 'contur=${contur:regex}', 'name=ceph_daemon_stats'), 'sum', 'type_instance'), 'key value(RocksDB cache)')"
    }
   ]
  },
  {
   "title": "Bluestore cache data bytes",
   "type": "graph",
   "description": "Объемы кэшей BlueStore под данные на OSD",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster=$cluster', 'cache_type=bluestore_cache_data_bytes', 'device_class=~${device_class:regex}', 'host=~${host:regex}'), 'ceph_daemon')"
    }
   ]
  },
  {
   "title": "Bluestore cache data items",
   "type": "graph",
   "description": "Количество объектов в кэше BlueStore на OSD",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster=$cluster', 'cache_type=bluestore_cache_data_items', 'device_class=~${device_class:regex}', 'host=~${host:regex}'), 'ceph_daemon')"
    }
   ]
  },
  {
   "title": "Bluestore cache onode bytes",
   "type": "graph",
   "description": "Объем кэша BlueStore занятый под onode на каждом OSD. В onode хранится вся метаинформация об объекте. Если соедержимое объекта малое (до 4kB) оно может храниться здесь же.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster=$cluster', 'cache_type=bluestore_cache_onode_bytes', 'device_class=~${device_class:regex}', 'host=~${host:regex}'), 'ceph_daemon')"
    }
   ]
  },
  {
   "title": "Bluestore cache onode items",
   "type": "graph",
   "description": "Количество onode в кэше BlueStore на каждом OSD . В onode хранится вся метаинформация об объекте. Если соедержимое объекта малое (до 4kB) оно может храниться здесь же.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster=$cluster', 'cache_type=bluestore_cache_onode_items', 'device_class=~${device_class:regex}', 'host=~${host:regex}'), 'ceph_daemon')"
    }
   ]
  },
  {
   "title": "Bluestore cache other bytes",
   "type": "graph",
   "description": "Прочие кэши BlueStore",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster=$cluster', 'cache_type=bluestore_cache_other_bytes', 'device_class=~${device_class:regex}', 'host=~${host:regex}'), 'ceph_daemon')"
    }
   ]
  },
  {
   "title": "Bluestore cache other items",
   "type": "graph",
   "description": "Количество закэшированный итемов",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster=$cluster', 'cache_type=bluestore_cache_other_items', 'device_class=~${device_class:regex}', 'host=~${host:regex}'), 'ceph_daemon')"
    }
   ]
  },
  {
   "title": "Bluestore buffer (hit, miss, bytes, delta)",
   "type": "graph",
   "description": "Попадение в буфер BlueStore",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(groupByTags(derivative(aliasByTags(seriesByTag('cluster=$cluster', 'cache_type=bluestore_buffer_hit_bytes', 'device_class=~${device_class:regex}', 'host=~${host:regex}', 'interval=60s'), 'ceph_daemon')), 'sum', 'cache_type'), 'hit')"
    },
    {
     "target": "alias(groupByTags(derivative(aliasByTags(seriesByTag('cluster=$cluster', 'cache_type=bluestore_buffer_miss_bytes', 'device_class=~${device_class:regex}', 'host=~${host:regex}', 'interval=60s'), 'ceph_daemon')), 'sum', 'cache_type'), 'miss')"
    }
   ]
  },
  {
   "title": "Bluestore onode (hit, miss, delta)",
   "type": "graph",
   "description": "Попадение в кэш onode",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(groupByTags(derivative(aliasByTags(seriesByTag('cluster=$cluster', 'cache_type=bluestore_onode_hits', 'device_class=~${device_class:regex}', 'host=~${host:regex}'), 'ceph_daemon')), 'sum', 'cache_type'), 'hit')"
    },
    {
     "target": "alias(groupByTags(derivative(aliasByTags(seriesByTag('cluster=$cluster', 'cache_type=bluestore_onode_misses', 'device_class=~${device_class:regex}', 'host=~${host:regex}'), 'ceph_daemon')), 'sum', 'cache_type'), 'miss')"
    }
   ]
  }
 ]
}