{
 "title": "СБИС Диск - ceph systemd units states",
 "description": "Ответственный: Грошев А.Н. (Разработка)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "systemd units graphincs",
   "type": "timeseries",
   "description": "Ok(0) - юнит запущен, остальное плохо",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('cluster=ceph-1', 'name=systemd_units.active_code', '_name=~(corosync|pacemaker|haproxy|pcsd)'), 'host', '_name'), 0, 4)"
    }
   ]
  },
  {
   "title": "systemd units (in table)",
   "type": "table",
   "gridPos": { "h": 32, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "seriesByTag('cluster=ceph-1', 'name=systemd_units.active_code', '_name=~(pcsd|pacemaker|haproxy|corosync)')"
    }
   ]
  },
  {
   "title": "Pacemaker fencing",
   "type": "timeseries",
   "description": "Ok (1) означает, что демон фенсинга проверил жертву и она ответила. Если не 1 значит демон фенсинга попытался убить жертву (reboot/off/on)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster=ceph-1', 'name=fencing.action'), 'victim')"
    }
   ]
  }
 ]
}