{
 "title": "СБИС Диск - FileLoader проверки",
 "description": "Ответственный:  Прикладной мониторинг сервиса fileloader. Данные из админки сервиса. Баулин С.А. (Эксплуатация), Куйкин Д.К. (Разработка)",
 "tags": [
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Сессии загрузки – в обработке (высокий приоритет)",
   "type": "graph",
   "description": "Сессии загрузки – в обработке (высокий приоритет)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=high.wait_count_grouping'), 'item')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=high.queue_count_all'), 'item')"
    }
   ]
  },
  {
   "title": "Сессии загрузки – в обработке (низкий приоритет)",
   "type": "graph",
   "description": "Сессии загрузки – в обработке (низкий приоритет)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=low.wait_count_grouping'), 'item')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=low.queue_count_all'), 'item')"
    }
   ]
  },
  {
   "title": "Загрузки LRS (высокий приоритет)",
   "type": "graph",
   "description": "Загрузки LRS (высокий приоритет)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "exclude(aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=~high.lrs_count.*'), 'item'), 'all')"
    }
   ]
  },
  {
   "title": "Загрузки LRS (низкий приоритет)",
   "type": "graph",
   "description": "Загрузки LRS (низкий приоритет)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "exclude(aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=~low.lrs_count.*'), 'item'), 'all')"
    }
   ]
  },
  {
   "title": "Сессии загрузки – очередь (состояние)",
   "type": "graph",
   "description": "Сессии загрузки – очередь (состояние)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "exclude(aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=~queue_count.*'), 'item'), 'err|all')"
    }
   ]
  },
  {
   "title": "Сессии загрузки – очередь (ошибки)",
   "type": "graph",
   "description": "Сессии загрузки – очередь (ошибки)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=~queue_count.*error$'), 'item')"
    }
   ]
  },
  {
   "title": "Сессии загрузки – обработка завершена за 1 мин",
   "type": "graph",
   "description": "Сессии загрузки – обработка завершена за 1 мин",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=~processed_count_(error|success)_1m'), 'item')"
    }
   ]
  },
  {
   "title": "Сессии загрузки – поступило в обработку за 1 мин",
   "type": "graph",
   "description": "Сессии загрузки – поступило в обработку за 1 мин",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=input_count_all_1m'), 'item')"
    }
   ]
  },
  {
   "title": "Группы серверов – число методов БЛ",
   "type": "graph",
   "description": "Группы серверов – число методов БЛ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.unit', 'subsystem=fileloader', 'item=~.*'), 'item')"
    }
   ]
  },
  {
   "title": "Методы БЛ – общее количество",
   "type": "graph",
   "description": "Методы БЛ – общее количество",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.method', 'subsystem=fileloader', 'item=count_all'), 'item')"
    }
   ]
  },
  {
   "title": "Сессии загрузки - очередь (высокий приоритет)",
   "type": "graph",
   "description": "Сессии загрузки - очередь (высокий приоритет)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "exclude(aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=~high.queue_count.*'), 'item'), 'err|all')"
    }
   ]
  },
  {
   "title": "Сессии загрузки - очередь (низкий приоритет)",
   "type": "graph",
   "description": "Сессии загрузки - очередь (низкий приоритет)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "exclude(aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=~low.queue_count.*'), 'item'), 'err|all')"
    }
   ]
  },
  {
   "title": "Сессии загрузки – ожидают (высокий приоритет)",
   "type": "graph",
   "description": "Сессии загрузки – ожидают (высокий приоритет)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=high.queue_count_ready'), 'item')"
    }
   ]
  },
  {
   "title": "Сессии загрузки – ожидают (низкий приоритет)",
   "type": "graph",
   "description": "Сессии загрузки – ожидают (низкий приоритет)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=low.queue_count_ready'), 'item')"
    }
   ]
  },
  {
   "title": "Сессии загрузки – в обработке",
   "type": "graph",
   "description": "Сессии загрузки – в обработке",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=~(wait_count_grouping|queue_count_all)'), 'item')"
    }
   ]
  },
  {
   "title": "Сессии загрузки – время обработки",
   "type": "graph",
   "description": "Сессии загрузки – время обработки",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=~processing_time_\\d\\dp_1m'), 'item')"
    }
   ]
  },
  {
   "title": "Группы сессий загрузки",
   "type": "graph",
   "description": "Группы сессий загрузки",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.session_group', 'subsystem=fileloader', 'item=~.*'), 'item')"
    }
   ]
  },
  {
   "title": "Сессии загрузки – заполняются",
   "type": "graph",
   "description": "Сессии загрузки – заполняются",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=fileloader.count.session', 'subsystem=fileloader', 'item=~(high|low).sheduler_count_filling'), 'item')"
    }
   ]
  }
 ]
}