{
 "title": "СБИС Диск - Filestorage SWIFT GET-cache",
 "description": "Ответственный: Ледяев И.К. (Эксплуатация)",
 "tags": [
  "sbisdisk",
  "exploitation",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Сервер",
    "query": "tag_values(host,subsystem=filestorage)"
   }
  ]
 },
 "panels": [
  { "title": "$server GET-cache responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "Filestorage SWIFT GET-cache responses",
   "type": "graph",
   "description": "Статистика get-кэширования file-storage для маленьких и средних файлов",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name!=~get.cache.ratio', 'subsystem=filestorage', 'filesize=~[small,mid]', 'host=$server'), 'name', 'filesize'), 'get.cache.', '')"
    }
   ]
  },
  {
   "title": "Filestorage SWIFT GET-cache responses (big files)",
   "type": "graph",
   "description": "Статистика get-кэширования file-storage для больших файлов",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name!=~get.cache.ratio', 'subsystem=filestorage', 'filesize=big', 'host=$server'), 'name', 'filesize'), 'get.cache.', '')"
    }
   ]
  },
  { "title": "$server GET-cache ratio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "server" },
  {
   "title": "Filestorage SWIFT GET-cache ratio",
   "type": "graph",
   "description": "Процент попадания в кэш для маленьких и средних файлов",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=get.cache.ratio', 'subsystem=filestorage', 'filesize=~[small,mid]', 'host=$server'), 'name', 'filesize'), 'get.cache.', '')"
    }
   ]
  },
  {
   "title": "Filestorage SWIFT GET-cache ratio (big files)",
   "type": "graph",
   "description": "Процент попадания в кэш для больших файлов",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=get.cache.ratio', 'subsystem=filestorage', 'filesize=big', 'host=$server'), 'name', 'filesize'), 'get.cache.', '')"
    }
   ]
  }
 ]
}