{
 "title": "СБИС Диск - Проверки",
 "description": "Ответственный: Ледяев И.К. (Эксплуатация)",
 "tags": [
  "sbisdisk",
  "exploitation",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Проверка загрузки в хранилища СбисДиск",
   "type": "graph",
   "description": "Время загрузки тестового файла в объектные хранилища (через сайт и напрямую на БЛ)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=upload.time', 'subsystem=filestorage'), 'storage', 'disp'), 'True', 'disp'), 'False', 'no.disp')"
    }
   ]
  },
  {
   "title": "Проверка получения из хранилища СбисДиск",
   "type": "graph",
   "description": "Время скачивания тестового файла из объектных хранилищ (через сайт и напрямую с БЛ)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=download.time', 'subsystem=filestorage'), 'storage', 'disp'), 'True', 'disp'), 'False', 'no.disp')"
    }
   ]
  },
  {
   "title": "Очередь изменений DB_OBJECT",
   "type": "graph",
   "description": "Очередь изменений в БД объектов СБИСДиска",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=sbisdisk', 'queue=data_change', 'db=~.*'), 'db')"
    }
   ]
  },
  {
   "title": "Очередь изменений DB_OBJECT (задержка)",
   "type": "graph",
   "description": "Задержка очереди изменений в БД объектов СБИСДиска",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=sbisdisk', 'queue=data_change', 'db=~.*'),  'db')"
    }
   ]
  },
  {
   "title": "Очередь индексации для поиска DB_OBJECT",
   "type": "graph",
   "description": "Очередь индексации в БД объектов СБИСДиска",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=sbisdisk', 'queue=search_queue', 'db=~.*'), 'db')"
    }
   ]
  },
  {
   "title": "Очередь индексации для поиска DB_OBJECT (задержка)",
   "type": "graph",
   "description": "Задержка очереди индексации для поиска в БД объектов СБИСДиска",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=sbisdisk', 'queue=search_queue', 'db=~.*'), 'db')"
    }
   ]
  },
  {
   "title": "Очередь подсчёта размеров папок DB_OBJECT",
   "type": "graph",
   "description": "Очередь подсчёта размеров папок в БД объектов СБИСДиска",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=sbisdisk', 'queue=children_sum', 'db=~.*'), 'db')"
    }
   ]
  },
  {
   "title": "Очередь подсчёта размеров папок DB_OBJECT (задержка)",
   "type": "graph",
   "description": "Задержка очереди подсчёта размеров папок в БД объектов СБИСДиска",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=sbisdisk', 'queue=children_sum', 'db=~.*'), 'db')"
    }
   ]
  },
  {
   "title": "Очередь удаляемых версий DB_VERSION",
   "type": "graph",
   "description": "Очередь удаляемых версий в БД версий СБИСДиска",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=sbisdisk', 'queue=del_version', 'db=~.*'), 'db')"
    }
   ]
  },
  {
   "title": "Очередь удаляемых версий DB_VERSION (задержка)",
   "type": "graph",
   "description": "Задержка очереди удаляемых версий в БД версий СБИСДиска",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=sbisdisk', 'queue=del_version', 'db=~.*'), 'db')"
    }
   ]
  },
  {
   "title": "Очередь очистки временных файлов DB_OBJECT (задержка)",
   "type": "graph",
   "description": "Задержка очереди очистки временных файлов в БД объектов СБИСДиска",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=sbisdisk', 'queue=temp_file_delete', 'db=~.*'), 'db')"
    }
   ]
  },
  {
   "title": "Очередь удаляемых файлов DB_OBJECT (задержка)",
   "type": "graph",
   "description": "Задержка очереди удаляемых файлов в БД объектов СБИСДиска",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=sbisdisk', 'queue=del_file', 'db=~.*'), 'db')"
    }
   ]
  },
  {
   "title": "Очередь удаления подписей DB_OBJECT (задержка)",
   "type": "graph",
   "description": "Задержка очереди удаления подписей в БД объектов СБИСДиска",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=sbisdisk', 'queue=del_sign', 'db=~.*'), 'db')"
    }
   ]
  },
  {
   "title": "Очередь удаления записей \"Со мной поделились\" DB_OBJECT (задержка)",
   "type": "graph",
   "description": "Задержка очереди удаления записей \"Со мной поделились\" в БД объектов СБИСДиска",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=sbisdisk', 'queue=shared_me_file_delete', 'db=~.*'), 'db')"
    }
   ]
  }
 ]
}