{
 "title": "СБИС Диск - Swift/ceph enclosures (полки)",
 "description": "Ответственный: Грошев А.Н. (Разработка)",
 "tags": [
  "sbisdisk",
  "telegraf",
  "swift",
  "ceph",
  "service"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "cluster",
    "query": "tag_values(cluster,contur=$contur)"
   },
   {
    "name": "host",
    "query": "tag_values(host,cluster=$cluster,servertype=~(swift|ceph))"
   },
   {
    "name": "device_id",
    "label": "SAS Device",
    "query": "tag_values(device_id,host=$host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Состояния сенсоров",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Состояние дополнительных датчиков полки. Собирается через sg_ses. Статусы так же берутся с полки.",
   "gridPos": { "h": 24, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=enclosure', 'cluster=$cluster', 'host=$host', 'sensor_type=status', 'interval=600s', 'device_id=$device_id'), 'sensor_name'), '_', ' ')"
    }
   ]
  },
  {
   "title": "Напряжение, V",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Состояние сенсоров напряжения. Описание, статусы и значения - всё берется с полки через sg_ses",
   "gridPos": { "h": 21, "w": 4, "x": 7, "y": 0 },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=enclosure', 'cluster=$cluster', 'host=$host', 'sensor_type=voltage', 'interval=600s', 'device_id=$device_id'), 'sensor_type', 'sensor_name'), '_', ' ')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=enclosure', 'cluster=$cluster', 'host=$host', 'sensor_type=status-voltage', 'interval=600s', 'device_id=$device_id'), 'sensor_type', 'sensor_name'), '_', ' ')"
    }
   ]
  },
  {
   "title": "Ток, A",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Состояние датчиков тока. Описание, статус и значение беретсяс полки через sg_Ses",
   "gridPos": { "h": 21, "w": 4, "x": 11, "y": 0 },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=enclosure', 'cluster=$cluster', 'host=$host', 'sensor_type=current', 'interval=600s', 'device_id=$device_id'), 'sensor_type', 'sensor_name'), '_', ' ')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=enclosure', 'cluster=$cluster', 'host=$host', 'sensor_type=status-current', 'interval=600s', 'device_id=$device_id'), 'sensor_type', 'sensor_name'), '_', ' ')"
    }
   ]
  },
  {
   "title": "Температура, °C",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Состояние датчиков температуры. Описание, статус и значение беретсяс полки через sg_ses",
   "gridPos": { "h": 21, "w": 4, "x": 15, "y": 0 },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=enclosure', 'cluster=$cluster', 'host=$host', 'sensor_type=temperature', 'interval=600s', 'device_id=$device_id'), 'sensor_type', 'sensor_name'), '_', ' ')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=enclosure', 'cluster=$cluster', 'host=$host', 'sensor_type=status-temperature', 'interval=600s', 'device_id=$device_id'), 'sensor_type', 'sensor_name'), '_', ' ')"
    }
   ]
  },
  {
   "title": "Охлаждение, RPS",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Состояние системы охлаждения полки.",
   "gridPos": { "h": 21, "w": 4, "x": 19, "y": 0 },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=enclosure', 'cluster=$cluster', 'host=$host', 'sensor_type=cooling', 'interval=600s', 'device_id=$device_id'), 'sensor_type', 'sensor_name'), '_', ' ')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=enclosure', 'cluster=$cluster', 'host=$host', 'sensor_type=status-cooling', 'interval=600s', 'device_id=$device_id'), 'sensor_type', 'sensor_name'), '_', ' ')"
    }
   ]
  }
 ]
}