{
 "title": "Сервисы ЭДО - edi.sbis.ru",
 "description": "Сервис EDI - сервис, обеспечивающий интеграцию организаций, работающих в парадигме EDI с OSR и другими сервисами. Ответственный: Смирнов К.В. (Эксплуатация)",
 "tags": [
  "edi.sbis.ru",
  "ftp",
  "EDIConnect",
  "service",
  "scripts",
  "telegraf"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Ошибки подключения к FTP edi.sbis.ru",
   "type": "graph",
   "description": "Проверка подключения к ftp edi.sbis.ru ",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=EDIConnect.ftp_connection_errors'), 'name')"
    }
   ]
  },
  {
   "title": "Ошибки подключения к FTP  \"edi.sbis.ru\" снаружи",
   "type": "graph",
   "description": "Проверка подключения к ftp edi.sbis.ru с внешнего сервера ",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByTags(aliasByTags(seriesByTag('name=ftp_checkout.ftp_connect_error'), 'name'), 'min', 'server')"
    }
   ]
  },
  {
   "title": " Файлы на FTP ",
   "type": "graph",
   "description": "Список фалов ожидающих обработки в FTP хранилищах, в том числе и меньше 10 минут.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=EDIConnect', 'contur=prod', 'script=edi_heartbeat_checkoldfiles.py', 'name=edi_files_count'), 'name')"
    }
   ]
  },
  {
   "title": "Задачи сервиса",
   "type": "graph",
   "description": "Список задач ожидающих обработки сервисом EDIConnect, в том числе и менее 10 минут",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=EDIConnect', 'contur=prod', 'script=edi_heartbeat_getunprocessedfiles.py', 'name=edi_tasks_count'), 'name')"
    }
   ]
  },
  {
   "title": "Количество ошибок выгрузки в сбербанк за вчера",
   "type": "graph",
   "description": "Количество ошибок выгрузки в сбербанк за вчера",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=sber_stat_errors_last_day', 'contur=prod'), 'name')"
    }
   ]
  },
  {
   "title": "Ошибка при отправке JMS X5",
   "type": "graph",
   "description": "Проверка наличия не обработанных сообщений edi x5.",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(seriesByTag('service=EDIConnect', 'contur=prod', 'script=edi_jms_x5_check.py')), 'Наличие не отправленных сообщений торговой сети X5')"
    }
   ]
  },
  {
   "title": "Запись/чтение на FTP",
   "type": "stat",
   "description": "Проверка на запись/чтение в папках ftp edi.sbis.ru",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=EDIConnect', 'contur=prod', 'script=edi_ftp-write_check.py', 'organization=~.*'), 'organization')"
    }
   ]
  },
  {
   "title": "Файлы на FTP старше 12 часов",
   "type": "graph",
   "description": "Файлы на ftp edi.sbis.ru с временем изменения более 12 часов",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=EDIConnect', 'contur=prod', 'script=edi_ftp-oldfiles_count.py', 'organization=~.*'), 'organization')"
    }
   ]
  },
  {
   "title": "Новые документы",
   "type": "graph",
   "description": "Данные по новым документам на ftp edi.sbis.ru по \"основным организациям\"",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(seriesByTag('service=EDIConnect', 'contur=prod', 'script=edi_ftp_stat.py'), 'company'))"
    }
   ]
  },
  {
   "title": "Квоты для ftp edi.sbis.ru",
   "type": "graph",
   "description": "Статистика по квотам для клиентов на ftp edi.sbis.ru",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=EDIConnect', 'contur=prod', 'objectname=ftpquotas', 'host=csr-edi-ftp1', 'servertype=ftpclient'), 'client')"
    }
   ]
  },
  {
   "title": "Проверка доступности sftp edi.sbis.ru",
   "type": "graph",
   "description": "Проверка доступности sftp edi.sbis.ru",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=EDIConnect', 'script=edi_sftp.py'), 'name')"
    }
   ]
  }
 ]
}