{
 "title": "Сервисы визуализации",
 "description": "Прикладной мониторинг сервисов визуализации. Ответственный: Баулин С.А. (Эксплуатация), Стадник А.В. (Разработка)",
 "tags": [
  "service",
  "scripts",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "tag_values(host,service=office-convert-win, contur=prod, name=~.*_time)"
   }
  ]
 },
 "panels": [
  {
   "title": "Word time",
   "type": "graph",
   "description": "Время конвертации word документа на сервисе office_convert_win",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=office-convert-win', 'name=word_time', 'host=~${host:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "Excel time",
   "type": "graph",
   "description": "Время конвертации excel документа на сервисе office_convert_win",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=office-convert-win', 'name=excel_time', 'host=~${host:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "Onlyoffice open time",
   "type": "graph",
   "description": "Время открытия документа в onlyoffice через интерфейс",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=onlyoffice', 'name=open_time'), 'host')"
    }
   ]
  },
  {
   "title": "Webapps open time",
   "type": "graph",
   "description": "Время открытия документа в webapps через интерфейс",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=webapps', 'name=open_time', 'script=monitoring.py'), 'host')"
    }
   ]
  },
  {
   "title": "Webapps open time",
   "type": "graph",
   "description": "Время открытия документа на ферме webapps",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('service=~(convert|webapps_preview|webapps_print)', 'script=monitoring1.py', 'name=webapps.queue'), 'service', 'host')"
    },
    {
     "target": "aliasByTags(transformNull(seriesByTag('name=open_time', 'script=monitoring1.py', 'service=webapps'), -1), 'host')"
    }
   ]
  }
 ]
}