{
 "title": "Сервисы sbis-geoserver-bl01 и sbis-geoserver-bl02",
 "description": "Формирование и отдача картографических файлов. Ответственный: Сорокин И.А. (Эксплуатация), Сизов П.А. (Разработка)",
 "tags": [
  "service",
  "sbis3mon",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "LA для sbis_geoserver",
   "type": "graph",
   "description": "LA на серверах сервиса sbis-geoserver",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~sbis-geoserver-bl0[1-2].unix.tensor.ru', 'name=system.system.load1'), 'host')"
    }
   ]
  },
  {
   "title": "Доступность раздела /opt/gwc",
   "type": "graph",
   "description": "Доступность раздела /opt/gwc примонтированного к серверам сервиса sbis-geosever",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(transformNull(seriesByTag('host=~sbis-geoserver-bl0[1-2].unix.tensor.ru', 'name=system.disk.used_percent', 'path=-opt-gwc'), -1), 'host', 'path')"
    }
   ]
  },
  {
   "title": "sbis-geoserver-bl01: storage.vdb.busy",
   "type": "graph",
   "description": "Активность использования раздела /opt/gwc на сервере sbis-geoserver-bl01",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl01.interval-30sec.storage.busy.vdb.avg, -4, -2, -3)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl01.interval-30sec.storage.queue.vdb.avg, -4, -2, -3)"
    }
   ]
  },
  {
   "title": "sbis-geoserver-bl01: storage.vdb.bps",
   "type": "graph",
   "description": "Операции чтения/записи на  разделе /opt/gwc на сервере sbis-geoserver-bl01",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl01.interval-30sec.storage.io.bps.vdb.read.avg, -6, -3, -4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl01.interval-30sec.storage.io.bps.vdb.write.avg, -6, -3, -4, -2)"
    }
   ]
  },
  {
   "title": "sbis-geoserver-bl01: storage.vdb.lag",
   "type": "graph",
   "description": "Лаг на диске /opt/gwc",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl01.interval-30sec.storage.lag.vdb.await.avg, -4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl01.interval-30sec.storage.lag.vdb.svctm.avg, -4, -2)"
    }
   ]
  },
  {
   "title": "sbis-geoserver-bl01: storage.vdb.ops",
   "type": "graph",
   "description": "Запросов (в сек ) на чтение, запись",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl01.interval-30sec.storage.io.rps.vdb.read.avg, -4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl01.interval-30sec.storage.io.rps.vdb.write.avg, -4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl01.interval-30sec.storage.io.rps.merged.vdb.read.avg, -4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl01.interval-30sec.storage.io.rps.merged.vdb.write.avg, -4, -2)"
    }
   ]
  },
  {
   "title": "sbis-geoserver-bl02: storage.vdb.busy",
   "type": "graph",
   "description": "Активность использования раздела /opt/gwc на сервере sbis-geoserver-bl02",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl02.interval-30sec.storage.busy.vdb.avg, -4, -2, -3)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl02.interval-30sec.storage.queue.vdb.avg, -4, -2, -3)"
    }
   ]
  },
  {
   "title": "sbis-geoserver-bl02: storage.vdb.bps",
   "type": "graph",
   "description": "Операции чтения/записи на  разделе /opt/gwc на сервере sbis-geoserver-bl02",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl02.interval-30sec.storage.io.bps.vdb.read.avg, -6, -3, -5, -4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl02.interval-30sec.storage.io.bps.vdb.write.avg, -6, -3, -5, -4, -2)"
    }
   ]
  },
  {
   "title": "sbis-geoserver-bl02: storage.vdb.lag",
   "type": "graph",
   "description": "Лаг на диске /opt/gwc",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl01.interval-30sec.storage.lag.vdb.await.avg, -4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl01.interval-30sec.storage.lag.vdb.svctm.avg, -4, -2)"
    }
   ]
  },
  {
   "title": "sbis-geoserver-bl02: storage.vdb.ops",
   "type": "graph",
   "description": "Запросов (в сек ) на чтение, запись",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl02.interval-30sec.storage.io.rps.vdb.read.avg, -4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl02.interval-30sec.storage.io.rps.vdb.write.avg, -4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl02.interval-30sec.storage.io.rps.merged.vdb.read.avg, -4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.sbis-geoserver-bl02.interval-30sec.storage.io.rps.merged.vdb.write.avg, -4, -2)"
    }
   ]
  },
  {
   "title": "Использование раздела / opt/gwc/ ",
   "type": "graph",
   "description": "Сколько места свободно (занято) на разделе /opt/gwc",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~sbis-geoserver-bl0[1,2].unix.tensor.ru', 'name=system.disk.used_percent', 'path=-opt-gwc'), 'host', 'path')"
    }
   ]
  }
 ]
}