{
 "title": "Сервисы ЭДО - EDIconnect",
 "description": "Ответственный: Смирнов К.В. (Эксплуатация)",
 "tags": [
  "EDIConnect",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Ping ActiveMQ",
   "type": "graph",
   "description": "При значении меньше 1 недоступен брокер ActiveMQ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servicetype=EDIConnect', 'contur=prod', 'host=activemq-bl.unix.tensor.ru', 'name=ediconnect.ping_activemq'), 'host')"
    }
   ]
  },
  {
   "title": "Task period timeout",
   "type": "graph",
   "description": "Длительное отсутствие задач от X5 при значении больше 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servicetype=EDIConnect', 'contur=prod', 'host=csr-edi-app1.unix.tensor.ru', 'name=ediconnect.task_period_timeout'), 'host')"
    }
   ]
  },
  {
   "title": "Транспортный коллапс в сервисе EDI",
   "type": "graph",
   "description": "Определение транспортного коллапса в сервисе EDI\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(groupByTags(seriesByTag('service=EDIConnect', 'script=edi_service_check.py', 'contur=prod', 'name=blockdetected'), 'max', 'name'), 'BlockDetected')"
    }
   ]
  }
 ]
}