{
 "title": "Сервис dwc",
 "description": "Сервис, способный выполнять распределенные сценарии, контролировать нагрузку на сервисы. Ответственный: Баулин С.А. (Эксплуатация), Бойцов Е. (Разработка).",
 "tags": [
  "service",
  "telegraf",
  "dwc"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Method time exceeded",
   "type": "timeseries",
   "description": "Превышено среднее допустимое время работы служебных методов ( Workflow.OnTaskDone, WOrkflow.OnTaskFailed)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=method_time_exceeded', 'contur=prod', 'servicetype=dwc'), 'contur', 'name')"
    }
   ]
  },
  {
   "title": "Launch queue size",
   "type": "timeseries",
   "description": "Сервис dwc не справляется с потоком сценариев",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=launch_queue_size', 'contur=prod', 'servicetype=dwc'), 'contur', 'name')"
    }
   ]
  },
  {
   "title": "Problematic classes by total",
   "type": "timeseries",
   "description": "Есть простаивающие сценарии",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=problematic_classes_by_total_downtime', 'contur=prod', 'servicetype=dwc'), 'contur', 'name')"
    }
   ]
  },
  {
   "title": "Problematic classes by own downtime",
   "type": "timeseries",
   "description": "Есть простаивающие сценарии",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=problematic_classes_by_own_downtime', 'contur=prod', 'servicetype=dwc'), 'contur', 'name')"
    }
   ]
  },
  {
   "title": "Problematic classes by amount",
   "type": "timeseries",
   "description": "Есть простаивающие сценарии",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=problematic_classes_by_amount', 'contur=prod', 'servicetype=dwc'), 'contur', 'name')"
    }
   ]
  }
 ]
}