{
 "title": "Сервис сверки",
 "description": "Ответственный: Сорокин И.А. (Эксплуатация)",
 "tags": [
  "service",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Использование процессора БД",
   "type": "graph",
   "description": "Использование процессора (cpu busy) на серверах БД",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.core.csr-collation-db*-1.*.cpu.busy.avg, 4)"
    }
   ]
  },
  {
   "title": "Использование процессора БЛ",
   "type": "graph",
   "description": "Использование процессора (cpu busy) на серверах БЛ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.core.osr-*collation*.*.cpu.busy.avg, 4)"
    }
   ]
  },
  {
   "title": "Использование диска с БД",
   "type": "graph",
   "description": "Использование диска (storage busy) на серверах БД",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.csr-collation-db*-1.*.storage.busy.sdb.avg, 4)"
    }
   ]
  },
  {
   "title": "Свободно памяти на БЛ",
   "type": "graph",
   "description": "Размер свободной памяти (memory free) на серверах БЛ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.memory.osr-*collation*.*.mem.ram.free.avg, 4)"
    }
   ]
  }
 ]
}