{
 "title": "Сервисы уведомлений-socnet-aggregation",
 "description": "Ответственный: Сорокин И.А. (Эксплуатация)",
 "tags": [
  "service",
  "scripts"
 ],
 "time": { "from": "now-5h", "to": "now" },
 "panels": [
  {
   "title": "Максимальная задержка обработки сообщений",
   "type": "graph",
   "description": "Максимальная задержка обработки сообщений с детализацией по очередям.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasByTags(seriesByTag('name=~.*._msg_delay', 'contur=prod', 'service=socnet-aggregation', 'interval=30s'), 'name'), 'incoming_msg_delay', 'Входящие сообщения'), 'by_doc_msg_delay', 'Письма по документам'), 'personal_msg_delay', 'Личные письма'), 'tech_supp_mail_msg_delay', 'Письма в рамках функционала ТП'), 'tech_supp_nonmail_msg_delay', 'Непочтовые сообщения в рамках функционала ТП')"
    }
   ]
  },
  {
   "title": "Максимальная задержка опроса почтовых каналов",
   "type": "graph",
   "description": "Максимальная задержка опроса почтовых каналов в доменах Тензора, быстрых и медленных.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=~email_poll_.*._max_delay', 'contur=prod', 'service=socnet-aggregation', 'interval=30s'), 'name'), 'email_poll_', ''), '_max_delay', '')"
    }
   ]
  },
  {
   "title": "Очередь сообщений socnet-aggregation",
   "type": "graph",
   "description": "Показывает  очередь сообщений socnet-aggregation. Критично если очередь > 10000. Метод: MessageGetQueueLens",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(seriesByTag('name=queue.size', 'subsystem=socnet-aggregation', 'method=MessageGetQueueLens', 'contur=prod'))"
    }
   ]
  },
  {
   "title": "Очередь почтовых каналов",
   "type": "graph",
   "description": "Очередь почтовых каналов, опрос в доменах Тензора, быстрых и медленных. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=~email_poll_.*._count', 'contur=prod', 'service=socnet-aggregation', 'interval=30s'), 'name'), 'email_poll_', ''), '_count', '')"
    }
   ]
  },
  {
   "title": "Количество доставленных за день почтовых сообщений",
   "type": "graph",
   "description": "Проверка числа писем отправленных с общего Sbis ящика для рассылок",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=DeliveredTodayEmailsCount', 'contur=prod'), 'Emails')"
    }
   ]
  }
 ]
}