{
 "title": "Сервисы связи: sms transport",
 "description": "Сервис smsc_service. Ответственный: Карпов С.В. (Эксплуатация), Суханов А.А. (Разработка)",
 "tags": [
  "smsc",
  "mv.konuhov",
  "service",
  "scripts"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Доступность SMPP service",
   "type": "graph",
   "description": "Проверяется по IP:port. 1 - ок. Меньше 0 - проблема. Работает через VPN peer.\nСкрипт https://adm-git.tensor.ru/exp/monitoring-scripts/smsc/-/tree/master/scripts",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=sms.transport.monitoring', 'script=sms_transport_monitoring.py', 'contur=prod', 'provider_name=~.*SMPP.*'), 'host', 'port', 'provider_name')"
    }
   ]
  },
  {
   "title": "Доступность VPN peer",
   "type": "graph",
   "description": "Проверка идет командой ping. Выше 0 - ок. Ниже - проблема.\nСкрипт https://adm-git.tensor.ru/exp/monitoring-scripts/smsc/-/tree/master/scripts",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=sms.transport.monitoring', 'script=sms_transport_monitoring.py', 'contur=prod', 'provider_name=~.*VPN.*'), 'host', 'provider_name')"
    }
   ]
  },
  {
   "title": "Доступность HTTP service",
   "type": "graph",
   "description": "Проверяется по IP:port. 1 - ок. Меньше 0 - проблема.\nСкрипт https://adm-git.tensor.ru/exp/monitoring-scripts/smsc/-/tree/master/scripts",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=sms.transport.monitoring', 'script=sms_transport_monitoring.py', 'contur=prod', 'provider_name=~.*HTTP.*'), 'host', 'port', 'provider_name')"
    }
   ]
  },
  {
   "title": "Статистика отправленных сообщений за сутки",
   "type": "graph",
   "description": "Всего отправлено сообщений по разным источникам за текущий день по разным направлениям\nДанные скрипта, снимается 1 раз в час.\nСкрипт https://adm-git.tensor.ru/exp/monitoring-scripts/smsc/-/tree/master/scripts",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('script=sms_counter_monitoring.py', 'type=~.*', 'contur=prod', 'name=message.count', 'service=smsc_service'), 'type', 'route')"
    }
   ]
  }
 ]
}