{
 "title": "Торги - Autotests / tender_robot (status)",
 "description": "Ответственный: Сорокин И.А. (Эксплуатация)",
 "tags": [
  "tender_tests",
  "service",
  "scripts",
  "tender"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "robot",
    "label": "Имя робота",
    "query": "tag_values(robot_name,name=tender-robots.autotests)"
   },
   {
    "name": "testname",
    "label": "Имя теста",
    "query": "tag_values(test_name,name=tender-robots.autotests, robot_name=~${robot:regex})"
   },
   { "name": "min_status", "label": "Минимальный статус", "query": "40, 30, 20, 10" },
   { "name": "max_status", "label": "Максмальный статус", "query": "40, 30, 20, 10" }
  ]
 },
 "panels": [
  {
   "title": "ВСЕГО ЗА ПЕРИОД",
   "type": "stat",
   "description": "Кол-во автотестов за период",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(seriesByTag('name=tender-robots.autotests', 'robot_name=~${robot:regex}', 'test_name=~${testname:regex}'))"
    }
   ]
  },
  {
   "title": "НЕУДАЧА",
   "type": "stat",
   "description": "Сколько автотестов не прошло за период",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(currentBelow(currentAbove(seriesByTag('name=tender-robots.autotests', 'robot_name=~${robot:regex}', 'test_name=~${testname:regex}'), 40), 40))"
    }
   ]
  },
  {
   "title": "ОШИБКА",
   "type": "stat",
   "description": "Кол-во ошибок при проведении автотестов за период",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(currentBelow(currentAbove(seriesByTag('name=tender-robots.autotests', 'robot_name=~${robot:regex}', 'test_name=~${testname:regex}'), 30), 30))"
    }
   ]
  },
  {
   "title": "ПРОПУЩЕН",
   "type": "stat",
   "description": "Пропущено автотестов за период",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(currentBelow(currentAbove(seriesByTag('name=tender-robots.autotests', 'robot_name=~${robot:regex}', 'test_name=~${testname:regex}'), 20), 20))"
    }
   ]
  },
  {
   "title": "УСПЕХ",
   "type": "stat",
   "description": "Успешных автотестов за период",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(currentBelow(currentAbove(seriesByTag('name=tender-robots.autotests', 'robot_name=~${robot:regex}', 'test_name=~${testname:regex}'), 10), 10))"
    }
   ]
  },
  {
   "title": "ОТОБРАНО",
   "type": "stat",
   "description": "Отобрано автотестов за период",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(currentBelow(currentAbove(seriesByTag('name=tender-robots.autotests', 'robot_name=~${robot:regex}', 'test_name=~${testname:regex}'), $min_status), $max_status))"
    }
   ]
  },
  {
   "title": "Статус теста",
   "type": "table-old",
   "description": "Показывает результаты последнего выполнения автотестов по роботам",
   "gridPos": { "h": 30, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "target": "currentAbove(currentBelow(aliasByTags(seriesByTag('name=tender-robots.autotests', 'robot_name=~${robot:regex}', 'test_name=~${testname:regex}'), 'robot_name', 'test_name', 'test_id'), $max_status), $min_status)"
    }
   ]
  }
 ]
}