{
 "title": "Торги - Очереди задач ZGR",
 "description": "Ответственный: Сорокин И.А. (Эксплуатация)",
 "tags": [
  "service",
  "scripts",
  "tender"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "stand", "label": "Стенд", "query": "prod" }
  ]
 },
 "panels": [
  {
   "title": "zgr44http: Task44FZ",
   "type": "graph",
   "description": "Дашборд с графиками очередей роботов ЕИС",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgr44http', 'kind=ZgrHttp44.Task44FZ', 'sub_metric=all'), 'max'), 'Всего')"
    },
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgr44http', 'kind=ZgrHttp44.Task44FZ', 'sub_metric=active', 'interval=600s'), 'max'), 'Активных')"
    },
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgr44http', 'kind=ZgrHttp44.Task44FZ', 'sub_metric=errors'), 'max'), 'С ошибками')"
    }
   ]
  },
  {
   "title": "zgr223http: ЗагрузчикТоргов223.Tender",
   "type": "graph",
   "description": "Дашборд с графиками очередей роботов ЕИС",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgr223http', 'kind=ЗагрузчикТоргов223.Tender', 'sub_metric=all'), 'max'), 'Всего')"
    },
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgr223http', 'kind=ЗагрузчикТоргов223.Tender', 'sub_metric=active', 'interval=600s'), 'max'), 'Активных')"
    },
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgr223http', 'kind=ЗагрузчикТоргов223.Tender', 'sub_metric=errors'), 'max'), 'С ошибками')"
    }
   ]
  },
  {
   "title": "DocumentLoader.Document",
   "type": "graph",
   "description": "Дашборд с графиками очередей роботов ЕИС",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-docs', 'kind=DocumentLoader.Document', 'sub_metric=all'), 'max'), 'Всего')"
    },
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-docs', 'kind=DocumentLoader.Document', 'sub_metric=active', 'interval=600s'), 'max'), 'Активных')"
    },
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-docs', 'kind=DocumentLoader.Document', 'sub_metric=errors'), 'max'), 'С ошибками')"
    }
   ]
  },
  {
   "title": "zgr44ftp: Tender + Download44Archive + Download44ContractArchive",
   "type": "graph",
   "description": "Дашборд с графиками очередей роботов ЕИС",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgr44ftp', 'kind=Zgr44FTP.Tender', 'sub_metric=all'), 'max'), 'Tender.Total')"
    },
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgr44ftp', 'kind=Zgr44FTP.Download44Archive', 'sub_metric=all'), 'max'), 'Download44Archive.Total')"
    },
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgr44ftp', 'kind=Zgr44FTP.Download44ContractArchive', 'sub_metric=all'), 'max'), 'Download44ContractArchive.Total')"
    }
   ]
  },
  {
   "title": "zgr223ftp: Tender + Archive",
   "type": "graph",
   "description": "Дашборд с графиками очередей роботов ЕИС",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgr223ftp', 'kind=ZakupkiGovRuFTP223Loader.Tender', 'sub_metric=all'), 'max'), 'Tender.Total')"
    },
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgr223ftp', 'kind=ZakupkiGovRuFTP223Loader.Archive', 'sub_metric=all'), 'max'), 'Archive.Total')"
    }
   ]
  },
  {
   "title": "zgr223ftp.Tender223Http + zgr44ftp.TenderHttp",
   "type": "graph",
   "description": "Дашборд с графиками очередей роботов ЕИС",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgr223ftp', 'kind=ZakupkiGovRuFTP223Loader.Tender223Http', 'sub_metric=all'), 'max'), 'Tender223Http.Total')"
    },
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgr44ftp', 'kind=Zgr44FTP.TenderHttp', 'sub_metric=all'), 'max'), 'TenderHttp.Total')"
    }
   ]
  },
  {
   "title": "zgrplan: Plan44 + DownloadPlan44",
   "type": "graph",
   "description": "Дашборд с графиками очередей роботов ЕИС",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgrplan', 'kind=PlanZakupkiFTPLoader.Plan44', 'sub_metric=all'), 'max'), 'Plan44.Total')"
    },
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgrplan', 'kind=PlanZakupkiFTPLoader.DownloadPlan44', 'sub_metric=all'), 'max'), 'DownloadPlan44.Total')"
    }
   ]
  },
  {
   "title": "zgrplan: Plan 223 + DownloadPlan223",
   "type": "graph",
   "description": "Дашборд с графиками очередей роботов ЕИС",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgrplan223', 'kind=PlanZakupkiFTPLoader.Plan223', 'sub_metric=all'), 'max'), 'Plan223.Total')"
    },
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgrplan223', 'kind=PlanZakupkiFTPLoader.DownloadPlan223', 'sub_metric=all'), 'max'), 'DownloadPlan223.Total')"
    }
   ]
  },
  {
   "title": "zgrplan: Plan44_2020 + Download44Plan2020",
   "type": "graph",
   "description": "Дашборд с графиками очередей роботов ЕИС",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgrplan', 'kind=PlanZakupkiFTPLoader.Plan44_2020', 'sub_metric=all'), 'max'), 'Plan44_2020.Total')"
    },
    {
     "target": "alias(consolidateBy(seriesByTag('name=tender-robots.QTasksCount', 'contur=${stand:regex}', 'robot=tender-robot-zgrplan', 'kind=PlanZakupkiFTPLoader.Download44Plan2020', 'sub_metric=all'), 'max'), 'Download44Plan2020.Total')"
    }
   ]
  }
 ]
}