{
 "title": "Торги - Сводная статистика робота",
 "description": "Ответственный: Сорокин И.А. (Эксплуатация)",
 "tags": [
  "service",
  "scripts",
  "tender"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "robot",
    "label": "Робот",
    "query": "tag_values(robot, name=tender-robots.RobotsActivity, contur=$stand)"
   },
   { "name": "stand", "label": "Стенд", "query": "prod" }
  ]
 },
 "panels": [
  {
   "title": "Выполнение задач",
   "type": "graph",
   "description": "Позволяет оценить общее состояние по конкретному роботу. В данном случае -выполнение роботом задач",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(cumulative(sum(summarize(seriesByTag('name=tender-robots.RobotQTask', 'contur=${stand:regex}', 'robot=$robot', 'sub_metric=created'), '1h', 'sum', false))), 'created')"
    },
    {
     "target": "alias(cumulative(sum(summarize(seriesByTag('name=tender-robots.RobotQTask', 'contur=${stand:regex}', 'robot=$robot', 'sub_metric=delayed'), '1h', 'sum', false))), 'delayed')"
    },
    {
     "target": "alias(cumulative(sum(summarize(seriesByTag('name=tender-robots.RobotQTask', 'contur=${stand:regex}', 'robot=$robot', 'sub_metric=warning'), '1h', 'sum', false))), 'warning')"
    },
    {
     "target": "alias(cumulative(sum(summarize(seriesByTag('name=tender-robots.RobotQTask', 'contur=${stand:regex}', 'robot=$robot', 'sub_metric=error'), '1h', 'sum', false))), 'error')"
    },
    {
     "target": "alias(cumulative(sum(summarize(seriesByTag('name=tender-robots.RobotQTask', 'contur=${stand:regex}', 'robot=$robot', 'sub_metric=cancelled'), '1h', 'sum', false))), 'cancelled')"
    },
    {
     "target": "alias(cumulative(sum(summarize(seriesByTag('name=tender-robots.RobotQTask', 'contur=${stand:regex}', 'robot=$robot', 'sub_metric=repeated'), '1h', 'sum', false))), 'repeated')"
    },
    {
     "target": "alias(cumulative(sum(summarize(seriesByTag('name=tender-robots.RobotQTask', 'contur=${stand:regex}', 'robot=$robot', 'sub_metric=done'), '1h', 'sum', false))), 'done')"
    }
   ]
  },
  {
   "title": "Последний торг загружен",
   "type": "stat",
   "description": "Когда был загружен роботом последний торг с источника",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "consolidateBy(seriesByTag('name=tender-robots.RobotsActivity', 'contur=${stand:regex}', 'event=NewTender', 'robot=$robot', 'sub_metric=date'), 'last')"
    }
   ]
  },
  {
   "title": "Последний торг обновлен",
   "type": "stat",
   "description": "Когда был обновлен последний торг на онлайне",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "consolidateBy(seriesByTag('name=tender-robots.RobotsActivity', 'contur=${stand:regex}', 'event=UpdateTender', 'robot=$robot', 'sub_metric=date'), 'last')"
    }
   ]
  },
  {
   "title": "Необработанных исключений за период",
   "type": "stat",
   "description": "Кол-во ошибок при загрузке",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "cumulative(sum(seriesByTag('name=tender-robots.RobotQTask', 'contur=${stand:regex}', 'robot=$robot', 'sub_metric=error')))"
    }
   ]
  },
  {
   "title": "Обработанных исключений за период",
   "type": "stat",
   "description": "Кол-во обработанных ошибок за период",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "cumulative(sum(seriesByTag('name=tender-robots.RobotQTask', 'contur=${stand:regex}', 'robot=$robot', 'sub_metric=warning')))"
    }
   ]
  },
  {
   "title": "Автотестов пройдено (%)",
   "type": "stat",
   "description": "Статистика по автотестам робота за период",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(divideSeries(#A, #B), 100)",
     "targetFull": "scale(divideSeries(countSeries(currentBelow(currentAbove(consolidateBy(summarize(seriesByTag('name=tender-robots.autotests', 'robot_name=$robot'), '6h', 'last', false), 'last'), 10), 10)), countSeries(consolidateBy(summarize(seriesByTag('name=tender-robots.autotests', 'robot_name=$robot'), '6h', 'last', false), 'last'))), 100)"
    }
   ]
  },
  {
   "title": "Динамика ошибок",
   "type": "graph",
   "description": "Позволяет оценить общее состояние по конкретному роботу. В данном случае -число ошибок при выполнении задач роботом за указанный период времени",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(cumulative(sum(summarize(seriesByTag('name=tender-robots.RobotQTask', 'contur=${stand:regex}', 'robot=$robot', 'sub_metric=error'), '1h', 'sum', false))), 'error_line')"
    },
    {
     "target": "alias(cumulative(sum(summarize(seriesByTag('name=tender-robots.RobotQTask', 'contur=${stand:regex}', 'robot=$robot', 'sub_metric=delayed'), '1h', 'sum', false))), 'delayed_line')"
    },
    {
     "target": "alias(cumulative(sum(summarize(seriesByTag('name=tender-robots.RobotQTask', 'contur=${stand:regex}', 'robot=~${robots:regex}', 'kind=~${kinds:regex}', 'sub_metric=warning'), '$step', 'sum', false))), 'warning_line')"
    }
   ]
  },
  {
   "title": "Самое частое исключение за выбранный период",
   "type": "stat",
   "description": "Самая частая ошибка за указанный период",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasSub(aliasByTags(highestAverage(cumulative(transformNull(seriesByTag('name=tender-robots.RobotQTaskException', 'contur=${stand:regex}', 'robot=$robot')))), 'exception'), '_p_', '.'), '_s_', ';'), '\\xa0', ' ')"
    }
   ]
  }
 ]
}