{
 "title": "Торги - Tender-robots",
 "description": "Ответственный: Сорокин И.А. (Эксплуатация)",
 "tags": [
  "service",
  "tender",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" }
  ]
 },
 "panels": [
  {
   "title": "Необработанные",
   "type": "graph",
   "description": "Показывает значения различных служебных очередей бизнес-логики торгов",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(consolidateBy(seriesByTag('contur=${contur:regex}', 'name=postgresql.unprocessed', 'worker_name!='), 'last'), 'worker_name'), true, false)"
    }
   ]
  },
  {
   "title": "Обрабатываемые",
   "type": "graph",
   "description": "Показывает значения различных служебных очередей бизнес-логики торгов",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=postgresql.in_processing', 'worker_name!=', 'contur=${contur:regex}'), 'last'), 'worker_name')"
    }
   ]
  },
  {
   "title": "Задержка",
   "type": "graph",
   "description": "Показывает значения различных служебных очередей бизнес-логики торгов",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=postgresql.lag_time', 'worker_name!=', 'contur=${contur:regex}'), 'last'), 'worker_name')"
    }
   ]
  }
 ]
}