{
 "title": "Инциденты \"Эксплуатация ЦОД\"",
 "description": "Ответственный: -",
 "tags": [
  "bosun",
  "инциденты",
  "service",
  "scripts"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Ошибки облака",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sum(exclude(keepLastValue(maximumAbove(seriesByTag('name=errors', 'subsystem=cloud.sbis.ru', 'source=cloud', 'contur=prod'), 1), 10), 'FNS.transport.OFD'))"
    }
   ]
  },
  {
   "title": "Критические ошибки",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=errors.critical', 'source=redis', 'contur=prod')"
    }
   ]
  },
  {
   "title": "Рабочие очереди",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(highestCurrent(currentAbove(seriesByTag('name=queue.size', 'subsystem=cloud.sbis.ru', 'type=work', 'host!=~.+', 'contur=prod'), 1), 10), 'service')"
    }
   ]
  },
  {
   "title": "Инциденты",
   "type": "bosun-grafana7-panel",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "requestFilter": "filter=hasTag:vision=*exp*" }
   ]
  },
  {
   "title": "Ошибки облака",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(keepLastValue(highestMax(maximumAbove(seriesByTag('name=errors', 'subsystem=cloud.sbis.ru', 'source=cloud', 'contur=prod'), 1), 5), 10), 'service')"
    }
   ]
  },
  {
   "title": "Использование cpu vcenter",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(highestMax(seriesByTag('cpu=instance-total', 'contur=prod', 'name=service.vcenter.usage_average', 'interval=20s', 'vcenter=~(s076vc50|vc-cloud).corp.tensor.ru'), 3), 'esxhostname'), 0)"
    }
   ]
  },
  {
   "title": "Служебные очереди",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(highestCurrent(currentAbove(seriesByTag('name=queue.size', 'subsystem=cloud.sbis.ru', 'type=special', 'host!=~.+', 'contur=prod'), 1), 10), 'service')"
    }
   ]
  },
  {
   "title": "Использование памяти vcenter",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByTags(highestCurrent(seriesByTag('vmname!=~*', 'cpu!=~*', 'name=service.vcenter.usage_average', 'vcenter=~(s076vc50|vc-cloud).corp.tensor.ru', 'interface!=~*'), 3), 'esxhostname')"
    }
   ]
  },
  {
   "title": "Задержки чтения СХД",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByTags(highestCurrent(seriesByTag('dsname=~.*vstor|VSTOR', 'name=service.vcenter.totalReadLatency_average', 'vcenter=~(s076vc50|vc-cloud).corp.tensor.ru'), 3), 'dsname')"
    }
   ]
  },
  {
   "title": "Асинхронные очереди",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(currentAbove(seriesByTag('name=async.queue.size', 'subsystem=cloud.sbis.ru', 'contur=prod'), 1), 'service')"
    }
   ]
  },
  {
   "title": "Задержки записи СХД",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByTags(highestCurrent(seriesByTag('dsname=~.*vstor|VSTOR', 'name=service.vcenter.totalWriteLatency_average', 'vcenter=~(s076vc50|vc-cloud).corp.tensor.ru'), 3), 'dsname')"
    }
   ]
  }
 ]
}