{
 "title": "Инциденты СПД",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "инциденты",
  "bosun",
  "telegraf",
  "service"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Провайдеры: состояние",
   "type": "stat",
   "description": "Отображается суммарно состояние BGP-сессии и успешный пинг шлюза.\nСсылка на дашборд на имени провайдера",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(multiplySeriesLists(sortByName(aliasByTags(seriesByTag('device=dts-r1-border', 'name=bgp.peer.state', 'type=isp', '_name!=~.*ipv6'), '_name'), false), #C), '_name')",
     "targetFull": "aliasByTags(multiplySeriesLists(sortByName(aliasByTags(seriesByTag('device=dts-r1-border', 'name=bgp.peer.state', 'type=isp', '_name!=~.*ipv6'), '_name'), false), sortByName(aliasByTags(seriesByTag('device=dts-r2-border', 'name=bgp.peer.state', 'type=isp'), '_name'), false)), '_name')"
    }
   ]
  },
  {
   "title": "Провайдеры: входящий трафик %",
   "type": "bargauge",
   "description": "Входящий трафик в % от выделенной провайдером полосы.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByTags(divideSeriesLists(sortByName(scale(seriesByTag('device=dts-r1-border', 'name=interface.traffic.in_octets_rate', 'type=isp'), 800), false), #B), 'description')",
     "targetFull": "aliasByTags(divideSeriesLists(sortByName(scale(seriesByTag('device=dts-r1-border', 'name=interface.traffic.in_octets_rate', 'type=isp'), 800), false), aliasByTags(sortByName(groupByTags(scale(seriesByTag('device=~dts-r\\d-border', 'name=interface.traffic.speed', 'type=isp'), 1000000), 'max', 'description'), false), 'description')), 'description')"
    }
   ]
  },
  {
   "title": "Провайдеры: исходящий трафик %",
   "type": "bargauge",
   "description": "Исходящий трафик в % от выделенной провайдером полосы.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByTags(divideSeriesLists(sortByName(scale(seriesByTag('device=dts-r1-border', 'name=interface.traffic.out_octets_rate', 'type=isp'), 800), false), #B), 'description')",
     "targetFull": "aliasByTags(divideSeriesLists(sortByName(scale(seriesByTag('device=dts-r1-border', 'name=interface.traffic.out_octets_rate', 'type=isp'), 800), false), aliasByTags(sortByName(groupByTags(scale(seriesByTag('device=~dts-r\\d-border', 'name=interface.traffic.speed', 'type=isp'), 1000000), 'max', 'description'), false), 'description')), 'description')"
    }
   ]
  },
  {
   "title": "Инциденты",
   "type": "bosun-grafana7-panel",
   "description": "Список активных инцидентов по СПД ЦОД",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "requestFilter": "filter=hasTag:vision=spd" }
   ]
  },
  {
   "title": "dts-fw1-ea1: трафик",
   "type": "graph",
   "description": "Трафик на внешнем интерфейсе на основном МСЭ между продуктивным ЦОД и интернет\n!!! Добавить линк",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(scale(seriesByTag('device=dts-fw1-ea1', 'interface=outside', 'name=~interface\\.traffic\\.(in|out)_octets_rate'), 8), '^.*(in|out)_octets.*$', '\\1')"
    }
   ]
  },
  {
   "title": "dts-fw1-ea1: соединения",
   "type": "graph",
   "description": "Количество активных соединений на основном МСЭ между продуктивным ЦОД и интернет",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('device=dts-fw1-ea1', 'name=system.conn.value'), 'connections')"
    }
   ]
  },
  {
   "title": "dts-fw1-ea1: новые соединения",
   "type": "graph",
   "description": "Количество новых соединений в секунду на основном МСЭ между продуктивным ЦОД и интернет",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('device=dts-fw1-ea1', 'name=system.connrate.value'), 'new conn per second')"
    }
   ]
  },
  {
   "title": "ea1-dts-lb1: трафик",
   "type": "graph",
   "description": "Трафик на основном балансировщике",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(scale(perSecond(seriesByTag('host=ea1-dts-lb1-fo.unix.tensor.ru', 'interface=bond0', 'name=~system.net.bytes_(recv|sent)')), 8), 'name'), '^.*(recv|sent).*$', '\\1')"
    }
   ]
  },
  {
   "title": "ea1-dts-lb1: соединения",
   "type": "graph",
   "description": "Количество активных соединений на основном балансировщике\n!!! Нужно завести метрику общего количества коннекций. Суммирование идет тяжело и обрывается на графике",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(seriesByTag('host=ea1-dts-lb1-fo.unix.tensor.ru', 'name=system.ipvs.active_connections', 'virtual_address!=')), 'connections')"
    }
   ]
  },
  {
   "title": "ea1-dts-lb1: новые соединения",
   "type": "graph",
   "description": "Количество новых соединений в секунду на основном балансировщике",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(seriesByTag('host=ea1-dts-lb1-fo.unix.tensor.ru', 'name=system.ipvs.cps', 'virtual_address!=')), 'new conn per second')"
    }
   ]
  },
  {
   "title": "dts-lb1: трафик",
   "type": "graph",
   "description": "Трафик на балансировщике PSR",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(scale(perSecond(seriesByTag('host=dts-lb1.unix.tensor.ru', 'interface=bond0', 'name=~system.net.bytes_(recv|sent)')), 8), 'name'), '^.*(recv|sent).*$', '\\1')"
    }
   ]
  },
  {
   "title": "dts-lb1: соединения",
   "type": "graph",
   "description": "Количество активных соединений на балансировщике PSR",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(seriesByTag('host=dts-lb1.unix.tensor.ru', 'name=system.ipvs.active_connections', 'virtual_address!=')), 'connections')"
    }
   ]
  },
  {
   "title": "dts-lb1: новые соединения",
   "type": "graph",
   "description": "Количество новых соединений в секунду на балансировщике PSR",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(seriesByTag('host=dts-lb1.unix.tensor.ru', 'name=system.ipvs.cps', 'virtual_address!=')), 'new conn per second')"
    }
   ]
  },
  {
   "title": "dts-fw1-dev: трафик",
   "type": "graph",
   "description": "Трафик на внешнем интерфейсе на основном МСЭ между ЦОД разработки и интернет",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(scale(seriesByTag('device=dts-fw1-dev', 'interface=outside', 'name=~interface\\.traffic\\.(in|out)_octets_rate'), 8), '^.*(in|out)_octets.*$', '\\1')"
    }
   ]
  },
  {
   "title": "dts-fw1-dev: соединения",
   "type": "graph",
   "description": "Количество активных соединений на основном МСЭ между ЦОД разработки и интернет",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('device=dts-fw1-dev', 'name=system.conn.value'), 'connections')"
    }
   ]
  },
  {
   "title": "dts-fw1-dev: новые соединения",
   "type": "graph",
   "description": "Количество новых соединений в секунду на основном МСЭ между ЦОД разработки и интернет",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('device=dts-fw1-dev', 'name=system.connrate.value'), 'new conn per second')"
    }
   ]
  },
  {
   "title": "PROD: CPU",
   "type": "table",
   "description": "Топ 5 сетевых устройств сегмента PROD с наибольшей нагрузкой на CPU (в %).",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "aliasByTags(highestCurrent(seriesByTag('device=~dts-(sw|fw).*-ea1.*', 'name=system.cpu.usage_1m'), 5), 'device')"
    }
   ]
  },
  {
   "title": "PROD: Memory",
   "type": "table",
   "description": "Топ 5 сетевых устройств сегмента PROD с наибольшей нагрузкой на RAM (в %).",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 18 },
   "targets": [
    {
     "target": "aliasByTags(highestCurrent(seriesByTag('device=~dts-(sw|fw).*-ea1.*', 'name=system.mem.util'), 5), 'device')"
    }
   ]
  },
  {
   "title": "DEV: CPU",
   "type": "table",
   "description": "Топ 5 сетевых устройств сегмента DEV с наибольшей нагрузкой на CPU (в %).",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 18 },
   "targets": [
    {
     "target": "aliasByTags(highestCurrent(seriesByTag('device=~dts-(sw|fw).*-(dev|fix).*', 'name=system.cpu.usage_1m'), 5), 'device')"
    }
   ]
  },
  {
   "title": "DEV: Memory",
   "type": "table",
   "description": "Топ 5 сетевых устройств сегмента DEV с наибольшей нагрузкой на RAM (в %).",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 18 },
   "targets": [
    {
     "target": "aliasByTags(highestCurrent(seriesByTag('device=~dts-(sw|fw).*-(dev|fix).*', 'name=system.mem.util'), 5), 'device')"
    }
   ]
  },
  {
   "title": "dts-lb1-test: трафик",
   "type": "graph",
   "description": "Трафик на балансировщике ЦОД разработки",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(scale(perSecond(seriesByTag('host=dts-lb1-test.unix.tensor.ru', 'interface=bond0', 'name=~system.net.bytes_(recv|sent)')), 8), 'name'), '^.*(recv|sent).*$', '\\1')"
    }
   ]
  },
  {
   "title": "dts-lb1-test: соединения",
   "type": "graph",
   "description": "Количество активных соединений на балансировщике ЦОД разработки",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(seriesByTag('host=dts-lb1-test.unix.tensor.ru', 'name=system.ipvs.active_connections', 'virtual_address!=')), 'connections')"
    }
   ]
  },
  {
   "title": "dts-lb1-test: новые соединения",
   "type": "graph",
   "description": "Количество новых соединений в секунду на балансировщике ЦОД разработки",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(seriesByTag('host=dts-lb1-test.unix.tensor.ru', 'name=system.ipvs.cps', 'virtual_address!=')), 'new conn per second')"
    }
   ]
  }
 ]
}