{
 "title": "Инциденты \"Администрирование ЦОД\"",
 "description": "Ответственный: Митрофанов А.Н. (АЦОД)",
 "tags": [
  "инциденты",
  "bosun",
  "дежурные",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "cpu usage (top 20)",
   "type": "graph",
   "description": "Топ 20 по нагрузке ЦПУ на гипервизорах vcenter",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(highestMax(seriesByTag('cpu=instance-total', 'contur=prod', 'name=service.vcenter.usage_average', 'esxhostname=~(ea1|s076vmk).*', 'interval=20s'), 20), 'esxhostname'), 0)"
    }
   ]
  },
  {
   "title": "Инциденты",
   "type": "bosun-grafana7-panel",
   "description": "Алертинг для дежурных",
   "gridPos": { "h": 23, "w": 14, "x": 10, "y": 0 },
   "targets": [
    { "requestFilter": "filter=hasTag:vision=*sys*" }
   ]
  },
  {
   "title": "mem usage (top 20)",
   "type": "graph",
   "description": "Топ 20 по использованию памяти на гипервизорах vcenter",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(aliasByTags(seriesByTag('esxhostname=~(ea1|s076vmk).*', 'name=service.vcenter.usage_average', 'cpu!=~*', 'interface!=~*', 'vmname!=~*'), 'esxhostname'), 20), 0)"
    }
   ]
  },
  {
   "title": "задержки на СХД (чтение)",
   "type": "graph",
   "description": "Задержки чтения в хранилище данных vcenter",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(highestMax(groupByTags(seriesByTag('vcenter=s076vc50.corp.tensor.ru', 'dsname=~.*', 'name=service.vcenter.totalReadLatency_average'), 'max', 'dsname'), 20), 'dsname')"
    }
   ]
  },
  {
   "title": "задержки СХД (запись)",
   "type": "graph",
   "description": "Задержки записи в хранилище данных vcenter",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(highestMax(groupByTags(seriesByTag('vcenter=s076vc50.corp.tensor.ru', 'dsname=~.*', 'name=service.vcenter.totalWriteLatency_average'), 'max', 'dsname'), 20), 'dsname')"
    }
   ]
  }
 ]
}