{
 "title": "ПЧ ЦОД: Очереди (история и актуальное состояние)",
 "description": "Ответственный: Абрамов В.И. (Разработка), Баулин С.А. (Эксплуатация)",
 "tags": [
  "exploitation",
  "TV",
  "scripts",
  "service",
  "tv5"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "bl",
    "query": "tag_values(host,service=file-transfer,contur=$contur)"
   }
  ]
 },
 "panels": [
  {
   "title": "Рабочие и служебные очереди (сумма)",
   "type": "graph",
   "description": "Сумма по всем активным очередям облака",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(highestMax(exclude(maximumAbove(seriesByTag('name=queue.size', 'subsystem=cloud.sbis.ru', 'host!=~.+', 'contur=${contur:regex}'), 1), 'Центр логирования'), 20), 'service')"
    },
    {
     "target": "alias(countSeries(currentAbove(seriesByTag('name=queue.size', 'subsystem=cloud.sbis.ru', 'host!=~.+', 'contur=${contur:regex}'), 1)), 'Количество активных очередей')"
    }
   ]
  },
  {
   "title": "Рабочие очереди (top 10 актуальных)",
   "type": "table-old",
   "description": "Топ 10 очередей основного пула",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "aliasByTags(highestCurrent(currentAbove(seriesByTag('name=queue.size', 'subsystem=cloud.sbis.ru', 'type=work', 'host!=~.+', 'contur=${contur:regex}'), 1), 10), 'service')"
    }
   ]
  },
  {
   "title": "Служебные очереди (top 10 актуальных)",
   "type": "table-old",
   "description": "Топ 10 очередей служебного пула",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "target": "aliasByTags(highestCurrent(currentAbove(seriesByTag('name=queue.size', 'subsystem=cloud.sbis.ru', 'type=special', 'host!=~.+', 'contur=${contur:regex}'), 1), 10), 'service')"
    }
   ]
  },
  {
   "title": "Асинхронные очереди (сумма)",
   "type": "graph",
   "description": "Сумма по всем асинхронным очередям облака",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(highestMax(countSeries(currentAbove(seriesByTag('name=async.queue.size', 'subsystem=cloud.sbis.ru', 'contur=${contur:regex}'), 1)), 20), 'Количество активных очередей')"
    },
    {
     "target": "aliasByTags(maximumAbove(seriesByTag('name=async.queue.size', 'subsystem=cloud.sbis.ru', 'contur=${contur:regex}'), 1), 'service')"
    }
   ]
  },
  {
   "title": "Ошибки облака (сумма)",
   "type": "gauge",
   "description": "Суммарное количество ошибок облака за предыдущую минуту",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sum(exclude(keepLastValue(maximumAbove(seriesByTag('name=errors', 'subsystem=cloud.sbis.ru', 'source=cloud', 'contur=${contur:regex}'), 1), 10), 'FNS.transport.OFD'))"
    }
   ]
  },
  {
   "title": "Критические ошибки redis",
   "type": "gauge",
   "description": "Суммарное количество критических ошибок в редисе",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=errors.critical', 'source=redis', 'contur=${contur:regex}')"
    }
   ]
  },
  {
   "title": "Асинхронные очереди (top 10 актуальных)",
   "type": "table-old",
   "description": "Топ 10 асинхронных очередей",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "target": "aliasByTags(currentAbove(seriesByTag('name=async.queue.size', 'subsystem=cloud.sbis.ru', 'contur=${contur:regex}'), 1), 'service')"
    }
   ]
  },
  {
   "title": "Критические ошибки логи",
   "type": "graph",
   "description": "Суммарное количество критических ошибок в логах",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "seriesByTag('name=errors.critical', 'subsystem=cloud.sbis.ru', 'source=cloud', 'contur=${contur:regex}')"
    }
   ]
  }
 ]
}