{
 "title": "ПЧ ЦОД: Контроль серверов БД",
 "description": "Ответственный: -",
 "tags": [
  "TV",
  "exploitation",
  "tv6",
  "sbis3mon",
  "service"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   { "name": "aggr", "query": "avg,min,max" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage, %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.linux.core.*-db*.interval-28sec.cpu.busy.$aggr, 10), 4)"
    }
   ]
  },
  {
   "title": "Load average m05",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.linux.la.*-db*.interval-28sec.cpu.la.m05.$aggr, 10), 4)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.linux.memory.*-db*.*.mem.ram.used.$aggr, 10), 4)"
    }
   ]
  },
  {
   "title": "Partition used, /, %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.linux.partition.*-db*.*.partition.volume._2F.prc.raw, 10), 4)"
    }
   ]
  },
  {
   "title": "Partition used, data, %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.linux.partition.*-db*.*.partition.volume._2Fvar_2Flib_2Fpgsql_2F10_2Fdata.prc.raw, 10), 4)"
    },
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.linux.partition.*-db*.*.partition.volume._2Fvar_2Flib_2Fpgsql_2F9.*_2Fdata.prc.raw, 10), 4)"
    }
   ]
  },
  {
   "title": "Storage await, ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.linux.storage.*-db*.interval-30sec.storage.lag.sd*.r_5Fawait.$aggr, 10), 4, -3)"
    }
   ]
  },
  {
   "title": "Etime query",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.postgres.db-time.*-db*.pgsql.*.pgsql.db.etime.total.query.avg, 10), 4)"
    }
   ]
  },
  {
   "title": "Lock exclusive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.postgres.db-locks.*-db*.pgsql.*.pgsql.db.lock.total.exclusive.$aggr, 10), 4)"
    }
   ]
  },
  {
   "title": "Swap usage, %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.linux.memory.*-db*.*.mem.swap.used.pct.max, 10), 4)"
    }
   ]
  }
 ]
}