{
 "title": "ПЧ ЦОД: ITR+RTR",
 "description": "Ответственный: -",
 "tags": [
  "TV",
  "scripts",
  "service",
  "exploitation"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "ins-db2: connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.postgres.db-connection-state.ins-db2.pgsql.*.pgsql.db.connection.total.idle.avg, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.postgres.db-connection-state.ins-db2.pgsql.*.pgsql.db.connection.total.transaction.avg, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.postgres.db-connection-state.ins-db2.pgsql.*.pgsql.db.connection.total.waiting.avg, -2)"
    }
   ]
  },
  {
   "title": "ins-db2: etime query",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.postgres.db-time.ins-db2.pgsql.*.pgsql.db.etime.total.query.avg, -2)"
    }
   ]
  },
  {
   "title": "ins-db2: busy, la",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.la.ins-db2.*.cpu.la.m01.avg, -3)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.core.ins-db2.*.cpu.busy.avg, -2)"
    }
   ]
  },
  {
   "title": "reg-db3: connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.postgres.db-connection-state.reg-db3.pgsql.*.pgsql.db.connection.total.idle.avg, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.postgres.db-connection-state.reg-db3.pgsql.*.pgsql.db.connection.total.transaction.avg, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.postgres.db-connection-state.reg-db3.pgsql.*.pgsql.db.connection.total.waiting.avg, -2)"
    }
   ]
  },
  {
   "title": "reg-db3: etime query",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.postgres.db-time.reg-db3.pgsql.*.pgsql.db.etime.total.query.avg, -2)"
    }
   ]
  },
  {
   "title": "reg-db3: busy, la",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.core.reg-db3.*.cpu.busy.avg, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.la.reg-db3.*.cpu.la.m01.avg, -3)"
    }
   ]
  },
  {
   "title": "Опрос основных сервисов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(scripts.prod.exec_5Fexploitation.*.exp_2Eosr_2Epagetimepass_2Eindex.raw, -2), '_2E', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(scripts.prod.exec_5Fexploitation.*.exp_2Ertr_2Epagetimepass_2Eindex.raw, -2), '_2E', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(scripts.prod.exec_5Fexploitation.*.exp_2Eitr_2Epagetimepass_2Einside_2Eindex.raw, -2), '_2E', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(scripts.prod.exec_5Fexploitation.*.exp_2Eitr_2Ecall_2Einside_2Etestecho.raw, -2), '_2E', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(scripts.prod.exec_5Fexploitation.*.exp_2Eitr_2Epagetimepass_2Einside-only_2Eindex.raw, -2), '_2E', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(scripts.prod.exec_5Fexploitation.*.exp.raw, -2), '_2E', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(scripts.prod.exec_5Fexploitation.*.exp_2Ertr_2Ecall_2Etestecho.raw, -2), '_2E', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(scripts.prod.exec_5Fexploitation.*.exp_2Eosr_2Ecall_2Etestecho.raw, -2), '_2E', ' ')"
    }
   ]
  },
  {
   "title": "Ошибки на ITR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(scripts.prod.exec_5Fexploitation.*.exp_2Eosr_2Eviewlog_2Eerrorcounter_2Einside.raw, -2), '_2E', ' ')"
    }
   ]
  },
  {
   "title": "Ошибки на OSR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(scripts.prod.exec_5Fexploitation.*.exp_2Eosr_2Eviewlog_2Eerrorcounter_2Ecloud.raw, -2), '_2E', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(scripts.prod.exec_5Fexploitation.*.exp_2Eosr_2Eviewlog_2Eerrorcounter_2Eonline.raw, -2), '_2E', ' ')"
    }
   ]
  }
 ]
}