{
 "title": "ПЧ ЦОД: Ошибки облака",
 "description": "Ответственный: -",
 "tags": [
  "TV",
  "exploitation",
  "scripts",
  "service",
  "tv1"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Ошибки облака",
   "type": "graph",
   "gridPos": { "h": 25, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sortByTotal(maximumAbove(exclude(seriesByTag('name=errors', 'subsystem=cloud.sbis.ru', 'source=cloud', 'contur=prod'), 'FNS.transport.OFD'), 1)), 'service')"
    }
   ]
  },
  {
   "title": "Критические ошибки redis",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=errors.critical', 'subsystem=cloud.sbis.ru', 'source=redis', 'contur=prod')"
    }
   ]
  },
  {
   "title": "Критические ошибки логи",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "seriesByTag('name=errors.critical', 'subsystem=cloud.sbis.ru', 'source=cloud', 'contur=prod')"
    }
   ]
  },
  {
   "title": "Ошибки Вип клиенты",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "groupByTags(alias(seriesByTag('name=errors.vip', 'subsystem=cloud.sbis.ru', 'source=cloud', 'contur=prod', 'agg_func=max'), 'Вип клиенты'), 'max', 'name')"
    }
   ]
  },
  {
   "title": "Ошибки облака (сумма)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "sum(maximumAbove(exclude(seriesByTag('name=errors', 'subsystem=cloud.sbis.ru', 'source=cloud', 'contur=prod'), 'FNS.transport.OFD'), 1))"
    }
   ]
  },
  {
   "title": "Ошибки ОФД (сумма)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "keepLastValue(maximumAbove(seriesByTag('name=errors', 'subsystem=cloud.sbis.ru', 'source=cloud', 'service=FNS transport OFD', 'contur=prod'), 1), 10)"
    }
   ]
  },
  {
   "title": "Ошибки облака",
   "type": "table-old",
   "gridPos": { "h": 18, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "target": "aliasByTags(keepLastValue(highestMax(maximumAbove(seriesByTag('name=errors', 'subsystem=cloud.sbis.ru', 'source=cloud', 'contur=prod'), 1), 20), 10), 'service')"
    }
   ]
  }
 ]
}