{
 "title": "ПЧ ЦОД: Контроль состояния виртуальных платформ",
 "description": "Ответственный: -",
 "tags": [
  "esxi",
  "TV",
  "telegraf",
  "tv3",
  "Virtualization",
  "service"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "domain", "query": "*.tensor.ru" }
  ]
 },
 "panels": [
  {
   "title": "cpu usage (top 20)",
   "type": "timeseries",
   "description": "Топ 20 по нагрузке ЦПУ на гипервизорах vcenter",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(highestMax(seriesByTag('cpu=instance-total', 'contur=prod', 'name=service.vcenter.usage_average', 'esxhostname=~(ea1|s076vmk|prod-bc|prod-esxi).*', 'interval=20s'), 20), 'esxhostname'), 0)"
    }
   ]
  },
  {
   "title": "cpu usage ( > 70% )",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 11, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(currentAbove(aliasByTags(highestMax(seriesByTag('cpu=instance-total', 'contur=prod', 'name=service.vcenter.usage_average', 'esxhostname=~(ea1|s076vmk|prod-bc|prod-esxi).*', 'interval=20s'), 20), 'esxhostname'), 70), 0)"
    }
   ]
  },
  {
   "title": "mem usage (top 20)",
   "type": "timeseries",
   "description": "Топ 20 по использованию памяти на гипервизорах vcenter",
   "gridPos": { "h": 13, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(highestMax(aliasByTags(seriesByTag('esxhostname=~(ea1|s076vmk|prod-bc|prod-esxi).*', 'name=service.vcenter.usage_average', 'cpu!=~*', 'interface!=~*', 'vmname!=~*'), 'esxhostname'), 20), 0)"
    }
   ]
  },
  {
   "title": "mem usage ( >85% )",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(currentAbove(highestMax(sbis3mon.prod.vcenter.common.*.vcenter.*.mem.{ea1,s076vmk,prod-bc,prod-esxi}*.$domain.usage, 20), 85), -5)"
    },
    {
     "target": "aliasByNode(currentAbove(highestMax(aliasByTags(seriesByTag('esxhostname=~(ea1|s076vmk|prod-bc).*', 'name=service.vcenter.usage_average', 'cpu!=~*', 'interface!=~*', 'vmname!=~*'), 'esxhostname'), 20), 85), 0)"
    }
   ]
  },
  {
   "title": "задержки на СХД (чтение)",
   "type": "timeseries",
   "description": "Задержки чтения в хранилище данных vcenter",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByTags(highestMax(groupByTags(seriesByTag('vcenter=s076vc50.corp.tensor.ru', 'dsname=~.*', 'name=service.vcenter.totalReadLatency_average'), 'max', 'dsname'), 20), 'dsname')"
    }
   ]
  },
  {
   "title": "задержки СХД ( чтение>100ms )",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 8, "y": 13 },
   "targets": [
    {
     "target": "aliasByTags(highestMax(currentAbove(groupByTags(seriesByTag('vcenter=s076vc50.corp.tensor.ru', 'dsname=~.*', 'name=service.vcenter.totalReadLatency_average'), 'max', 'dsname'), 100), 20), 'dsname')"
    }
   ]
  },
  {
   "title": "задержки СХД (запись)",
   "type": "timeseries",
   "description": "Задержки записи в хранилище данных vcenter",
   "gridPos": { "h": 13, "w": 8, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByTags(highestMax(groupByTags(seriesByTag('vcenter=s076vc50.corp.tensor.ru', 'dsname=~.*', 'name=service.vcenter.totalWriteLatency_average'), 'max', 'dsname'), 20), 'dsname')"
    }
   ]
  },
  {
   "title": "задержки СХД ( запись>100ms )",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 13 },
   "targets": [
    {
     "target": "aliasByTags(highestMax(currentAbove(groupByTags(seriesByTag('vcenter=s076vc50.corp.tensor.ru', 'dsname=~.*', 'name=service.vcenter.totalWriteLatency_average'), 'max', 'dsname'), 100), 20), 'dsname')"
    }
   ]
  }
 ]
}