{
 "title": "ПЧ ЦОД: OTR",
 "description": "Ответственный: Ледяев И.К. (Эксплуатация), Урываев Б.В. (Разработка)",
 "tags": [
  "exploitation",
  "otr",
  "TV",
  "service",
  "scripts",
  "tv4"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  {
   "title": "Количество запросов в очереди",
   "type": "graph",
   "description": "Число запросов в очереди на сервисах ядра",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "exclude(aliasByTags(seriesByTag('name=queue.size', 'subsystem=cloud.sbis.ru', 'type=work', 'service=~.+-transport-core.*', 'host!=~.+'), 'service'), 'for2')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=cloud.sbis.ru', 'type=work', 'service=operator-sbismon', 'host!=~.+'), 'service')"
    }
   ]
  },
  {
   "title": "Количество принимаемых документов в час",
   "type": "graph",
   "description": "Расчетная скорость получения документов в час",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=document.count', 'type=speed', 'source=database'), 'doctype')"
    }
   ]
  },
  {
   "title": "Внешний (внутренний) опрос",
   "type": "graph",
   "description": "Время ответа сервисов Оператора доступных снаружи. Проверка идет изнутри и снаружи.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=response.time', 'subsystem=otr'), 'route', 'name', 'service')"
    }
   ]
  },
  {
   "title": "Количество запросов в секунду",
   "type": "graph",
   "description": "Количество запросов в секунду по сервисам основного ядра оператора",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(sbis3mon.prod.sbis3app.info.otr-edo-core-bl*.sbis3.10081.*.sbis3.service.request.processed._2Fedo-transport-core_2Fservice_2F.$aggr), 'edo-transport-core')"
    },
    {
     "target": "alias(sumSeries(sbis3mon.prod.sbis3app.info.otr-edo-core-bl*.sbis3.10081.*.sbis3.service.request.processed._2Fedo-internal-transport-core_2Fservice_2F.$aggr), 'edo-internal-transport-core')"
    },
    {
     "target": "alias(sumSeries(sbis3mon.prod.sbis3app.info.otr-eo-core-bl*.sbis3.10081.*.sbis3.service.request.processed._2Feo-internal-transport-core_2Fservice_2F.$aggr), 'eo-internal-transport-core')"
    },
    {
     "target": "alias(sumSeries(sbis3mon.prod.sbis3app.info.otr-eo-core-bl*.sbis3.10081.*.sbis3.service.request.processed._2Foperator-sbismon_2Fservice_2F.$aggr), 'operator-sbismon')"
    },
    {
     "target": "alias(sumSeries(sbis3mon.prod.sbis3app.info.otr-eo-core-bl*.sbis3.10081.*.sbis3.service.request.processed._2Feo-transport-core_2Fservice_2F.$aggr), 'eo-transport-core')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров в системы доставки",
   "type": "graph",
   "description": "Число контейнеров в ядрах готовых к передаче в Транспортные модули и онлайн",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(seriesByTag('name=queue.size', 'subsystem=~core-elo\\d', 'queue=core_to_cloud', 'unit!=~.*')), 'core elo to cloud')"
    },
    {
     "target": "alias(sumSeries(seriesByTag('name=queue.size', 'subsystem=~core-edo\\d', 'queue=core_to_cloud', 'unit!=~.*')), 'core edo to cloud')"
    },
    {
     "target": "alias(sumSeries(seriesByTag('name=queue.size', 'subsystem=mail', 'queue=~core_elo\\d_to_mail')), 'core elo to mail')"
    },
    {
     "target": "alias(sumSeries(seriesByTag('name=queue.size', 'subsystem=fold', 'queue=~core_elo\\d_to_folders')), 'core elo to folders')"
    },
    {
     "target": "alias(sumSeries(seriesByTag('name=queue.size', 'subsystem=fss', 'queue=~core_elo\\d_to_fss')), 'core elo to fss')"
    },
    {
     "target": "alias(sumSeries(seriesByTag('name=queue.size', 'subsystem=fsrar', 'queue=~core_elo\\d_to_fsrar')), 'core elo to fsrar')"
    },
    {
     "target": "alias(sumSeries(seriesByTag('name=queue.size', 'subsystem=rpn', 'queue=~core_elo\\d_to_rpn')), 'core elo to rpn')"
    },
    {
     "target": "alias(sumSeries(seriesByTag('name=queue.size', 'subsystem=cb', 'queue=~core_elo\\d_to_cb')), 'core elo to cb')"
    },
    {
     "target": "alias(sumSeries(seriesByTag('name=queue.size', 'subsystem=pf', 'queue=~core_elo\\d_to_pf')), 'core elo to pf')"
    },
    {
     "target": "alias(sumSeries(seriesByTag('name=queue.size', 'subsystem=fnsreg', 'queue=~core_elo\\d_to_fnsreg')), 'core elo to fnsreg')"
    }
   ]
  },
  {
   "title": "Очередь репликации первичных документов в хранилище",
   "type": "graph",
   "description": "Число первичных документов в ядре, ожидающих репликации в хранилище",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=wh', 'queue=~Primary docs.*'), 'queue')"
    }
   ]
  },
  {
   "title": "Количество запросов в секунду",
   "type": "graph",
   "description": "Количество запросов в секунду по сервисам резервного ядра оператора",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(sbis3mon.prod.sbis3app.info.otr-res-edo-bl*.sbis3.10081.*.sbis3.service.request.processed._2Fres-edo-transport-core_2Fservice_2F.$aggr), 'res-edo-transport-core')"
    },
    {
     "target": "alias(sumSeries(sbis3mon.prod.sbis3app.info.otr-res-elo-bl*.sbis3.10081.*.sbis3.service.request.processed._2Fres-eo-transport-core_2Fservice_2F.$aggr), 'res-eo-transport-core')"
    }
   ]
  },
  {
   "title": "Очереди контейнеров из систем доставки",
   "type": "graph",
   "description": "Число контейнеров в Транспортных модулях готовых к отправке до получателя или в ядро",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=mail', 'queue=~mail\\d_to_[core,mailbox]'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=mail', 'queue=~primary_docs_to_mailbox\\d'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=fold', 'queue=~folders\\d_to_[core,PF]'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=fss', 'queue=fss_to_core'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=fsrar', 'queue=fsrar_to_core'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=pf', 'queue=~pf_to_[core,pfinsp]'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=cb', 'queue=~cb_to_[core,cbportal]'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=fnsreg', 'queue=~fnsreg_to_[core,fns]'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=rpn', 'queue=~rpn_to_[core,portal]'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=mail', 'queue=~mail-\\d_to_[core,mailbox]'), 'queue')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=queue.size', 'subsystem=mail', 'queue=~primary_docs-\\d_to_mailbox'), 'queue')"
    }
   ]
  },
  {
   "title": "Очередь репликации первичных документов в хранилище (задержка)",
   "type": "graph",
   "description": "Задержка репликации первичных документов из ядра в Хранилище",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.lag', 'subsystem=wh', 'queue=~Primary docs.*'), 'queue')"
    }
   ]
  }
 ]
}