{
 "title": "HL/HA — NGINX-CACHE CLUSTER",
 "description": "Ответственный: Конюхов М.В. (Эксплуатация)",
 "tags": [
  "hlha",
  "nginx-cache",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   { "name": "servertype", "label": "Тип", "query": "nginx-cache" },
   {
    "name": "nginxcachecluster",
    "label": "Кластер",
    "query": "tag_values(nginxcachecluster,contur=$contur,servertype=$servertype)"
   },
   {
    "name": "host",
    "label": "Сервер",
    "query": "tag_values(host,contur=$contur,servertype=$servertype,nginxcachecluster=$nginxcachecluster)"
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Запросы",
   "type": "graph",
   "description": "Сколько запросов пришло от клиентов и ушло на бакенды",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(consolidateBy(aliasByTags(perSecond(seriesByTag('name=nginx.requests', 'host=~${host:regex}')), 'host'), 'max'))"
    }
   ]
  },
  {
   "title": "Запросы stack",
   "type": "graph",
   "description": "Сколько запросов пришло от клиентов и ушло на бакенды",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(consolidateBy(aliasByTags(perSecond(seriesByTag('name=nginx.requests', 'host=~${host:regex}')), 'host'), 'max'))"
    }
   ]
  },
  {
   "title": "Ответы кеша STALE",
   "type": "graph",
   "description": "Соотношение попадания в кеш и промахов.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(consolidateBy(aliasByTags(seriesByTag('name=~nginx-cache.STALE', 'host=~${host:regex}'), 'host'), 'max')), 0)"
    }
   ]
  },
  {
   "title": "Ответы кеша",
   "type": "graph",
   "description": "Соотношение попадания в кеш и промахов.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(consolidateBy(aliasByTags(seriesByTag('name=~nginx-cache.*', 'name!=nginx-cache.RATIO', 'name!=nginx-cache.TOTAL', 'host=~${host:regex}', 'name!=nginx-cache.b', 'name!=nginx-cache.r', 'name!=nginx-cache.response_time', 'name!=nginx-cache.rt', 'name!=nginx-cache.urt'), 'host', 'name'), 'max'))"
    }
   ]
  },
  {
   "title": "Ответы кеша stack",
   "type": "graph",
   "description": "Соотношение попадания в кеш и промахов.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(consolidateBy(aliasByTags(seriesByTag('name=~nginx-cache.*', 'name!=nginx-cache.RATIO', 'name!=nginx-cache.TOTAL', 'host=~${host:regex}', 'name!=nginx-cache.b', 'name!=nginx-cache.r', 'name!=nginx-cache.response_time', 'name!=nginx-cache.rt', 'name!=nginx-cache.urt'), 'host', 'name'), 'max'))"
    }
   ]
  }
 ]
}