{
 "title": "HL/HA — UPDATE.SBIS.RU",
 "description": "Сервис предназначен для мониторинга и управления балансировкой трафика между зеркалами update.sbis.ru. Ответственный:  Смирнов К.В. (Эксплуатация)",
 "tags": [
  "telegraf",
  "exploitation",
  "service",
  "hlha"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Хост",
    "query": "tag_values(host,servertype=update)"
   }
  ]
 },
 "panels": [
  {
   "title": "active",
   "type": "graph",
   "description": "Общее количество открытых соединений",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(aliasByTags(sortByMaxima(seriesByTag('name=nginx.active', 'host=~${host:regex}')), 'host')), -4)"
    }
   ]
  },
  {
   "title": "requests",
   "type": "graph",
   "description": "Текущее число клиентских запросов",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(aliasByTags(sortByMaxima(perSecond(seriesByTag('name=nginx.requests', 'host=~${host:regex}'))), 'host')), -4)"
    }
   ]
  },
  {
   "title": "accepts",
   "type": "graph",
   "description": "Суммарное число принятых клиентских соединений",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sortByMaxima(aliasByTags(perSecond(seriesByTag('name=~nginx.accepts', 'host=~${host:regex}')), 'host'))), -4)"
    }
   ]
  },
  {
   "title": "handled",
   "type": "graph",
   "description": "Суммарное число обработанных соединений.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sortByMaxima(aliasByTags(perSecond(seriesByTag('name=~nginx.handled', 'host=~${host:regex}')), 'host'))), -4)"
    }
   ]
  },
  {
   "title": "waiting",
   "type": "graph",
   "description": "Текущее число бездействующих клиентских соединений в ожидании запроса.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(aliasByTags(sortByMaxima(seriesByTag('name=nginx.waiting', 'host=~${host:regex}')), 'host')), -4)"
    }
   ]
  },
  {
   "title": "writing",
   "type": "graph",
   "description": "Текущее число соединений, в которых nginx в настоящий момент отвечает клиенту.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(keepLastValue(aliasByTags(seriesByTag('name=~nginx.writing', 'host=~${host:regex}'), 'host')), -4))"
    }
   ]
  },
  {
   "title": "Исходящий трафик",
   "type": "graph",
   "description": "Статистика по исходящему трафику",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(keepLastValue(sortByMaxima(perSecond(scale(seriesByTag('name=system.net.bytes_sent', 'host=~${host:regex}'), 8)))), 'host')"
    }
   ]
  },
  {
   "title": "Входящий трафик",
   "type": "graph",
   "description": "Статистика по входящему трафику",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(keepLastValue(perSecond(sortByMaxima(scale(seriesByTag('host=~${host:regex}', 'name=system.net.bytes_recv'), 8)))), 'host')"
    }
   ]
  },
  {
   "title": "memory available",
   "type": "graph",
   "description": "Статистика по памяти",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(keepLastValue(consolidateBy(aliasByTags(seriesByTag('host=~${host:regex}', 'name=system.mem.available'), 'host'), 'max')), -4))"
    }
   ]
  },
  {
   "title": "LA",
   "type": "graph",
   "description": "Статистика по la за 5 минут",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(keepLastValue(aliasByTags(seriesByTag('name=system.system.load5', 'host=~${host:regex}'), 'host')), -4))"
    }
   ]
  }
 ]
}