{
 "title": "HL/HA — ROUTER LATENCY",
 "description": "Мониторинг диспетчера на уровне nginx. Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "hlha_router",
  "prometheus",
  "hlha"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "servertype", "label": "Тип", "query": "dispatcher" },
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "cluster",
    "label": "Кластер",
    "query": "tag_values(cluster,contur=prod,servertype=$servertype)"
   },
   {
    "name": "host",
    "label": "Хост",
    "query": "tag_values(host,cluster=$cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Запросы и перцентили задержек",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps", "label": "Request(s)" }
   ],
   "targets": [
    {
     "target": "alias(nPercentile(groupByTags(perSecond(seriesByTag('name=prometheus.nginx_front_latency_bucket', 'host=~${host:regex}')), 'average', 'name'), 95), '95% front')"
    },
    {
     "target": "alias(nPercentile(groupByTags(perSecond(seriesByTag('name=prometheus.nginx_back_latency_bucket', 'host=~${host:regex}')), 'average', 'name'), 95), '95% back')"
    },
    {
     "target": "sortByMaxima(aliasByNode(aliasByTags(perSecond(seriesByTag('name=nginx.requests', 'host=~${host:regex}')), 'host'), 0))"
    }
   ]
  },
  {
   "title": "LATENCY FRONT",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "groupByTags(perSecond(seriesByTag('name=prometheus.nginx_front_latency_bucket', 'host=~${host:regex}')), 'average', 'name')"
    }
   ]
  },
  {
   "title": "LATENCY BACK",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "target": "groupByTags(perSecond(seriesByTag('name=prometheus.nginx_back_latency_bucket', 'host=~${host:regex}')), 'average', 'name')"
    }
   ]
  }
 ]
}