{
 "title": "HL/HA — CDN / GCORE",
 "description": "Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "cdn",
  "hlha"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cdnprov", "label": "CDNPROV", "query": "gcore" },
   {
    "name": "cdnstand",
    "label": "Стенд",
    "query": "tag_values(cdnstand,cdnprov=$cdnprov)"
   },
   {
    "name": "site",
    "label": "Сайт",
    "query": "tag_values(site,cdnprov=$cdnprov,cdnstand=$cdnstand)"
   }
  ]
 },
 "panels": [
  { "title": "${site}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "site" },
  {
   "title": "Requests ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('name=cdn.requests', 'site=~${site:regex}'), 'median', 'requests'), 1)"
    }
   ]
  },
  {
   "title": "Trafic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('name=cdn.sent_bytes', 'site=~${site:regex}'), 'median', 'requests'), 1)"
    }
   ]
  },
  {
   "title": "Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('name=cdn.cache_hit_traffic_ratio', 'site=~${site:regex}'), 'median', 'requests'), 1)"
    }
   ]
  }
 ]
}