{
 "title": "HL/HA — ROUTER REDISCLUSTER",
 "description": "Мониторинг диспетчера на уровне nginx. Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "hlha_router",
  "prometheus",
  "hlha"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "servertype", "label": "Тип", "query": "dispatcher" },
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "cluster",
    "label": "Кластер",
    "query": "tag_values(cluster,contur=prod,servertype=$servertype)"
   },
   {
    "name": "host",
    "label": "Хост",
    "query": "tag_values(host,cluster=$cluster,contur=prod,servertype=$servertype)"
   }
  ]
 },
 "panels": [
  {
   "title": "NGINX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=nginx.requests', 'host=~${host:regex}')), 'host')"
    }
   ]
  },
  {
   "title": "Ошибки RedisCluster",
   "type": "graph",
   "description": "Запросы",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(sortByMaxima(consolidateBy(groupByTags(nonNegativeDerivative(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_rc_err')), 'sum', 'host', 'error'), 'max')), 'host', 'error'), 0, 4)"
    }
   ]
  },
  {
   "title": "СЕТЬ / TCP",
   "type": "graph",
   "description": "Очередь SYN пакетов",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~system.netstat.*', 'host=~${host:regex}'), 'name')"
    }
   ]
  },
  {
   "title": "Ошибки RedisCluster 75% перцентиль",
   "type": "graph",
   "description": "Запросы",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(sortByMaxima(groupByTags(nPercentile(perSecond(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_rc_err')), 75), 'sum', 'host')), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Запросы RedisCluster",
   "type": "graph",
   "description": "Запросы",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sortByMaxima(groupByTags(perSecond(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_rc_cmd')), 'sum', 'cmd')), 'cmd')"
    }
   ]
  },
  {
   "title": "MEMCACHE Connection(s)",
   "type": "graph",
   "description": "Скорость текущих подключений",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "alias(derivative(seriesByTag('host=memcached-cache.unix.tensor.ru', 'name=memcached.total_connections')), 'connections')"
    }
   ]
  }
 ]
}