{
 "title": "HL/HA — ROUTER CLUSTER LA",
 "description": "Мониторинг LA. Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "hlha",
  "service",
  "telegraf",
  "hlha_router"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Кластер", "query": "tag_values(cluster)" },
   {
    "name": "host",
    "label": "Хост",
    "query": "tag_values(host,cluster=${cluster},servertype=dispatcher,contur=prod)"
   }
  ]
 },
 "panels": [
  {
   "title": "LA1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.system.load1', 'host=~${host:regex}'), 'host'), 0)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.system.n_cpus', 'host=~${host:regex}'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "LA5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.system.load5', 'host=~${host:regex}'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "LA15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.system.load15', 'host=~${host:regex}'), 'host'), 0)"
    }
   ]
  }
 ]
}