{
 "title": "HL/HA — FAIL2BAN JAIL(s) 2",
 "description": "Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "hlha",
  "hlhajail",
  "fail2ban"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "cluster",
    "label": "Кластер",
    "query": "tag_values(cluster,contur=$contur,jail!=)"
   },
   {
    "name": "jail",
    "label": "JAIL",
    "query": "tag_values(jail,contur=$contur,cluster=~${cluster})"
   }
  ]
 },
 "panels": [
  { "title": "KEYDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BLOCKED IP(s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=redis.keys', 'host=memcached-cache.unix.tensor.ru', 'port=6379'), 'name')"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=redis.used_memory', 'port=6379', 'host=~memcached-cache.unix.tensor.ru'), 'name')"
    }
   ]
  },
  { "title": "FAIL2BAN — ${cluster}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "cluster" },
  {
   "title": "BANNED — $cluster — ${jail}",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "repeat": "jail",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(aliasByTags(seriesByTag('jail=~${jail:regex}', 'name=fail2ban.banned', 'contur=${contur:regex}', 'cluster=~${cluster:regex}'), 'host')), 0)"
    }
   ]
  }
 ]
}