{
 "title": "HL/HA — SSL",
 "description": "Мониторинг сертификатов x509_cert. Ответственный: Конюхов М.В. (Эксплуатация)",
 "tags": [
  "x509_cert",
  "ssl",
  "nginx",
  "hlha",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "servertype",
    "label": "Кластер",
    "query": "tag_values(servertype,name=nginx.ssl.expiry,contur=prod)"
   },
   {
    "name": "host",
    "label": "Хост",
    "query": "tag_values(host,servertype=${servertype},contur=prod)"
   },
   {
    "name": "source",
    "query": "tag_values(source,servertype=${servertype},host=~${host:regex},contur=prod)"
   },
   {
    "name": "cert",
    "query": "tag_values(common_name,servertype=${servertype},source=~${source:regex},contur=prod)"
   },
   {
    "name": "serial",
    "query": "tag_values(serial_number,servertype=${servertype},source=~${source:regex},contur=prod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Список сертов по хостам",
   "type": "table",
   "description": "Список всех хостов и сертов, которые на них мониторятся. Если не нашли в списке - значит хост не мониторится",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByTags(scale(sortByMinima(seriesByTag('name=nginx.ssl.expiry', 'host=~${host:regex}', 'servertype=$servertype', 'source=~${source:regex}', 'common_name=~${cert:regex}', 'serial_number=~${serial:regex}')), 1000, 0), 'host', 'common_name', 'serial_number')"
    }
   ]
  },
  {
   "title": "SSL.EXPIRE",
   "type": "graph",
   "description": "expiry (int, seconds)\n> кол-во секунд, оставшихся до истечения сертификата. учитываем тот факт, что также проверяются родительские и кросс сертификаты (пока это не убрать из метрик)",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=nginx.ssl.expiry', 'host=~${host:regex}', 'servertype=$servertype', 'source=~${source:regex}', 'common_name=~${cert:regex}', 'serial_number=~${serial:regex}'), 'host', 'common_name', 'serial_number')"
    }
   ]
  },
  { "title": "No data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "SSL.EXPIRE NO data",
   "type": "graph",
   "description": "> все nodata преобразуются в -1 значения. на графике отображаем только их. нужно это для проверки где проблемы со сбором данных.\n> кол-во секунд, оставшихся до истечения сертификата. учитываем тот факт, что также проверяются родительские и кросс сертификаты (пока это не убрать из метрик)",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(keepLastValue(removeAboveValue(transformNull(seriesByTag('name=nginx.ssl.expiry', 'host=~${host:regex}', 'servertype=$servertype', 'source=~${source:regex}', 'common_name=~${cert:regex}', 'serial_number=~${serial:regex}'), -1), 0), 1), 'host', 'common_name', 'serial_number')"
    }
   ]
  }
 ]
}