{
 "title": "HL/HA — ELASTIC CLUSTER",
 "description": "Экран Elasticsearch. Ответственный: Конюхов М.В. (Эксплуатация), Федорин Д.В. и Смирнов И.В. (Разработка)",
 "tags": [
  "es",
  "hlha",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "cluster_name",
    "label": "Кластер",
    "query": "tag_values(clustername,contur=$contur,servertype=elasticsearch)"
   },
   {
    "name": "host",
    "label": "Узел",
    "query": "tag_values(host,clustername=$cluster_name)"
   },
   {
    "name": "index",
    "label": "Индекс",
    "query": "tag_values(index,clustername=$cluster_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "description": "Статус кластера в целом. \n- Green - все ок\n- Yellow - есть часть нод с проблемами, но в целом индекс полностью доступен, т.к. зарезервирован\n- Red - кластер частично или полностью недоступен, часть или все данные невозможно запросить.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('clustername=$cluster_name', 'name=service.elastic.status_code', 'servertype=elasticsearch', 'index!=~.*'), 1)"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Статистика по нодам кластера. \n- Total - всего\n- Master - кол-во мастеров\n- Data - кол-во нод для хранения данных",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(highestMax(seriesByTag('name=service.elastic.number_of_nodes', 'clustername=$cluster_name', 'index!=~.*'), 1), 'Total')"
    },
    {
     "target": "alias(highestMax(seriesByTag('name=service.elastic.count_master', 'clustername=$cluster_name', 'index!=~.*'), 1), 'Master')"
    },
    {
     "target": "alias(highestMax(seriesByTag('name=service.elastic.number_of_data_nodes', 'clustername=$cluster_name', 'index!=~.*'), 1), 'Data')"
    }
   ]
  },
  {
   "title": "Active Shards",
   "type": "stat",
   "description": "Шарда - это единица, в которой elastic распределяет данные по кластеру. Скорость, с которой система может перемещать шарды при ребалансировке данных, например, после сбоя, зависит от размера и кол-ва шард, а также от диска и сети.",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(highestMax(seriesByTag('name=service.elastic.active_shards', 'clustername=$cluster_name'), 1), 'nodes')"
    }
   ]
  },
  {
   "title": "Pri. Shards",
   "type": "stat",
   "description": "Кол-во основных(первичных) шард.\nСуществует два типа шард: первичные и реплики. Каждый документ в индексе принадлежит одному первичному шарду. Шарды реплики - это копия основного шарда. Реплики предоставляют избыточные копии ваших данных для защиты от сбоев оборудования и увеличения емкости для обслуживания запросов на чтение, таких как поиск или получение документа.\n\nКоличество первичных шардов в индексе фиксируется на момент создания индекса, но количество реплик может быть изменено в любое время без прерывания операций индексирования или запросов. ",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('name=service.elastic.active_primary_shards', 'clustername=$cluster_name'), 1)"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "description": "Кол-во инициализируемых шард (в процессе пересоздания, создания, перебалансировки итд). В идеале их значение должно быть равным 0.",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('name=service.elastic.initializing_shards', 'clustername=$cluster_name'), 1)"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "description": "Кол-во шард, которые не удалось привязать к ноде кластера.  В идеале должно быть равным 0.",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('name=service.elastic.unassigned_shards', 'clustername=$cluster_name'), 1)"
    }
   ]
  },
  {
   "title": "Delayed Un. Shards",
   "type": "stat",
   "description": "Кол-во отложенных шард на ребалансировку. В идеале должно быть равным 0.",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('name=service.elastic.delayed_unassigned_shards', 'clustername=$cluster_name'), 1)"
    }
   ]
  },
  {
   "title": "Relocating Tasks",
   "type": "stat",
   "description": "Кол-во перемещаемых в данный момент времени шард на кластере.  В идеале должно быть равным 0.",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('name=service.elastic.relocating_shards', 'clustername=$cluster_name'), 1)"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "description": "Ожидающие выполнения задачи кластера.",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('name=service.elastic.number_of_pending_tasks', 'clustername=$cluster_name'), 1)"
    }
   ]
  },
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Primary Docs Count",
   "type": "graph",
   "description": "Всего документов в data хранилище и кол-во удаленных документов",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(highestAverage(seriesByTag('name=service.elastic.docs_count', 'clustername=$cluster_name', 'contur=${contur:regex}', 'node_roles=~.*data.*'), 1), 'total ')"
    },
    {
     "target": "aliasSub(aliasByNode(aliasByTags(seriesByTag('name=service.elastic.docs_deleted', 'clustername=$cluster_name', 'contur=${contur:regex}', 'node_roles=~.*data.*'), 'host'), 0), '$', ',Deleted')"
    }
   ]
  },
  {
   "title": "Место в хранилище",
   "type": "graph",
   "description": "Кол-во байт свободно и всего, выделенное для кластера",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(seriesByTag('name=service.elastic.fs_free_in_bytes', 'clustername=$cluster_name', 'contur=${contur:regex}')), 'free')"
    },
    {
     "target": "alias(sumSeries(seriesByTag('name=service.elastic.fs_total_in_bytes', 'clustername=$cluster_name', 'contur=${contur:regex}')), 'total')"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Процент загрузки CPU процессом elastic",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=service.elastic.process_cpu_percent', 'clustername=$cluster_name', 'contur=${contur:regex}'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "JVM heap used in bytes",
   "type": "graph",
   "description": "Java Heap (куча) используется Java Runtime для выделения памяти под объекты и JRE классы. Создание нового объекта также происходит в куче. Здесь работает сборщик мусора: освобождает память путем удаления объектов, на которые нет каких-либо ссылок. Любой объект, созданный в куче, имеет глобальный доступ и на него могут ссылаться с любой части приложения.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(sumSeries(seriesByTag('name=service.elastic.jvm_mem_heap_used_in_bytes', 'clustername=$cluster_name', 'contur=${contur:regex}')), 'host'), 0)"
    }
   ]
  },
  { "title": "Cluster Indices Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Search Rate  /per sec",
   "type": "graph",
   "description": "Кол-во запросов к кластеру пользователей на поиск данных. Присутствует как счетчик, поэтому берется perSecond. На периодах >7 дней может отображаться некорректно. Ненулевые данные обычно показывают, что кто-то выполнял поиск по индексам.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=~service.elastic.search_query_total', 'contur=${contur:regex}', 'node_roles=~.*data.*')), 'host', 'name'), 'perSecond\\(', ''), 0, -1)"
    }
   ]
  },
  {
   "title": "Search Latency  /per sec",
   "type": "graph",
   "description": "Время исполнения запросов в кластере на поиск. Присутствует как счетчик, поэтому берется perSecond. На периодах >7 дней может отображаться некорректно. Ненулевые данные обычно показывают, что кто-то выполнял поиск по индексам. ",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=~service.elastic.search_query_time_in_millis', 'contur=${contur:regex}', 'node_roles=~.*data.*')), 'host', 'name'), 'perSecond\\(', ''), 0, -1)"
    }
   ]
  },
  {
   "title": "Indexing Rate /per sec",
   "type": "graph",
   "description": "Кол-во запросов к кластеру от источников, попадающие в индексы. Присутствует как счетчик, поэтому берется perSecond. На периодах >7 дней может отображаться некорректно. Нулевые значения могут показывать, что на вход перестали идти запросы.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.indexing_index_total', 'contur=${contur:regex}')), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Indexing Latency /per sec",
   "type": "graph",
   "description": "Задержка обработки индекса или время на его создание. Присутствует как счетчик, поэтому берется perSecond. На периодах >7 дней может отображаться некорректно. Нулевые значения могут показывать, что на вход перестали идти запросы.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.indexing_index_time_in_millis', 'contur=${contur:regex}')), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Merges /per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.merges_total', 'contur=${contur:regex}', 'node_roles=~.*data.*')), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Merges Latency /per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.merges_total_time_in_millis', 'contur=${contur:regex}', 'node_roles=~.*data.*')), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Field Data Memory /per sec",
   "type": "graph",
   "description": "Опция indices.fielddata.cache.size. Кол-во байт, задействованных под данную опцию. Используется при поиске для ускорения работы с полями (сортировка, аггрегация итд). Накладываем perSecond для отображения факта роста использования памяти.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.fielddata_memory_size_in_bytes', 'contur=${contur:regex}')), 'host')"
    }
   ]
  },
  {
   "title": "Segments Memory / Count",
   "type": "graph",
   "description": "Количество байтов, используемых для сегментов, по данным API статистики индексов. \nИ общее количество сегментов (если только растет - плохо)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.segments_memory_in_bytes', 'contur=${contur:regex}', 'node_roles=~data.*'), 'host', 'name'), 0, 6)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.segments_count', 'contur=${contur:regex}', 'node_roles=~data.*'), 'host', 'name'), 0, 6)"
    }
   ]
  },
  { "title": "Node OS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "FS Free",
   "type": "bargauge",
   "description": "Доступно байт от выделенных. Стоит понимать, что выделено может быть с общей хранилки и лимит фиктивный.",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.total_free_in_bytes', 'contur=${contur:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "CPU Node",
   "type": "graph",
   "description": "Общее использование CPU нодой кластера.",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.cpu_percent', 'contur=${contur:regex}'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "CPU Instance",
   "type": "graph",
   "description": "Время использования нодой CPU в милисекундах.",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.cpu_total_in_millis', 'contur=${contur:regex}')), 'host')"
    }
   ]
  },
  {
   "title": "LA",
   "type": "graph",
   "description": "Load average системы. Не должен превышать в идеале кол-ва ядер на виртуальном сервере.",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.cpu_load_average_1m', 'contur=${contur:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Использование памяти нодой кластера. В байтах.",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.mem_used_in_bytes', 'contur=${contur:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "description": "Использование свапа на сервере с нодой. В байтах.",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.swap_used_in_bytes', 'contur=${contur:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "fs.io_stats.total Read /per sec",
   "type": "graph",
   "description": "Input/Output статистика на чтение на диск. Берем килобайты в секунду.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.io_stats_total_read_kilobytes', 'contur=${contur:regex}')), 'host')"
    }
   ]
  },
  {
   "title": "fs.io_stats.total Write /per sec",
   "type": "graph",
   "description": "Input/Output статистика на запись на диск. Берем килобайты в секунду.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.io_stats_total_write_kilobytes', 'contur=${contur:regex}')), 'host')"
    }
   ]
  },
  {
   "title": "Transport /per sec",
   "type": "graph",
   "description": "Рейтинг пересылки транспортный логов. Берем байты в секунду.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.translog_size_in_bytes', 'contur=${contur:regex}')), 'host')"
    }
   ]
  },
  {
   "title": "Node Stats Indices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Field Data & Breakers",
     "type": "graph",
     "description": "Статистика по индексам. Отображается в байтах:\n- размер request_estimated_size\n- размер parent_estimated_size\n- размер fielddata_estimated_size\n- размер in_flight_estimated_size",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.request_estimated_size_in_bytes', 'contur=${contur:regex}'), 'host', 'name'), 0, -1)"
      },
      {
       "target": "aliasByNode(aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.parent_estimated_size_in_bytes', 'contur=${contur:regex}'), 'host', 'name'), 0, -1)"
      },
      {
       "target": "aliasByNode(aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.fielddata_estimated_size_in_bytes', 'contur=${contur:regex}'), 'host', 'name'), 0, -1)"
      },
      {
       "target": "aliasByNode(aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.fielddata_memory_size_in_bytes', 'contur=${contur:regex}'), 'host', 'name'), 0, -1)"
      },
      {
       "target": "aliasByNode(aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.in_flight_requests_estimated_size_in_bytes', 'contur=${contur:regex}'), 'host', 'name'), 0, -1)"
      }
     ]
    },
    {
     "title": "HTTP Open /per sec",
     "type": "graph",
     "description": "Кол-во открытых HTTP подключений в секунду.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 60 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.total_opened', 'contur=${contur:regex}')), 'host')"
      }
     ]
    },
    {
     "title": "Indices docs /per sec",
     "type": "graph",
     "description": "Размер docs индексов",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=~service.elastic.docs', 'contur=${contur:regex}')), 'host', 'name'), 'perSecond\\(', ''), 0, -1)"
      }
     ]
    },
    {
     "title": "Indexing Latency",
     "type": "graph",
     "description": "Задержка индексирования. В секунду.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.indexing_index_time_in_millis', 'contur=${contur:regex}')), 'host')"
      }
     ]
    },
    {
     "title": "Indexing Rate /per sec",
     "type": "graph",
     "description": "Рейнтин индексирования - кол-во обрабатываемых индексов в секунду. В секунду.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.indexing_index_total', 'contur=${contur:regex}')), 'host')"
      }
     ]
    },
    {
     "title": "Merges Rate /per sec",
     "type": "graph",
     "description": "Кол-во merges в секунду.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=~service.elastic.merges_(total|total_docs)$', 'contur=${contur:regex}')), 'host', 'name'), 'perSecond\\(', ''), 0, -1)"
      }
     ]
    },
    {
     "title": "merges.total_size_in_bytes",
     "type": "graph",
     "description": "Размер merges в байтах в секунду.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.merges_total_size_in_bytes', 'contur=${contur:regex}')), 'host')"
      }
     ]
    },
    {
     "title": "Merges Latency & Thrrottling",
     "type": "graph",
     "description": "Скорость обработки merges в секунду. Также отображает throttling на merges.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 67 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.merges_total_throttled_time_in_millis', 'contur=${contur:regex}')), 'host', 'name'), 'perSecond\\(', ''), 0, -1)"
      },
      {
       "target": "aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.refresh_total_time_in_millis', 'contur=${contur:regex}')), 'host', 'name'), 'perSecond\\(', ''), 0, -1)"
      }
     ]
    },
    {
     "title": "Indices Search",
     "type": "graph",
     "description": "Время задержки поиска по индексу в секунду.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.search_query_time_in_millis', 'contur=${contur:regex}')), 'host', 'name'), 'perSecond\\(', ''), 0, -1)"
      },
      {
       "target": "aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('clustername=$cluster_name', 'name=service.elastic.search_query_total', 'contur=${contur:regex}')), 'host', 'name'), 'perSecond\\(', ''), 0, -1)"
      }
     ]
    },
    {
     "title": "Segments",
     "type": "graph",
     "description": "Кол-во сегментов всего.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.segments_count', 'contur=${contur:regex}', 'node_roles=~data.*'), 'host')"
      }
     ]
    },
    {
     "title": "Segments Memory",
     "type": "graph",
     "description": "Сколько всего памяти в байтах использовали сегменты.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.segments_memory_in_bytes', 'contur=${contur:regex}', 'node_roles=~data.*'), 'host')"
      }
     ]
    },
    {
     "title": "Translog",
     "type": "graph",
     "description": "Сколько всего байтов использовал transport log.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 74 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.translog_size_in_bytes', 'contur=${contur:regex}', 'node_roles=~data.*'), 'host')"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "young times",
     "type": "graph",
     "description": "Garbage collector young collection time в милисекунду. ",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasByTags(aliasSub(perSecond(seriesByTag('contur=${contur:regex}', 'clustername=$cluster_name', 'host=~${host:regex}', 'name=service.elastic.gc_collectors_young_collection_time_in_millis')), 'perSecond', ''), 'host', 'name'), '.service.elastic.', ':')"
      }
     ]
    },
    {
     "title": "young count",
     "type": "graph",
     "description": "Garbage collector young collection кол-во объектов в милисекунду. ",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasByTags(aliasSub(perSecond(seriesByTag('contur=${contur:regex}', 'clustername=$cluster_name', 'host=~${host:regex}', 'name=service.elastic.gc_collectors_young_collection_count')), 'perSecond', ''), 'host', 'name'), '.service.elastic.', ':')"
      }
     ]
    },
    {
     "title": "old times",
     "type": "graph",
     "description": "Сейчас используется G1CC поэтому OLD вызывается только по достижению какого то процента. По дефолту у Эластика 30%.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasByTags(aliasSub(perSecond(seriesByTag('contur=${contur:regex}', 'clustername=$cluster_name', 'host=~${host:regex}', 'name=service.elastic.gc_collectors_old_collection_time_in_millis')), 'perSecond', ''), 'host', 'name'), '.service.elastic.', ':')"
      }
     ]
    },
    {
     "title": "old count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasByTags(aliasSub(perSecond(seriesByTag('contur=${contur:regex}', 'clustername=$cluster_name', 'host=~${host:regex}', 'name=service.elastic.gc_collectors_old_collection_count')), 'perSecond', ''), 'host', 'name'), '.service.elastic.', ':')"
      }
     ]
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Write threads",
   "type": "graph",
   "description": "Потоки на запись. Показывает активности записи и очередь на запись.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasSub(aliasByTags(seriesByTag('contur=${contur:regex}', 'clustername=$cluster_name', 'host=~${host:regex}', 'name=~service.elastic.write_active', 'node_roles=~.*data.*'), 'name', 'host'), '.unix.tensor.ru', ''), 3, 2)"
    },
    {
     "target": "aliasByNode(aliasSub(aliasByTags(seriesByTag('contur=${contur:regex}', 'clustername=$cluster_name', 'host=~${host:regex}', 'name=~service.elastic.write_queue', 'node_roles=~.*data.*'), 'name', 'host'), '.unix.tensor.ru', ''), 3, 2)"
    }
   ]
  },
  {
   "title": "Search threads",
   "type": "graph",
   "description": "Потоки на поиск.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasSub(aliasByTags(seriesByTag('contur=${contur:regex}', 'clustername=$cluster_name', 'host=~${host:regex}', 'name=~service.elastic.search_active', 'node_roles=~.*data.*'), 'name', 'host'), '.unix.tensor.ru', ''), 3, 2)"
    },
    {
     "target": "aliasByNode(aliasSub(aliasByTags(seriesByTag('contur=${contur:regex}', 'clustername=$cluster_name', 'host=~${host:regex}', 'name=~service.elastic.search_queue', 'node_roles=~.*data.*'), 'name', 'host'), '.unix.tensor.ru', ''), 3, 2)"
    }
   ]
  },
  { "title": "Memory pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "young",
   "type": "graph",
   "description": "Использованная память в байтах в пуле young.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('clustername=$cluster_name', 'host=~${host:regex}', 'contur=${contur:regex}', 'name=~service.elastic.mem_pools_young_used_in_bytes', 'node_roles=~.*data.*'), 'host', 'name'), 'unix.tensor.ru', ':')"
    }
   ]
  },
  {
   "title": "old",
   "type": "graph",
   "description": "Использованная память в байтах в пуле old.",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('clustername=$cluster_name', 'host=~${host:regex}', 'contur=${contur:regex}', 'name=~service.elastic.mem_pools_old_used_in_bytes'), 'host', 'name'), 'unix.tensor.ru', ':')"
    }
   ]
  },
  {
   "title": "survivor",
   "type": "graph",
   "description": "Использованная память в байтах в пуле survivor.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('clustername=$cluster_name', 'host=~${host:regex}', 'contur=${contur:regex}', 'name=~service.elastic.mem_pools_survivor_used_in_bytes', 'node_roles=~.*data.*'), 'host', 'name'), 'unix.tensor.ru', ':')"
    }
   ]
  },
  { "title": "Node JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Сколько милисекунд назад запущен процесс jvm.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.jvm_max_uptime_in_millis', 'contur=${contur:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "gauge",
   "description": "Свободно в куче. Высчитывается как процент от лимита к использованному в байтах. ",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(asPercent(aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.jvm_mem_heap_used_in_bytes', 'contur=${contur:regex}'), 'host'), #C))",
     "targetFull": "sumSeries(asPercent(aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.jvm_mem_heap_used_in_bytes', 'contur=${contur:regex}'), 'host'), sumSeries(aliasByTags(seriesByTag('clustername=$cluster_name', 'name=service.elastic.jvm_mem_heap_max_in_bytes', 'contur=${contur:regex}'), 'host'))))"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "description": "Размер кучи в байтах.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sumSeries(seriesByTag('clustername=$cluster_name', 'name=service.elastic.jvm_mem_heap_used_in_bytes', 'contur=${contur:regex}')), 'host')"
    }
   ]
  }
 ]
}