{
 "title": "HL/HA — REDIS",
 "description": "Тесты. Ответственный:  Конюхов М.В. (Эксплуатация)",
 "tags": [
  "telegraf",
  "service",
  "redis",
  "mv.konuhov",
  "hlha"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   { "name": "servertype", "label": "Тип", "query": "redis" },
   {
    "name": "host",
    "label": "Сервер",
    "query": "tag_values(host,contur=$contur,servertype=$servertype)"
   },
   {
    "name": "port",
    "label": "Порт",
    "query": "tag_values(port,contur=$contur,servertype=$servertype,host=$host)"
   }
  ]
 },
 "panels": [
  { "title": "Сервер", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Использование ЦПУ",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "exclude(exclude(aliasByTags(seriesByTag('name=~system.cpu.*', 'cpu=cpu-total', 'host=$host'), 'name'), 'idle'), 'active')"
    }
   ]
  },
  {
   "title": "LA",
   "type": "graph",
   "description": "LA 1 5 15",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=system.system.n_cpus', 'host=$host'), 'CPU')"
    },
    {
     "target": "consolidateBy(alias(seriesByTag('name=system.system.load1', 'host=$host'), 'la1'), 'maximum')"
    },
    {
     "target": "alias(seriesByTag('name=system.system.load5', 'host=$host'), 'la5')"
    },
    {
     "target": "alias(seriesByTag('name=system.system.load15', 'host=$host'), 'la15')"
    }
   ]
  },
  {
   "title": "Context switches",
   "type": "graph",
   "description": "Переключение контекста",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=system.kernel.context_switches', 'host=$host')), 'name'))"
    }
   ]
  },
  {
   "title": "CPU IOWAIT",
   "type": "graph",
   "description": "CPU IOWAIT",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(seriesByTag('name=system.cpu.usage_iowait', 'cpu=cpu-total', 'host=$host'), 'name'))"
    }
   ]
  },
  {
   "title": "Память",
   "type": "graph",
   "description": "Использование памяти",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.used'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.free'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.shared'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.buffered'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.cached'), 'name')), 'max')"
    }
   ]
  },
  {
   "title": "Диски",
   "type": "bargauge",
   "description": "Состояние дисков",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=system.disk.used_percent', 'host=$host'), 'path'), '-', '/')"
    }
   ]
  },
  {
   "title": "Сетевой стек",
   "type": "graph",
   "description": "Состояния сетевых сокетовв",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=~system.netstat.tcp_*'), 'name'))"
    }
   ]
  },
  {
   "title": "Память",
   "type": "graph",
   "description": "Использование памяти",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByMetric(seriesByTag('host=$host', 'name=system.mem.available')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(seriesByTag('host=$host', 'name=system.mem.total')), 'max')"
    },
    {
     "target": "alias(consolidateBy(aliasByMetric(nonNegativeDerivative(seriesByTag('host=$host', 'name=system.mem.available'))), 'max'), 'avlder')"
    }
   ]
  },
  { "title": "REDIS ${port}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "port" },
  {
   "title": "REDIS - COMMAND's",
   "type": "gauge",
   "description": "Среднее кол-во команд",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "perSecond(aliasByTags(seriesByTag('name=redis.total_commands_processed', 'host=$host', 'port=${port:regex}'), 'name'))"
    }
   ]
  },
  {
   "title": "REDIS - SLAVES",
   "type": "stat",
   "description": "Кол-во слейвов",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=redis.connected_slaves', 'host=$host', 'port=${port:regex}'), 'name')"
    }
   ]
  },
  {
   "title": "Ключей в БД",
   "type": "graph",
   "description": "Кол-во ключей",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=redis.keys', 'host=$host', 'port=${port:regex}'), 'name')"
    }
   ]
  },
  {
   "title": "Ключи в динамике",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "derivative(aliasByTags(seriesByTag('name=redis.keys', 'host=$host', 'port=${port:regex}'), 'name'))"
    }
   ]
  },
  {
   "title": "Команды",
   "type": "graph",
   "description": "Кол-во ключей",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=redis.total_commands_processed', 'host=$host', 'port=~${port:regex}')), 1)"
    }
   ]
  },
  {
   "title": "Вытесненные ключи",
   "type": "graph",
   "description": "Кол-во ключей",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=redis.evicted_keys', 'host=$host', 'port=${port:regex}')), 'name')"
    }
   ]
  },
  {
   "title": "Использование памяти",
   "type": "graph",
   "description": "Использование памяти.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~redis.used_memory.*', 'host=$host', 'port=${port:regex}'), 'name')"
    }
   ]
  },
  {
   "title": "Подключения",
   "type": "graph",
   "description": "Кол-во ключей",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=redis.total_connections_received', 'host=$host', 'port=~${port:regex}')), 1)"
    }
   ]
  },
  {
   "title": "REDIS - HIT/MISS",
   "type": "graph",
   "description": "Использовано памяти",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~redis.keyspace_hits', 'host=$host', 'port=${port:regex}')), 'name')"
    },
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~redis.keyspace_misses', 'host=$host', 'port=${port:regex}')), 'name')"
    }
   ]
  },
  {
   "title": "REDIS - HITRATE",
   "type": "graph",
   "description": "Использовано памяти",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~redis.keyspace_hitrate', 'host=$host', 'port=${port:regex}'), 'name')"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "description": "Использовано памяти",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~redis.instantaneous_ops_per_sec', 'host=$host', 'port=${port:regex}'), 1)"
    }
   ]
  },
  {
   "title": "Клиенты",
   "type": "graph",
   "description": "Кол-во клиентов.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=redis.clients', 'host=$host', 'port=${port:regex}'), 1)"
    },
    {
     "target": "aliasByTags(seriesByTag('name=redis.blocked_clients', 'host=$host', 'port=${port:regex}'), 1)"
    },
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=redis.rejected_connections', 'host=$host', 'port=${port:regex}')), 1)"
    }
   ]
  },
  {
   "title": "REDIS - CMDSTAT CALLS",
   "type": "graph",
   "description": "Кол-во вызовов",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(perSecond(seriesByTag('host=$host', 'port=~${port:regex}', 'command=~*', 'name=redis.calls')), 'command'))"
    }
   ]
  },
  {
   "title": "REDIS - CMDSTAT USEC",
   "type": "graph",
   "description": "Время задержки запросов.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(perSecond(seriesByTag('host=$host', 'port=~${port:regex}', 'command=~*', 'name=redis.usec')), 'command'))"
    }
   ]
  }
 ]
}