{
 "title": "HL/HA — K8S — ROUTER",
 "description": "Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "k8s",
  "prometheus",
  "hlha"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   { "name": "servertype", "query": "dispatcher" },
   {
    "name": "namespace",
    "query": "tag_values(namespace,contur=prod,servertype=$servertype)"
   },
   {
    "name": "cluster",
    "query": "tag_values(cluster,namespace=$namespace)"
   },
   {
    "name": "domain",
    "query": "tag_values(domain,namespace=$namespace)"
   },
   {
    "name": "host",
    "label": "Pod",
    "query": "tag_values(pod,namespace=$namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "NGINX - Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(perSecond(seriesByTag('name=prometheus_remote_write.nginx_requests_total', 'pod=~${host:regex}', 'domain=~${domain:regex}')), 'sum', 'name', 'pod'), 'pod')"
    }
   ]
  },
  {
   "title": "Запросы в сервисы",
   "type": "graph",
   "description": "Кол-во запросов в секунду",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "highestMax(aliasByTags(sortByMaxima(groupByTags(perSecond(seriesByTag('name=prometheus_remote_write.nginx_requests_total', 'pod=~${host:regex}', 'domain=~${domain:regex}')), 'sum', 'systemname')), 'systemname'), 12)"
    }
   ]
  },
  {
   "title": "Запросы в домены",
   "type": "graph",
   "description": "Кол-во запросов в секунду",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(groupByTags(perSecond(seriesByTag('name=prometheus_remote_write.nginx_requests_total', 'pod=~${host:regex}')), 'sum', 'domain'), 'domain'))"
    }
   ]
  },
  {
   "title": "Подключения к nginx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(perSecond(seriesByTag('name=prometheus_remote_write.nginx_connections', 'pod=~${host:regex}', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}')), 'sum', 'state'), 'state')"
    }
   ]
  }
 ]
}