{
 "title": "HL/HA — ROUTER CLUSTER",
 "description": "Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "hlha_router",
  "prometheus",
  "hlha"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   { "name": "servertype", "label": "Тип", "query": "dispatcher" },
   {
    "name": "cluster",
    "label": "Кластер",
    "query": "tag_values(cluster,contur=prod,servertype=$servertype)"
   }
  ]
 },
 "panels": [
  {
   "title": "NGINX - Запросы в диспетчера",
   "type": "graph",
   "description": "Кол-во запросов в секунду",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(perSecond(seriesByTag('name=nginx.requests', 'cluster=~${cluster:regex}')), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Домены и сервисы",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "NGINX - Запросы в домены",
     "type": "graph",
     "description": "Кол-во запросов в секунду",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "target": "aliasByTags(sortByMaxima(groupByTags(perSecond(seriesByTag('name=prometheus.nginx_requests_total', 'cluster=~${cluster:regex}', 'domain!=')), 'sum', 'domain')), 'domain')"
      }
     ]
    },
    {
     "title": "NGINX - Запросы в сервисы",
     "type": "graph",
     "description": "Кол-во запросов в секунду",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "target": "highestMax(aliasByTags(sortByMaxima(groupByTags(perSecond(seriesByTag('name=prometheus.nginx_requests_total', 'cluster=~${cluster:regex}')), 'sum', 'systemname')), 'systemname'), 12)"
      }
     ]
    }
   ]
  }
 ]
}