{
 "title": "HL/HA — SYSTEM",
 "description": "Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "hlha",
  "telegraf",
  "system",
  "mv.konuhov"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "servertype",
    "label": "Тип",
    "query": "tag_values(servertype,name=system.system.n_cpus,contur=$contur)"
   },
   {
    "name": "host",
    "label": "Сервер",
    "query": "tag_values(host,contur=$contur,servertype=~${servertype:regex})"
   }
  ]
 },
 "panels": [
  { "title": "SYSTEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ЦПУ",
   "type": "stat",
   "description": "Кол-во ядер в системе",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=system.system.n_cpus', 'host=$host')"
    }
   ]
  },
  {
   "title": "Память",
   "type": "stat",
   "description": "Кол-во памяти в системе",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=system.mem.total', 'host=$host')"
    }
   ]
  },
  {
   "title": "UpTime",
   "type": "stat",
   "description": "Время работы сервера",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=system.system.uptime', 'host=$host')"
    }
   ]
  },
  {
   "title": "KIR",
   "type": "stat",
   "description": "Прерывания в ядре",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "perSecond(seriesByTag('name=system.kernel.interrupts', 'host=$host'))"
    }
   ]
  },
  {
   "title": "Система",
   "type": "bargauge",
   "description": "Общее состояние системы",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('name=system.cpu.usage_active', 'cpu=cpu-total', 'host=$host'), 'CPU active')"
    },
    {
     "target": "alias(seriesByTag('name=system.mem.used_percent', 'host=$host'), 'Memory used')"
    },
    {
     "target": "alias(seriesByTag('name=system.swap.used_percent', 'host=$host'), 'Swap used')"
    }
   ]
  },
  {
   "title": "Диски",
   "type": "bargauge",
   "description": "Состояние дисков",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=system.disk.used_percent', 'host=$host'), 'path'), '-', '/')"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Трафик",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=~system.net.bytes.*', 'host=$host', 'interface=~ens*')), 'name'))"
    }
   ]
  },
  {
   "title": "Сетевой стек",
   "type": "graph",
   "description": "Состояния сетевых сокетовв",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=~system.netstat.tcp_*'), 'name'))"
    }
   ]
  },
  {
   "title": "LA",
   "type": "graph",
   "description": "LA 1 5 15",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=system.system.n_cpus', 'host=$host'), 'CPU')"
    },
    {
     "target": "consolidateBy(alias(seriesByTag('name=system.system.load1', 'host=$host'), 'la1'), 'maximum')"
    },
    {
     "target": "alias(seriesByTag('name=system.system.load5', 'host=$host'), 'la5')"
    },
    {
     "target": "alias(seriesByTag('name=system.system.load15', 'host=$host'), 'la15')"
    }
   ]
  },
  {
   "title": "Диски % занято",
   "type": "graph",
   "description": "Занятость дисков",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=system.disk.used_percent', 'host=$host'), 'path'), '-', '/')"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~system.disk', 'host=$host', '_name=~(sd.$|mpath.)')), '_name', 'name')"
    }
   ]
  },
  {
   "title": "Ожидание ЦПУ",
   "type": "graph",
   "description": "Ожидание ЦПУ",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(seriesByTag('name=system.cpu.usage_iowait', 'cpu=cpu-total', 'host=$host'), 'name'))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Использование ЦПУ",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "exclude(exclude(aliasByTags(seriesByTag('name=~system.cpu.*', 'cpu=cpu-total', 'host=$host'), 'name'), 'idle'), 'active')"
    }
   ]
  },
  {
   "title": "Память",
   "type": "graph",
   "description": "Использование памяти",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.used'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.free'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.shared'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.buffered'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.cached'), 'name')), 'max')"
    }
   ]
  },
  {
   "title": "Переключение контекста",
   "type": "graph",
   "description": "Переключение контекста",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=system.kernel.context_switches', 'host=$host')), 'name'))"
    }
   ]
  },
  {
   "title": "Память",
   "type": "graph",
   "description": "Использование памяти.\nВсего памяти, доступно памяти, avlder(nonNegativeDerivative функция от доступной памяти, то есть колебания доступной памяти)\n\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByMetric(seriesByTag('host=$host', 'name=system.mem.available')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(seriesByTag('host=$host', 'name=system.mem.total')), 'max')"
    },
    {
     "target": "alias(consolidateBy(aliasByMetric(nonNegativeDerivative(seriesByTag('host=$host', 'name=system.mem.available'))), 'max'), 'avlder')"
    }
   ]
  },
  {
   "title": "Диск чтение/запись",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(perSecond(seriesByTag('name=~system.diskio.(read|write)_bytes', 'host=$host', '_name=~(sd?|mpath?)')), 'name', '_name'), 3, 2)"
    }
   ]
  },
  {
   "title": "Inode занято",
   "type": "graph",
   "description": "inodes_free (integer, files)\ninodes_total (integer, files)\ninodes_used (integer, files)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(asPercent(aliasByTags(seriesByTag('name=system.disk.inodes_used', 'host=$host', 'contur=${contur:regex}'), 2, 'path'), #B), 1))",
     "targetFull": "sortByMaxima(aliasByNode(asPercent(aliasByTags(seriesByTag('name=system.disk.inodes_used', 'host=$host', 'contur=${contur:regex}'), 2, 'path'), sortByMaxima(aliasByTags(seriesByTag('name=system.disk.inodes_total', 'host=$host', 'contur=${contur:regex}'), 2, 'path'))), 1))"
    }
   ]
  },
  {
   "title": "Диски занято",
   "type": "graph",
   "description": "Для оценки использования дисков в байтах",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "aliasSub(aliasByTags(seriesByTag('name=system.disk.used', 'host=$host', 'servertype=${servertype:regex}'), 'path'), '-', '/')"
    }
   ]
  },
  {
   "title": "Network Traffic Packets",
   "type": "graph",
   "description": "Сетевой трафик в пакетах",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=~system.net.packets_*', 'host=$host', 'interface=~(ens|eth)*')), 'name'))"
    }
   ]
  },
  {
   "title": "Network Error(s)",
   "type": "graph",
   "description": "Сетевые ошибки",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~system.net.err_(.+)', 'host=$host')), 'name')"
    }
   ]
  },
  {
   "title": "Network Traffic Bytes",
   "type": "graph",
   "description": "Сетевой трафик в байтах",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=~system.net.bytes.*', 'host=$host', 'interface=~(ens|eth)*')), 'name'))"
    }
   ]
  },
  {
   "title": "TCP stats",
   "type": "graph",
   "description": "Состояние ТСП стека",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "exclude(exclude(aliasByTags(perSecond(seriesByTag('name=~system.net.tcp', 'host=$host')), 'name'), 'insegs'), 'outsegs')"
    }
   ]
  },
  {
   "title": "Network ICMP",
   "type": "graph",
   "description": "Состояние ICMP стека",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(perSecond(seriesByTag('name=~system.net.icmp_.+', 'host=$host')), 'max'), 'name')"
    }
   ]
  },
  {
   "title": "Network TCP CLOSE-WAIT",
   "type": "graph",
   "description": "Не закрытые TCP соединения",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~system.netstat.tcp_close_wait', 'host=$host'), 'name')"
    }
   ]
  },
  {
   "title": "Network TCP SYN",
   "type": "graph",
   "description": "Очередь SYN пакетов",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=~system.netstat.tcp_syn_.+', 'host=$host'), 'max'), 'name')"
    }
   ]
  },
  { "title": "NET", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Network TCP NETSTAT",
   "type": "graph",
   "description": "Очередь SYN пакетов",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(aliasByTags(consolidateBy(seriesByTag('name=~system.netstat.*', 'host=$host'), 'max'), 'name'), 2))"
    }
   ]
  },
  {
   "title": "Network NET BYTES",
   "type": "graph",
   "description": "Очередь SYN пакетов",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(aliasByTags(consolidateBy(perSecond(seriesByTag('name=~system.net.bytes*', 'host=$host')), 'max'), 'interface', 'name'), 0, 3))"
    }
   ]
  },
  {
   "title": "Network NET DROP",
   "type": "graph",
   "description": "Очередь SYN пакетов",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(aliasByTags(consolidateBy(perSecond(seriesByTag('name=~system.net.drop*', 'host=$host')), 'max'), 'interface', 'name'), 0, 3))"
    }
   ]
  },
  {
   "title": "Network NET ERR",
   "type": "graph",
   "description": "Очередь SYN пакетов",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(aliasByTags(consolidateBy(perSecond(seriesByTag('name=~system.net.err*', 'host=$host')), 'max'), 'interface', 'name'), 0, 3))"
    }
   ]
  },
  {
   "title": "Network NET PACKETS",
   "type": "graph",
   "description": "Очередь SYN пакетов",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(aliasByTags(consolidateBy(perSecond(seriesByTag('name=~system.net.packets*', 'host=$host')), 'max'), 'interface', 'name'), 0, 3))"
    }
   ]
  },
  {
   "title": "Network NET IP",
   "type": "graph",
   "description": "Очередь SYN пакетов",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(consolidateBy(perSecond(seriesByTag('name=~system\\.net\\.ip_*', 'host=$host')), 'max'), 'interface', 'name'), 0, 3)"
    }
   ]
  },
  {
   "title": "Network NET TCP",
   "type": "graph",
   "description": "Очередь SYN пакетов",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(consolidateBy(perSecond(seriesByTag('name=~system.net.tcp*', 'host=$host')), 'max'), 'interface', 'name'), 0, 3)"
    }
   ]
  },
  {
   "title": "Network NET UDP",
   "type": "graph",
   "description": "Очередь SYN пакетов",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(consolidateBy(perSecond(seriesByTag('name=~system\\.net\\.udp_*', 'host=$host')), 'max'), 'interface', 'name'), 0, 3)"
    }
   ]
  }
 ]
}