{
 "title": "HL/HA — REDIS - 2",
 "description": "Ответственный:  Конюхов М.В. (Эксплуатация)",
 "tags": [
  "service",
  "telegraf",
  "redis",
  "mv.konuhov",
  "hlha"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "tag_values(host,servertype=redis,contur=prod)"
   },
   {
    "name": "port",
    "query": "tag_values(port,host=~${server:regex})"
   },
   { "name": "role", "query": "master,slave" }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Operations per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.instantaneous_ops_per_sec', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "instantaneous Input, kbps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.instantaneous_input_kbps', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "instantaneous Output, kbps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.instantaneous_output_kbps', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Connected clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(groupByTags(seriesByTag('servertype=redis', 'name=redis.clients', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'sum', 'name'), 'host', 'port'), 0, 4)"
    }
   ]
  },
  {
   "title": "Blocked clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.blocked_clients', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Rejected connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(nonNegativeDerivative(seriesByTag('servertype=redis', 'name=redis.rejected_connections', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}')), 'sum', 'name'), 'host', 'port')"
    }
   ]
  },
  { "title": "Keyspace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Keys total",
   "type": "graph",
   "description": "Total keys in db",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.keys', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Keyspace hits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.keyspace_hits', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Keyspace miss",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.keyspace_misses', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Keyspace hitrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.keyspace_hitrate', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Keys expires",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.keys', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Keys avg_ttl",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.avg_ttl', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.used_memory', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Used Memory Rss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.used_memory_rss', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Used Memory Peak",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.used_memory_peak', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Memory fragmentation ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.mem_fragmentation_ratio', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Maxmemory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.maxmemory', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Used CPU Sys",
   "type": "graph",
   "description": "CPU time (expressed in seconds) accumulated since the launch of the Redis instance, as reported by the getrusage() call.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.used_cpu_sys', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Used CPU User",
   "type": "graph",
   "description": "CPU time (expressed in seconds) accumulated since the launch of the Redis instance, as reported by the getrusage() call.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.used_cpu_user', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "used_cpu_sys_children",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.used_cpu_sys_children', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  }
 ]
}