{
 "title": "HL/HA — ROUTER",
 "description": "Мониторинг диспетчера на уровне nginx. Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "hlha_router",
  "prometheus",
  "hlha"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "servertype", "label": "Тип", "query": "dispatcher" },
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "cluster",
    "label": "Кластер",
    "query": "tag_values(cluster,contur=prod,servertype=$servertype)"
   },
   {
    "name": "host",
    "label": "Хост",
    "query": "tag_values(host,cluster=$cluster,contur=prod,servertype=$servertype)"
   }
  ]
 },
 "panels": [
  {
   "title": "NGINX",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=nginx.requests', 'host=~${host:regex}')), 'host')"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=nginx.pid_count', 'host=~${host:regex}'), 'workers')"
    },
    {
     "target": "aliasByMetric(seriesByTag('name=system.system.n_cpus', 'host=~${host:regex}'))"
    }
   ]
  },
  {
   "title": "PID",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~${host:regex}', 'file=-var-run-nginx-nginx.pid', 'name=filestat.exists'), 'name')"
    },
    {
     "target": "aliasByTags(seriesByTag('host=~${host:regex}', 'file=-var-run-nginx-nginx.pid', 'name=filestat.size_bytes'), 'name')"
    }
   ]
  },
  {
   "title": "LIMITS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Лимитные запросы",
     "type": "graph",
     "description": "Запросы",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "target": "aliasByTags(sortByMaxima(groupByTags(perSecond(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_limits', 'cmd=PASSED')), 'sum', 'domain', 'cmd')), 'domain', 'cmd')"
      }
     ]
    },
    {
     "title": "Лимитные запросы",
     "type": "graph",
     "description": "Запросы",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_limits', 'cmd=REJECTED')), 'domain', 'cmd')"
      }
     ]
    }
   ]
  },
  {
   "title": "Диспетчер - NGINX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Запросы в домены",
     "type": "graph",
     "description": "Кол-во запросов в секунду",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(groupByTags(perSecond(seriesByTag('name=prometheus.nginx_requests_total', 'host=~${host:regex}', 'domain!=')), 'sum', 'domain'), 'domain'))"
      }
     ]
    },
    {
     "title": "Запросы в сервисы",
     "type": "graph",
     "description": "Кол-во запросов в секунду",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "target": "highestMax(sortByMaxima(aliasByTags(groupByTags(perSecond(seriesByTag('name=prometheus.nginx_requests_total', 'host=~${host:regex}')), 'sum', 'systemname'), 'systemname')), 12)"
      }
     ]
    },
    {
     "title": "Запросы RC CMD",
     "type": "graph",
     "description": "Запросы",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "target": "aliasByTags(sortByMaxima(groupByTags(perSecond(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_rc_cmd')), 'sum', 'cmd')), 'cmd')"
      }
     ]
    },
    {
     "title": "Запросы JSON",
     "type": "graph",
     "description": "Запросы",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "target": "aliasByTags(groupByTags(perSecond(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_json')), 'sum', 'cmd'), 'cmd')"
      }
     ]
    },
    {
     "title": "Запросы RC ERR",
     "type": "graph",
     "description": "Запросы",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "target": "aliasByTags(aliasByTags(sortByMaxima(consolidateBy(groupByTags(nonNegativeDerivative(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_rc_err')), 'sum', 'host', 'error'), 'max')), 'host', 'error'), 0, 4)"
      }
     ]
    },
    {
     "title": "Запросы EGGS",
     "type": "graph",
     "description": "Запросы",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_disp')), 'cmd'))"
      }
     ]
    },
    {
     "title": "Запросы REDIS",
     "type": "graph",
     "description": "Запросы",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_redis')), 'cmd'))"
      }
     ]
    }
   ]
  },
  {
   "title": "Диспетчер - ресурсы",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "NET - Входящий трафик",
     "type": "graph",
     "description": "bytes_recv",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "scale(sortByMaxima(aliasByTags(perSecond(seriesByTag('name=system.net.bytes_recv', 'host=~${host:regex}')), 'host')), 8)"
      }
     ]
    },
    {
     "title": "NET - Исходящий трафик",
     "type": "graph",
     "description": "bytes_sent",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "scale(sortByMaxima(aliasByTags(perSecond(seriesByTag('name=system.net.bytes_sent', 'host=~${host:regex}')), 'host')), 8)"
      }
     ]
    },
    {
     "title": "LA",
     "type": "graph",
     "description": "LA 1 5 15",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('name=system.system.n_cpus', 'host=~${host:regex}'), 'CPU')"
      },
      {
       "target": "consolidateBy(alias(seriesByTag('name=system.system.load1', 'host=~${host:regex}'), 'la1'), 'max')"
      },
      {
       "target": "consolidateBy(alias(seriesByTag('name=system.system.load5', 'host=~${host:regex}'), 'la5'), 'max')"
      },
      {
       "target": "consolidateBy(alias(seriesByTag('name=system.system.load15', 'host=~${host:regex}'), 'la15'), 'max')"
      }
     ]
    },
    {
     "title": "СЕТЬ / TCP",
     "type": "graph",
     "description": "Очередь SYN пакетов",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=~system.netstat.*', 'host=~${host:regex}'), 'name')"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "description": "Процент загруженности ядра.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "exclude(exclude(aliasByTags(seriesByTag('name=~system.cpu.*', 'cpu=cpu-total', 'host=~${host:regex}'), 'name'), 'idle'), 'active')"
      }
     ]
    },
    {
     "title": "Network Traffic Packets",
     "type": "graph",
     "description": "Количество входящего/исходящего трафика.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=~system.net.packets_*', 'host=~${host:regex}', 'interface=~ens*')), 'name'))"
      }
     ]
    }
   ]
  },
  {
   "title": "Диспетчер - MEMCACHED",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "UpTime",
     "type": "stat",
     "description": "Время работы сервера",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "target": "seriesByTag('name=memcached.uptime', 'host=~${host:regex}')"
      }
     ]
    },
    {
     "title": "MEMCACHE - ITEMS",
     "type": "graph",
     "description": "Кол-во ключей",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('name=memcached.curr_items', 'host=~${host:regex}'), 'items')"
      }
     ]
    },
    {
     "title": "MEMCACHE -CONNECTIONS",
     "type": "graph",
     "description": "Кол-во ключей",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Все" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=memcached.total_connections', 'host=~${host:regex}')), 'name'))"
      },
      {
       "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=memcached.accepting_conns', 'host=~${host:regex}')), 'name'))"
      },
      {
       "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=memcached.curr_connections', 'host=~${host:regex}')), 'name'))"
      }
     ]
    },
    {
     "title": "MEMCACHE - GET/SET",
     "type": "graph",
     "description": "Кол-во GET и SET команд",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=memcached.cmd_get', 'host=~${host:regex}')), 'name'))"
      },
      {
       "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=memcached.cmd_set', 'host=~${host:regex}')), 'name'))"
      }
     ]
    },
    {
     "title": "MEMCACHE - RW",
     "type": "graph",
     "description": "Объем чтения/записи в байтах",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(perSecond(seriesByTag('name=memcached.bytes_read', 'host=~${host:regex}')), 'read')"
      },
      {
       "target": "alias(perSecond(seriesByTag('name=memcached.bytes_written', 'host=~${host:regex}')), 'written')"
      }
     ]
    }
   ]
  }
 ]
}