{
 "title": "HL/HA — K8S — VARNISH",
 "description": "Комплексный экран по кэширующему кластеру Varnish. Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "telegraf",
  "varnish",
  "service",
  "hlha",
  "mv.konuhov",
  "k8s"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Кластер", "query": "prod2" },
   { "name": "contur", "label": "Контур", "query": "prod" },
   { "name": "servertype", "label": "Тип", "query": "varnish" },
   {
    "name": "cachecluster",
    "label": "Кластер",
    "query": "tag_values(cachecluster,contur=prod,servertype=${servertype:regex},name=prometheus_remote_write.up)"
   }
  ]
 },
 "panels": [
  { "title": "K8S", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Запросы HAPROXY суммарно",
   "type": "timeseries",
   "description": "Сколько запросов пришло от клиентов\nHaproxy используется только в некоторых кластерах",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "alias(perSecond(groupByTags(keepLastValue(seriesByTag('name=prometheus_remote_write.haproxy_frontend_http_responses_total', 'cachecluster=${cachecluster:regex}', 'cluster=~${cluster:regex}'), 1), 'sum', 'cachecluster')), 'rps')"
    }
   ]
  },
  {
   "title": "Запросы HAPROXY - PODs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps", "label": "Request(s)" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(perSecond(keepLastValue(seriesByTag('name=prometheus_remote_write.haproxy_frontend_http_responses_total', 'cachecluster=${cachecluster:regex}', 'cluster=~${cluster:regex}'), 1)), 'sum', 'pod'), 'cluster', 'pod')"
    }
   ]
  },
  {
   "title": "Запросы NGINX суммарно",
   "type": "timeseries",
   "description": "Сколько запросов пришло от клиентов",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "alias(perSecond(groupByTags(keepLastValue(seriesByTag('name=prometheus_remote_write.nginx_http_requests_total', 'cachecluster=${cachecluster:regex}','cluster=~${cluster:regex}'), 1), 'sum', 'cachecluster')), 'rps')"
    }
   ]
  },
  {
   "title": "Запросы NGINX - PODs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "reqps", "label": "Request(s)" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(keepLastValue(seriesByTag('name=prometheus_remote_write.nginx_http_requests_total', 'cachecluster=${cachecluster:regex}', 'cluster=~${cluster:regex}'), 1)), 'cluster', 'pod')"
    }
   ]
  },
  {
   "title": "Запросы VARNISH суммарно",
   "type": "timeseries",
   "description": "Сколько запросов ушло на варниш",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "alias(perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.varnish_main_client_req', 'cachecluster=~${cachecluster:regex}','cluster=~${cluster:regex}'), 'sum', 'cachecluster')), 'rps')"
    }
   ]
  },
  {
   "title": "Запросы VARNISH - PODs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "reqps", "label": "Request(s)" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(keepLastValue(seriesByTag('name=prometheus_remote_write.varnish_main_client_req', 'cachecluster=${cachecluster:regex}', 'cluster=~${cluster:regex}'), 1)), 'cluster', 'pod')"
    }
   ]
  },
  {
   "title": "POD(s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(groupByTags(keepLastValue(seriesByTag('cachecluster=${cachecluster:regex}', 'name=prometheus_remote_write.varnish_main_threads', 'cluster=~${cluster:regex}'), 1), 'count', 'cachecluster'), 'pod(s)')"
    }
   ]
  },
  { "title": "VARNISH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "VARNISH — Попадание в кеш ",
   "type": "graph",
   "description": "Соотношение попадания в кеш и промахов.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "alias(groupByTags(perSecond(seriesByTag('name=prometheus_remote_write.varnish_main_cache_hit', 'cachecluster=$cachecluster','cluster=~${cluster:regex}')), 'sum', 'cachecluster'), 'hit')"
    },
    {
     "target": "alias(groupByTags(perSecond(seriesByTag('name=prometheus_remote_write.varnish_main_cache_miss', 'cachecluster=$cachecluster','cluster=~${cluster:regex}')), 'sum', 'cachecluster'), 'miss')"
    }
   ]
  },
  {
   "title": "VARNISH — LRU",
   "type": "timeseries",
   "description": "Вытеснение ключей из кеша\n\nЕсли NUKED не ноль - кеш полон",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "alias(perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.varnish_main_n_lru_nuked', 'cachecluster=~${cachecluster:regex}','cluster=~${cluster:regex}'), 'sum', 'cachecluster')), 'nuked')"
    },
    {
     "target": "alias(perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.varnish_main_n_lru_moved', 'cachecluster=~${cachecluster:regex}','cluster=~${cluster:regex}'), 'sum', 'cachecluster')), 'moved')"
    },
    {
     "target": "alias(perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.varnish_main_n_lru_limited', 'cachecluster=~${cachecluster:regex}','cluster=~${cluster:regex}'), 'sum', 'cachecluster')), 'limited')"
    }
   ]
  },
  {
   "title": "VARNISH — Threads & Queue — TOTAL",
   "type": "graph",
   "description": "Сколько тредов использует варниш  и очередь тредов",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "target": "alias(groupByTags(seriesByTag('name=prometheus_remote_write.varnish_main_threads', 'cachecluster=${cachecluster:regex}','cluster=~${cluster:regex}'), 'sum', 'cachecluster'), 'threads')"
    },
    {
     "target": "alias(groupByTags(seriesByTag('name=prometheus_remote_write.varnish_main_thread_queue_len', 'cachecluster=${cachecluster:regex}','cluster=~${cluster:regex}'), 'sum', 'cachecluster'), 'queue')"
    }
   ]
  },
  {
   "title": "VARNISH — Threads STACK",
   "type": "graph",
   "description": "Сколько тредов использует варниш  стек поды",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=prometheus_remote_write.varnish_main_threads', 'cachecluster=${cachecluster:regex}', 'cluster=~${cluster:regex}'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "VARNISH — размер кеша подов",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes", "label": "Object(s)" }
   ],
   "targets": [
    {
     "target": "aliasByTags(keepLastValue(seriesByTag('name=prometheus_remote_write.varnish_sma_g_bytes', 'cachecluster=${cachecluster:regex}', 'cluster=~${cluster:regex}', 'type=mem'), 1), 'pod')"
    }
   ]
  },
  {
   "title": "VARNISH — Queue STACK",
   "type": "graph",
   "description": "Сколько очередь стек поды",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=prometheus_remote_write.varnish_main_thread_queue_len', 'cachecluster=${cachecluster:regex}', 'cluster=~${cluster:regex}'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "VARNISH — Backend request(s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "Object(s)" }
   ],
   "targets": [
    {
     "target": "perSecond(aliasByTags(keepLastValue(seriesByTag('name=~prometheus_remote_write.varnish_main_backend_req', 'cachecluster=${cachecluster:regex}', 'cluster=~${cluster:regex}'), 1), 'name'))"
    }
   ]
  },
  {
   "title": "VARNISH — Размер кеша",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(groupByTags(keepLastValue(seriesByTag('name=prometheus_remote_write.varnish_sma_g_bytes', 'cachecluster=${cachecluster:regex}', 'cluster=~${cluster:regex}'), 1), 'sum', 'cachecluster'), 'used')"
    },
    {
     "target": "alias(groupByTags(keepLastValue(seriesByTag('name=prometheus_remote_write.varnish_sma_g_space', 'cachecluster=${cachecluster:regex}', 'cluster=~${cluster:regex}'), 1), 'sum', 'cachecluster'), 'free')"
    }
   ]
  },
  {
   "title": "VARNISH — Backend fail(s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "Object(s)" }
   ],
   "targets": [
    {
     "target": "perSecond(aliasByTags(keepLastValue(seriesByTag('name=~prometheus_remote_write.varnish_main_backend_fail', 'cachecluster=${cachecluster:regex}', 'cluster=~${cluster:regex}'), 1), 'name'))"
    }
   ]
  },
  {
   "title": "VARNISH — объектов в поде",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes", "label": "Object(s)" }
   ],
   "targets": [
    {
     "target": "aliasByTags(keepLastValue(seriesByTag('name=prometheus_remote_write.varnish_main_n_object', 'cachecluster=${cachecluster:regex}', 'cluster=~${cluster:regex}'), 1), 'pod')"
    }
   ]
  }
 ]
}