{
 "title": "HL/HA — MEMCACHED",
 "description": "Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "hlha",
  "memcached"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "servertype", "query": "memcached" },
   { "name": "contur", "query": "prod" },
   {
    "name": "host",
    "label": "Хост",
    "query": "tag_values(host,contur=$contur,servertype=$servertype)"
   }
  ]
 },
 "panels": [
  {
   "title": "СЕТЬ / TCP",
   "type": "timeseries",
   "description": "Состояние TCP соединений",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(sortByMaxima(seriesByTag('name=~system.netstat.*', 'host=~${host:regex}')), 'name'), 2)"
    }
   ]
  },
  {
   "title": "Соединения",
   "type": "graph",
   "description": "struct — сколько структур выделено в мемкеше для приема коннектов. должна быть немного больше чем текучка.\n\nconnection — текущие коннекты",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('host=~${host:regex}', 'name=memcached.connection_structures', 'servertype=memcached'), 'struct')"
    },
    {
     "target": "alias(seriesByTag('host=~${host:regex}', 'name=memcached.curr_connections', 'servertype=memcached'), 'connection')"
    }
   ]
  },
  {
   "title": "Connection(s) RPS",
   "type": "graph",
   "description": "Скорость текущих подключений",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "alias(nonNegativeDerivative(seriesByTag('host=~${host:regex}', 'name=memcached.total_connections', 'servertype=memcached')), 'connections')"
    }
   ]
  },
  {
   "title": "Ключи",
   "type": "timeseries",
   "description": "Кол-во ключей в мемкеше",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(seriesByTag('host=~${host:regex}', 'name=memcached.curr_items', 'servertype=memcached'), 'items')"
    }
   ]
  },
  {
   "title": "GET/SET",
   "type": "graph",
   "description": "Команды чтения/записи",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('host=~${host:regex}', 'name=memcached.cmd_get', 'servertype=memcached')), 'get')"
    },
    {
     "target": "alias(perSecond(seriesByTag('host=~${host:regex}', 'name=memcached.cmd_set', 'servertype=memcached')), 'set')"
    }
   ]
  },
  {
   "title": "HIT/MISS",
   "type": "graph",
   "description": "Попадания/промахи в кеш",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('host=~${host:regex}', 'name=memcached.get_hits', 'servertype=memcached')), 'hit')"
    },
    {
     "target": "alias(perSecond(seriesByTag('host=~${host:regex}', 'name=memcached.get_misses', 'servertype=memcached')), 'miss')"
    }
   ]
  },
  {
   "title": "BYTES",
   "type": "graph",
   "description": "Размер кеша",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('host=~${host:regex}', 'name=memcached.bytes', 'servertype=memcached'), 'bytes')"
    }
   ]
  },
  {
   "title": "READ/WRITTEN",
   "type": "graph",
   "description": "Трафик чтения/записи",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('host=~${host:regex}', 'name=memcached.bytes_read', 'servertype=memcached')), 'read')"
    },
    {
     "target": "alias(perSecond(seriesByTag('host=~${host:regex}', 'name=memcached.bytes_written', 'servertype=memcached')), 'written')"
    }
   ]
  },
  {
   "title": "EVICTIONS",
   "type": "graph",
   "description": "Выселенные ключи когда не хватает места. Должно быть в ноль. Если не ноль - добавлять памяти memcached",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('host=~${host:regex}', 'name=memcached.evictions', 'servertype=memcached'), 'items')"
    }
   ]
  },
  {
   "title": "LA1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByNode(seriesByTag('name=system.system.load1', 'host=~${host:regex}'), 'host', 'name'), 0, 6)"
    },
    {
     "target": "aliasByNode(aliasByNode(seriesByTag('name=system.system.load5', 'host=~${host:regex}'), 'host', 'name'), 0, 6)"
    },
    {
     "target": "aliasByNode(aliasByNode(seriesByTag('name=system.system.load15', 'host=~${host:regex}'), 'host', 'name'), 0, 6)"
    },
    {
     "target": "aliasByNode(aliasByNode(seriesByTag('name=system.system.n_cpus', 'host=~${host:regex}'), 'host', 'name'), 0, 6)"
    }
   ]
  }
 ]
}