{
 "title": "HL/HA — FEATURE",
 "description": "Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "feature",
  "hlha"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "nginxcache", "label": "Тип", "query": "feature" },
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "host",
    "label": "Сервер",
    "query": "tag_values(host,contur=prod,nginxcache=$nginxcache)"
   }
  ]
 },
 "panels": [
  {
   "title": "Запросы по диспетчерам",
   "type": "graph",
   "description": "Сколько запросов пришло от клиентов и ушло на бакенды",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('name=nginx.requests', 'host=~${host:regex}')), 'host'), 0)"
    }
   ]
  },
  {
   "title": "RATIO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(perSecond(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_cache', 'status=HIT')), 'sum', 'status'), 'status')"
    },
    {
     "target": "aliasByTags(groupByTags(perSecond(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_cache', 'status=MISS')), 'sum', 'status'), 'status')"
    }
   ]
  },
  {
   "title": "Запросы в фичи — HIT",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "highestMax(sortByMaxima(aliasByTags(groupByTags(perSecond(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_cache', 'status=HIT')), 'sum', 'service'), 'service')), 14)"
    }
   ]
  },
  {
   "title": "Запросы в фичи — MISS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "highestMax(sortByMaxima(aliasByTags(groupByTags(perSecond(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_cache', 'status=MISS')), 'sum', 'service'), 'service')), 14)"
    }
   ]
  },
  {
   "title": "RATIO %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(perSecond(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_cache', 'status=HIT', 'domain=feature')), 'sum', 'status'), 'status')"
    },
    {
     "target": "aliasByTags(groupByTags(perSecond(seriesByTag('host=~${host:regex}', 'name=prometheus.nginx_cache', 'status=MISS', 'domain=feature')), 'sum', 'status'), 'status')"
    }
   ]
  },
  {
   "title": "Заполненность дискового кеша",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.disk.used_percent', 'path=-etc-nginx-cache', 'host=~${host:regex}'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "NOCACHE FEATURE",
   "type": "graph",
   "description": "Соотношение попадания в кеш и промахов.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "sortByMaxima(aliasByTags(groupByTags(perSecond(seriesByTag('name=~prometheus.nginx_cache', 'host=~${host:regex}', 'status=NOCACHE')), 'sum', 'service'), 'service'))"
    }
   ]
  },
  {
   "title": "Процент заполнения кеша < 25%",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "highestMax(minimumBelow(sortByMaxima(aliasByTags(groupByTags(seriesByTag('name=feature_dirstat.feature_proc', 'host=~${host:regex}'), 'average', 'service'), 'service')), 25), 20)"
    }
   ]
  },
  {
   "title": "Процент заполнения кеша > 75%",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "maximumAbove(highestMax(sortByMaxima(aliasByTags(groupByTags(seriesByTag('name=feature_dirstat.feature_proc', 'host=~${host:regex}'), 'average', 'service'), 'service')), 20), 75)"
    }
   ]
  }
 ]
}