{
 "title": "HL/HA — HLS TRAFIC",
 "description": "Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "hls",
  "hlha",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Хост",
    "query": "tag_values(host,nginxcachecluster=hls)"
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(aliasByTags(perSecond(seriesByTag('name=nginx.requests', 'host=~${host:regex}')), 'host'), 0))"
    }
   ]
  },
  {
   "title": "Входящий трафик",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(aliasByTags(scale(perSecond(seriesByTag('name=system.net.bytes_recv', 'host=~${host:regex}')), 8), 'host'), 0))"
    }
   ]
  },
  {
   "title": "Исходящий трафик",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(aliasByTags(scale(perSecond(seriesByTag('name=system.net.bytes_sent', 'host=~${host:regex}')), 8), 'host'), 0))"
    }
   ]
  }
 ]
}