{
 "title": "HL/HA — HLS",
 "description": "Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "hls",
  "hlha",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Хост",
    "query": "tag_values(host,nginxcachecluster=hls)"
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(aliasByTags(perSecond(seriesByTag('nginxcachecluster=hls', 'name=nginx-cache.r', 'host=~${host:regex}')), 'host'), 0))"
    }
   ]
  },
  {
   "title": "Среднее время ответа клиенту",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(divideSeriesLists(#B, #A)), 0)",
     "targetFull": "aliasByNode(sortByMaxima(divideSeriesLists(aliasByNode(aliasByTags(perSecond(seriesByTag('nginxcachecluster=hls', 'name=nginx-cache.rt', 'host=~${host:regex}')), 'host'), 0), aliasByNode(aliasByTags(perSecond(seriesByTag('nginxcachecluster=hls', 'name=nginx-cache.r', 'host=~${host:regex}')), 'host'), 0))), 0)"
    }
   ]
  },
  {
   "title": "Суммарное время получения с бакенда",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('nginxcachecluster=hls', 'name=nginx-cache.urt', 'host=~${host:regex}')), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Суммарное время отдачи клиентам",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(aliasByTags(perSecond(seriesByTag('nginxcachecluster=hls', 'name=nginx-cache.rt', 'host=~${host:regex}')), 'host'), 0))"
    }
   ]
  },
  {
   "title": "Отдано байт",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('nginxcachecluster=hls', 'name=nginx-cache.b', 'host=~${host:regex}')), 'host'), 0)"
    }
   ]
  }
 ]
}