{
 "title": "HL/HA — COORDINATOR",
 "description": "Тесты. Ответственный:  Конюхов М.В. (Эксплуатация)",
 "tags": [
  "hlha",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   { "name": "servertype", "label": "Тип", "query": "ipvscoordinator" },
   {
    "name": "host",
    "label": "Сервер",
    "query": "tag_values(host,contur=$contur,servertype=$servertype)"
   },
   {
    "name": "coordinatorcluster",
    "label": "Кластер",
    "query": "tag_values(coordinatorcluster,host=$host)"
   }
  ]
 },
 "panels": [
  { "title": "${coordinatorcluster}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "coordinatorcluster" },
  {
   "title": "STATUS",
   "type": "stat",
   "description": "Тип балансировки пула. \n> А - auto, M - manual",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(seriesByTag('contur=$contur', 'servertype=~${servertype:regex}', 'host=$host', 'coordinatorcluster=~${coordinatorcluster:regex}', 'name=coordinator.status'))"
    }
   ]
  },
  {
   "title": "SERVERS",
   "type": "stat",
   "description": "Кол-во серверов в пуле балансировщика",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(seriesByTag('contur=$contur', 'servertype=~${servertype:regex}', 'host=$host', 'coordinatorcluster=~${coordinatorcluster:regex}', 'name=coordinator.servers'))"
    }
   ]
  },
  {
   "title": "REBAL",
   "type": "stat",
   "description": "Кол-во серверов в пуле в ребалансировке\n> По умолчанию вес сервера в пуле равен 5. Когда оно начинает автоматом или при вводе в работу балансироваться, его вес может меняться с 1 до 5 постепенно",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(seriesByTag('contur=$contur', 'servertype=~${servertype:regex}', 'host=$host', 'coordinatorcluster=~${coordinatorcluster:regex}', 'name=coordinator.balance'))"
    }
   ]
  },
  {
   "title": "Coordinator Pool Stats",
   "type": "graph",
   "description": "Кол-во серверов в пуле в статусе DEL/LOCK/OFF\n> любое из них выше нуля означает, что в пуле не все идет гладко",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(seriesByTag('contur=$contur', 'servertype=~${servertype:regex}', 'host=$host', 'coordinatorcluster=~${coordinatorcluster:regex}', 'name=coordinator.del'))"
    },
    {
     "target": "aliasByMetric(seriesByTag('contur=$contur', 'servertype=~${servertype:regex}', 'host=$host', 'coordinatorcluster=~${coordinatorcluster:regex}', 'name=coordinator.lock'))"
    },
    {
     "target": "aliasByMetric(seriesByTag('contur=$contur', 'servertype=~${servertype:regex}', 'host=$host', 'coordinatorcluster=~${coordinatorcluster:regex}', 'name=coordinator.off'))"
    }
   ]
  },
  {
   "title": "Servers in rebalancing",
   "type": "graph",
   "description": "Кол-во серверов в пуле в ребалансировке\n> По умолчанию вес сервера в пуле равен 5. Когда оно начинает автоматом или при вводе в работу балансироваться, его вес может меняться с 1 до 5 постепенно",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(seriesByTag('contur=$contur', 'servertype=~${servertype:regex}', 'host=$host', 'coordinatorcluster=~${coordinatorcluster:regex}', 'name=coordinator.balance'))"
    }
   ]
  },
  {
   "title": "DEL",
   "type": "stat",
   "description": "Кол-во серверов в пуле в статусе DEL",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(seriesByTag('contur=$contur', 'servertype=~${servertype:regex}', 'host=$host', 'coordinatorcluster=~${coordinatorcluster:regex}', 'name=coordinator.del'))"
    }
   ]
  },
  {
   "title": "LOCK",
   "type": "stat",
   "description": "Кол-во серверов в пуле в статусе LOCK",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "movingMax(aliasByMetric(seriesByTag('contur=$contur', 'servertype=~${servertype:regex}', 'host=$host', 'coordinatorcluster=~${coordinatorcluster:regex}', 'name=coordinator.lock')), '1min')"
    }
   ]
  },
  {
   "title": "OFF",
   "type": "stat",
   "description": "Кол-во серверов в пуле в статусе OFF",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(seriesByTag('contur=$contur', 'servertype=~${servertype:regex}', 'host=$host', 'coordinatorcluster=~${coordinatorcluster:regex}', 'name=coordinator.off'))"
    }
   ]
  },
  {
   "title": "Coordinator Pool Mode",
   "type": "graph",
   "description": "Статус пула балансировщика, 1 - auto, 0 - manual\n> Все собирается со страницы координатора \"http://<host>/teletag\"\n",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(seriesByTag('contur=$contur', 'servertype=~${servertype:regex}', 'host=$host', 'coordinatorcluster=~${coordinatorcluster:regex}', 'name=coordinator.status'))"
    }
   ]
  }
 ]
}