{
 "title": "HL/HA — GRAYLOG CLUSTER",
 "description": "Основные метрики Graylog. Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "graylog",
  "telegraf",
  "service",
  "hlhs"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   { "name": "cluster", "query": "tag_values(graylog_name)" }
  ]
 },
 "panels": [
  {
   "title": "INPUT - Messages rate msg/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=org.graylog2.throughput.input.1-sec-rate', 'graylog_name=$cluster'), 'host', 'name'), 0)"
    }
   ]
  },
  {
   "title": "OUTPUT - Messages rate msg/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=org.graylog2.throughput.output.1-sec-rate', 'graylog_name=$cluster'), 'host', 'name'), 0)"
    }
   ]
  },
  {
   "title": "Journal - SIZE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=org.graylog2.journal.size', 'contur=~${contur:regex}', 'graylog_name=$cluster'), 'host', 'name'), 0)"
    }
   ]
  },
  {
   "title": "Journal - SIZE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=org.graylog2.journal.utilization-ratio', 'contur=~${contur:regex}', 'graylog_name=$cluster'), 'host', 'name'), 0)"
    }
   ]
  },
  {
   "title": "JVM memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=jvm.memory.total.init', 'graylog_name=$cluster'), 'host', 'name'), 0, 5, 6, 7)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=jvm.memory.total.used', 'graylog_name=$cluster'), 'host', 'name'), 0, 5, 6, 7)"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('graylog_name=$cluster', 'name=org.graylog2.buffers.input.size'), 'host', 'name'), 0, 7, 8)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('graylog_name=$cluster', 'name=org.graylog2.buffers.input.usage'), 'host', 'name'), 0, 7, 8)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('graylog_name=$cluster', 'name=org.graylog2.buffers.output.size'), 'host', 'name'), 0, 7, 8)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('graylog_name=$cluster', 'name=org.graylog2.buffers.output.usage'), 'host', 'name'), 0, 7, 8)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('graylog_name=$cluster', 'name=org.graylog2.buffers.process.size'), 'host', 'name'), 0, 7, 8)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('graylog_name=$cluster', 'name=org.graylog2.buffers.process.usage'), 'host', 'name'), 0, 7, 8)"
    }
   ]
  },
  {
   "title": "Journal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=org.graylog2.journal.append.1-sec-rate',  'contur=~${contur:regex}', 'graylog_name=$cluster'), 'host', 'name'), 0, 7, 8, 9)"
    }
   ]
  },
  {
   "title": "Journal utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(consolidateBy(seriesByTag('name=org.graylog2.journal.utilization-ratio', 'graylog_name=$cluster'), 'maximum'), 'host', 'name'), 0)"
    }
   ]
  }
 ]
}