{
 "title": "HL/HA — NGINX-CACHE",
 "description": "Ответственный:  Конюхов М.В. (Эксплуатация)",
 "tags": [
  "hlha",
  "nginx-cache",
  "mv.konuhov",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   { "name": "servertype", "label": "Тип", "query": "nginx-cache" },
   {
    "name": "host",
    "label": "Сервер",
    "query": "tag_values(host,contur=$contur,servertype=$servertype)"
   }
  ]
 },
 "panels": [
  {
   "title": "Эффективность кеша",
   "type": "gauge",
   "description": "Соотношение попадания в кеш и промахов.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(seriesByTag('name=~nginx-cache.RATIO', 'host=$host'), 'name'))"
    }
   ]
  },
  {
   "title": "Запросы",
   "type": "graph",
   "description": "Сколько запросов пришло от клиентов и ушло на бакенды",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=nginx.requests', 'host=$host')), 'name'))"
    }
   ]
  },
  {
   "title": "Запросы",
   "type": "graph",
   "description": "Соотношение попадания в кеш и промахов.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(seriesByTag('name=~nginx-cache.*', 'name!=nginx-cache.RATIO', 'name!=nginx-cache.TOTAL', 'host=$host'), 'name'))"
    }
   ]
  },
  {
   "title": "Трафик",
   "type": "graph",
   "description": "RX и TX трафик в байтах.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(scale(aliasByTags(perSecond(seriesByTag('host=$host', 'name=~system.net.bytes*')), 'name'), 8))"
    }
   ]
  },
  {
   "title": "Диски Чтение\\Запись",
   "type": "graph",
   "description": "Размер прочитанных и записанных данных на диски, исключая системные разделы",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "perSecond(aliasByTags(exclude(seriesByTag('host=$host', 'name=~system.diskio.*_bytes'), 'sda'), '_name', 'name'))"
    }
   ]
  },
  {
   "title": "LA",
   "type": "graph",
   "description": "LA 1 5 15",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=system.system.n_cpus', 'host=$host'), 'CPU')"
    },
    {
     "target": "alias(seriesByTag('name=system.system.load1', 'host=$host'), 'la1')"
    },
    {
     "target": "alias(seriesByTag('name=system.system.load5', 'host=$host'), 'la5')"
    },
    {
     "target": "alias(seriesByTag('name=system.system.load15', 'host=$host'), 'la15')"
    }
   ]
  },
  {
   "title": "Пакеты",
   "type": "graph",
   "description": "Входящие и исходящие пакеты",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('host=$host', 'name=~system.net.packets_recv')), 'name'))"
    },
    {
     "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('host=$host', 'name=~system.net.packets_sent')), 'name'))"
    }
   ]
  },
  {
   "title": "Диски Время Чтения/Записи",
   "type": "graph",
   "description": "Время прочитанных и записанных данных на диски, исключая системные разделы",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(exclude(seriesByTag('host=$host', 'name=~system.diskio.read_time'), 'sda')), '_name', 'name')"
    },
    {
     "target": "aliasByTags(perSecond(exclude(seriesByTag('host=$host', 'name=~system.diskio.write_time'), 'sda')), '_name', 'name')"
    }
   ]
  },
  {
   "title": "Сетевой стек",
   "type": "graph",
   "description": "Состояния сетевых сокетов",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=~system.netstat.tcp_*'), 'name'))"
    }
   ]
  },
  {
   "title": "Память - использование",
   "type": "graph",
   "description": "Статистика по использованию памяти. \n- used - использовано\n- free - свободно \n- shared - общая использованная память\n- buffered - память, использованная под буферы\n- cached - по сути занятая системой, но временно не используемая память, готовая к высвобождению в любой момент",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.used'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.free'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.shared'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.buffered'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.cached'), 'name')), 'max')"
    }
   ]
  },
  {
   "title": "Память",
   "type": "graph",
   "description": "Доступно и использовано памяти.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.available'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.total'), 'name')), 'max')"
    }
   ]
  }
 ]
}