{
 "title": "HL/HA — FEATURE RATIO/DISK",
 "description": "Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "feature",
  "hlha"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "nginxcache", "label": "Тип", "query": "feature" },
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "host",
    "label": "Сервер",
    "query": "tag_values(host,contur=prod,nginxcache=$nginxcache)"
   },
   {
    "name": "service",
    "label": "ИД Функционала",
    "query": "tag_values(service,host=~${host:regex},status!=NOCACHE,domain=feature)"
   }
  ]
 },
 "panels": [
  {
   "title": "Запросы в фичу",
   "type": "graph",
   "description": "Соотношение попадания в кеш и промахов.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(perSecond(seriesByTag('name=~prometheus.nginx_cache', 'service=~${service:regex}', 'host=~${host:regex}', 'status=HIT')), 'sum', 'host'), 'status')"
    },
    {
     "target": "aliasByTags(groupByTags(perSecond(seriesByTag('name=~prometheus.nginx_cache', 'service=~${service:regex}', 'host=~${host:regex}', 'status=MISS')), 'sum', 'host'), 'status')"
    }
   ]
  },
  {
   "title": "RATIO",
   "type": "graph",
   "description": "Соотношение попадания в кеш и промахов.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByTags(divideSeriesLists(aliasByTags(perSecond(seriesByTag('name=prometheus.nginx_cache', 'host=~${host:regex}', 'service=${service:regex}', 'status=HIT')), 'service'), #B), 'service')",
     "targetFull": "aliasByTags(divideSeriesLists(aliasByTags(perSecond(seriesByTag('name=prometheus.nginx_cache', 'host=~${host:regex}', 'service=${service:regex}', 'status=HIT')), 'service'), aliasByTags(groupByTags(perSecond(seriesByTag('name=~prometheus.nginx_cache', 'host=~${host:regex}', 'service=${service:regex}', 'status=~(HIT|MISS)')), 'sum', 'service'), 'service')), 'service')"
    }
   ]
  },
  {
   "title": "% DISK",
   "type": "gauge",
   "description": "Процент заполнения дискового кеша",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('name=feature_dirstat.feature_proc', 'host=~${host:regex}', 'service=~${service:regex}'), 'proc')"
    }
   ]
  },
  {
   "title": "MIN RATIO",
   "type": "gauge",
   "description": "Соотношение попадания в кеш и промахов",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "target": "aliasByTags(divideSeriesLists(aliasByTags(perSecond(seriesByTag('name=prometheus.nginx_cache', 'host=~${host:regex}', 'service=${service:regex}', 'status=HIT', 'domain=feature')), 'service'), #B), 'service')",
     "targetFull": "aliasByTags(divideSeriesLists(aliasByTags(perSecond(seriesByTag('name=prometheus.nginx_cache', 'host=~${host:regex}', 'service=${service:regex}', 'status=HIT', 'domain=feature')), 'service'), aliasByTags(groupByTags(perSecond(seriesByTag('name=~prometheus.nginx_cache', 'host=~${host:regex}', 'service=${service:regex}', 'status=~(HIT|MISS)', 'domain=feature')), 'sum', 'service'), 'service')), 'service')"
    }
   ]
  },
  {
   "title": "MEAN RATIO",
   "type": "gauge",
   "description": "Соотношение попадания в кеш и промахов.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByTags(divideSeriesLists(aliasByTags(perSecond(seriesByTag('name=prometheus.nginx_cache', 'host=~${host:regex}', 'service=${service:regex}', 'status=HIT', 'domain=feature')), 'service'), #B), 'service')",
     "targetFull": "aliasByTags(divideSeriesLists(aliasByTags(perSecond(seriesByTag('name=prometheus.nginx_cache', 'host=~${host:regex}', 'service=${service:regex}', 'status=HIT', 'domain=feature')), 'service'), aliasByTags(groupByTags(perSecond(seriesByTag('name=~prometheus.nginx_cache', 'host=~${host:regex}', 'service=${service:regex}', 'status=~(HIT|MISS)', 'domain=feature')), 'sum', 'service'), 'service')), 'service')"
    }
   ]
  },
  {
   "title": "Количество файлов в кеше",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(seriesByTag('name=feature_dirstat.feature_filecount', 'host=~${host:regex}', 'service=${service:regex}'), 'service'), 'max')"
    }
   ]
  },
  {
   "title": "Размер кеша в блоках по 4k",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(seriesByTag('name=feature_dirstat.feature_dirlimit', 'host=~${host:regex}', 'service=${service:regex}'), 'max'), 'limit')"
    },
    {
     "target": "consolidateBy(aliasByTags(seriesByTag('name=feature_dirstat.feature_dirblocks', 'host=~${host:regex}', 'service=${service:regex}'), 'service'), 'max')"
    }
   ]
  }
 ]
}