{
 "title": "HL/HA — FEATURE LANENCY",
 "description": "Ответственный: Голубев А.Ф. (Разработка)",
 "tags": [
  "feature",
  "hlha"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "nginxcache", "label": "Тип", "query": "feature" },
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "host",
    "label": "Сервер",
    "query": "tag_values(host,contur=prod,nginxcache=$nginxcache)"
   }
  ]
 },
 "panels": [
  {
   "title": "Запросы по диспетчерам и 95 персентили задержки",
   "type": "graph",
   "description": "Сколько запросов пришло от клиентов и ушло на бакенды",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps", "label": "Request(s)" }
   ],
   "targets": [
    {
     "target": "alias(nPercentile(groupByTags(perSecond(seriesByTag('name=prometheus.nginx_front_latency_bucket', 'host=~${host:regex}')), 'average', 'name'), 95), '95% front')"
    },
    {
     "target": "alias(nPercentile(groupByTags(perSecond(seriesByTag('name=prometheus.nginx_back_latency_bucket', 'host=~${host:regex}')), 'average', 'name'), 95), '95% backend')"
    },
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('name=nginx.requests', 'host=~${host:regex}')), 'host'), 0)"
    }
   ]
  },
  {
   "title": "LATENCY FRONT",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "target": "groupByTags(perSecond(seriesByTag('name=prometheus.nginx_front_latency_bucket', 'host=~${host:regex}')), 'average', 'name')"
    }
   ]
  },
  {
   "title": "LATENCY BACK",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "target": "groupByTags(perSecond(seriesByTag('name=prometheus.nginx_back_latency_bucket', 'host=~${host:regex}')), 'average', 'name')"
    }
   ]
  }
 ]
}