{
 "title": "Asterisk",
 "description": "Комплексный экран по АТС asterisk. Ответственный: Конюхов М.В. (Эксплуатация)",
 "tags": [
  "telegraf",
  "service",
  "mv.konuhov",
  "asterisk",
  "telephony",
  "телефония"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod,corp" },
   { "name": "servertype", "label": "Тип", "query": "telephony" },
   {
    "name": "host",
    "label": "Сервер",
    "query": "tag_values(host,contur=$contur,servertype=$servertype,name=asterisk_metrics.uptime)"
   },
   {
    "name": "container",
    "label": "Имя контейнера",
    "query": "tag_values(container,contur=$contur,servertype=$servertype,host=~${host:regex},name=asterisk_metrics.uptime)"
   }
  ]
 },
 "panels": [
  {
   "title": "Статус pbx_monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "tensor_pbx_monitor response time on $host",
     "type": "graph",
     "description": "Проверяем доступность дохлика путем опроса страницы http://service:9991/service/?load  Если она недоступна - все данные по хосту от asterisk будут отсутствовать",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=http_response.response_time', 'contur=${contur}', 'host=~${host:regex}', 'service=asterisk'), 'host')"
      }
     ]
    },
    {
     "title": "tensor_pbx_monitor result code on $host",
     "type": "graph",
     "description": "Проверяем доступность дохлика путем опроса страницы http://service:9991/service/?load  Если она недоступна - все данные по хосту от asterisk будут отсутствовать\nresponse_time (float, seconds)\nresult_code (int, success = 0, timeout = 1, connection_failed = 2, read_failed = 3, string_mismatch = 4)",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=http_response.result_code', 'contur=${contur}', 'host=~${host:regex}', 'service=asterisk'), 'host')"
      }
     ]
    }
   ]
  },
  {
   "title": "Статистика по выбранным серверам",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "ODBC errors TOP 50 by selected servers",
   "type": "graph",
   "description": "Количество неудавшихся запросов к БД (count_odbc_errors) по всем контейнерам выбранных серверов\n> No data = не найдено ошибок",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maximumAbove(highestMax(aliasByTags(seriesByTag('name=~asterisk_metrics.count_odbc_errors.*', 'contur=${contur}', 'host=~${host:regex}'), 'host', 'container'), 50), 0)"
    }
   ]
  },
  {
   "title": "ODBC errors TOP 50 by selected servers",
   "type": "graph",
   "description": "Количество неудавшихся запросов к БД (count_odbc_errors) по всем контейнерам выбранных серверов\n> No data = не найдено ошибок",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maximumAbove(highestMax(aliasByTags(seriesByTag('name=~asterisk_metrics.count_odbc_errors.*', 'contur=${contur}', 'host=~${host:regex}'), 'host', 'container'), 50), 0)"
    }
   ]
  },
  {
   "title": "Containers active / max allowed",
   "type": "graph",
   "description": "tel.get.host.load.stats.containers.active\ntel.get.host.load.stats.containers.max\n> динамически считаем текущее и максимальное кол-во АТС:\nhttps://adm-git.tensor.ru/exp/telephony/tree/dev_mv.konuhov/tel_get_hosts_load_stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=tel.get.host.load.stats.containers.active', 'contur=${contur}', 'cloud_host=~${host:regex}', 'cloud_type=platforma'), 'cloud_host', 'name')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=tel.get.host.load.stats.containers.max', 'contur=${contur}', 'cloud_host=~${host:regex}', 'cloud_type=platforma'), 'cloud_host', 'name')"
    }
   ]
  },
  {
   "title": "Load tensor_platforma $host",
   "type": "graph",
   "description": "Загрузка БЛ на сервере. Замеряется скриптом https://adm-git.tensor.ru/exp/monitoring-scripts/telephony/-/blob/master/scripts/tel_service_check.py\n\n(NumberOfProcessedRequests|NumberOfErrors) - rps. Остальное текущие значения",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=tel_service_check', 'contur=${contur}', 'host=~${host:regex}', 'service_name=tensor_platforma', 'metric_name!=~(NumberOfProcessedRequests|NumberOfErrors)'), 'metric_name')"
    },
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=tel_service_check', 'contur=${contur}', 'host=~${host:regex}', 'service_name=tensor_platforma', 'metric_name=~(NumberOfProcessedRequests|NumberOfErrors)')), 'metric_name')"
    }
   ]
  },
  {
   "title": "TOP Calls spectrogram errors by servers",
   "type": "graph",
   "description": "Выводит топ ненулевых ошибок по спектрограмам по всем контейнерам выбранных серверов\n\n0 = все ок. >0 - присутствуют проблемы. Счетчик сбрасывается раз в сутки.\n\naudiofile_spectrogram_getter_parse_error - ошибка парсинга входных данных\n\naudiofile_spectrogram_getter_empty_file - пустой аудиофайл\n\naudiofile_spectrogram_getter_insert_error - ошибка сохранения данных в БД\n\naudiofile_spectrogram_getter_exception - исключение в работе скрипта",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maximumAbove(aliasSub(aliasByTags(groupByTags(seriesByTag('name=~asterisk_metrics.audiofile_spectrogram.*', 'contur=${contur}', 'host=~${host:regex}'), 'max', 'host', 'name', 'container'), 'host', 'name', 'container'), 'asterisk_metrics.audiofile_spectrogram_', ''), 0)"
    }
   ]
  },
  {
   "title": "Load tel_hub $host",
   "type": "graph",
   "description": "Загрузка БЛ на сервере. Замеряется скриптом https://adm-git.tensor.ru/exp/monitoring-scripts/telephony/-/blob/master/scripts/tel_service_check.py\n\n(NumberOfProcessedRequests|NumberOfErrors) - rps. Остальное текущие значения",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=tel_service_check', 'contur=${contur}', 'host=~${host:regex}', 'service_name=tel_hub', 'metric_name!=~(NumberOfProcessedRequests|NumberOfErrors)'), 'metric_name')"
    },
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=tel_service_check', 'contur=${contur}', 'host=~${host:regex}', 'service_name=tel_hub', 'metric_name=~(NumberOfProcessedRequests|NumberOfErrors)')), 'metric_name')"
    }
   ]
  },
  {
   "title": "tel-hub top 20 ats with not uploaded files $host",
   "type": "graph",
   "description": "metric_name=tel_hub_media_files_err_count\nколичество проблемных медиафайлов у АТС из тега ats = XYZ\n\nСкрипт https://adm-git.tensor.ru/exp/monitoring-scripts/telephony/-/blob/master/scripts/tel_hub_redis_stats.py\n\n>> No data - нет проблемных",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(highestMin(seriesByTag('name=tel_hub_redis_stats', 'contur=${contur}', 'host=~${host:regex}', 'metric_name=tel_hub_media_files_err_count'), 20), 'metric_name')"
    }
   ]
  },
  {
   "title": "Load tel-hub pbxapi $host",
   "type": "graph",
   "description": "Загрузка БЛ на сервере. Замеряется скриптом https://adm-git.tensor.ru/exp/monitoring-scripts/telephony/-/blob/master/scripts/tel_service_check.py\n\n(NumberOfProcessedRequests|NumberOfErrors) - rps. Остальное текущие значения",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=tel_service_check', 'contur=${contur}', 'host=~${host:regex}', 'service_name=pbxapi', 'metric_name!=~(NumberOfProcessedRequests|NumberOfErrors)'), 'metric_name')"
    },
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=tel_service_check', 'contur=${contur}', 'host=~${host:regex}', 'service_name=pbxapi', 'metric_name=~(NumberOfProcessedRequests|NumberOfErrors)')), 'metric_name')"
    }
   ]
  },
  {
   "title": "Load tel-hub serviceproxy $host",
   "type": "graph",
   "description": "Загрузка БЛ на сервере. Замеряется скриптом https://adm-git.tensor.ru/exp/monitoring-scripts/telephony/-/blob/master/scripts/tel_service_check.py\n\n(NumberOfProcessedRequests|NumberOfErrors) - rps. Остальное текущие значения",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=tel_service_check', 'contur=${contur}', 'host=~${host:regex}', 'service_name=serviceproxy', 'metric_name!=~(NumberOfProcessedRequests|NumberOfErrors)'), 'metric_name')"
    },
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=tel_service_check', 'contur=${contur}', 'host=~${host:regex}', 'service_name=serviceproxy', 'metric_name=~(NumberOfProcessedRequests|NumberOfErrors)')), 'metric_name')"
    }
   ]
  },
  {
   "title": "Load tel-hub dbmanager $host",
   "type": "graph",
   "description": "Загрузка БЛ на сервере. Замеряется скриптом https://adm-git.tensor.ru/exp/monitoring-scripts/telephony/-/blob/master/scripts/tel_service_check.py\n\n(NumberOfProcessedRequests|NumberOfErrors) - rps. Остальное текущие значения",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=tel_service_check', 'contur=${contur}', 'host=~${host:regex}', 'service_name=dbmanager', 'metric_name!=~(NumberOfProcessedRequests|NumberOfErrors)'), 'metric_name')"
    },
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=tel_service_check', 'contur=${contur}', 'host=~${host:regex}', 'service_name=dbmanager', 'metric_name=~(NumberOfProcessedRequests|NumberOfErrors)')), 'metric_name')"
    }
   ]
  },
  {
   "title": "tel-hub not uploaded files last 24h $host",
   "type": "graph",
   "description": "metric_name=tel_hub_files_not_uploaded_24h\nкол-во невыгруженных за 24 файлов сервисов tel-hub\n\nСкрипт https://adm-git.tensor.ru/exp/monitoring-scripts/telephony/-/blob/master/scripts/tel_hub_redis_stats.py",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=tel_hub_redis_stats', 'contur=${contur}', 'host=~${host:regex}', 'metric_name=tel_hub_files_not_uploaded_24h'), 'metric_name')"
    }
   ]
  },
  { "title": "Контейнер ${container}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 }, "repeat": "container" },
  {
   "title": "UPTIME ${container:regex}",
   "type": "graph",
   "description": "Время со старта asterisk (uptime)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.uptime', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "ASTDB rows ${container:regex}",
   "type": "graph",
   "description": "Количество записей в astdb (count_record_astdb)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.count_record_astdb.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "RTP errors $container",
   "type": "graph",
   "description": "Количество ошибок выделения RTP порта (count_rtp_errors)",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.count_rtp_errors.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "Statis in queue $container",
   "type": "graph",
   "description": "Количество stasis событый в очереди (count_stasis_in_queue)",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.count_stasis_in_queue.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "Active calls ${container:regex}",
   "type": "graph",
   "description": "Текущее количество звонков (count_calls)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.count_calls.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "ODBC generate errors ${container:regex}",
   "type": "graph",
   "description": "Всего количество ошибок генерации конфигурации АТС за день (count_generate_errors)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.count_generate_errors.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "ODBC errors ${container:regex}",
   "type": "graph",
   "description": "Всего количество неудавшихся запросов к БД (count_odbc_errors)",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.count_odbc_errors.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "Call duration flag ${container:regex}",
   "type": "graph",
   "description": "Проверка длительной продолжительности звонка. Есть такие или нет.  call_duration:Flag",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.call_duration.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "Manager processes ${container:regex}",
   "type": "graph",
   "description": "Количество процессов manager в очереди count_manager_in_queue",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.count_manager_in_queue.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "Dropped calls ${container:regex}",
   "type": "graph",
   "description": "Количество обрывов звонков из-за проблем на транспорте за день count_dropped_calls",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.count_dropped_calls.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "SIP endpoint and reg statuses ${container:regex}",
   "type": "graph",
   "description": "endpoint_status_{sip_name}:Flag\nendpoint_reg_status_*{pstn_name}:Flag\nстатусы sip транков (физическая доступность и доступность регистрации)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.endpoint_status.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.endpoint_reg_status.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "Status AMI / ARI / SIP registration $container",
   "type": "graph",
   "description": "Статусы AMI (порт 5038)  (ami_status:Flag)\nARI (Asterisk HTTP 8088) (ari_status:Flag)\nSip регистрация (status_sip_registry)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.ami_status', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.ari-status', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.status_sip_registry', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "Contacts count $container",
   "type": "graph",
   "description": "Количества контактов по номерам (sip_name) в мониторинге АТС\n(count_contact_{sip_name})",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.count_contact.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "Connections PSTN / LOCAL / CORE $container",
   "type": "graph",
   "description": "Текущее количество соединений между:\n1) pstn и core  (count_pstn_core)\n2) pstn и local (count_pstn_local)\n3) core и local (count_core_local)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.count_pstn_core.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.count_pstn_local.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.count_core_local.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "Empty queues $container",
   "type": "graph",
   "description": "Показывает звонковые очереди, в которых отсутствуют операторы (empty_queue_{queue}:Flag)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.empty_queue.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "Queue invalid operators $container",
   "type": "graph",
   "description": "Статус проверки Invalid операторов в очереди (queue) (count_invalid_{queue})",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.count_invalid.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "Operators in queues $container",
   "type": "graph",
   "description": "Показывает количество операторов в звонковой очереди (count_members_{queue})",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~asterisk_metrics.count_members.*', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "Unconverted call records  $container",
   "type": "graph",
   "description": "Показывает количество несконвертированныхз записей разговоров в штуках (count_call_records, int)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=asterisk_metrics.count_call_records', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "Oldest unconverted call record  $container",
   "type": "graph",
   "description": "Показывает самую старую несконвертированную завись разговора в днях (oldest_call_record, int)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 93 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=asterisk_metrics.oldest_call_record', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.', '')"
    }
   ]
  },
  {
   "title": "Calls spectrogram errors $container",
   "type": "graph",
   "description": "0 = все ок. >0 - присутствуют проблемы. Счетчик сбрасывается раз в сутки.\n\naudiofile_spectrogram_getter_parse_error - ошибка парсинга входных данных\n\naudiofile_spectrogram_getter_empty_file - пустой аудиофайл\n\naudiofile_spectrogram_getter_insert_error - ошибка сохранения данных в БД\n\naudiofile_spectrogram_getter_exception - исключение в работе скрипта",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=asterisk_metrics.audiofile_spectrogram_getter_empty_file', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.audiofile_spectrogram_', '')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=asterisk_metrics.audiofile_spectrogram_getter_parse_error', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.audiofile_spectrogram_', '')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=asterisk_metrics.audiofile_spectrogram_getter_insert_error', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.audiofile_spectrogram_', '')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=asterisk_metrics.audiofile_spectrogram_getter_exception', 'contur=${contur}', 'host=~${host:regex}', 'container=${container}'), 'name'), 'asterisk_metrics.audiofile_spectrogram_', '')"
    }
   ]
  }
 ]
}