{
 "title": "Clickhouse by telegraf",
 "description": "ClickHouse internal exporter metrics. Ответственный: Воробьев П.А. (Эксплуатация)",
 "tags": [
  "ClickHouse",
  "telegraf",
  "service",
  "db"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Node",
    "query": "tag_values(host,name=clickhouse_asynchronous_metrics.number_of_databases)"
   }
  ]
 },
 "panels": [
  {
   "title": "Databases",
   "type": "stat",
   "description": "Number of currently active databases",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$instance', 'name=clickhouse_asynchronous_metrics.number_of_databases'), 'host')"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "stat",
   "description": "Number of used tables, including replicas on another servers",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$instance', 'name=clickhouse_asynchronous_metrics.number_of_tables'), 'host')"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time, spending since last restart",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$instance', 'name=clickhouse_asynchronous_metrics.uptime'), 'host')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Total amount of memory (bytes) allocated by the server.",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking",
     "legendFormat": "{{instance}}",
     "target": "aliasByTags(seriesByTag('host=$instance', 'name=clickhouse_metrics.memory_tracking'), 'host')"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Number of connections to TCP server (clients with native interface), also included server-server distributed query connections. \nNumber of connections to HTTP server",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection",
     "legendFormat": "tcp - {{instance}}",
     "target": "aliasByTags(seriesByTag('host=$instance', 'name=clickhouse_metrics.tcp_connection'), 'host', 'name')"
    },
    {
     "expr": "ClickHouseMetrics_HTTPConnection",
     "legendFormat": "http - {{instance}}",
     "target": "aliasByTags(seriesByTag('host=$instance', 'name=clickhouse_metrics.http_connection'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Read backoff",
   "type": "graph",
   "description": "Number of times the number of query processing threads was lowered due to slow reads.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBackoff{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.read_buffer_aio_read')), 'host')"
    }
   ]
  },
  {
   "title": "Slow reads",
   "type": "graph",
   "description": "Number of reads from a file that were slow. This indicate system overload. Thresholds are controlled by read_backoff_* settings.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SlowRead{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.slow_read')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries",
     "type": "graph",
     "description": "Number of queries to be interpreted and potentially executed. Does not include queries that failed to parse or were rejected due to AST size limits, quota limits or limits on the number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_Query{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.query')), 'host')"
      }
     ]
    },
    {
     "title": "SELECT queries",
     "type": "graph",
     "description": "Same as Queries, but only for SELECT queries.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.select_query')), 'host')"
      }
     ]
    },
    {
     "title": "INSERT queries",
     "type": "graph",
     "description": "Same as Queries, but only for INSERT queries.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_InsertQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.insert_query')), 'host')"
      }
     ]
    },
    {
     "title": "Failed queries",
     "type": "graph",
     "description": "Number of failed queries.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_FailedQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.failed_query')), 'host')"
      }
     ]
    },
    {
     "title": "Failed SELECT queries",
     "type": "graph",
     "description": "Same as Failed queries, but only for SELECT queries.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_FailedSelectQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.failed_select_query')), 'host')"
      }
     ]
    },
    {
     "title": "Failed INSERT queries",
     "type": "graph",
     "description": "Same as Failed queries, but only for INSERT queries.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_FailedInsertQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.failed_insert_query')), 'host')"
      }
     ]
    },
    {
     "title": "Query latencies (avg)",
     "type": "graph",
     "description": "Avg queries latencies",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_QueryTimeMicroseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_Query{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.query_time_microseconds')), 'host')"
      }
     ]
    },
    {
     "title": "SELECT query latencies (avg)",
     "type": "graph",
     "description": "Avg SELECT queries latencies",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_SelectQueryTimeMicroseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_SelectQuery{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.select_query_time_microseconds')), 'host')"
      }
     ]
    },
    {
     "title": "INSERT query latencies (avg)",
     "type": "graph",
     "description": "Avg INSERT queries latencies",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_InsertQueryTimeMicroseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_InsertQuery{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.insert_query_time_microseconds')), 'host')"
      }
     ]
    },
    {
     "title": "Query preemted",
     "type": "graph",
     "description": "Number of queries that are stopped and waiting due to 'priority' setting.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseMetrics_QueryPreempted{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_metrics.query_preempted')), 'host')"
      }
     ]
    }
   ]
  },
  {
   "title": "Insert",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inserted rows",
     "type": "graph",
     "description": "Number of rows INSERTed to all tables.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_InsertedRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.inserted_rows')), 'host')"
      }
     ]
    },
    {
     "title": "Inserted bytes",
     "type": "graph",
     "description": "Number of bytes (uncompressed; for columns as they stored in memory) INSERTed to all tables.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_InsertedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.inserted_bytes')), 'host')"
      }
     ]
    },
    {
     "title": "Delayed inserts",
     "type": "graph",
     "description": "Number of times the INSERT of a block to a MergeTree table was throttled due to high number of active data parts for partition.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DelayedInserts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_metrics.delayed_inserts')), 'host')"
      }
     ]
    }
   ]
  },
  {
   "title": "Select",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Parts",
     "type": "graph",
     "description": "Number of data parts selected to read from a MergeTree table.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedParts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.selected_parts')), 'host')"
      }
     ]
    },
    {
     "title": "Ranges",
     "type": "graph",
     "description": "Number of (non-adjacent) ranges in all data parts selected to read from a MergeTree table.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedRanges{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.selected_ranges')), 'host')"
      }
     ]
    },
    {
     "title": "Marks",
     "type": "graph",
     "description": "Number of marks (index granules) selected to read from a MergeTree table.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedMarks{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.selected_marks')), 'host')"
      }
     ]
    },
    {
     "title": "Rows",
     "type": "graph",
     "description": "Number of rows SELECTed from all tables.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.selected_rows')), 'host')"
      }
     ]
    },
    {
     "title": "Bytes",
     "type": "graph",
     "description": "Number of bytes (uncompressed; for columns as they stored in memory) SELECTed from all tables.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.selected_bytes')), 'host')"
      }
     ]
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "lseek",
     "type": "graph",
     "description": "Number of times the 'lseek' function was called.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_Seek{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.seek')), 'host')"
      }
     ]
    },
    {
     "title": "Open Files",
     "type": "graph",
     "description": "Number of files opened",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_FileOpen{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.file_open')), 'host')"
      }
     ]
    },
    {
     "title": "Compressed blocks",
     "type": "graph",
     "description": "Number of compressed blocks (the blocks of data that are compressed independent of each other) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_CompressedReadBufferBlocks{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.compressed_read_buffer_blocks')), 'host')"
      }
     ]
    },
    {
     "title": "Read from FD",
     "type": "graph",
     "description": "Number of reads (read/pread) from a file descriptor. Does not include sockets.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorRead{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.read_buffer_from_file_descriptor_read')), 'host')"
      }
     ]
    },
    {
     "title": "Write to FD",
     "type": "graph",
     "description": "Number of writes (write/pwrite) to a file descriptor. Does not include sockets.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWrite{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.write_buffer_from_file_descriptor_write')), 'host')"
      }
     ]
    },
    {
     "title": "Read compressed bytes",
     "type": "graph",
     "description": "Number of bytes (the number of bytes before decompression) read from compressed sources (files, network).",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadCompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.read_compressed_bytes')), 'host')"
      }
     ]
    },
    {
     "title": "Read bytes from FD",
     "type": "graph",
     "description": "Number of bytes read from file descriptors. If the file is compressed, this will show the compressed data size.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.read_buffer_from_file_descriptor_read_bytes')), 'host')"
      }
     ]
    },
    {
     "title": "Write bytes to FD",
     "type": "graph",
     "description": "Number of bytes written to file descriptors. If the file is compressed, this will show compressed data size.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.write_buffer_from_file_descriptor_write_bytes')), 'host')"
      }
     ]
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Readonly replica",
     "type": "graph",
     "description": "Number of Replicated tables that are currently in readonly state due to re-initialization after ZooKeeper session loss or due to startup without ZooKeeper configured.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_ReadonlyReplica",
       "legendFormat": "{{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_metrics.readonly_replica')), 'host')"
      }
     ]
    },
    {
     "title": "Replicated part failed fetches",
     "type": "graph",
     "description": "Number of times a data part was failed to download from replica of a ReplicatedMergeTree table.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFailedFetches{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.replicated_part_failed_fetches')), 'host')"
      }
     ]
    },
    {
     "title": "Replicated part fetches",
     "type": "graph",
     "description": "Number of times a data part was downloaded from replica of a ReplicatedMergeTree table.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFetches{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.replicated_part_fetches')), 'host')"
      }
     ]
    },
    {
     "title": "Replicated part merges",
     "type": "graph",
     "description": "Number of times data parts of ReplicatedMergeTree tables were successfully merged.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartMerges{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.replicated_part_merges')), 'host')"
      }
     ]
    },
    {
     "title": "Replicated part fetches of merged",
     "type": "graph",
     "description": "Number of times we prefer to download already merged part from replica of ReplicatedMergeTree table instead of performing a merge ourself (usually we prefer doing a merge ourself to save network traffic). This happens when we have not all source parts to perform a merge or when the data part is old enough.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFetchesOfMerged{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.replicated_part_fetches_of_merged')), 'host')"
      }
     ]
    },
    {
     "title": "Replicated part data loss",
     "type": "graph",
     "description": "Number of times a data part that we wanted doesn't exist on any replica (even on replicas that are offline right now). That data parts are definitely lost. This is normal due to asynchronous replication (if quorum inserts were not enabled), when the replica on which the data part was written was failed and when it became online after fail it doesn't contain that data part.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedDataLoss{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.replicated_data_loss')), 'host')"
      }
     ]
    }
   ]
  },
  {
   "title": "Merge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Merge",
     "type": "graph",
     "description": "Number of launched background merges.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_Merge{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.merge')), 'host')"
      }
     ]
    },
    {
     "title": "Merged rows",
     "type": "graph",
     "description": "Rows read for background merges. This is the number of rows before merge.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergedRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.merged_rows')), 'host')"
      }
     ]
    },
    {
     "title": "Merge uncompressed bytes",
     "type": "graph",
     "description": "Uncompressed bytes (for columns as they stored in memory) that was read for background merges. This is the number before merge.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergedUncompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.merged_uncompressed_bytes')), 'host')"
      }
     ]
    },
    {
     "title": "MergeTree rows",
     "type": "graph",
     "description": "Number of rows INSERTed to MergeTree tables.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.merge_tree_data_writer_rows')), 'host')"
      }
     ]
    },
    {
     "title": "Merge duration (avg)",
     "type": "graph",
     "description": "Avg merge duration",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_MergesTimeMilliseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_Merge{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.merges_time_milliseconds')), 'host')"
      }
     ]
    },
    {
     "title": "Reserved space",
     "type": "graph",
     "description": "Disk space reserved for currently running background merges. It is slightly more than the total size of currently merging parts.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_DiskSpaceReservedForMerge",
       "legendFormat": "{{instance}}",
       "target": "aliasByTags(seriesByTag('host=$instance', 'name=clickhouse_metrics.disk_space_reserved_for_merge'), 'host')"
      }
     ]
    },
    {
     "title": "MergeTree uncompressed bytes",
     "type": "graph",
     "description": "Uncompressed bytes (for columns as they stored in memory) INSERTed to MergeTree tables.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterUncompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.merge_tree_data_writer_uncompressed_bytes')), 'host')"
      }
     ]
    },
    {
     "title": "MergeTree compressed bytes",
     "type": "graph",
     "description": "Bytes written to filesystem for data INSERTed to MergeTree tables.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterCompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.merge_tree_data_writer_compressed_bytes')), 'host')"
      }
     ]
    },
    {
     "title": "MergeTree blocks",
     "type": "graph",
     "description": "Number of blocks INSERTed to MergeTree tables. Each block forms a data part of level zero.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterBlocks{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.merge_tree_data_writer_blocks')), 'host')"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mark Cache Hits",
     "type": "graph",
     "description": "Number of hits to granularity (markup) tables",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MarkCacheHits{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.mark_cache_hits')), 'host')"
      }
     ]
    },
    {
     "title": "Mark Cache Misses",
     "type": "graph",
     "description": "Number of misses to granularity (markup) tables",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MarkCacheMisses{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}",
       "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.mark_cache_misses')), 'host')"
      }
     ]
    }
   ]
  },
  {
   "title": "Parts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temporary",
     "type": "graph",
     "description": "The part is generating now, it is not in data_parts list.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ]
    },
    {
     "title": "Pre commited",
     "type": "graph",
     "description": "The part is in data_parts, but not used for SELECTs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsPreCommitted",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Commited",
     "type": "graph",
     "description": "The part is in data_parts, but not used for SELECTs.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsCommitted",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outdated",
     "type": "graph",
     "description": "Not active data part, but could be used by only current SELECTs, could be deleted after SELECTs finishes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsOutdated",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Deleting",
     "type": "graph",
     "description": "Not active data part with identity refcounter, it is deleting right now by a cleaner.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsDeleting",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Delete on destroy",
     "type": "graph",
     "description": "Part was moved to another disk and should be deleted in own destructor.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsDeleteOnDestroy",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Wide",
     "type": "graph",
     "description": "Wide parts.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "ClickHouseMetrics_PartsWide", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Compact",
     "type": "graph",
     "description": "Compact parts.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "ClickHouseMetrics_PartsCompact", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "In-memory",
     "type": "graph",
     "description": "In-memory parts.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsInMemory",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distributed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Send",
     "type": "graph",
     "description": "Number of connections to remote servers sending data that was INSERTed into Distributed tables. Both synchronous and asynchronous mode.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_DistributedSend",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Files to insert",
     "type": "graph",
     "description": "Number of pending files to process for asynchronous insertion into Distributed tables. Number of files for every shard is summed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_DistributedFilesToInsert",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Distributed delayed inserts",
     "type": "graph",
     "description": "Number of times the INSERT of a block to a Distributed table was throttled due to high number of pending bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedDelayedInserts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedDelayedInserts{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Distributed rejected inserts",
     "type": "graph",
     "description": "Number of times the INSERT of a block to a Distributed table was rejected with 'Too many bytes' exception due to high number of pending bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedRejectedInserts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedRejectedInserts{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Distributed delayed inserts blocks (avg)",
     "type": "graph",
     "description": "Total number of milliseconds spent while the INSERT of a block to a Distributed table was throttled due to high number of pending bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_DistributedDelayedInsertsMilliseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_DistributedDelayedInserts{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Distributed connection fail try",
     "type": "graph",
     "description": "Total count when distributed connection fails with retry",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedConnectionFailTry{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedConnectionFailTry{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Distributed connection fail at all",
     "type": "graph",
     "description": "Total count when distributed connection fails after all retries finished",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedConnectionFailAtAll{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedConnectionFailAtAll{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Distributed sync insertation timeout",
     "type": "graph",
     "description": "Total number of milliseconds spent while the INSERT of a block to a Distributed table was synced to other servers in shard.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedSyncInsertionTimeoutExceeded{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedSyncInsertionTimeoutExceeded{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Background pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "BackgroundPool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundProcessingPool (merges, mutations, or replication queue bookkeeping)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundPoolTask",
       "legendFormat": "{{instance}}",
       "target": "aliasByTags(seriesByTag('host=$instance', 'name=~clickhouse_metrics.background_pool_task'), 'host')"
      }
     ]
    },
    {
     "title": "BackgroundFetchesPool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundFetchesPool",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundFetchesPoolTask",
       "legendFormat": "{{instance}}",
       "target": "aliasByTags(seriesByTag('host=$instance', 'name=~clickhouse_metrics.background_fetches_pool_task'), 'host')"
      }
     ]
    },
    {
     "title": "BackgroundMovePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundProcessingPool for moves",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundMovePoolTask",
       "legendFormat": "{{instance}}",
       "target": "aliasByTags(seriesByTag('host=$instance', 'name=~clickhouse_metrics.background_move_pool_task'), 'host')"
      }
     ]
    },
    {
     "title": "BackgroundBufferFlushSchedulePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundBufferFlushSchedulePool. This pool is used for periodic Buffer flushes",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundBufferFlushSchedulePoolTask",
       "legendFormat": "{{instance}}",
       "target": "aliasByTags(seriesByTag('host=$instance', 'name=~clickhouse_metrics.background_buffer_flush_schedule_pool_task'), 'host')"
      }
     ]
    },
    {
     "title": "BackgroundDistributedSchedulePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundDistributedSchedulePool. This pool is used for distributed sends that is done in background.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundDistributedSchedulePoolTask",
       "legendFormat": "{{instance}}",
       "target": "aliasByTags(seriesByTag('host=$instance', 'name=~clickhouse_metrics.background_distributed_schedule_pool_task'), 'host')"
      }
     ]
    },
    {
     "title": "BackgroundMessageBrokerSchedulePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundProcessingPool for message streaming",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundMessageBrokerSchedulePoolTask",
       "legendFormat": "{{instance}}",
       "target": "aliasByTags(seriesByTag('host=$instance', 'name=~clickhouse_metrics.background_message_broker_schedule_pool_task'), 'host')"
      }
     ]
    },
    {
     "title": "BackgroundSchedulePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundSchedulePool. This pool is used for periodic ReplicatedMergeTree tasks, like cleaning old data parts, altering data parts, replica re-initialization, etc.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundSchedulePoolTask",
       "legendFormat": "{{instance}}",
       "target": "aliasByTags(seriesByTag('host=$instance', 'name=~clickhouse_metrics.background_schedule_pool_task'), 'host')"
      }
     ]
    }
   ]
  },
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Init",
   "type": "graph",
   "description": "Number of restarts of zookeeper nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperInit{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.zoo_keeper_init')), 'host')"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "Number of transaction (inserts, removes) completed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperTransactions{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.zoo_keeper_transactions')), 'host')"
    }
   ]
  },
  {
   "title": "List",
   "type": "graph",
   "description": "Number of list requests to get all znodes in the path",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperList{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.zoo_keeper_list')), 'host')"
    }
   ]
  },
  {
   "title": "Create",
   "type": "graph",
   "description": "Number of create znode requests (usually new partitions)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperCreate{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.zoo_keeper_create')), 'host')"
    }
   ]
  },
  {
   "title": "Remove",
   "type": "graph",
   "description": "Number of remove requests to drop znodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperRemove{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.zoo_keeper_remove')), 'host')"
    }
   ]
  },
  {
   "title": "Exists",
   "type": "graph",
   "description": "Number of exist requests to check znodes in the path",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperExists{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.zoo_keeper_exists')), 'host')"
    }
   ]
  },
  {
   "title": "Get",
   "type": "graph",
   "description": "Number of Get requests to get all data from znodes in the path",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperGet{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.zoo_keeper_get')), 'host')"
    }
   ]
  },
  {
   "title": "Watch response",
   "type": "graph",
   "description": "Sum of getData, list and exist requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperWatchResponse{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.zoo_keeper_watch_response')), 'host')"
    }
   ]
  },
  {
   "title": "Multi",
   "type": "graph",
   "description": "Number of requests consist of multiple methods like exist, list, getData",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperMulti{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.zoo_keeper_multi')), 'host')"
    }
   ]
  },
  {
   "title": "Hardware Exceptions",
   "type": "graph",
   "description": "Number of hardware troubles. See the sytem logs or journalctl",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperHardwareExceptions{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(seriesByTag('host=$instance', 'name=clickhouse_events.zoo_keeper_hardware_exceptions'), 'host')"
    }
   ]
  },
  {
   "title": "Close",
   "type": "graph",
   "description": "Number of close requests (usually deleting replicated table)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperClose{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.zoo_keeper_close')), 'host')"
    }
   ]
  },
  {
   "title": "Bytes sent",
   "type": "graph",
   "description": "Incoming bandwidth usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperBytesSent{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.zoo_keeper_bytes_sent')), 'host')"
    }
   ]
  },
  {
   "title": "User Exceptions",
   "type": "graph",
   "description": "Incorrect request recieved from userspace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperUserExceptions{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.zoo_keeper_user_exceptions')), 'host')"
    }
   ]
  },
  {
   "title": "Bytes received",
   "type": "graph",
   "description": "Outgiong bandwidth usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperBytesReceived{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_events.zoo_keeper_bytes_received')), 'host')"
    }
   ]
  },
  {
   "title": "Watches",
   "type": "graph",
   "description": "Number of watches (event subscriptions) in ZooKeeper.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_ZooKeeperWatch",
     "legendFormat": "{{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_metrics.zoo_keeper_watch')), 'host')"
    }
   ]
  },
  {
   "title": "Ephemeral Node",
   "type": "graph",
   "description": "Number of ephemeral nodes hold in ZooKeeper.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_EphemeralNode",
     "legendFormat": "{{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=~clickhouse_zookeeper.root_nodes')), 'host')"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "description": "Number of sessions (connections) to ZooKeeper. Should be no more than one, because using more than one connection to ZooKeeper may lead to bugs due to lack of linearizability (stale reads) that ZooKeeper consistency model allows.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_ZooKeeperSession",
     "legendFormat": "{{instance}}",
     "target": "aliasByTags(perSecond(seriesByTag('host=$instance', 'name=clickhouse_metrics.zoo_keeper_session')), 'host')"
    }
   ]
  }
 ]
}