{
 "title": "Clickhouse",
 "description": "Метрики Clickhouse. Ответственный: Воробьев П.А. (Эксплуатация)",
 "tags": [
  "db",
  "carbon",
  "ClickHouse",
  "service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Сервер",
    "query": "carbon.clickhouse.interval-10sec.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Запросы",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_query_total[1m])",
     "target": "aliasSub(aliasByNode(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.Metrics.Query, -4), '_unix_tensor_ru', '\\1')"
    }
   ]
  },
  {
   "title": "Объединения",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_merge",
     "legendFormat": "merge {{job}}",
     "target": "aliasSub(aliasByNode(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.Metrics.Merge, -4, -1), '_unix_tensor_ru', '\\1')"
    },
    {
     "expr": "clickhouse_merge",
     "legendFormat": "merge {{job}}",
     "target": "aliasSub(aliasByNode(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.ProfileEvents.MergedRows, -4, -1), '_unix_tensor_ru', '\\1')"
    }
   ]
  },
  {
   "title": "Попадания/промахи в кэш",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_mark_cache_misses_total[5m])",
     "legendFormat": "misses {{job}}",
     "target": "aliasSub(aliasSub(aliasByNode(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.ProfileEvents.MarkCache{Misses,Hits}, -4, -1), '_unix_tensor_ru', '\\1'), 'MarkCache', '\\1')"
    }
   ]
  },
  {
   "title": "Чтение/запись",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_read",
     "target": "aliasSub(aliasByNode(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.Metrics.{Read,Write}, -4, -1), '_unix_tensor_ru', '\\1')"
    }
   ]
  },
  {
   "title": "Репликаций выполнено",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_replicated_checks",
     "target": "aliasSub(aliasSub(aliasByNode(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.Metrics.Replicated{Checks,Fetch,Send}, -4, -1), '_unix_tensor_ru', '\\1'), 'Replicated', '\\1')"
    }
   ]
  },
  {
   "title": "Количество реплик",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "clickhouse_leader_replica",
     "legendFormat": "{{job}}",
     "target": "aliasSub(aliasByNode(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.Metrics.LeaderReplica, -4, -1), '_unix_tensor_ru', '\\1')"
    }
   ]
  },
  {
   "title": "ReadOnly replica",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(carbon.clickhouse.interval-10sec.$server.ClickHouse.Metrics.ReadonlyReplica, 1)"
    }
   ]
  },
  {
   "title": "Чтение сжатого буфера",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_compressed_read_buffer_bytes_total[1m])",
     "legendFormat": "{{job}}",
     "target": "aliasSub(aliasByNode(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.ProfileEvents.CompressedReadBufferBytes, -4), '_unix_tensor_ru', '\\1')"
    }
   ]
  },
  {
   "title": "Вставлено строк",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_tcp_connection",
     "legendFormat": "tcp {{instance}}",
     "target": "aliasSub(aliasSub(aliasByNode(scale(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.ProfileEvents.InsertedRows, 0.1), -4), '_unix_tensor_ru', '\\1'), 'Connection', '\\1')"
    }
   ]
  },
  {
   "title": "Соединения",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_tcp_connection",
     "legendFormat": "tcp {{instance}}",
     "target": "aliasSub(aliasSub(aliasByNode(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.Metrics.{TCP,HTTP,Interserver}Connection, -4, -1), '_unix_tensor_ru', '\\1'), 'Connection', '\\1')"
    }
   ]
  },
  {
   "title": "InsertQuery",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "clickhouse_tcp_connection",
     "legendFormat": "tcp {{instance}}",
     "target": "aliasSub(aliasSub(aliasByNode(scale(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.ProfileEvents.InsertQuery, 0.1), -4), '_unix_tensor_ru', '\\1'), 'Connection', '\\1')"
    }
   ]
  },
  {
   "title": "Очередь задач",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_background_pool_task",
     "legendFormat": "{{job}}",
     "target": "aliasSub(aliasByNode(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.Metrics.BackgroundPoolTask, -4), '_unix_tensor_ru', '\\1')"
    }
   ]
  },
  {
   "title": "Средняя нагрузка/переключения контекста",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.*.linux.la.$server.*.cpu.la.m01.avg, 4, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.*.linux.la.$server.*.cpu.contextSwitch.avg, 4, -2)"
    }
   ]
  },
  {
   "title": "Ожидание ввода/вывода",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.*.linux.cpuTime.$server.*.cpu.iowait.avg, 4)"
    }
   ]
  },
  {
   "title": "Использование памяти",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "clickhouse_memory_tracking",
     "target": "aliasSub(aliasSub(aliasByNode(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.Metrics.MemoryTracking, -4), '_unix_tensor_ru', '\\1'), 'Memory', '\\1')"
    }
   ]
  },
  {
   "title": "Использование подкачки",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.*.linux.memory.$server.*.mem.swap.used.avg, 4)"
    }
   ]
  },
  {
   "title": "Использование дисков",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.*.linux.storage.$server.*.storage.io.rps.{sd,vg}*.*.avg, 4, -3, -2)"
    }
   ]
  },
  {
   "title": "Файлов распределённой вставки",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_replicated_checks",
     "target": "aliasSub(aliasSub(aliasByNode(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.Metrics.DistributedFilesToInsert, -4, -1), '_unix_tensor_ru', '\\1'), 'Replicated', '\\1')"
    }
   ]
  },
  {
   "title": "Отправлено распределённых запросов",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_replicated_checks",
     "target": "aliasSub(aliasSub(aliasByNode(carbon.clickhouse.interval-10sec.{$server}*.ClickHouse.Metrics.DistributedSend, -4, -1), '_unix_tensor_ru', '\\1'), 'Replicated', '\\1')"
    }
   ]
  },
  {
   "title": "Утилизация разделов",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.prod.linux.partition.$server.*.partition.volume.*.prc.raw, -3), '_2F', '/')"
    }
   ]
  }
 ]
}