{
 "title": "DNS-LOG",
 "description": "Комплексный экран по сервису логирования dns запросов. Ответственный: -",
 "tags": [
  "dns",
  "telegraf",
  "dns-log",
  "system"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "cluster",
    "query": "tag_values(graylog_name,contur=$contur)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "% времени CPU затрачиваемый на ожидание завершения ввода-вывода, пользовательский режим",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(seriesByTag('contur=~${contur:regex}', 'servertype=$cluster', 'name=~system.cpu.usage(_iowait|_user)', 'cpu=cpu-total'), 'host', 'name'), 0, -1), 'usage_', '')"
    }
   ]
  },
  {
   "title": "Disk activity",
   "type": "graph",
   "description": "вверх - байт на запить\nвниз - байт на чтение",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(perSecond(aliasByTags(seriesByTag('contur=~${contur:regex}', 'servertype=$cluster', 'name=~system.diskio.(read|write)_bytes', '_name=~ sd(a|b)$'), 'host', 'name', '_name')), 0, -2, -1), '_bytes', '')"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "% использования памяти",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('contur=~${contur:regex}', 'servertype=$cluster', 'name=system.mem.used_percent'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  {
   "title": "Status elastic",
   "type": "stat",
   "description": "Статус кластера Elasticsearch",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('contur=~${contur:regex}', '_name=$cluster', 'name=service.elastic.status_code'), 1)"
    }
   ]
  },
  {
   "title": "Messages rate msg/s",
   "type": "graph",
   "description": "Кол-во сообщений в секунду",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=org.graylog2.throughput.input.1-sec-rate', 'contur=~${contur:regex}', 'graylog_name=$cluster'), 'host', 'name'), 0, 7)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=org.graylog2.throughput.output.1-sec-rate', 'contur=~${contur:regex}', 'graylog_name=$cluster'), 'host', 'name'), 0, 7)"
    },
    {
     "target": "alias(sum(seriesByTag('name=org.graylog2.throughput.input.1-sec-rate', 'contur=~${contur:regex}', 'graylog_name=$cluster')), 'Sum input')"
    }
   ]
  },
  {
   "title": "Journal utilization",
   "type": "graph",
   "description": "Использование журнала",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(consolidateBy(seriesByTag('name=org.graylog2.journal.utilization-ratio', 'contur=~${contur:regex}', 'graylog_name=$cluster'), 'maximum'), 'host', 'name'), 0)"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "graph",
   "description": "Размер и использование буфера.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag( 'contur=~${contur:regex}', 'graylog_name=$cluster', 'name=org.graylog2.buffers.input.size'), 'host', 'name'), 0, 7, 8)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag( 'contur=~${contur:regex}', 'graylog_name=$cluster', 'name=org.graylog2.buffers.input.usage'), 'host', 'name'), 0, 7, 8)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag( 'contur=~${contur:regex}', 'graylog_name=$cluster', 'name=org.graylog2.buffers.output.size'), 'host', 'name'), 0, 7, 8)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag( 'contur=~${contur:regex}', 'graylog_name=$cluster', 'name=org.graylog2.buffers.output.usage'), 'host', 'name'), 0, 7, 8)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag( 'contur=~${contur:regex}', 'graylog_name=$cluster', 'name=org.graylog2.buffers.process.size'), 'host', 'name'), 0, 7, 8)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag( 'contur=~${contur:regex}', 'graylog_name=$cluster', 'name=org.graylog2.buffers.process.usage'), 'host', 'name'), 0, 7, 8)"
    }
   ]
  },
  {
   "title": "Journal",
   "type": "graph",
   "description": "Размеры журналов",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=org.graylog2.journal.append.1-sec-rate',  'contur=~${contur:regex}', 'graylog_name=$cluster'), 'host', 'name'), 0, 7, 8, 9)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=org.graylog2.journal.size', 'contur=~${contur:regex}', 'graylog_name=$cluster'), 'host', 'name'), 0, 7, 8, 9)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=org.graylog2.journal.size-limit',  'contur=~${contur:regex}', 'graylog_name=$cluster'), 'host', 'name'), 0, 7, 8, 9)"
    }
   ]
  },
  {
   "title": "JVM memory",
   "type": "graph",
   "description": "Кол-во памяти всего/используется",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=jvm.memory.total.init', 'contur=~${contur:regex}', 'graylog_name=$cluster'), 'host', 'name'), 0, 5, 6, 7)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=jvm.memory.total.used',  'contur=~${contur:regex}', 'graylog_name=$cluster'), 'host', 'name'), 0, 5, 6, 7)"
    }
   ]
  },
  {
   "title": "IPVS conection",
   "type": "graph",
   "description": "Кол-во активных подключений",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=ipvs_real_server.active_connections', 'servertype=$cluster', 'port=6000', 'virtual_protocol=tcp'), 'host', 'address'), true, false)"
    }
   ]
  }
 ]
}