{
 "title": "Elasticsearch (telegraf)",
 "description": "Экран Elasticsearch. Ответственный: Нет ответственного.",
 "tags": [
  "telegraf",
  "elasticsearch",
  "service"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "Cluster",
    "label": "Кластер",
    "query": "tag_values(_name,contur=$contur,servertype=elasticsearch)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(highestMax(seriesByTag('name=service.elastic.number_of_nodes', '_name=$Cluster'), 1), 'nodes')"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(highestMax(seriesByTag('name=service.elastic.number_of_data_nodes', '_name=$Cluster'), 1), 'nodes')"
    }
   ]
  },
  {
   "title": "Active Shards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(highestMax(seriesByTag('name=service.elastic.active_shards', '_name=$Cluster'), 1), 'nodes')"
    }
   ]
  },
  {
   "title": "Pri. Shards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('name=service.elastic.active_primary_shards', '_name=$Cluster'), 1)"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('name=service.elastic.initializing_shards', '_name=$Cluster'), 1)"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('name=service.elastic.unassigned_shards', '_name=$Cluster'), 1)"
    }
   ]
  },
  {
   "title": "Delayed Un. Shards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('name=service.elastic.delayed_unassigned_shards', '_name=$Cluster'), 1)"
    }
   ]
  },
  {
   "title": "Relocating Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('name=service.elastic.relocating_shards', '_name=$Cluster'), 1)"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('name=service.elastic.number_of_pending_tasks', '_name=$Cluster'), 1)"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('name=service.elastic.status_code', '_name=$Cluster'), 1)"
    }
   ]
  },
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Primary Docs Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(highestMax(seriesByTag('name=service.elastic.docs_count', 'cluster_name=$Cluster', 'contur=${contur:regex}'), 1), 'host', 'name'), 0, -1)"
    },
    {
     "target": "aliasByNode(aliasByTags(highestMax(seriesByTag('name=service.elastic.docs_deleted', 'cluster_name=$Cluster', 'contur=${contur:regex}'), 1), 'host', 'name'), 0, -1)"
    }
   ]
  },
  {
   "title": "Total Store Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=service.elastic.fs_total_in_bytes', 'cluster_name=$Cluster', 'contur=${contur:regex}'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Master Node CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "seriesByTag('name=service.elastic.process_cpu_percent', 'cluster_name=$Cluster', 'contur=${contur:regex}')"
    }
   ]
  },
  {
   "title": "FS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=service.elastic.fs_free_in_bytes', 'cluster_name=$Cluster', 'contur=${contur:regex}'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=service.elastic.jvm_mem_heap_used_in_bytes', 'cluster_name=$Cluster', 'contur=${contur:regex}'), 'host'), 0)"
    }
   ]
  },
  { "title": "Cluster Indices Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Indexing Rate /per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.indexing_index_total', 'contur=${contur:regex}')), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Indexing Latency /per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByNode(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.indexing_index_time_in_millis', 'contur=${contur:regex}')), 'host'), 0), false)"
    }
   ]
  },
  {
   "title": "Merges /per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByNode(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.merges_total', 'contur=${contur:regex}')), 'host'), 0), false)"
    }
   ]
  },
  {
   "title": "Segments Memory / Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByNode(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.segments_memory_in_bytes', 'contur=${contur:regex}', 'node_roles=~.*data.*'), 'host'), 0), false)"
    },
    {
     "target": "aliasSub(aliasByNode(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.segments_count', 'contur=${contur:regex}', 'node_roles=~.*data.*'), 'host'), 0), '$', ' segments count')"
    }
   ]
  },
  {
   "title": "Search Rate / Latency  /per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=~service.elastic.search_query_(total|time_in_millis)', 'contur=${contur:regex}')), 'host', 'name'), 'perSecond\\(', ''), 0, -1), false)"
    }
   ]
  },
  {
   "title": "Field Data Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.fielddata_memory_size_in_bytes', 'contur=${contur:regex}')), 'host'), false)"
    }
   ]
  },
  {
   "title": "Merges Latency /per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByNode(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.merges_total_time_in_millis', 'contur=${contur:regex}')), 'host'), 0), false)"
    }
   ]
  },
  { "title": "Node OS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "FS Free",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.total_free_in_bytes', 'contur=${contur:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "CPU Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByNode(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.cpu_percent', 'contur=${contur:regex}'), 'host'), 0), false)"
    }
   ]
  },
  {
   "title": "CPU Instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.cpu_total_in_millis', 'contur=${contur:regex}')), 'host'), false)"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.cpu_load_average_1m', 'contur=${contur:regex}'), 'host'), false)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.mem_used_in_bytes', 'contur=${contur:regex}'), 'host'), false)"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.swap_used_in_bytes', 'contur=${contur:regex}'), 'host'), false)"
    }
   ]
  },
  {
   "title": "fs.io_stats.total Read /per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.io_stats_total_read_kilobytes', 'contur=${contur:regex}')), 'host'), false)"
    }
   ]
  },
  {
   "title": "fs.io_stats.total Write /per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.io_stats_total_write_kilobytes', 'contur=${contur:regex}')), 'host'), false)"
    }
   ]
  },
  {
   "title": "Transport /per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.translog_size_in_bytes', 'contur=${contur:regex}')), 'host'), false)"
    }
   ]
  },
  { "title": "Node Stats Indices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Field Data & Breakers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.request_estimated_size_in_bytes', 'contur=${contur:regex}'), 'host', 'name'), 0, -1)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.parent_estimated_size_in_bytes', 'contur=${contur:regex}'), 'host', 'name'), 0, -1)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.fielddata_estimated_size_in_bytes', 'contur=${contur:regex}'), 'host', 'name'), 0, -1)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.fielddata_memory_size_in_bytes', 'contur=${contur:regex}'), 'host', 'name'), 0, -1)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.in_flight_requests_estimated_size_in_bytes', 'contur=${contur:regex}'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  {
   "title": "HTTP Open",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.total_opened', 'contur=${contur:regex}')), 'host'), false)"
    }
   ]
  },
  {
   "title": "Indices docs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=~service.elastic.docs', 'contur=${contur:regex}')), 'host', 'name'), 'perSecond\\(', ''), 0, -1), false)"
    }
   ]
  },
  {
   "title": "Indexing Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.indexing_index_time_in_millis', 'contur=${contur:regex}')), 'host'), false)"
    }
   ]
  },
  {
   "title": "Indexing Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.indexing_index_total', 'contur=${contur:regex}')), 'host'), false)"
    }
   ]
  },
  {
   "title": "Merges Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=~service.elastic.merges_(total|total_docs)$', 'contur=${contur:regex}')), 'host', 'name'), 'perSecond\\(', ''), 0, -1), false)"
    }
   ]
  },
  {
   "title": "merges.total_size_in_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.merges_total_size_in_bytes', 'contur=${contur:regex}')), 'host'), false)"
    }
   ]
  },
  {
   "title": "Merges Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.merges_total_throttled_time_in_millis', 'contur=${contur:regex}')), 'host', 'name'), 'perSecond\\(', ''), 0, -1), false)"
    },
    {
     "target": "sortByName(aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.refresh_total_time_in_millis', 'contur=${contur:regex}')), 'host', 'name'), 'perSecond\\(', ''), 0, -1), false)"
    }
   ]
  },
  {
   "title": "Indices Search",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.search_query_time_in_millis', 'contur=${contur:regex}')), 'host', 'name'), 'perSecond\\(', ''), 0, -1), false)"
    },
    {
     "target": "sortByName(aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.search_query_total', 'contur=${contur:regex}')), 'host', 'name'), 'perSecond\\(', ''), 0, -1), false)"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.segments_count', 'contur=${contur:regex}'), 'host'), false)"
    }
   ]
  },
  {
   "title": "Segments Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.segments_memory_in_bytes', 'contur=${contur:regex}'), 'host'), false)"
    }
   ]
  },
  {
   "title": "Translog",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.translog_size_in_bytes', 'contur=${contur:regex}'), 'host'), false)"
    }
   ]
  },
  { "title": "Node JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.jvm_max_uptime_in_millis', 'contur=${contur:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "asPercent(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.jvm_mem_heap_used_in_bytes', 'contur=${contur:regex}'), 'host'), #C)",
     "targetFull": "asPercent(aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.jvm_mem_heap_used_in_bytes', 'contur=${contur:regex}'), 'host'), aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.jvm_mem_heap_max_in_bytes', 'contur=${contur:regex}'), 'host'))"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster_name=$Cluster', 'name=service.elastic.jvm_mem_heap_used_in_bytes', 'contur=${contur:regex}'), 'host')"
    }
   ]
  }
 ]
}