{
 "title": "Email: статистика отправок",
 "description": "Комплексный экран для просмотра логов smtp серверов, подключенных к mail-log. Ответственный: Казанкин Л.Е./Никитин М.С. (Эксплуатация)",
 "tags": [
  "email",
  "telegraf",
  "scripts",
  "service"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Source",
    "query": "{\"find\":\"terms\", \"field\":\"source\"}"
   },
   {
    "name": "Email",
    "query": "{\"find\":\"terms\", \"field\":\"email\", \"query\":\"source:$Source\"}"
   },
   {
    "name": "Exim_id",
    "query": "{\"find\":\"terms\", \"field\":\"exim_id\", \"query\":\"email:$Email\"}"
   },
   {
    "name": "Spam_Exim_id",
    "query": "{\"find\":\"terms\", \"field\":\"exim_id\", \"query\":\"transport_name:maildir_spam_delivery AND router_name:maildir_spam AND message_type:to\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Лог отправки писем",
   "type": "table",
   "description": "В поле Email вводится адрес с которого шли отправки, например, в списке он может не появится, это норма, жмете Enter и должно подставится.\n\nComplete - Хорошо\n\nmessage_type != {to,from} - Плохо",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "exim_id:$Exim_id AND source:$Source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Спам / Ошибки",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Соотношение принятых и переданных писем",
     "type": "piechart",
     "description": "Соотношение принятых и переданных писем по источникам. Чем больше к 50%, тем лучше. (письма не задерживаются в очереди)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "FROM",
       "bucketAggs": [
        { "field": "timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "source:$Source AND message_type:from AND reception_time:>=0.000s",
       "timeField": "timestamp"
      },
      {
       "alias": "TO",
       "bucketAggs": [
        { "field": "timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "source:$Source AND message_type:to AND delivery_time:>=0.000s",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Количество полученных писем ОТ доменов первого уровня",
     "type": "barchart",
     "description": "source:$Source AND message_type:from AND reception_time:>=0.000s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "email",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "source:$Source AND message_type:from AND reception_time:>=0.000s",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Общее количество и Топ 10 адресов полученных писем ОТ",
     "type": "graph",
     "description": "source:$Source AND message_type:from AND reception_time:>=0.000s",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "email",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "source:$Source AND message_type:from AND reception_time:>=0.000s",
       "timeField": "timestamp"
      },
      {
       "alias": "Всего писем",
       "bucketAggs": [
        { "field": "timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "source:$Source AND message_type:from AND reception_time:>=0.000s",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Общее количество и Топ 10 адресов отправленных писем ДО",
     "type": "graph",
     "description": "source:$Source AND message_type:to AND delivery_time:>=0.000s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "email",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "source:$Source AND message_type:to AND delivery_time:>=0.000s",
       "timeField": "timestamp"
      },
      {
       "alias": "Всего писем",
       "bucketAggs": [
        { "field": "timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "source:$Source AND message_type:to AND delivery_time:>=0.000s",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Общее количество и Топ 10 отправителей спама в нашу сторону",
     "type": "graph",
     "description": "В нашу сторону. Считаются только те, которые успешно доставили письмо по maildir_spam_delivery",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "email",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "exim_id:$Spam_Exim_id AND source:$Source AND message_type:from",
       "timeField": "timestamp"
      },
      {
       "alias": "Всего писем",
       "bucketAggs": [
        { "field": "timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "exim_id:$Spam_Exim_id AND source:$Source AND message_type:from",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Ошибки отправки (message_type:failed)",
     "type": "table",
     "description": "Лог ошибок отправок SMTP серверов.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "message_type:failed AND source:$Source",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Нагрузка на mail-log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load average",
     "type": "graph",
     "description": "Среднее значение загрузки системы. Чем ниже эта величина, тем менее нагружена система. ",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('host=mail-log.unix.tensor.ru', 'name=system.system.load1'), 'LA1')"
      },
      {
       "target": "alias(seriesByTag('host=mail-log.unix.tensor.ru', 'name=system.system.load5'), 'LA5')"
      },
      {
       "target": "alias(seriesByTag('host=mail-log.unix.tensor.ru', 'name=system.system.load15'), 'LA15')"
      },
      {
       "target": "alias(seriesByTag('host=mail-log.unix.tensor.ru', 'name=system.system.n_cpus'), 'CPU numbers')"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "description": "Процент загруженности ядра.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('host=mail-log.unix.tensor.ru', 'name=system.cpu.usage_user', 'cpu=cpu-total'), 'Usage_user')"
      },
      {
       "target": "alias(seriesByTag('host=mail-log.unix.tensor.ru', 'name=system.cpu.usage_system', 'cpu=cpu-total'), 'Usage_system')"
      },
      {
       "target": "alias(seriesByTag('host=mail-log.unix.tensor.ru', 'name=system.cpu.usage_softirq', 'cpu=cpu-total'), 'Usage_softirq')"
      },
      {
       "target": "alias(seriesByTag('host=mail-log.unix.tensor.ru', 'name=system.cpu.usage_iowait', 'cpu=cpu-total'), 'Usage_iowait')"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "description": "Метрика оперативной памяти.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('host=mail-log.unix.tensor.ru', 'name=system.mem.total'), 'Total')"
      },
      {
       "target": "alias(seriesByTag('host=mail-log.unix.tensor.ru', 'name=system.mem.available'), 'Available')"
      },
      {
       "target": "alias(seriesByTag('host=mail-log.unix.tensor.ru', 'name=system.mem.used'), 'Used')"
      },
      {
       "target": "alias(seriesByTag('host=mail-log.unix.tensor.ru', 'name=system.swap.total'), 'Swap total')"
      },
      {
       "target": "alias(seriesByTag('host=mail-log.unix.tensor.ru', 'name=system.swap.used'), 'Swap used')"
      }
     ]
    }
   ]
  }
 ]
}