{
 "title": "eventmq web",
 "description": "Ответственный:  Конюхов М.В. (Эксплуатация)",
 "tags": [
  "sbis3mon-kafka",
  "service",
  "mv.konuhov"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.web.pushStat.*"
   }
  ]
 },
 "panels": [
  { "title": "$server (status, xhr)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.http_5Fstatus.raw, -2), '_5F', ' ')"
    }
   ]
  },
  {
   "title": "$server: xhr",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.xhr.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: front isOpen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.front.isOpen.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: front sess",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.front.sess.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: front http",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.front.http.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: front request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.front.requests.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: front bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.front.bytes.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: mgr",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.mgr.isUp.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.mgr.errors.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.mgr.queue.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: mgr http",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.mgr.http.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: mgr check",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.mgr.check.*.raw, -2), '(_20|_5F)', ' ')"
    }
   ]
  },
  {
   "title": "$server: mgr state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.mgr.state.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: mgr times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.mgr.avg_5Ftimes.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: mgr bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.mgr.bytes.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: mgr sess",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.mgr.sess.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: ws",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.ws.isUp.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.ws.errors.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.ws.queue.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: ws bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.ws.bytes.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: ws http",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.ws.http.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: ws times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.ws.avg_5Ftimes.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: ws sess",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.web.pushStat.$server.eventmq-web.*.eventmq-web.ws.sess.*.raw, -2)"
    }
   ]
  }
 ]
}