{
 "title": "Flussonic mediaserver",
 "description": "Комплексный экран по Flussonic. Ответственный:  Конюхов М.В. (Эксплуатация)",
 "tags": [
  "mv.konuhov",
  "видеонаблюдение",
  "videostreaming",
  "flussonic",
  "telegraf",
  "exploitation",
  "service"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "host",
    "label": "Сервер",
    "query": "tag_values(host,contur=$contur,servertype=videostreaming)"
   },
   {
    "name": "camera",
    "label": "Камера",
    "query": "tag_values(camera_name,contur=$contur,servertype=videostreaming,host=$host,name=flussonic_snmp.camera_bitrate)"
   }
  ]
 },
 "panels": [
  { "title": "Статистика по $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flussonic process started at $host",
   "type": "stat",
   "description": "epoch timestamp в наносекундах - время когда стартовал процесс.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(aliasByTags(seriesByTag('name=procstat.flussonic.created_at', 'contur=${contur}', 'host=${host}'), 'name'), 0.000001)"
    }
   ]
  },
  {
   "title": "Flussonic process faults $host",
   "type": "stat",
   "description": "procstat flussonic фейлы процессов в секундах",
   "gridPos": { "h": 5, "w": 9, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~procstat.flussonic.*faults', 'contur=${contur}', 'host=${host}')), 'name'), 'procstat.flussonic.', '')"
    }
   ]
  },
  {
   "title": "Flussonic OOM Killer Counter $host",
   "type": "graph",
   "description": "все вхождения oom_killer в логах на системе выводятся в файл, у которого ведется подсчет строк. ежесуточная ротация файла сбрасывает counter. -1 означает отсутствие файла, no data означают проблемы скрипта.",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=flussonic_oomkiller_count', 'contur=${contur}', 'host=${host}'), 'name')"
    }
   ]
  },
  {
   "title": "Flussonic procstat on $host",
   "type": "graph",
   "description": "systemd procstat.flussonic.memory - статистика по выделению и использованию памяти процессом flussonic\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasSub(aliasByNode(aliasByTags(seriesByTag('host=$host', 'name=~procstat.flussonic.memory.*', 'contur=$contur'), 'name'), -1), 'memory_', ''))"
    }
   ]
  },
  {
   "title": "Memory used by $host",
   "type": "graph",
   "description": "Статистика использования памяти на выбранном в фильтре сервере",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.used'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.free'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.shared'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.buffered'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.cached'), 'name')), 'max')"
    }
   ]
  },
  {
   "title": "Traffic summary OUT $host",
   "type": "graph",
   "description": "Скрипт sbis_flussonic_traffic\nСуммарный исходящий трафик по всему серверу со всех камер",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=flussonic_traffic', 'contur=${contur}', 'host=${host}')), 'name')"
    }
   ]
  },
  {
   "title": "Traffic summary IN $host",
   "type": "graph",
   "description": "Суммарный входящий трафик по всему серверу со всех камер",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(sumSeries(seriesByTag('name=flussonic_snmp.camera_traffic_in', 'contur=${contur}', 'host=${host}'))), 'name')"
    }
   ]
  },
  {
   "title": "flussonic.ru HTTP response and HTTP Code $host",
   "type": "graph",
   "description": "net_response 80/443 порт\nдоступность самого сервиса flussonic\n0 = нет данных, проблема доступа\nнормальные коды ответа - 200 и 302",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=flussonic_web.response_time', 'contur=${contur}', 'host=${host}', 'server=https:--flussonic.ru-'), 'flussonic.ru ping')"
    },
    {
     "target": "alias(seriesByTag('name=flussonic_web.http_response_code', 'contur=${contur}', 'host=${host}', 'server=https:--flussonic.ru-'), 'flussonic.ru http code')"
    },
    {
     "target": "alias(seriesByTag('name=flussonic_web.response_time', 'contur=${contur}', 'host=${host}', 'server=http:--localhost'), 'localhost flussonic ping')"
    },
    {
     "target": "alias(seriesByTag('name=flussonic_web.http_response_code', 'contur=${contur}', 'host=${host}', 'server=http:--localhost'), 'localhost flussonic http code')"
    }
   ]
  },
  {
   "title": "Flussonic Licence errors $host",
   "type": "graph",
   "description": "проверка лицензии. если сервер не имеет доступа к лицензиям - будут ошибки",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=flussonic_log', 'contur=${contur}', 'host=${host}'), 'name')"
    }
   ]
  },
  {
   "title": "Flussonic connected clients and cameras $host",
   "type": "graph",
   "description": "Скрипт sbis_flussonic_clients\nобщее количество подключенных клиентов",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=flussonic_clients', 'contur=${contur}', 'host=${host}'), 'name')"
    }
   ]
  },
  {
   "title": "Flussonic cameras counter $host",
   "type": "graph",
   "description": "Статистика по подключенным к системе камерам. active = 1, notInService = 2, notReady = 3. Мы выводим общее количество, кол-во с проблемами и кол-во с норм статусом.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=flussonic_snmp.total_cameras_connected', 'contur=prod', 'host=${host}', 'service=flussonic'), 'Total cameras')"
    },
    {
     "target": "alias(countSeries(maximumBelow(maximumAbove(groupByTags(seriesByTag('name=flussonic_snmp.camera_status', 'contur=prod', 'host=${host}', 'service=flussonic'), 'max', 'camera_name'), 0.9), 1.1)), 'Total cameras with status 1')"
    },
    {
     "target": "alias(countSeries(maximumBelow(maximumAbove(groupByTags(seriesByTag('name=flussonic_snmp.camera_status', 'contur=prod', 'host=${host}', 'service=flussonic'), 'max', 'camera_name'), 1.1), 2.1)), 'Total cameras with status 2')"
    },
    {
     "target": "alias(countSeries(maximumBelow(maximumAbove(groupByTags(seriesByTag('name=flussonic_snmp.camera_status', 'contur=prod', 'host=${host}', 'service=flussonic'), 'max', 'camera_name'), 2.1), 3.1)), 'Total cameras with status 3')"
    }
   ]
  },
  {
   "title": "CPU usage $host",
   "type": "graph",
   "description": "использование CPU по каждому ядру системы",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu!=cpu-total', 'contur=${contur}', 'host=${host}'), 'cpu')"
    }
   ]
  },
  {
   "title": "LA $host",
   "type": "graph",
   "description": "Показывает LA1, LA5, LA15 и кол-во ядер CPU на сервере.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~system.system.load', 'contur=${contur}', 'host=${host}'), 2)"
    },
    {
     "target": "aliasByTags(seriesByTag('name=system.system.n_cpus', 'contur=${contur}', 'host=${host}'), 2)"
    }
   ]
  },
  {
   "title": "Context switching $host",
   "type": "graph",
   "description": "context_switching usage - переключение контекста между ядрами CPU на сервере",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~system.kernel.context_switches', 'contur=${contur}', 'host=${host}')), 2)"
    }
   ]
  },
  {
   "title": "Net bps $host",
   "type": "graph",
   "description": "входящий (RX) и исходящий (TX) трафик в байтах в секунду на всех сетевых интерфейсах.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(perSecond(seriesByTag('name=~system.net.bytes_(sent|recv)', 'contur=${contur}', 'host=${host}')))"
    }
   ]
  },
  {
   "title": "Connections $host",
   "type": "graph",
   "description": "connection stats - статистики подключений на всем сервере",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~system.netstat.*', 'contur=${contur}', 'host=${host}'), 'name')"
    }
   ]
  },
  {
   "title": "Disk IO Time $host",
   "type": "graph",
   "description": "diskio.io_time - время обращения к подмонтированным разделам диска на чтение и запись",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~system.diskio.io_time', 'contur=${contur}', 'host=${host}')), '_name', 'name')"
    }
   ]
  },
  { "title": "Камера ${camera}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }, "repeat": "container" },
  {
   "title": "Clients connected",
   "type": "graph",
   "description": "oid = \"1.3.6.1.4.1.36342.1.1.2.1.3\"\nкол-во подключенных пользователей к камере на просмотр.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=flussonic_snmp.camera_clients_count', 'contur=${contur}', 'host=${host}', 'camera_name=${camera}'), 'host', 'camera_name')"
    }
   ]
  },
  {
   "title": "Camera status",
   "type": "graph",
   "description": "oid = \"1.3.6.1.4.1.36342.1.1.2.1.9\". показывает статус камеры. всего существует 3 статуса:\n- active = 1 \n- notInService = 2\n- notReady = 3",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=flussonic_snmp.camera_status', 'contur=${contur}', 'host=${host}', 'camera_name=${camera}'), 'host', 'camera_name')"
    }
   ]
  },
  {
   "title": "Camera bitrate",
   "type": "graph",
   "description": "oid = \"1.3.6.1.4.1.36342.1.1.2.1.6\". битрейт — скорость передачи битов за определенный период времени  (объём информации измеряют в байтах, а скорость в битах). в нашем случае это битрейт камеры из расчета битов, посланных в секунду.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=flussonic_snmp.camera_bitrate', 'contur=${contur}', 'host=${host}', 'camera_name=${camera}'), 'host', 'camera_name')"
    }
   ]
  },
  {
   "title": "Camera Traffic IN",
   "type": "graph",
   "description": "oid = \"1.3.6.1.4.1.36342.1.1.2.1.7\" - входящий на медиасервер трафик от камеры в секунду.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=flussonic_snmp.camera_traffic_in', 'contur=${contur}', 'host=${host}', 'camera_name=${camera}')), 'host', 'camera_name')"
    }
   ]
  },
  {
   "title": "Camera Traffic OUT",
   "type": "graph",
   "description": "oid = \"1.3.6.1.4.1.36342.1.1.2.1.8\". отдаваемый по камере трафик в секунду в байтах,",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=flussonic_snmp.camera_traffic_out', 'contur=${contur}', 'host=${host}', 'camera_name=${camera}')), 'host', 'camera_name')"
    }
   ]
  }
 ]
}