{
 "title": "GitLab pipeline",
 "description": "Ответственный: Окунев А.С. (АЦОД)",
 "tags": [
  "GitLab",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "tag_values(host, servertype = gitlab)"
   },
   {
    "name": "project",
    "query": "tag_values(project, host=$host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pipelines",
   "type": "stat",
   "description": "Общее кол-во пайплайнов",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(seriesByTag('name=gitlab.pipeline_status', 'host=~${host:regex}', 'project=~${project:regex}'))"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "description": "Success Pipelines",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(seriesByTag('name=gitlab.pipeline_status', 'status=success', 'host=~${host:regex}', 'project=~${project:regex}'))"
    }
   ]
  },
  {
   "title": "Filed",
   "type": "stat",
   "description": "Filed Pipelines",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(seriesByTag('name=gitlab.pipeline_status', 'status=failed', 'host=~${host:regex}', 'project=~${project:regex}'))"
    }
   ]
  },
  {
   "title": "Runs",
   "type": "stat",
   "description": "Runs Pipelines",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(seriesByTag('name=gitlab.pipeline_status', 'status=running', 'host=~${host:regex}', 'project=~${project:regex}'))"
    }
   ]
  },
  {
   "title": "Skipped",
   "type": "stat",
   "description": "Skipped Pipelines",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(seriesByTag('name=gitlab.pipeline_status', 'status=skipped', 'host=~${host:regex}', 'project=~${project:regex}'))"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "description": "Pending Pipelines",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(seriesByTag('name=gitlab.pipeline_status', 'status=pending', 'host=~${host:regex}', 'project=~${project:regex}'))"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "description": "Canceled Pipelines",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(seriesByTag('name=gitlab.pipeline_status', 'status=canceled', 'host=~${host:regex}', 'project=~${project:regex}'))"
    }
   ]
  },
  {
   "title": "URL",
   "type": "table",
   "description": "Источник получения метрик",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(groupByTags(seriesByTag('name=gitlab.pipeline_status', 'host=~${host:regex}', 'project=~${project:regex}'), 'count', 'url'), 'url'), '--', '//'), '-metrics', '/metrics')"
    }
   ]
  },
  {
   "title": "Pipeline ID",
   "type": "table",
   "description": "ID последнего запущенного пайплайна по проекту",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "target": "sortByMinima(aliasByTags(seriesByTag('name=gitlab.pipeline_id', 'host=~${host:regex}', 'project=~${project:regex}'), 'project'))"
    }
   ]
  },
  {
   "title": "Pipeline run count",
   "type": "table",
   "description": "Кол-во выполненных пайплайнов по проекту",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=gitlab.pipeline_run_count', 'host=~${host:regex}', 'project=~${project:regex}'), 'project')"
    }
   ]
  },
  {
   "title": "Pipeline duration",
   "type": "table",
   "description": "Duration in seconds of the most recent pipeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(seriesByTag('name=gitlab.pipeline_duration', 'host=~${host:regex}', 'project=~${project:regex}'), 'project'))"
    }
   ]
  },
  {
   "title": "Skipped, failed, pending, canceled",
   "type": "table",
   "description": "Список проектов с неуспешно завершенным статусом пайплайна",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=gitlab.pipeline_status', 'status=~(canceled|failed|skipped|pending)', 'host=~${host:regex}', 'project=~${project:regex}'), 'project')"
    }
   ]
  },
  {
   "title": "Successfully complited",
   "type": "table",
   "description": "Список проектов с успешно завершенным статусом пайплайна",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=gitlab.pipeline_status', 'status=success', 'host=~${host:regex}', 'project=~${project:regex}'), 'project')"
    }
   ]
  },
  {
   "title": "Running",
   "type": "table",
   "description": "Список проектов с выполняющимся пайплайном",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=gitlab.pipeline_status', 'status=running', 'host=~${host:regex}', 'project=~${project:regex}'), 'project')"
    }
   ]
  }
 ]
}