{
 "title": "HtmlConverter",
 "description": "Ответственный: -",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "converter_server", "label": "Main", "query": "tag_values(host)" },
   { "name": "big_server", "label": "BIG", "query": "tag_values(host)" },
   { "name": "webshot_server", "label": "Webshot", "query": "tag_values(host)" }
  ]
 },
 "panels": [
  {
   "title": "Converter Free Ram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByNode(sbis3mon.prod.linux.memory.$converter_server.*.mem.ram.free.min, -6), '.*bl(\\d+)', '\\1'), true)"
    }
   ]
  },
  {
   "title": "Converter LA",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByNode(sbis3mon.prod.linux.la.$converter_server.*.cpu.la.m01.max, -6), '.*bl(\\d\\d?)', '\\1'), true)"
    },
    { "target": "alias(constantLine(9), '|')" },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.prod.linux.la.$big_server.*.cpu.la.m01.max, -6), '.*bl(\\d)', '\\1')"
    },
    { "target": "alias(constantLine(9), '|')" },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.prod.linux.la.$webshot_server.*.cpu.la.m01.max, -6), '.*bl(\\d+)', '\\1')"
    }
   ]
  },
  {
   "title": "Main Queue",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "exclude(sortByName(aliasSub(aliasByTags(seriesByTag('contur=prod', 'name=queue.size', 'service=converter_html', 'type=work'), 'host', 'type'), 'csr-pdfconvert-bl(\\d*).*', '\\1'), true, false), '^\\..*')"
    },
    { "target": "alias(constantLine(8), '|')" },
    {
     "target": "exclude(sortByName(aliasSub(aliasByTags(seriesByTag('contur=prod', 'name=queue.size', 'service=converter_big_html', 'type=work'), 'host', 'type'), 'csr-big-html-bl(\\d*).*', '\\1'), true, false), '^\\..*')"
    },
    { "target": "alias(constantLine(8), '|')" },
    {
     "target": "exclude(sortByName(aliasSub(aliasByTags(seriesByTag('contur=prod', 'name=queue.size', 'service=webshot', 'type=work'), 'host', 'type'), 'csr-webshot-bl(\\d*).*', '\\1'), true, false), '^\\..*')"
    }
   ]
  },
  {
   "title": "Service Queue",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "exclude(sortByName(aliasSub(aliasByTags(seriesByTag('contur=prod', 'name=queue.size', 'service=converter_html', 'type=special'), 'host', 'type'), 'csr-pdfconvert-bl(\\d*).*', '\\1'), true, false), '^\\..*')"
    },
    { "target": "alias(constantLine(8), '|')" },
    {
     "target": "exclude(sortByName(aliasSub(aliasByTags(seriesByTag('contur=prod', 'name=queue.size', 'service=converter_big_html', 'type=special'), 'host', 'type'), 'csr-big-html-bl(\\d*).*', '\\1'), true, false), '^\\..*')"
    },
    { "target": "alias(constantLine(8), '|')" },
    {
     "target": "exclude(sortByName(aliasSub(aliasByTags(seriesByTag('contur=prod', 'name=queue.size', 'service=webshot', 'type=special'), 'host', 'type'), 'csr-webshot-bl(\\d*).*', '\\1'), true, false), '^\\..*')"
    }
   ]
  },
  {
   "title": "Big Free Ram",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.prod.linux.memory.$big_server.*.mem.ram.free.min, -6), '.*(bl\\d+)', '\\1')"
    }
   ]
  },
  {
   "title": "Очереди",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "exclude(aliasSub(maximumAbove(sortByName(aliasByTags(seriesByTag('contur=prod', 'name=queue.size', 'service=converter_html'), 'host', 'type'), true, false), 2), 'csr-pdfconvert-bl(\\d*\\..).*', 'C-\\1'), '^\\..*')"
    },
    {
     "target": "exclude(aliasSub(maximumAbove(sortByName(aliasByTags(seriesByTag('contur=prod', 'name=queue.size', 'service=converter_big_html'), 'host', 'type'), true, false), 2), 'csr-big-html-bl(\\d*\\..).*', 'B-\\1'), '^\\..*')"
    },
    {
     "target": "exclude(aliasSub(maximumAbove(sortByName(aliasByTags(seriesByTag('contur=prod', 'name=queue.size', 'service=webshot'), 'host', 'type'), true, false), 2), 'csr-webshot-bl(\\d*\\..).*', 'W-\\1'), '^\\..*')"
    }
   ]
  },
  {
   "title": "Converter Free Ram",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByNode(consolidateBy(sbis3mon.prod.linux.memory.$converter_server.*.mem.ram.free.min, 'minimum'), -6), '.*(bl\\d+)', '\\1'), true)"
    }
   ]
  },
  {
   "title": "Webshot Free Ram",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByNode(consolidateBy(sbis3mon.prod.linux.memory.$webshot_server.*.mem.ram.free.min, 'minimum'), -6), '.*(bl\\d+)', '\\1'), true)"
    }
   ]
  },
  {
   "title": "Webshot Free Ram",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.prod.linux.memory.$webshot_server.*.mem.ram.free.min, -6), '.*(bl\\d+)', '\\1')"
    }
   ]
  },
  {
   "title": "Converter PS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByNode(sbis3mon.prod.linux.ps.$converter_server.*.process.state.sleeping.max, -6), '.*bl(\\d\\d?)', '\\1'), true)"
    }
   ]
  },
  {
   "title": "Big PS",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByNode(sbis3mon.prod.linux.ps.$big_server.*.process.state.sleeping.max, -6), '.*bl(\\d\\d?)', '\\1'), true)"
    }
   ]
  },
  {
   "title": "Converter FileCashed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByNode(consolidateBy(sbis3mon.prod.linux.memory.$converter_server.*.mem.ram.active_5Ffile.max, 'maximum'), -6), '.*bl(\\d\\d?)', '\\1'), true)"
    }
   ]
  },
  {
   "title": "Big FileCashed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(consolidateBy(sbis3mon.prod.linux.memory.$big_server.*.mem.ram.active_5Ffile.max, 'maximum'), -6), '.*bl(\\d)', '\\1')"
    }
   ]
  },
  {
   "title": "Webshot FileCashed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(consolidateBy(sbis3mon.prod.linux.memory.$webshot_server.*.mem.ram.active_5Ffile.max, 'maximum'), -6), '.*bl(\\d+)', '\\1')"
    }
   ]
  },
  {
   "title": "WebShot PS",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByNode(sbis3mon.prod.linux.ps.$webshot_server.*.process.state.sleeping.max, -6), '.*bl(\\d\\d?)', '\\1'), true)"
    }
   ]
  }
 ]
}