{
 "title": "IDM LDAP",
 "description": "Комплексный экран показателей LDAP из плагина ds389. Многие атрибуты отображаются для простой проверки работоспособности. Ответственный: Гломаздов А.Ю. (АЦОД)",
 "tags": [
  "telegraf",
  "service"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "tag_values(instance)" },
   {
    "name": "host",
    "query": "tag_values(host,instance=$instance)"
   }
  ]
 },
 "panels": [
  { "title": "Доступность сервисов", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Доступность сервисов",
   "type": "table",
   "description": "Активность сервисов.\n0 - Активен.\nИное значение - Не Активен.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "seriesByTag('host=~${host:regex}', 'name=systemd_units.active_code')"
    }
   ]
  },
  { "title": "DS389", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Table Size",
   "type": "stat",
   "description": "Размер dTableSize\n-- Этот атрибут показывает размер Directory Server connection table. Каждое соединение связано со слотом в этой таблице и обычно соответствует файловому дескриптору, используемому этим соединением.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ds389",
     "query": "aliasByMetric(seriesByTag('instance=$instance', 'name=ds389.dtablesize'))",
     "select": [
      [
       { "params": [ "dtablesize" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "target": "aliasSub(aliasByTags(seriesByTag('instance=$instance', 'name=ds389.dtablesize', 'host=~${host:regex}'), 'host', 'name'), '.pre-dev.nix.tensor.ru.ds389', '')"
    }
   ]
  },
  {
   "title": "Ops flow",
   "type": "graph",
   "description": "Кол-во операций, которые сервер инициировал и выполнил с интервалом в 5 м. \nЗначения должны быть равны.",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ds389",
     "target": "aliasByTags(movingAverage(perSecond(seriesByTag('instance=$instance', 'name=~ds389.ops*', 'host=~${host:regex}')), '5min'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Current connections",
   "type": "graph",
   "description": "Определяет количество подключений, находящихся в настоящее время в обслуживании, по каталогу.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ds389",
     "query": "aliasByMetric(seriesByTag('instance=$instance', 'name=ds389.currentconnections'))",
     "select": [
      [
       { "params": [ "currentconnections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "currentconnections" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "target": "aliasSub(aliasByTags(seriesByTag('name=ds389.connections', 'instance=$instance', 'host=~${host:regex}'), 'host', 'name'), '.pre-dev.nix.tensor.ru.ds389', '')"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "Потоки\n-- Текущее количество активных потоков, используемых для обработки запросов. Дополнительные потоки могут создаваться внутренними задачами сервера, такими как репликация или объединение в цепочки.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ds389",
     "query": "aliasByMetric(seriesByTag('instance=$instance', 'name=~ds389.connectionsmaxthreadscount'))",
     "select": [
      [
       { "params": [ "currentconnectionsatmaxthreads" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "curConMaxTh" ], "type": "alias" }
      ],
      [
       { "params": [ "threads" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "maxthreadsperconnhits" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "maxThPerConnHits" ], "type": "alias" }
      ],
      [
       { "params": [ "connectionsinmaxthreads" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "connInMaxTh" ], "type": "alias" }
      ],
      [
       { "params": [ "connectionsmaxthreadscount" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "connMaxThCount" ], "type": "alias" }
      ]
     ],
     "target": "aliasByTags(seriesByTag('instance=$instance', 'name=ds389.connectionsmaxthreadscount', 'host=~${host:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Ошибки.\n\n- Ошибки: Здесь отображается количество ошибок.\n\n- Ошибки безопасности: здесь показано количество ошибок, связанных с безопасностью, таких как неверные пароли, неизвестные или недопустимые методы проверки подлинности или требуется более строгая проверка подлинности.\n\n- Ошибки BindSecurityErrors: Это показывает количество раз, когда в запросе привязки был указан неверный пароль. \n\nВсе, что получено из интервала 5 м.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ds389",
     "query": "aliasByMetric(perSecond(seriesByTag('instance=$instance', 'name=ds389.errors')))",
     "select": [
      [
       { "params": [ "errors" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "Errors" ], "type": "alias" }
      ],
      [
       { "params": [ "bindsecurityerrors" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "BindSecurityErrors" ], "type": "alias" }
      ],
      [
       { "params": [ "securityerrors" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "SecurityErrors" ], "type": "alias" }
      ]
     ],
     "target": "aliasByTags(movingAverage(perSecond(seriesByTag('instance=$instance', 'name=ds389.errors', 'host=~${host:regex}')), '5min'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Operation Types",
   "type": "graph",
   "description": "Кол-во операций по типам.\n",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "exclude(aliasSub(aliasByTags(perSecond(seriesByTag('instance=$instance', 'name=~ds389.*ops*', 'host=~${host:regex}')), 'host', 'name'), '.pre-dev.nix.tensor.ru.ds389', ''), 'initiated|completed')"
    }
   ]
  },
  {
   "title": "Megabytes sent",
   "type": "graph",
   "description": "Количество байтов, отправленных в 5 м.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ds389",
     "query": "aliasByMetric(perSecond(seriesByTag('instance=$instance', 'name=ds389.bytessent')))",
     "select": [
      [
       { "params": [ "bytessent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "MB" ], "type": "alias" }
      ]
     ],
     "target": "aliasSub(aliasByTags(movingAverage(perSecond(seriesByTag('instance=$instance', 'name=ds389.bytessent', 'host=~${host:regex}')), '5min'), 'host', 'name'), '.pre-dev.nix.tensor.ru.ds389', '')"
    }
   ]
  },
  {
   "title": "Binds",
   "type": "graph",
   "description": "Все, что касается операций ПРИВЯЗКИ.\n\n- AnonymousBinds: Здесь отображается количество анонимных запросов на привязку. \n\n- UnAuthBinds: Здесь отображается количество не прошедших проверку подлинности (анонимных) привязок. \n\n- SimpleAuthBinds: Здесь показано количество простых запросов привязки LDAP (DN и пароль). \n\n- StrongAuthBinds: Показывает количество запросов привязки SASL LDAP для всех механизмов SASL.\n\n- BindSecurityErrors: Показывает количество раз, когда в запросе привязки был указан неверный пароль. \n\nВсе, что происходит с интервалом 5 м.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ds389",
     "query": "aliasByMetric(perSecond(seriesByTag('instance=$instance', 'name=~ds389.*binds')))",
     "select": [
      [
       { "params": [ "anonymousbinds" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "AnonymousBinds" ], "type": "alias" }
      ],
      [
       { "params": [ "simpleauthbinds" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "SimpleAuthBinds" ], "type": "alias" }
      ],
      [
       { "params": [ "strongauthbinds" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "StrongAuthBinds " ], "type": "alias" }
      ],
      [
       { "params": [ "unauthbinds" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "UnAuthBinds" ], "type": "alias" }
      ],
      [
       { "params": [ "bindsecurityerrors" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "BindSecurityErrors" ], "type": "alias" }
      ]
     ],
     "target": "aliasByTags(movingAverage(perSecond(seriesByTag('name=~ds389.*binds', 'host=~${host:regex}')), '5min'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Entries returned to clients",
   "type": "graph",
   "description": "Показывает количество записей, возвращенных в качестве результатов поиска, в 5 млн.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ds389",
     "query": "aliasByMetric(perSecond(seriesByTag('instance=$instance', 'name=ds389.entriesreturned')))",
     "select": [
      [
       { "params": [ "entriesreturned" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "EntriesReturned" ], "type": "alias" }
      ]
     ],
     "target": "aliasSub(aliasByTags(movingAverage(perSecond(seriesByTag('name=ds389.entriesreturned', 'host=~${host:regex}')), '5min'), 'host', 'name'), '.pre-dev.nix.tensor.ru.ds389', '')"
    }
   ]
  },
  {
   "title": "Read waiters",
   "type": "graph",
   "description": "readWaiters\n-- Этот атрибут показывает количество подключений, в которых некоторые запросы находятся на рассмотрении и в настоящее время не обслуживаются потоком на сервере каталогов.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ds389",
     "query": "aliasByMetric(seriesByTag('instance=$instance', 'name=ds389.readwaiters'))",
     "select": [
      [
       { "params": [ "readwaiters" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "target": "aliasSub(aliasByTags(seriesByTag('name=ds389.readwaiters', 'host=~${host:regex}'), 'host', 'name'), '.pre-dev.nix.tensor.ru.ds389', '')"
    }
   ]
  },
  { "title": "LDAP_ORG", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Host Groups",
   "type": "stat",
   "description": "Кол-во групп hosts",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aggregate(seriesByTag('name=ldap_org.hostgroups', 'host=~${host:regex}'), 'sum')"
    }
   ]
  },
  {
   "title": "Groups",
   "type": "stat",
   "description": "Кол-во групп",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aggregate(seriesByTag('name=ldap_org.groups', 'host=~${host:regex}'), 'sum')"
    }
   ]
  },
  {
   "title": "All ldap_org",
   "type": "graph",
   "description": "Кол-во различных итемов в базе",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~ldap_org.*', 'host=~${host:regex}'), 'host', 'name'), 'ldap_org.', '')"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "stat",
   "description": "Кол-во пользователей",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aggregate(seriesByTag('name=ldap_org.users', 'host=~${host:regex}'), 'sum')"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "description": "Кол-во сервисов",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aggregate(seriesByTag('name=ldap_org.services', 'host=~${host:regex}'), 'sum')"
    }
   ]
  }
 ]
}