{
 "title": "iis (site)",
 "description": "Ответственный: -",
 "tags": [
  "service",
  "iis",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   { "name": "server", "label": "Имя сервера", "query": "sbis3mon.$contur.iis.pool.*" },
   {
    "name": "site",
    "label": "Сайт",
    "query": "sbis3mon.$contur.iis.site.$server.iis.*.iis.site.*"
   },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  {
   "title": "$server $site (connections, isapi)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "server"
  },
  {
   "title": "$server: site connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.iis.site.$server.iis.*.iis.site.$site.connections.*.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: site isapi",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.iis.site.$server.iis.*.iis.site.$site.isapi.*.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server $site (requests, traffic)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "$server: site requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.iis.site.$server.iis.*.iis.site.$site.requests.http.*.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: site traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.iis.site.$server.iis.*.iis.site.$site.traffic.*.$aggr, -2)"
    }
   ]
  }
 ]
}