{
 "title": "inside.tensor.ru - front",
 "description": "Ответственный: -",
 "tags": [
  "service",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.nginx.stubstatus.*"
   },
   { "name": "aggr", "query": "max, avg, min" }
  ]
 },
 "panels": [
  {
   "title": "requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.nginx.stubstatus.$server.nginx.*.nginx.*.requests.raw, 4, -3)"
    }
   ]
  },
  {
   "title": "stat listen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.netstatCounter.$server.*.net.stat.listen.drops.raw, 4,-2)"
    }
   ]
  },
  {
   "title": "$server: requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "repeat": "server",
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.nginx.stubstatus.$server.nginx.*.nginx.request.raw, 4, -3)"
    }
   ]
  },
  {
   "title": "$server: connection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "repeat": "server",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.netstat.$server.*.net.total.connection.*.$aggr, -2), '_5F', ' ')"
    }
   ]
  },
  {
   "title": "$server: stat listen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "repeat": "server",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.netstatCounter.$server.*.net.stat.listen.*.raw, 4,-2)"
    }
   ]
  }
 ]
}