{
 "title": "keepalived",
 "description": "Ответственный: -",
 "tags": [
  "service",
  "sbis3mon-kafka",
  "keepalived",
  "mv.konuhov"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.keepalived.enabled.*"
   }
  ]
 },
 "panels": [
  { "title": "server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ]
    }
   ]
  },
  {
   "title": "$server: enabled",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(aliasByNode(sbis3mon.$contur.keepalived.enabled.$server.keepalived.*.keepalived.is_5Fenabled.raw, -2), 'is enabled')"
    }
   ]
  },
  {
   "title": "$server: net",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sbis3mon.$contur.keepalived.clusterIp.$server.keepalived.*.net.has_5Fcluster_5Fip.raw, 'has cluster ip')"
    }
   ]
  },
  { "title": "server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$server: node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ]
    }
   ]
  },
  {
   "title": "$server: enabled",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(aliasByNode(sbis3mon.$contur.keepalived.enabled.$server.keepalived.*.keepalived.is_5Fenabled.raw, -2), 'is enabled')"
    }
   ]
  },
  {
   "title": "$server: net",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sbis3mon.$contur.keepalived.clusterIp.$server.keepalived.*.net.has_5Fcluster_5Fip.raw, 'has cluster ip')"
    }
   ]
  }
 ]
}