{
 "title": "Kibana|opensearch-dashboards",
 "description": "Ответственный: Гломаздов А.Ю. (АЦОД)",
 "tags": [
  "kibana",
  "opensearch-dashboards",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "tag_values(clustername,service=kibana)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status code",
   "type": "stat",
   "description": "Статус сервиса",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=${cluster:regex}', 'service=kibana', 'name=~kibana.status_code'), 'host')"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=${cluster:regex}', 'service=kibana', 'name=kibana.uptime_ms'), 'host')"
    }
   ]
  },
  {
   "title": "Response time avg",
   "type": "timeseries",
   "description": "Response time avg ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=${cluster:regex}', 'service=kibana', 'name=kibana.response_time_avg_ms'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Response time max",
   "type": "timeseries",
   "description": "Response time max",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=${cluster:regex}', 'service=kibana', 'name=~kibana.response_time_max_ms'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Requests per sec",
   "type": "timeseries",
   "description": "Requests per sec",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 13 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=${cluster:regex}', 'service=kibana', 'name=~kibana.requests_per_sec'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Concurrent connections",
   "type": "timeseries",
   "description": "Concurrent connections",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 21 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=${cluster:regex}', 'service=kibana', 'name=~kibana.concurrent_connections'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "description": "Heap",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 29 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=${cluster:regex}', 'service=kibana', 'name=~kibana.heap_*'), 'host', 'name')"
    }
   ]
  }
 ]
}