{
 "title": "Minio cluster",
 "description": "Экран с информацией о состоянии кластера minio. Ответственный: Пантелеев А.С. (АЦОД)",
 "tags": [
  "service",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "cluster",
    "query": "tag_values(cluster,contur=$contur,servertype=minio)"
   }
  ]
 },
 "panels": [
  { "title": "Общая информация", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes total",
   "type": "stat",
   "description": "Количество хостов в кластере",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "consolidateBy(sumSeries(timeShift(seriesByTag('name=~(prometheus.minio_cluster_nodes_offline_total|prometheus.minio_cluster_nodes_online_total)', 'contur=~${contur:regex}', 'servertype=minio', 'cluster=$cluster'), '60s', true)), 'max')"
    }
   ]
  },
  {
   "title": "Disks total",
   "type": "stat",
   "description": "Количество дисков в кластере",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "consolidateBy(sumSeries(timeShift(seriesByTag('servertype=minio', 'contur=${contur:regex}', 'name=~(prometheus.minio_cluster_disk_online_total|prometheus.minio_cluster_disk_offline_total)', 'cluster=$cluster'), '60s', true)), 'maximum')"
    }
   ]
  },
  {
   "title": "Cluster healthcheck",
   "type": "bargauge",
   "description": "Проверка работы хостов кластера",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(timeShift(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'cluster=$cluster', 'interval=20s', 'name=http_response.http_response_code'), '30s', true), 'server'), ':9000-minio-health-live', ''), 'http:--', '')"
    }
   ]
  },
  {
   "title": "HTTP codes counter",
   "type": "gauge",
   "description": "Код, отдаваемый сервером на запрос метрик.\nСкачки значений для 200 кода — норма",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(exclude(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.promhttp_metric_handler_requests_total', 'cluster=$cluster'), 'metrics-node'), 'sum', 'code'), 'code'), true)"
    }
   ]
  },
  {
   "title": "Nodes online",
   "type": "stat",
   "description": "Количество доступных хостов",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(exclude(seriesByTag('servertype=minio', 'name=prometheus.minio_cluster_nodes_online_total', 'contur=~${contur:regex}', 'cluster=$cluster'), '-metrics-node'))"
    }
   ]
  },
  {
   "title": "Nodes offline",
   "type": "stat",
   "description": "Количество недоступных хостов",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(exclude(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_cluster_nodes_offline_total', 'cluster=$cluster'), 'metrics-node'))"
    }
   ]
  },
  {
   "title": "Disks online",
   "type": "stat",
   "description": "Количество дисков в работе",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_cluster_disk_online_total', 'cluster=$cluster'))"
    }
   ]
  },
  {
   "title": "Disks offline",
   "type": "stat",
   "description": "Количество дисков не в работе",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_cluster_disk_offline_total', 'cluster=$cluster'))"
    }
   ]
  },
  {
   "title": "Cluster capacity usable",
   "type": "stat",
   "description": "Доступное место на кластере",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_cluster_capacity_usable_total_bytes', 'cluster=$cluster'))"
    }
   ]
  },
  {
   "title": "Cluster capacity usable free",
   "type": "stat",
   "description": "Свободное доступное место на кластере",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_cluster_capacity_usable_free_bytes', 'cluster=$cluster'))"
    }
   ]
  },
  {
   "title": "Internode traffic ",
   "type": "graph",
   "description": "Трафик между хостами в кластере",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(derivative(sumSeries(seriesByTag('servertype=minio', 'contur=${contur:regex}', 'name=prometheus.minio_inter_node_traffic_sent_bytes', 'cluster=$cluster'))), 'Internode traffic sent')"
    },
    {
     "target": "alias(derivative(sumSeries(seriesByTag('servertype=minio', 'contur=${contur:regex}', 'name=prometheus.minio_inter_node_traffic_received_bytes', 'cluster=$cluster'))), 'Internode traffic received')"
    }
   ]
  },
  {
   "title": "Cluster nodes uptime",
   "type": "stat",
   "description": "Время работы каждой ноды кластера ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByTags(groupByTags(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_node_process_uptime_seconds', 'cluster=$cluster'), 'sum', 'server'), 'server'), ':9000', ''), true, false)"
    }
   ]
  },
  {
   "title": "S3 total requests + error requests",
   "type": "graph",
   "description": "Прирост всех S3 запросов и запросов, закончившихся с ошибкой ",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(derivative(sumSeries(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'cluster=$cluster', 'name=prometheus.minio_s3_requests_total'))), 'S3 requests')"
    },
    {
     "target": "alias(derivative(sumSeries(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'cluster=$cluster', 'name=prometheus.minio_s3_requests_errors_total'))), 'S3 error requests')"
    }
   ]
  },
  {
   "title": "Current version",
   "type": "stat",
   "description": "Текущая версия minio",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "highestMax(aliasByTags(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_software_version_info', 'cluster=$cluster'), 'version'))"
    }
   ]
  },
  {
   "title": "Total S3 traffic sent/received",
   "type": "graph",
   "description": "Прирост по полученному и отправленному S3 трафику",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(derivative(sumSeries(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_s3_traffic_received_bytes', 'cluster=$cluster'))), 'S3 traffic received')"
    },
    {
     "target": "alias(derivative(sumSeries(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_s3_traffic_sent_bytes', 'cluster=$cluster'))), 'S3 traffic sent')"
    }
   ]
  },
  { "title": "Syscalls and I/O ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Disk usage per disk",
   "type": "graph",
   "description": "Занятое дисковое пространство",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(sortByName(aliasByTags(groupByTags(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'disk=~*', 'name=prometheus.minio_node_disk_used_bytes', 'cluster=$cluster'), 'sum', 'server', 'disk'), 'server', 'disk'), true), '.-data', '/data'), ':9000', '')"
    }
   ]
  },
  {
   "title": "Disk free per disk",
   "type": "graph",
   "description": "Свободное дисковое пространство",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(sortByName(aliasByTags(groupByTags(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'disk=~*', 'name=prometheus.minio_node_disk_free_bytes', 'cluster=$cluster'), 'sum', 'server', 'disk'), 'server', 'disk'), true), '.-data', '/data'), ':9000', '')"
    }
   ]
  },
  {
   "title": "SysCalls read/write total",
   "type": "graph",
   "description": "Сумма системных вызовов на чтение и запись по всем хостам кластера",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(derivative(sumSeries(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_node_syscall_read_total', 'cluster=$cluster'))), 'SysCalls read total')"
    },
    {
     "target": "alias(derivative(sumSeries(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_node_syscall_write_total', 'cluster=$cluster'))), 'SysCalls write total')"
    }
   ]
  },
  {
   "title": "read/write operations with FS + cache",
   "type": "graph",
   "description": "Прирост обращений к файловой системе на чтение и на запись + кэш",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(derivative(sumSeries(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_node_io_rchar_bytes', 'cluster=$cluster'))), 'FS Read + cache')"
    },
    {
     "target": "alias(derivative(sumSeries(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_node_io_wchar_bytes', 'cluster=$cluster'))), 'FS Write + cache')"
    }
   ]
  },
  {
   "title": "Total Open FD's per node",
   "type": "stat",
   "description": "Общее количество открытых файловых дескрипторов для каждого хоста кластера. Верхний предел — 1048576, задан явно",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "consolidateBy(sortByName(aliasByTags(groupByTags(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_node_file_descriptor_open_total', 'cluster=$cluster'), 'sum', 'server'), 'server'), true), 'maximum')"
    }
   ]
  },
  {
   "title": "Total Goroutines per node",
   "type": "stat",
   "description": "Общее количество параллельных мини-потоков go для каждого хоста кластера",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(sortByName(aliasByTags(groupByTags(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_node_go_routine_total', 'cluster=$cluster'), 'sum', 'server'), 'server'), true, false), ':9000', '')"
    }
   ]
  },
  { "title": "Bucket objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Number of buckets",
   "type": "stat",
   "description": "Количество бакетов",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "countSeries(groupByTags(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'bucket=~*', 'name=prometheus.minio_bucket_usage_object_total', 'cluster=$cluster'), 'sum', 'bucket'))"
    }
   ]
  },
  {
   "title": "Bucket usage total",
   "type": "stat",
   "description": "Общий вес всех бакетов",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sum(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_bucket_usage_total_bytes', 'cluster=$cluster'))"
    }
   ]
  },
  {
   "title": "Number of objects per bucket",
   "type": "graph",
   "description": "Количество объектов по бакетам",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'bucket=~*', 'name=prometheus.minio_bucket_usage_object_total', 'cluster=$cluster'), 'sum', 'bucket'), 'bucket'), true, false)"
    }
   ]
  },
  {
   "title": "Buckets data usage",
   "type": "graph",
   "description": "Вес каждого бакета по отдельности",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('servertype=minio', 'contur=${contur:regex}', 'name=prometheus.minio_bucket_usage_total_bytes', 'bucket=~*', 'cluster=$cluster'), 'sum', 'bucket'), 'bucket'), true, false)"
    }
   ]
  },
  {
   "title": "Object size destribution",
   "type": "bargauge",
   "description": "Распределение файлов по объему файлов",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByMaxima(groupByTags(seriesByTag('servertype=minio', 'contur=~${contur:regex}', 'name=prometheus.minio_bucket_objects_size_distribution', 'bucket=~*', 'range=~*', 'cluster=$cluster'), 'sum', 'range'))"
    }
   ]
  }
 ]
}