{
 "title": "MySQL: Overview",
 "description": "Экран MySQL. Ответственный: Никитин М.С. (Эксплуатация)",
 "tags": [
  "service",
  "telegraf"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "MyInstance",
    "query": "tag_values(host,name=mysql.connections)"
   },
   {
    "name": "MyStatistics",
    "label": "Custom Statistic",
    "query": "tag_values(name,host=$MyInstance)"
   },
   {
    "name": "MyVar",
    "query": "tag_values(server,host=$MyInstance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Connection Info",
   "type": "text",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">$MyInstance port:<b>$MyVar</b></div>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  c1 AS \"time\",\n  v1\nFROM mylog\nWHERE\n  $__timeFilter(c1)\nORDER BY c1"
    }
   ]
  },
  {
   "title": "Connections/sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timest) as time_sec,\n  variable_value/600 as value\nFROM my2.status\nWHERE $__timeFilter(timest)\n  AND variable_name='CONNECTIONS-d'\n  AND variable_value>=0\nORDER BY timest ASC\n",
     "target": "perSecond(seriesByTag('host=$MyInstance', 'servertype=email', 'name=mysql.connections'))"
    }
   ]
  },
  {
   "title": "Threads & Errors",
   "type": "graph",
   "description": "Количество потоков mysql и ошибки по ним",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(timest, '10m') AS time,\n       variable_name as metric,\n       avg(variable_value+0) as value\n  FROM my2.status\n WHERE $__timeFilter(timest)\n   AND variable_name in ('THREADS_CONNECTED', 'THREADS_RUNNING')\n GROUP BY 1,2\n ORDER BY 1 ASC",
     "target": "aliasByTags(seriesByTag('host=$MyInstance', 'name=~mysql.threads'), 'name')"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(timest, '10m') as time,\n  substr(variable_name,1,length(variable_name)-2) as metric,\n  avg(variable_value+0) as value\nFROM my2.status\nWHERE $__timeFilter(timest)\n  and variable_name in ('SLOW_QUERIES-d', 'ABORTED_CONNECTS-d','ABORTED_CLIENTS-d')\n  and variable_value>=0\nGROUP BY 1,2\nORDER BY 1 ASC\n",
     "target": "aliasSub(aliasByTags(exclude(exclude(perSecond(seriesByTag('host=$MyInstance', 'name=~mysql.aborted_(clients|connects)')), 'variables'), 'error_log'), 'name'), 'mysql.', '')"
    },
    {
     "target": "exclude(exclude(aliasByTags(perSecond(seriesByTag('host=$MyInstance', 'name=~mysql.slow_queries')), 'name'), 'variables'), 'error_log')"
    }
   ]
  },
  {
   "title": "Space usage",
   "type": "graph",
   "description": "Использование места на диске",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(timest,'24h') as time,\n  variable_name as metric,\n  avg(variable_value+0) as value\nFROM my2.status\nWHERE $__timeFilter(timest)\n  and variable_name in ('SIZEDB.TOTAL')\nGROUP BY 1,2\nORDER BY 1 ASC\n",
     "target": "aliasSub(aliasByTags(seriesByTag('host=$MyInstance', 'name=~system.disk.used_percent'), 'path'), '-', '/')"
    }
   ]
  },
  {
   "title": "InnoDB Cache Hit",
   "type": "stat",
   "description": "Попадание в кэш InnoDB",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(s1.timest,'30m') as time_sec,\n  avg(1-s1.variable_value/s2.variable_value)*100 as value\nFROM my2.status s1,  my2.status s2\nWHERE $__timeFilter(s1.timest)\n  AND s1.timest=s2.timest\n  AND s1.variable_name='INNODB_BUFFER_POOL_READS-d'\n  AND s2.variable_name='INNODB_BUFFER_POOL_READ_REQUESTS-d'\n  AND s2.variable_value>0\nGROUP BY 1\nORDER BY 1 ASC\n",
     "target": "aliasByTags(perSecond(seriesByTag('host=csr-nikitinms-email1.unix.tensor.ru', 'server=127.0.0.1:3306', 'name=mysql.innodb_buffer_pool_read_requests')), 'host')"
    }
   ]
  },
  {
   "title": "Aborted clients",
   "type": "stat",
   "description": "Количество клиентских соединений, откинутых СУБД",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(s1.timest,'30m') as time_sec,\n  avg(1-s1.variable_value/s2.variable_value)*100 as value\nFROM my2.status s1,  my2.status s2\nWHERE $__timeFilter(s1.timest)\n  AND s1.timest=s2.timest\n  AND s1.variable_name='KEY_READS-d'\n  AND s2.variable_name='KEY_READ_REQUESTS-d'\n  AND s2.variable_value>0\nGROUP BY 1\nORDER BY 1 ASC\n",
     "target": "aliasByTags(perSecond(seriesByTag('host=csr-nikitinms-email1.unix.tensor.ru', 'server=127.0.0.1:3306', 'name=mysql.aborted_clients')), 'host')"
    }
   ]
  },
  {
   "title": "SQL Commands /sec",
   "type": "graph",
   "description": "Количество исполненных sql-запросов",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(timest, '10m') AS time,\n       substr(variable_name,5,length(variable_name)-6) as metric,\n       avg(variable_value/600) as value\n  FROM my2.status\n WHERE $__timeFilter(timest)\n   and variable_name in ('COM_SELECT-d', 'COM_INSERT-d', 'COM_UPDATE-d', 'COM_DELETE-d')\n   and variable_value >=0\n GROUP BY 1,2\n ORDER BY 1 ASC\n",
     "target": "aliasByTags(perSecond(seriesByTag('host=$MyInstance', 'servertype=email', 'name=~mysql.com_(insert|select)$')), 'name')"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "description": "Использование сети",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "binBps", "label": "recieved | sent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(timest, '10m') AS time,\n       variable_name as metric,\n       avg(variable_value+0)/600 as value\n  FROM my2.status\n WHERE $__timeFilter(timest)\n   and variable_name in ('Bytes_received-d', 'Bytes_sent-d')\n GROUP BY 1,2\n ORDER BY 1 ASC\n",
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('host=$MyInstance', 'name=~mysql.bytes_(sent|received)')), 'name'), 'mysql.', '')"
    }
   ]
  },
  {
   "title": "Query Cache Hit",
   "type": "stat",
   "description": "Запросы с результатами из кэша",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(s1.timest,'30m') as time_sec,\n  avg((s1.variable_value/(s1.variable_value+s2.variable_value))*100) as value\nFROM my2.status s1,  my2.status s2\nWHERE $__timeFilter(s1.timest)\n  AND s1.timest=s2.timest\n  AND s1.variable_name='QCACHE_HITS-d'\n  AND s2.variable_name='COM_SELECT-d'\n  AND s2.variable_value>0\nGROUP BY 1\nORDER BY 1 ASC\n\n\n\n",
     "target": "aliasByTags(perSecond(seriesByTag('host=$MyInstance', 'name=mysql.aborted_connects')), 'name')"
    }
   ]
  },
  {
   "title": "Custom Statistic",
   "type": "graph",
   "description": "Количество запросов нарастающим итогом",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timest) as time,\n  variable_value+0 as value, variable_value/600 as value_sec,\n  variable_name as metric\nFROM my2.status\nWHERE $__timeFilter(timest)\n  and variable_name in ($MyStatistics)\nORDER BY timest ASC\n",
     "target": "aliasByTags(seriesByTag('host=$MyInstance', 'name=mysql.com_insert'), 'name')"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timest) as time,\n  variable_value+0 as value, variable_value/600 as value_sec,\n  variable_name as metric\nFROM my2.status\nWHERE $__timeFilter(timest)\n  and variable_name in ($MyStatistics)\nORDER BY timest ASC\n",
     "target": "aliasByTags(seriesByTag('host=$MyInstance', 'name=mysql.com_select'), 'name')"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timest) as time,\n  variable_value+0 as value, variable_value/600 as value_sec,\n  variable_name as metric\nFROM my2.status\nWHERE $__timeFilter(timest)\n  and variable_name in ($MyStatistics)\nORDER BY timest ASC\n",
     "target": "aliasByTags(seriesByTag('host=$MyInstance', 'name=mysql.com_update'), 'name')"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timest) as time,\n  variable_value+0 as value, variable_value/600 as value_sec,\n  variable_name as metric\nFROM my2.status\nWHERE $__timeFilter(timest)\n  and variable_name in ($MyStatistics)\nORDER BY timest ASC\n",
     "target": "aliasByTags(seriesByTag('host=$MyInstance', 'name=mysql.com_delete'), 'name')"
    }
   ]
  },
  {
   "title": "Heatmap (Queries /sec)",
   "type": "heatmap",
   "description": "Тепловая карта по успешности запросов sql",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(timest, '24h') as time,\n  concat(' ',max(date_format(timest,'%H'))) as metric,\n  sum(variable_value)/3600 as value\nFROM my2.status\nWHERE variable_name='QUERIES-d'\n  and variable_value>0\n  and $__timeFilter(timest)\nGROUP BY $__timeGroup(timest, '1h'),$__timeGroup(timest, '24h')\nORDER BY 2, 1 \n",
     "target": "exclude(aliasByTags(perSecond(seriesByTag('host=$MyInstance', 'name=~mysql.*(insert|select)')), 'name'), 'variables')"
    }
   ]
  }
 ]
}