{
 "title": "named (queries)",
 "description": "Ответственный: -",
 "tags": [
  "named",
  "service",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   { "name": "server", "label": "Имя сервера", "query": "sbis3mon.$contur.named.stats.*" },
   {
    "name": "port",
    "query": "sbis3mon.$contur.named.stats.$server.sbis3mon.named.*"
   }
  ]
 },
 "panels": [
  { "title": "$server (opcodes, cache)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: opcodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.sbis3mon.named.$port.*.named.opcodes.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.sbis3mon.named.$port.*.named.cahce.{dele,*hits,*miss}*.raw, -2)"
    }
   ]
  },
  { "title": "$server (qtypes, rcodes)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "server" },
  {
   "title": "$server: qtypes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.sbis3mon.named.$port.*.named.qtypes.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: rcodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.sbis3mon.named.$port.*.named.rcodes.*.raw, -2)"
    }
   ]
  }
 ]
}