{
 "title": "named (nsstats)",
 "description": "Ответственный: -",
 "tags": [
  "named",
  "sbis3mon-kafka",
  "service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "sbis3mon.*" },
   { "name": "server", "label": "Имя сервера", "query": "sbis3mon.$contur.named.stats.*" }
  ]
 },
 "panels": [
  { "title": "$server (request, response)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.named.*.named.nsstats.{req*,xfrreqdone}.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: response",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.named.*.named.nsstats.resp*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server (query, update, rejected)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "server"
  },
  {
   "title": "$server: query",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.named.*.named.nsstats.qry*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: update",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.named.*.named.nsstats.upd*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: rejected",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.named.*.named.nsstats.*rej*.raw, -2)"
    }
   ]
  }
 ]
}