{
 "title": "new-edu: основной дашборд",
 "description": "Комплексный экран по всем прикладным сервисам сайта Учебного Центра new-edu.tensor.ru. Ответственный: Казанкин Л.Е. (Эксплуатация)",
 "tags": [
  "telegraf",
  "service",
  "new-edu"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "tag_values(host, servertype=new-edu)"
   }
  ]
 },
 "panels": [
  {
   "title": "Время получения HTTP статуса new-edu.tensor.ru",
   "type": "timeseries",
   "description": "Время получения HTTP статуса new-edu.tensor.ru с 3-х разных площадок. Делается запрос на https://new-edu.tensor.ru/!ping/",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=http_response.response_time', 'host=~(monitor-remote-3.local|us.malysh|379475)', 'server=https:--new-edu.tensor.ru-_ping-'), 'server', 'host'), 'https:--', ''), '-\\_ping-', '')"
    }
   ]
  },
  {
   "title": "История состояния сервисов (${Host: regex})",
   "type": "timeseries",
   "description": "https://dpc-docs.tensor.ru/pages/viewpage.action?pageId=57185268",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('host=$Host', 'name=systemd_units.active_code'), 'last', '_name'), '_name')"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "description": "Среднее значение загрузки системы. Чем ниже эта величина, тем менее нагружена система.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasSub(aliasByTags(seriesByTag('host=$Host', 'name=~system.system.(load1|load5|load15|n_cpus)'), 'name'), 'system.system.load1', 'LA1'), 'system.system.load5', 'LA5'), 'system.system.n_cpus', 'CPUs number')"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Процент загруженности ядра.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(seriesByTag('host=$Host', 'name=~system.cpu.(usage_user|usage_system|usage_softirq|usage_iowait)', 'cpu=cpu-total'), 2)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Метрика оперативной памяти.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "aliasByNode(exclude(seriesByTag('host=$Host', 'name=~system.(mem.total|mem.available|mem.used|swap.total|swap.used)'), 'percent'), 1, 2)"
    }
   ]
  },
  {
   "title": "Network data",
   "type": "timeseries",
   "description": "Количество входящего/исходящего трафика.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('host=$Host', 'name=~system.net.bytes_(recv|sent)')), 'name', 'interface'), 2, 3)"
    }
   ]
  },
  {
   "title": "Network packages",
   "type": "timeseries",
   "description": "Количество потери входящих/исходящих пакетов.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('host=$Host', 'name=~system.net.(drop_in|drop_out|err_in|err_out)')), 'name', 'interface'), 2, 3)"
    }
   ]
  },
  {
   "title": "Disk wait, ms",
   "type": "graph",
   "description": "Задержки дисковой подсистемы.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(divideSeriesLists(perSecond(seriesByTag('name=~system.diskio.(write|read)_time', 'host=$Host')), #A), '_name', 'name'), 'system.diskio.write_time', 'write_lag'), 'system.diskio.read_time', 'read_lag')",
     "targetFull": "aliasSub(aliasSub(aliasByTags(divideSeriesLists(perSecond(seriesByTag('name=~system.diskio.(write|read)_time', 'host=$Host')), perSecond(seriesByTag('name=~system.diskio.(reads|writes)', 'host=$Host'))), '_name', 'name'), 'system.diskio.write_time', 'write_lag'), 'system.diskio.read_time', 'read_lag')"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "aliasByTags(perSecond(seriesByTag('name=~system.diskio.(read|write)_bytes', 'host=$Host', '_name=~(sd\\w$|md?)')), '_name', 'name')"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Процент занятого объема дискового пространства от максимального.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=system.disk.used_percent', 'host=$Host'), 'path'), '-', '/')"
    }
   ]
  },
  {
   "title": "Статистика Fail2Ban по ${Host}",
   "type": "timeseries",
   "description": "Увеличение failed / banned за 5 секунд\n\nСмотрит currently failed, которая считает неудачные попытки входа за время в параметре findtime (/etc/fail2ban/jail.d/*.conf)\n\nСмотрит currently banned. Бан проходит по истечению времени в параметре bantime в /etc/fail2ban/jail.d/*.conf",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~new-edu.fail2ban.* ', 'host=$Host'), 'jail', 2)"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Запросы",
     "type": "timeseries",
     "description": "Количество запросов в секунду",
     "gridPos": { "h": 7, "w": 15, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "alias(derivative(seriesByTag('host=$Host', 'name=new-edu.nginx.requests')), 'Requests')"
      },
      {
       "target": "alias(derivative(seriesByTag('host=$Host', 'name=new-edu.nginx.active')), 'Active')"
      }
     ]
    },
    {
     "title": "Коды ответов HTTP",
     "type": "timeseries",
     "description": "Коды диспетчеров: https://online.sbis.ru/shared/disk/d5aa8e13-64f8-4c8a-bf66-570e652e190a",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(derivative(seriesByTag('host=$Host', 'name=~new-edu.http_code_.*')), 'name'), 'new-edu.http_code_', '')"
      }
     ]
    },
    {
     "title": "Принято / Обработано",
     "type": "timeseries",
     "description": "Количество принятых и обработанных запросов в секунду",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "alias(derivative(seriesByTag('host=$Host', 'name=new-edu.nginx.accepts')), 'Accepts')"
      },
      {
       "target": "alias(derivative(seriesByTag('host=$Host', 'name=new-edu.nginx.handled')), 'Handled')"
      }
     ]
    },
    {
     "title": "Чтение / Запись / Ожидание",
     "type": "timeseries",
     "description": "Чтение / Запись / Ожидание в секунду",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "alias(seriesByTag('host=$Host', 'name=new-edu.nginx.reading'), 'Reading')"
      },
      {
       "target": "alias(seriesByTag('host=$Host', 'name=new-edu.nginx.writing'), 'Writing')"
      },
      {
       "target": "alias(seriesByTag('host=$Host', 'name=new-edu.nginx.waiting'), 'Waiting')"
      }
     ]
    },
    {
     "title": "SSL сертификаты на серверах",
     "type": "table",
     "description": "Название, расположение и срок годности SSL сертификатов на сервере.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "target": "seriesByTag('name=new-edu.ssl.expiry')"
      }
     ]
    }
   ]
  }
 ]
}