{
 "title": "Nginx server",
 "description": "Ответственный: Конюхов М.В. (Эксплуатация)",
 "tags": [
  "service",
  "telegraf",
  "nginx"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Сервер",
    "query": "tag_values(host,name=nginx.requests)"
   }
  ]
 },
 "panels": [
  {
   "title": "Запросы",
   "type": "graph",
   "description": "Сколько запросов пришло от клиентов и ушло на бакенды",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=nginx.requests', 'host=$host')), 'name'))"
    },
    {
     "target": "aliasByMetric(aliasByTags(seriesByTag('name=nginx.active', 'host=$host'), 'name'))"
    }
   ]
  },
  {
   "title": "Принято/обработано",
   "type": "graph",
   "description": "Соотношение попадания в кеш и промахов.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=~nginx.(accepts|handled)', 'host=$host')), 'name'))"
    }
   ]
  },
  {
   "title": "Чтения/записи/ожидание",
   "type": "graph",
   "description": "Соотношение попадания в кеш и промахов.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(seriesByTag('name=~nginx.(reading|writing|waiting)', 'host=$host'), 'name'))"
    }
   ]
  },
  {
   "title": "Трафик",
   "type": "graph",
   "description": "Сетевой трафик в байтах",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(aliasByTags(perSecond(seriesByTag('host=$host', 'name=~system.net.bytes*')), 'name', 'interface'), 8), -1, -2)"
    }
   ]
  },
  {
   "title": "Диски Чтение\\Запись",
   "type": "graph",
   "description": "Размер прочитанных и записанных данных на диски, исключая системные разделы",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "perSecond(aliasByTags(exclude(seriesByTag('host=$host', 'name=~system.diskio.*_bytes'), 'sda'), '_name', 'name'))"
    }
   ]
  },
  {
   "title": "LA",
   "type": "graph",
   "description": "LA 1 5 15",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=system.system.n_cpus', 'contur=${contur:regex}', 'host=$host'), 'CPU')"
    },
    {
     "target": "alias(seriesByTag('name=system.system.load1', 'host=$host'), 'la1')"
    },
    {
     "target": "alias(seriesByTag('name=system.system.load5', 'host=$host'), 'la5')"
    },
    {
     "target": "alias(seriesByTag('name=system.system.load15', 'host=$host'), 'la15')"
    }
   ]
  },
  {
   "title": "Пакеты",
   "type": "graph",
   "description": "Входящие и исходящие пакеты",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('host=$host', 'name=~system.net.packets_recv')), 'name'))"
    },
    {
     "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('host=$host', 'name=~system.net.packets_sent')), 'name'))"
    }
   ]
  },
  {
   "title": "Диски Время Чтения/Записи",
   "type": "graph",
   "description": "Время прочитанных и записанных данных на диски, исключая системные разделы",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "perSecond(aliasByTags(exclude(seriesByTag('host=$host', 'name=~system.diskio.read_time'), 'sda'), '_name', 'name'))"
    },
    {
     "target": "perSecond(aliasByTags(exclude(seriesByTag('host=$host', 'name=~system.diskio.write_time'), 'sda'), '_name', 'name'))"
    }
   ]
  },
  {
   "title": "Сетевой стек",
   "type": "graph",
   "description": "Состояния сетевых сокетовв",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=~system.netstat.tcp_*'), 'name'))"
    }
   ]
  },
  {
   "title": "Память - использование",
   "type": "graph",
   "description": "Использование памяти",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.used'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.free'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('contur=~${contur:regex}', 'servertype=~${servertype:regex}', 'host=$host', 'name=system.mem.shared'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('contur=~${contur:regex}', 'servertype=~${servertype:regex}', 'host=$host', 'name=system.mem.buffered'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('contur=~${contur:regex}', 'servertype=~${servertype:regex}', 'host=$host', 'name=system.mem.cached'), 'name')), 'max')"
    }
   ]
  },
  {
   "title": "Память",
   "type": "graph",
   "description": "Использование памяти",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.available'), 'name')), 'max')"
    },
    {
     "target": "consolidateBy(aliasByMetric(aliasByTags(seriesByTag('host=$host', 'name=system.mem.total'), 'name')), 'max')"
    }
   ]
  }
 ]
}