{
 "title": "pgbouncer",
 "description": "Стандартный мониторинг pgbouncer. Ответственный: -",
 "tags": [
  "service",
  "sbis3mon-kafka",
  "PostgreSQL"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.pgbouncer.dbs.*"
   },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  { "title": "$server (requests, traffic)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.pgbouncer.dbs.$server.pgbouncer.*.pgbouncer.{requests,queryTime}.$aggr, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.pgbouncer.dbs.$server.pgbouncer.*.pgbouncer.traffic.rx.$aggr, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.pgbouncer.dbs.$server.pgbouncer.*.pgbouncer.traffic.tx.$aggr, -3, -2)"
    }
   ]
  },
  { "title": "$server (server)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "server" },
  {
   "title": "$server: server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.pgbouncer.pools.$server.pgbouncer.*.pgbouncer.server.*.$aggr, '-pct'), -2)"
    }
   ]
  },
  {
   "title": "$server: server, %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.pgbouncer.pools.$server.pgbouncer.*.pgbouncer.server.*.pct.$aggr, -3)"
    }
   ]
  },
  { "title": "$server (pool)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "server" },
  {
   "title": "$server: pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.pgbouncer.poolUsed.$server.pgbouncer.*.pgbouncer.pool.*.used.$aggr, -3)"
    }
   ]
  },
  {
   "title": "$server: pool, %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.pgbouncer.poolUsed.$server.pgbouncer.*.pgbouncer.pool.*.used.pct.$aggr, -4)"
    }
   ]
  },
  { "title": "$server (client, cpu)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "server" },
  {
   "title": "$server: client",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.pgbouncer.pools.$server.pgbouncer.*.pgbouncer.client.waiting.$aggr, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.pgbouncer.pools.$server.pgbouncer.*.pgbouncer.maxwait.$aggr, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(sbis3mon.$contur.pgbouncer.procCPU.$server.pgbouncer.*.pgbouncer.cpu.used.$aggr, '$aggr'), 'used-max')"
    }
   ]
  }
 ]
}