{
 "title": "Postgres (db, summarize)",
 "description": "Ответственный: -",
 "tags": [
  "service",
  "sbis3mon-kafka",
  "PostgreSQL"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   { "name": "server", "label": "Имя сервера", "query": "sbis3mon.$contur.postgres.*.*" },
   { "name": "domain", "label": "Домен", "query": "*.tensor.ru" },
   {
    "name": "db",
    "label": "База данных",
    "query": "sbis3mon.$contur.postgres.db-time.$server.pgsql.*.pgsql.db.etime.*"
   },
   { "name": "aggr", "query": "max, avg, min" }
  ]
 },
 "panels": [
  { "title": "$server (connection)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: connection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-connection-state.$server.pgsql.*.pgsql.db.connection.$db.{idle,transaction,waiting,all,running,maintenance}.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server (wait event types and locks)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "server"
  },
  {
   "title": "$server: lock",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-locks.$server.pgsql.*.pgsql.db.lock.$db.*.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-wait-events.$server.pgsql.*.pgsql.db.connection.$db.io.$aggr, -2)"
    }
   ]
  },
  { "title": "$server (xact lock)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "server" },
  {
   "title": "$server: xact",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(exclude(sbis3mon.$contur.postgres.db-xact-tuples.$server.pgsql.*.pgsql.db.xact.$db.commit.max, 'total'), 'commit-max')"
    },
    {
     "target": "alias(exclude(sbis3mon.$contur.postgres.db-xact-tuples.$server.pgsql.*.pgsql.db.xact.$db.rollback.max, 'total'), 'rollback-max')"
    },
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.postgres.db-xact-tuples.$server.pgsql.*.pgsql.db.xact.$db.{commit,rollback}.$aggr, 'total'), -2)"
    }
   ]
  },
  { "title": "$server (tuples)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "server" },
  {
   "title": "$server: tuples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-xact-tuples.$server.pgsql.*.pgsql.db.tuples.$db.{returned,fetched}.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-xact-tuples.$server.pgsql.*.pgsql.db.tuples.$db.read.ratio.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: tuples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-xact-tuples.$server.pgsql.*.pgsql.db.tuples.$db.{deleted,updated,inserted}.$aggr, -2)"
    }
   ]
  },
  { "title": "$server (scan, tuples scan)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "server" },
  {
   "title": "$server: scan",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.perdb-scan-tuples.$server.pgsql.*.pgsql.db.scan.$db.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: tuples scan",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.perdb-scan-tuples.$server.pgsql.*.pgsql.db.tuples.scan.$db.*.raw, -2)"
    }
   ]
  },
  { "title": "$server (tuples state, block)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }, "repeat": "server" },
  {
   "title": "$server: tuples state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.perdb-scan-tuples.$server.pgsql.*.pgsql.db.tuples.$db.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: block",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-block.$server.pgsql.*.pgsql.db.block.$db.*.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-block.$server.pgsql.*.pgsql.db.block.$db.read.ratio.$aggr, -3, -2)"
    }
   ]
  },
  { "title": "$server (real, temp)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }, "repeat": "server" },
  {
   "title": "$server: real",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.perdb-real-relation.$server.pgsql.*.pgsql.db.real.$db.*.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.perdb-real-schema.$server.pgsql.*.pgsql.db.real.$db.schema.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: temp",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sbis3mon.$contur.postgres.$server.$domain.$port.*.aggr-$aggr.pgsql.db.$db.temp.*)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.perdb-temp-relation.$server.pgsql.*.pgsql.db.temp.$db.*.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.perdb-temp-schema.$server.pgsql.*.pgsql.db.temp.$db.schema.$aggr, -2)"
    }
   ]
  },
  { "title": "$server (itime, etime)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 }, "repeat": "server" },
  {
   "title": "$server: itime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-time.$server.pgsql.*.pgsql.db.itime.$db.*.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: etime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(exclude(sbis3mon.$contur.postgres.db-time.$server.pgsql.*.pgsql.db.etime.$db.*.$aggr, 'nobackup'), -2), '_5F', '_')"
    }
   ]
  },
  { "title": "$server (size, frozenxid)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 }, "repeat": "server" },
  {
   "title": "$server: size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.$server.$domain.$port.*.aggr-$aggr.pgsql.db.$db.size, -1)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.perdb-size.$server.pgsql.*.pgsql.db.size.$db.raw, -3)"
    }
   ]
  },
  {
   "title": "$server: frozenxid",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.postgres.db-frozenxid.$server.pgsql.*.pgsql.db.frozenxid.$db.*.raw, -2), '_5F', ' ')"
    }
   ]
  },
  { "title": "$server: (query)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }, "repeat": "server" },
  {
   "title": "$server: query_etime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.$contur.postgres.db-time.$server.pgsql.interval-30sec.pgsql.db.etime.$db.query.$aggr, -4, -2)"
    }
   ]
  },
  {
   "title": "$server: query_itime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.$contur.postgres.db-time.$server.pgsql.interval-30sec.pgsql.db.itime.$db.query.$aggr, -4, -2)"
    }
   ]
  },
  {
   "title": "$server: (connections wainting/running)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "repeat": "server"
  },
  {
   "title": "$server: connections wainting/running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-connection-state.$server.pgsql.*.pgsql.db.connection.$db.{waiting,running}.$aggr, -2)"
    }
   ]
  },
  { "title": "$server: (maintenance_query)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 }, "repeat": "server" },
  {
   "title": "$server: maintenance_query etime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.postgres.db-time.$server.pgsql.interval-30sec.pgsql.db.etime.total.maintenance_5Fnoautovacuum.raw, -2), '_5F', '_')"
    }
   ]
  }
 ]
}