{
 "title": "Postgres (buffers)",
 "description": "Ответственный: -",
 "tags": [
  "service",
  "sbis3mon-kafka",
  "PostgreSQL"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.postgres.configuration.*"
   }
  ]
 },
 "panels": [
  { "title": "$server checkpoints time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: checkpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-bgwriter.$server.pgsql.*.pgsql.checkpoints.{tim,request}ed.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: checkpoints time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-bgwriter.$server.pgsql.*.pgsql.checkpoints.time.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server buffers (checkpoint, bgwriter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "server"
  },
  {
   "title": "$server: buffers checkpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-bgwriter.$server.pgsql.*.pgsql.buffers.checkpoint.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: buffers bgwriter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-bgwriter.$server.pgsql.*.pgsql.buffers.{maxwrittenc,c}lean.raw, -2)"
    }
   ]
  },
  {
   "title": "$server buffers (alloc, backend)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "server"
  },
  {
   "title": "$server: buffers alloc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-bgwriter.$server.pgsql.*.pgsql.buffers.alloc.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: buffers backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-bgwriter.$server.pgsql.*.pgsql.buffers.backen{d,dfsync}.raw, -2)"
    }
   ]
  },
  {
   "title": "$server archiver (wal, lasttime)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "server"
  },
  {
   "title": "$server: archiver wal",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-archiver.$server.pgsql.*.pgsql.archiver.wal.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: archiver lasttime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-archiver.$server.pgsql.*.pgsql.archiver.lasttime.*.raw, -2)"
    }
   ]
  }
 ]
}