{
 "title": "Postgres (server) архивация",
 "description": "Ответственный: -",
 "tags": [
  "service",
  "sbis3mon-kafka",
  "PostgreSQL"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.postgres.configuration.*"
   },
   { "name": "aggr", "label": "Агрегация", "query": "avg,max,min" }
  ]
 },
 "panels": [
  {
   "title": "Log error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sbis3mon.$contur.postgres.*.*.*.*.*.pgsql.lo"
    }
   ]
  },
  {
   "title": "Log summarize",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.$server.$domain.$port.*.aggr-$aggr.pgsql.log.log, -1)"
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.service-master-replication-xlog.$server.pgsql.*.pgsql.replication.lag.$aggr, 4)"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.service-ping.$server.pgsql.*.pgsql.ping.postgres, 4)"
    }
   ]
  },
  {
   "title": "Tmpfiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-tmp-files.osr-eng-db2.pgsql.*.pgsql.tmpfiles.size, 4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-tmp-files.$server.pgsql.*.pgsql.tmpfiles.count, 4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.perdb-temp-schema.$server.pgsql.*.pgsql.db.temp.$server, 4, -2)"
    }
   ]
  },
  {
   "title": "Xlog files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-xlog-files.$server.pgsql.*.pgsql.xlog.files.raw, 4, -2)"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.postgres.db-xlog-files.$server.pgsql.*.pgsql.xlog.files_5Farchived.raw, 4, -2), '_5F', '_')"
    }
   ]
  }
 ]
}