{
 "title": "Postgres (server)",
 "description": "Стандартный мониторинг postgres. Ответственный: -",
 "tags": [
  "service",
  "sbis3mon-kafka",
  "PostgreSQL"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.postgres.configuration.*"
   },
   { "name": "aggr", "label": "Агрегация", "query": "avg,max,min" }
  ]
 },
 "panels": [
  { "title": "$server log (error, summarize)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: log error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sbis3mon.$contur.postgres.*.*.*.*.*.pgsql.lo"
    }
   ]
  },
  {
   "title": "$server: log summarize",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.$server.$domain.$port.*.aggr-$aggr.pgsql.log.log, -1)"
    }
   ]
  },
  {
   "title": "$server replication (lag, diff)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "server"
  },
  {
   "title": "$server: replication lag (bytes, ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.service-master-replication-xlog.$server.pgsql.*.pgsql.replication.lag.$aggr, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-slave-replication-timelag.$server.pgsql.*.pgsql.replication.time.$aggr, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: replication diff",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sbis3mon.$contur.postgres.db-slave-replication-diff.$server.pgsql.*.pgsql.replication.diff.$aggr | aliasByNode(-3, -2)"
    }
   ]
  },
  { "title": "$server ping, xlog files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "server" },
  {
   "title": "$server: ping",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "sbis3mon.$contur.postgres.service-ping.$server.pgsql.*.pgsql.ping.postgres | aliasByNode(-2)"
    }
   ]
  },
  {
   "title": "$server: xlog files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sbis3mon.$contur.postgres.db-xlog-files.$server.pgsql.*.pgsql.xlog.files.raw | aliasByNode(-2)"
    },
    {
     "target": "sbis3mon.$contur.postgres.db-xlog-files.$server.pgsql.*.pgsql.xlog.files_5Farchived.raw | aliasByNode(-2) | aliasSub('_2|_5F|_28|_29', ' ')"
    }
   ]
  },
  { "title": "$server tmpfiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "server" },
  {
   "title": "$server: tmpfiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sbis3mon.$contur.postgres.db-tmp-files.$server.pgsql.*.pgsql.tmpfiles.size.raw | aliasByNode(-3, -2)"
    },
    {
     "target": "sbis3mon.$contur.postgres.db-tmp-files.$server.pgsql.*.pgsql.tmpfiles.count.raw | aliasByNode(-3, -2)"
    }
   ]
  },
  {
   "title": "$server rslave-replication-paused",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "server"
  },
  {
   "title": "$server: rslave-replication-paused",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.postgres.db-slave-replication-paused.$server.pgsql.*.pgsql.replication.paused.raw, -7)"
    }
   ]
  }
 ]
}