{
 "title": "Postgres:  последовательности",
 "description": "Ответственный: -",
 "tags": [
  "service",
  "PostgreSQL",
  "telegraf"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Последовательности использованные >80%",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=postresql.sequences.usage', 'host=~.+'), 'host', 'database', 'sequence')"
    }
   ]
  },
  {
   "title": "Последовательности использованные >80%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=postresql.sequences.usage', 'host=~.+'), 'host', 'database', 'sequence')"
    }
   ]
  },
  {
   "title": "Ошибки при сборе",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=postresql.sequences.errors'), 'name')"
    }
   ]
  },
  {
   "title": "Появление последовательностей с >80% и >90%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=postresql.sequences.usage', 'percent=~.+'), 'percent', 'type')"
    }
   ]
  },
  {
   "title": "Базы с проблемами последовательностей",
   "type": "timeseries",
   "description": "Показывает секвенции https://online.sbis.ru/opendoc.html?guid=c26e22d9-b252-4553-aa9e-9a06bd93f027\n\nПуляется напрямую платформами. Попытка отказаться от скрипта.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "scale(aliasByTags(seriesByTag('name=sequence_limits_is_depleting', 'contur=prod'), 'database', 'sequence'), 100, 0)"
    }
   ]
  }
 ]
}