{
 "title": "Proxy gateway",
 "description": "Шлюз proxy-доступа в интернет. Ответственный: Ожиганов Г.А. и Конюхов М.В. (Эксплуатация)",
 "tags": [
  "exploitation",
  "service",
  "scripts",
  "proxy",
  "mv.konuhov",
  "telegraf",
  "dante",
  "sockd",
  "keepalived",
  "Squid",
  "sbis3mon"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Proxy cluster health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "Cluster csr-dts-proxy-app.unix.tensor.ru status",
   "type": "graph",
   "description": "Опрос squid и socks прокси кластера csr-dts-proxy-app.unix.tensor.ru",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=proxy.check', 'server=~csr-dts-proxy-app.unix.tensor.ru', 'contur=prod', 'proxyport=~.*', 'protocol=~.*'),  'protocol', 'server', 'proxyport')"
    }
   ]
  },
  {
   "title": "Single instance csr-dts-proxy-app3(4).unix.tensor.ru status",
   "type": "graph",
   "description": "Опрос socks прокси csr-dts-proxy-app3.unix.tensor.ru и резерва csr-dts-proxy-app4.unix.tensor.ru",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=proxy.check', 'server=~csr-dts-proxy-app4.unix.tensor.ru', 'contur=prod', 'proxyport=~.*', 'protocol=~.*'), 'protocol', 'server', 'proxyport')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=proxy.check', 'server=~csr-dts-proxy-app3.unix.tensor.ru', 'contur=prod', 'proxyport=~.*', 'protocol=~.*'), 'protocol', 'server', 'proxyport')"
    }
   ]
  },
  {
   "title": "Dante (sockd) status",
   "type": "graph",
   "description": "Жив ли демон. Опрос через procstat telegraf",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=procstat.sockd.running', 'host=~.*dts-proxy-app.*'), 'host')"
    }
   ]
  },
  {
   "title": "Squid status",
   "type": "graph",
   "description": "Жив ли демон. Опрос через procstat telegraf",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=procstat.squid.running', 'host=~.*dts-proxy-app.*'), 'host')"
    }
   ]
  },
  {
   "title": "Keepalived status",
   "type": "graph",
   "description": "Жив ли демон. Опрос через procstat telegraf",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=procstat.keepalived.running', 'host=~.*dts-proxy-app.*'), 'host')"
    }
   ]
  },
  { "title": "Dante (sockd)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Dante active connections",
   "type": "graph",
   "description": " ss | grep ESTAB.*:9999 ....",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~exec.sockd.connections.active', 'contur=prod'), 'host')"
    }
   ]
  },
  {
   "title": "Dante inactive connections",
   "type": "graph",
   "description": " ss | grep -v ESTAB.*:9999 ....",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~exec.sockd.connections.inactive', 'contur=prod'), 'host')"
    }
   ]
  },
  { "title": "Squid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Cache Uptime",
   "type": "stat",
   "description": "squidclient -h localhost cache_object://localhost/ mgr:info\nищем UP time",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=snmpsquid.uptime', 'host=~.*dts-proxy-app.*'), 'host')"
    }
   ]
  },
  {
   "title": "Cache CPU usage",
   "type": "stat",
   "description": "squidclient -h localhost cache_object://localhost/ mgr:info\nищем CPU Usage",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=snmpsquid.cacheCpuUsage', 'host=~.*dts-proxy-app.*'), 'host')"
    }
   ]
  },
  {
   "title": "Cache Memory usage",
   "type": "stat",
   "description": "squidclient -h localhost cache_object://localhost/ mgr:info\nищем Memory accounted",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByTags(asPercent(seriesByTag('name=snmpsquid.cacheMemUsage', 'host=~.*dts-proxy-app.*'), #A), 'host')",
     "targetFull": "aliasByTags(asPercent(seriesByTag('name=snmpsquid.cacheMemUsage', 'host=~.*dts-proxy-app.*'), scale(seriesByTag('name=snmpsquid.cacheMemMaxSize', 'host=~.*dts-proxy-app.*'), 1024)), 'host')"
    }
   ]
  },
  {
   "title": "Squid connected clients",
   "type": "stat",
   "description": "squidclient -h localhost cache_object://localhost/ mgr:info\nищем Number of clients accessing cache",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~.*dts-proxy-app.*', 'name=~snmpsquid.cacheClients'), 'host')"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "squidclient -h localhost cache_object://localhost/ mgr:info\nКоличество полученных запросов",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=snmpsquid.cacheProtoClientHttpRequests', 'host=~.*dts-proxy-app.*'), 'host')"
    }
   ]
  },
  {
   "title": "HTTP Hits",
   "type": "graph",
   "description": "squidclient -h localhost cache_object://localhost/ mgr:info",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=snmpsquid.cacheHttpHits', 'host=~.*dts-proxy-app.*'), 'host')"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "description": "squidclient -h localhost cache_object://localhost/ mgr:info\nКоличество полученных запросов",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=snmpsquid.cacheHttpErrors', 'host=~.*dts-proxy-app.*'), 'Errors')"
    }
   ]
  },
  {
   "title": "HTTP In",
   "type": "graph",
   "description": "squidclient -h localhost cache_object://localhost/ mgr:info\nБерем количество килобайт входящих КБ и смотрим в разрезе 1 секунды",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~snmpsquid.cacheHttp(In)Kb', 'host=~.*dts-proxy-app.*')), 'host')"
    }
   ]
  },
  {
   "title": "HTTP Out",
   "type": "graph",
   "description": "squidclient -h localhost cache_object://localhost/ mgr:info\nБерем количество килобайт исходящих КБ и смотрим в разрезе 1 секунды",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~snmpsquid.cacheHttp(Out)Kb', 'host=~.*dts-proxy-app.*')), 'host')"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "csr-dts-proxy-app1 CPU",
   "type": "graph",
   "description": "Статистика использования CPU",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByMetric(aliasByTags(seriesByTag('cpu=cpu-total', 'name=~system.cpu.usage_(user|softirq|nice|iowait|system|steal|guest|irq)', 'host=~csr-dts-proxy-app1.unix.tensor.ru'), 'name')), 'usage_', '')"
    }
   ]
  },
  {
   "title": "csr-dts-proxy-app2 CPU",
   "type": "graph",
   "description": "Статистика использования CPU",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByMetric(aliasByTags(seriesByTag('cpu=cpu-total', 'name=~system.cpu.usage_(user|softirq|nice|iowait|system|steal|guest|irq)', 'host=~csr-dts-proxy-app2.unix.tensor.ru'), 'name')), 'usage_', '')"
    }
   ]
  },
  {
   "title": "csr-dts-proxy-app3 CPU",
   "type": "graph",
   "description": "Статистика использования CPU",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByMetric(aliasByTags(seriesByTag('cpu=cpu-total', 'name=~system.cpu.usage_(user|softirq|nice|iowait|system|steal|guest|irq)', 'host=~csr-dts-proxy-app3.unix.tensor.ru'), 'name')), 'usage_', '')"
    }
   ]
  },
  {
   "title": "csr-dts-proxy-app3 CPU",
   "type": "graph",
   "description": "Статистика использования CPU",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByMetric(aliasByTags(seriesByTag('cpu=cpu-total', 'name=~system.cpu.usage_(user|softirq|nice|iowait|system|steal|guest|irq)', 'host=~csr-dts-proxy-app4.unix.tensor.ru'), 'name')), 'usage_', '')"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "csr-dts-proxy-app1 Memory",
   "type": "graph",
   "description": "Статистика использования памяти",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.memory.csr-dts-proxy-app1.*.mem.ram.{slab,proc,buffers,free,cached,used}.avg, -2)"
    }
   ]
  },
  {
   "title": "csr-dts-proxy-app2 Memory",
   "type": "graph",
   "description": "Статистика использования памяти",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.memory.csr-dts-proxy-app2.*.mem.ram.{slab,proc,buffers,free,cached,used}.avg, -2)"
    }
   ]
  },
  {
   "title": "csr-dts-proxy-app3 Memory",
   "type": "graph",
   "description": "Статистика использования памяти",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.memory.csr-dts-proxy-app3.*.mem.ram.{slab,proc,buffers,free,cached,used}.avg, -2)"
    }
   ]
  },
  {
   "title": "csr-dts-proxy-app4 Memory",
   "type": "graph",
   "description": "Статистика использования памяти",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.memory.csr-dts-proxy-app4.*.mem.ram.{slab,proc,buffers,free,cached,used}.avg, -2)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "csr-dts-proxy-app1 Traffic",
   "type": "graph",
   "description": "Статистика использования трафика",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.prod.linux.iface.csr-dts-proxy-app1.*.net.*.*.bps.avg, 'lo'), -3, -4)"
    }
   ]
  },
  {
   "title": "csr-dts-proxy-app2 Traffic",
   "type": "graph",
   "description": "Статистика использования трафика",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.prod.linux.iface.csr-dts-proxy-app2.*.net.*.*.bps.avg, 'lo'), -3, -4)"
    }
   ]
  },
  {
   "title": "csr-dts-proxy-app3 Traffic",
   "type": "graph",
   "description": "Статистика использования трафика",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.prod.linux.iface.csr-dts-proxy-app3.*.net.*.*.bps.avg, 'lo'), -3, -4)"
    }
   ]
  },
  {
   "title": "csr-dts-proxy-app4 Traffic",
   "type": "graph",
   "description": "Статистика использования трафика",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.prod.linux.iface.csr-dts-proxy-app4.*.net.*.*.bps.avg, 'lo'), -3, -4)"
    }
   ]
  }
 ]
}