{
 "title": "Puppetserver Performance",
 "description": "Ответственный: Борбат Я.Д. (АЦОД)",
 "tags": [
  "telegraf",
  "system",
  "puppetserver"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "tag_values(host)" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Active Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=puppet.http.active-histo.mean', 'host=$server'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "HTTP Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(exclude(seriesByTag('name=~puppet.http.puppet-v3-.*-----.*.mean', 'host=$server'), '(file-metadata|v3-file_content|metadata)'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "JRuby metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~puppet.jruby.(free|requested)-jrubies-histo.mean', 'host=$server'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "JRuby metrics timers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "jrubies - free, requested" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~puppet.jruby.(borrow-|lock-held-|lock-wait-|wait-)timer.mean', 'host=$server'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Heap Memory and Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes", "label": "heap-memory-used" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~puppet.memory.heap.(used|committed)', 'host=$server'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Compiler metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~puppet.compiler.(find_facts|compile|find_node).mean', 'host=$server'), 'host', 'name')"
    }
   ]
  }
 ]
}