{
 "title": "Rabbitmq - elastic",
 "description": "Ответственный: Конюхов М.В. (Эксплуатация)",
 "tags": [
  "linux",
  "service",
  "rabbit",
  "sbis3mon-kafka",
  "mv.konuhov"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.linux.cpuTime.*"
   },
   { "name": "domain", "label": "Домен", "query": "*.tensor.ru" },
   { "name": "aggr", "label": "Агргегация", "query": "max, avg, min" },
   { "name": "interval", "query": "1s" }
  ]
 },
 "panels": [
  {
   "title": "$server: cpu time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "repeat": "server",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.user.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.system.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.iowait.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.nice.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.softirq.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.irq.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.guest.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.steal.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: la",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "repeat": "server",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.la.$server.*.cpu.la.*.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "repeat": "server",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.cached.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.free.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.buffers.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.proc.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.slab.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: jvm mem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.node.jvm.mem.heap.used.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: net bps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "repeat": "server",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.tx.*.bps.$aggr, 'net.tx.lo'), -4, -3)"
    },
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.rx.*.bps.$aggr, 'net.rx.lo'), -4, -3)"
    },
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.ratio.*.bps.$aggr, 'net.ratio.lo'), -4, -3)"
    }
   ]
  },
  {
   "title": "$server: net (pps, error)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "repeat": "server",
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.tx.*.pps.$aggr, 'net.tx.lo'), -4, -3)"
    },
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.rx.*.pps.$aggr, 'net.rx.lo'), -4, -3)"
    },
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.ratio.*.pps.$aggr, 'net.ratio.lo'), -4, -3)"
    }
   ]
  },
  {
   "title": "$server: indices translog",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.node.indices.translog.stats.bytes.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: storage sdb bps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "repeat": "server",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.io.bps.sdb.*.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "repeat": "server",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.lag.sdb.svctm.$aggr, -4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.lag.sdb.await.$aggr, -4, -2)"
    }
   ]
  },
  {
   "title": "$server: storage sdb ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "repeat": "server",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(sbis3mon.$contur.linux.$server.$domain.*.aggr-$aggr.storage.sdb.io.rps.merged.{read,write}, '$interval', '$aggr', false), -5, -2, -1)"
    },
    {
     "target": "aliasByNode(summarize(sbis3mon.$contur.linux.$server.$domain.*.aggr-$aggr.storage.sdb.io.rps.{read,write}, '$interval', '$aggr', false), -4, -1)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.io.rps.merged.sdb.{read,write}.$aggr, -5, -4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.io.rps.sdb.{read,write}.$aggr, -4, -2)"
    }
   ]
  },
  {
   "title": "$server: partition used %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "repeat": "server",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sbis3mon.$contur.linux.partition.$server.*.partition.volume._2F.prc.raw | aliasByNode(-4)"
    },
    {
     "target": "sbis3mon.$contur.linux.partition.$server.*.partition.inode.*.prc.raw | aliasByNode(-4)"
    }
   ]
  }
 ]
}