{
 "title": "Rabbitmq - sbis3mon",
 "description": "Брокер серверных событий. Ответственный: Конюхов М.В. (Эксплуатация), Смирнов И.В. (Разработка)",
 "tags": [
  "linux",
  "service",
  "rabbit",
  "sbis3mon-kafka",
  "mv.konuhov"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.rabbitmq.pushStat.*"
   },
   { "name": "aggr", "label": "Агргегация", "query": "max, avg, min" },
   { "name": "interval", "query": "1s" }
  ]
 },
 "panels": [
  {
   "title": "lost and fount errors",
   "type": "timeseries",
   "description": "ошибки маршрутизации ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByTags(sbis3mon.prod.rabbitmq.*.$server.rabbitmq.*.rabbitmq.queue.lost-and-found.messages_5Fready.raw, 4)"
    }
   ]
  },
  {
   "title": "amqp-tools откачка",
   "type": "timeseries",
   "description": "откачка сообщений",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "target": "aliasByTags(transformNull(seriesByTag('interval=180s', 'name=rabbitmq.queue', 'script=cloud_rabbit_sucking_amqp-tools.py', 'contur=prod', 'service=rabbitmq'), -1), 'type', 'layer')"
    }
   ]
  },
  {
   "title": "$server: msgRate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "repeat": "server",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.msgRate.publish.raw, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.msgRate.confirm.raw, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.msgRate.deliver.raw, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.msgRate.deliverNoAck.raw, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.msgRate.get.raw, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.msgRate.ack.raw, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.msgRate.re*.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: msgQueued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "repeat": "server",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.msgQueued.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cpu time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "repeat": "server",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.user.$aggr, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.system.$aggr, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.iowait.$aggr, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.nice.$aggr, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.softirq.$aggr, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.irq.$aggr, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.guest.$aggr, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.steal.$aggr, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: node memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "repeat": "server",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeries(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.node.memory.conns.*.raw), -4, -3)"
    },
    {
     "target": "aliasByNode(sumSeries(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.node.memory.queues.*.raw), -4, -3)"
    },
    {
     "target": "aliasByNode(sumSeries(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.node.memory.processes.*.raw), -4, -3)"
    },
    {
     "target": "aliasByNode(sumSeries(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.node.memory.tables.*.raw), -4, -3)"
    },
    {
     "target": "aliasByNode(sumSeries(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.node.memory.binaries.raw), -3, -2)"
    },
    {
     "target": "aliasByNode(sumSeries(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.node.memory.system.other.raw), -4, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: net bps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "repeat": "server",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.tx.*.bps.$aggr, 'net.tx.lo'), -2, -4)"
    },
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.rx.*.bps.$aggr, 'net.rx.lo'), -2, -4)"
    },
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.ratio.*.bps.$aggr, 'net.ratio.lo'), -2, -4)"
    }
   ]
  },
  {
   "title": "$server: net (pps, error)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "repeat": "server",
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.tx.*.pps.$aggr, 'net.tx.lo'), -2, -4)"
    },
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.rx.*.pps.$aggr, 'net.rx.lo'), -2, -4)"
    },
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.ratio.*.pps.$aggr, 'net.ratio.lo'), -2, -4)"
    }
   ]
  },
  {
   "title": "$server: node io",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "repeat": "server",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.node.io.bytes.*.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: node io",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "repeat": "server",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.node.io.ops.*.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: node io",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 132 },
   "repeat": "server",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.node.clusterLinks.*.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: log.errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 146 },
   "repeat": "server",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.checkLog.$server.rabbitmq.*.rabbitmq.log.errors.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 160 },
   "repeat": "server",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.objects.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: node io",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
   "repeat": "server",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.node.io.avgtime.*.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
   "repeat": "server",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.node.queueIndex.*.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 206 },
   "repeat": "server",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.rabbitmq.pushStat.$server.rabbitmq.*.rabbitmq.node.msgStore.*.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 222 },
   "repeat": "server",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.cached.$aggr, -4, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.free.$aggr, -4, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.buffers.$aggr, -4, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.proc.$aggr, -4, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.slab.$aggr, -4, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: connection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 236 },
   "repeat": "server",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.netstat.$server.*.net.total.connection.*.$aggr, -4, -2), '_5F', ' ')"
    }
   ]
  },
  {
   "title": "$server: storage sdb bps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 250 },
   "repeat": "server",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.io.bps.sdb.*.$aggr, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: storage sdb ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 264 },
   "repeat": "server",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.io.rps.merged.sdb.{read,write}.$aggr, -6, -5, -4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.io.rps.sdb.{read,write}.$aggr, -5, -4, -2)"
    }
   ]
  },
  {
   "title": "$server: storage sdb busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 278 },
   "repeat": "server",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.busy.sdb.$aggr, -2, -3)"
    },
    {
     "target": "aliasByNode(summarize(sbis3mon.$contur.linux.storage.$server.*.storage.queue.sdb.$aggr, '$interval', '$aggr', false), -2, -3)"
    }
   ]
  },
  {
   "title": "$server: lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 292 },
   "repeat": "server",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.lag.sdb.await.$aggr, -3, -4, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.lag.sdb.svctm.$aggr, -3, -4, -2)"
    }
   ]
  }
 ]
}