{
 "title": "Rabbitmq - graylog",
 "description": "Ответственный: Конюхов М.В. (Эксплуатация)",
 "tags": [
  "service",
  "rabbit",
  "sbis3mon-kafka",
  "mv.konuhov"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.linux.cpuTime.*"
   },
   { "name": "domain", "label": "Домен", "query": "*.tensor.ru" },
   { "name": "aggr", "label": "Агргегация", "query": "max, avg, min" },
   { "name": "interval", "query": "1s" }
  ]
 },
 "panels": [
  {
   "title": "$server: cpu time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "repeat": "server",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.{user,system,iowait,nice,softirq,irq,guest,steal}.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: cpu time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.{user,system,iowait,nice,softirq,irq,guest,steal}.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: mem usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "repeat": "server",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.{cached,free,buffers,proc,slab}.$aggr, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: mem usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.{cached,free,buffers,proc,slab}.$aggr, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: net bps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "repeat": "server",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.{tx,rx,ratio}.*.bps.$aggr, 'net.tx.lo'), -4, -3)"
    }
   ]
  },
  {
   "title": "$server: net bps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.{tx,rx,ratio}.*.bps.$aggr, 'net.tx.lo'), -4, -3)"
    }
   ]
  },
  {
   "title": "$server: storage sdb bps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "repeat": "server",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.io.bps.sdb.*.$aggr, -4, -2)"
    }
   ]
  },
  {
   "title": "$server: storage sdb bps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.io.bps.sdb.*.$aggr, -4, -2)"
    }
   ]
  },
  {
   "title": "$server: storage lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "repeat": "server",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.lag.sdb.{await,svctm}.$aggr, -4, -2)"
    }
   ]
  },
  {
   "title": "$server: storage lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.lag.sdb.{await,svctm}.$aggr, -4, -2)"
    }
   ]
  }
 ]
}