{
 "title": "Redis telegraf",
 "description": "Redis - noSQL база данных по типу ключ-значение. Ответственный: Конюхов М.В. (Эксплуатация), Голубев А.Ф. (Разработка)",
 "tags": [
  "service",
  "telegraf",
  "redis",
  "mv.konuhov"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "tag_values(host,servertype=redis,contur=prod)"
   },
   {
    "name": "port",
    "query": "tag_values(port,host=~${server:regex})"
   },
   { "name": "role", "query": "master,slave" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "bargauge",
   "description": "server uptime(int, seconds)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.uptime', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Connected clients",
   "type": "bargauge",
   "description": "connected clients(int, number)",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.clients', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Commans/s",
   "type": "bargauge",
   "description": "operations per second instantaneous_ops_per_sec(int, number)",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.instantaneous_ops_per_sec', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "DB Keys",
   "type": "bargauge",
   "description": "total keys keys(int, number)",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.keys', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Memory Fragmentation",
   "type": "bargauge",
   "description": "memory fragmentation ratio mem_fragmentation_ratio(float, number)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.mem_fragmentation_ratio', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "bargauge",
   "description": "used_memory(int, bytes) в процентах от maxmemory(int, bytes)\n> начинаем вытеснение вида allkeys_lru при достижении 100%\n",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(asPercent(seriesByTag('servertype=redis', 'name=redis.used_memory', 'port=$port', 'host=~${server:regex}', 'replication_role=~.*'), #A), 'host', 'port', 'replication_role')",
     "targetFull": "aliasByTags(asPercent(seriesByTag('servertype=redis', 'name=redis.used_memory', 'port=$port', 'host=~${server:regex}', 'replication_role=~.*'), aliasByTags(removeEmptySeries(seriesByTag('servertype=redis', 'name=redis.maxmemory', 'port=$port', 'host=~${server:regex}', 'replication_role=~.*')), 'host', 'port', 'replication_role')), 'host', 'port', 'replication_role')"
    }
   ]
  },
  {
   "title": "Master link status",
   "type": "bargauge",
   "description": "master_link_down_since_seconds(int, number)\n> т.к. master_link_status(string) передается текстом, но кафка текст не ест, мы смотрим на время когда линк отвалился.\nесли подключение к мастеру впорядке - данных по метрике не будет",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "aliasByTags(transformNull(seriesByTag('servertype=redis', 'name=redis.master_link_down_since_seconds', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), -1), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "bargauge",
   "description": "redis replication lag(int, number)\n> разница в командах между мастером и слейвом. можно также смотреть offset на мастере и слейве и сравнивать их разницу.\n0 и 1 = норма. снимается только с мастера.\nhost.port.replica_ip.state\nhost - сервер редиса\nport - порт редиса\nreplica_ip - слейв, который замеряется\nstate - состояние репликации (\"online\", \"wait_bgsave\", or \"send_bulk\")\n",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(transformNull(seriesByTag('servertype=redis', 'name=redis.lag', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 1), 'host', 'port', 'replica_ip', 'state')"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Operations per second",
   "type": "graph",
   "description": "Кол-во запросов в секунду.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.instantaneous_ops_per_sec', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Total commands processed/s",
   "type": "graph",
   "description": "Кол-во обработанных команд в секунду.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('servertype=redis', 'name=redis.total_commands_processed', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}')), 'host', 'port')"
    }
   ]
  },
  {
   "title": "instantaneous Input",
   "type": "graph",
   "description": "Рейтинг входящего трафика операций. килобайты в секунду.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.instantaneous_input_kbps', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "instantaneous Output",
   "type": "graph",
   "description": "Рейтинг исходящего трафика операций. килобайты в секунду.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.instantaneous_output_kbps', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Connected clients",
   "type": "graph",
   "description": "Кол-во подключенных клиентов. Лимит 10к.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.clients', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Total connection received/s",
   "type": "graph",
   "description": "Кол-во новых подключений в секунду. Обычно наглядно показывает резкий рост подключений при проблемах.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.clients', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Rejected connections/s",
   "type": "graph",
   "description": "Кол-во новых подключений в секунду, которые redis отклонил. Обычно наглядно показывает резкий рост подключений при проблемах.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('servertype=redis', 'name=redis.rejected_connections', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}')), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Blocked clients",
   "type": "graph",
   "description": "Всего заблокировано клиентов.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.blocked_clients', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  { "title": "Keyspace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Keys total",
   "type": "graph",
   "description": "Всего ключей во всех БД порта redis.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.keys', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Keys avg_ttl",
   "type": "graph",
   "description": "Среднее время жизни ключей.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.avg_ttl', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Keys expires / s",
   "type": "graph",
   "description": "Кол-во истекших ключей в секунду.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('servertype=redis', 'name=redis.expired_keys', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}')), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Keys evicted / s",
   "type": "graph",
   "description": "Кол-во вытесненных ключей в секунду. Если вытеснение явно противопоказано, наличие вытесненных ключей может показывать проблемы.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('servertype=redis', 'name=redis.evicted_keys', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}')), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Keyspace hits / s ",
   "type": "graph",
   "description": "Кол-во попаданий по запросу ключа в секунду.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('servertype=redis', 'name=redis.keyspace_hits', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}')), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Keyspace miss / s",
   "type": "graph",
   "description": "Кол-во промахов по запросу ключа в секунду.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('servertype=redis', 'name=redis.keyspace_misses', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}')), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Keyspace hitrate",
   "type": "graph",
   "description": "Отношение hits к miss keyspace_hitrate(float, number). Ожидается, что ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.keyspace_hitrate', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Used Memory",
   "type": "graph",
   "description": "Использовано памяти в байтах портом. Внимание! Порт может физически потребить гораздо больше памяти, нежели ему выделено. Смотрим фрагментацию. ",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.used_memory', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Maxmemory",
   "type": "graph",
   "description": "Максимально выделенная память для порта",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.maxmemory', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Memory fragmentation ratio",
   "type": "graph",
   "description": "The fragmentation is calculated as the physical memory actually used (the RSS value) divided by the amount of memory currently in use (as the sum of all the allocations performed by Redis)",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.mem_fragmentation_ratio', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Used Memory Rss",
   "type": "graph",
   "description": "Использование памяти включая не только данные ключей, но и служебную rss информацию. Более приближенное к реальному потреблению памяти в системе значение. В байтах",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.used_memory_rss', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Used Memory Peak",
   "type": "graph",
   "description": "Пиковое потребление памяти, зафиксированное статистикой redis.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.used_memory_peak', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Used Memory LUA",
   "type": "graph",
   "description": "used_memory_lua(int, bytes)\n> используемое значение памяти всяческими скриптами",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.used_memory_lua', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "CPU SYS Time",
   "type": "graph",
   "description": "used_cpu_sys(float, number). Здесь может отображаться более 100%, т.к. значение высчитываемое из cpu time и берется оно в секнуду.\n> CPU time (expressed in seconds) accumulated since the launch of the Redis instance, as reported by the getrusage() call.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('servertype=redis', 'name=redis.used_cpu_sys', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}')), 'host', 'port')"
    }
   ]
  },
  {
   "title": "CPU SYS Time",
   "type": "graph",
   "description": "used_cpu_sys(float, number). Здесь может отображаться более 100%, т.к. значение высчитываемое из cpu time и берется оно в секнуду.\n> CPU time (expressed in seconds) accumulated since the launch of the Redis instance, as reported by the getrusage() call.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('servertype=redis', 'name=redis.used_cpu_sys', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}')), 'host', 'port')"
    }
   ]
  },
  {
   "title": "CPU Sys Children Time",
   "type": "graph",
   "description": "used_cpu_sys_children(float, number)\n> CPU time (expressed in seconds) accumulated since the launch of the Redis instance, as reported by the getrusage() call.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('servertype=redis', 'name=redis.used_cpu_sys_children', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}')), 'host', 'port')"
    }
   ]
  },
  {
   "title": "CPU User Time",
   "type": "graph",
   "description": "used_cpu_user(float, number). Здесь может отображаться более 100%, т.к. значение высчитываемое из cpu time и берется оно в секнуду.\n> CPU time (expressed in seconds) accumulated since the launch of the Redis instance, as reported by the getrusage() call.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('servertype=redis', 'name=redis.used_cpu_user', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}')), 'host', 'port')"
    }
   ]
  },
  { "title": "Persistence and Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Loading dataset in memory",
   "type": "graph",
   "description": "loading(int,flag)\n>  в логах примерно такое:  ERROR: LOADING Redis is loading the dataset in memory.\nВо время репликации (поднялся порт после падения) или полной ресинхронизации слейв может быть недоступен. Данный флаг будет равен 1.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.loading', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Active bgsave",
   "type": "graph",
   "description": "rdb_bgsave_in_progress(int, flag)\n> идет ли в фоне процесс bgsave 1= да",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.rdb_bgsave_in_progress', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Connected slaves",
   "type": "graph",
   "description": "connected_slaves(int, number)\n> сколько слейвов подключено к мастеру",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.connected_slaves', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "RDB last save ago",
   "type": "graph",
   "description": "rdb_last_save_time(int, seconds)\n> время в формате Epoch, прошедшее с последней сохранения БД на диск в /var/lib/redis",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "dateTimeFromNow" }
   ],
   "targets": [
    {
     "target": "aliasByTags(scale(seriesByTag('servertype=redis', 'name=redis.rdb_last_save_time', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 1000), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Duration of master_link_down",
   "type": "graph",
   "description": "master_link_down_since_seconds(int, number)\n> показывает сколько времени прошло с момента, когда слейв отвалился от мастера master_link_status = down. Если нет данных - линк живой",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 109 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(transformNull(seriesByTag('servertype=redis', 'name=redis.master_link_down_since_seconds', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 0), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Backlog active",
   "type": "graph",
   "description": "repl_backlog_active(int, number)\n> Backlog stores the data after the moment a slave disconnected",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(transformNull(seriesByTag('servertype=redis', 'name=redis.repl_backlog_active', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 0), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Sync Full",
   "type": "graph",
   "description": "sync_full(int, number)\n> счетчик full partial resync",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.sync_full', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Sync Partial OK",
   "type": "graph",
   "description": "sync_partial_ok(int, number)\n> счетчик удачных full partial resync",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.sync_full', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Sync Partial Errors",
   "type": "graph",
   "description": "sync_partial_err(int, number)\n> количество denied partial resync запросов",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis.sync_partial_err', 'port=$port', 'host=~${server:regex}', 'replication_role=~${role:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "Cluster failed actions",
   "type": "graph",
   "description": "redis_failed_actions\n> в crm status присутствуют Failed actions (снимается скриптом). если их вовремя не почистить после устранения проблем - могут быть другие проблемы в корректности работы кластера",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=redis', 'name=redis_failed_actions', 'host=~${server:regex}'), 'host', 'port')"
    }
   ]
  },
  {
   "title": "CMD stats ~ $server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "repeat": "server",
   "collapsed": true,
   "panels": [
    {
     "title": "CMD stats CALLS/s $server",
     "type": "graph",
     "description": "Кол-во вызовов redis_cmdstat calls(int, number)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 131 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(seriesByTag('servertype=redis', 'name=redis.calls', 'port=$port', 'host=~${server:regex}')), 'command'))"
      }
     ]
    },
    {
     "title": "CMD stats USEC $server",
     "type": "graph",
     "description": "Кол-во вызовов redis_cmdstat usec(int, mircoseconds)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 131 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(seriesByTag('servertype=redis', 'name=redis.usec', 'port=$port', 'host=~${server:regex}')), 'command'))"
      }
     ]
    }
   ]
  }
 ]
}