{
 "title": "Sbis3mon",
 "description": "Ответственный: -",
 "tags": [
  "service",
  "sbis3mon",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   { "name": "server", "query": "sbis3mon.$contur.sbis3mon.*" }
  ]
 },
 "panels": [
  {
   "title": "Sbis3mon server latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.collector.latency.$server.interval-4sec.sbis3mon.collector.latency.p99, -3, -2, -1)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.collector.latency.$server.interval-4sec.sbis3mon.collector.latency.p90, -3, -2, -1)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.collector.latency.$server.interval-4sec.sbis3mon.collector.latency.p50, -3, -2, -1)"
    }
   ]
  },
  {
   "title": "Sbis3mon server LA/contextSwitch",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.la.$server.interval-28sec.cpu.la.*.avg, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.la.$server.interval-28sec.cpu.contextSwitch.avg, -3, -2)"
    }
   ]
  },
  {
   "title": "Sbis3mon server cpu.busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(aliasByNode(sbis3mon.$contur.linux.core.$server.interval-28sec.cpu.busy.avg, 3, -3, -2), 'cpu.busy.avg')"
    },
    {
     "target": "alias(aliasByNode(sbis3mon.$contur.linux.core.$server.interval-28sec.cpu.busy.max, 3, -3, -2), 'cpu.busy.max')"
    }
   ]
  },
  {
   "title": "Sbis3mon server memory.base",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.interval-28sec.mem.ram.proc.avg, 3, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.interval-28sec.mem.ram.free.avg, 3, -3, -2)"
    }
   ]
  },
  {
   "title": "Sbis3mon server net.connection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.netstat.$server.interval-30sec.net.total.connection.*.avg, 8, 9)"
    }
   ]
  },
  {
   "title": "Sbis3mon server net.stat.listen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.netstatCounter.$server.interval-30sec.net.stat.listen.*.raw, 8, 9)"
    }
   ]
  },
  {
   "title": "Summarized trapper processed/queued",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.worker.stats.$server.interval-5sec.sbis3mon.worker.summarize.trapper.processed, 3, -3, -2, -1)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.worker.stats.$server.interval-5sec.sbis3mon.worker.summarize.trapper.queued, 3, -3, -2, -1)"
    }
   ]
  },
  {
   "title": "Summarized trapper processingTime/responseTime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.worker.stats.$server.interval-5sec.sbis3mon.worker.summarize.trapper.processingTime, 3, -3, -2, -1)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.worker.stats.$server.interval-5sec.sbis3mon.worker.summarize.trapper.responseTime, 3, -3, -2, -1)"
    }
   ]
  },
  {
   "title": "Summarize kafka metrics/messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.worker.stats.$server.interval-5sec.sbis3mon.worker.summarize.kafka.metrics, 3, -3, -2, -1)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.worker.stats.$server.interval-5sec.sbis3mon.worker.summarize.kafka.messages, 3, -3, -2, -1)"
    }
   ]
  },
  {
   "title": "Summarize kafka queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.worker.stats.$server.interval-5sec.sbis3mon.worker.summarize.kafka.queue.msg_5Fcnt, 3, -3, -2, -1)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.worker.stats.$server.interval-5sec.sbis3mon.worker.summarize.kafka.queue.msg_5Fsize, 3, -3, -2, -1)"
    }
   ]
  },
  {
   "title": "worker.processingTime/responseTime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(sbis3mon.$contur.worker.stats.$server.interval-5sec.sbis3mon.worker.trapper.processingTime.*), 9, 10)"
    },
    {
     "target": "aliasByNode(sortByMaxima(sbis3mon.$contur.worker.stats.$server.interval-5sec.sbis3mon.worker.trapper.responseTime.*), 9, 10)"
    }
   ]
  },
  {
   "title": "worker.latency.p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(sbis3mon.$contur.worker.latency.$server.interval-4sec.sbis3mon.worker.latency.*.p99), 7, 9)"
    }
   ]
  },
  {
   "title": "lms3-db cpu.busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.core.lms3-db.interval-28sec.cpu.busy.*, -3, -2, -1)"
    }
   ]
  },
  {
   "title": "lms3-db mem.used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.memory.lms3-db.interval-28sec.mem.ram.used.*, -3, -2, -1)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.memory.lms3-db.interval-28sec.mem.ram.total.max, -3, -2, -1)"
    }
   ]
  },
  {
   "title": "lms3 net.stat.listen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.netstatCounter.lms3.interval-30sec.net.stat.listen.*.raw, 8, 9)"
    }
   ]
  },
  {
   "title": "lms3-db LA/contextSwitch",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.la.lms3-db.interval-28sec.cpu.la.*.avg, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.la.lms3-db.interval-28sec.cpu.contextSwitch.avg, -3, -2)"
    }
   ]
  },
  {
   "title": "lms3-db.DATA disk.busy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.lms3-db.interval-30sec.storage.busy.mpathd.*, 8, 7, 9)"
    }
   ]
  },
  {
   "title": "lms3-db.LOG disk.busy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.lms3-db.interval-30sec.storage.busy.mpathf.*, 8, 7, 9)"
    }
   ]
  },
  {
   "title": "lms3-db.DATA disk.lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.lms3-db.interval-30sec.storage.lag.mpathd.await.*, 8, 7, 10)"
    }
   ]
  },
  {
   "title": "lms3-db.LOG disk.lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.lms3-db.interval-30sec.storage.lag.mpathf.await.*, 8, 7, 10)"
    }
   ]
  },
  {
   "title": "lms3-db.DATA read/write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.lms3-db.interval-30sec.storage.io.bps.mpathd.write.*, 9, 8, 10, 11)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.lms3-db.interval-30sec.storage.io.bps.mpathd.read.*, 9, 8, 10, 11)"
    }
   ]
  },
  {
   "title": "lms3-db.LOG read/write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.lms3-db.interval-30sec.storage.io.bps.mpathf.write.*, 9, 8, 10, 11)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.linux.storage.lms3-db.interval-30sec.storage.io.bps.mpathf.read.*, 9, 8, 10, 11)"
    }
   ]
  }
 ]
}