{
 "title": "sip-autocall, kamailio",
 "description": "Комплексный экран по sip-autocall и автодозвону (kamailio + платформы телефонии по дозвону). Ответственный: Конюхов М.В. (Эксплуатация)",
 "tags": [
  "telegraf",
  "service",
  "mv.konuhov",
  "telephony",
  "телефония",
  "kamailio",
  "autocall",
  "sip-autocall"
 ],
 "time": { "from": "now-5m", "to": "now-1m" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   { "name": "servertype", "label": "Тип", "query": "telephony" },
   {
    "name": "host",
    "label": "Сервер",
    "query": "tag_values(host,contur=$contur,servertype=$servertype,service=kamailio,name=procstat.keepalived.running)"
   }
  ]
 },
 "panels": [
  { "title": "sip-autocall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kamailio АТС в балансировке",
   "type": "timeseries",
   "description": "Количество АТС в балансировке и кол-во рабочих АТС в балансировке",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "alias(seriesByTag('name=kamailio_api_metrics.count_pbx', 'contur=${contur:regex}'), 'всего АТС', false)"
    },
    {
     "target": "alias(seriesByTag('name=kamailio_api_metrics.count_active_pbx', 'contur=${contur:regex}'), 'активных АТС', false)"
    }
   ]
  },
  {
   "title": "Kamailio статус провайдеров",
   "type": "timeseries",
   "description": "Статус провайдеров. 0 - не работает,  1 - работает.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=~kamailio_api_metrics.providers*', 'contur=${contur:regex}'), 'name'), '\\?contur\\=prod\\&host\\=exp-monitoring3\\.unix\\.tensor\\.ru&interval\\=60s\\&servertype=telephony\\&service=kamailio', ''), 'kamailio_api_metrics.providers_', '')"
    }
   ]
  },
  {
   "title": "Kamailio статус регистраций",
   "type": "timeseries",
   "description": "Статус регистраций. 0 - не работает,  1 - работает.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=~kamailio_api_metrics.registrations*', 'contur=${contur:regex}'), 'name'), '\\?contur=prod&host=exp-monitoring3.unix.tensor.ru&interval=60s&servertype=telephony&service=kamailio', ''), 'kamailio_api_metrics.registrations_', '')"
    }
   ]
  },
  {
   "title": "Keepalived InstanceState",
   "type": "timeseries",
   "description": "telegraf flussonic_snmp.InstanceState\ninit(0), backup(1), master(2), fault(3), unknown(4)\nТекущее состояние инстанса keepalived на сервере в разрезе instanceRouterID",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "aliasByTags(transformNull(seriesByTag('name=kamailio_snmp.instanceState', 'contur=${contur:regex}', 'host=~${host:regex}'), -1), 'host', 'instanceRouterID')"
    }
   ]
  },
  {
   "title": "Keepalived instanceWantedState",
   "type": "timeseries",
   "description": "telegraf flussonic_snmp.instanceWantedState\ninit(0), backup(1), master(2), fault(3), unknown(4)\nОжидаемое состояние инстанса keepalived на сервере в разрезе instanceRouterID",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "target": "aliasByTags(transformNull(seriesByTag('name=kamailio_snmp.instanceWantedState', 'contur=${contur:regex}', 'host=~${host:regex}'), -1), 'host', 'instanceRouterID')"
    }
   ]
  },
  {
   "title": "Статус keepalived.service",
   "type": "timeseries",
   "description": "telegraf procstat.keepalived.running. ok (1) else bad.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=procstat.keepalived.running', 'contur=${contur:regex}', 'host=~${host:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "Статус kamailio.service",
   "type": "timeseries",
   "description": "telegraf procstat.kamailio.running. ok (1) else bad.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=procstat.keepalived.running', 'contur=${contur:regex}', 'host=~${host:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "Время ответа точки входа csr-tel-autocall-bl.unix.tensor.ru",
   "type": "timeseries",
   "description": "опрос доступности csr-tel-autocall-bl.unix.tensor.ru:5060 и csr-tel-autocall-bl.unix.tensor.ru:8080\n\nмониторится с exp-monitoring3 telegraf /etc/telegraf/telegraf.d/sbis-sip-autocall.conf",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=kamailio_net_response.response_time', 'contur=${contur:regex}'), 'port')"
    }
   ]
  },
  {
   "title": "Код ответа точки входа csr-tel-autocall-bl.unix.tensor.ru",
   "type": "table",
   "description": "опрос доступности csr-tel-autocall-bl.unix.tensor.ru:5060 и csr-tel-autocall-bl.unix.tensor.ru:8080\n\nмониторится с exp-monitoring3 telegraf /etc/telegraf/telegraf.d/sbis-sip-autocall.conf\n\nкоды: int, success = 0, timeout = 1, connection_failed = 2, read_failed = 3, string_mismatch = 4",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=kamailio_net_response.result_code', 'contur=${contur:regex}'), 'port')"
    }
   ]
  },
  { "title": "autocall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Статистика по autocall",
   "type": "timeseries",
   "description": "Сделано по https://online.sbis.ru/opendoc.html?guid=94efae5c-8f41-4bde-abf3-2e887dbeecee\nСкрипт https://adm-git.tensor.ru/exp/monitoring-scripts/telephony/-/blob/master/scripts/tel_sip_autocall_stats.py\nСупервизор http://exp-monitoring3.unix.tensor.ru:9015/\n\ntasks_failed_in_row_count - Количество неудачных звонков подряд\n\ntasks_in_progress_count  - Очередь задач на дозвон, которые находятся в процессе звонка\n\ntasks_new_count - Очередь задач на дозвон, которые только запущены, но дозвон по ним еще не начался\n\ntemporary_switched_to_sms - Признак неправильной работы. Переключились на смс.\n\noriginate_fails - Наличие неудачных звонков по причине неправильной настройки службы дозвона ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=tel_sip_autocall_stats', 'contur=${contur:regex}'), 'metric_name')"
    }
   ]
  }
 ]
}