{
 "title": "SQUID Overview",
 "description": "Показатели производительности для кэша Squid. Ответственный: Конюхов М.В. (Эксплуатация)",
 "tags": [
  "Squid",
  "service",
  "telegraf",
  "mv.konuhov"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "IP",
    "label": "IP SQUID",
    "query": "tag_values(host,name=snmpsquid.cacheHttpHits)"
   }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "IP" },
  {
   "title": "Cache Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SQUID_CACHE_cacheUptime{ip=~\"$IP\"} / 8640000",
     "target": "seriesByTag('name=snmpsquid.uptime', 'host=$IP')"
    }
   ]
  },
  {
   "title": "Cache CPU usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(SQUID_CACHE_cacheHttpHits{ip=~\"$IP\"}[5m]))   / sum (rate(SQUID_CACHE_cacheProtoClientHttpRequests{ip=~\"$IP\"}[5m])) * 100",
     "target": "seriesByTag('name=snmpsquid.cacheCpuUsage', 'host=$IP')"
    }
   ]
  },
  {
   "title": "Cache Memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SQUID_CACHE_cacheHttpErrors{ip=\"10.30.11.42:3402\"} / 100",
     "target": "asPercent(seriesByTag('name=snmpsquid.cacheMemUsage', 'host=$IP'), #B)",
     "targetFull": "asPercent(seriesByTag('name=snmpsquid.cacheMemUsage', 'host=$IP'), scale(seriesByTag('name=snmpsquid.cacheMemMaxSize', 'host=$IP'), 1024))"
    }
   ]
  },
  {
   "title": "Connected clients",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "\nsum (rate(SQUID_CACHE_cacheHttpInKb{ip=~\"$IP\"}[5m])) ",
     "legendFormat": "In",
     "target": "aliasByNode(aliasByTags(seriesByTag('host=$IP', 'name=~snmpsquid.cacheClients'), 'name'), -1)"
    }
   ]
  },
  {
   "title": "HTTP Requests/Hits/Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "SQUID_CACHE_CacheOject{ip=~\"$IP\"}",
     "legendFormat": "CacheOject",
     "target": "alias(perSecond(seriesByTag('name=snmpsquid.cacheProtoClientHttpRequests', 'host=$IP')), 'Requests')"
    },
    {
     "expr": "SQUID_CACHE_CacheOject{ip=~\"$IP\"}",
     "legendFormat": "CacheOject",
     "target": "alias(perSecond(seriesByTag('name=snmpsquid.cacheHttpHits', 'host=$IP')), 'Hits')"
    },
    {
     "expr": "SQUID_CACHE_CacheOject{ip=~\"$IP\"}",
     "legendFormat": "CacheOject",
     "target": "alias(perSecond(seriesByTag('name=snmpsquid.cacheHttpErrors', 'host=$IP')), 'Errors')"
    }
   ]
  },
  {
   "title": "HTTP In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "SQUID_CACHE_Memory{ip=~\"$IP\"}\n",
     "legendFormat": "Memory",
     "target": "aliasByNode(aliasByTags(seriesByTag('name=~snmpsquid.cacheHttp(In|Out)Kb', 'host=$IP'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "SQUID_CACHE_cacheHttpMissSvcTime5{ip=~\"$IP\"}",
     "legendFormat": "HTTP miss service time",
     "target": "aliasByTags(seriesByTag('name=snmpsquid.cacheCurrentSwapSize', 'host=$IP'), 'name')"
    }
   ]
  },
  {
   "title": "Cacheserver In/Out",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "\nsum (rate(SQUID_CACHE_cacheHttpInKb{ip=~\"$IP\"}[5m])) ",
     "legendFormat": "In",
     "target": "aliasByNode(aliasByTags(seriesByTag('host=$IP', 'name=~snmpsquid.cacheServer(In|Out)Kb'), 'name'), -1)"
    }
   ]
  },
  {
   "title": "Использование памяти",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=$IP', 'name=~procstat.squid.memory_.*'), 'name'), 'procstat.squid.memory_', '')"
    }
   ]
  },
  {
   "title": "Использование CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=$IP', 'name=~procstat.squid.cpu_time_.+'), 'name'), 'procstat.squid.cpu_time_', '')"
    }
   ]
  },
  {
   "title": "Переключение контекста",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=$IP', 'name=~procstat.squid.involuntary_context_switches'), 'host'), 'procstat.squid.cpu_time_', '')"
    }
   ]
  },
  {
   "title": "Количество потоков",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=$IP', 'name=~procstat.squid.num_threads'), 'host'), 'procstat.squid.cpu_time_', '')"
    }
   ]
  }
 ]
}