{
 "title": "Turn servers",
 "description": "Ответственный: Никитин М.С. (Эксплуатация)",
 "tags": [
  "telegraf",
  "service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Загрузка CPU",
   "type": "graph",
   "description": "Загрузка процессоров по всем turn-серверам",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~(csr-|.*)turn-server.*\\.unix\\.tensor\\.ru', 'cpu=cpu-total', 'name=system.cpu.usage_active'), 'host', 'name'), 'unix.tensor.ru.system.cpu.usage_', '')"
    }
   ]
  },
  {
   "title": "Использование памяти",
   "type": "graph",
   "description": "Использование оперативной памяти на turn-серверах",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~(csr-|.*)turn-server.*\\.unix\\.tensor\\.ru', 'name=system.mem.active'), 'host', 'name')"
    },
    {
     "target": "aliasByTags(seriesByTag('host=~(csr-|.*)turn-server.*\\.unix\\.tensor\\.ru', 'name=system.mem.free'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Использование корневого раздела",
   "type": "graph",
   "description": "Использование корневого раздела на диске",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~(csr-|.*)turn-server.*\\.unix\\.tensor\\.ru', 'path=-', 'name=~system.disk.(total|used$)'), 'host', 'name'), '.unix.tensor.ru.system.disk', '')"
    }
   ]
  },
  {
   "title": "Использование /var/log/turnserver",
   "type": "graph",
   "description": "Использование раздела под логи",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~(csr-|.*)turn-server.*\\.unix\\.tensor\\.ru', 'path=-var-log-turnserver', 'name=~system.disk.(total|used$)'), 'host', 'name'), '.unix.tensor.ru.system.disk', '')"
    }
   ]
  },
  {
   "title": "Трафик на интерфейсе, pps",
   "type": "graph",
   "description": "Использование сетевых интерфейсов",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('host=~(csr-|.*)turn-server.*\\.unix\\.tensor\\.ru', 'name=~system.net.packets_(recv|sent)')), 'host', 'name'), '.unix.tensor.ru.system.net', '')"
    }
   ]
  },
  {
   "title": "Трафик на интерфейсе, bytes /s",
   "type": "graph",
   "description": "Использование сетевых интерфейсов в байтах",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('host=~(csr-|.*)turn-server.*\\.unix\\.tensor\\.ru', 'name=~system.net.bytes_(recv|sent)', 'interval=15s')), 'host', 'name'), '.unix.tensor.ru.system.net', '')"
    }
   ]
  },
  {
   "title": "Сетевая статистика",
   "type": "graph",
   "description": "Статистика использования сетевых интерфейсов",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "connections" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~(csr-|.*)turn-server.*\\.unix\\.tensor\\.ru', 'name=~system.netstat.*'), 'host', 'name'), '.unix.tensor.ru.system.netstat', '')"
    }
   ]
  }
 ]
}