{
 "title": "Vault",
 "description": "Ответственный: -",
 "tags": [
  "service",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prod" },
   {
    "name": "host",
    "query": "tag_values(host,cluster=$cluster,servertype=vault)"
   }
  ]
 },
 "panels": [
  {
   "title": "Servers count",
   "type": "stat",
   "description": "Количество серверов в кластере",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aggregate(keepLastValue(seriesByTag('name=vault.runtime.free_count', 'cluster=~${cluster:regex}'), 1), 'count')"
    }
   ]
  },
  {
   "title": "Leader Last Contact",
   "type": "gauge",
   "description": "Время, прошедшее с тех пор, как лидер последний раз смог связаться со своими последователями",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=vault.raft.leader.lastContact.upper', 'cluster=~${cluster:regex}'), 'host', 'name'), 0)"
    }
   ]
  },
  {
   "title": "Leadership changes",
   "type": "table",
   "description": "Продолжительность времени, которое сервер был лидером последний раз",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=vault.core.leadership_lost.upper', 'cluster=~${cluster:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "Count alias for entity",
   "type": "stat",
   "description": "Количество псевдонимов (alias) сущностей (entity) для объектов",
   "gridPos": { "h": 3, "w": 1, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aggregate(seriesByTag('name=vault.identity.entity.count', 'host=~${host:regex}'), 'last')"
    }
   ]
  },
  {
   "title": "Count entities",
   "type": "stat",
   "description": "Количество сущностей (entities)",
   "gridPos": { "h": 3, "w": 1, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aggregate(seriesByTag('name=vault.identity.entity.count', 'host=~${host:regex}'), 'last')"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "вверх - % загрузки CPU \nвниз - % CPU IOwait",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(seriesByTag('name=~cpu.usage_(user|iowait)', 'servertype=vault', 'host=~${host:regex}', 'cpu=cpu-total'), 'host', 'name'), 0, -1), 'usage_', '')"
    }
   ]
  },
  {
   "title": "Disk activity",
   "type": "graph",
   "description": "вверх - байт на запить\nвверх - байт на чтение",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(perSecond(aliasByTags(seriesByTag('name=~diskio.(read|write)_bytes', 'contur=prod', 'host=~${host:regex}', '_name=~sd(a|b)$', 'servertype=vault'), 'host', 'name', '_name')), 0, -2, -1), '_bytes', '')"
    }
   ]
  },
  {
   "title": "Count tokens",
   "type": "stat",
   "description": "Количество сервисных токенов",
   "gridPos": { "h": 3, "w": 1, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aggregate(groupByNodes(aliasByTags(seriesByTag('host=~${host:regex}', 'name=vault.token.count'), 'host'), 'sum', 0), 'last')"
    }
   ]
  },
  {
   "title": "Count k-v secrets",
   "type": "stat",
   "description": "Количество key-value секретов",
   "gridPos": { "h": 3, "w": 1, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aggregate(seriesByTag('name=vault.secret.kv.count', 'host=~${host:regex}'), 'last')"
    }
   ]
  },
  {
   "title": "Лидер",
   "type": "table",
   "description": "Текущие лидер кластера",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "targets": [
    {
     "target": "aliasByTags(isNotNull(seriesByTag('name=vault.raft-storage.put.sum', 'host=~${host:regex}')), 'host')"
    }
   ]
  },
  {
   "title": "Seal status",
   "type": "table",
   "description": "Статус доступности хранилища",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 6 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=http.progress', 'host=~${host:regex}'), 'host', 'sealed'), '\\.false', ' - распечатано'), '.true', ' - запечатано')"
    }
   ]
  },
  {
   "title": "Request handle time",
   "type": "graph",
   "description": "Время ответа лидера на поступающие запросы и их количество",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=vault.core.handle_request.mean', 'host=~${host:regex}'), 'host', 'name', '_name'), 0, -3)"
    },
    {
     "target": "aliasByNode(aliasByTags(scaleToSeconds(seriesByTag('name=vault.core.handle_request.count', 'host=~${host:regex}'), 1), 'host', 'name', '_name'), 0, -3, -2)"
    }
   ]
  },
  {
   "title": "Network activity",
   "type": "graph",
   "description": "байт принято/отправлено по сети",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(aliasByTags(seriesByTag('name=net.bytes_recv', 'host=~${host:regex}'), 'host', 'name', '_name')), 0, -2)"
    },
    {
     "target": "aliasByNode(perSecond(aliasByTags(seriesByTag('name=net.bytes_sent', 'host=~${host:regex}'), 'host', 'name', '_name')), 0, -2)"
    }
   ]
  },
  {
   "title": "Raft GET",
   "type": "graph",
   "description": "Суммарное время выполнения GET запроса",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=vault.raft-storage.get.sum'), 'host', 'name'), 0, -3, -2)"
    }
   ]
  },
  {
   "title": "Raft PUT",
   "type": "graph",
   "description": "Суммарное время выполнения PUT запроса",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=vault.raft-storage.put.sum', 'host=~${host:regex}'), 'host', 'name'), 0, -3, -2)"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "% использования памяти",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=mem.used_percent', 'host=~${host:regex}'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  {
   "title": "Raft LIST",
   "type": "graph",
   "description": "Суммарное время выполнения LIST запроса",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=vault.raft-storage.list.sum', 'host=~${host:regex}'), 'host', 'name'), 0, -3, -2)"
    }
   ]
  },
  {
   "title": "Raft DELETE",
   "type": "graph",
   "description": "Суммарное время выполнения DELETE запроса",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=vault.raft-storage.delete.sum', 'host=~${host:regex}'), 'host', 'name'), 0, -3, -2)"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "description": "Общее количество открытых файловых дескрипторов и их \"потолок\"",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=linux_sysctl_fs.file-nr', 'host=~${host:regex}'), 'host', 'name'), 0, -1)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=linux_sysctl_fs.file-max', 'host=~${host:regex}'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  {
   "title": "Raft transaction",
   "type": "graph",
   "description": "Количество транзакций Raft за интервал. Является общим показателем нагрузки записи на серверах Raft.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=vault.raft.apply', 'host=~${host:regex}'), 'host', 'name'), 0, -3, -2)"
    }
   ]
  },
  {
   "title": "Raft commit time",
   "type": "graph",
   "description": "Время создания новой записи на лидере",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=vault.raft.commitTime.upper', 'host=~${host:regex}'), 'name')"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "description": "Время «остановки мира», означающее, что все потоки времени выполнения блокируются до завершения GC. И количество этих остановок.\nПредупреждение: если total_gc_pause_ns превышает 2 секунды/минуту\nКритическое: если оно превышает 5 секунд/минуту",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "ns", "label": "Time" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=vault.runtime.gc_pause_ns.upper', 'host=~${host:regex}'), 'host', 'name'), 0, -1)"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=vault.runtime.gc_pause_ns.count', 'host=~${host:regex}'), 'host', 'name'), 0, -2, -1)"
    }
   ]
  }
 ]
}