{
 "title": "VideoCall Stomp",
 "description": "Ответственный: Штей А.И. (Видеосвязь\\Медиасервисы)",
 "tags": [ "telegraf" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Количество инвайтов",
   "type": "timeseries",
   "description": "Общее количество приглашений пользователей в беседы",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "seriesByTag('name=VideoCall.STOMP.Sending.Cnt')"
    }
   ]
  },
  {
   "title": "Инвайты продолжительнее 3 секунд в браузере",
   "type": "timeseries",
   "description": "Количество приглашений которые были реализованы через браузер и длились дольше 3 секунд",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "seriesByTag('name=VideoCall.STOMP.Delay.OverLimit.Browser')"
    }
   ]
  },
  {
   "title": "Инвайты продолжительнее 3 секунд в плагине",
   "type": "timeseries",
   "description": "Количество приглашений которые были реализованы через плагин и длились дольше 3 секунд",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "target": "seriesByTag('name=VideoCall.STOMP.Delay.OverLimit.Plugin')"
    }
   ]
  },
  {
   "title": "Максимальное время доставки инвайта в браузер, сек",
   "type": "timeseries",
   "description": "Самое долгое приглашение которое было зарегистрировано за минуту, реализованное в браузере",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "seriesByTag('name=VideoCall.STOMP.Delay.Max.Browser')"
    }
   ]
  },
  {
   "title": "Максимальное время доставки инвайта в плагин, сек",
   "type": "timeseries",
   "description": "Самое долгое приглашение которое было зарегистрировано за минуту, реализованное в плагине",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "target": "seriesByTag('name=VideoCall.STOMP.Delay.Max.Plugin')"
    }
   ]
  }
 ]
}