{
 "title": "Vipnet",
 "description": "Ответственный: Карпов С.В. (Эксплуатация)",
 "tags": [
  "exploitation",
  "telegraf",
  "service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Статус служб координаторов",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(sortByName(aliasByTags(seriesByTag('name=~(iplircontrol|Itcsrvup|monitor)', 'servertype=coordinator'), 'host', 'name'), true, false), 'iplircontrol', 'обновления'), 'Itcsrvup', 'драйвер')"
    }
   ]
  },
  {
   "title": "Получено конвертов",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(scale(seriesByTag('name=mftpstats.Received', 'servertype=coordinator'), 0.0011111111), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Отправлено конвертов",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(scale(seriesByTag('name=mftpstats.Sent', 'servertype=coordinator'), 0.00111111111), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Удаленные конверты",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=mftpstats.Deleted', 'servertype=coordinator'), 'host'), true, false)"
    }
   ]
  },
  { "title": "Файлы в каталогах координатора", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Возраст файла mftp-env.dat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=mftpenvdat', 'servertype=coordinator'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Возраст файла mftp.log",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=mftplog', 'servertype=coordinator'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Возраст самого старого файла в каталоге OUTENV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=OUTENV', 'servertype=coordinator'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('servertype=coordinator', 'objectname=filecount', 'name=OUT'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "CCC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=CCC', 'servertype=coordinator'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Trash",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=TRASH', 'servertype=coordinator'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "BAD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=BAD', 'servertype=coordinator'), 'host')"
    }
   ]
  },
  {
   "title": "Статус служб клиентов",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 19, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(sortByName(aliasByTags(seriesByTag('name=~(iplircontrol|Itcsrvup|wmail)', 'servertype=client'), 'host', 'name'), true, false), 'iplircontrol', 'обновления'), 'Itcsrvup', 'драйвер')"
    }
   ]
  },
  {
   "title": "Удаленные конверты",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=mftpstats.Deleted', 'servertype=client'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "OUT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('servertype=client', 'objectname=filecount', 'name=OUT'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "TRANSPORT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('servertype=client', 'objectname=filecount', 'name=TRANSPORT'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "IN",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('servertype=client', 'objectname=filecount', 'name=IN'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "CCC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=CCC', 'servertype=client'), 'host')"
    }
   ]
  },
  {
   "title": "Trash",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=TRASH', 'servertype=client'), 'host')"
    }
   ]
  },
  {
   "title": "BAD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('servertype=client', 'objectname=filecount', 'name=BAD'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "mftpenvdat client",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=mftpenvdat', 'servertype=client'), 'host'), true, false)"
    }
   ]
  }
 ]
}