{
 "title": "ZooKeeper",
 "description": "Ответственный: Воробьев П.А. (Эксплуатация)",
 "tags": [
  "zookeeper",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "system",
    "query": "tag_values(host,name=zookeeper.min_latency)"
   },
   {
    "name": "role",
    "query": "tag_values(state,host=~${system:regex})"
   }
  ]
 },
 "panels": [
  {
   "title": "min_latency",
   "type": "graph",
   "description": "Минимальные задержки",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=zookeeper.min_latency', 'host=~${system:regex}', 'state=~${role:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "avg_latency",
   "type": "graph",
   "description": "Средняя задержка",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=zookeeper.avg_latency', 'host=~${system:regex}', 'state=~${role:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "max_latency",
   "type": "graph",
   "description": "Максимальная задержка",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=zookeeper.max_latency', 'host=~${system:regex}', 'state=~${role:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "znode_count",
   "type": "graph",
   "description": "Количество znode в кластере",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=zookeeper.znode_count', 'host=~${system:regex}', 'state=~${role:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "open_file_descriptor_count",
   "type": "graph",
   "description": "Открытые файловые дескрипторы",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=zookeeper.open_file_descriptor_count', 'host=~${system:regex}', 'state=~${role:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "followers",
   "type": "graph",
   "description": "Общее количество фоловерров в кластере (вне зависимости от синхронизации)",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=zookeeper.followers', 'host=~${system:regex}', 'state=~leader'), 'host')"
    }
   ]
  },
  {
   "title": "synced_followers",
   "type": "graph",
   "description": "Количество синхронизированных фоловеров в кластере",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=zookeeper.synced_followers', 'host=~${system:regex}', 'state=~leader'), 'host')"
    }
   ]
  }
 ]
}