{
 "title": "Мониторинг: шина данных kafka",
 "description": "Ответственный: Новожилов Р.А. и Смирнов К.В. (Эксплуатация)",
 "tags": [
  "telegraf",
  "exploitation",
  "monitoring",
  "system"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Поток метрик в clickhouse",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "aliasByTags(groupByTags(aliasByTags(movingAverage(scale(seriesByTag('name=~carbon.clickhouse.interval-10sec.monitor\\d_unix_tensor_ru.ClickHouse.ProfileEvents.InsertedRows'), 0.05), '1m'), 'host'), 'sum', 'name'), 'name')"
    },
    {
     "target": "alias(sumSeries(#A), 'Суммарно')",
     "targetFull": "alias(sumSeries(aliasByTags(groupByTags(aliasByTags(movingAverage(scale(seriesByTag('name=~carbon.clickhouse.interval-10sec.monitor\\d_unix_tensor_ru.ClickHouse.ProfileEvents.InsertedRows'), 0.05), '1m'), 'host'), 'sum', 'name'), 'name')), 'Суммарно')"
    }
   ]
  },
  {
   "title": "Количество сообщений в секунду",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('host=~lms-kafka-*', 'name=kafka.server_brokertopics_messagesinpersec.Count')), 'host')"
    }
   ]
  },
  {
   "title": "Объем новых сообщений в скунду",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('service=kafka', 'name=kafka.server_brokertopics_bytesinpersec.Count')), 'host')"
    }
   ]
  },
  {
   "title": "Количество соединений",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~lms-kafka-\\d.+', 'name=system.netstat.tcp_established'), 'host')"
    }
   ]
  },
  {
   "title": "Использование CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~lms-kafka-\\d.*', 'name=system.cpu.usage_active', 'cpu=cpu-total'), 'host', 'cpu')"
    }
   ]
  },
  {
   "title": "Использование памяти",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~lms-kafka-\\d*', 'name=system.mem.used_percent'), 'host')"
    }
   ]
  },
  {
   "title": "Disk I\\O read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('host=~lms-kafka-\\d.*', 'name=system.diskio.read_bytes', '_name=~sd.$')), 'host', '_name')"
    }
   ]
  },
  {
   "title": "Load Average 1/5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~lms-kafka-*', 'name=system.system.load1'), 'host', 2)"
    },
    {
     "target": "aliasByTags(seriesByTag('host=~lms-kafka-*', 'name=system.system.load5'), 'host', 2)"
    }
   ]
  },
  {
   "title": "Disk I\\O bytes write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('host=~lms-kafka-\\d.*', 'name=system.diskio.write_bytes', '_name=~sd.$')), 'host', '_name')"
    }
   ]
  },
  {
   "title": "Использование диска",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(exclude(aliasSub(exclude(aliasByTags(seriesByTag('host=~lms-kafka-\\d.*', 'name=system.disk.used_percent'), 'host', 'path'), 'boot'), '', ''), '\\.-$'), '-mnt-', '/mnt/'), '-zk', '/zk')"
    }
   ]
  }
 ]
}