{
 "title": "Мониторинг: статистика хранения и отображения",
 "description": "Ответственный: Новожилов Р.А. и Смирнов К.В. (Эксплуатация)",
 "tags": [
  "telegraf",
  "monitoring",
  "system"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Получено метрик carbon-clickhouse",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "carbon.agents.*.tcp.metricsReceived"
    }
   ]
  },
  {
   "title": "carbon-clickhouse Отправлено байт",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "carbon.agents.*.writer.writtenBytes"
    }
   ]
  },
  {
   "title": "Ошибки на carbon-clickhouse",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "carbon.agents.*.tcp.errors" }
   ]
  },
  {
   "title": "carbonapi-long render_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "perSecond(carbon.api.*.*.render_requests)"
    }
   ]
  },
  {
   "title": "Статистика запросов Grafana",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "carbon.grafana.*.datasource_request_total.*.*.datasource.*.method.get.count"
    }
   ]
  }
 ]
}