{
 "title": "Мониторинг: серверы основного кластера",
 "description": "Ответственный: Новожилов Р.А. и Смирнов К.В. (Эксплуатация)",
 "tags": [
  "telegraf",
  "monitoring",
  "system"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Системные метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Средняя нагрузка",
   "type": "graph",
   "description": "Load Average за одну минуту для серверов хранилищ прода и стендов. Стенды отложены вниз по оси.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(sortByName(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=system.system.load1'), true, false), 'host')"
    },
    {
     "target": "aliasByTags(sortByName(seriesByTag('host=~monitor-tc-\\d.*', 'name=system.system.load1'), true, false), 'host')"
    }
   ]
  },
  {
   "title": "Переключения контекста",
   "type": "graph",
   "description": "Переключение контекста ядра, высокое значение (выше 100к) говорит о том, что система работает нестабильно",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=system.kernel.context_switches', 'host=~monitor\\d.unix.tensor.ru')), 'host')"
    }
   ]
  },
  {
   "title": "Использование памяти",
   "type": "graph",
   "description": "Процент использования оперативной памяти system.mem.used_percent. Нормальными являются значения 40-80%",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=system.mem.used_percent'), 'host'), true)"
    }
   ]
  },
  {
   "title": "Сетевые интерфейсы",
   "type": "graph",
   "description": "Исходящий и входящий потоки данных на серверах хранилищ прода, получение данных отложено вниз",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~system.net.bytes_*', 'host=~monitor\\d.unix.tensor.ru', 'interface=~(bond0.111|eth0)')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Загрузка процессора",
   "type": "graph",
   "description": "Суммарная нагрузка на CPU (cpu.usage_active) и нахождение системы в ожидании ввода/вывода. Iowait откладывается вниз, шкала - справа.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('name=system.cpu.usage_active', 'host=~monitor\\d.unix.tensor.ru', 'cpu=cpu-total'), 'max'), 'host', 'name')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=system.cpu.usage_iowait', 'host=~monitor\\d.unix.tensor.ru', 'cpu=cpu-total'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Занятость разделов с базами",
   "type": "graph",
   "description": "Процент использования всех активных разделов на основных серверах прода",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~system.disk.used_percent', 'host=~monitor\\d.unix.tensor.ru'), 'host', 'path', 'name'), '-', '/')"
    }
   ]
  },
  {
   "title": "Failed Systemd Units",
   "type": "stat",
   "description": "Количество сервисов, находящихся в состоянии failed",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=systemd_units.failed', 'interval=30s'), 'host')"
    }
   ]
  },
  {
   "title": "Операции ввода/вывода",
   "type": "graph",
   "description": "IOPS на дисковой подсистеме основных серверов мониторинга. Чтение отложено вниз по оси",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('name=~system.diskio.(writes|reads)', '_name=~sd\\w$', 'host=~monitor\\d.unix.tensor.ru')), 'host', '_name', 'name'), 0, 4, -1)"
    }
   ]
  },
  {
   "title": "Шина данных",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Кол-во новых сообщений",
     "type": "graph",
     "description": "Распределение поступления сообщений по узлам кластера lms-kafka-{1,2,3} Значительное расхождение графиков между собой - ненормально.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('service=kafka', 'name=kafka.server_brokertopics_messagesinpersec.Count')), 'host')"
      }
     ]
    },
    {
     "title": "Объем новых сообщений",
     "type": "graph",
     "description": "Распределение поступления данных по узлам кластера lms-kafka-{1,2,3}, расхождение среднего траффика более, чем в полтора раза - ненормально",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('service=kafka', 'name=kafka.server_brokertopics_bytesinpersec.Count')), 'host')"
      }
     ]
    },
    {
     "title": "Количество znode",
     "type": "bargauge",
     "description": "Количество записей в журналах репликации и обращений к шине данных. Числа должны быть равными или очень близкими",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('name=zookeeper.znode_count', 'host=~lms-kafka-\\d.unix.tensor.ru'), 'host'), '.unix.tensor.ru', '')"
      }
     ]
    },
    {
     "title": "Insync Followers",
     "type": "stat",
     "description": "Количество синхронизированных последователей. Всегда в штатном режиме должно быть 2, при обновлениях и перезагрузках обязано меняться.",
     "gridPos": { "h": 6, "w": 3, "x": 20, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aggregate(seriesByTag('name=zookeeper.synced_followers', 'host=~lms-kafka-\\d.unix.tensor.ru'), 'sum')"
      }
     ]
    },
    {
     "title": "Открытые соединения на kafka",
     "type": "graph",
     "description": "Открытые сетевые подключения к узлам кластера шины, должны быть сопоставимыми, с перекосом в пределах 10% в пользу мастера кластера.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('host=~lms-kafka-\\d.+', 'name=system.netstat.tcp_established'), 'host')"
      }
     ]
    },
    {
     "title": "Средняя нагрузка",
     "type": "graph",
     "description": "Load Average за одну минуту на серверах шины данных. Неоднородность - норма.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "sortByName(seriesByTag('host=~lms-kafka-\\d.unix.tensor.ru', 'name=system.system.load1'), true, false)"
      }
     ]
    },
    {
     "title": "Время отклика Zookeeper",
     "type": "bargauge",
     "description": "более 200 мс - ненормально. Неравномерность - норма",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(seriesByTag('host=~lms-kafka-\\d.unix.tensor.ru', 'name=~zookeeper.p999_readlatency'), 'host'), true, false)"
      }
     ]
    }
   ]
  },
  {
   "title": "Поставка в хранилище (carbon-clickhouse)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tagged metrics recieved",
     "type": "graph",
     "description": "Количество метрик от скриптов и telegerfa (graphite1.1)",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(scaleToSeconds(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=carbon-clickhouse-tagged.tcp.metricsReceived'), 1), 'host')"
      }
     ]
    },
    {
     "title": "Sbis3mon metrics recieved",
     "type": "graph",
     "description": "Количество полученный в секунду метрик от sbis3mon (graphite1.0)",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(scaleToSeconds(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=carbon-clickhouse.tcp.metricsReceived'), 1), 'host')"
      }
     ]
    },
    {
     "title": "Bytes written",
     "type": "graph",
     "description": "Поток записи в clickhouse",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(aliasSub(aliasByTags(scaleToSeconds(groupByTags(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=~carbon-clickhouse.*.writer.writtenBytes'), 'sum', 'name'), 1), 'name'), '.unix.tensor.ru', ''), '.writer.writtenBytes', '')"
      }
     ]
    },
    {
     "title": "Tagged metrics dropped",
     "type": "graph",
     "description": "Количество тэгированных метрик отброшенных фильтром, как несоответствующие поставки данных",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(scaleToSeconds(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=~carbon-clickhouse-tagged.tcp..*Dropped'), 1), 'host')"
      }
     ]
    },
    {
     "title": "Sbis3mon metrics dropped",
     "type": "graph",
     "description": "Количество нетэгированных метрик (sbis3mon) отброшенных фильтром, как несоответствующие поставки данных",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(scaleToSeconds(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=~carbon-clickhouse.tcp..*Dropped'), 1), 'host')"
      }
     ]
    }
   ]
  },
  { "title": "Хранилище (clickhouse)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Поступление значений в хранилища",
   "type": "graph",
   "description": "Индивидуальное по хранилищам и суммарное (RowsTotal) поступление данных (INSERT)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByTags(scale(perSecond(seriesByTag('name=clickhouse_events.inserted_rows', 'host=~monitor\\d.unix.tensor.ru')), 0.5), 'host')"
    },
    {
     "target": "alias(sumSeries(#A), 'RowsTotal')",
     "targetFull": "alias(sumSeries(aliasByTags(scale(perSecond(seriesByTag('name=clickhouse_events.inserted_rows', 'host=~monitor\\d.unix.tensor.ru')), 0.5), 'host')), 'RowsTotal')"
    }
   ]
  },
  {
   "title": "Clickhouse connections",
   "type": "graph",
   "description": "Открытые соединения к серверам (не должно быть большим): graphite-clickhouse.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~clickhouse_metrics..*_connection', 'host=~monitor\\d.unix.tensor.ru'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Объединения данных Clickhouse",
   "type": "graph",
   "description": "Идущие в данный момент процессы объединения данных и колисчество строк, объединяемых этими мерджами (вниз - количество процессов)",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Rows count" }
   ],
   "targets": [
    {
     "target": "perSecond(seriesByTag('name=clickhouse_events.merged_rows', 'host=~monitor\\d.unix.tensor.ru'))"
    },
    {
     "target": "seriesByTag('name=clickhouse_metrics.merge', 'host=~monitor\\d.unix.tensor.ru')"
    }
   ]
  },
  {
   "title": "Clickhouse Queries",
   "type": "graph",
   "description": "Количество процессов вставки и запросов на чтение к БД. Запись - вниз от оси.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=clickhouse_events.insert_query', 'host=~monitor\\d.unix.tensor.ru')), 'host', 'name')"
    },
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=clickhouse_events.select_query', 'host=~monitor\\d.unix.tensor.ru')), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Время отклика Zookeeper",
   "type": "bargauge",
   "description": "среднее время доступа к данным zookeeper, оптимальная величина - в предела 20 мс.",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=zookeeper.avg_latency'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Количество znode",
   "type": "bargauge",
   "description": "Количество записей о репликах и количестве parts в базах. Не должно быть резкого роста",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=zookeeper.znode_count', 'host=~monitor\\d.unix.tensor.ru'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Clickouse ZK Followers",
   "type": "stat",
   "description": "Синхронность узлов кластера. Должно быть 2 в штатном состоянии и обязано меняться при перезагрузках/обновлениях.",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "groupByTags(seriesByTag('name=zookeeper.synced_followers', 'host=~monitor\\d.unix.tensor.ru'), 'sum', 'name')"
    }
   ]
  },
  {
   "title": "Представление (carbonapi+graphite-clickhouse)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Render requests",
     "type": "graph",
     "description": "Поток запросов на предоставление точек данных",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "perSecond(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=carbonapi.render_requests'))"
      }
     ]
    },
    {
     "title": "Request cache hits",
     "type": "graph",
     "description": "Использование кэша на верхнем уровне представления данныхуровне.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=carbonapi.request_cache_hits')), 'host', 'service', 'name')"
      },
      {
       "target": "aliasByTags(perSecond(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=carbonapi.request_cache_misses')), 'host', 'service', 'name')"
      }
     ]
    }
   ]
  },
  {
   "title": "Отображение (Grafana)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Datasource requests",
     "type": "graph",
     "description": "Распределение запросов по источникам данных без привязки к узлу",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByTags(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=grafana.datasource_request_total'), 'sum', 'datasource')"
      }
     ]
    },
    {
     "title": "Datasource requests",
     "type": "graph",
     "description": "Распределение запросов по узлам",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByTags(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=grafana.datasource_request_total', 'code=200'), 'sum', 'host')"
      }
     ]
    },
    {
     "title": "HTTP requests",
     "type": "graph",
     "description": "Распределение HTTP запросов по источникам",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByTags(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=grafana.http_request_total'), 'sum', 'datasource')"
      }
     ]
    },
    {
     "title": "Datasource request duration",
     "type": "graph",
     "description": "Лаг получения ответов на запросы с распределением по источникам",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByTags(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=grafana.datasource_request_duration_seconds_count', 'method=get'), 'sum', 'datasource')"
      }
     ]
    },
    {
     "title": "Datasource requests queue",
     "type": "graph",
     "description": "Количество одновременно обрабатываемых запросов с распределением по источникам",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByTags(seriesByTag('host=~monitor\\d.unix.tensor.ru', 'name=grafana.datasource_request_in_flight'), 'sum', 'datasource')"
      }
     ]
    }
   ]
  }
 ]
}