{
 "title": "Мониторинг: статистика агентов сбора telegraf",
 "description": "Ответственный: Новожилов Р.А. и Смирнов К.В. (Эксплуатация)",
 "tags": [
  "telegraf",
  "monitoring",
  "system"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "tag_values(host,name=internal_agent.metrics_gathered)"
   }
  ]
 },
 "panels": [
  {
   "title": "Gathered/Written total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~internal_agent.metrics_gathered', 'host=$host')), 'service_name', 'service', 'name')"
    },
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~internal_agent.metrics_written', 'host=$host')), 'service_name', 'service', 'name')"
    },
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~internal_agent.metrics_dropped', 'host=$host')), 'service_name', 'service', 'name')"
    }
   ]
  },
  {
   "title": "Dropped metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~internal_agent.metrics_dropped', 'host=$host')), 'service_name', 'service', 'name')"
    }
   ]
  },
  {
   "title": "Gathered count by input",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~internal_gather.metrics_gathered', 'host=$host')), 'input', 'service_name')"
    }
   ]
  },
  {
   "title": "Errors by source",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~internal_gather.errors', 'host=$host')), 'input', 'service_name')"
    },
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~internal_write.errors', 'host=$host')), 'output', 'service_name')"
    }
   ]
  },
  {
   "title": "Gather time by input",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~internal_gather.gather_time_ns', 'host=$host'), 'input', 'service_name')"
    }
   ]
  },
  {
   "title": "Written metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~internal_write.metrics_written', 'host=$host')), 'output', 'service_name')"
    }
   ]
  },
  {
   "title": "Buffer size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~internal_write.buffer_size', 'host=$host'), 'output', 'service_name', 'service')"
    }
   ]
  },
  {
   "title": "Write time by output",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~internal_write.write_time_ns', 'host=$host'), 'output', 'service_name')"
    }
   ]
  }
 ]
}