{
 "title": "Параметры csr-adm-upd",
 "description": "Ответственный:  Смирнов К.В. (Эксплуатация)",
 "tags": [
  "exploitation",
  "telegraf",
  "service"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Количество балансировщиков ",
   "type": "stat",
   "description": "Количество балансировщиков  update.sbis.ru",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=balancers.count', 'service=update.sbis.ru', 'role=master', 'host=csr-adm-upd.unix.tensor.ru'), 'host')"
    }
   ]
  },
  {
   "title": "Количество зеркал",
   "type": "stat",
   "description": "Количество зеркал (за исключением локальных и cdn)",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=mirrors.count', 'service=update.sbis.ru', 'role=master', 'host=csr-adm-upd.unix.tensor.ru'), 'host')"
    }
   ]
  },
  {
   "title": "Количество CDN",
   "type": "stat",
   "description": "Количество внешних CDN",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=cdn.count', 'service=update.sbis.ru', 'role=master', 'host=csr-adm-upd.unix.tensor.ru'), 'host')"
    }
   ]
  },
  {
   "title": "Очистка кэша CDN ",
   "type": "stat",
   "description": "Проверка очистки кэша внешнего CDN после выкладки",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=clear_cache.check', 'service=update.sbis.ru', 'role=master', 'host=csr-adm-upd.unix.tensor.ru'), 'host')"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "stat",
   "description": "Статус работы redis на csr-adm-upd",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=redis.check', 'service=update.sbis.ru', 'role=master', 'host=csr-adm-upd.unix.tensor.ru'), 'host')"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "description": "Статус работы MySQL на csr-adm-upd ",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=mysql.check', 'service=update.sbis.ru', 'role=master', 'host=csr-adm-upd.unix.tensor.ru'), 'host')"
    }
   ]
  },
  {
   "title": "sync check",
   "type": "graph",
   "description": "Отображение активной синхронизации папок на update.sbis.ru",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=sync.check', 'service=update.sbis.ru', 'role=master', 'host=csr-adm-upd.unix.tensor.ru'), 'host')"
    }
   ]
  }
 ]
}