{
 "title": "Панели отображения одиночных метрик",
 "description": "Ответственный: Новожилов Р.А. (Эксплуатация)",
 "tags": [
  "telegraf",
  "service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Ошибки планировщика",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "seriesByTag('name=scheduler.task.count', 'script=sheduler_mon.py')"
    }
   ]
  },
  {
   "title": "Node_app.js process count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=node_app.js', 'servertype=videocall'), 'host')"
    }
   ]
  },
  {
   "title": "Частота вызовов метода Ereports.PerformEvent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.sbis3app.statistikaOblaka.csr-planned-events-bl{1,2}.sbis3.10081.interval-600sec.sbis3.method.calls.Ereports.PerformEvent.raw, -10)"
    }
   ]
  },
  {
   "title": "recorder.js process count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=node_recorder.js', 'servertype=videocall'), 'host')"
    }
   ]
  },
  {
   "title": "Вызовы сервисов",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('script=cloud_calls_count.py', 'name=service.calls_count', 'interval=86400s'), 'service')"
    }
   ]
  },
  {
   "title": "состояние сервисов webinars и webinars-ps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~procstat.sbis-webinar_service.*running', 'servertype=~(webinars|webinar-static)'), 'systemd_unit','host')"
    }
   ]
  },
  {
   "title": "Среднее время PlannedEvents.GetEvents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.sbis3app.statistikaOblaka.csr-planned-events-bl3.sbis3.10081.interval-600sec.sbis3.method.avgtimeday.PlannedEvents.GetEvents.raw, -10, -3, -2)"
    }
   ]
  },
  {
   "title": "Число вызовов метода ЭДО.ИнформацияОСлужебныхЭтапах на ea1-signature2",
   "type": "graph",
   "description": "https://adm-git.tensor.ru/exp/monitoring-scripts/montools/-/blob/master/scripts/method_call_count_sign.py",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=method.request.count', 'contur=prod', 'host=ea1-signature2', 'interval=900s', 'script=method_call_count_sign.py'), 'host', 'method')"
    }
   ]
  },
  {
   "title": "Внешняя переписка",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=response.time', 'site=socnet-aggregation.sbis.ru'), 'site')"
    }
   ]
  },
  {
   "title": "Число вызовов методов проблем по биометрии и заявкам",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=method.request.count', 'contur=prod', 'method=~.+', 'interval=300s'), 'method')"
    }
   ]
  },
  {
   "title": "Длина очереди сценариев \"Проверка документов\"",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.scenario', 'service=checkxml3', 'contur=prod'), 'name')"
    }
   ]
  },
  {
   "title": "Ошибки отправки пакетов оператору ГИС МТ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('type=motp', 'name=roaming-edo.tasks.errors'), 'name')"
    }
   ]
  },
  {
   "title": "Проблемные задачи сервиса clients-filtering",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=tasks.count', 'service=clients-filtering', 'contur=prod'), 'tasks')"
    }
   ]
  },
  {
   "title": "Количество доставленных за день почтовых сообщений",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=DeliveredTodayEmailsCount', 'contur=prod'), 'Emails')"
    }
   ]
  },
  {
   "title": "Состояние оффлайн-выпуска",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s", "label": "Задержка" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=offline.requests', 'contur=prod', 'subsystem=uc'), 'name')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=offline.requests.lag', 'contur=prod', 'subsystem=uc'), 'name')"
    }
   ]
  },
  {
   "title": "Число пользователей на ботах telegram-service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=user.count', 'service=telegram-service', 'bot_name=~.+'), 'bot_name')"
    }
   ]
  },
  {
   "title": "Наличие ошибок отправки пакетов оператору ГИС МТ",
   "type": "graph",
   "description": "Для alert pmd-transport.errors_on_send. Срабатывает при значениии > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=errors_on_send_to_pmd', 'servicetype=pmd-transport', 'contur=prod'), 'name')"
    }
   ]
  },
  {
   "title": "Число сообщений на ботах telegram-service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=message.count', 'service=telegram-service', 'bot_name=~.+'), 'bot_name')"
    }
   ]
  },
  {
   "title": "Таблица сайта sbis.ru  \"Разрешен доступ к ресурсам компании «Тензор»\" ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('script=check_ip_change.py', 'contur=prod', 'subsystem=teh_terms'), 'name')"
    }
   ]
  },
  {
   "title": "Время до истекания ssl сертификатов диспетчеров ",
   "type": "graph",
   "description": "триггер dispatch.ssl.expire. 60 дней (8.57 недель) - момент, когда загорается триггер. Задача - добиться, чтобы на этом графике не было диспетчеров с сертами меньше 60 дней.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "target": "limit(sortByMinima(groupByNodes(sbis3mon.prod.sbis3dispatcher.cert.*.sbis3disp.*.sbis3disp.cert.*.pem.days, 'min', 4, 9)), 20)"
    }
   ]
  },
  {
   "title": "vcall-sip-gateway",
   "type": "graph",
   "description": "Не обнаружен процесс vcall-sip-gateway, если значение 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=vcall', 'servertype=vcall-sip-gateway'), 'host')"
    }
   ]
  },
  {
   "title": "Статус службы ralph на asset.mgmt.tensor.ru",
   "type": "graph",
   "description": "Если значение 1 => running. \nЕсли значение 0 => not running.\nТриггер asset.mgmt_ralph.service срабатыват при значении 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=asset.mgmt.tensor.ru', 'name=procstat_lookup.running', 'systemd_unit=ralph.service'), 'host', 'systemd_unit')"
    }
   ]
  },
  {
   "title": "sequence_limits_is_depleting",
   "type": "graph",
   "description": "Сервис database-maintenance\n> \nhttps://online.sbis.ru/opendoc.html?guid=c26e22d9-b252-4553-aa9e-9a06bd93f027\n> Метрика имеет два значения 0.0 - ошибок нет и 1.0 - есть ошибка.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "seriesByTag('name=sequence_limits_is_depleting')"
    }
   ]
  },
  {
   "title": "Статус состояния cdn G-Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('script=gcore_cdn.py', 'contur=prod', 'service=gcore'), 'name')"
    }
   ]
  },
  {
   "title": "SSL-cert ",
   "type": "stat",
   "description": "'name=x509_cert.expiry', 'common_name=-.wasaby.dev'",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=x509_cert.expiry', 'common_name=-.wasaby.dev', 'host=dts-speedtest.unix.tensor.ru'), 'name')"
    }
   ]
  },
  {
   "title": "Максимальное время выполнения метода EOMEventSync.GetData",
   "type": "timeseries",
   "description": "Максимальное время выполнения метода EOMEventSync.GetData",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=method.time.max', 'method=EOMEventSync.GetData'), 'method')"
    }
   ]
  },
  {
   "title": "SSL-cert   -.tensor.ru",
   "type": "stat",
   "description": "'name=x509_cert.expiry',\n 'common_name=-.tensor.ru'",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=x509_cert.expiry', 'common_name=-.tensor.ru', 'host=dts-ncms-backuper.mgmt.tensor.ru'), 'name')"
    }
   ]
  },
  {
   "title": "Sequence Database",
   "type": "timeseries",
   "description": "Показывает секвенции https://online.sbis.ru/opendoc.html?guid=c26e22d9-b252-4553-aa9e-9a06bd93f027\nПуляется напрямую платформами",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "seriesByTag('name=sequence_limits_is_depleting', 'contur=prod')"
    }
   ]
  },
  {
   "title": "Блокировки входов пользователей",
   "type": "timeseries",
   "description": "Показывает кол-во заблокированных пользователей с разными причинами.\n\n\"Вход заблокирован по логину\": \"blocked_by_login\",\n\n\"Вход заблокирован по ip\": \"blocked_by_ip\",\n\n\"Вход заблокирован по логину+ip\": \"blocked_by_login_and_ip\",\n\n\"Ввод неправильного пароля\": \"wrong_password\",\n\n\"Незарегистрированный пользователь\": \"unregistered_user\",\n\n\"Пользователь заблокирован\": \"user_is_blocked\",\n\n\"Устройство заблокировано\": \"device_is_blocked\",\n\n\"IP-адрес заблокирован\": \"ip_is_blocked\",\n\n\"Клиент утилизирован\": \"client_is_disposed\",\n\n\"Ограничение по временному интервалу\": \"time_limit\",\n\n\"Неверно ввели номер аккаунта для пользователя\": \"wrong_user_account\",\n\n\"Другое\": \"other_reason\"\n\n\nСбор скриптом https://adm-git.tensor.ru/exp/monitoring-scripts/montools/-/blob/master/scripts/cloud_failing_auth_stats.py",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(seriesByTag('name=cloud_failing_auth_stats', 'contur=prod', 'script=cloud_failing_auth_stats.py'), 'reason'))"
    }
   ]
  }
 ]
}