{
 "title": "Резервное копирование Elastic (backup)",
 "description": "Ответственный: -",
 "tags": [
  "backup",
  "telegraf",
  "elasticsearch",
  "service"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "cluster",
    "query": "tag_values(cluster_name,contur=$contur,servertype=elasticsearch,script=DPC_elastic_backup.py)"
   }
  ]
 },
 "panels": [
  {
   "title": "Состояние бекапа кластера",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=elastic-backup.status', 'servertype=elasticsearch', 'contur=~${contur:regex}', 'script=DPC_elastic_backup.py'), 'cluster_name')"
    }
   ]
  },
  {
   "title": "Время завершения последнего бекапа",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(scale(seriesByTag('name=elastic-backup.end_epoch', 'servertype=elasticsearch', 'contur=~${contur:regex}', 'script=DPC_elastic_backup.py'), 1000), 'cluster_name')"
    }
   ]
  },
  {
   "title": "Очередь бекапа шардов ",
   "type": "graph",
   "description": "Суммарный графиг очередей бекапа шардов. По пересечению можно оценить есть ли одновременный бекап или нет.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "consolidateBy(groupByNodes(aliasByTags(seriesByTag('name=service.elastic.snapshot_queue', 'servertype=elasticsearch', 'contur=~${contur:regex}', 'cluster_name=~${cluster:regex}'), 'cluster_name'), 'sum', 0), 'maximum')"
    }
   ]
  },
  {
   "title": "$cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 18 },
   "repeat": "cluster",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('cluster_name=$cluster', 'name=elastic-backup.backuptime', 'script=DPC_elastic_backup.py', 'servertype=elasticsearch'), 'Duration backup (sec)')"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('cluster_name=$cluster', 'name=elastic-backup.failed_shards', 'script=DPC_elastic_backup.py', 'servertype=elasticsearch'), 'name'), 1)"
    }
   ]
  },
  {
   "title": "$cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('cluster_name=$cluster', 'name=elastic-backup.backuptime', 'script=DPC_elastic_backup.py', 'servertype=elasticsearch'), 'Duration backup (sec)')"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('cluster_name=$cluster', 'name=elastic-backup.failed_shards', 'script=DPC_elastic_backup.py', 'servertype=elasticsearch'), 'name'), 1)"
    }
   ]
  },
  {
   "title": "$cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('cluster_name=$cluster', 'name=elastic-backup.backuptime', 'script=DPC_elastic_backup.py', 'servertype=elasticsearch'), 'Duration backup (sec)')"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('cluster_name=$cluster', 'name=elastic-backup.failed_shards', 'script=DPC_elastic_backup.py', 'servertype=elasticsearch'), 'name'), 1)"
    }
   ]
  },
  {
   "title": "$cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('cluster_name=$cluster', 'name=elastic-backup.backuptime', 'script=DPC_elastic_backup.py', 'servertype=elasticsearch'), 'Duration backup (sec)')"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('cluster_name=$cluster', 'name=elastic-backup.failed_shards', 'script=DPC_elastic_backup.py', 'servertype=elasticsearch'), 'name'), 1)"
    }
   ]
  },
  {
   "title": "$cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('cluster_name=$cluster', 'name=elastic-backup.backuptime', 'script=DPC_elastic_backup.py', 'servertype=elasticsearch'), 'Duration backup (sec)')"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('cluster_name=$cluster', 'name=elastic-backup.failed_shards', 'script=DPC_elastic_backup.py', 'servertype=elasticsearch'), 'name'), 1)"
    }
   ]
  },
  {
   "title": "$cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('cluster_name=$cluster', 'name=elastic-backup.backuptime', 'script=DPC_elastic_backup.py', 'servertype=elasticsearch'), 'Duration backup (sec)')"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('cluster_name=$cluster', 'name=elastic-backup.failed_shards', 'script=DPC_elastic_backup.py', 'servertype=elasticsearch'), 'name'), 1)"
    }
   ]
  },
  {
   "title": "$cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('cluster_name=$cluster', 'name=elastic-backup.backuptime', 'script=DPC_elastic_backup.py', 'servertype=elasticsearch'), 'Duration backup (sec)')"
    },
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('cluster_name=$cluster', 'name=elastic-backup.failed_shards', 'script=DPC_elastic_backup.py', 'servertype=elasticsearch'), 'name'), 1)"
    }
   ]
  },
  { "title": "$cluster графики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "cluster" },
  {
   "title": "активность снапшотов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=~service.elastic.(snapshot_active|snapshot_largest|snapshot_rejected|snapshot_threads)', 'cluster_name=~${cluster:regex}'), 'host', 'name'), 0, -1), 'maximum')"
    }
   ]
  },
  {
   "title": "очередь бекапа шардов ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=~service.elastic.snapshot_queue', 'cluster_name=~${cluster:regex}'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  {
   "title": "общее кол-во забекапленых шардов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'cluster_name=~${cluster:regex}', 'name=~service.elastic.snapshot_completed'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  { "title": "$cluster графики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "активность снапшотов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=~service.elastic.(snapshot_active|snapshot_largest|snapshot_rejected|snapshot_threads)', 'cluster_name=~${cluster:regex}'), 'host', 'name'), 0, -1), 'maximum')"
    }
   ]
  },
  {
   "title": "очередь бекапа шардов ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=~service.elastic.snapshot_queue', 'cluster_name=~${cluster:regex}'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  {
   "title": "общее кол-во забекапленых шардов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'cluster_name=~${cluster:regex}', 'name=~service.elastic.snapshot_completed'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  { "title": "$cluster графики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "активность снапшотов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=~service.elastic.(snapshot_active|snapshot_largest|snapshot_rejected|snapshot_threads)', 'cluster_name=~${cluster:regex}'), 'host', 'name'), 0, -1), 'maximum')"
    }
   ]
  },
  {
   "title": "очередь бекапа шардов ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=~service.elastic.snapshot_queue', 'cluster_name=~${cluster:regex}'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  {
   "title": "общее кол-во забекапленых шардов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'cluster_name=~${cluster:regex}', 'name=~service.elastic.snapshot_completed'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  { "title": "$cluster графики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "активность снапшотов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=~service.elastic.(snapshot_active|snapshot_largest|snapshot_rejected|snapshot_threads)', 'cluster_name=~${cluster:regex}'), 'host', 'name'), 0, -1), 'maximum')"
    }
   ]
  },
  {
   "title": "очередь бекапа шардов ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=~service.elastic.snapshot_queue', 'cluster_name=~${cluster:regex}'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  {
   "title": "общее кол-во забекапленых шардов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'cluster_name=~${cluster:regex}', 'name=~service.elastic.snapshot_completed'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  { "title": "$cluster графики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "активность снапшотов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=~service.elastic.(snapshot_active|snapshot_largest|snapshot_rejected|snapshot_threads)', 'cluster_name=~${cluster:regex}'), 'host', 'name'), 0, -1), 'maximum')"
    }
   ]
  },
  {
   "title": "очередь бекапа шардов ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=~service.elastic.snapshot_queue', 'cluster_name=~${cluster:regex}'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  {
   "title": "общее кол-во забекапленых шардов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'cluster_name=~${cluster:regex}', 'name=~service.elastic.snapshot_completed'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  { "title": "$cluster графики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "активность снапшотов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=~service.elastic.(snapshot_active|snapshot_largest|snapshot_rejected|snapshot_threads)', 'cluster_name=~${cluster:regex}'), 'host', 'name'), 0, -1), 'maximum')"
    }
   ]
  },
  {
   "title": "очередь бекапа шардов ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=~service.elastic.snapshot_queue', 'cluster_name=~${cluster:regex}'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  {
   "title": "общее кол-во забекапленых шардов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'cluster_name=~${cluster:regex}', 'name=~service.elastic.snapshot_completed'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  { "title": "$cluster графики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "активность снапшотов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=~service.elastic.(snapshot_active|snapshot_largest|snapshot_rejected|snapshot_threads)', 'cluster_name=~${cluster:regex}'), 'host', 'name'), 0, -1), 'maximum')"
    }
   ]
  },
  {
   "title": "очередь бекапа шардов ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'name=~service.elastic.snapshot_queue', 'cluster_name=~${cluster:regex}'), 'host', 'name'), 0, -1)"
    }
   ]
  },
  {
   "title": "общее кол-во забекапленых шардов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasByTags(seriesByTag('contur=~${contur:regex}', 'cluster_name=~${cluster:regex}', 'name=~service.elastic.snapshot_completed'), 'host', 'name'), 0, -1)"
    }
   ]
  }
 ]
}