{
 "title": "СКУД",
 "description": "Сервис контроля доступа. Ответственный: Смирнов К.В. (Эксплуатация)",
 "tags": [
  "service",
  "scripts",
  "СКУД",
  "exploitation"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Активность СБИС-плагина",
   "type": "graph",
   "description": "Время последней активности СБИС-плагина для ОрионПро",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=skud.activity', 'skud=~.+'), 'skud')"
    }
   ]
  },
  {
   "title": "Количество задач в плохом состоянии",
   "type": "graph",
   "description": "Количество задач в плохом состоянии в ОрионПро",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=skud.badjobs.count', 'skud=~.+'), 'skud')"
    }
   ]
  },
  {
   "title": "Количество событий в минуту",
   "type": "graph",
   "description": "Количество событий в минуту ОринПро",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=skud.events.count', 'skud=~.+'), 'skud')"
    }
   ]
  }
 ]
}