{
 "title": "Состояние обновлений admin.sbis.ru",
 "description": "Ответственный: Смирнов К.В. (Эксплуатация)",
 "tags": [
  "exploitation",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "Подготовка",
   "type": "table",
   "description": "Обновления в admin.sbis.ru на фазе подготовки",
   "gridPos": { "h": 23, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "currentAbove(aliasByTags(seriesByTag('contur=prod', 'name=update.state', 'phase=prepare', 'subsystem=asr'), 'service', 'update_type'), 0)"
    }
   ]
  },
  {
   "title": "Обновление",
   "type": "table",
   "description": "Обновления в admin.sbis.ru на фазе обновление",
   "gridPos": { "h": 23, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "currentAbove(aliasByTags(seriesByTag('contur=prod', 'name=update.state', 'phase=update', 'subsystem=asr'), 'service', 'update_type'), 0)"
    }
   ]
  },
  {
   "title": "Ошибки",
   "type": "table",
   "description": "Ошибки обновления в admin.sbis.ru ",
   "gridPos": { "h": 23, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "currentAbove(aliasByTags(seriesByTag('contur=prod', 'name=update.state', 'phase=error', 'subsystem=asr'), 'service', 'update_type'), 0)"
    }
   ]
  }
 ]
}