{
 "title": "Телефония - System_screen",
 "description": "Сервис видеосвязи. Ответственный: Конюхов М.В. (Эксплуатация)",
 "tags": [
  "exploitation",
  "service",
  "scripts",
  "mv.konuhov",
  "телефония",
  "telephony"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.sbis3app.info.*"
   },
   { "name": "domain", "label": "Домен", "query": "*.tensor.ru" },
   {
    "name": "port",
    "label": "Порт",
    "query": "sbis3mon.$contur.sbis3app.status.$server.sbis3.*"
   },
   {
    "name": "service",
    "label": "Сервис",
    "query": "sbis3mon.$contur.sbis3app.*.*.sbis3.*.*.sbis3.service.workers.free.*"
   },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  { "title": "Платформенное", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Очереди Telephony",
   "type": "graph",
   "description": "Очереди БЛ Telephony",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=queue.size', 'service=~.*elephony.+', 'host!=~.+', 'type=work'), 'service', 'type'), 'work', 'основная')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=queue.size', 'service=~.*elephony.+', 'host!=~.+', 'type=special'), 'service', 'type'), 'special', 'служебная')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=queue.size', 'service=contact_router', 'host!=~.+', 'type=special'), 'service', 'type'), 'special', 'служебная')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=queue.size', 'service=~.*PBX Admin.*', 'host!=~.+', 'type=special'), 'service', 'type'), 'special', 'служебная')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=queue.size', 'service=~.*PBX Admin.*', 'host!=~.+', 'type=work'), 'service', 'type'), 'work', 'основная')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=queue.size', 'service=contact_router', 'host!=~.+', 'type=work'), 'service', 'type'), 'work', 'основная')"
    }
   ]
  },
  {
   "title": "Очереди inside.tensor.ru",
   "type": "graph",
   "description": "Очереди БЛ сервиса inside",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=queue.size', 'service=~.*inside.+', 'host!=~.+', 'type=work'), 'service', 'type'), 'work', 'основная')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=queue.size', 'service=~.*inside.+', 'host!=~.+', 'type=special'), 'service', 'type'), 'special', 'служебная')"
    }
   ]
  },
  {
   "title": "Использование воркеров /telephony/service/",
   "type": "graph",
   "description": "Использование воркеров /telephony/service/",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "max 100%" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info.*.sbis3.$port.*.sbis3.service.workers.used._2Ftelephony_2Fservice_2F.pct.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info_srv.*.sbis3.$port.*.sbis3.service.workers.used._2Ftelephony_2Fservice_2F_5Fsrv.pct.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
    }
   ]
  },
  {
   "title": "Использование воркеров /tel-configs/service/",
   "type": "graph",
   "description": "Использование воркеров /tel-configs/service/",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "max 100%" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info.*.sbis3.$port.*.sbis3.service.workers.used._2Ftel-configs_2Fservice_2F.pct.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info_srv.*.sbis3.$port.*.sbis3.service.workers.used._2Ftel-configs_2Fservice_2F_5Fsrv.pct.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
    }
   ]
  },
  {
   "title": "Использование воркеров /tel-mon/service/",
   "type": "graph",
   "description": "Использование воркеров /tel-mon/service/",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent", "label": "max 100%" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info.*.sbis3.$port.*.sbis3.service.workers.used._2Ftel-mon_2Fservice_2F.pct.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info_srv.*.sbis3.$port.*.sbis3.service.workers.used._2Ftel-mon_2Fservice_2F_5Fsrv.pct.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
    }
   ]
  },
  {
   "title": "Использование воркеров /pbx-admin/service/",
   "type": "graph",
   "description": "Использование воркеров /pbx-admin/service/",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent", "label": "max 100%" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info.*.sbis3.$port.*.sbis3.service.workers.used._2Fpbx-admin_2Fservice_2F.pct.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info_srv.*.sbis3.$port.*.sbis3.service.workers.used._2Fpbx-admin_2Fservice_2F_5Fsrv.pct.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
    }
   ]
  },
  {
   "title": "Использование воркеров /tel-infrastructure/service/",
   "type": "graph",
   "description": "Использование воркеров /tel-infrastructure/service/",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent", "label": "max 100%" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info.*.sbis3.$port.*.sbis3.service.workers.used._2Ftel-infrastructure_2Fservice_2F.pct.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info_srv.*.sbis3.$port.*.sbis3.service.workers.used._2Ftel-infrastructure_2Fservice_2F_5Fsrv.pct.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
    }
   ]
  },
  {
   "title": "Использование воркеров /contact_router/service/",
   "type": "graph",
   "description": "Использование воркеров /contact_router/service/",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percent", "label": "max 100%" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info.*.sbis3.$port.*.sbis3.service.workers.used._2Ftel-control_2Fservice_2F.pct.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info_srv.*.sbis3.$port.*.sbis3.service.workers.used._2Ftel-control_2Fservice_2F_5Fsrv.pct.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
    }
   ]
  },
  {
   "title": "Использование воркеров /tel-control/service/",
   "type": "graph",
   "description": "Использование воркеров /tel-control/service/",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent", "label": "max 100%" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info.*.sbis3.$port.*.sbis3.service.workers.used._2Ftel-control_2Fservice_2F.pct.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.sbis3app.info_srv.*.sbis3.$port.*.sbis3.service.workers.used._2Ftel-control_2Fservice_2F_5Fsrv.pct.$aggr, 4, 6, 12), '(_2F|_5F)', ' ')"
    }
   ]
  },
  {
   "title": "csr-telephony-db1 разделы",
   "type": "graph",
   "description": "csr-telephony-db1 разделы",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.partition.csr-telephony-db1.*.partition.volume._2F.used.raw, 4, 7, 8), '_2F', '/')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.partition.csr-telephony-db1.*.partition.volume.*pgsql*.*.used.raw, 4, 7, 8, 9), '_2F', '/')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.partition.csr-telephony-db1.*.partition.inode._2F.used.raw, 4, 7, 8, 9), '_2F', '/')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.partition.csr-telephony-db1.*.partition.inode.*pgsql*.*.used.raw, 4, 7, 8, 9), '_2F', '/')"
    }
   ]
  },
  {
   "title": "osr-telephony-infrastructure-db1 разделы",
   "type": "graph",
   "description": "osr-telephony-infrastructure-db1 разделы",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.partition.osr-telephony-infrastructure-db1.*.partition.volume._2F.used.raw, 4, 7, 8), '_2F', '/')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.partition.osr-telephony-infrastructure-db1.*.partition.volume.*data*.used.raw, 4, 7, 8, 9), '_2F', '/')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.partition.osr-telephony-infrastructure-db1.*.partition.inode._2F.used.raw, 4, 7, 8, 9), '_2F', '/')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.partition.osr-telephony-infrastructure-db1.*.partition.inode.*data*.used.raw, 4, 7, 8, 9), '_2F', '/')"
    }
   ]
  },
  { "title": "СПД и другое", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Конфигурация АТС in_work_tasks_dir",
   "type": "graph",
   "description": "Данные из редис серверов, где располагается контейнер tensor_configurator\nВыводит значения ключа configurator:in_work",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'script=tel_configurator_monitoring_tasks.py', 'key=conf_in_work_key'), 'host')"
    }
   ]
  },
  {
   "title": "Конфигурация АТС conf_stuck_key",
   "type": "graph",
   "description": "Данные из редис серверов, где располагается контейнер tensor_configurator\nВыводит количество записей в ключе configurator:stuck (ключ не числовой, а список значений)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'script=tel_configurator_monitoring_tasks.py', 'key=conf_stuck_key'), 'host')"
    }
   ]
  },
  {
   "title": "Конфигурация АТС failed_tasks_dir",
   "type": "graph",
   "description": "Данные из редис серверов, где располагается контейнер tensor_configurator\nВыводит разницу между значениями ключа configurator:total и configurator:in_work",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(diffSeriesLists(seriesByTag('contur=prod', 'script=tel_configurator_monitoring_tasks.py', 'key=conf_total_key'), #A), 'host')",
     "targetFull": "aliasByTags(diffSeriesLists(seriesByTag('contur=prod', 'script=tel_configurator_monitoring_tasks.py', 'key=conf_total_key'), aliasByTags(seriesByTag('contur=prod', 'script=tel_configurator_monitoring_tasks.py', 'key=conf_in_work_key'), 'host', 'key')), 'host')"
    }
   ]
  },
  {
   "title": "Кол-во свободных IP по сетям",
   "type": "stat",
   "description": "Количество оставшихся IP в подсетях, используемых в telephony-infrastructure. Если IP не осталось - значит разворачивать АТС не на чем.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'script=tel_subnet_monitoring.py', 'service=telephony-infrastructure', 'name=tel_subnet_monitoring.addresses.free'), 'subnet')"
    }
   ]
  },
  {
   "title": "Кол-во ошибок генерации схем вызовов",
   "type": "graph",
   "description": "Количество ошибочных генераций схем вызовов. -1 - нет ключа в редисе (может означать что ошибок не было и ключ ниразу не записали). 0 - норма. >10 - плохо.\ntel_scheme_generation_errors\nhttps://dpc-docs.tensor.ru/x/fR2-Ag",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'script=tel_scheme_generation_errors.py'), 'host')"
    }
   ]
  },
  {
   "title": "Автодозвон autocall_clients_call_queue",
   "type": "graph",
   "description": "Данные из редис серверов, где располагается контейнер tensor_autocall*\nhttps://dpc-docs.tensor.ru:8443/pages/viewpage.action?pageId=32186530",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'script=tel_autocall_monitoring.py', 'name=tel.autocall.monitoring', 'key=autocall_clients_call_queue'), 'host')"
    }
   ]
  },
  {
   "title": "Автодозвон autocall_workers_amount",
   "type": "graph",
   "description": "Количество свободных воркеров\nДанные из редис серверов, где располагается контейнер tensor_autocall*\nhttps://dpc-docs.tensor.ru:8443/pages/viewpage.action?pageId=32186543",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'script=tel_autocall_monitoring.py', 'name=tel.autocall.monitoring', 'key=autocall_workers_amount'), 'host')"
    }
   ]
  },
  {
   "title": "Код http ответа страницы загрузки iso образа АТС",
   "type": "table",
   "description": "Код ответа загрузки страницы, на которой выложен iso образ развертывания АТС\nhttps://dpc-docs.tensor.ru:8443/pages/viewpage.action?pageId=32186834",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "target": "alias(transformNull(seriesByTag('contur=prod', 'script=tel_iso_monitoring.py', 'code=~*', 'name=tel.iso.monitoring'), -3), 'http.code')"
    }
   ]
  },
  {
   "title": "Автодозвон autocall_failed_calls_amount",
   "type": "graph",
   "description": "Данные из редис серверов, где располагается контейнер tensor_autocall*\nhttps://dpc-docs.tensor.ru:8443/pages/viewpage.action?pageId=32186547",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'script=tel_autocall_monitoring.py', 'name=tel.autocall.monitoring', 'key=autocall_failed_calls_amount'), 'host')"
    }
   ]
  },
  {
   "title": "Результат метода Telephony.GetConnectData",
   "type": "graph",
   "description": "Мониторинг выполнения Telephony.GetConnectData (сервис telephony). Возвращает 1 - если вернуло информацию по АТС и 0, если не вернуло. -1 = ошибка скрипта. Если значение =0, то звонок с сайта sbis.ru не работает.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'script=tel_call_from_site_monitoring.py', 'service=telephony'), 'name')"
    }
   ]
  },
  {
   "title": "Длительность метода Container.TaskRunPBX",
   "type": "graph",
   "description": "Мониторинг выполнения длительности метода Container.TaskRunPBX/4 (сервис telephony-infrastructure). Отображается самый длинный или 0, если активных методов нет.\nВ выборку с большей долей вероятности не попадут менее 1 минуты запросы.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'script=tel_taskrun_duration_monitoring.py', 'service=telephony-infrastructure', 'name=tel.taskrun.method.duration'), 'name')"
    }
   ]
  },
  {
   "title": "Количество АТС в состоянии ошибки развертывания",
   "type": "graph",
   "description": "Скрипт дергает метод Container.GetFailedDeployContainerNames/0 у сервиса telephony-infrastructure, который выводит из реестра https://cloud.sbis.ru/pbx-admin/page/pbx/ кол-во АТС, которые при развороте имели проблемы. \nhttps://dpc-docs.tensor.ru/x/jADPAw\n>> 0 - ок\n>0 - счетчик неудачно развернутых\n-1 - проблемы с получением из облака\n-2 - нет данных",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'service=telephony-infrastructure', 'name=tel_container_check_deploy', 'script=tel_container_check_deploy.py'), 'name')"
    }
   ]
  },
  {
   "title": "Очереди tensor_listener по АТС. Топ 20",
   "type": "graph",
   "description": "Выводит топ 20 контейнеров АТС с очередями по сервисам с платформой телефонии",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "highestMax(aliasByTags(seriesByTag('contur=prod', 'script=tel_listener_monitoring_tasks.py', 'ats=~.*'), 'host', 'ats'), 20)"
    }
   ]
  },
  { "title": "Kamailio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Статус keepalived.service",
   "type": "graph",
   "description": "telegraf procstat.keepalived.running. ok (1) else bad.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=procstat.keepalived.running', 'service=kamailio', 'contur=prod'), 'host')"
    }
   ]
  },
  {
   "title": "Статус kamailio.service",
   "type": "graph",
   "description": "telegraf procstat.kamailio.running ok (1) else bad.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=procstat.kamailio.running', 'service=kamailio', 'contur=prod'), 'host')"
    }
   ]
  },
  {
   "title": "Статус rtpengine.service",
   "type": "graph",
   "description": "telegraf procstat.kamailio.running ok (1) else bad.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=procstat.rtpengine.running', 'service=kamailio', 'contur=prod'), 'host')"
    }
   ]
  },
  {
   "title": "Keepalived InstanceState",
   "type": "graph",
   "description": "telegraf flussonic_snmp.InstanceState\ninit(0), backup(1), master(2), fault(3), unknown(4)\nТекущее состояние инстанса keepalived на сервере в разрезе instanceRouterID",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=flussonic_snmp.instanceState', 'service=kamailio', 'contur=prod'), 'host', 'instanceRouterID')"
    }
   ]
  },
  {
   "title": "Keepalived InstanceWantedState",
   "type": "graph",
   "description": "telegraf flussonic_snmp.InstanceState\ninit(0), backup(1), master(2), fault(3), unknown(4)\nТекущее ожидание состояния инстанса keepalived на сервере в разрезе instanceRouterID",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=flussonic_snmp.instanceWantedState', 'service=kamailio', 'contur=prod'), 'host', 'instanceRouterID')"
    }
   ]
  },
  {
   "title": "Наличие маршрута по умолчанию",
   "type": "graph",
   "description": "telegraf kamailio.custom.route.default. снимается скриптом наличие маршрута по умолчанию:\n`default 10.76.229.1 0.0.0.0 ens224`\nСтатусы: \n`exist(1), nonexist(0)`\nДолжен быть на всех серверах в списке равен 1",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=kamailio.custom.route.default', 'service=kamailio', 'contur=prod'), 'host')"
    }
   ]
  },
  {
   "title": "Наличие маршрута до 10.76.21.0/24",
   "type": "graph",
   "description": "telegraf kamailio.custom.route.default. снимается скриптом наличие маршрута до 10.76.21.0/24. Внимание! Для текущего мастера маршрут должен быть, а для слейва отсутствовать! \nДоступные статусы: \n`exist(1), nonexist(0)`\nДолжно быть согласно [документу](https://dpc-docs.tensor.ru/pages/viewpage.action?pageId=32181429 \"документу\")\n",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=kamailio.custom.route.10_76_21_0', 'service=kamailio', 'contur=prod'), 'host')"
    }
   ]
  },
  {
   "title": "Наличие маршрута до 10.76.228.0/24",
   "type": "graph",
   "description": "telegraf kamailio.custom.route.default. снимается скриптом наличие маршрута до 10.76.228.0/24. Внимание! Для текущего мастера маршрут должен быть, а для слейва отсутствовать! \nДоступные статусы: \n`exist(1), nonexist(0)`\nДолжно быть согласно [документу](https://dpc-docs.tensor.ru/pages/viewpage.action?pageId=32181429 \"документу\")",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=kamailio.custom.route.10_76_228_0', 'service=kamailio', 'contur=prod'), 'host')"
    }
   ]
  },
  {
   "title": "RTPengine кол-во активных звонков",
   "type": "graph",
   "description": "собирается скриптом /etc/telegraf/telegraf.d/scripts/kamailio_rtpengine_calls.sh",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=kamailio.rtpengine.active.calls', 'service=kamailio', 'contur=prod'), 'host')"
    }
   ]
  },
  {
   "title": "Количество ошибок в логах rtpengine/kamailio",
   "type": "graph",
   "description": "собирается скриптом /etc/telegraf/telegraf.d/scripts/kamailio_rtpengine_calls.sh\nдля RTPENGINE = /var/log/rtpengine/rtpengine-packets-errors.log\nдля KAMAILIO = /var/log/kamailio/kamailio-resolve-errors.log",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=kamailio.custom.log.errors', 'service=kamailio', 'contur=prod'), 'host')"
    }
   ]
  },
  {
   "title": "Время ответа Kamailio",
   "type": "graph",
   "description": "Мониторится с 3 внешних площадок доступность sip*.tel.sbis.ru шлюза телефонии\nТочка.Порт.Площадка\nresponse_time (float, seconds)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'name=net_response.response_time', 'server=~.*', 'host=~.*', 'service=sip'), 'server', 'port', 'host', 'name')"
    }
   ]
  },
  {
   "title": "Код ответа Kamailio",
   "type": "graph",
   "description": "Мониторится с 3 внешних площадок доступность sip*.tel.sbis.ru шлюза телефонии\nТочка.Порт.Площадка\nresult_code (int, success = 0, timeout = 1, connection_failed = 2, read_failed = 3, string_mismatch = 4)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'name=net_response.result_code', 'server=~.*', 'host=~.*'), 'server', 'port', 'host', 'name')"
    }
   ]
  }
 ]
}