{
 "title": "УЦ - Количество серийников CSP",
 "description": "Ответственный: Карпов С.В. и Кравченко С.Н. (Эксплуатация)",
 "tags": [
  "uc",
  "exploitation",
  "service",
  "scripts"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Остаток годовых серийников Крипто Про CSP 4.0",
   "type": "graph",
   "description": "Число свободных серийный номеров Крипто Про CSP",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=csp.sn.count', 'contur=prod', 'item=КриптоПро 4.0 (на 1 год)'), 'item', 'type')"
    }
   ]
  },
  {
   "title": "Остаток годовых серийников Крипто Про CSP 5.0",
   "type": "graph",
   "description": "Число свободных серийный номеров Крипто Про CSP",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=csp.sn.count', 'contur=prod', 'item=КриптоПро 5.0 (на 1 год)'), 'item', 'type')"
    }
   ]
  },
  {
   "title": "Остаток бессрочных серийников Крипто Про CSP 4.0",
   "type": "graph",
   "description": "Число свободных серийный номеров Крипто Про CSP",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=csp.sn.count', 'contur=prod', 'item=КриптоПро 4.0 (бессрочно)', 'type=today'), 'item')"
    }
   ]
  },
  {
   "title": "Остаток бессрочных серийников Крипто Про CSP 5.0",
   "type": "graph",
   "description": "Число свободных серийный номеров Крипто Про CSP",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=csp.sn.count', 'contur=prod', 'item=КриптоПро 5.0 (бессрочно)', 'type=today'), 'item')"
    }
   ]
  }
 ]
}