{
 "title": "УЦ - Проверки",
 "description": "Эксплуатация УЦ. Ответственный: Карпов С.В. и Кравченко С.Н. (Эксплуатация)",
 "tags": [
  "uc",
  "exploitation",
  "service",
  "scripts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "ucname",
    "label": "Имя УЦ",
    "query": "tag_values(ucname,subsystem=uc)"
   }
  ]
 },
 "panels": [
  { "title": "$ucname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ucname" },
  {
   "title": "$ucname: Время публикации CRL",
   "type": "graph",
   "description": "Сколько времени назад был опубликован СОС, берется из поля Last Update в crl по каждой точке распространения",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=crl.publtime', 'ucname=$ucname'), 'url')"
    }
   ]
  },
  {
   "title": "$ucname: Время протухания CRL",
   "type": "graph",
   "description": "Срок действия СОС, берется из поля Next Update в crl для каждой точки распространения",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=crl.rottime', 'ucname=$ucname'), 'url')"
    }
   ]
  },
  {
   "title": "$ucname: Время создания файла CRL",
   "type": "graph",
   "description": "Время изменения файла на точке распространения, заголовок Last-Modified, показывает обновляется ли файл на точке",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=crl.file.publtime', 'ucname=$ucname'), 'url')"
    }
   ]
  },
  {
   "title": "$ucname: Доступность CRL\\CRT",
   "type": "graph",
   "description": "Проверка доступности файла СОС и корневого (код 200) по точкам распространения",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=crl.availability', 'ucname=$ucname'), 'url')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=crt.availability', 'ucname=$ucname'), 'url')"
    }
   ]
  },
  {
   "title": "$ucname: Различие CRL",
   "type": "graph",
   "description": "Сравнение файлов СОС между основной точкой (обычно tax4 или tax5.tensor.ru) и остальными точками с помощью md5",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=crl.diff', 'ucname=$ucname'), 'url')"
    }
   ]
  },
  {
   "title": "$ucname: Различие CRT",
   "type": "graph",
   "description": "Сравнение файлов корневых между основной точкой (обычно tax4 или tax5.tensor.ru) и остальными точками с помощью md5",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=crt.diff', 'ucname=$ucname'), 'url')"
    }
   ]
  },
  {
   "title": "$ucname: Свободное место в БД",
   "type": "graph",
   "description": "Оставшееся выделенное место в БД Центра Регистрации и Центра Сертификации",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=db.unallocated.space', 'subsystem=uc', 'ucname=$ucname'), 'type', 'name')"
    }
   ]
  },
  {
   "title": "$ucname: Проверка службы регистрации",
   "type": "graph",
   "description": "Проверка работает ли служба \"КриптоПро УЦ 2.0. Служба регистрации\" на Центре Регистрации",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=service.state', 'subsystem=uc', 'ucname=$ucname'), 'type', 'name')"
    }
   ]
  },
  {
   "title": "$ucname: Очередь ServiceBroker",
   "type": "graph",
   "description": "Очередь задач в компоненте MSSQL ServiceBroker в БД на Центре Регистрации",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=queue.servicebroker', 'subsystem=uc', 'ucname=$ucname'), 'name')"
    }
   ]
  }
 ]
}