{
 "title": "HelpDesk. Клиентские чаты",
 "description": "Ответственный: Смирнова С.С. (Эксплуатация)",
 "tags": [
  "scripts",
  "staff"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "HelpDesk. Клиентские чаты",
   "type": "graph",
   "description": "Статистика по завершенным клиентским чатам за сутки. Все группы",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aliasBy": "$field_group",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "group",
     "queryText": "query{\n            records(\n            script: \"helpdesk_chats.py\",\n            department: \"HelpDesk\",\n            person: \"Всего\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            group\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Основной",
   "type": "graph",
   "description": "Статистика по завершенным клиентским чатам за сутки. Группа Основной",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"helpdesk_chats.py\",\n            group: \"Основной\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Техподдержка ЭДО HelpDesk",
   "type": "graph",
   "description": "Статистика по завершенным клиентским чатам за сутки. Группа Техподдержка ЭДО HelpDesk",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"helpdesk_chats.py\",\n            group: \"Техподдержка ЭДО HelpDesk\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Премиум ЭО HelpDesk",
   "type": "graph",
   "description": "Статистика по завершенным клиентским чатам за сутки.\nГруппа  Премиум ЭО HelpDesk",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"helpdesk_chats.py\",\n            group: \"Премиум ЭО HelpDesk\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Гос. системы HelpDesk",
   "type": "graph",
   "description": "Статистика по завершенным клиентским чатам",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"helpdesk_chats.py\",\n            group: \"Гос. системы HelpDesk\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Техподдержка Розницы HelpDesk",
   "type": "graph",
   "description": "Статистика по завершенным клиентским чатам",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"helpdesk_chats.py\",\n            group: \"Техподдержка Розницы HelpDesk\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Заполнение отчетности HelpDesk",
   "type": "graph",
   "description": "Статистика по завершенным клиентским чатам",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"helpdesk_chats.py\",\n            group: \"Заполнение отчетности HelpDesk\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Прочие продукты HelpDesk",
   "type": "graph",
   "description": "Статистика по завершенным клиентским чатам",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"helpdesk_chats.py\",\n            group: \"Прочие продукты HelpDesk\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Техподдержка Бухгалтерии HelpDesk",
   "type": "graph",
   "description": "Статистика по завершенным клиентским чатам",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"helpdesk_chats.py\",\n            group: \"Техподдержка Бухгалтерии HelpDesk\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Электронные подписи, торговые площадки и гос. порталы HelpDesk",
   "type": "graph",
   "description": "Статистика по завершенным клиентским чатам",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"helpdesk_chats.py\",\n            group: \"Электронные подписи, торговые площадки и гос. порталы HelpDesk\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Премиум Госсистемы HelpDesk",
   "type": "graph",
   "description": "Статистика по завершенным клиентским чатам",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"helpdesk_chats.py\",\n            group: \"Премиум Госсистемы HelpDesk\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Поддержка SabyGet HelpDesk",
   "type": "graph",
   "description": "Статистика по завершенным клиентским чатам",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"helpdesk_chats.py\",\n            group: \"Поддержка SabyGet HelpDesk\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Премиум RPS",
   "type": "graph",
   "description": "Статистика по завершенным клиентским чатам",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"helpdesk_chats.py\",\n            group: \"Премиум RPS\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  }
 ]
}