{
 "title": "Выполненные задачи",
 "description": "Ответственный: Смирнова С.С. (Эксплуатация)",
 "tags": [
  "scripts",
  "staff"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Бэкенд. Решение задач эксплуатации",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"tensor_exp_tasks.py\",\n            group: \"Бэкенд\",\n            tsFrom: \"${__from:date:iso}\",\n            tsTo: \"${__to:date:iso}\"\n            )\n            {\n            time_stamp\n            person\n            plan_time\n            fact_time\n            reassignments\n            delays\n            }\n        }"
    }
   ]
  },
  {
   "title": "СПД. Норма выполненных задач",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"tensor_exp_tasks.py\",\n            group: \"СПД\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            plan_time\n            done\n            }\n        }"
    }
   ]
  },
  {
   "title": "Телефония,  выполнено задач с начала месяца",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 0 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"tensor_exp_tasks.py\",\n            group: \"Телефония\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }"
    }
   ]
  },
  {
   "title": "Телефония",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"tensor_exp_tasks_daily.py\",\n            group: \"Телефония\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "СПД",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"tensor_exp_tasks_daily.py\",\n            group: \"СПД\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Бэкенд",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"tensor_exp_tasks_daily.py\",\n            group: \"Бэкенд\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Дежурные",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"tensor_exp_tasks_daily.py\",\n            group: \"Дежурные\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  }
 ]
}