{
 "title": "Новый отчет по задачам",
 "description": "Ответственный: Смирнова С.С. (Эксплуатация)",
 "tags": [
  "staff",
  "scripts"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Распределение задач по отделам",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_department",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "department",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            group: \"Все\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            department\n            remain\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Проектный отдел",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_group",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "group",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Проектный отдел\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            department\n            group\n            remain\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Поступило на отдел",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Проектный отдел\"\n            group: \"Все\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            received\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Эксплуатация Тензора",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_group",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "group",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Эксплуатация Тензора\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            department\n            group\n            remain\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Поступило на отдел",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Эксплуатация Тензора\"\n            group: \"Все\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            received\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Выполнено",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Эксплуатация Тензора\"\n            group: \"Все\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "СПД",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "Задачи",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"СПД\"\n            group: \"Все\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            not_scenarios\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Сценарии работы",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"СПД\"\n            group: \"Все\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            scenarios\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "$field_group",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "group",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"СПД\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            department\n            group\n            remain\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Поступило на отдел",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"СПД\"\n            group: \"Все\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            received\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Просрочено",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"СПД\"\n            group: \"Все\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            expired\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Техподдержка Тензора",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aliasBy": "$field_group",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "group",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Техподдержка Тензора\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            department\n            group\n            remain\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Поступило на отдел",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Техподдержка Тензора\",\n            group: \"Все\",\n            tsFrom: \"${__from:date:iso}\",\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            received\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Задачи старше недели на сисадминах",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Техподдержка Тензора\",\n            group: \"Все\",\n            tsFrom: \"${__from:date:iso}\",\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            old\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Чаты",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"support_chats.py\",\n            group: \"Чаты\",\n            person: \"Всего\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            done\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Администрирование ЦОД",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_group",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "group",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Администрирование ЦОД\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            department\n            group\n            remain\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Поступило на отдел",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Администрирование ЦОД\"\n            group: \"Все\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            received\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Пул задач, больше месяца",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Администрирование ЦОД\"\n            group: \"Все\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            old\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Пул задач, меньше недели",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Администрирование ЦОД\"\n            group: \"Все\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            new\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Просрочено",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Администрирование ЦОД\"\n            group: \"Все\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            expired\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Эксплуатация ЦОД",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_group",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "group",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Эксплуатация ЦОД\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            department\n            group\n            remain\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Поступило на отдел",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Эксплуатация ЦОД\"\n            group: \"Все\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            received\n            }\n        }",
     "timePath": "time_stamp"
    },
    {
     "aliasBy": "Просрочено",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "queryText": "query{\n            records(\n            script: \"task_report.py\",\n            department: \"Эксплуатация ЦОД\"\n            group: \"Все\"\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            expired\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  }
 ]
}