{
 "title": "Проектный отдел. По группам",
 "description": "Ответственный: Смирнова С.С. (Эксплуатация)",
 "tags": [
  "scripts",
  "staff"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Разработка",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"project_tasks_daily.py\",\n            department: \"Проектный отдел\"\n            group: \"Разработка\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            remain\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Управление проектами",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"project_tasks_daily.py\",\n            department: \"Проектный отдел\"\n            group: \"Управление проектами\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            remain\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  },
  {
   "title": "Контейнерная инфраструктура",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "$field_person",
     "constant": 6.5,
     "dataPath": "records",
     "endTimePath": "endTime",
     "groupBy": "person",
     "queryText": "query{\n            records(\n            script: \"project_tasks_daily.py\",\n            department: \"Проектный отдел\"\n            group: \"Контейнерная инфраструктура\",\n            tsFrom: \"${__from:date:iso}\"\n            tsTo: \"${__to:date:iso}\"\n            ){\n            time_stamp\n            person\n            remain\n            }\n        }",
     "timePath": "time_stamp"
    }
   ]
  }
 ]
}