{
 "title": "elasticsearch2",
 "description": "На удаление. Ответственный: -",
 "tags": [
  "service",
  "sbis3mon-kafka",
  "elasticsearch"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.elasticsearch2.pushStat.*"
   }
  ]
 },
 "panels": [
  { "title": "$server (sessions)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: evict rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.cluster.fieldData.evict.rate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: docs deleted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.cluster.docs.primaries.deleted.rate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: docs primaries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.cluster.docs.primaries.count.rat{e,e2}.raw, -2)"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$server: cluster indices queryCache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.cluster.queryCache.{evict,avg}.{bytes,rate}.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster cache hitrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.cluster.queryCache.{hit,miss}.rate.raw, -3)"
    }
   ]
  },
  {
   "title": "$server: cluster indices segments bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.node.segments.bytes.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices segment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.node.segments.count.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices store",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.node.store.bytes.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.node.store.bytes.rate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.cluster.indices.count.raw, -2)"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "$server: cluster nodes count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.count.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.cluster.shards.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster nodes capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.fs.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster nodes mem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.mem.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.node.mem.virtual.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.cluster.status.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: node status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch2.pushStat.$server.elastic.*.elasticsearch.node.status.raw, -2)"
    }
   ]
  }
 ]
}