{
 "title": "elasticsearch5",
 "description": "На удаление. Ответственный: Сорокин И.А. (Эксплуатация), Барган А.В. (Разработка)",
 "tags": [
  "service",
  "sbis3mon-kafka",
  "elasticsearch"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.elasticsearch5.pushStat.*"
   }
  ]
 },
 "panels": [
  {
   "title": "$server cluster indices (count, field data)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "server"
  },
  {
   "title": "$server: cluster indices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.count.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.fieldData.bytes.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.fieldData.evictionsRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster indices (count, field data)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "$server: cluster indices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.count.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.fieldData.bytes.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.fieldData.evictionsRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster indices (count, field data)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "$server: cluster indices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.count.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.fieldData.bytes.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.fieldData.evictionsRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster docs (incoming, deleted)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "server"
  },
  {
   "title": "$server: docs incoming",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.docs.count.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.docs.countRate2.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: docs deleted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.docs.deleted.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.docs.deletedRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster docs (incoming, deleted)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "$server: docs incoming",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.docs.count.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.docs.countRate2.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: docs deleted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.docs.deleted.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.docs.deletedRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster docs (incoming, deleted)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "$server: docs incoming",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.docs.count.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.docs.countRate2.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: docs deleted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.docs.deleted.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.docs.deletedRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster indices (query cache)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "repeat": "server"
  },
  {
   "title": "$server: cluster indices queryCache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.queryCache.size.bytes.raw, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.queryCache.evictionsRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices queryCache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.queryCache.missRate.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.queryCache.hitRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster indices (query cache)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 }
  },
  {
   "title": "$server: cluster indices queryCache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.queryCache.size.bytes.raw, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.queryCache.evictionsRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices queryCache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.queryCache.missRate.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.queryCache.hitRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster indices (query cache)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 }
  },
  {
   "title": "$server: cluster indices queryCache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.queryCache.size.bytes.raw, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.queryCache.evictionsRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices queryCache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.queryCache.missRate.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.queryCache.hitRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster indices (segments)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "repeat": "server"
  },
  {
   "title": "$server: cluster indices segments bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.segments.bytes.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices segment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.segments.count.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster indices (segments)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 }
  },
  {
   "title": "$server: cluster indices segments bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.segments.bytes.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices segment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.segments.count.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster indices (segments)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 }
  },
  {
   "title": "$server: cluster indices segments bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.segments.bytes.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices segment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.segments.count.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster indices (store)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "repeat": "server"
  },
  {
   "title": "$server: cluster indices store",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.store.size.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.store.sizeRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices store",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.store.throttleTimeRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster indices (store)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 }
  },
  {
   "title": "$server: cluster indices store",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.store.size.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.store.sizeRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices store",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.store.throttleTimeRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster indices (store)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 }
  },
  {
   "title": "$server: cluster indices store",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.store.size.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.store.sizeRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster indices store",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.indices.store.throttleTimeRate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster (nodes, shards)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "repeat": "server"
  },
  {
   "title": "$server: cluster nodes count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.count.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.shards.*.raw, 'Pct'), -2)"
    }
   ]
  },
  {
   "title": "$server cluster (nodes, shards)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 }
  },
  {
   "title": "$server: cluster nodes count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.count.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.shards.*.raw, 'Pct'), -2)"
    }
   ]
  },
  {
   "title": "$server cluster (nodes, shards)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 }
  },
  {
   "title": "$server: cluster nodes count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.count.*.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.shards.*.raw, 'Pct'), -2)"
    }
   ]
  },
  {
   "title": "$server cluster nodes (capacity, fs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 },
   "repeat": "server"
  },
  {
   "title": "$server: cluster nodes capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.fs.used.raw, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.fs.total.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster nodes fs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 145 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.fs.rate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster nodes (capacity, fs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 }
  },
  {
   "title": "$server: cluster nodes capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.fs.used.raw, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.fs.total.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster nodes fs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.fs.rate.raw, -2)"
    }
   ]
  },
  {
   "title": "$server cluster nodes (capacity, fs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 }
  },
  {
   "title": "$server: cluster nodes capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.fs.used.raw, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.fs.total.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster nodes fs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 161 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.fs.rate.raw, -2)"
    }
   ]
  },
  { "title": "$server cluster nodes (mem)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 }, "repeat": "server" },
  {
   "title": "$server: cluster nodes mem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.mem.used.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.mem.total.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster nodes mem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 169 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.mem.rate.raw, -2)"
    }
   ]
  },
  { "title": "$server cluster nodes (mem)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 } },
  {
   "title": "$server: cluster nodes mem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.mem.used.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.mem.total.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster nodes mem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 177 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.mem.rate.raw, -2)"
    }
   ]
  },
  { "title": "$server cluster nodes (mem)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 } },
  {
   "title": "$server: cluster nodes mem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 185 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.mem.used.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.mem.total.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cluster nodes mem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 185 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.nodes.mem.rate.raw, -2)"
    }
   ]
  },
  { "title": "$server cluster status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 192 }, "repeat": "server" },
  {
   "title": "$server: cluster status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 193 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.status.raw, -2)"
    }
   ]
  },
  { "title": "$server cluster status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "$server: cluster status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.status.raw, -2)"
    }
   ]
  },
  { "title": "$server cluster status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 208 } },
  {
   "title": "$server: cluster status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 209 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.cluster.status.raw, -2)"
    }
   ]
  }
 ]
}