{
 "title": "elasticsearch5 (JVM)",
 "description": "На удаление. Ответственный: -",
 "tags": [
  "service",
  "elasticsearch",
  "sbis3mon"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "query": "sbis3mon.$contur.elasticsearch5.pushStat.*"
   },
   { "name": "domain", "label": "Домен", "query": "*.tensor.ru" },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  { "title": "JVM $server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "Heap mem",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.node.jvm.mem.heap.committed.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.node.jvm.mem.heap.used.raw, -2)"
    }
   ]
  },
  {
   "title": "Non-heap mem",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.node.jvm.mem.nonheap.committed.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.node.jvm.mem.nonheap.used.raw, -2)"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.node.jvm.threads.*.raw, -2)"
    }
   ]
  },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sbis3mon.$contur.elasticsearch5.$server.$domain.9200.*.aggr-$aggr.elasticsearch.node.jvm.gc.metrics.old.{countRate,avgItemTime}  | summarize('$__interval', '$aggr', false) | aliasByNode(-2,-1)"
    },
    {
     "target": "sbis3mon.$contur.elasticsearch5.$server.$domain.9200.*.aggr-$aggr.elasticsearch.node.jvm.gc.metrics.young.{countRate,avgItemTime}  | summarize('$__interval', '$aggr', false) | aliasByNode(-2,-1)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.node.jvm.gc.metrics.old.{countRate,avgItemTime}.raw, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.elasticsearch5.pushStat.$server.elastic.*.elasticsearch.node.jvm.gc.metrics.young.{countRate,avgItemTime}.raw, -3, -2)"
    }
   ]
  }
 ]
}