{
 "title": "linux (net) Telegraf",
 "description": "На удаление. Ответственный: -",
 "tags": [
  "system",
  "telegraf",
  "simple"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "tag_values(host,contur=$contur)"
   },
   { "name": "domain", "label": "Домен", "query": "*.tensor.ru" }
  ]
 },
 "panels": [
  {
   "title": "$server (connection, stat listen)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "server"
  },
  {
   "title": "$server: connection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.netstat.tcp_established', 'contur=~${contur:regex}', 'host=~${server:regex}'), 'name', 'name')"
    }
   ]
  },
  {
   "title": "$server: drops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~system.net.drop.*', 'contur=~${contur:regex}', 'host=~${server:regex}')), 'interface', 'name')"
    }
   ]
  },
  { "title": "$server (bps, pps)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "server" },
  {
   "title": "$server: net bps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~system.net.bytes_(sent|recv)', 'contur=~${contur:regex}', 'host=~${server:regex}')), 'interface','name')"
    }
   ]
  },
  {
   "title": "$server: net pps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~system.net.packets_(sent|recv)', 'contur=~${contur:regex}', 'host=~${server:regex}')), 'interface','name')"
    }
   ]
  },
  { "title": "$server (errors)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "server" },
  {
   "title": "$server: net (pps, error)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~system.net.err.*', 'contur=~${contur:regex}', 'host=~${server:regex}')), 'interface', 'name')"
    }
   ]
  }
 ]
}