{
 "title": "linux (cpu) zabbix sbis3mon",
 "description": "На удаление. Ответственный: -",
 "tags": [
  "zabbix",
  "system",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "telegraf.$contur.system.system.*"
   },
   { "name": "domain", "label": "Домен", "query": "*.tensor.ru" },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  { "title": "$server (time, time %)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.*.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.*.$aggr, -2)"
    }
   ]
  },
  { "title": "$server (busy, la)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "server" },
  {
   "title": "$server: busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByMetric(sbis3mon.$contur.linux.core.$server.*.cpu.busy.max)"
    },
    {
     "refCount": 2,
     "target": "aliasByMetric(sbis3mon.$contur.linux.core.$server.*.cpu.busy.avg)"
    }
   ]
  },
  {
   "title": "$server: la",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(telegraf.$contur.system.system.$server.$domain.*.load1)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.la.$server.*.cpu.la.*.$aggr, -2)"
    }
   ]
  },
  { "title": "$server (context, core avg)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "server" },
  {
   "title": "$server: context",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sbis3mon.$contur.linux.la.$server.*.cpu.contextSwitch.max, 'contextSwitch.aggr-max')"
    },
    {
     "target": "alias(sbis3mon.$contur.linux.la.$server.*.cpu.contextSwitch.avg, 'contextSwitch.aggr-avg')"
    }
   ]
  },
  {
   "title": "$server: core avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.coreAvg.$server.*.cpu.core.*.busy.avg.avg, -6, -5, -4, -3, -2)"
    }
   ]
  },
  { "title": "$server (core busy, core %)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "server" },
  {
   "title": "$server: core busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.core.$server.*.cpu.core.*.busy.avg, -5, -4, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: core busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.core.$server.*.cpu.core.*.busy.pct.avg, -5, -4, -3, -2)"
    }
   ]
  }
 ]
}