{
 "title": "linux (cpu) telegraf",
 "description": "На удаление. Ответственный: -",
 "tags": [
  "telegraf",
  "system",
  "simple"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "tag_values(host,contur=$contur,cpu=cpu-total)"
   }
  ]
 },
 "panels": [
  { "title": "$server (time, time %)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByMetric(aliasByTags(seriesByTag('cpu=cpu-total', 'name=~system.cpu.usage_(user|softirq|nice|iowait|system|steal|guest|irq)', 'host=~${server:regex}'), 'name')), 'usage_', '')"
    }
   ]
  },
  {
   "title": "$server: la",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(seriesByTag('name=~system.system.load', 'host=~${server:regex}'), 'name'))"
    },
    {
     "target": "aliasByMetric(aliasByTags(perSecond(seriesByTag('name=~system.kernel.context_switches', 'host=~${server:regex}')), 'name'))"
    }
   ]
  },
  { "title": "$server (busy, la)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "server" },
  {
   "title": "$server: busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(diffSeries(seriesByTag('cpu=cpu-total', 'name=system.cpu.usage_active', 'host=~${server:regex}'), #A), 'busy')",
     "targetFull": "alias(diffSeries(seriesByTag('cpu=cpu-total', 'name=system.cpu.usage_active', 'host=~${server:regex}'), seriesByTag('cpu=cpu-total', 'name=system.cpu.usage_iowait', 'host=~${server:regex}')), 'busy')"
    }
   ]
  },
  {
   "title": "$server: core",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu!=cpu-total', 'host=~${server:regex}'), 'cpu')"
    }
   ]
  }
 ]
}