{
 "title": "linux (storage) telegraf",
 "description": "Информация о хранилище. Ответственный: -",
 "tags": [
  "system",
  "telegraf",
  "simple"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "tag_values(host,contur=$contur,cpu=cpu-total)"
   },
   { "name": "storage", "query": "tag_values(_name,host=$server)" }
  ]
 },
 "panels": [
  { "title": "$server (busy, lag)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=~${server:regex}', 'name=system.diskio.iops_in_progress', '_name=~${storage:regex}'), '_name', 'name'), 0, -1)"
    },
    {
     "target": "aliasByNode(perSecond(scale(aliasByTags(seriesByTag('host=~${server:regex}', 'name=system.diskio.io_time', '_name=~${storage:regex}'), '_name', 'name'), 0.1)), 0, -1)"
    }
   ]
  },
  {
   "title": "$server: lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(perSecond(aliasByTags(seriesByTag('host=~${server:regex}', 'name=~system.diskio.io_time', '_name=~${storage:regex}'), '_name', 'name')), 0, -1), '_bytes', '')"
    }
   ]
  },
  { "title": "$server (bps, ops)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "server" },
  {
   "title": "$server: bps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(perSecond(aliasByTags(seriesByTag('host=~${server:regex}', 'name=~system.diskio.(read|write)_bytes', '_name=~${storage:regex}'), '_name', 'name')), 0, -1), '_bytes', '')"
    }
   ]
  },
  {
   "title": "$server: ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(perSecond(aliasByTags(seriesByTag('host=~${server:regex}', 'name=~system.diskio.(reads|writes)', '_name=~${storage:regex}'), '_name', 'name')), 0, -1), '_bytes', '')"
    }
   ]
  }
 ]
}