{
 "title": "named",
 "description": "На удаление. Ответственный: -",
 "tags": [
  "named",
  "sbis3mon-kafka",
  "service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "sbis3mon.*" },
   { "name": "server", "label": "Имя сервера", "query": "sbis3mon.$contur.named.stats.*" }
  ]
 },
 "panels": [
  { "title": "$server (resolve, memory)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: resolve",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.resolve.$server.named.*.named.resolve.{time,count}.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.named.*.named.memory.{inuse,contextsize,blocksize,lost}.raw, -2)"
    }
   ]
  },
  { "title": "$server (resolve, memory)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$server: resolve",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.resolve.$server.named.*.named.resolve.{time,count}.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.named.*.named.memory.{inuse,contextsize,blocksize,lost}.raw, -2)"
    }
   ]
  },
  { "title": "$server (resolve, memory)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$server: resolve",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.resolve.$server.named.*.named.resolve.{time,count}.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.named.*.named.memory.{inuse,contextsize,blocksize,lost}.raw, -2)"
    }
   ]
  },
  { "title": "$server (qps)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "server" },
  {
   "title": "$server: qps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.named.*.named.qps.raw, -2)"
    }
   ]
  },
  { "title": "$server (qps)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "$server: qps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.named.*.named.qps.raw, -2)"
    }
   ]
  },
  { "title": "$server (qps)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "$server: qps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.named.stats.$server.named.*.named.qps.raw, -2)"
    }
   ]
  }
 ]
}