{
 "title": "RHV - Virtual Machines Resource Usage Dashboard (Не удалять до запроса)",
 "description": "На экране мониторинга использования ресурсов виртуальных машин отображаются измерения использования ресурсов - скорости использования диска ( ввода-вывода), процессора, памяти и сетевого Tx / Rx. Ответственный:  Альбещенко М.Н. (АЦОД)",
 "tags": [
  "RHV",
  "Virtualization",
  "system",
  "Warehouse",
  "scripts"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "show_deleted", "label": "Show Deleted Entities?", "query": "No,Yes" },
   {
    "name": "datacenter_id",
    "label": "Data Center",
    "query": "SELECT DISTINCT   CAST ( datacenter_id AS varchar ) AS __value,  CASE          WHEN delete_date IS NULL  \t     \t    THEN datacenter_name \t \tWHEN delete_date IS NOT null  \t      \t    THEN datacenter_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')'  END AS __text  \t\tFROM v4_4_configuration_history_datacenters  \t\tWHERE       \t\t    history_id           \t\t\t    IN               \t\t\t\t(  \t             \t\t\t\t\tSELECT MAX ( a.history_id )  \t\t         \t\t\t\t\tFROM v4_4_configuration_history_datacenters a  \t\t         \t\t\t\t\tGROUP BY a.datacenter_id \t         \t\t\t\t) \t \t\t\tAND datacenter_id  \t         \t\t\t    IN \t\t\t     \t\t\t\t    ( \t\t\t\t\t \t\t\t\t\t\tSELECT DISTINCT datacenter_id \t\t\t\t\t \t\t\t\t\t\tFROM v4_4_configuration_history_clusters \t\t\t\t\t \t\t\t\t\t\tWHERE  \t\t\t\t\t     \t\t\t\t\t\t    cluster_id \t\t\t\t\t         \t\t\t\t\t\t        IN \t\t\t\t\t             \t\t\t\t\t\t            ( \t\t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t\tSELECT DISTINCT cluster_id \t\t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t\tFROM v4_4_configuration_history_vms  \t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t) \t\t\t\t\t) \t \t\t\tAND \t    \t\t\t    CASE  \t        \t\t\t\t    WHEN '$show_deleted'='Yes' \t            \t\t\t\t\t    THEN 1=1 \t\t    \t\t\t\t\tWHEN '$show_deleted'='No' \t\t        \t\t\t\t\t    THEN v4_4_configuration_history_datacenters.delete_date ISNULL \t                END  \t\t"
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "SELECT DISTINCT        CAST ( cluster_id AS varchar ) AS __value,  \tCASE      \t    WHEN delete_date IS NULL  \t     \t\t    THEN cluster_name \t \t\tWHEN delete_date IS NOT null  \t      \t\t    THEN cluster_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')'  \tEND AS __text  \tFROM v4_4_configuration_history_clusters  \tWHERE       \t    history_id           \t\t    IN               \t\t\t    (  \t             \t\t\t\t\tSELECT MAX ( a.history_id )  \t\t         \t\t\t\t\tFROM v4_4_configuration_history_clusters a  \t\t         \t\t\t\t\tGROUP BY a.cluster_id \t         \t\t\t\t) \t \t\tAND cluster_id  \t\t    IN \t\t\t     \t\t\t    ( \t\t\t\t\t \t\t\t\t\tSELECT DISTINCT cluster_id \t\t\t\t\t \t\t\t\t\tFROM v4_4_configuration_history_vms \t\t\t\t \t\t\t\t) \t\tAND \t    \t\t    CASE  \t        \t\t\t    WHEN '$show_deleted'='Yes' \t            \t\t\t\t    THEN 1=1 \t\t    \t\t\t\tWHEN '$show_deleted'='No' \t\t        \t\t\t\t    THEN v4_4_configuration_history_clusters.delete_date ISNULL \t    \t\t\tEND     \t\tAND datacenter_id IN ($datacenter_id)  \t\t"
   },
   {
    "name": "vm_id",
    "label": "Virtual Machine",
    "query": "SELECT DISTINCT        CAST ( vm_id AS varchar ) AS __value,  \tCASE      \t    WHEN delete_date IS NULL  \t     \t\t    THEN vm_name \t \t\tWHEN delete_date IS NOT null  \t      \t\t    THEN vm_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')'  \tEND AS __text  \tFROM v4_4_configuration_history_vms  \tWHERE       \t    history_id           \t\t    IN               \t\t\t    (  \t             \t\t\t\t\tSELECT MAX ( a.history_id )  \t\t         \t\t\t\t\tFROM v4_4_configuration_history_vms a  \t\t         \t\t\t\t\tGROUP BY a.vm_id \t         \t\t\t\t) \t \t\tAND \t    \t\t    CASE  \t        \t\t\t    WHEN '$show_deleted'='Yes' \t            \t\t\t\t    THEN 1=1 \t\t    \t\t\t\tWHEN '$show_deleted'='No' \t\t        \t\t\t\t    THEN v4_4_configuration_history_vms.delete_date ISNULL \t    \t\t\tEND     \t\tAND cluster_id IN ($cluster_id)  \t\t"
   },
   {
    "name": "period_id",
    "label": "Period",
    "query": "SELECT 'Day of Week' AS __text, 1 AS __value UNION SELECT  'Hour of Day' AS  __text, 2 AS __value"
   }
  ]
 },
 "panels": [
  { "title": "Virtual Machine CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average CPU Usage (BR10C)",
   "type": "graph",
   "description": "This report displays average CPU usage for a selected virtual machines within a selected period.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm\n-- the average CPU_Usage and CPU_Peak for the hour of day and day of week.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- CPU usage\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    CPU_Usage AS \"CPU Usage\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num ,\n            AVG ( CPU_Usage ) AS CPU_Usage\n        FROM \n            (\n                -- VMs average CPU usage \n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( cpu_usage_percent, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS CPU_Usage\n                FROM\n                    (\n                        SELECT history_datetime, cpu_usage_percent, minutes_in_status, vm_status, vm_id\n                        FROM v4_4_statistics_vms_resources_usage_samples\n                    ) AS samples\n                WHERE\n                    -- Here we filter by active vms only\n                    samples.vm_status = 1\n                    -- Here we filter by the vm chosen by the user\n                    AND samples.vm_id IN ($vm_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query \n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    },
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm\n-- the average CPU_Usage and CPU_Peak for the hour of day and day of week.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- CPU usage\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    CPU_Usage AS \"CPU Usage\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num ,\n            AVG ( CPU_Usage ) AS CPU_Usage\n        FROM \n            (\n                -- VMs average CPU usage \n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( cpu_usage_percent, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS CPU_Usage\n                FROM\n                    (\n                            SELECT history_datetime, cpu_usage_percent, minutes_in_status, vm_status, vm_id\n                            FROM v4_4_statistics_vms_resources_usage_hourly\n                        UNION\n                            SELECT history_datetime, cpu_usage_percent, minutes_in_status, vm_status, vm_id\n                            FROM v4_4_statistics_vms_resources_usage_daily\n                            WHERE\n                                history_datetime <\n                                    (\n                                        SELECT MIN ( history_datetime )\n                                        FROM v4_4_statistics_vms_resources_usage_hourly\n                                    )\n                    ) AS hourly_daily\n                WHERE\n                    -- Here we filter by active vms only\n                    hourly_daily.vm_status = 1\n                    -- Here we filter by the vm chosen by the user\n                    AND hourly_daily.vm_id IN ($vm_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query \n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    }
   ]
  },
  {
   "title": "Average CPU Usage Peaks (BR10C)",
   "type": "graph",
   "description": "This report displays average CPU usage peaks for a selected virtual machines within a selected period.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm\n-- the average CPU_Usage and CPU_Peak for the hour of day and day of week.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- CPU peak\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    CPU_Peak AS \"CPU Peak\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num ,\n            AVG ( CPU_Peak ) AS CPU_Peak\n        FROM \n            (\n                -- VMs max CPU usage \n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( max_cpu_usage, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS CPU_Peak\n                FROM\n                    (\n                        SELECT history_datetime, cpu_usage_percent AS max_cpu_usage, minutes_in_status, vm_status, vm_id\n                        FROM v4_4_statistics_vms_resources_usage_samples\n                    ) AS samples\n                WHERE\n                    -- Here we filter by active vms only\n                    samples.vm_status = 1\n                    -- Here we filter by the vm chosen by the user\n                    AND samples.vm_id IN ($vm_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query \n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES') \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    },
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm\n-- the average CPU_Usage and CPU_Peak for the hour of day and day of week.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- CPU peak\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    CPU_Peak AS \"CPU Peak\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num ,\n            AVG ( CPU_Peak ) AS CPU_Peak\n        FROM \n            (\n                -- VMs max CPU usage \n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( max_cpu_usage, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS CPU_Peak\n                FROM\n                    (\n                            SELECT history_datetime, max_cpu_usage, minutes_in_status, vm_status, vm_id\n                            FROM v4_4_statistics_vms_resources_usage_hourly\n                        UNION\n                            SELECT history_datetime, max_cpu_usage, minutes_in_status, vm_status, vm_id\n                            FROM v4_4_statistics_vms_resources_usage_daily\n                            WHERE\n                                history_datetime <\n                                    (\n                                        SELECT MIN ( history_datetime )\n                                        FROM v4_4_statistics_vms_resources_usage_hourly\n                                    )\n                    ) AS hourly_daily\n                WHERE\n                    -- Here we filter by active vms only\n                    hourly_daily.vm_status = 1\n                    -- Here we filter by the vm chosen by the user\n                    AND hourly_daily.vm_id IN ($vm_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query \n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    }
   ]
  },
  { "title": "Virtual Machine Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Average Memory Usage (BR10C)",
   "type": "graph",
   "description": "This report displays average memory usage for a selected virtual machines within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm\n-- the average MEM_Usage and MEM_Peak for the hour of day and day of week.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Memory usage\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    MEM_Usage AS \"Memory Usage\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num ,\n            AVG ( MEM_Usage ) AS MEM_Usage\n        FROM \n            (\n                -- VMs average memory usage \n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( memory_usage_percent, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS MEM_Usage\n                FROM\n                    (\n                        SELECT history_datetime, memory_usage_percent, minutes_in_status, vm_status, vm_id\n                        FROM v4_4_statistics_vms_resources_usage_samples\n                    ) AS samples\n                WHERE\n                    -- Here we filter by active vms only\n                    samples.vm_status = 1\n                    -- Here we filter by the vm chosen by the user\n                    AND samples.vm_id IN ($vm_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query \n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')         \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    },
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm\n-- the average MEM_Usage and MEM_Peak for the hour of day and day of week.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Memory usage\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    MEM_Usage AS \"Memory Usage\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num ,\n            AVG ( MEM_Usage ) AS MEM_Usage\n        FROM \n            (\n                -- VMs average memory usage \n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( memory_usage_percent, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS MEM_Usage\n                FROM\n                    (\n                            SELECT history_datetime, memory_usage_percent, minutes_in_status, vm_status, vm_id\n                            FROM v4_4_statistics_vms_resources_usage_hourly\n                        UNION\n                            SELECT history_datetime, memory_usage_percent, minutes_in_status, vm_status, vm_id\n                            FROM v4_4_statistics_vms_resources_usage_daily\n                            WHERE\n                                history_datetime <\n                                    (\n                                        SELECT MIN ( history_datetime )\n                                        FROM v4_4_statistics_vms_resources_usage_hourly\n                                    )\n                    ) AS hourly_daily\n                WHERE\n                    -- Here we filter by active vms only\n                    hourly_daily.vm_status = 1\n                    -- Here we filter by the vm chosen by the user\n                    AND hourly_daily.vm_id IN ($vm_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query \n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    }
   ]
  },
  {
   "title": "Average Memory Usage Peaks (BR10C)",
   "type": "graph",
   "description": "This report displays average memory usage peaks for a selected virtual machines within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm\n-- the average MEM_Usage and MEM_Peak for the hour of day and day of week.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Memory peak\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    MEM_Peak AS \"Memory Usage Peaks\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num ,\n            AVG ( MEM_Peak ) AS MEM_Peak\n        FROM \n            (\n                -- VMs max memory usage \n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( max_memory_usage, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS MEM_Peak\n                FROM\n                    (\n                        SELECT history_datetime, memory_usage_percent AS max_memory_usage, minutes_in_status, vm_status, vm_id\n                        FROM v4_4_statistics_vms_resources_usage_samples\n                    ) AS samples\n                WHERE\n                    -- Here we filter by active vms only\n                    samples.vm_status = 1\n                    -- Here we filter by the vm chosen by the user\n                    AND samples.vm_id IN ($vm_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query \n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')         \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    },
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm\n-- the average MEM_Usage and MEM_Peak for the hour of day and day of week.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Memory peak\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    MEM_Peak AS \"Memory Usage Peaks\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num ,\n            AVG ( MEM_Peak ) AS MEM_Peak\n        FROM \n            (\n                -- VMs max memory usage \n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( max_memory_usage, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS MEM_Peak\n                FROM\n                    (\n                            SELECT history_datetime, max_memory_usage, minutes_in_status, vm_status, vm_id\n                            FROM v4_4_statistics_vms_resources_usage_hourly\n                        UNION\n                            SELECT history_datetime, max_memory_usage, minutes_in_status, vm_status, vm_id\n                            FROM v4_4_statistics_vms_resources_usage_daily\n                            WHERE\n                                history_datetime <\n                                    (\n                                        SELECT MIN ( history_datetime )\n                                        FROM v4_4_statistics_vms_resources_usage_hourly\n                                    )\n                    ) AS hourly_daily\n                WHERE\n                    -- Here we filter by active vms only\n                    hourly_daily.vm_status = 1\n                    -- Here we filter by the vm chosen by the user\n                    AND hourly_daily.vm_id IN ($vm_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query \n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    }
   ]
  },
  {
   "title": "Virtual Machine Interface Rx and Tx Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Top 3 Most Utilized Network Interfaces - Transmit Rate (BR10C)",
   "type": "graph",
   "description": "This report displays for the top 3 most utilized network interfaces the average transmit rate for a selected virtual machine within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm,\n-- for the top 3 most utilized network interfaces,\n-- the Rx_rate and Tx_rate, by the hour of day and day of week.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Tx_rate\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    Tx_rate AS \"Transmit Rate\"\nFROM \n    (\n        SELECT DISTINCT\n            num,\n            COALESCE ( interface_name, MAX ( interface_name ) over ( partition BY 1 ), '' ) AS interface_name,\n            AVG ( Tx_rate ) AS Tx_rate\n        FROM \n            (\n                -- VMs ethernet interface Rx rate\n                SELECT\n                    v4_4_configuration_history_vms_interfaces.vm_interface_id,\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN v4_4_configuration_history_vms_interfaces.vm_interface_name\n                        ELSE v4_4_configuration_history_vms_interfaces.vm_interface_name\n                    ||\n                    '*'\n                    END AS interface_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00') \n                    END AS num,\n                    AVG ( COALESCE ( transmit_rate_percent, 0 ) ) AS Tx_rate\n                FROM\n                    (\n                        SELECT history_datetime, vm_interface_id, transmit_rate_percent\n                        FROM v4_4_statistics_vms_interfaces_resources_usage_samples\n                    ) AS samples\n                    INNER JOIN v4_4_configuration_history_vms_interfaces\n                        ON \n                            (\n                                v4_4_configuration_history_vms_interfaces.vm_interface_id =\n                                samples.vm_interface_id\n                            )\n                WHERE\n                    history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    -- Here we get the latest vms interfaces configuration\n                    AND v4_4_configuration_history_vms_interfaces.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_vms_interfaces AS a\n                                GROUP BY a.vm_interface_id\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                        -- Here we get the top 3 utilised network interfaces for the vm chosen by the user\n                    AND v4_4_configuration_history_vms_interfaces.vm_interface_id \n                        IN \n                            (\n                                SELECT c.vm_interface_id\n                                FROM\n                                    (\n                                        SELECT history_datetime, vm_interface_id, receive_rate_percent, transmit_rate_percent\n                                        FROM v4_4_statistics_vms_interfaces_resources_usage_samples\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_vms_interfaces c\n                                        ON \n                                            (\n                                                c.vm_interface_id = \n                                                b.vm_interface_id\n                                            )\n                                    INNER JOIN\n                                    (\n                                        SELECT history_datetime, vm_configuration_version, vm_status, vm_id \n                                        FROM v4_4_statistics_vms_resources_usage_samples\n                                    ) AS d\n                                        ON \n                                            (\n                                                d.vm_configuration_version =\n                                                c.vm_configuration_version\n                                            )\n                                WHERE\n                                    -- Here we filter by active vms only\n                                    d.vm_status = 1\n                                    AND c.vm_interface_id \n                                        IN \n                                            (\n                                                SELECT device_id\n                                                FROM v4_4_configuration_history_vms_devices\n                                                WHERE\n                                                    -- Here we filter by the vm chosen by the user\n                                                    vm_id IN ($vm_id)\n                                                    AND create_date < $__timeTo()\n                                                    AND ( delete_date > $__timeFrom() OR delete_date IS NULL )\n                                                    -- Here we get the latest vms devices configuration\n                                                    AND history_id \n                                                        IN \n                                                            (\n                                                                SELECT MAX ( a.history_id )\n                                                                FROM v4_4_configuration_history_vms_devices a\n                                                                GROUP BY a.vm_id, a.device_id\n                                                            )\n                                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                                    -- in the \"show_deleted\" parameter        \n                                                    AND\n                                                        CASE\n                                                            WHEN '$show_deleted'='Yes'\n                                                                THEN 1=1\n                                                            WHEN '$show_deleted'='No'\n                                                                THEN delete_date isnull\n                                                        END\n                                            )\n                                    AND b.history_datetime >= $__timeFrom()\n                                    AND b.history_datetime < $__timeTo()\n                                    -- Here we get the latest vms interface configuration\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM  v4_4_configuration_history_vms_interfaces AS d\n                                                GROUP BY d.vm_interface_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                    GROUP BY c.vm_interface_id\n                                    ORDER BY\n                                    AVG ( COALESCE ( b.receive_rate_percent, 0 ) ) +\n                                    AVG ( COALESCE ( b.transmit_rate_percent, 0 ) ) \n                                    DESC\n                                LIMIT 3\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    v4_4_configuration_history_vms_interfaces.vm_interface_id,\n                    interface_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00') \n                    END\n            ) AS sub_query\n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')         \n        GROUP BY num, interface_name\n        ORDER BY num\n    ) AS all_sub_queries "
    },
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm,\n-- for the top 3 most utilized network interfaces,\n-- the Rx_rate and Tx_rate, by the hour of day and day of week.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Tx_rate\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    Tx_rate AS \"Transmit Rate\"\nFROM \n    (\n        SELECT DISTINCT\n            num,\n            COALESCE ( interface_name, MAX ( interface_name ) over ( partition BY 1 ), '' ) AS interface_name,\n            AVG ( Tx_rate ) AS Tx_rate\n        FROM \n            (\n                -- VMs ethernet interface Rx rate\n                SELECT\n                    v4_4_configuration_history_vms_interfaces.vm_interface_id,\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN v4_4_configuration_history_vms_interfaces.vm_interface_name\n                        ELSE v4_4_configuration_history_vms_interfaces.vm_interface_name\n                    ||\n                    '*'\n                    END AS interface_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00') \n                    END AS num,\n                    AVG ( COALESCE ( transmit_rate_percent, 0 ) ) AS Tx_rate\n                FROM\n                    (\n                            SELECT history_datetime, vm_interface_id, transmit_rate_percent\n                            FROM v4_4_statistics_vms_interfaces_resources_usage_hourly\n                        UNION\n                            SELECT history_datetime, vm_interface_id, transmit_rate_percent\n                            FROM v4_4_statistics_vms_interfaces_resources_usage_daily\n                            WHERE\n                                history_datetime <\n                                    (\n                                        SELECT MIN ( history_datetime )\n                                        FROM v4_4_statistics_vms_interfaces_resources_usage_hourly\n                                    )\n                    ) AS hourly_daily\n                    INNER JOIN v4_4_configuration_history_vms_interfaces\n                        ON \n                            (\n                                v4_4_configuration_history_vms_interfaces.vm_interface_id =\n                                hourly_daily.vm_interface_id\n                            )\n                WHERE\n                    history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    -- Here we get the latest vms interfaces configuration\n                    AND v4_4_configuration_history_vms_interfaces.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_vms_interfaces AS a\n                                GROUP BY a.vm_interface_id\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                        -- Here we get the top 3 utilised network interfaces for the vm chosen by the user\n                    AND v4_4_configuration_history_vms_interfaces.vm_interface_id \n                        IN \n                            (\n                                SELECT c.vm_interface_id\n                                FROM\n                                    (\n                                            SELECT history_datetime, vm_interface_id, receive_rate_percent, transmit_rate_percent\n                                            FROM v4_4_statistics_vms_interfaces_resources_usage_hourly\n                                        UNION\n                                            SELECT history_datetime, vm_interface_id, receive_rate_percent, transmit_rate_percent\n                                            FROM v4_4_statistics_vms_interfaces_resources_usage_daily\n                                            WHERE\n                                                history_datetime <\n                                                    (\n                                                        SELECT MIN ( history_datetime )\n                                                        FROM v4_4_statistics_vms_interfaces_resources_usage_hourly\n                                                    )\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_vms_interfaces c\n                                        ON \n                                            (\n                                                c.vm_interface_id = \n                                                b.vm_interface_id\n                                            )\n                                    INNER JOIN\n                                    (\n                                            SELECT history_datetime, vm_configuration_version, vm_status, vm_id \n                                            FROM v4_4_statistics_vms_resources_usage_hourly\n                                        UNION\n                                            SELECT history_datetime, vm_configuration_version, vm_status, vm_id\n                                            FROM v4_4_statistics_vms_resources_usage_daily\n                                            WHERE\n                                                history_datetime <\n                                                    (\n                                                        SELECT MIN ( history_datetime )\n                                                        FROM v4_4_statistics_vms_resources_usage_hourly\n                                                    )\n                                    ) AS d\n                                        ON \n                                            (\n                                                d.vm_configuration_version =\n                                                c.vm_configuration_version\n                                            )\n                                WHERE\n                                    -- Here we filter by active vms only\n                                    d.vm_status = 1\n                                    AND c.vm_interface_id \n                                        IN \n                                            (\n                                                SELECT device_id\n                                                FROM v4_4_configuration_history_vms_devices\n                                                WHERE\n                                                    -- Here we filter by the vm chosen by the user\n                                                    vm_id IN ($vm_id)\n                                                    AND create_date < $__timeTo()\n                                                    AND ( delete_date > $__timeFrom() OR delete_date IS NULL )\n                                                    -- Here we get the latest vms devices configuration\n                                                    AND history_id \n                                                        IN \n                                                            (\n                                                                SELECT MAX ( a.history_id )\n                                                                FROM v4_4_configuration_history_vms_devices a\n                                                                GROUP BY a.vm_id, a.device_id\n                                                            )\n                                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                                    -- in the \"show_deleted\" parameter        \n                                                    AND\n                                                        CASE\n                                                            WHEN '$show_deleted'='Yes'\n                                                                THEN 1=1\n                                                            WHEN '$show_deleted'='No'\n                                                                THEN delete_date isnull\n                                                        END\n                                            )\n                                    AND b.history_datetime >= $__timeFrom()\n                                    AND b.history_datetime < $__timeTo()\n                                    -- Here we get the latest vms interface configuration\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM  v4_4_configuration_history_vms_interfaces AS d\n                                                GROUP BY d.vm_interface_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                    GROUP BY c.vm_interface_id\n                                    ORDER BY\n                                    AVG ( COALESCE ( b.receive_rate_percent, 0 ) ) +\n                                    AVG ( COALESCE ( b.transmit_rate_percent, 0 ) ) \n                                    DESC\n                                LIMIT 3\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    v4_4_configuration_history_vms_interfaces.vm_interface_id,\n                    interface_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00') \n                    END\n            ) AS sub_query\n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY num, interface_name\n        ORDER BY num\n    ) AS all_sub_queries "
    }
   ]
  },
  {
   "title": "Top 3 Most Utilized Network Interfaces - Receive Rate (BR10C)",
   "type": "graph",
   "description": "This report displays for the top 3 most utilized network interfaces the average receive rate for a selected virtual machine within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm,\n-- for the top 3 most utilized network interfaces,\n-- the Rx_rate and Tx_rate, by the hour of day and day of week.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Rx_rate\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    Rx_rate AS \"Receive Rate\"\nFROM \n    (\n        SELECT DISTINCT\n            num,\n            COALESCE ( interface_name, MAX ( interface_name ) over ( partition BY 1 ), '' ) AS interface_name,\n            AVG ( Rx_rate ) AS Rx_rate\n        FROM \n            (\n                -- VMs ethernet interface Rx rate\n                SELECT\n                    v4_4_configuration_history_vms_interfaces.vm_interface_id,\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN v4_4_configuration_history_vms_interfaces.vm_interface_name\n                        ELSE v4_4_configuration_history_vms_interfaces.vm_interface_name\n                    ||\n                    '*'\n                    END AS interface_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00') \n                    END AS num,\n                    AVG ( COALESCE ( receive_rate_percent, 0 ) ) AS Rx_rate\n                FROM\n                    (\n                        SELECT history_datetime, vm_interface_id, receive_rate_percent\n                        FROM v4_4_statistics_vms_interfaces_resources_usage_samples\n                    ) AS samples\n                    INNER JOIN v4_4_configuration_history_vms_interfaces\n                        ON \n                            (\n                                v4_4_configuration_history_vms_interfaces.vm_interface_id =\n                                samples.vm_interface_id\n                            )\n                WHERE\n                    history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    -- Here we get the latest vms interfaces configuration\n                    AND v4_4_configuration_history_vms_interfaces.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_vms_interfaces AS a\n                                GROUP BY a.vm_interface_id\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                        -- Here we get the top 3 utilised network interfaces for the vm chosen by the user\n                    AND v4_4_configuration_history_vms_interfaces.vm_interface_id \n                        IN \n                            (\n                                SELECT c.vm_interface_id\n                                FROM\n                                    (\n                                        SELECT history_datetime, vm_interface_id, receive_rate_percent, transmit_rate_percent\n                                        FROM v4_4_statistics_vms_interfaces_resources_usage_samples\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_vms_interfaces c\n                                        ON \n                                            (\n                                                c.vm_interface_id = \n                                                b.vm_interface_id\n                                            )\n                                    INNER JOIN\n                                    (\n                                        SELECT history_datetime, vm_configuration_version, vm_status, vm_id\n                                        FROM v4_4_statistics_vms_resources_usage_samples\n                                    ) AS d\n                                        ON \n                                            (\n                                                d.vm_configuration_version =\n                                                c.vm_configuration_version\n                                            )\n                                WHERE\n                                    -- Here we filter by active vms only\n                                    d.vm_status = 1\n                                    AND c.vm_interface_id \n                                        IN \n                                            (\n                                                SELECT device_id\n                                                FROM v4_4_configuration_history_vms_devices\n                                                WHERE\n                                                    -- Here we filter by the vm chosen by the user\n                                                    vm_id IN ($vm_id)\n                                                    AND create_date < $__timeTo()\n                                                    AND ( delete_date > $__timeFrom() OR delete_date IS NULL )\n                                                    -- Here we get the latest vms devices configuration\n                                                    AND history_id \n                                                        IN \n                                                            (\n                                                                SELECT MAX ( a.history_id )\n                                                                FROM v4_4_configuration_history_vms_devices a\n                                                                GROUP BY a.vm_id, a.device_id\n                                                            )\n                                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                                    -- in the \"show_deleted\" parameter        \n                                                    AND\n                                                        CASE\n                                                            WHEN '$show_deleted'='Yes'\n                                                                THEN 1=1\n                                                            WHEN '$show_deleted'='No'\n                                                                THEN delete_date isnull\n                                                        END\n                                            )\n                                    AND b.history_datetime >= $__timeFrom()\n                                    AND b.history_datetime < $__timeTo()\n                                    -- Here we get the latest vms interface configuration\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM  v4_4_configuration_history_vms_interfaces AS d\n                                                GROUP BY d.vm_interface_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                    GROUP BY c.vm_interface_id\n                                    ORDER BY\n                                    AVG ( COALESCE ( b.receive_rate_percent, 0 ) ) +\n                                    AVG ( COALESCE ( b.transmit_rate_percent, 0 ) ) \n                                    DESC\n                                LIMIT 3\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    v4_4_configuration_history_vms_interfaces.vm_interface_id,\n                    interface_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00') \n                    END\n            ) AS sub_query\n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')         \n        GROUP BY num, interface_name\n        ORDER BY num\n    ) AS all_sub_queries "
    },
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm,\n-- for the top 3 most utilized network interfaces,\n-- the Rx_rate and Tx_rate, by the hour of day and day of week.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Rx_rate\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    Rx_rate AS \"Receive Rate\"\nFROM \n    (\n        SELECT DISTINCT\n            num,\n            COALESCE ( interface_name, MAX ( interface_name ) over ( partition BY 1 ), '' ) AS interface_name,\n            AVG ( Rx_rate ) AS Rx_rate\n        FROM \n            (\n                -- VMs ethernet interface Rx rate\n                SELECT\n                    v4_4_configuration_history_vms_interfaces.vm_interface_id,\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN v4_4_configuration_history_vms_interfaces.vm_interface_name\n                        ELSE v4_4_configuration_history_vms_interfaces.vm_interface_name\n                    ||\n                    '*'\n                    END AS interface_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00') \n                    END AS num,\n                    AVG ( COALESCE ( receive_rate_percent, 0 ) ) AS Rx_rate\n                FROM\n                    (\n                            SELECT history_datetime, vm_interface_id, receive_rate_percent\n                            FROM v4_4_statistics_vms_interfaces_resources_usage_hourly\n                        UNION\n                            SELECT history_datetime, vm_interface_id, receive_rate_percent\n                            FROM v4_4_statistics_vms_interfaces_resources_usage_daily\n                            WHERE\n                                history_datetime <\n                                    (\n                                        SELECT MIN ( history_datetime )\n                                        FROM v4_4_statistics_vms_interfaces_resources_usage_hourly\n                                    )\n                    ) AS hourly_daily\n                    INNER JOIN v4_4_configuration_history_vms_interfaces\n                        ON \n                            (\n                                v4_4_configuration_history_vms_interfaces.vm_interface_id =\n                                hourly_daily.vm_interface_id\n                            )\n                WHERE\n                    history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    -- Here we get the latest vms interfaces configuration\n                    AND v4_4_configuration_history_vms_interfaces.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_vms_interfaces AS a\n                                GROUP BY a.vm_interface_id\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                        -- Here we get the top 3 utilised network interfaces for the vm chosen by the user\n                    AND v4_4_configuration_history_vms_interfaces.vm_interface_id \n                        IN \n                            (\n                                SELECT c.vm_interface_id\n                                FROM\n                                    (\n                                            SELECT history_datetime, vm_interface_id, receive_rate_percent, transmit_rate_percent\n                                            FROM v4_4_statistics_vms_interfaces_resources_usage_hourly\n                                        UNION\n                                            SELECT history_datetime, vm_interface_id, receive_rate_percent, transmit_rate_percent \n                                            FROM v4_4_statistics_vms_interfaces_resources_usage_daily\n                                            WHERE\n                                                history_datetime <\n                                                    (\n                                                        SELECT MIN ( history_datetime )\n                                                        FROM v4_4_statistics_vms_interfaces_resources_usage_hourly\n                                                    )\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_vms_interfaces c\n                                        ON \n                                            (\n                                                c.vm_interface_id = \n                                                b.vm_interface_id\n                                            )\n                                    INNER JOIN\n                                    (\n                                            SELECT history_datetime, vm_configuration_version, vm_status, vm_id\n                                            FROM v4_4_statistics_vms_resources_usage_hourly\n                                        UNION\n                                            SELECT history_datetime, vm_configuration_version, vm_status, vm_id\n                                            FROM v4_4_statistics_vms_resources_usage_daily\n                                            WHERE\n                                                history_datetime <\n                                                    (\n                                                        SELECT MIN ( history_datetime )\n                                                        FROM v4_4_statistics_vms_resources_usage_hourly\n                                                    )\n                                    ) AS d\n                                        ON \n                                            (\n                                                d.vm_configuration_version =\n                                                c.vm_configuration_version\n                                            )\n                                WHERE\n                                    -- Here we filter by active vms only\n                                    d.vm_status = 1\n                                    AND c.vm_interface_id \n                                        IN \n                                            (\n                                                SELECT device_id\n                                                FROM v4_4_configuration_history_vms_devices\n                                                WHERE\n                                                    -- Here we filter by the vm chosen by the user\n                                                    vm_id IN ($vm_id)\n                                                    AND create_date < $__timeTo()\n                                                    AND ( delete_date > $__timeFrom() OR delete_date IS NULL )\n                                                    -- Here we get the latest vms devices configuration\n                                                    AND history_id \n                                                        IN \n                                                            (\n                                                                SELECT MAX ( a.history_id )\n                                                                FROM v4_4_configuration_history_vms_devices a\n                                                                GROUP BY a.vm_id, a.device_id\n                                                            )\n                                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                                    -- in the \"show_deleted\" parameter        \n                                                    AND\n                                                        CASE\n                                                            WHEN '$show_deleted'='Yes'\n                                                                THEN 1=1\n                                                            WHEN '$show_deleted'='No'\n                                                                THEN delete_date isnull\n                                                        END\n                                            )\n                                    AND b.history_datetime >= $__timeFrom()\n                                    AND b.history_datetime < $__timeTo()\n                                    -- Here we get the latest vms interface configuration\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM  v4_4_configuration_history_vms_interfaces AS d\n                                                GROUP BY d.vm_interface_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                    GROUP BY c.vm_interface_id\n                                    ORDER BY\n                                    AVG ( COALESCE ( b.receive_rate_percent, 0 ) ) +\n                                    AVG ( COALESCE ( b.transmit_rate_percent, 0 ) ) \n                                    DESC\n                                LIMIT 3\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    v4_4_configuration_history_vms_interfaces.vm_interface_id,\n                    interface_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00') \n                    END\n            ) AS sub_query\n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY num, interface_name\n        ORDER BY num\n    ) AS all_sub_queries "
    }
   ]
  },
  { "title": "Virtual Machine Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Top 5 Most Utilized Disks - Read Rate (BR10C)",
   "type": "graph",
   "description": "This report displays for the top 5 most utilized disks the average read rate for a selected virtual machine within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm,\n-- for the top 5 most utilized disks, the Read_Rate and Write_Rate\n-- by the hour of day and day of week.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Read rate\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    Read_Rate AS \"Read Rate\"\nFROM \n    (\n        SELECT DISTINCT\n            num,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' ) AS disk_name,\n            AVG ( Read_Rate ) AS Read_Rate\n        FROM \n            (\n                -- VMs Disk Usage ( I/O ) Rates\n                SELECT\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN vm_disk_name\n                        ELSE vm_disk_name\n                    ||\n                    '*'\n                    END AS disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00')\n                    END AS num,\n                    AVG ( ROUND ( CAST ( COALESCE ( read_rate_bytes_per_second, 0 ) AS FLOAT ) :: numeric / ( 1024 * 1024 ), 1 ) ) AS Read_Rate\n                FROM\n                    (\n                        SELECT history_datetime, vm_disk_id, read_rate_bytes_per_second\n                        FROM v4_4_statistics_vms_disks_resources_usage_samples\n                    ) AS samples\n                    INNER JOIN v4_4_configuration_history_vms_disks\n                        ON \n                            (\n                                v4_4_configuration_history_vms_disks.vm_disk_id =\n                                samples.vm_disk_id\n                            )\n                WHERE\n                    history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    -- Here we get the latest vms disks configuration\n                    AND v4_4_configuration_history_vms_disks.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_vms_disks AS a\n                                GROUP BY a.vm_disk_id\n                            )\n                    -- Here we get the top 5 utilised disks for the vm chosen by the user\n                    AND v4_4_configuration_history_vms_disks.vm_disk_id \n                        IN \n                            (\n                                SELECT c.vm_disk_id\n                                FROM\n                                    (\n                                        SELECT history_datetime, vm_disk_id, vm_disk_status, read_rate_bytes_per_second, write_rate_bytes_per_second\n                                        FROM v4_4_statistics_vms_disks_resources_usage_samples\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_vms_disks c\n                                        ON \n                                            (\n                                                c.vm_disk_id = \n                                                b.vm_disk_id\n                                            )\n                                WHERE\n                                    -- Here we filter by active vms disks only\n                                    b.vm_disk_status = 1\n                                    AND c.vm_disk_id \n                                        IN \n                                            (\n                                                SELECT device_id\n                                                FROM \n                                                    v4_4_configuration_history_vms_devices\n                                                    INNER JOIN\n                                                    (\n                                                        SELECT history_datetime, vm_configuration_version, vm_status, vm_id\n                                                        FROM v4_4_statistics_vms_resources_usage_samples\n                                                    ) AS samples_resources_usage\n                                                        ON \n                                                            (\n                                                                samples_resources_usage.vm_configuration_version =\n                                                                v4_4_configuration_history_vms_devices.vm_configuration_version\n                                                            )\n                                                WHERE\n                                                    -- Here we filter by active vms only\n                                                    samples_resources_usage.vm_status = 1\n                                                    -- Here we filter by the vm chosen by the user\n                                                    AND v4_4_configuration_history_vms_devices.vm_id IN ($vm_id)\n                                                    AND create_date < $__timeTo()\n                                                    AND ( delete_date > $__timeFrom() OR delete_date IS NULL )\n                                                    -- Here we get the latest vms devices configuration\n                                                    AND v4_4_configuration_history_vms_devices.history_id \n                                                        IN \n                                                            (\n                                                                SELECT MAX ( a.history_id )\n                                                                FROM v4_4_configuration_history_vms_devices a\n                                                                GROUP BY a.vm_id, a.device_id\n                                                            )\n                                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                                    -- in the \"show_deleted\" parameter\n                                                    AND\n                                                        CASE\n                                                            WHEN '$show_deleted'='Yes'\n                                                                THEN 1=1\n                                                            WHEN '$show_deleted'='No'\n                                                                THEN delete_date isnull\n                                                    END\n                                            )\n                                    AND history_datetime >= $__timeFrom()\n                                    AND history_datetime < $__timeTo()\n                                    -- Here we get the latest vms disks configuration\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM  v4_4_configuration_history_vms_disks AS d\n                                                GROUP BY d.vm_disk_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                GROUP BY c.vm_disk_id\n                                ORDER BY\n                                    AVG ( ROUND ( CAST ( COALESCE ( b.read_rate_bytes_per_second, 0 ) AS FLOAT ) :: numeric, 1 ) ) +\n                                    AVG ( ROUND ( CAST ( COALESCE ( b.write_rate_bytes_per_second, 0 ) AS FLOAT ) :: numeric, 1 ) ) \n                                    DESC\n                                LIMIT 5\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    samples.vm_disk_id, \n                    disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR ( history_datetime, 'D' )\n                        WHEN 2\n                            THEN TO_CHAR ( history_datetime, 'HH24:00' ) \n                    END\n            ) AS sub_query\n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')         \n        GROUP BY num, disk_name\n        ORDER BY\n            num ASC,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' )\n    ) AS all_sub_queries"
    },
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm,\n-- for the top 5 most utilized disks, the Read_Rate and Write_Rate\n-- by the hour of day and day of week.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Read rate\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    Read_Rate AS \"Read Rate\"\nFROM \n    (\n        SELECT DISTINCT\n            num,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' ) AS disk_name,\n            AVG ( Read_Rate ) AS Read_Rate\n        FROM \n            (\n                -- VMs Disk Usage ( I/O ) Rates\n                SELECT\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN vm_disk_name\n                        ELSE vm_disk_name\n                    ||\n                    '*'\n                    END AS disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00')\n                    END AS num,\n                    AVG ( ROUND ( CAST ( COALESCE ( read_rate_bytes_per_second, 0 ) AS FLOAT ) :: numeric / ( 1024 * 1024 ), 1 ) ) AS Read_Rate\n                FROM\n                    (\n                            SELECT history_datetime, vm_disk_id, read_rate_bytes_per_second\n                            FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                        UNION\n                            SELECT history_datetime, vm_disk_id, read_rate_bytes_per_second\n                            FROM v4_4_statistics_vms_disks_resources_usage_daily\n                            WHERE\n                                history_datetime <\n                                    (\n                                        SELECT MIN ( history_datetime )\n                                        FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                                    )\n                    ) AS hourly_daily\n                    INNER JOIN v4_4_configuration_history_vms_disks\n                        ON \n                            (\n                                v4_4_configuration_history_vms_disks.vm_disk_id =\n                                hourly_daily.vm_disk_id\n                            )\n                WHERE\n                    history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    -- Here we get the latest vms disks configuration\n                    AND v4_4_configuration_history_vms_disks.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_vms_disks AS a\n                                GROUP BY a.vm_disk_id\n                            )\n                    -- Here we get the top 5 utilised disks for the vm chosen by the user\n                    AND v4_4_configuration_history_vms_disks.vm_disk_id \n                        IN \n                            (\n                                SELECT c.vm_disk_id\n                                FROM\n                                    (\n                                            SELECT history_datetime, vm_disk_id, vm_disk_status, read_rate_bytes_per_second, write_rate_bytes_per_second\n                                            FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                                        UNION\n                                            SELECT history_datetime, vm_disk_id, vm_disk_status, read_rate_bytes_per_second, write_rate_bytes_per_second\n                                            FROM v4_4_statistics_vms_disks_resources_usage_daily\n                                            WHERE\n                                                history_datetime <\n                                                    (\n                                                        SELECT MIN ( history_datetime )\n                                                        FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                                                    )\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_vms_disks c\n                                        ON \n                                            (\n                                                c.vm_disk_id = \n                                                b.vm_disk_id\n                                            )\n                                WHERE\n                                    -- Here we filter by active vms disks only\n                                    b.vm_disk_status = 1\n                                    AND c.vm_disk_id \n                                        IN \n                                            (\n                                                SELECT device_id\n                                                FROM \n                                                    v4_4_configuration_history_vms_devices\n                                                    INNER JOIN\n                                                    (\n                                                            SELECT history_datetime, vm_configuration_version, vm_status, vm_id\n                                                            FROM v4_4_statistics_vms_resources_usage_hourly\n                                                        UNION\n                                                            SELECT history_datetime, vm_configuration_version, vm_status, vm_id\n                                                            FROM v4_4_statistics_vms_resources_usage_daily\n                                                            WHERE\n                                                                history_datetime <\n                                                                    (\n                                                                        SELECT MIN ( history_datetime )\n                                                                        FROM v4_4_statistics_vms_resources_usage_hourly\n                                                                    )\n                                                    ) AS hourly_daily_resources_usage\n                                                        ON \n                                                            (\n                                                                hourly_daily_resources_usage.vm_configuration_version =\n                                                                v4_4_configuration_history_vms_devices.vm_configuration_version\n                                                            )\n                                                WHERE\n                                                    -- Here we filter by active vms only\n                                                    hourly_daily_resources_usage.vm_status = 1\n                                                    -- Here we filter by the vm chosen by the user\n                                                    AND v4_4_configuration_history_vms_devices.vm_id IN ($vm_id)\n                                                    AND create_date < $__timeTo()\n                                                    AND ( delete_date > $__timeFrom() OR delete_date IS NULL )\n                                                    -- Here we get the latest vms devices configuration\n                                                    AND v4_4_configuration_history_vms_devices.history_id \n                                                        IN \n                                                            (\n                                                                SELECT MAX ( a.history_id )\n                                                                FROM v4_4_configuration_history_vms_devices a\n                                                                GROUP BY a.vm_id, a.device_id\n                                                            )\n                                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                                    -- in the \"show_deleted\" parameter\n                                                    AND\n                                                        CASE\n                                                            WHEN '$show_deleted'='Yes'\n                                                                THEN 1=1\n                                                            WHEN '$show_deleted'='No'\n                                                                THEN delete_date isnull\n                                                    END\n                                            )\n                                    AND history_datetime >= $__timeFrom()\n                                    AND history_datetime < $__timeTo()\n                                    -- Here we get the latest vms disks configuration\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM  v4_4_configuration_history_vms_disks AS d\n                                                GROUP BY d.vm_disk_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                GROUP BY c.vm_disk_id\n                                ORDER BY\n                                    AVG ( ROUND ( CAST ( COALESCE ( b.read_rate_bytes_per_second, 0 ) AS FLOAT ) :: numeric, 1 ) ) +\n                                    AVG ( ROUND ( CAST ( COALESCE ( b.write_rate_bytes_per_second, 0 ) AS FLOAT ) :: numeric, 1 ) ) \n                                    DESC\n                                LIMIT 5\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    hourly_daily.vm_disk_id, \n                    disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR ( history_datetime, 'D' )\n                        WHEN 2\n                            THEN TO_CHAR ( history_datetime, 'HH24:00' ) \n                    END\n            ) AS sub_query\n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY num, disk_name\n        ORDER BY\n            num ASC,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' )\n    ) AS all_sub_queries\n"
    }
   ]
  },
  {
   "title": "Top 5 Most Utilized Disks - Write Rate (BR10C)",
   "type": "graph",
   "description": "This report displays for the top 5 most utilized disks the average write rate for a selected virtual machine within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm,\n-- for the top 5 most utilized disks, the Read_Rate and Write_Rate\n-- by the hour of day and day of week.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Write rate\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    Write_Rate AS \"Write Rate\"\nFROM \n    (\n        SELECT DISTINCT\n            num,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' ) AS disk_name,\n            AVG ( Write_Rate ) AS Write_Rate\n        FROM \n            (\n                -- VMs Disk Usage ( I/O ) Rates\n                SELECT\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN vm_disk_name\n                        ELSE vm_disk_name\n                    ||\n                    '*'\n                    END AS disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00')\n                    END AS num,\n                    AVG ( ROUND ( CAST ( COALESCE ( write_rate_bytes_per_second, 0 ) AS FLOAT ) ::numeric / ( 1024 * 1024 ), 1 ) ) AS Write_Rate\n                FROM\n                    (\n                        SELECT history_datetime, vm_disk_id, write_rate_bytes_per_second\n                        FROM v4_4_statistics_vms_disks_resources_usage_samples\n                    ) AS samples\n                    INNER JOIN v4_4_configuration_history_vms_disks\n                        ON \n                            (\n                                v4_4_configuration_history_vms_disks.vm_disk_id =\n                                samples.vm_disk_id\n                            )\n                WHERE\n                    history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    -- Here we get the latest vms disks configuration\n                    AND v4_4_configuration_history_vms_disks.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_vms_disks AS a\n                                GROUP BY a.vm_disk_id\n                            )\n                    -- Here we get the top 5 utilised disks for the vm chosen by the user\n                    AND v4_4_configuration_history_vms_disks.vm_disk_id \n                        IN \n                            (\n                                SELECT c.vm_disk_id\n                                FROM\n                                    (\n                                        SELECT history_datetime, vm_disk_id, vm_disk_status, read_rate_bytes_per_second, write_rate_bytes_per_second \n                                        FROM v4_4_statistics_vms_disks_resources_usage_samples\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_vms_disks c\n                                        ON \n                                            (\n                                                c.vm_disk_id = \n                                                b.vm_disk_id\n                                            )\n                                WHERE\n                                    -- Here we filter by active vms disks only\n                                    b.vm_disk_status = 1\n                                    AND c.vm_disk_id \n                                        IN \n                                            (\n                                                SELECT device_id\n                                                FROM \n                                                    v4_4_configuration_history_vms_devices\n                                                    INNER JOIN\n                                                    (\n                                                        SELECT history_datetime, vm_configuration_version, vm_status, vm_id \n                                                        FROM v4_4_statistics_vms_resources_usage_samples\n                                                    ) AS samples_resources_usage\n                                                        ON \n                                                            (\n                                                                samples_resources_usage.vm_configuration_version =\n                                                                v4_4_configuration_history_vms_devices.vm_configuration_version\n                                                            )\n                                                WHERE\n                                                    -- Here we filter by active vms only\n                                                    samples_resources_usage.vm_status = 1\n                                                    -- Here we filter by the vm chosen by the user\n                                                    AND v4_4_configuration_history_vms_devices.vm_id IN ($vm_id)\n                                                    AND create_date < $__timeTo()\n                                                    AND ( delete_date > $__timeFrom() OR delete_date IS NULL )\n                                                    -- Here we get the latest vms devices configuration\n                                                    AND v4_4_configuration_history_vms_devices.history_id \n                                                        IN \n                                                            (\n                                                                SELECT MAX ( a.history_id )\n                                                                FROM v4_4_configuration_history_vms_devices a\n                                                                GROUP BY a.vm_id, a.device_id\n                                                            )\n                                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                                    -- in the \"show_deleted\" parameter\n                                                    AND\n                                                        CASE\n                                                            WHEN '$show_deleted'='Yes'\n                                                                THEN 1=1\n                                                            WHEN '$show_deleted'='No'\n                                                                THEN delete_date isnull\n                                                    END\n                                            )\n                                    AND history_datetime >= $__timeFrom()\n                                    AND history_datetime < $__timeTo()\n                                    -- Here we get the latest vms disks configuration\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM  v4_4_configuration_history_vms_disks AS d\n                                                GROUP BY d.vm_disk_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                GROUP BY c.vm_disk_id\n                                ORDER BY\n                                    AVG ( ROUND ( CAST ( COALESCE ( b.read_rate_bytes_per_second, 0 ) AS FLOAT ) :: numeric, 1 ) ) +\n                                    AVG ( ROUND ( CAST ( COALESCE ( b.write_rate_bytes_per_second, 0 ) AS FLOAT ) :: numeric, 1 ) ) \n                                    DESC\n                                LIMIT 5\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    samples.vm_disk_id, \n                    disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00')\n                    END\n            ) AS sub_query\n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')         \n        GROUP BY num, disk_name\n        ORDER BY\n            num ASC,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' )\n    ) AS all_sub_queries"
    },
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm,\n-- for the top 5 most utilized disks, the Read_Rate and Write_Rate\n-- by the hour of day and day of week.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Write rate\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    Write_Rate AS \"Write Rate\"\nFROM \n    (\n        SELECT DISTINCT\n            num,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' ) AS disk_name,\n            AVG ( Write_Rate ) AS Write_Rate\n        FROM \n            (\n                -- VMs Disk Usage ( I/O ) Rates\n                SELECT\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN vm_disk_name\n                        ELSE vm_disk_name\n                    ||\n                    '*'\n                    END AS disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00')\n                    END AS num,\n                    AVG ( ROUND ( CAST ( COALESCE ( write_rate_bytes_per_second, 0 ) AS FLOAT ) ::numeric / ( 1024 * 1024 ), 1 ) ) AS Write_Rate\n                FROM\n                    (\n                            SELECT history_datetime, vm_disk_id, write_rate_bytes_per_second\n                            FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                        UNION\n                            SELECT history_datetime, vm_disk_id, write_rate_bytes_per_second\n                            FROM v4_4_statistics_vms_disks_resources_usage_daily\n                            WHERE\n                                history_datetime <\n                                    (\n                                        SELECT MIN ( history_datetime )\n                                        FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                                    )\n                    ) AS hourly_daily\n                    INNER JOIN v4_4_configuration_history_vms_disks\n                        ON \n                            (\n                                v4_4_configuration_history_vms_disks.vm_disk_id =\n                                hourly_daily.vm_disk_id\n                            )\n                WHERE\n                    history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    -- Here we get the latest vms disks configuration\n                    AND v4_4_configuration_history_vms_disks.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_vms_disks AS a\n                                GROUP BY a.vm_disk_id\n                            )\n                    -- Here we get the top 5 utilised disks for the vm chosen by the user\n                    AND v4_4_configuration_history_vms_disks.vm_disk_id \n                        IN \n                            (\n                                SELECT c.vm_disk_id\n                                FROM\n                                    (\n                                            SELECT history_datetime, vm_disk_id, vm_disk_status, read_rate_bytes_per_second, write_rate_bytes_per_second \n                                            FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                                        UNION\n                                            SELECT history_datetime, vm_disk_id, vm_disk_status, read_rate_bytes_per_second, write_rate_bytes_per_second \n                                            FROM v4_4_statistics_vms_disks_resources_usage_daily\n                                            WHERE\n                                                history_datetime <\n                                                    (\n                                                        SELECT MIN ( history_datetime )\n                                                        FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                                                    )\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_vms_disks c\n                                        ON \n                                            (\n                                                c.vm_disk_id = \n                                                b.vm_disk_id\n                                            )\n                                WHERE\n                                    -- Here we filter by active vms disks only\n                                    b.vm_disk_status = 1\n                                    AND c.vm_disk_id \n                                        IN \n                                            (\n                                                SELECT device_id\n                                                FROM \n                                                    v4_4_configuration_history_vms_devices\n                                                    INNER JOIN\n                                                    (\n                                                            SELECT history_datetime, vm_configuration_version, vm_status, vm_id \n                                                            FROM v4_4_statistics_vms_resources_usage_hourly\n                                                        UNION\n                                                            SELECT history_datetime, vm_configuration_version, vm_status, vm_id\n                                                            FROM v4_4_statistics_vms_resources_usage_daily\n                                                            WHERE\n                                                                history_datetime <\n                                                                    (\n                                                                        SELECT MIN ( history_datetime )\n                                                                        FROM v4_4_statistics_vms_resources_usage_hourly\n                                                                    )\n                                                    ) AS hourly_daily_resources_usage\n                                                        ON \n                                                            (\n                                                                hourly_daily_resources_usage.vm_configuration_version =\n                                                                v4_4_configuration_history_vms_devices.vm_configuration_version\n                                                            )\n                                                WHERE\n                                                    -- Here we filter by active vms only\n                                                    hourly_daily_resources_usage.vm_status = 1\n                                                    -- Here we filter by the vm chosen by the user\n                                                    AND v4_4_configuration_history_vms_devices.vm_id IN ($vm_id)\n                                                    AND create_date < $__timeTo()\n                                                    AND ( delete_date > $__timeFrom() OR delete_date IS NULL )\n                                                    -- Here we get the latest vms devices configuration\n                                                    AND v4_4_configuration_history_vms_devices.history_id \n                                                        IN \n                                                            (\n                                                                SELECT MAX ( a.history_id )\n                                                                FROM v4_4_configuration_history_vms_devices a\n                                                                GROUP BY a.vm_id, a.device_id\n                                                            )\n                                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                                    -- in the \"show_deleted\" parameter\n                                                    AND\n                                                        CASE\n                                                            WHEN '$show_deleted'='Yes'\n                                                                THEN 1=1\n                                                            WHEN '$show_deleted'='No'\n                                                                THEN delete_date isnull\n                                                    END\n                                            )\n                                    AND history_datetime >= $__timeFrom()\n                                    AND history_datetime < $__timeTo()\n                                    -- Here we get the latest vms disks configuration\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM  v4_4_configuration_history_vms_disks AS d\n                                                GROUP BY d.vm_disk_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                GROUP BY c.vm_disk_id\n                                ORDER BY\n                                    AVG ( ROUND ( CAST ( COALESCE ( b.read_rate_bytes_per_second, 0 ) AS FLOAT ) :: numeric, 1 ) ) +\n                                    AVG ( ROUND ( CAST ( COALESCE ( b.write_rate_bytes_per_second, 0 ) AS FLOAT ) :: numeric, 1 ) ) \n                                    DESC\n                                LIMIT 5\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    hourly_daily.vm_disk_id, \n                    disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00')\n                    END\n            ) AS sub_query\n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY num, disk_name\n        ORDER BY\n            num ASC,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' )\n    ) AS all_sub_queries"
    }
   ]
  },
  {
   "title": "Top 5 Most Utilized Disks - Read I/O operations/sec (over time) (over time) (BR10C)",
   "type": "graph",
   "description": "This report displays for the top 5 most utilized disks the average read operations per second for a selected virtual machine within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm,\n-- for the top 5 most utilized disks, the Read_ops and Write_ops\n-- by the hour of day and day of week.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Read ops\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    Read_ops AS \"Read ops\"\nFROM \n    (\n        SELECT DISTINCT\n            num,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' ) AS disk_name,\n            AVG ( Read_ops ) AS Read_ops\n        FROM \n            (\n                -- VMs Disk Usage ( I/O ) Rates\n                SELECT\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN vm_disk_name\n                        ELSE vm_disk_name\n                    ||\n                    '*'\n                    END AS disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00')\n                    END AS num,\n                    AVG ( COALESCE ( read_ops_per_second, 0 ) ) AS Read_ops\n                FROM\n                    (\n                        SELECT history_datetime, vm_disk_id, read_ops_per_second\n                        FROM v4_4_statistics_vms_disks_resources_usage_samples\n                    ) AS samples\n                    INNER JOIN v4_4_configuration_history_vms_disks\n                        ON \n                            (\n                                v4_4_configuration_history_vms_disks.vm_disk_id =\n                                samples.vm_disk_id\n                            )\n                WHERE\n                    history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    -- Here we get the latest vms disks configuration\n                    AND v4_4_configuration_history_vms_disks.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_vms_disks AS a\n                                GROUP BY a.vm_disk_id\n                            )\n                    -- Here we get the top 5 utilised disks for the vm chosen by the user\n                    AND v4_4_configuration_history_vms_disks.vm_disk_id \n                        IN \n                            (\n                                SELECT c.vm_disk_id\n                                FROM\n                                    (\n                                        SELECT history_datetime, vm_disk_id, vm_disk_status, read_ops_per_second, write_ops_per_second\n                                        FROM v4_4_statistics_vms_disks_resources_usage_samples\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_vms_disks c\n                                        ON \n                                            (\n                                                c.vm_disk_id = \n                                                b.vm_disk_id\n                                            )\n                                WHERE\n                                    -- Here we filter by active vms disks only\n                                    b.vm_disk_status = 1\n                                    AND c.vm_disk_id \n                                        IN \n                                            (\n                                                SELECT device_id\n                                                FROM \n                                                    v4_4_configuration_history_vms_devices\n                                                    INNER JOIN\n                                                    (\n                                                        SELECT history_datetime, vm_configuration_version, vm_status, vm_id\n                                                        FROM v4_4_statistics_vms_resources_usage_samples\n                                                    ) AS samples_resources_usage\n                                                        ON \n                                                            (\n                                                                samples_resources_usage.vm_configuration_version =\n                                                                v4_4_configuration_history_vms_devices.vm_configuration_version\n                                                            )\n                                                WHERE\n                                                    -- Here we filter by active vms only\n                                                    samples_resources_usage.vm_status = 1\n                                                    -- Here we filter by the vm chosen by the user\n                                                    AND v4_4_configuration_history_vms_devices.vm_id IN ($vm_id)\n                                                    AND create_date < $__timeTo()\n                                                    AND ( delete_date > $__timeFrom() OR delete_date IS NULL )\n                                                    -- Here we get the latest vms devices configuration\n                                                    AND v4_4_configuration_history_vms_devices.history_id \n                                                        IN \n                                                            (\n                                                                SELECT MAX ( a.history_id )\n                                                                FROM v4_4_configuration_history_vms_devices a\n                                                                GROUP BY a.vm_id, a.device_id\n                                                            )\n                                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                                    -- in the \"show_deleted\" parameter\n                                                    AND\n                                                        CASE\n                                                            WHEN '$show_deleted'='Yes'\n                                                                THEN 1=1\n                                                            WHEN '$show_deleted'='No'\n                                                                THEN delete_date isnull\n                                                    END\n                                            )\n                                    AND history_datetime >= $__timeFrom()\n                                    AND history_datetime < $__timeTo()\n                                    -- Here we get the latest vms disks configuration\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM  v4_4_configuration_history_vms_disks AS d\n                                                GROUP BY d.vm_disk_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                GROUP BY c.vm_disk_id\n                                ORDER BY\n                                    AVG ( COALESCE ( b.read_ops_per_second, 0 ) ) +\n                                    AVG ( COALESCE ( b.write_ops_per_second, 0 ) ) \n                                    DESC\n                                LIMIT 5\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    samples.vm_disk_id, \n                    disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR ( history_datetime, 'D' )\n                        WHEN 2\n                            THEN TO_CHAR ( history_datetime, 'HH24:00' ) \n                    END\n            ) AS sub_query\n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')         \n        GROUP BY num, disk_name\n        ORDER BY\n            num ASC,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' )\n    ) AS all_sub_queries"
    },
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm,\n-- for the top 5 most utilized disks, the Read_ops and Write_ops\n-- by the hour of day and day of week.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Read ops\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    Read_ops AS \"Read ops\"\nFROM \n    (\n        SELECT DISTINCT\n            num,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' ) AS disk_name,\n            AVG ( Read_ops ) AS Read_ops\n        FROM \n            (\n                -- VMs Disk Usage ( I/O ) Rates\n                SELECT\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN vm_disk_name\n                        ELSE vm_disk_name\n                    ||\n                    '*'\n                    END AS disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00')\n                    END AS num,\n                    AVG ( COALESCE ( read_ops_per_second, 0 ) ) AS Read_ops\n                FROM\n                    (\n                            SELECT history_datetime, vm_disk_id, read_ops_per_second\n                            FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                        UNION\n                            SELECT history_datetime, vm_disk_id, read_ops_per_second\n                            FROM v4_4_statistics_vms_disks_resources_usage_daily\n                            WHERE\n                                history_datetime <\n                                    (\n                                        SELECT MIN ( history_datetime )\n                                        FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                                    )\n                    ) AS hourly_daily\n                    INNER JOIN v4_4_configuration_history_vms_disks\n                        ON \n                            (\n                                v4_4_configuration_history_vms_disks.vm_disk_id =\n                                hourly_daily.vm_disk_id\n                            )\n                WHERE\n                    history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    -- Here we get the latest vms disks configuration\n                    AND v4_4_configuration_history_vms_disks.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_vms_disks AS a\n                                GROUP BY a.vm_disk_id\n                            )\n                    -- Here we get the top 5 utilised disks for the vm chosen by the user\n                    AND v4_4_configuration_history_vms_disks.vm_disk_id \n                        IN \n                            (\n                                SELECT c.vm_disk_id\n                                FROM\n                                    (\n                                            SELECT history_datetime, vm_disk_id, vm_disk_status, read_ops_per_second, write_ops_per_second\n                                            FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                                        UNION\n                                            SELECT history_datetime, vm_disk_id, vm_disk_status, read_ops_per_second, write_ops_per_second\n                                            FROM v4_4_statistics_vms_disks_resources_usage_daily\n                                            WHERE\n                                                history_datetime <\n                                                    (\n                                                        SELECT MIN ( history_datetime )\n                                                        FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                                                    )\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_vms_disks c\n                                        ON \n                                            (\n                                                c.vm_disk_id = \n                                                b.vm_disk_id\n                                            )\n                                WHERE\n                                    -- Here we filter by active vms disks only\n                                    b.vm_disk_status = 1\n                                    AND c.vm_disk_id \n                                        IN \n                                            (\n                                                SELECT device_id\n                                                FROM \n                                                    v4_4_configuration_history_vms_devices\n                                                    INNER JOIN\n                                                    (\n                                                            SELECT history_datetime, vm_configuration_version, vm_status, vm_id\n                                                            FROM v4_4_statistics_vms_resources_usage_hourly\n                                                        UNION\n                                                            SELECT history_datetime, vm_configuration_version, vm_status, vm_id\n                                                            FROM v4_4_statistics_vms_resources_usage_daily\n                                                            WHERE\n                                                                history_datetime <\n                                                                    (\n                                                                        SELECT MIN ( history_datetime )\n                                                                        FROM v4_4_statistics_vms_resources_usage_hourly\n                                                                    )\n                                                    ) AS hourly_daily_resources_usage\n                                                        ON \n                                                            (\n                                                                hourly_daily_resources_usage.vm_configuration_version =\n                                                                v4_4_configuration_history_vms_devices.vm_configuration_version\n                                                            )\n                                                WHERE\n                                                    -- Here we filter by active vms only\n                                                    hourly_daily_resources_usage.vm_status = 1\n                                                    -- Here we filter by the vm chosen by the user\n                                                    AND v4_4_configuration_history_vms_devices.vm_id IN ($vm_id)\n                                                    AND create_date < $__timeTo()\n                                                    AND ( delete_date > $__timeFrom() OR delete_date IS NULL )\n                                                    -- Here we get the latest vms devices configuration\n                                                    AND v4_4_configuration_history_vms_devices.history_id \n                                                        IN \n                                                            (\n                                                                SELECT MAX ( a.history_id )\n                                                                FROM v4_4_configuration_history_vms_devices a\n                                                                GROUP BY a.vm_id, a.device_id\n                                                            )\n                                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                                    -- in the \"show_deleted\" parameter\n                                                    AND\n                                                        CASE\n                                                            WHEN '$show_deleted'='Yes'\n                                                                THEN 1=1\n                                                            WHEN '$show_deleted'='No'\n                                                                THEN delete_date isnull\n                                                    END\n                                            )\n                                    AND history_datetime >= $__timeFrom()\n                                    AND history_datetime < $__timeTo()\n                                    -- Here we get the latest vms disks configuration\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM  v4_4_configuration_history_vms_disks AS d\n                                                GROUP BY d.vm_disk_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                GROUP BY c.vm_disk_id\n                                ORDER BY\n                                    AVG ( COALESCE ( b.read_ops_per_second, 0 ) ) +\n                                    AVG ( COALESCE ( b.write_ops_per_second, 0 ) ) \n                                    DESC\n                                LIMIT 5\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    hourly_daily.vm_disk_id, \n                    disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR ( history_datetime, 'D' )\n                        WHEN 2\n                            THEN TO_CHAR ( history_datetime, 'HH24:00' ) \n                    END\n            ) AS sub_query\n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY num, disk_name\n        ORDER BY\n            num ASC,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' )\n    ) AS all_sub_queries"
    }
   ]
  },
  {
   "title": "Top 5 Most Utilized Disks - Write I/O operations/sec (over time) (BR10C)",
   "type": "graph",
   "description": "This report displays for the top 5 most utilized disks the average write operations per second for a selected virtual machine within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm,\n-- for the top 5 most utilized disks, the Read_ops and Write_ops\n-- by the hour of day and day of week.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Write ops\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    Write_ops AS \"Write ops\"\nFROM \n    (\n        SELECT DISTINCT\n            num,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' ) AS disk_name,\n            AVG ( Write_ops ) AS Write_ops\n        FROM \n            (\n                -- VMs Disk Usage ( I/O ) Rates\n                SELECT\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN vm_disk_name\n                        ELSE vm_disk_name\n                    ||\n                    '*'\n                    END AS disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00')\n                    END AS num,\n                    AVG ( COALESCE ( write_ops_per_second, 0 ) ) AS Write_ops\n                FROM\n                    (\n                        SELECT history_datetime, vm_disk_id, write_ops_per_second\n                        FROM v4_4_statistics_vms_disks_resources_usage_samples\n                    ) AS samples\n                    INNER JOIN v4_4_configuration_history_vms_disks\n                        ON \n                            (\n                                v4_4_configuration_history_vms_disks.vm_disk_id =\n                                samples.vm_disk_id\n                            )\n                WHERE\n                    history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    -- Here we get the latest vms disks configuration\n                    AND v4_4_configuration_history_vms_disks.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_vms_disks AS a\n                                GROUP BY a.vm_disk_id\n                            )\n                    -- Here we get the top 5 utilised disks for the vm chosen by the user\n                    AND v4_4_configuration_history_vms_disks.vm_disk_id \n                        IN \n                            (\n                                SELECT c.vm_disk_id\n                                FROM\n                                    (\n                                        SELECT history_datetime, vm_disk_id, vm_disk_status, read_ops_per_second, write_ops_per_second \n                                        FROM v4_4_statistics_vms_disks_resources_usage_samples\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_vms_disks c\n                                        ON \n                                            (\n                                                c.vm_disk_id = \n                                                b.vm_disk_id\n                                            )\n                                WHERE\n                                    -- Here we filter by active vms disks only\n                                    b.vm_disk_status = 1\n                                    AND c.vm_disk_id \n                                        IN \n                                            (\n                                                SELECT device_id\n                                                FROM \n                                                    v4_4_configuration_history_vms_devices\n                                                    INNER JOIN\n                                                    (\n                                                        SELECT history_datetime, vm_configuration_version, vm_status, vm_id \n                                                        FROM v4_4_statistics_vms_resources_usage_samples\n                                                    ) AS samples_resources_usage\n                                                        ON \n                                                            (\n                                                                samples_resources_usage.vm_configuration_version =\n                                                                v4_4_configuration_history_vms_devices.vm_configuration_version\n                                                            )\n                                                WHERE\n                                                    -- Here we filter by active vms only\n                                                    samples_resources_usage.vm_status = 1\n                                                    -- Here we filter by the vm chosen by the user\n                                                    AND v4_4_configuration_history_vms_devices.vm_id IN ($vm_id)\n                                                    AND create_date < $__timeTo()\n                                                    AND ( delete_date > $__timeFrom() OR delete_date IS NULL )\n                                                    -- Here we get the latest vms devices configuration\n                                                    AND v4_4_configuration_history_vms_devices.history_id \n                                                        IN \n                                                            (\n                                                                SELECT MAX ( a.history_id )\n                                                                FROM v4_4_configuration_history_vms_devices a\n                                                                GROUP BY a.vm_id, a.device_id\n                                                            )\n                                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                                    -- in the \"show_deleted\" parameter\n                                                    AND\n                                                        CASE\n                                                            WHEN '$show_deleted'='Yes'\n                                                                THEN 1=1\n                                                            WHEN '$show_deleted'='No'\n                                                                THEN delete_date isnull\n                                                    END\n                                            )\n                                    AND history_datetime >= $__timeFrom()\n                                    AND history_datetime < $__timeTo()\n                                    -- Here we get the latest vms disks configuration\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM  v4_4_configuration_history_vms_disks AS d\n                                                GROUP BY d.vm_disk_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                GROUP BY c.vm_disk_id\n                                ORDER BY\n                                    AVG ( COALESCE ( b.read_ops_per_second, 0 ) ) +\n                                    AVG ( COALESCE ( b.write_ops_per_second, 0 ) ) \n                                    DESC\n                                LIMIT 5\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    samples.vm_disk_id, \n                    disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00')\n                    END\n            ) AS sub_query\n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')         \n        GROUP BY num, disk_name\n        ORDER BY\n            num ASC,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' )\n    ) AS all_sub_queries"
    },
    {
     "rawSql": "-- BR10C - This query returns for the chosen vm,\n-- for the top 5 most utilized disks, the Read_ops and Write_ops\n-- by the hour of day and day of week.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Write ops\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST ( num AS INT )\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    Write_ops AS \"Write ops\"\nFROM \n    (\n        SELECT DISTINCT\n            num,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' ) AS disk_name,\n            AVG ( Write_ops ) AS Write_ops\n        FROM \n            (\n                -- VMs Disk Usage ( I/O ) Rates\n                SELECT\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN vm_disk_name\n                        ELSE vm_disk_name\n                    ||\n                    '*'\n                    END AS disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00')\n                    END AS num,\n                    AVG ( COALESCE ( write_ops_per_second, 0 ) ) AS Write_ops\n                FROM\n                    (\n                            SELECT history_datetime, vm_disk_id, write_ops_per_second\n                            FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                        UNION\n                            SELECT history_datetime, vm_disk_id, write_ops_per_second\n                            FROM v4_4_statistics_vms_disks_resources_usage_daily\n                            WHERE\n                                history_datetime <\n                                    (\n                                        SELECT MIN ( history_datetime )\n                                        FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                                    )\n                    ) AS hourly_daily\n                    INNER JOIN v4_4_configuration_history_vms_disks\n                        ON \n                            (\n                                v4_4_configuration_history_vms_disks.vm_disk_id =\n                                hourly_daily.vm_disk_id\n                            )\n                WHERE\n                    history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    -- Here we get the latest vms disks configuration\n                    AND v4_4_configuration_history_vms_disks.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_vms_disks AS a\n                                GROUP BY a.vm_disk_id\n                            )\n                    -- Here we get the top 5 utilised disks for the vm chosen by the user\n                    AND v4_4_configuration_history_vms_disks.vm_disk_id \n                        IN \n                            (\n                                SELECT c.vm_disk_id\n                                FROM\n                                    (\n                                            SELECT history_datetime, vm_disk_id, vm_disk_status, read_ops_per_second, write_ops_per_second \n                                            FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                                        UNION\n                                            SELECT history_datetime, vm_disk_id, vm_disk_status, read_ops_per_second, write_ops_per_second \n                                            FROM v4_4_statistics_vms_disks_resources_usage_daily\n                                            WHERE\n                                                history_datetime <\n                                                    (\n                                                        SELECT MIN ( history_datetime )\n                                                        FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                                                    )\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_vms_disks c\n                                        ON \n                                            (\n                                                c.vm_disk_id = \n                                                b.vm_disk_id\n                                            )\n                                WHERE\n                                    -- Here we filter by active vms disks only\n                                    b.vm_disk_status = 1\n                                    AND c.vm_disk_id \n                                        IN \n                                            (\n                                                SELECT device_id\n                                                FROM \n                                                    v4_4_configuration_history_vms_devices\n                                                    INNER JOIN\n                                                    (\n                                                            SELECT history_datetime, vm_configuration_version, vm_status, vm_id \n                                                            FROM v4_4_statistics_vms_resources_usage_hourly\n                                                        UNION\n                                                            SELECT history_datetime, vm_configuration_version, vm_status, vm_id\n                                                            FROM v4_4_statistics_vms_resources_usage_daily\n                                                            WHERE\n                                                                history_datetime <\n                                                                    (\n                                                                        SELECT MIN ( history_datetime )\n                                                                        FROM v4_4_statistics_vms_resources_usage_hourly\n                                                                    )\n                                                    ) AS hourly_daily_resources_usage\n                                                        ON \n                                                            (\n                                                                hourly_daily_resources_usage.vm_configuration_version =\n                                                                v4_4_configuration_history_vms_devices.vm_configuration_version\n                                                            )\n                                                WHERE\n                                                    -- Here we filter by active vms only\n                                                    hourly_daily_resources_usage.vm_status = 1\n                                                    -- Here we filter by the vm chosen by the user\n                                                    AND v4_4_configuration_history_vms_devices.vm_id IN ($vm_id)\n                                                    AND create_date < $__timeTo()\n                                                    AND ( delete_date > $__timeFrom() OR delete_date IS NULL )\n                                                    -- Here we get the latest vms devices configuration\n                                                    AND v4_4_configuration_history_vms_devices.history_id \n                                                        IN \n                                                            (\n                                                                SELECT MAX ( a.history_id )\n                                                                FROM v4_4_configuration_history_vms_devices a\n                                                                GROUP BY a.vm_id, a.device_id\n                                                            )\n                                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                                    -- in the \"show_deleted\" parameter\n                                                    AND\n                                                        CASE\n                                                            WHEN '$show_deleted'='Yes'\n                                                                THEN 1=1\n                                                            WHEN '$show_deleted'='No'\n                                                                THEN delete_date isnull\n                                                    END\n                                            )\n                                    AND history_datetime >= $__timeFrom()\n                                    AND history_datetime < $__timeTo()\n                                    -- Here we get the latest vms disks configuration\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM  v4_4_configuration_history_vms_disks AS d\n                                                GROUP BY d.vm_disk_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                GROUP BY c.vm_disk_id\n                                ORDER BY\n                                    AVG ( COALESCE ( b.read_ops_per_second, 0 ) ) +\n                                    AVG ( COALESCE ( b.write_ops_per_second, 0 ) ) \n                                    DESC\n                                LIMIT 5\n                            )\n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    hourly_daily.vm_disk_id, \n                    disk_name,\n                    CASE $period_id\n                        WHEN 1\n                            THEN TO_CHAR (history_datetime, 'D')\n                        WHEN 2\n                            THEN TO_CHAR (history_datetime, 'HH24:00')\n                    END\n            ) AS sub_query\n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY num, disk_name\n        ORDER BY\n            num ASC,\n            COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' )\n    ) AS all_sub_queries"
    }
   ]
  }
 ]
}