{
 "title": "RHV - System Dashboard (Не удалять до запроса)",
 "description": "На системном экране мониторинга отображаются последние конфигурации, состояние ресурсов системных объектов и процент использования. Ответственный:  Альбещенко М.Н. (АЦОД)",
 "tags": [
  "RHV",
  "Virtualization",
  "system",
  "Warehouse",
  "scripts"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Entities (DR1) ",
   "type": "table-old",
   "description": "System entities counts list. The number of data centers, clusters, hosts, virtual machines, and storage domains. ",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "-- DR1 - This query returns entities count per entity\n\nSELECT \n    (\n        SELECT COUNT ( * )\n        FROM v4_4_latest_configuration_datacenters\n    ) AS datacenter_count,\n    (\n        SELECT COUNT ( * )\n        FROM v4_4_latest_configuration_clusters\n    ) AS cluster_count,\n    (\n        SELECT COUNT ( * )\n        FROM v4_4_latest_configuration_hosts\n    ) AS host_count,\n    (\n        SELECT COUNT ( * )\n        FROM v4_4_latest_configuration_vms\n    ) AS vm_count"
    },
    {
     "rawSql": "-- DR1 - This query returns the total count of storage domains\n\nSELECT\n    COUNT ( DISTINCT v4_4_latest_map_datacenters_storage_domains.storage_domain_id ) AS storage_count\nFROM \n    v4_4_latest_map_datacenters_storage_domains"
    }
   ]
  },
  {
   "title": "System Host CPU Usage (DR10)",
   "type": "singlestat",
   "description": "Average percentage of CPU usage for all hosts in the system. The thresholds are 60% and 80%. This report shows the latest configuration.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- DR10 - This query returns the average\n-- hosts resources ( cpu and memory ) that are used,\n-- in the latest configuration.\n\nSELECT \n    cpu_usage_percent_avg AS average_cpu_used\nFROM \n    (\n        SELECT\n            AVG ( cpu_usage_percent ) AS cpu_usage_percent_avg\n        FROM \n            v4_4_statistics_hosts_resources_usage_samples\n            INNER JOIN v4_4_latest_configuration_hosts\n                ON \n                    (\n                        v4_4_latest_configuration_hosts.host_id =\n                        v4_4_statistics_hosts_resources_usage_samples.host_id\n                    )\n        WHERE\n            -- Here we filter only active hosts\n            v4_4_statistics_hosts_resources_usage_samples.host_status = 1  \n    ) AS average_cpu_percent"
    }
   ]
  },
  {
   "title": "System Host Memory Usage (DR10)",
   "type": "singlestat",
   "description": "Average percentage of memory usage for all hosts in the system. The thresholds are 60% and 80%. This report shows the latest configuration.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- DR10 - This query returns the average\n-- hosts resources ( cpu and memory ) that are used,\n-- in the latest configuration.\n\nSELECT\n    memory_usage_percent_avg AS average_memory_used\nFROM \n    (\n        SELECT\n            AVG ( memory_usage_percent ) AS memory_usage_percent_avg\n        FROM \n            v4_4_statistics_hosts_resources_usage_samples\n            INNER JOIN v4_4_latest_configuration_hosts\n                ON \n                    (\n                        v4_4_latest_configuration_hosts.host_id =\n                        v4_4_statistics_hosts_resources_usage_samples.host_id\n                    )\n        WHERE\n            -- Here we filter only active hosts\n            v4_4_statistics_hosts_resources_usage_samples.host_status = 1  \n    ) AS average_memory_percent"
    }
   ]
  },
  {
   "title": "System Host Uptime (DR4)",
   "type": "singlestat",
   "description": "Calculates average uptime percent for all hosts in the system. Thresholds are 60% and 80%.\nThis report shows the latest configuration.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- DR4 - This query returns the total hosts uptime percent\n-- in the latest configuration.\n\nSELECT\n    (\n        SUM \n            (\n                CASE\n                    WHEN v4_4_statistics_hosts_resources_usage_samples.host_status = 1\n                        THEN COALESCE ( v4_4_statistics_hosts_resources_usage_samples.minutes_in_status, 0 )\n                    ELSE 0\n                END\n            ) \n        / SUM ( v4_4_statistics_hosts_resources_usage_samples.minutes_in_status )\n    ) * 100 AS uptime_mins_percent\nFROM \n    v4_4_statistics_hosts_resources_usage_samples\n    INNER JOIN v4_4_latest_configuration_hosts\n        ON \n            (\n                v4_4_latest_configuration_hosts.host_id =\n                v4_4_statistics_hosts_resources_usage_samples.host_id\n            )"
    }
   ]
  },
  {
   "title": "System Storage Space Usage (DR7)",
   "type": "singlestat",
   "description": "Calculates used disk size percent average for all storage domains in the system from their latest configuration. Thresholds are 60% and 80%.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- DR7 - This query returns the used disk size percent\n-- out of the total storage domains disks space.\n-- in the latest configuration.\n\nSELECT\n    CASE\n        WHEN \n            SUM \n                (\n                    cast ( used_disk_size_gb AS float ) +\n                    cast ( available_disk_size_gb AS float )\n                ) != 0\n            THEN \n                ( \n                    SUM ( cast ( used_disk_size_gb AS float ) ) \n                    /\n                    SUM \n                        (\n                            cast ( used_disk_size_gb AS float ) +\n                            cast ( available_disk_size_gb AS float )\n                        )\n                ) * 100\n        ELSE NULL\n    END AS used_disk_size_gb_percent\nFROM \n    storage_domain_samples_history\nWHERE\n    -- Here we get the latest storage domains configuration\n    history_id \n        IN \n            (\n                SELECT MAX ( a.history_id )\n                FROM storage_domain_samples_history AS a\n                GROUP BY a.storage_domain_id\n            )"
    }
   ]
  }
 ]
}