{
 "title": "RHV - Executive Dashboard (Не удалять до запроса)",
 "description": "На экране отображается количество пользователей и операционных систем для хостов и виртуальных машин. Ответственный:  Альбещенко М.Н. (АЦОД)",
 "tags": [
  "RHV",
  "Virtualization",
  "system",
  "Warehouse",
  "scripts"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "show_deleted", "label": "Show  Deleted Entities?", "query": "No,Yes" },
   {
    "name": "datacenter_id",
    "label": "Data Center",
    "query": "SELECT DISTINCT   CAST ( datacenter_id AS varchar ) AS __value,  CASE          WHEN delete_date IS NULL  \t     \t    THEN datacenter_name \t \tWHEN delete_date IS NOT null  \t      \t    THEN datacenter_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')'  END AS __text  \t\tFROM v4_4_configuration_history_datacenters  \t\tWHERE       \t\t    history_id           \t\t\t    IN               \t\t\t\t(  \t             \t\t\t\t\tSELECT MAX ( a.history_id )  \t\t         \t\t\t\t\tFROM v4_4_configuration_history_datacenters a  \t\t         \t\t\t\t\tGROUP BY a.datacenter_id \t         \t\t\t\t) \t \t\t\tAND datacenter_id  \t         \t\t\t    IN \t\t\t     \t\t\t\t    ( \t\t\t\t\t \t\t\t\t\t\tSELECT DISTINCT datacenter_id \t\t\t\t\t \t\t\t\t\t\tFROM v4_4_configuration_history_clusters \t\t\t\t\t \t\t\t\t\t\tWHERE  \t\t\t\t\t     \t\t\t\t\t\t    cluster_id \t\t\t\t\t         \t\t\t\t\t\t        IN \t\t\t\t\t             \t\t\t\t\t\t            ( \t\t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t\tSELECT DISTINCT cluster_id \t\t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t\tFROM v4_4_configuration_history_vms  \t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t) \t\t\t\t\t\t    OR cluster_id  \t\t\t\t\t\t        IN \t\t\t\t\t\t            ( \t\t\t\t\t\t\t\t\t\tSELECT DISTINCT cluster_id \t\t\t\t\t\t\t\t\t\tFROM v4_4_configuration_history_hosts \t\t\t\t\t\t\t\t\t) \t\t\t\t\t) \t \t\t\tAND \t    \t\t\t    CASE  \t        \t\t\t\t    WHEN '$show_deleted'='Yes' \t            \t\t\t\t\t    THEN 1=1 \t\t    \t\t\t\t\tWHEN '$show_deleted'='No' \t\t        \t\t\t\t\t    THEN v4_4_configuration_history_datacenters.delete_date ISNULL \t                END  \t\t"
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "SELECT DISTINCT        CAST ( cluster_id AS varchar ) AS __value,  \tCASE      \t    WHEN delete_date IS NULL  \t     \t\t    THEN cluster_name \t \t\tWHEN delete_date IS NOT null  \t      \t\t    THEN cluster_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')'  \tEND AS __text  \tFROM v4_4_configuration_history_clusters  \tWHERE       \t    history_id           \t\t    IN               \t\t\t    (  \t             \t\t\t\t\tSELECT MAX ( a.history_id )  \t\t         \t\t\t\t\tFROM v4_4_configuration_history_clusters a  \t\t         \t\t\t\t\tGROUP BY a.cluster_id \t         \t\t\t\t) \t \t\tAND  \t\t    (  \t\t\t\tcluster_id IN \t\t\t     \t\t\t        ( \t\t\t\t\t \t\t\t\t\t    SELECT DISTINCT cluster_id \t\t\t\t\t \t\t\t\t\t    FROM v4_4_configuration_history_vms \t\t\t\t \t\t\t\t    ) \t\t    OR cluster_id IN \t\t\t        ( \t\t\t\t\t    SELECT DISTINCT cluster_id \t\t\t\t\t    FROM v4_4_configuration_history_hosts \t\t\t\t    )  \t\t\t) \t\tAND \t    \t\t    CASE  \t        \t\t\t    WHEN '$show_deleted'='Yes' \t            \t\t\t\t    THEN 1=1 \t\t    \t\t\t\tWHEN '$show_deleted'='No' \t\t        \t\t\t\t    THEN v4_4_configuration_history_clusters.delete_date ISNULL \t    \t\t\tEND     \t\tAND datacenter_id IN ($datacenter_id)  \t\t"
   }
  ]
 },
 "panels": [
  { "title": "Sessions Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User Spice Session Activity (BR45)",
   "type": "table-old",
   "description": "This table details user Spice activity - time spent and resources used in the session in a selected data center and cluster within a selected period.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "-- BR45 - This query returns for each VM in the specific data center , the\n-- hourly or daily statistics: session time, CPU and memory usage statistics.\n\nSELECT DISTINCT\n    v4_4_configuration_history_clusters.cluster_id,\n    v4_4_configuration_history_clusters.cluster_name,\n    history_datetime,\n    username AS user_name,\n    v4_4_configuration_history_vms.vm_name,\n -- hourly_daily.vm_id,\n    session_time_in_minutes,\n    cpu_usage_percent,\n    max_cpu_usage,\n    memory_usage_percent,\n    max_memory_usage,\n    user_cpu_usage_percent,\n    max_user_cpu_usage_percent,\n    system_cpu_usage_percent,\n    max_system_cpu_usage_percent,\n    v4_4_configuration_history_clusters.delete_date AS cluster_delete,\n    v4_4_configuration_history_vms.delete_date\nFROM\n    (\n            SELECT history_datetime, vm_id, user_id, session_time_in_minutes, cpu_usage_percent, max_cpu_usage, memory_usage_percent, max_memory_usage, user_cpu_usage_percent, max_user_cpu_usage_percent, system_cpu_usage_percent, max_system_cpu_usage_percent\n            FROM v4_4_statistics_vms_users_usage_hourly\n        UNION\n            SELECT history_datetime, vm_id, user_id, session_time_in_minutes, cpu_usage_percent, max_cpu_usage, memory_usage_percent, max_memory_usage, user_cpu_usage_percent, max_user_cpu_usage_percent, system_cpu_usage_percent, max_system_cpu_usage_percent \n            FROM v4_4_statistics_vms_users_usage_daily\n            WHERE\n                history_datetime <\n                    (\n                        SELECT MIN ( history_datetime )\n                        FROM v4_4_statistics_vms_users_usage_hourly\n                    )\n    ) AS hourly_daily\n    LEFT OUTER JOIN v4_4_configuration_history_vms\n        ON \n            (\n                hourly_daily.vm_id =\n                v4_4_configuration_history_vms.vm_id\n            )\n    LEFT OUTER JOIN v4_4_configuration_history_clusters\n        ON \n            (\n                v4_4_configuration_history_vms.cluster_id =\n                v4_4_configuration_history_clusters.cluster_id\n                -- Here we get the latest cluster configurations\n                AND v4_4_configuration_history_clusters.history_id \n                    IN \n                        (\n                            SELECT MAX ( a.history_id )\n                            FROM v4_4_configuration_history_clusters a\n                            GROUP BY a.cluster_id\n                        )\n            )\n    LEFT OUTER JOIN v4_4_users_details_history\n        ON \n            (\n                hourly_daily.user_id =\n                v4_4_users_details_history.user_id\n            )\nWHERE\n    -- Here we filter by the datacenter chosen by the user\n    v4_4_configuration_history_vms.cluster_id \n        IN \n            (\n                SELECT cluster_id\n                FROM v4_4_configuration_history_clusters\n                WHERE datacenter_id IN ($datacenter_id)\n            )\n    -- Here we filter by the cluster chosen by the user\n    AND v4_4_configuration_history_vms.cluster_id IN ($cluster_id)\n    -- Here we get the latest vm configurations\n    AND v4_4_configuration_history_vms.history_id \n        IN \n            (\n                SELECT MAX ( a.history_id )\n                FROM v4_4_configuration_history_vms a\n                GROUP BY a.vm_id\n            )\n    AND history_datetime >= $__timeFrom()\n    AND history_datetime < $__timeTo()\n    -- This will determine if deleted entities will be included in the report,\n    -- according to the user selection for \"show_deleted\" parameter\n    AND \n        CASE\n            WHEN '$show_deleted'='Yes'\n                THEN 1=1\n            WHEN '$show_deleted'='No'\n                THEN v4_4_configuration_history_vms.delete_date isnull\n        END\nORDER BY\n    v4_4_configuration_history_clusters.cluster_name,\n    history_datetime,\n    username,\n    session_time_in_minutes DESC"
    }
   ]
  },
  { "title": "Virtual Machines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Active Virtual Machines by OS (BR18)",
   "type": "graph",
   "description": "This report displays the number of running virtual machines and OS usage for a selected cluster within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "VM Count" }
   ],
   "targets": [
    {
     "rawSql": "-- BR18 - This query returns for each OS the number\n-- of active vms, up to an hour back.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT DISTINCT\n    NOW () AS time,\n    COALESCE ( os_type, 'RHEL' ) AS os_type,\n    vm_count\nFROM \n    (\n        SELECT DISTINCT\n            CASE\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                    THEN 'Other OS'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE '%WINDOWS%'\n                    THEN 'Windows'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'RHEL%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'RED HAT%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'OTHER L%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'LINUX'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE '%UBUNTU%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE '%SUSE%'\n                    THEN 'Other Linux'\n                ELSE 'Other OS'\n            END AS os_type,\n            samples.history_datetime AS time,\n            COUNT ( DISTINCT v4_4_configuration_history_vms.vm_id ) AS vm_count\n        FROM \n            (\n                SELECT history_datetime, vm_id, vm_status, vm_configuration_version \n                FROM v4_4_statistics_vms_resources_usage_samples\n            ) AS samples\n            INNER JOIN v4_4_configuration_history_vms\n                ON \n                    (\n                        v4_4_configuration_history_vms.history_id =\n                        samples.vm_configuration_version\n                    )\n            INNER JOIN enum_translator enum_os_type\n                ON \n                    (\n                        enum_os_type.enum_key =\n                        v4_4_configuration_history_vms.operating_system\n                        AND enum_os_type.enum_type = 'OS_TYPE'\n                        AND language_code = 'en_US'\n                    )\n            INNER JOIN v4_4_configuration_history_vms latest_config\n                ON \n                    (\n                        latest_config.vm_id =\n                        samples.vm_id\n                    )\n        WHERE\n            -- Here we filter only the vms that are in active status\n            samples.vm_status = 1\n            -- Filter vms list according to the cluster that was chosen by the user\n            AND v4_4_configuration_history_vms.cluster_id \n                IN \n                    (\n                        SELECT v4_4_configuration_history_clusters.cluster_id\n                        FROM v4_4_configuration_history_clusters\n                        WHERE v4_4_configuration_history_clusters.cluster_id IN ( $cluster_id ) \n                    )\n            -- Here we get the vm latest configuration\n            AND latest_config.history_id \n                IN\n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_4_configuration_history_vms b\n                        GROUP BY b.vm_id\n                    )\n            AND samples.history_datetime >= $__timeFrom()\n            AND samples.history_datetime < $__timeTo()\n            -- This will determine where deleted entities will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted' = 'No'\n                        THEN latest_config.delete_date IS NULL\n                    ELSE\n                        latest_config.delete_date IS NULL\n                        OR\n                        latest_config.delete_date IS NOT NULL\n                END\n        GROUP BY\n            -- Here we calculate for each OS type\n            CASE\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                    THEN 'Other OS'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%WINDOWS%'\n                    THEN 'Windows'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RHEL%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RED HAT%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'OTHER L%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'LINUX'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%UBUNTU%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%SUSE%'\n                    THEN 'Other Linux'\n                ELSE 'Other OS'\n            END,\n            samples.History_datetime\n    ) AS all_sub_queries\n-- Show data only when the selected period is up to 24 hours back \nWHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\nORDER BY os_type, time"
    },
    {
     "rawSql": "-- BR18 - This query returns for each OS the number\n-- of active vms, up to an hour back.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT DISTINCT\n    NOW () AS time,\n    COALESCE ( os_type, 'RHEL' ) AS os_type,\n    vm_count\nFROM \n    (\n        SELECT DISTINCT\n            CASE\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                    THEN 'Other OS'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE '%WINDOWS%'\n                    THEN 'Windows'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'RHEL%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'RED HAT%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'OTHER L%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'LINUX'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE '%UBUNTU%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE '%SUSE%'\n                    THEN 'Other Linux'\n                ELSE 'Other OS'\n            END AS os_type,\n            hourly_daily.history_datetime AS time,\n            COUNT ( DISTINCT v4_4_configuration_history_vms.vm_id ) AS vm_count\n        FROM \n            (\n                    SELECT history_datetime, vm_id, vm_status, vm_configuration_version \n                    FROM v4_4_statistics_vms_resources_usage_hourly\n                UNION\n                    SELECT history_datetime, vm_id, vm_status, vm_configuration_version \n                    FROM v4_4_statistics_vms_resources_usage_daily\n                    WHERE\n                        history_datetime <\n                            (\n                                SELECT MIN ( history_datetime )\n                                FROM v4_4_statistics_vms_resources_usage_hourly\n                            )\n            ) AS hourly_daily\n            INNER JOIN v4_4_configuration_history_vms\n                ON \n                    (\n                        v4_4_configuration_history_vms.history_id =\n                        hourly_daily.vm_configuration_version\n                    )\n            INNER JOIN enum_translator enum_os_type\n                ON \n                    (\n                        enum_os_type.enum_key =\n                        v4_4_configuration_history_vms.operating_system\n                        AND enum_os_type.enum_type = 'OS_TYPE'\n                        AND language_code = 'en_US'\n                    )\n            INNER JOIN v4_4_configuration_history_vms latest_config\n                ON \n                    (\n                        latest_config.vm_id =\n                        hourly_daily.vm_id\n                    )\n        WHERE\n            -- Here we filter only the vms that are in active status\n            hourly_daily.vm_status = 1\n            -- Filter vms list according to the cluster that was chosen by the user\n            AND v4_4_configuration_history_vms.cluster_id \n                IN \n                    (\n                        SELECT v4_4_configuration_history_clusters.cluster_id\n                        FROM v4_4_configuration_history_clusters\n                        WHERE v4_4_configuration_history_clusters.cluster_id IN ( $cluster_id ) \n                    )\n            -- Here we get the vm latest configuration\n            AND latest_config.history_id \n                IN\n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_4_configuration_history_vms b\n                        GROUP BY b.vm_id\n                    )\n            AND hourly_daily.history_datetime >= $__timeFrom()\n            AND hourly_daily.history_datetime < $__timeTo()\n            -- This will determine where deleted entities will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted' = 'No'\n                        THEN latest_config.delete_date IS NULL\n                    ELSE\n                        latest_config.delete_date IS NULL\n                        OR\n                        latest_config.delete_date IS NOT NULL\n                END\n        GROUP BY\n            -- Here we calculate for each OS type\n            CASE\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                    THEN 'Other OS'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%WINDOWS%'\n                    THEN 'Windows'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RHEL%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RED HAT%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'OTHER L%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'LINUX'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%UBUNTU%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%SUSE%'\n                    THEN 'Other Linux'\n                ELSE 'Other OS'\n            END,\n            hourly_daily.History_datetime\n    ) AS all_sub_queries\n-- Show data only when the selected period is more then 24 hours back\nWHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\nORDER BY os_type, time"
    }
   ]
  },
  {
   "title": "Active Virtual Machines by OS (over time) (BR18)",
   "type": "graph",
   "description": "This report displays the number of running virtual machines and OS usage for a selected cluster over a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "VM Count" }
   ],
   "targets": [
    {
     "rawSql": "-- BR18 - This query returns for each OS the number\n-- of active vms over time.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT DISTINCT\n    $__time(time),\n    COALESCE ( os_type, 'RHEL' ) AS os_type,\n    vm_count\nFROM \n    (\n        SELECT DISTINCT\n            CASE\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                    THEN 'Other OS'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE '%WINDOWS%'\n                    THEN 'Windows'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'RHEL%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'RED HAT%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'OTHER L%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'LINUX'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE '%UBUNTU%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE '%SUSE%'\n                    THEN 'Other Linux'\n                ELSE 'Other OS'\n            END AS os_type,\n            samples.history_datetime AS time,\n            COUNT ( DISTINCT v4_4_configuration_history_vms.vm_id ) AS vm_count\n        FROM \n            (\n                SELECT history_datetime, vm_id, vm_status, vm_configuration_version \n                FROM v4_4_statistics_vms_resources_usage_samples\n            ) AS samples\n            INNER JOIN v4_4_configuration_history_vms\n                ON \n                    (\n                        v4_4_configuration_history_vms.history_id =\n                        samples.vm_configuration_version\n                    )\n            INNER JOIN enum_translator enum_os_type\n                ON \n                    (\n                        enum_os_type.enum_key =\n                        v4_4_configuration_history_vms.operating_system\n                        AND enum_os_type.enum_type = 'OS_TYPE'\n                        AND language_code = 'en_US'\n                    )\n            INNER JOIN v4_4_configuration_history_vms latest_config\n                ON \n                    (\n                        latest_config.vm_id =\n                        samples.vm_id\n                    )\n        WHERE\n            -- Here we filter only the vms that are in active status\n            samples.vm_status = 1\n            -- Filter vms list according to the cluster that was chosen by the user\n            AND v4_4_configuration_history_vms.cluster_id \n                IN \n                    (\n                        SELECT v4_4_configuration_history_clusters.cluster_id\n                        FROM v4_4_configuration_history_clusters\n                        WHERE v4_4_configuration_history_clusters.cluster_id IN ( $cluster_id ) \n                    )\n        \n            -- Here we get the vm latest configuration\n            AND latest_config.history_id \n                IN\n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_4_configuration_history_vms b\n                        GROUP BY b.vm_id\n                    )\n            AND samples.history_datetime >= $__timeFrom()\n            AND samples.history_datetime < $__timeTo()\n            -- This will determine where deleted entities will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted' = 'No'\n                        THEN latest_config.delete_date IS NULL\n                    ELSE\n                        latest_config.delete_date IS NULL\n                        OR\n                        latest_config.delete_date IS NOT NULL\n                END\n        GROUP BY\n            -- Here we calculate for each OS type\n            CASE\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                    THEN 'Other OS'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%WINDOWS%'\n                    THEN 'Windows'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RHEL%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RED HAT%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'OTHER L%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'LINUX'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%UBUNTU%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%SUSE%'\n                    THEN 'Other Linux'\n                ELSE 'Other OS'\n            END,\n            samples.History_datetime\n    ) AS all_sub_queries\n-- Show data only when the selected period is up to 24 hours back \nWHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\nORDER BY os_type, time"
    },
    {
     "rawSql": "-- BR18 - This query returns for each OS the number\n-- of active vms over time.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT DISTINCT\n    $__time(time),\n    COALESCE ( os_type, 'RHEL' ) AS os_type,\n    vm_count\nFROM \n    (\n        SELECT DISTINCT\n            CASE\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                    THEN 'Other OS'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE '%WINDOWS%'\n                    THEN 'Windows'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'RHEL%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'RED HAT%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'OTHER L%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE 'LINUX'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE '%UBUNTU%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) LIKE '%SUSE%'\n                    THEN 'Other Linux'\n                ELSE 'Other OS'\n            END AS os_type,\n            hourly_daily.history_datetime AS time,\n            COUNT ( DISTINCT v4_4_configuration_history_vms.vm_id ) AS vm_count\n        FROM \n            (\n                    SELECT history_datetime, vm_id, vm_status, vm_configuration_version \n                    FROM v4_4_statistics_vms_resources_usage_hourly\n                UNION\n                    SELECT history_datetime, vm_id, vm_status, vm_configuration_version\n                    FROM v4_4_statistics_vms_resources_usage_daily\n                    WHERE\n                        history_datetime <\n                            (\n                                SELECT MIN ( history_datetime )\n                                FROM v4_4_statistics_vms_resources_usage_hourly\n                            )\n            ) AS hourly_daily\n            INNER JOIN v4_4_configuration_history_vms\n                ON \n                    (\n                        v4_4_configuration_history_vms.history_id =\n                        hourly_daily.vm_configuration_version\n                    )\n            INNER JOIN enum_translator enum_os_type\n                ON \n                    (\n                        enum_os_type.enum_key =\n                        v4_4_configuration_history_vms.operating_system\n                        AND enum_os_type.enum_type = 'OS_TYPE'\n                        AND language_code = 'en_US'\n                    )\n            INNER JOIN v4_4_configuration_history_vms latest_config\n                ON \n                    (\n                        latest_config.vm_id =\n                        hourly_daily.vm_id\n                    )\n        WHERE\n            -- Here we filter only the vms that are in active status\n            hourly_daily.vm_status = 1\n            -- Filter vms list according to the cluster that was chosen by the user\n            AND v4_4_configuration_history_vms.cluster_id \n                IN \n                    (\n                        SELECT v4_4_configuration_history_clusters.cluster_id\n                        FROM v4_4_configuration_history_clusters\n                        WHERE v4_4_configuration_history_clusters.cluster_id IN ( $cluster_id ) \n                    )\n        \n            -- Here we get the vm latest configuration\n            AND latest_config.history_id \n                IN\n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_4_configuration_history_vms b\n                        GROUP BY b.vm_id\n                    )\n            AND hourly_daily.history_datetime >= $__timeFrom()\n            AND hourly_daily.history_datetime < $__timeTo()\n            -- This will determine where deleted entities will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted' = 'No'\n                        THEN latest_config.delete_date IS NULL\n                    ELSE\n                        latest_config.delete_date IS NULL\n                        OR\n                        latest_config.delete_date IS NOT NULL\n                END\n        GROUP BY\n            -- Here we calculate for each OS type\n            CASE\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                    THEN 'Other OS'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%WINDOWS%'\n                    THEN 'Windows'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RHEL%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RED HAT%'\n                    THEN 'RHEL'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'OTHER L%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'LINUX'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%UBUNTU%'\n                    THEN 'Other Linux'\n                WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%SUSE%'\n                    THEN 'Other Linux'\n                ELSE 'Other OS'\n            END,\n            hourly_daily.History_datetime\n    ) AS all_sub_queries\n-- Show data only when the selected period is more then 24 hours back\nWHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\nORDER BY os_type, time"
    }
   ]
  },
  { "title": "Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Host OS Break Down (BR22)",
   "type": "graph",
   "description": "This report displays the number of hosts for each OS version for a selected cluster within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "Host Count" }
   ],
   "targets": [
    {
     "rawSql": "-- BR22 - This query returns for each OS version the \n-- number of hosts,  up to an hour back.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT DISTINCT\n    NOW () AS time,\n    COALESCE ( os_type, MAX ( os_type ) over (partition by 1), '' ) AS os_type,\n    host_count\nFROM \n    (\n        SELECT\n            COALESCE ( v4_4_configuration_history_hosts.host_os, 'Unknown' ) AS os_type,\n            samples.history_datetime AS time,\n            COUNT ( DISTINCT samples.host_id ) AS host_count\n        FROM  \n            (\n                SELECT history_datetime, host_id\n                FROM v4_4_statistics_hosts_resources_usage_samples\n            ) AS samples\n            INNER JOIN v4_4_configuration_history_hosts \n                ON \n                    (\n                        v4_4_configuration_history_hosts.host_id =\n                        samples.host_id\n                    )\n        WHERE\n            v4_4_configuration_history_hosts.cluster_id \n                IN \n                    (\n                        SELECT v4_4_configuration_history_clusters.cluster_id\n                        FROM v4_4_configuration_history_clusters\n                        WHERE v4_4_configuration_history_clusters.cluster_id IN ( $cluster_id )\n                    )\n\n            AND samples.history_datetime >= $__timeFrom()\n            AND samples.history_datetime < $__timeTo()\n            -- Here we get the host latest configuration\n            AND v4_4_configuration_history_hosts.history_id \n                IN \n                    (\n                        SELECT MAX ( v4_4_configuration_history_hosts.history_id )\n                        FROM v4_4_configuration_history_hosts \n                        GROUP BY v4_4_configuration_history_hosts.host_id\n                    )\n            -- This will determine where deleted entities will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter     \n            AND\n                CASE\n                    WHEN '$show_deleted' = 'No'\n                        THEN v4_4_configuration_history_hosts.delete_date IS NULL\n                    ELSE\n                        v4_4_configuration_history_hosts.delete_date IS NULL\n                        OR\n                        v4_4_configuration_history_hosts.delete_date IS NOT NULL\n                END\n        GROUP BY\n            -- Here we calculate for each OS version\n            COALESCE ( v4_4_configuration_history_hosts.host_os, 'Unknown' ), \n            time\n    ) AS all_sub_queries\n-- Show data only when the selected period is up to 24 hours back \nWHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\nORDER BY time"
    },
    {
     "rawSql": "-- BR22 - This query returns for each OS version the \n-- number of hosts,  up to an hour back.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT DISTINCT\n    NOW () AS time,\n    COALESCE ( os_type, MAX ( os_type ) over (partition by 1), '' ) AS os_type,\n    host_count\nFROM \n    (\n        SELECT\n            COALESCE ( v4_4_configuration_history_hosts.host_os, 'Unknown' ) AS os_type,\n            hourly_daily.history_datetime AS time,\n            COUNT ( DISTINCT hourly_daily.host_id ) AS host_count\n        FROM  \n            (\n                    SELECT history_datetime, host_id\n                    FROM v4_4_statistics_hosts_resources_usage_hourly\n                UNION\n                    SELECT history_datetime, host_id\n                    FROM v4_4_statistics_hosts_resources_usage_daily\n                    WHERE\n                        history_datetime <\n                            (\n                                SELECT MIN ( history_datetime )\n                                FROM v4_4_statistics_hosts_resources_usage_hourly\n                            )\n            ) AS hourly_daily\n            INNER JOIN v4_4_configuration_history_hosts \n                ON \n                    (\n                        v4_4_configuration_history_hosts.host_id =\n                        hourly_daily.host_id\n                    )\n        WHERE\n            v4_4_configuration_history_hosts.cluster_id \n                IN \n                    (\n                        SELECT v4_4_configuration_history_clusters.cluster_id\n                        FROM v4_4_configuration_history_clusters\n                        WHERE v4_4_configuration_history_clusters.cluster_id IN ( $cluster_id )\n                    )\n\n            AND hourly_daily.history_datetime >= $__timeFrom()\n            AND hourly_daily.history_datetime < $__timeTo()\n            -- Here we get the host latest configuration\n            AND v4_4_configuration_history_hosts.history_id \n                IN \n                    (\n                        SELECT MAX ( v4_4_configuration_history_hosts.history_id )\n                        FROM v4_4_configuration_history_hosts \n                        GROUP BY v4_4_configuration_history_hosts.host_id\n                    )\n            -- This will determine where deleted entities will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter     \n            AND\n                CASE\n                    WHEN '$show_deleted' = 'No'\n                        THEN v4_4_configuration_history_hosts.delete_date IS NULL\n                    ELSE\n                        v4_4_configuration_history_hosts.delete_date IS NULL\n                        OR\n                        v4_4_configuration_history_hosts.delete_date IS NOT NULL\n                END\n        GROUP BY\n            -- Here we calculate for each OS version\n            COALESCE ( v4_4_configuration_history_hosts.host_os, 'Unknown' ), \n            time\n    ) AS all_sub_queries\n-- Show data only when the selected period is more then 24 hours back\nWHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\nORDER BY time"
    }
   ]
  },
  {
   "title": "Host OS Breakdown (over time) (BR22)",
   "type": "graph",
   "description": "This report displays the number of hosts for each OS version for a selected cluster over a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "Host Count" }
   ],
   "targets": [
    {
     "rawSql": "-- BR22 - This query returns for each OS version the \n-- number of hosts over time.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT DISTINCT\n    $__time(time),\n    COALESCE ( os_type, MAX ( os_type ) over (partition by 1), '' ) AS os_type,\n    host_count\nFROM \n    (\n        SELECT\n            COALESCE ( v4_4_configuration_history_hosts.host_os, 'Unknown' ) AS os_type,\n            samples.history_datetime AS time,\n            COUNT ( DISTINCT samples.host_id ) AS host_count\n        FROM  \n            (\n                SELECT history_datetime, host_id \n                FROM v4_4_statistics_hosts_resources_usage_samples\n            ) AS samples\n            INNER JOIN v4_4_configuration_history_hosts \n                ON \n                    (\n                        v4_4_configuration_history_hosts.host_id =\n                        samples.host_id\n                    )\n        WHERE\n            v4_4_configuration_history_hosts.cluster_id \n                IN \n                    (\n                        SELECT v4_4_configuration_history_clusters.cluster_id\n                        FROM v4_4_configuration_history_clusters\n                        WHERE v4_4_configuration_history_clusters.cluster_id IN ( $cluster_id ) \n                    )\n            AND samples.history_datetime >= $__timeFrom()\n            AND samples.history_datetime < $__timeTo()\n            -- Here we get the host latest configuration\n            AND v4_4_configuration_history_hosts.history_id \n                IN \n                    (\n                        SELECT MAX ( v4_4_configuration_history_hosts.history_id )\n                        FROM v4_4_configuration_history_hosts \n                        GROUP BY v4_4_configuration_history_hosts.host_id\n                    )\n            -- This will determine where deleted entities will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter \n            AND\n                CASE\n                    WHEN '$show_deleted' = 'No'\n                        THEN v4_4_configuration_history_hosts.delete_date IS NULL\n                    ELSE\n                        v4_4_configuration_history_hosts.delete_date IS NULL\n                        OR\n                        v4_4_configuration_history_hosts.delete_date IS NOT NULL\n                END\n        GROUP BY\n            -- Here we calculate for each OS version\n            COALESCE ( v4_4_configuration_history_hosts.host_os, 'Unknown' ), \n            time\n    ) AS all_sub_queries\n-- Show data only when the selected period is up to 24 hours back \nWHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\nORDER BY time"
    },
    {
     "rawSql": "-- BR22 - This query returns for each OS version the \n-- number of hosts over time.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT DISTINCT\n    $__time(time),\n    COALESCE ( os_type, MAX ( os_type ) over (partition by 1), '' ) AS os_type,\n    host_count\nFROM \n    (\n        SELECT\n            COALESCE ( v4_4_configuration_history_hosts.host_os, 'Unknown' ) AS os_type,\n            hourly_daily.history_datetime AS time,\n            COUNT ( DISTINCT hourly_daily.host_id ) AS host_count\n        FROM  \n            (\n                    SELECT history_datetime, host_id \n                    FROM v4_4_statistics_hosts_resources_usage_hourly\n                UNION\n                    SELECT history_datetime, host_id\n                    FROM v4_4_statistics_hosts_resources_usage_daily\n                    WHERE\n                        history_datetime <\n                            (\n                                SELECT MIN ( history_datetime )\n                                FROM v4_4_statistics_hosts_resources_usage_hourly\n                            )\n            ) AS hourly_daily\n            INNER JOIN v4_4_configuration_history_hosts \n                ON \n                    (\n                        v4_4_configuration_history_hosts.host_id =\n                        hourly_daily.host_id\n                    )\n        WHERE\n            v4_4_configuration_history_hosts.cluster_id \n                IN \n                    (\n                        SELECT v4_4_configuration_history_clusters.cluster_id\n                        FROM v4_4_configuration_history_clusters\n                        WHERE v4_4_configuration_history_clusters.cluster_id IN ( $cluster_id ) \n                    )\n            AND hourly_daily.history_datetime >= $__timeFrom()\n            AND hourly_daily.history_datetime < $__timeTo()\n            -- Here we get the host latest configuration\n            AND v4_4_configuration_history_hosts.history_id \n                IN \n                    (\n                        SELECT MAX ( v4_4_configuration_history_hosts.history_id )\n                        FROM v4_4_configuration_history_hosts \n                        GROUP BY v4_4_configuration_history_hosts.host_id\n                    )\n            -- This will determine where deleted entities will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter \n            AND\n                CASE\n                    WHEN '$show_deleted' = 'No'\n                        THEN v4_4_configuration_history_hosts.delete_date IS NULL\n                    ELSE\n                        v4_4_configuration_history_hosts.delete_date IS NULL\n                        OR\n                        v4_4_configuration_history_hosts.delete_date IS NOT NULL\n                END\n        GROUP BY\n            -- Here we calculate for each OS version\n            COALESCE ( v4_4_configuration_history_hosts.host_os, 'Unknown' ), \n            time\n    ) AS all_sub_queries\n-- Show data only when the selected period is more then 24 hours back\nWHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\nORDER BY time"
    }
   ]
  }
 ]
}