{
 "title": "RHV - Cluster Quality of Service - Virtual Machines Dashboard (Не удалять до запроса)",
 "description": "Панель мониторинга качества обслуживания кластера виртуальных машин содержит отчеты, в которых показано время и общее время, в течение которого каждая виртуальная машина выполняла работу выше/ниже порога процессора или памяти, с использованием единой статистики и таблицы. Ответственный: Альбещенко М.Н. (АЦОД)",
 "tags": [
  "RHV",
  "Virtualization",
  "system",
  "Warehouse",
  "scripts"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "show_deleted", "label": "Show Deleted Entities?", "query": "No, Yes" },
   {
    "name": "datacenter_id",
    "label": "Data Center",
    "query": "SELECT DISTINCT   CAST ( datacenter_id AS varchar ) AS __value,  CASE          WHEN delete_date IS NULL  \t     \t    THEN datacenter_name \t \tWHEN delete_date IS NOT null  \t      \t    THEN datacenter_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')'  END AS __text  \t\tFROM v4_4_configuration_history_datacenters  \t\tWHERE       \t\t    history_id           \t\t\t    IN               \t\t\t\t(  \t             \t\t\t\t\tSELECT MAX ( a.history_id )  \t\t         \t\t\t\t\tFROM v4_4_configuration_history_datacenters a  \t\t         \t\t\t\t\tGROUP BY a.datacenter_id \t         \t\t\t\t) \t \t\t\tAND datacenter_id  \t         \t\t\t    IN \t\t\t     \t\t\t\t    ( \t\t\t\t\t \t\t\t\t\t\tSELECT DISTINCT datacenter_id \t\t\t\t\t \t\t\t\t\t\tFROM v4_4_configuration_history_clusters \t\t\t\t\t \t\t\t\t\t\tWHERE  \t\t\t\t\t     \t\t\t\t\t\t    cluster_id \t\t\t\t\t         \t\t\t\t\t\t        IN \t\t\t\t\t             \t\t\t\t\t\t            ( \t\t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t\tSELECT DISTINCT cluster_id \t\t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t\tFROM v4_4_configuration_history_vms  \t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t) \t\t\t\t \t\t\t\t\t) \t \t\t\tAND \t    \t\t\t    CASE  \t        \t\t\t\t    WHEN '$show_deleted'='Yes' \t            \t\t\t\t\t    THEN 1=1 \t\t    \t\t\t\t\tWHEN '$show_deleted'='No' \t\t        \t\t\t\t\t    THEN v4_4_configuration_history_datacenters.delete_date ISNULL \t                END  \t\t"
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "SELECT DISTINCT        CAST ( cluster_id AS varchar ) AS __value,  \tCASE      \t    WHEN delete_date IS NULL  \t     \t\t    THEN cluster_name \t \t\tWHEN delete_date IS NOT null  \t      \t\t    THEN cluster_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')'  \tEND AS __text  \tFROM v4_4_configuration_history_clusters  \tWHERE       \t    history_id           \t\t    IN               \t\t\t    (  \t             \t\t\t\t\tSELECT MAX ( a.history_id )  \t\t         \t\t\t\t\tFROM v4_4_configuration_history_clusters a  \t\t         \t\t\t\t\tGROUP BY a.cluster_id \t         \t\t\t\t) \t \t\tAND cluster_id  \t         \t\t    IN \t\t\t     \t\t\t    ( \t\t\t\t\t \t\t\t\t\tSELECT DISTINCT cluster_id \t\t\t\t\t \t\t\t\t\tFROM v4_4_configuration_history_vms \t\t\t\t \t\t\t\t) \t \t\tAND \t    \t\t    CASE  \t        \t\t\t    WHEN '$show_deleted'='Yes' \t            \t\t\t\t    THEN 1=1 \t\t    \t\t\t\tWHEN '$show_deleted'='No' \t\t        \t\t\t\t    THEN v4_4_configuration_history_clusters.delete_date ISNULL \t    \t\t\tEND     \t\tAND datacenter_id IN ($datacenter_id)  \t\t"
   },
   {
    "name": "vm_id",
    "label": "Virtual Machine",
    "query": "SELECT DISTINCT        CAST ( vm_id AS varchar ) AS __value,  \tCASE      \t    WHEN delete_date IS NULL  \t     \t\t    THEN vm_name \t \t\tWHEN delete_date IS NOT null  \t      \t\t    THEN vm_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')'  \tEND AS __text  \tFROM v4_4_configuration_history_vms  \tWHERE       \t    history_id           \t\t    IN               \t\t\t    (  \t             \t\t\t\t\tSELECT MAX ( a.history_id )  \t\t         \t\t\t\t\tFROM v4_4_configuration_history_vms a  \t\t         \t\t\t\t\tGROUP BY a.vm_id \t         \t\t\t\t) \t \t\tAND \t    \t\t    CASE  \t        \t\t\t    WHEN '$show_deleted'='Yes' \t            \t\t\t\t    THEN 1=1 \t\t    \t\t\t\tWHEN '$show_deleted'='No' \t\t        \t\t\t\t    THEN v4_4_configuration_history_vms.delete_date ISNULL \t    \t\t\tEND     \t\tAND cluster_id IN ($cluster_id)"
   },
   {
    "name": "cpu_threshold",
    "label": "CPU Threshold",
    "query": "0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100"
   },
   {
    "name": "mem_threshold",
    "label": "Memory Threshold",
    "query": "0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100"
   }
  ]
 },
 "panels": [
  { "title": "Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time Above CPU Threshold (BR13)",
   "type": "singlestat",
   "description": "This report displays the time virtual machines have performed above CPU threshold.",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 1 },
   "format": "m",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- BR13 - VMs cpu and memory performance\n-- in relation to the thresholds set by the user\n\n-- Time above CPU threshold\nSELECT  \n    CASE \n        -- Show data only when the selected period is up to 24 hours back\n        WHEN $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\n            THEN\n                (\n                    SELECT\n                        COALESCE ( AVG ( cpu_above ), 0 ) AS cpu_above\n                    FROM \n                        (\n                            SELECT\n                                SUM \n                                    (\n                                        CASE\n                                            WHEN cpu_usage_percent >= '$cpu_threshold'\n                                                THEN minutes_in_status\n                                            ELSE 0\n                                        END\n                                    ) AS cpu_above\n                            FROM \n                                (\n                                    SELECT DISTINCT\n                                        v4_4_configuration_history_vms.vm_id,\n                                        history_datetime,\n                                        cpu_usage_percent,\n                                        minutes_in_status\n                                    FROM\n                                        (\n                                            SELECT history_datetime, vm_id, cpu_usage_percent, minutes_in_status, vm_status \n                                            FROM v4_4_statistics_vms_resources_usage_samples\n                                        ) AS stats_vms\n                                        INNER JOIN v4_4_configuration_history_vms\n                                            ON \n                                                (\n                                                    v4_4_configuration_history_vms.vm_id =\n                                                    stats_vms.vm_id\n                                                )\n                                    WHERE\n                                        -- Here we filter only vm in active status\n                                        stats_vms.vm_status = 1\n                                        -- Here we filter by the datacenter chosen by the users\n                                        AND v4_4_configuration_history_vms.cluster_id \n                                            IN \n                                                (\n                                                    SELECT cluster_id\n                                                    FROM v4_4_configuration_history_clusters\n                                                    WHERE datacenter_id IN ($datacenter_id)\n                                                )\n                                        -- Here we filter by the virtual machine/s chosen by the user\n                                        AND v4_4_configuration_history_vms.vm_id IN ($vm_id)\n                                        -- Here we get the latest vm configurations\n                                        AND v4_4_configuration_history_vms.history_id \n                                            IN \n                                                (\n                                                    SELECT MAX ( a.history_id )\n                                                    FROM v4_4_configuration_history_vms a\n                                                    GROUP BY a.vm_id\n                                                )\n                                        AND history_datetime >= $__timeFrom()\n                                        AND history_datetime < $__timeTo()\n                                        -- This will determine if deleted entities will be included in the report,\n                                        -- according to the user selection for \"show_deleted\" parameter\n                                        AND\n                                            CASE\n                                                WHEN '$show_deleted'='Yes'\n                                                    THEN 1=1\n                                                WHEN '$show_deleted'='No'\n                                                    THEN delete_date isnull\n                                            END\n                                ) AS sub_query\n                            GROUP BY vm_id\n                        ) AS samples_sub_queries\n                )\n        -- Show data only when the selected period is more then 24 hours back\n        WHEN $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\n            THEN\n                (\n                    SELECT\n                        COALESCE ( AVG ( cpu_above ), 0 ) AS cpu_above \n                    FROM \n                        (\n                            SELECT\n                                SUM \n                                    (\n                                        CASE\n                                            WHEN cpu_usage_percent >= '$cpu_threshold'\n                                                THEN minutes_in_status\n                                            ELSE 0\n                                        END\n                                    ) AS cpu_above\n                            FROM \n                                (\n                                    SELECT DISTINCT\n                                        v4_4_configuration_history_vms.vm_id,\n                                        history_datetime,\n                                        cpu_usage_percent,\n                                        minutes_in_status\n                                    FROM\n                                        (\n                                                SELECT history_datetime, vm_id, cpu_usage_percent, minutes_in_status, vm_status \n                                                FROM v4_4_statistics_vms_resources_usage_hourly\n                                            UNION\n                                                SELECT history_datetime, vm_id, cpu_usage_percent, minutes_in_status, vm_status\n                                                FROM v4_4_statistics_vms_resources_usage_daily\n                                                WHERE\n                                                    history_datetime <\n                                                        (\n                                                            SELECT MIN ( history_datetime )\n                                                            FROM v4_4_statistics_vms_resources_usage_hourly\n                                                        )\n                                        ) AS stats_vms\n                                        INNER JOIN v4_4_configuration_history_vms\n                                            ON \n                                                (\n                                                    v4_4_configuration_history_vms.vm_id =\n                                                    stats_vms.vm_id\n                                                )\n                                    WHERE\n                                        -- Here we filter only vm in active status\n                                        stats_vms.vm_status = 1\n                                        -- Here we filter by the datacenter chosen by the users\n                                        AND v4_4_configuration_history_vms.cluster_id \n                                            IN \n                                                (\n                                                    SELECT cluster_id\n                                                    FROM v4_4_configuration_history_clusters\n                                                    WHERE datacenter_id IN ($datacenter_id)\n                                                )\n                                        -- Here we filter by the virtual machine/s chosen by the user\n                                        AND v4_4_configuration_history_vms.vm_id IN ($vm_id)\n                                        -- Here we get the latest vm configurations\n                                        AND v4_4_configuration_history_vms.history_id \n                                            IN \n                                                (\n                                                    SELECT MAX ( a.history_id )\n                                                    FROM v4_4_configuration_history_vms a\n                                                    GROUP BY a.vm_id\n                                                )\n                                        AND history_datetime >= $__timeFrom()\n                                        AND history_datetime < $__timeTo()\n                                        -- This will determine if deleted entities will be included in the report,\n                                        -- according to the user selection for \"show_deleted\" parameter\n                                        AND\n                                            CASE\n                                                WHEN '$show_deleted'='Yes'\n                                                    THEN 1=1\n                                                WHEN '$show_deleted'='No'\n                                                    THEN delete_date isnull\n                                            END\n                                ) AS sub_query\n                            GROUP BY vm_id\n                        ) AS hourly_daily_sub_queries\n                )\n    END"
    }
   ]
  },
  {
   "title": "Time Above Memory Threshold (BR13)",
   "type": "singlestat",
   "description": "This report displays the time virtual machines have performed above memory threshold.",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 1 },
   "format": "m",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- BR13 - VMs cpu and memory performance\n-- in relation to the thresholds set by the user\n\n-- Time above memory threshold\nSELECT  \n    CASE \n        -- Show data only when the selected period is up to 24 hours back\n        WHEN $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\n            THEN\n                (\n                    SELECT\n                        COALESCE ( AVG ( mem_above ), 0 ) AS mem_above\n                    FROM \n                        (\n                            SELECT\n                                SUM \n                                    (\n                                        CASE\n                                            WHEN memory_usage_percent >= '$mem_threshold'\n                                                THEN minutes_in_status\n                                            ELSE 0\n                                        END\n                                    ) AS mem_above\n                            FROM \n                                (\n                                    SELECT DISTINCT\n                                        v4_4_configuration_history_vms.vm_id,\n                                        history_datetime,\n                                        memory_usage_percent,\n                                        minutes_in_status\n                                    FROM\n                                        (\n                                            SELECT history_datetime, vm_id, memory_usage_percent, minutes_in_status, vm_status \n                                            FROM v4_4_statistics_vms_resources_usage_samples\n                                        ) AS stats_vms\n                                        INNER JOIN v4_4_configuration_history_vms\n                                            ON \n                                                (\n                                                    v4_4_configuration_history_vms.vm_id =\n                                                    stats_vms.vm_id\n                                                )\n                                    WHERE\n                                        -- Here we filter only vm in active status\n                                        stats_vms.vm_status = 1\n                                        -- Here we filter by the datacenter chosen by the users\n                                        AND v4_4_configuration_history_vms.cluster_id \n                                            IN \n                                                (\n                                                    SELECT cluster_id\n                                                    FROM v4_4_configuration_history_clusters\n                                                    WHERE datacenter_id IN ($datacenter_id)\n                                                )\n                                        -- Here we filter by the virtual machine/s chosen by the user\n                                        AND v4_4_configuration_history_vms.vm_id IN ($vm_id)\n                                        -- Here we get the latest vm configurations\n                                        AND v4_4_configuration_history_vms.history_id \n                                            IN \n                                                (\n                                                    SELECT MAX ( a.history_id )\n                                                    FROM v4_4_configuration_history_vms a\n                                                    GROUP BY a.vm_id\n                                                )\n                                        AND history_datetime >= $__timeFrom()\n                                        AND history_datetime < $__timeTo()\n                                        -- This will determine if deleted entities will be included in the report,\n                                        -- according to the user selection for \"show_deleted\" parameter\n                                        AND\n                                            CASE\n                                                WHEN '$show_deleted'='Yes'\n                                                    THEN 1=1\n                                                WHEN '$show_deleted'='No'\n                                                    THEN delete_date isnull\n                                            END\n                                ) AS sub_query\n                            GROUP BY vm_id\n                        ) AS samples_sub_queries\n                )\n        -- Show data only when the selected period is more then 24 hours back\n        WHEN $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\n            THEN\n                (\n                    SELECT\n                        COALESCE ( AVG ( mem_above ), 0 ) AS mem_above \n                    FROM \n                        (\n                            SELECT\n                                SUM \n                                    (\n                                        CASE\n                                            WHEN memory_usage_percent >= '$mem_threshold'\n                                                THEN minutes_in_status\n                                            ELSE 0\n                                        END\n                                    ) AS mem_above\n                            FROM \n                                (\n                                    SELECT DISTINCT\n                                        v4_4_configuration_history_vms.vm_id,\n                                        history_datetime,\n                                        memory_usage_percent,\n                                        minutes_in_status\n                                    FROM\n                                        (\n                                                SELECT history_datetime, vm_id, memory_usage_percent, minutes_in_status, vm_status \n                                                FROM v4_4_statistics_vms_resources_usage_hourly\n                                            UNION\n                                                SELECT history_datetime, vm_id, memory_usage_percent, minutes_in_status, vm_status\n                                                FROM v4_4_statistics_vms_resources_usage_daily\n                                                WHERE\n                                                    history_datetime <\n                                                        (\n                                                            SELECT MIN ( history_datetime )\n                                                            FROM v4_4_statistics_vms_resources_usage_hourly\n                                                        )\n                                        ) AS stats_vms\n                                        INNER JOIN v4_4_configuration_history_vms\n                                            ON \n                                                (\n                                                    v4_4_configuration_history_vms.vm_id =\n                                                    stats_vms.vm_id\n                                                )\n                                    WHERE\n                                        -- Here we filter only vm in active status\n                                        stats_vms.vm_status = 1\n                                        -- Here we filter by the datacenter chosen by the users\n                                        AND v4_4_configuration_history_vms.cluster_id \n                                            IN \n                                                (\n                                                    SELECT cluster_id\n                                                    FROM v4_4_configuration_history_clusters\n                                                    WHERE datacenter_id IN ($datacenter_id)\n                                                )\n                                        -- Here we filter by the virtual machine/s chosen by the user\n                                        AND v4_4_configuration_history_vms.vm_id IN ($vm_id)\n                                        -- Here we get the latest vm configurations\n                                        AND v4_4_configuration_history_vms.history_id \n                                            IN \n                                                (\n                                                    SELECT MAX ( a.history_id )\n                                                    FROM v4_4_configuration_history_vms a\n                                                    GROUP BY a.vm_id\n                                                )\n                                        AND history_datetime >= $__timeFrom()\n                                        AND history_datetime < $__timeTo()\n                                        -- This will determine if deleted entities will be included in the report,\n                                        -- according to the user selection for \"show_deleted\" parameter\n                                        AND\n                                            CASE\n                                                WHEN '$show_deleted'='Yes'\n                                                    THEN 1=1\n                                                WHEN '$show_deleted'='No'\n                                                    THEN delete_date isnull\n                                            END\n                                ) AS sub_query\n                            GROUP BY vm_id\n                        ) AS hourly_daily_sub_queries\n                )\n    END"
    }
   ]
  },
  {
   "title": "Time Below CPU Threshold (BR13)",
   "type": "singlestat",
   "description": "This report displays the time virtual machines have performed below CPU threshold.",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 3 },
   "format": "m",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- BR13 - VMs cpu and memory performance\n-- in relation to the thresholds set by the user\n\n-- Time below CPU threshold\nSELECT  \n    CASE \n        -- Show data only when the selected period is up to 24 hours back\n        WHEN $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\n            THEN\n                (\n                    SELECT\n                        COALESCE ( AVG ( cpu_below ), 0 ) AS cpu_below\n                    FROM \n                        (\n                            SELECT\n                                SUM \n                                    (\n                                        CASE\n                                            WHEN cpu_usage_percent < '$cpu_threshold'\n                                                THEN minutes_in_status\n                                            ELSE 0\n                                        END\n                                    ) AS cpu_below\n                            FROM \n                                (\n                                    SELECT DISTINCT\n                                        v4_4_configuration_history_vms.vm_id,\n                                        history_datetime,\n                                        cpu_usage_percent,\n                                        minutes_in_status\n                                    FROM\n                                        (\n                                            SELECT history_datetime, vm_id, cpu_usage_percent, minutes_in_status, vm_status \n                                            FROM v4_4_statistics_vms_resources_usage_samples\n                                        ) AS stats_vms\n                                        INNER JOIN v4_4_configuration_history_vms\n                                            ON \n                                                (\n                                                    v4_4_configuration_history_vms.vm_id =\n                                                    stats_vms.vm_id\n                                                )\n                                    WHERE\n                                        -- Here we filter only vm in active status\n                                        stats_vms.vm_status = 1\n                                        -- Here we filter by the datacenter chosen by the users\n                                        AND v4_4_configuration_history_vms.cluster_id \n                                            IN \n                                                (\n                                                    SELECT cluster_id\n                                                    FROM v4_4_configuration_history_clusters\n                                                    WHERE datacenter_id IN ($datacenter_id)\n                                                )\n                                        -- Here we filter by the virtual machine/s chosen by the user\n                                        AND v4_4_configuration_history_vms.vm_id IN ($vm_id)\n                                        -- Here we get the latest vm configurations\n                                        AND v4_4_configuration_history_vms.history_id \n                                            IN \n                                                (\n                                                    SELECT MAX ( a.history_id )\n                                                    FROM v4_4_configuration_history_vms a\n                                                    GROUP BY a.vm_id\n                                                )\n                                        AND history_datetime >= $__timeFrom()\n                                        AND history_datetime < $__timeTo()\n                                        -- This will determine if deleted entities will be included in the report,\n                                        -- according to the user selection for \"show_deleted\" parameter\n                                        AND\n                                            CASE\n                                                WHEN '$show_deleted'='Yes'\n                                                    THEN 1=1\n                                                WHEN '$show_deleted'='No'\n                                                    THEN delete_date isnull\n                                            END\n                                ) AS sub_query\n                            GROUP BY vm_id\n                        ) AS samples_sub_queries\n                )\n        -- Show data only when the selected period is more then 24 hours back\n        WHEN $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\n            THEN\n                (\n                    SELECT\n                        COALESCE ( AVG ( cpu_below ), 0 ) AS cpu_below \n                    FROM \n                        (\n                            SELECT\n                                SUM \n                                    (\n                                        CASE\n                                            WHEN cpu_usage_percent < '$cpu_threshold'\n                                                THEN minutes_in_status\n                                            ELSE 0\n                                        END\n                                    ) AS cpu_below\n                            FROM \n                                (\n                                    SELECT DISTINCT\n                                        v4_4_configuration_history_vms.vm_id,\n                                        history_datetime,\n                                        cpu_usage_percent,\n                                        minutes_in_status\n                                    FROM\n                                        (\n                                                SELECT history_datetime, vm_id, cpu_usage_percent, minutes_in_status, vm_status \n                                                FROM v4_4_statistics_vms_resources_usage_hourly\n                                            UNION\n                                                SELECT history_datetime, vm_id, cpu_usage_percent, minutes_in_status, vm_status\n                                                FROM v4_4_statistics_vms_resources_usage_daily\n                                                WHERE\n                                                    history_datetime <\n                                                        (\n                                                            SELECT MIN ( history_datetime )\n                                                            FROM v4_4_statistics_vms_resources_usage_hourly\n                                                        )\n                                        ) AS stats_vms\n                                        INNER JOIN v4_4_configuration_history_vms\n                                            ON \n                                                (\n                                                    v4_4_configuration_history_vms.vm_id =\n                                                    stats_vms.vm_id\n                                                )\n                                    WHERE\n                                        -- Here we filter only vm in active status\n                                        stats_vms.vm_status = 1\n                                        -- Here we filter by the datacenter chosen by the users\n                                        AND v4_4_configuration_history_vms.cluster_id \n                                            IN \n                                                (\n                                                    SELECT cluster_id\n                                                    FROM v4_4_configuration_history_clusters\n                                                    WHERE datacenter_id IN ($datacenter_id)\n                                                )\n                                        -- Here we filter by the virtual machine/s chosen by the user\n                                        AND v4_4_configuration_history_vms.vm_id IN ($vm_id)\n                                        -- Here we get the latest vm configurations\n                                        AND v4_4_configuration_history_vms.history_id \n                                            IN \n                                                (\n                                                    SELECT MAX ( a.history_id )\n                                                    FROM v4_4_configuration_history_vms a\n                                                    GROUP BY a.vm_id\n                                                )\n                                        AND history_datetime >= $__timeFrom()\n                                        AND history_datetime < $__timeTo()\n                                        -- This will determine if deleted entities will be included in the report,\n                                        -- according to the user selection for \"show_deleted\" parameter\n                                        AND\n                                            CASE\n                                                WHEN '$show_deleted'='Yes'\n                                                    THEN 1=1\n                                                WHEN '$show_deleted'='No'\n                                                    THEN delete_date isnull\n                                            END\n                                ) AS sub_query\n                            GROUP BY vm_id\n                        ) AS hourly_daily_sub_queries\n                )\n    END"
    }
   ]
  },
  {
   "title": "Time Below Memory Threshold (BR13)",
   "type": "singlestat",
   "description": "This report displays the time virtual machines have performed below memory threshold.",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 3 },
   "format": "m",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- BR13 - VMs cpu and memory performance\n-- in relation to the thresholds set by the user\n\n-- Time below memory threshold\nSELECT  \n    CASE \n        -- Show data only when the selected period is up to 24 hours back\n        WHEN $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\n            THEN\n                (\n                    SELECT\n                        COALESCE ( AVG ( mem_below ), 0 ) AS mem_below\n                    FROM \n                        (\n                            SELECT\n                                SUM \n                                    (\n                                        CASE\n                                            WHEN memory_usage_percent < '$mem_threshold'\n                                                THEN minutes_in_status\n                                            ELSE 0\n                                        END\n                                    ) AS mem_below\n                            FROM \n                                (\n                                    SELECT DISTINCT\n                                        v4_4_configuration_history_vms.vm_id,\n                                        history_datetime,\n                                        memory_usage_percent,\n                                        minutes_in_status\n                                    FROM\n                                        (\n                                            SELECT history_datetime, vm_id, memory_usage_percent, minutes_in_status, vm_status \n                                            FROM v4_4_statistics_vms_resources_usage_samples\n                                        ) AS stats_vms\n                                        INNER JOIN v4_4_configuration_history_vms\n                                            ON \n                                                (\n                                                    v4_4_configuration_history_vms.vm_id =\n                                                    stats_vms.vm_id\n                                                )\n                                    WHERE\n                                        -- Here we filter only vm in active status\n                                        stats_vms.vm_status = 1\n                                        -- Here we filter by the datacenter chosen by the users\n                                        AND v4_4_configuration_history_vms.cluster_id \n                                            IN \n                                                (\n                                                    SELECT cluster_id\n                                                    FROM v4_4_configuration_history_clusters\n                                                    WHERE datacenter_id IN ($datacenter_id)\n                                                )\n                                        -- Here we filter by the virtual machine/s chosen by the user\n                                        AND v4_4_configuration_history_vms.vm_id IN ($vm_id)\n                                        -- Here we get the latest vm configurations\n                                        AND v4_4_configuration_history_vms.history_id \n                                            IN \n                                                (\n                                                    SELECT MAX ( a.history_id )\n                                                    FROM v4_4_configuration_history_vms a\n                                                    GROUP BY a.vm_id\n                                                )\n                                        AND history_datetime >= $__timeFrom()\n                                        AND history_datetime < $__timeTo()\n                                        -- This will determine if deleted entities will be included in the report,\n                                        -- according to the user selection for \"show_deleted\" parameter\n                                        AND\n                                            CASE\n                                                WHEN '$show_deleted'='Yes'\n                                                    THEN 1=1\n                                                WHEN '$show_deleted'='No'\n                                                    THEN delete_date isnull\n                                            END\n                                ) AS sub_query\n                            GROUP BY vm_id\n                        ) AS samples_sub_queries\n                )\n        -- Show data only when the selected period is more then 24 hours back\n        WHEN $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\n            THEN\n                (\n                    SELECT\n                        COALESCE ( AVG ( mem_below ), 0 ) AS mem_below \n                    FROM \n                        (\n                            SELECT\n                                SUM \n                                    (\n                                        CASE\n                                            WHEN memory_usage_percent < '$mem_threshold'\n                                                THEN minutes_in_status\n                                            ELSE 0\n                                        END\n                                    ) AS mem_below\n                            FROM \n                                (\n                                    SELECT DISTINCT\n                                        v4_4_configuration_history_vms.vm_id,\n                                        history_datetime,\n                                        memory_usage_percent,\n                                        minutes_in_status\n                                    FROM\n                                        (\n                                                SELECT history_datetime, vm_id, memory_usage_percent, minutes_in_status, vm_status \n                                                FROM v4_4_statistics_vms_resources_usage_hourly\n                                            UNION\n                                                SELECT history_datetime, vm_id, memory_usage_percent, minutes_in_status, vm_status\n                                                FROM v4_4_statistics_vms_resources_usage_daily\n                                                WHERE\n                                                    history_datetime <\n                                                        (\n                                                            SELECT MIN ( history_datetime )\n                                                            FROM v4_4_statistics_vms_resources_usage_hourly\n                                                        )\n                                        ) AS stats_vms\n                                        INNER JOIN v4_4_configuration_history_vms\n                                            ON \n                                                (\n                                                    v4_4_configuration_history_vms.vm_id =\n                                                    stats_vms.vm_id\n                                                )\n                                    WHERE\n                                        -- Here we filter only vm in active status\n                                        stats_vms.vm_status = 1\n                                        -- Here we filter by the datacenter chosen by the users\n                                        AND v4_4_configuration_history_vms.cluster_id \n                                            IN \n                                                (\n                                                    SELECT cluster_id\n                                                    FROM v4_4_configuration_history_clusters\n                                                    WHERE datacenter_id IN ($datacenter_id)\n                                                )\n                                        -- Here we filter by the virtual machine/s chosen by the user\n                                        AND v4_4_configuration_history_vms.vm_id IN ($vm_id)\n                                        -- Here we get the latest vm configurations\n                                        AND v4_4_configuration_history_vms.history_id \n                                            IN \n                                                (\n                                                    SELECT MAX ( a.history_id )\n                                                    FROM v4_4_configuration_history_vms a\n                                                    GROUP BY a.vm_id\n                                                )\n                                        AND history_datetime >= $__timeFrom()\n                                        AND history_datetime < $__timeTo()\n                                        -- This will determine if deleted entities will be included in the report,\n                                        -- according to the user selection for \"show_deleted\" parameter\n                                        AND\n                                            CASE\n                                                WHEN '$show_deleted'='Yes'\n                                                    THEN 1=1\n                                                WHEN '$show_deleted'='No'\n                                                    THEN delete_date isnull\n                                            END\n                                ) AS sub_query\n                            GROUP BY vm_id\n                        ) AS hourly_daily_sub_queries\n                )\n    END"
    }
   ]
  },
  {
   "title": "Cluster Quality of Service - Virtual Machines (BR13)",
   "type": "table-old",
   "description": "This report displays the total time each virtual machine have performed above the CPU or the memory threshold.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "-- BR13 - Cluster Quality of Service - Virtual Machines\n-- This query returns for each vm in the specific datacenter,\n-- the  \"time_above_cpu_threshold\", the \"time_above_mem_threshold\"\n-- and the \"overall_vm_time\".\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT *\nFROM \n    (\n        SELECT\n            cluster_id,\n            vm_id,\n            vm_name,\n            is_delete,\n            vm_delete_only_date,\n            SUM \n                (\n                    CASE\n                        WHEN cpu_usage_percent >= '$cpu_threshold'\n                            THEN minutes_in_status\n                        ELSE 0\n                    END\n                ) AS time_above_cpu_threshold,\n            SUM \n                (\n                    CASE\n                        WHEN memory_usage_percent >= '$mem_threshold'\n                            THEN minutes_in_status\n                        ELSE 0\n                    END\n                ) AS time_above_mem_threshold,\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS overall_vm_time\n        FROM \n            (\n                SELECT DISTINCT\n                    v4_4_configuration_history_vms.cluster_id,\n                    v4_4_configuration_history_vms.vm_id,\n                    v4_4_configuration_history_vms.vm_name,\n                    (\n                        CASE\n                            WHEN v4_4_configuration_history_vms.delete_date IS NULL\n                                THEN FALSE\n                            ELSE TRUE\n                        END\n                    ) AS is_delete,\n                    CAST ( v4_4_configuration_history_vms.delete_date AS date ) AS vm_delete_only_date,\n                    stats_vms.history_datetime,\n                    cpu_usage_percent,\n                    memory_usage_percent,\n                    minutes_in_status\n                FROM\n                    (\n                        SELECT history_datetime, vm_id, cpu_usage_percent, memory_usage_percent, minutes_in_status, vm_status \n                        FROM v4_4_statistics_vms_resources_usage_samples\n                    ) AS stats_vms\n                    INNER JOIN v4_4_configuration_history_vms\n                        ON \n                            (\n                                stats_vms.vm_id =\n                                v4_4_configuration_history_vms.vm_id\n                            )\n                WHERE\n                    -- Here we get only vms in active status\n                    stats_vms.vm_status = 1\n                    -- Here we filter by the datacenter chosen by the user\n                    AND v4_4_configuration_history_vms.cluster_id \n                        IN \n                            (\n                                SELECT cluster_id\n                                FROM v4_4_configuration_history_clusters\n                                WHERE datacenter_id IN ($datacenter_id)\n                            )\n                    -- Here we filter by the virtual machine/s chosen by the user\n                    AND v4_4_configuration_history_vms.vm_id IN ($vm_id)\n                    -- Here we get the latest vm configurations\n                    AND v4_4_configuration_history_vms.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_vms a\n                                GROUP BY a.vm_id\n                            )\n                    AND stats_vms.history_datetime >= $__timeFrom()\n                    AND stats_vms.history_datetime < $__timeTo()\n                    -- This will determine if deleted entities will be included in the report,\n                    -- according to the user selection for \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n            ) AS sub_query\n        GROUP BY\n            cluster_id,\n            vm_id,\n            vm_name,\n            is_delete,\n            vm_delete_only_date\n    ) AS all_sub_queries\n-- Show data only when the selected period is up to 24 hours back \nWHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\nORDER BY\n    cluster_id,\n    (\n        CASE\n            WHEN time_above_mem_threshold = 0 AND time_above_cpu_threshold = 0\n                THEN 1 -- Memory and cpu are below the threshold\n            ELSE 0 -- Memory and / or cpu are above threshold\n        END\n    ) ASC,\n    all_sub_queries.is_delete ASC,\n    -- This will order the vms based on the time the memory and cpu\n    -- where above the threshold out of the overall vm time.\n    ( CAST ( all_sub_queries.time_above_cpu_threshold AS float ) / CAST ( all_sub_queries.overall_vm_time AS float ) ) * 100 +\n    ( CAST ( all_sub_queries.time_above_mem_threshold AS float ) / CAST ( all_sub_queries.overall_vm_time AS float ) ) *100 DESC"
    },
    {
     "rawSql": "-- BR13 - Cluster Quality of Service - Virtual Machines\n-- This query returns for each vm in the specific datacenter,\n-- the  \"time_above_cpu_threshold\", the \"time_above_mem_threshold\"\n-- and the \"overall_vm_time\".\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT *\nFROM \n    (\n        SELECT\n            cluster_id,\n            vm_id,\n            vm_name,\n            is_delete,\n            vm_delete_only_date,\n            SUM \n                (\n                    CASE\n                        WHEN cpu_usage_percent >= '$cpu_threshold'\n                            THEN minutes_in_status\n                        ELSE 0\n                    END\n                ) AS time_above_cpu_threshold,\n            SUM \n                (\n                    CASE\n                        WHEN memory_usage_percent >= '$mem_threshold'\n                            THEN minutes_in_status\n                        ELSE 0\n                    END\n                ) AS time_above_mem_threshold,\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS overall_vm_time\n        FROM \n            (\n                SELECT DISTINCT\n                    v4_4_configuration_history_vms.cluster_id,\n                    v4_4_configuration_history_vms.vm_id,\n                    v4_4_configuration_history_vms.vm_name,\n                    (\n                        CASE\n                            WHEN v4_4_configuration_history_vms.delete_date IS NULL\n                                THEN FALSE\n                            ELSE TRUE\n                        END\n                    ) AS is_delete,\n                    CAST ( v4_4_configuration_history_vms.delete_date AS date ) AS vm_delete_only_date,\n                    stats_vms.history_datetime,\n                    cpu_usage_percent,\n                    memory_usage_percent,\n                    minutes_in_status\n                FROM\n                    (\n                            SELECT history_datetime, vm_id, cpu_usage_percent, memory_usage_percent, minutes_in_status, vm_status \n                            FROM v4_4_statistics_vms_resources_usage_hourly\n                        UNION\n                            SELECT history_datetime, vm_id, cpu_usage_percent, memory_usage_percent, minutes_in_status, vm_status\n                            FROM v4_4_statistics_vms_resources_usage_daily\n                            WHERE\n                                history_datetime <\n                                    (\n                                        SELECT MIN ( history_datetime )\n                                        FROM v4_4_statistics_vms_resources_usage_hourly\n                                    )\n                    ) AS stats_vms\n                    INNER JOIN v4_4_configuration_history_vms\n                        ON \n                            (\n                                stats_vms.vm_id =\n                                v4_4_configuration_history_vms.vm_id\n                            )\n                WHERE\n                    -- Here we get only vms in active status\n                    stats_vms.vm_status = 1\n                    -- Here we filter by the datacenter chosen by the user\n                    AND v4_4_configuration_history_vms.cluster_id \n                        IN \n                            (\n                                SELECT cluster_id\n                                FROM v4_4_configuration_history_clusters\n                                WHERE datacenter_id IN ($datacenter_id)\n                            )\n                    -- Here we filter by the virtual machine/s chosen by the user\n                    AND v4_4_configuration_history_vms.vm_id IN ($vm_id)\n                    -- Here we get the latest vm configurations\n                    AND v4_4_configuration_history_vms.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_vms a\n                                GROUP BY a.vm_id\n                            )\n                    AND stats_vms.history_datetime >= $__timeFrom()\n                    AND stats_vms.history_datetime < $__timeTo()\n                    -- This will determine if deleted entities will be included in the report,\n                    -- according to the user selection for \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n            ) AS sub_query\n        GROUP BY\n            cluster_id,\n            vm_id,\n            vm_name,\n            is_delete,\n            vm_delete_only_date\n    ) AS all_sub_queries\n-- Show data only when the selected period is more then 24 hours back\nWHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\nORDER BY\n    cluster_id,\n    (\n        CASE\n            WHEN time_above_mem_threshold = 0 AND time_above_cpu_threshold = 0\n                THEN 1 -- Memory and cpu are below the threshold\n            ELSE 0 -- Memory and / or cpu are above threshold\n        END\n    ) ASC,\n    all_sub_queries.is_delete ASC,\n    -- This will order the vms based on the time the memory and cpu\n    -- where above the threshold out of the overall vm time.\n    ( CAST ( all_sub_queries.time_above_cpu_threshold AS float ) / CAST ( all_sub_queries.overall_vm_time AS float ) ) * 100 +\n    ( CAST ( all_sub_queries.time_above_mem_threshold AS float ) / CAST ( all_sub_queries.overall_vm_time AS float ) ) *100 DESC"
    }
   ]
  }
 ]
}