{
 "title": "Adm Gitlab",
 "description": "Ответственный: Смирнов К.В. (Эксплуатация)",
 "tags": [
  "telegraf",
  "GitLab",
  "service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "tag_values(host,host=adm-git.unix.tensor.ru)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Аптайм системы",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=system.system.uptime')"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "description": "Load Average за 1, 5 и 15 минут",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'name=~system.system.load*'), 'name')"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Загрузка по памяти",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'name=system.mem.used_percent'), 'name')"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "description": "Процент использования swap",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'name=system.swap.used_percent'), 'name')"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "graph",
   "description": "Процент использования разделов диска",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=$host', 'name=system.disk.used_percent', 'path!=-boot'), 'path'), '-', '/')"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "description": "Статистика по сетевым интерфейсам",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('host=$host', 'name=~system.net.bytes_*')), 'name')"
    }
   ]
  },
  {
   "title": "Disk Activity In/Out",
   "type": "graph",
   "description": "Статистика по использованию дисков",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(aliasByTags(sumSeries(perSecond(seriesByTag('host=$host', 'name=~system.diskio.read_bytes'))), 'name', '_name'), 'system.diskio.read_bytes')"
    },
    {
     "target": "alias(aliasByTags(sumSeries(perSecond(seriesByTag('host=$host', 'name=~system.diskio.write_bytes'))), 'name', '_name'), 'system.diskio.write_bytes')"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "graph",
   "description": "Показатель, означающий процентное соотношение времени процессора, потраченное на ожидание ввода/вывода.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'name=system.cpu.usage_iowait', 'cpu=cpu-total'), 'cpu')"
    }
   ]
  },
  {
   "title": "Connected Users",
   "type": "graph",
   "description": "Количество коннектов",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "пользователи" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'name=nginx.active'), 'name')"
    }
   ]
  },
  {
   "title": "HTTP Response time",
   "type": "graph",
   "description": "Статистика по времени ответа",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'name=http_response.response_time'), 'name')"
    }
   ]
  },
  {
   "title": "HTTP Access code",
   "type": "graph",
   "description": "Код ответа",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "код ответа" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'name=http_response.http_response_code'), 'name')"
    }
   ]
  }
 ]
}