{
 "title": "Automation Hub",
 "description": "Ответственный: Добровольский А.И. (АЦОД)",
 "tags": [ "telegraf" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "servertype",
    "query": "tag_values(servertype, servertype=autohub)"
   },
   {
    "name": "contur",
    "query": "tag_values(contur,servertype=$servertype)"
   },
   {
    "name": "autohub_url",
    "query": "tag_values(autohub_url,contur=$contur,servertype=$servertype)"
   }
  ]
 },
 "panels": [
  { "title": "QUICK REVIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Automation Hub - Response",
   "type": "stat",
   "description": "Код ответа autohub.\n\nЕсли сервис возвращает 200 - то всё ок,\nиначе выводит код возврата ",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "groupByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'name=http_response.http_response_code', 'servertype=autohub'), 'sum', 'server')"
    }
   ]
  },
  {
   "title": "Статус основных служб autohub",
   "type": "stat",
   "description": "Статус основных служб автохаба.\n\nОК - служба запущена\n\nError - служба завершилась с ошибкой, выключена, или находится в состоянии перезапуска",
   "gridPos": { "h": 5, "w": 18, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByTags(groupByTags(keepLastValue(seriesByTag('autohub_url=~${autohub_url:regex}', 'serverrole=service', '_name=~pulp*', 'name=systemd_units.active_code'), 6), 'sum', '_name'), '_name'), '.service', ''))"
    }
   ]
  },
  {
   "title": "Статус службы postgresql",
   "type": "stat",
   "description": "Статус службы postgresql на сервере БД.\n\nОК - служба запущена\n\nError - служба завершилась с ошибкой, выключена, или находится в состоянии перезапуска",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', '_name=~postgresql*', 'name=systemd_units.active_code', 'active=~*')"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "description": "Текущее использование CPU на серверах инстанса autohub",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.cpu.usage_active', 'cpu=cpu-total'), 'host')"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "description": "Текущее использование памяти на серверах инстанса autohub",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(asPercent(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.mem.used'), #B), 'host')",
     "targetFull": "aliasByTags(asPercent(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.mem.used'), aliasByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.mem.total'), 'host')), 'host')"
    }
   ]
  },
  {
   "title": "/var/lib/pgsql/",
   "type": "gauge",
   "description": "Объем базы данных postgresql",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.disk.used_percent', 'path=~-var-lib-pgsql*'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Uptime сервера autohub",
   "type": "stat",
   "description": "Время с последнего запуска серверов инстанса autohub",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.system.uptime'), 'host')"
    }
   ]
  },
  {
   "title": "Automation Hub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Automation Hub - CPU",
     "type": "timeseries",
     "description": "% использования процессора",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "sortByMaxima(aliasSub(aliasByTags(exclude(exclude(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=~system.cpu*', 'cpu=cpu-total', 'serverrole=service'), 'idle'), 'active'), 'name'), 'system.cpu.usage_', ''))"
      }
     ]
    },
    {
     "title": "Automation Hub - CPU usage by core",
     "type": "timeseries",
     "description": "% использования процессора по каждому ядру",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(groupByTags(exclude(exclude(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'cpu=~cpu*', 'serverrole=service'), 'idle'), 'usage_active'), 'sum', 'cpu'), 'cpu'), false)"
      }
     ]
    },
    {
     "title": "Automation Hub - CPU load average",
     "type": "timeseries",
     "description": "Среднее значение загрузки CPU за 1, 5 и 15 минут",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=~system.system.load(1|5|15)', 'serverrole=service'), 'name'), 'system.system.', '')"
      }
     ]
    },
    {
     "title": "Automation Hub - CPU context switches",
     "type": "timeseries",
     "description": "Переключение контекста",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(perSecond(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.kernel.context_switches', 'serverrole=service')), 'name'), 'system.kernel.', '')"
      }
     ]
    },
    {
     "title": "Automation Hub - Memory usage",
     "type": "timeseries",
     "description": "Использование оперативной памяти",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.mem.used', 'serverrole=service'), 'name'), 'system.mem.', '')"
      },
      {
       "target": "aliasSub(aliasByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.mem.total', 'serverrole=service'), 'name'), 'system.mem.', '')"
      }
     ]
    },
    {
     "title": "Automation Hub - Timeline статуса служб pulp",
     "type": "timeseries",
     "description": "Статус основных служб автохаба.\n\nОК - служба запущена.\n\nЛюбое другое значение - сервис находится в ненормальном состоянии.\nOK - active,\n1 - reloading,\n2 - inactive,\n3 - failed,\n4 - activating,\n5 - deactivating\n\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "target": "sortByName(aliasSub(aliasByTags(groupByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', '_name=~pulp*', 'name=systemd_units.active_code', 'serverrole=service'), 'sum', '_name'), '_name'), '.service', ''))"
      }
     ]
    },
    {
     "title": "Automation Hub - Disk iops",
     "type": "timeseries",
     "description": "Количество операций чтения/записи в секунду",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(perSecond(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=~system.diskio.reads', 'serverrole=service')), '_name', 'name'), 'system.diskio.', '')"
      },
      {
       "target": "aliasSub(aliasByTags(perSecond(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=~system.diskio.writes', 'serverrole=service')), '_name', 'name'), 'system.diskio.', '')"
      }
     ]
    },
    {
     "title": "Automation Hub - Disk i/o time",
     "type": "timeseries",
     "description": "Время ожидания операции чтения/записи",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.diskio.io_time', 'serverrole=service')), '_name'))"
      }
     ]
    },
    {
     "title": "Automation Hub - Disk bps",
     "type": "timeseries",
     "description": "Объем чтения и записи данных с блочных устройств в байтах в секунду",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(perSecond(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=~system.diskio.*_bytes', 'serverrole=service')), '_name', 'name'), 'system.diskio.', '')"
      }
     ]
    },
    {
     "title": "Automation Hub - Used space",
     "type": "bargauge",
     "description": "% занятого места",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.disk.used_percent', 'serverrole=service'), 'path'), '-', '/')"
      }
     ]
    },
    {
     "title": "Automation Hub - Netowk pps",
     "type": "timeseries",
     "description": "Количество пакетов в секунду",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(perSecond(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=~system.net.packets_*', 'serverrole=service')), 'interface', 'name'), 'system.net.', '')"
      }
     ]
    },
    {
     "title": "Automation Hub - Network bps",
     "type": "timeseries",
     "description": "Количество байтов в секунду",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(perSecond(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=~system.net.bytes_*', 'serverrole=service')), 'interface', 'name'), 'system.net.', '')"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL - CPU",
     "type": "timeseries",
     "description": "% использования процессора",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "sortByMaxima(aliasSub(aliasByTags(exclude(exclude(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=~system.cpu*', 'cpu=cpu-total', 'serverrole=database'), 'idle'), 'active'), 'name'), 'system.cpu.usage_', ''))"
      }
     ]
    },
    {
     "title": "PostgreSQL - CPU usage by core",
     "type": "timeseries",
     "description": "% использования процессора по каждому ядру",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(groupByTags(exclude(exclude(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'cpu=~cpu*', 'serverrole=database'), 'idle'), 'usage_active'), 'sum', 'cpu'), 'cpu'), false)"
      }
     ]
    },
    {
     "title": "PostgreSQL - CPU load average",
     "type": "timeseries",
     "description": "Среднее значение загрузки CPU за 1, 5 и 15 минут",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=~system.system.load(1|5|15)', 'serverrole=database'), 'name'), 'system.system.', '')"
      }
     ]
    },
    {
     "title": "PostgreSQL - CPU context switches",
     "type": "timeseries",
     "description": "Переключение контекста",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(perSecond(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.kernel.context_switches', 'serverrole=database')), 'name'), 'system.kernel.', '')"
      }
     ]
    },
    {
     "title": "PostgreSQL - Memory usage",
     "type": "timeseries",
     "description": "Использование оперативной памяти",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.mem.used', 'serverrole=database'), 'name'), 'system.mem.', '')"
      },
      {
       "target": "aliasSub(aliasByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.mem.total', 'serverrole=database'), 'name'), 'system.mem.', '')"
      }
     ]
    },
    {
     "title": "PostgreSQL - Timeline статуса службы postgresql",
     "type": "timeseries",
     "description": "Статус службы Postgresql.\n\nОК - служба запущена.\n\nЛюбое другое значение - сервис находится в ненормальном состоянии.\nOK - active,\n1 - reloading,\n2 - inactive,\n3 - failed,\n4 - activating,\n5 - deactivating\n\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "target": "sortByName(aliasSub(aliasByTags(groupByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', '_name=~postgres*', 'name=systemd_units.active_code'), 'sum', '_name'), '_name'), '.service', ''))"
      }
     ]
    },
    {
     "title": "PostgreSQL - Disk iops",
     "type": "timeseries",
     "description": "Количество операций чтения/записи в секунду",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(perSecond(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=~system.diskio.reads', 'serverrole=database')), '_name', 'name'), 'system.diskio.', '')"
      },
      {
       "target": "aliasSub(aliasByTags(perSecond(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=~system.diskio.writes', 'serverrole=database')), '_name', 'name'), 'system.diskio.', '')"
      }
     ]
    },
    {
     "title": "PostgreSQL - Disk i/o time",
     "type": "timeseries",
     "description": "Время ожидания операции чтения/записи",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.diskio.io_time', 'serverrole=database')), '_name')"
      }
     ]
    },
    {
     "title": "PostgreSQL - Disk bps",
     "type": "timeseries",
     "description": "Объем чтения и записи данных с блочных устройств в байтах в секунду",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(perSecond(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=~system.diskio.*_bytes', 'serverrole=database')), '_name', 'name'), 'system.diskio.', '')"
      }
     ]
    },
    {
     "title": "PostgreSQL - Used space",
     "type": "bargauge",
     "description": "% занятого места",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.disk.used_percent', 'serverrole=database'), 'path'), '-', '/')"
      }
     ]
    },
    {
     "title": "PostgreSQL - Netowk pps",
     "type": "timeseries",
     "description": "Количество пакетов в секунду",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(perSecond(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=~system.net.packets_*', 'serverrole=database')), 'interface', 'name'), 'system.net.', '')"
      }
     ]
    },
    {
     "title": "PostgreSQL - Network bps",
     "type": "timeseries",
     "description": "Количество байтов в секунду",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(perSecond(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=~system.net.bytes_*', 'serverrole=database')), 'interface', 'name'), 'system.net.', '')"
      }
     ]
    },
    {
     "title": "PostgreSQL - PG_DATA used space",
     "type": "timeseries",
     "description": "Динамика изменения занимаемого пространства PG_DATA",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.disk.used', 'path=~-var-lib-pgsql*'), 'name'), '-', '/'), 'system.disk.', '')"
      },
      {
       "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('autohub_url=~${autohub_url:regex}', 'servertype=autohub', 'name=system.disk.total', 'path=~-var-lib-pgsql*'), 'name'), '-', '/'), 'system.disk.', '')"
      }
     ]
    }
   ]
  }
 ]
}