{
 "title": "AWX",
 "description": "Ответственный: Забродин А.Н. (Эксплуатация)",
 "tags": [
  "telegraf",
  "service"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "awx_address", "query": "tag_values(instance, job=awx)" }
  ]
 },
 "panels": [
  {
   "title": "AWX version",
   "type": "stat",
   "description": "Текущая версия AWX",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('job=awx', 'instance=$awx_address', 'name=prometheus_remote_write.awx_instance_info'), 'version')"
    }
   ]
  },
  {
   "title": "Backends",
   "type": "stat",
   "description": "Кол-во управляющих POD'ов AWX",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "consolidateBy(aggregate(seriesByTag('name=prometheus_remote_write.awx_instance_info', 'instance=$awx_address'), 'sum'), 'max')"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "stat",
   "description": "Общее кол-во проектов",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('job=awx', 'name=prometheus_remote_write.awx_projects_total', 'instance=$awx_address')"
    }
   ]
  },
  {
   "title": "Templates",
   "type": "stat",
   "description": "Общее кол-во шаблонов",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('job=awx', 'name=prometheus_remote_write.awx_job_templates_total', 'instance=$awx_address')"
    }
   ]
  },
  {
   "title": "Teams",
   "type": "stat",
   "description": "Общее кол-во команд (подразделений) со связанными пользователями, проектами и учетными данными",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('job=awx', 'name=prometheus_remote_write.awx_teams_total', 'instance=$awx_address')"
    }
   ]
  },
  {
   "title": "Workflow",
   "type": "stat",
   "description": "Общее кол-во workflow шаблонов",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('job=awx', 'name=prometheus_remote_write.awx_workflow_job_templates_total', 'instance=$awx_address')"
    }
   ]
  },
  {
   "title": "Inventories",
   "type": "stat",
   "description": "Общее кол-во групп с управляемыми хостами",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('job=awx', 'name=prometheus_remote_write.awx_inventories_total', 'instance=$awx_address')"
    }
   ]
  },
  {
   "title": "Organizations",
   "type": "stat",
   "description": "Общее кол-во организаций, включающих в себя пользователей, команд, проектов и групп управляемых хостов",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('job=awx', 'name=prometheus_remote_write.awx_organizations_total', 'instance=$awx_address')"
    }
   ]
  },
  {
   "title": "Total jobs running",
   "type": "gauge",
   "description": "Общее кол-во запущенных задач",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "consolidateBy(transformNull(seriesByTag('job=awx', 'name=prometheus_remote_write.awx_running_jobs_total', 'instance=$awx_address'), 0), 'last')"
    }
   ]
  },
  {
   "title": "Current redis queue",
   "type": "gauge",
   "description": "Current number of events in redis queue",
   "gridPos": { "h": 4, "w": 12, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(seriesByTag('job=awx', 'name=prometheus_remote_write.callback_receiver_events_queue_size_redis', 'instance=$awx_address'), 'last'), 'node')"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "description": "Общее кол-во пользователей системы",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('job=awx', 'name=prometheus_remote_write.awx_users_total', 'instance=$awx_address')"
    }
   ]
  },
  {
   "title": "Schedules",
   "type": "stat",
   "description": "Общее кол-во задач, выполняемых по расписанию",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('job=awx', 'name=prometheus_remote_write.awx_schedules_total', 'instance=$awx_address')"
    }
   ]
  },
  {
   "title": "Total jobs successful",
   "type": "stat",
   "description": "Общее кол-во успешно выполненных задач",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('job=awx', 'name=prometheus_remote_write.awx_status_total', 'instance=$awx_address', 'status=successful')"
    }
   ]
  },
  {
   "title": "Total jobs failed",
   "type": "stat",
   "description": "Общее кол-во безуспешно выполненных задач",
   "gridPos": { "h": 5, "w": 8, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('job=awx', 'name=prometheus_remote_write.awx_status_total', 'instance=$awx_address', 'status=failed')"
    }
   ]
  },
  {
   "title": "Total jobs pending",
   "type": "gauge",
   "description": "Общее кол-во незавершенных задач",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "transformNull(seriesByTag('job=awx', 'name=prometheus_remote_write.awx_pending_jobs_total', 'instance=$awx_address'), 0)"
    }
   ]
  },
  {
   "title": "Backend stats",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Stats for failed and successful jobs per node",
   "gridPos": { "h": 5, "w": 16, "x": 3, "y": 13 },
   "targets": [
    {
     "target": "consolidateBy(aliasByTags(seriesByTag('job=awx', 'name=prometheus_remote_write.awx_instance_remaining_capacity', 'instance=$awx_address'), 0, 'hostname'), 'last')"
    },
    {
     "target": "consolidateBy(aliasByTags(transformNull(seriesByTag('job=awx', 'name=prometheus_remote_write.awx_instance_consumed_capacity', 'instance=$awx_address'), 0), 0, 'hostname'), 'last')"
    },
    {
     "target": "consolidateBy(aliasByTags(seriesByTag('job=awx', 'name=prometheus_remote_write.awx_instance_status_total', 'status=successful', 'instance=$awx_address'), 'status', 'node'), 'last')"
    },
    {
     "target": "consolidateBy(aliasByTags(seriesByTag('job=awx', 'name=prometheus_remote_write.awx_instance_status_total', 'status=failed', 'instance=$awx_address'), 'status', 'node'), 'last')"
    },
    {
     "target": "consolidateBy(aliasByTags(seriesByTag('job=awx', 'name=prometheus_remote_write.awx_instance_status_total', 'status=running', 'instance=$awx_address'), 'status', 'node'), 'last')"
    },
    {
     "target": "consolidateBy(aliasByTags(seriesByTag('job=awx', 'name=prometheus_remote_write.awx_instance_status_total', 'status=canceled', 'instance=$awx_address'), 'status', 'node'), 'last')"
    }
   ]
  },
  {
   "title": "Total jobs waiting",
   "type": "gauge",
   "description": "NO INFO IN NEW AWX",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "seriesByTag('job=awx', 'name=prometheus_remote_write.awx_status_total', 'instance=$awx_address', 'status=waiting')"
    }
   ]
  },
  {
   "title": "Total users / Online users",
   "type": "bargauge",
   "description": "Кол-во открытых сеансов пользователей (Все/Анонимные/Авторизованные)",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_users_total",
     "legendFormat": "Total",
     "target": "alias(seriesByTag('job=awx', 'name=prometheus_remote_write.awx_users_total', 'instance=$awx_address'), 'total')"
    },
    {
     "expr": "count(awx_sessions_total{type=\"user\"})",
     "legendFormat": "Users",
     "target": "aliasByTags(seriesByTag('job=awx', 'name=prometheus_remote_write.awx_sessions_total', 'instance=$awx_address'), 'type')"
    }
   ]
  },
  {
   "title": "Inventory hosts",
   "type": "bargauge",
   "description": "Кол-во управляемых хостов (Всего/Активных)",
   "gridPos": { "h": 5, "w": 8, "x": 11, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_users_total",
     "legendFormat": "Total",
     "target": "aliasByTags(seriesByTag('job=awx', 'name=prometheus_remote_write.awx_hosts_total', 'instance=$awx_address'), 'type')"
    }
   ]
  }
 ]
}