{
 "title": "DC",
 "description": "Ответственный: Добровольский А.И. (АЦОД)",
 "tags": [
  "test_scripts",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now-1m" },
 "panels": [
  {
   "title": "LDAP Bind Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('domain=corp.tensor.ru', 'name=DirectoryServices_ntds.LDAP_Bind_Time', 'objectname=DirectoryServices', 'host=~*'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "LDAP Client Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('domain=corp.tensor.ru', 'name=DirectoryServices_ntds.LDAP_Client_Sessions', 'objectname=DirectoryServices', 'host=~*'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "LDAP Searches/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('domain=corp.tensor.ru', 'name=DirectoryServices_ntds.LDAP_Searches_persec', 'objectname=DirectoryServices', 'host=~*'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "LDAP Successful Binds/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('domain=corp.tensor.ru', 'name=DirectoryServices_ntds.LDAP_Successful_Binds_persec', 'objectname=DirectoryServices', 'host=~*'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Database Cache % hit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('domain=corp.tensor.ru', 'objectname=Database', 'host=~*', 'name=Database_lsass.Database_Cache_Percent_Hit'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Database Cache Requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('domain=corp.tensor.ru', 'objectname=Database', 'host=~*', 'name=Database_lsass.Database_Cache_Requests_persec'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Database Cache Miss/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('domain=corp.tensor.ru', 'objectname=Database', 'host=~*', 'name=Database_lsass.Database_Cache_Misses_persec'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "LSASS Processortime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('domain=corp.tensor.ru', 'objectname=Process', 'host=~*', 'name=Process_lsass.Percent_Processor_Time'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "DNS Processortime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('domain=corp.tensor.ru', 'objectname=Process', 'host=~*', 'name=Process_dns.Percent_Processor_Time'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 32 },
   "targets": [
    {
     "target": "seriesByTag('domain=corp.tensor.ru', 'host=~*', 'servertype=domaincontroller', 'service_name=~*', 'name=win_services.state', 'interval=10s')"
    }
   ]
  },
  {
   "title": "C: used Pct",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.windows.partition.dc1.interval-60sec.partition.volume.C.pct.raw, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.partition.dc3.interval-60sec.partition.volume.C.pct.raw, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.partition.dc4.interval-60sec.partition.volume.C.pct.raw, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.partition.dc5.interval-60sec.partition.volume.C.pct.raw, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.partition.dev-dc0*.interval-60sec.partition.volume.C.pct.raw, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.partition.ea1-dc0*.interval-60sec.partition.volume.C.pct.raw, 4)"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.windows.cpu.dc1.interval-1sec.cpu.busy.raw, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.cpu.dc3.interval-1sec.cpu.busy.raw, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.cpu.dc4.interval-1sec.cpu.busy.raw, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.cpu.dc5.interval-1sec.cpu.busy.raw, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.cpu.dev-dc0*.interval-1sec.cpu.busy.raw, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.cpu.ea1-dc0*.interval-1sec.cpu.busy.raw, 4)"
    }
   ]
  },
  {
   "title": "Mem Free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.prod.windows.memory.dc1.interval-28sec.mem.ram.free.min, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.memory.dc3.interval-28sec.mem.ram.free.min, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.memory.dc4.interval-28sec.mem.ram.free.min, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.memory.dc5.interval-28sec.mem.ram.free.min, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.memory.dev-dc0*.interval-28sec.mem.ram.free.min, 4)"
    },
    {
     "target": "aliasByNode(sbis3mon.prod.windows.memory.ea1-dc0*.interval-28sec.mem.ram.free.min, 4)"
    }
   ]
  }
 ]
}