{
 "title": "DHCP Widows",
 "description": "Ответственный: Гончаров З.А. (АЦОД)",
 "tags": [ "telegraf" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "tag_values(host)" },
   {
    "name": "score_id",
    "query": "tag_values(scope_id,host=$host,scope_id!=~(10.52.13.0|10.76.56.0|10.76.7.0))"
   }
  ]
 },
 "panels": [
  {
   "title": "Всего адресов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sum(seriesByTag('host=$host', 'name=~dhcp_stats.(free|in_use)'))"
    }
   ]
  },
  {
   "title": "Всего пулов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sum(seriesByTag('host=$host', 'name=dhcp_stats.scope'))"
    }
   ]
  },
  {
   "title": "Использовано адресов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sum(seriesByTag('host=$host', 'name=dhcp_stats.in_use'))"
    }
   ]
  },
  {
   "title": "Свободно адресов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sum(seriesByTag('host=$host', 'name=dhcp_stats.free'))"
    }
   ]
  },
  {
   "title": "% использования пула",
   "type": "stat",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(aliasByTags(exclude(exclude(seriesByTag('host=$host', 'name=dhcp_stats.percent_full', 'scope_id=~${score_id:regex}'), 'total'), 'Total'), '_name'), 20)"
    }
   ]
  },
  {
   "title": "Адреса",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(sum(seriesByTag('host=$host', 'name=dhcp_stats.in_use')), 'Использовано', false)"
    },
    {
     "target": "alias(sum(seriesByTag('host=$host', 'name=~dhcp_stats.(free|in_use)')), 'Всего', false)"
    }
   ]
  }
 ]
}