{
 "title": "DHCP",
 "description": "Ответственный: Альбещенко М.Н. (АЦОД)",
 "tags": [ "telegraf" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "query": "tag_values(contur)" },
   {
    "name": "dhcp_cluster",
    "query": "tag_values(dhcp_cluster, contur=$contur)"
   },
   {
    "name": "host",
    "query": "tag_values(host, dhcp_cluster=$dhcp_cluster)"
   },
   {
    "name": "pool",
    "label": "pool(после - маска)",
    "query": "tag_values(location, dhcp_cluster=$dhcp_cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Статус", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Статус сервисов",
   "type": "stat",
   "description": "Если статус ОК - все сервисы запущены",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "maxSeries(keepLastValue(seriesByTag('name=systemd_units.active_code', 'contur=${contur:regex}', 'dhcp_cluster=$dhcp_cluster')))"
    }
   ]
  },
  {
   "title": "Статус пулов",
   "type": "stat",
   "description": "Если статус ОК - во всех пулах свободно больше 10 адресов.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "minSeries(seriesByTag('name=dhcp_subnet.free', 'dhcp_cluster=$dhcp_cluster', 'location=~${pool:regex}'))"
    }
   ]
  },
  {
   "title": "Статус кластера",
   "type": "stat",
   "description": "Проверка по логам.\n0 - normal\n1 - communications-interrupted",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "maxSeries(keepLastValue(seriesByTag('name=dhcp_cluster_status', 'dhcp_cluster=$dhcp_cluster')))"
    }
   ]
  },
  {
   "title": "Всего пулов",
   "type": "stat",
   "description": "Всего пулов определено в конфигурации",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "groupByTags(groupByTags(seriesByTag('name=dhcp_subnet.free', 'dhcp_cluster=$dhcp_cluster'), 'last', 'location', 'dhcp_cluster'), 'count', 'dhcp_cluster')"
    }
   ]
  },
  {
   "title": "Всего определено адресов",
   "type": "stat",
   "description": "Всего адресов определено в конфигурации",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=dhcp_summary.defined', 'dhcp_cluster=$dhcp_cluster')"
    }
   ]
  },
  {
   "title": "Всего использовано адресов",
   "type": "stat",
   "description": "Всего использовано адресов",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=dhcp_summary.used', 'dhcp_cluster=$dhcp_cluster')"
    }
   ]
  },
  {
   "title": "Всего свободно адресов",
   "type": "stat",
   "description": "Всего свободно адресов",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=dhcp_summary.free', 'dhcp_cluster=$dhcp_cluster')"
    }
   ]
  },
  {
   "title": "Пулы подробно",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pools Stats",
     "type": "stat",
     "description": "Занятость пула в процентах.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(groupByTags(divideSeriesLists(seriesByTag('name=dhcp_subnet.used', 'contur=${contur:regex}', 'dhcp_cluster=${dhcp_cluster:regex}', 'location=~${pool:regex}'), seriesByTag('name=dhcp_subnet.defined', 'contur=${contur:regex}', 'dhcp_cluster=${dhcp_cluster:regex}', 'location=~${pool:regex}')), 'last', 'location'), 'location'), '(.*)-(.*)', '\\1/\\2')"
      }
     ]
    },
    {
     "title": "Свободно адресов по пулам",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "target": "groupByTags(seriesByTag('name=dhcp_subnet.free', 'dhcp_cluster=$dhcp_cluster', 'location=~${pool:regex}'), 'last', 'location')"
      }
     ]
    },
    {
     "title": "Определено адресов по пулам",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(groupByTags(seriesByTag('name=dhcp_subnet.defined', 'dhcp_cluster=$dhcp_cluster', 'location=~${pool:regex}'), 'last', 'location'), 'location'), '(.*)-(.*)', '\\1/\\2')"
      }
     ]
    },
    {
     "title": "Использовано адресов по пулам",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(groupByTags(seriesByTag('name=dhcp_subnet.used', 'dhcp_cluster=$dhcp_cluster', 'location=~${pool:regex}'), 'last', 'location'), 'location'), '(.*)-(.*)', '\\1/\\2')"
      }
     ]
    },
    {
     "title": "Свободно адресов по пулам",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(groupByTags(seriesByTag('name=dhcp_subnet.free', 'dhcp_cluster=$dhcp_cluster', 'location=~${pool:regex}'), 'last', 'location'), 'location'), '(.*)-(.*)', '\\1/\\2')"
      }
     ]
    }
   ]
  },
  {
   "title": "Системные метрики",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('cpu=cpu-total', 'name=~system.cpu.usage_(user|softirq|nice|iowait|system|steal|irq)', 'host=~${host:regex}'), 'host', 'name')"
      }
     ]
    },
    {
     "title": "LA ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=~system.system.load', 'host=~${host:regex}'), 'host', 'name')"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=~system.mem.(used|available)_percent', 'host=~${host:regex}'), 'host', 'name')"
      }
     ]
    },
    {
     "title": "Net Drops/Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=~system.net.(drop|err)_(in|out)', 'host=~${host:regex}'), 'host', 'name')"
      }
     ]
    }
   ]
  }
 ]
}