{
 "title": "docker",
 "description": "Ответственный: Конюхов М.В. (Эксплуатация)",
 "tags": [
  "docker",
  "telegraf",
  "system"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "tag_values(engine_host,contur=prod)"
   },
   {
    "name": "container",
    "query": "tag_values(container_name,engine_host=$server)"
   }
  ]
 },
 "panels": [
  {
   "title": "Количество контейнеров",
   "type": "stat",
   "description": "Отображает состояния docker контейнеров на сервере и показывает статистику по ним. \nВсего, На паузе, Запущены, Остановлены",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=~docker.n_containers.*', 'engine_host=$server'), 'name'), 'docker.n_containers_', ''), 'docker.n_containers', 'total')"
    }
   ]
  },
  {
   "title": "Memory total",
   "type": "stat",
   "description": "Отображает кол-во памяти возможно к использованию docker'ом. Чаще всего равно памяти сервера. См \n>> docker info",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=docker.memory_total', 'engine_host=$server'), 'name')"
    }
   ]
  },
  {
   "title": "Goroutins number",
   "type": "graph",
   "description": "Отображает кол-во потоков, используемых для Go runtime. Планировщик горутин (Goroutine scheduler) является перехватывающим задачи (work-stealing) планировщиком. Основная задача планировщика состоит в том, чтобы сопоставить каждую G (код, который мы хотим выполнить) с M (где его выполнять) и P (права и ресурсы для выполнения). См\n>> docker info | grep Goroutines",
   "gridPos": { "h": 4, "w": 12, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=docker.n_goroutines', 'engine_host=$server'), 'name')"
    }
   ]
  },
  {
   "title": "tmp table",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Отображает сводную таблицу по состоянию docker контейнеров на сервере. Показывает название контейнера, его PID на сервере и время с запуска",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 4 },
   "targets": [
    {
     "target": "aliasByTags(scale(seriesByTag('name=~docker_container_status.started_at', 'engine_host=$server', 'container_name=~${container:regex}'), 0.000001), 'container_name', 'name')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=docker_container_status.pid', 'engine_host=$server', 'container_name=~${container:regex}'), 'container_name', 'name')"
    }
   ]
  },
  {
   "title": "Container CPU Usage %",
   "type": "graph",
   "description": "Отображает CPU Time, которое потребляет выбранный контейнер в процентах. В простых числах 1 ядро CPU = 100% нагрузка, таким образом контейнер может потреблять более 100% CPU, а максимальное число, если оно не задано в настройках docker, равно 100*кол-во ядер.",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(seriesByTag('name=docker_container_cpu.usage_percent', 'engine_host=$server', 'container_name=~${container:regex}'), 'container_name'))"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "description": "Отображает использование CPU, которое потребляет выбранный контейнер в герцах.",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 4 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(perSecond(aliasByTags(seriesByTag('name=~docker_container_cpu.usage_in_.*mode', 'engine_host=$server', 'container_name=~${container:regex}'), 'container_name', 'name')), 0, -1), 'usage_in_', '')"
    }
   ]
  },
  {
   "title": "Container Memory Usage %",
   "type": "graph",
   "description": "Отображает потребление выделенной контейнеру памяти. Считается как отношение Mem Usage к Mem Limit. Стоит понимать, что Mem Limit может быть ограничен и не может превышеть Memory Total на сервере. См\n>> docker stats",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(seriesByTag('name=docker_container_mem.usage_percent', 'engine_host=$server', 'container_name=~${container:regex}'), 'container_name'))"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "description": "Отображает потребление выделенной контейнеру памяти в байтах. См\n>> docker stats",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(seriesByTag('name=docker_container_mem.limit', 'engine_host=$server', 'container_name=~${container:regex}'), 'container_name', 'name'))"
    },
    {
     "target": "sortByMaxima(aliasByTags(seriesByTag('name=docker_container_mem.usage', 'engine_host=$server', 'container_name=~${container:regex}'), 'container_name', 'name'))"
    }
   ]
  },
  {
   "title": "Container Throttling",
   "type": "graph",
   "description": "Показывает прерывание тактов CPU при работе выбранного контейнера. Обычно тротлинг говорит о нехватке ресурсов, возросшей нагрузке или некорректно выставленных лимитах. Подробнее про него лучше читать в интернете.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=~docker_container_cpu.throttling_throttled_.*', 'engine_host=$server', 'container_name=~${container:regex}'), 'container_name', 'name'), 'docker_container_cpu.throttling_throttled_', '')"
    }
   ]
  },
  {
   "title": "Container Block device write / s",
   "type": "graph",
   "description": "Отображает кол-во байт, отправленных на запись на диск контейнером. Актуально у тех контейнеров, которые используют разделы. Накладывается функция perSecond (может некорректно считать на периодих от 7 дней)\nСм BLOCK I/O\n>> docker stats",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~docker_container_blkio.io_service_bytes_recursive_write', 'engine_host=$server', 'container_name=~${container:regex}')), 'container_name')"
    }
   ]
  },
  {
   "title": "Container Block device read / s",
   "type": "graph",
   "description": "Отображает кол-во байт, полученных на чтение на диск контейнером. Актуально у тех контейнеров, которые используют разделы. Накладывается функция perSecond (может некорректно считать на периодих от 7 дней)\nСм BLOCK I/O\n>> docker stats",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~docker_container_blkio.io_service_bytes_recursive_read', 'engine_host=$server', 'container_name=~${container:regex}')), 'container_name')"
    }
   ]
  },
  {
   "title": "Container Network packets ratio",
   "type": "graph",
   "description": "Отображает кол-во полученных (RX) and отправленных (TX) пакетов в секунду по сетевому интерфейсу контейнера. Накладывается функция perSecond (может некорректно считать на периодих от 7 дней)",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~docker_container_net..x_packets', 'engine_host=$server', 'container_name=~${container:regex}')), 'container_name', 'name')"
    }
   ]
  },
  {
   "title": "Container Network Usage / s",
   "type": "graph",
   "description": "Отображает кол-во полученных (RX) and отправленных (TX) байт по сетевому интерфейсу контейнера. Накладывается функция perSecond (может некорректно считать на периодих от 7 дней)",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~docker_container_net..x_bytes', 'engine_host=$server', 'container_name=~${container:regex}')), 'container_name', 'name')"
    }
   ]
  },
  {
   "title": "Container Healthy Failing Streaks",
   "type": "graph",
   "description": "Отображает счетчик кол-ва ошибок в Health check , если такой функционал используется. В случае, если контейнер уходит в состояние unhealth, счетчик обычно вырастает. См docker_container_health https://github.com/influxdata/telegraf/tree/master/plugins/inputs/docker",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~docker_container_health.*', 'engine_host=$server', 'container_name=~${container:regex}'), 'container_name', 'name')"
    }
   ]
  }
 ]
}