{
 "title": "dpc-netbox-reporter",
 "description": "Ответственный: Добровольский А.И. (Интеграция и автоматизация)",
 "tags": [ "telegraf" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "contur",
    "query": "tag_values(contur,servertype=dpc-netbox-reporter)"
   },
   {
    "name": "host",
    "query": "tag_values(host,contur=$contur,servertype=dpc-netbox-reporter)"
   }
  ]
 },
 "panels": [
  {
   "title": "dpc-netbox-reporter - errors",
   "type": "graph",
   "description": "Количество различных ошибок на различным компонентах сервиса. No data означает что нет ошибок.",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(transformNull(seriesByTag('service=dpc-netbox-reporter'), 0), 'name'), 'log_level_', '')"
    }
   ]
  },
  {
   "title": "REDIS - глубина очередей",
   "type": "graph",
   "description": "в очередях появляются задания для робота и результат его работы",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(aliasByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=redis.len_queue'), 'name'), 'Очередь заданий')"
    },
    {
     "target": "alias(aliasByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=redis.len_result'), 'name'), 'Очередь отчетов')"
    }
   ]
  },
  {
   "title": "REDIS - keys",
   "type": "graph",
   "description": "Ключей в БД",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(aliasByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=redis.keys', 'database=db1'), 'name', 'database'), 'db1 - Справочники')"
    },
    {
     "target": "alias(aliasByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=redis.keys', 'database=db0'), 'name', 'database'), 'db0 - Очереди')"
    }
   ]
  },
  {
   "title": "REDIS - command's",
   "type": "gauge",
   "description": "Количество команд, обрабатываемых в секунду",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=~${contur:regex}', 'service=redis', 'name=redis.instantaneous_ops_per_sec', 'host=~${host:regex}'), 'name')"
    }
   ]
  },
  {
   "title": "REDIS - total command's",
   "type": "gauge",
   "description": "Общее количество команд, обработанных сервером",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "perSecond(aliasByTags(seriesByTag('contur=~${contur:regex}', 'service=redis', 'name=redis.total_commands_processed', 'host=~${host:regex}'), 'name'))"
    }
   ]
  },
  {
   "title": "Docker - container uptime",
   "type": "table",
   "description": "время обновления",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByTags(groupByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=docker_container_status.uptime_ns'), 'last', 'com.docker.swarm.service.name'), 'com.docker.swarm.service.name'), 'netbox-reporter_', ''), true, false)"
    }
   ]
  },
  {
   "title": "Docker - память по контейнерам",
   "type": "stat",
   "description": "память по контейнерам",
   "gridPos": { "h": 3, "w": 7, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=docker.memory_total'), 'last', 'com.docker.swarm.service.name'), 'name')"
    },
    {
     "target": "aliasSub(aliasByTags(groupByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=docker_container_mem.limit'), 'last', 'com.docker.swarm.service.name'), 'com.docker.swarm.service.name', 1), 'netbox-reporter_', '')"
    }
   ]
  },
  {
   "title": "REDIS - cmd calls",
   "type": "graph",
   "description": "Количество различных вызовов",
   "gridPos": { "h": 12, "w": 8, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=redis.calls')), 'command')"
    }
   ]
  },
  {
   "type": "gauge",
   "description": "память по контейнерам",
   "gridPos": { "h": 3, "w": 7, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(asPercent(groupByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=docker_container_mem.usage'), 'last', 'com.docker.swarm.service.name'), #B), 'com.docker.swarm.service.name', 1), 'netbox-reporter_', '')",
     "targetFull": "aliasSub(aliasByTags(asPercent(groupByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=docker_container_mem.usage'), 'last', 'com.docker.swarm.service.name'), aliasSub(aliasByTags(groupByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=docker_container_mem.limit'), 'last', 'com.docker.swarm.service.name'), 'com.docker.swarm.service.name', 1), 'netbox-reporter_', '')), 'com.docker.swarm.service.name', 1), 'netbox-reporter_', '')"
    }
   ]
  },
  {
   "title": "Docker - количество контейнеров",
   "type": "table",
   "description": "количество контейнеров на сервере",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "aliasByMetric(aliasSub(aliasSub(seriesByTag('name=~docker.n_containers.*', 'contur=~${contur:regex}', 'host=~${host:regex}'), 'docker.n_containers_', ''), 'docker.n_containers', 'total'))"
    }
   ]
  },
  {
   "title": "Linux - место на дисках",
   "type": "bargauge",
   "description": "% занятого места",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=system.disk.used_percent'), 'path'), '-', '/')"
    }
   ]
  },
  {
   "title": "Linux - использование CPU",
   "type": "graph",
   "description": "% использования ЦПУ",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "exclude(exclude(aliasByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=~system.cpu.*', 'cpu=cpu-total'), 'name'), 'idle'), 'active')"
    }
   ]
  },
  {
   "title": "REDIS - использование памяти",
   "type": "graph",
   "description": "Использование памяти",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=~redis.used_memory.*'), 'name'), '.used_memory', '')"
    }
   ]
  },
  {
   "title": "Docker - использование cpu",
   "type": "graph",
   "description": "% использования процессора",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "substr(aliasSub(aliasByTags(groupByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=docker_container_cpu.usage_percent'), 'last', 'com.docker.swarm.service.name'), 'com.docker.swarm.service.name', 1), 'netbox-reporter_', ''), 0, 1)"
    }
   ]
  },
  {
   "title": "REDIS - client's",
   "type": "graph",
   "description": "Количество различных клиентов\nblocked_clients: Number of clients pending on a blocking call (BLPOP, BRPOP, BRPOPLPUSH, BLMOVE, BZPOPMIN, BZPOPMAX)\n",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=redis.blocked_clients'), 1)"
    },
    {
     "target": "aliasByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=redis.clients'), 1)"
    },
    {
     "target": "aliasByTags(perSecond(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=redis.rejected_connections')), 1)"
    }
   ]
  },
  {
   "title": "Linux - сеть",
   "type": "graph",
   "description": "tcp_close - Начальное состояние узла. Фактически фиктивное\n\ntcp_lisnet - Сервер ожидает запросов установления соединения от клиента\n\ntcp_syn-sent - Клиент отправил запрос серверу на установление соединения и ожидает ответа\n\ntcp_syn-received - Сервер получил запрос на соединение, отправил ответный запрос и ожидает подтверждения\n\ntcp_established - Соединение установлено, идёт передача данных\n\ntcp_fin_wait1 - Одна из сторон (назовём её узел-1) завершает соединение, отправив сегмент с флагом FIN\n\ntcp_close_wait - Другая сторона (узел-2) переходит в это состояние, отправив, в свою очередь сегмент ACK и продолжает одностороннюю передачу\n\ntcp_fin_wait2 - Узел-1 получает ACK, продолжает чтение и ждёт получения сегмента с флагом FIN\n\ntcp_last_ack - Узел-2 заканчивает передачу и отправляет сегмент с флагом FIN\n\ntcp_time_wait - Узел-1 получил сегмент с флагом FIN, отправил сегмент с флагом ACK и ждёт 2*MSL секунд, перед окончательным закрытием соединения\n\ntcp_closing - Обе стороны инициировали закрытие соединения одновременно: после отправки сегмента с флагом FIN узел-1 также получает сегмент FIN, отправляет ACK и находится в ожидании сегмента ACK (подтверждения на свой запрос о разъединении)",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(seriesByTag('contur=~${contur:regex}', 'host=~${host:regex}', 'name=~system.netstat.tcp_*'), 'name'))"
    }
   ]
  }
 ]
}