{
 "title": "DPC-Logs",
 "description": "Мониторинг состояния Logstash по проекту ад-аудита. Ответственный: Пантелеев А.С. (АЦОД)",
 "tags": [ "telegraf" ],
 "time": { "from": "now-1h", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "clustername",
    "label": "cluster opensearch ",
    "query": "tag_values(clustername,contur=$contur)"
   }
  ]
 },
 "panels": [
  {
   "title": "Keepalived service status",
   "type": "stat",
   "description": "Green - Master\nLight Green - Backup",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(keepLastValue(seriesByTag('servertype=dpc-logs', 'name=exec_keepalived.data_state'), 5), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Logstash service status",
   "type": "stat",
   "description": "Статус сервиса Logstash",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('servertype=dpc-logs', 'name=http.status'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Opensearch cluster status",
   "type": "stat",
   "description": "Статус кластера в целом. \n- OK - все ок\n- Yellow - есть часть нод с проблемами, но в целом индекс полностью доступен, т.к. зарезервирован\n- Red - кластер частично или полностью недоступен, часть или все данные невозможно запросить.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highestMax(seriesByTag('clustername=prod-dns-log', 'name=service.elastic.status_code', 'servertype=elasticsearch', 'index!=~.*'), 1)"
    }
   ]
  },
  {
   "title": "Dashboards service status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('clustername=prod-dpc-logs', 'service=kibana', 'name=~kibana.status_code'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Total incoming events",
   "type": "bargauge",
   "description": "Количество входящих ивентов",
   "gridPos": { "h": 3, "w": 7, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('servertype=dpc-logs', 'name=http.events_in')), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  { "title": "Logstash", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Logstash Open File Descriptors",
   "type": "gauge",
   "description": "Количество открытых файловых дескрипторов на сервере",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('servertype=dpc-logs', 'name=http.process_open_file_descriptors'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Logstash process Uptime",
   "type": "stat",
   "description": "Время работы процесса Logstash на сервере",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('servertype=dpc-logs', 'name=http.jvm_uptime_in_millis'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "JVM threads count per node",
   "type": "stat",
   "description": "Колимчество потоков JVM",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('servertype=dpc-logs', 'name=http.jvm_threads_count'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Logstash Disk Usage",
   "type": "bargauge",
   "description": "место на диске",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasSub(aliasByTags(seriesByTag('servertype=dpc-logs', 'host=~dpc-logs-logstash.*', 'name=system.disk.used_percent'), 'host', 'path'), '-', '/'), 'dpc/logs/log', 'dpc-logs-log'), '.unix.tensor.ru.', ': ')"
    }
   ]
  },
  {
   "title": "Logstash event queue",
   "type": "timeseries",
   "description": "Количество событий в очереди Logstash",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('servertype=dpc-logs', 'name=http.queue_events_count'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Logstash queue size",
   "type": "timeseries",
   "description": "Размер очереди Logstash в байтах",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('servertype=dpc-logs', 'name=http.pipelines_main_queue_capacity_queue_size_in_bytes'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Logstash queue size pct",
   "type": "timeseries",
   "description": "Размер очереди Logstash в процентах",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByTags(asPercent(seriesByTag('servertype=dpc-logs', 'name=http.pipelines_main_queue_capacity_queue_size_in_bytes'), #B), 'host')",
     "targetFull": "aliasByTags(asPercent(seriesByTag('servertype=dpc-logs', 'name=http.pipelines_main_queue_capacity_queue_size_in_bytes'), aliasSub(seriesByTag('servertype=dpc-logs', 'name=http.pipelines_main_queue_capacity_max_queue_size_in_bytes'), '.unix.tensor.ru', '')), 'host')"
    }
   ]
  },
  {
   "title": "Logstash CPU Usage",
   "type": "timeseries",
   "description": "загрузка CPU",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "exclude(aliasSub(aliasByTags(seriesByTag('servertype=dpc-logs', 'name=~system.cpu.usage_*', 'cpu=cpu-total', 'host=~dpc-logs-logstash*'), 'host', 'name'), '.unix.tensor.ru.system.cpu.usage', ''), 'idle')"
    }
   ]
  },
  {
   "title": "Logstash Mem free",
   "type": "timeseries",
   "description": "memory free",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('servertype=dpc-logs', 'name=system.mem.available_percent', 'host=~dpc-logs-logstash*'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Logstash Bytes received",
   "type": "timeseries",
   "description": "Получено байт/с",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('servertype=dpc-logs', 'name=system.net.bytes_recv', 'host=~dpc-logs-logstash*')), 'host', 'interface'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Logstash Bytes sent",
   "type": "timeseries",
   "description": "отправлено байт/с",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('servertype=dpc-logs', 'name=system.net.bytes_sent', 'host=~dpc-logs-logstash*')), 'host', 'interface'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Logstash incoming events",
   "type": "timeseries",
   "description": "Количество входящих ивентов",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('servertype=dpc-logs', 'name=http.events_in')), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Logstash outcoming events",
   "type": "timeseries",
   "description": "Количество исходящих ивентов",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('contur=~${contur:regex}', 'servertype=dpc-logs', 'name=http.events_out')), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Old GC count",
   "type": "timeseries",
   "description": "Количество проходов Old GC",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(derivative(seriesByTag('servertype=dpc-logs', 'name=http.jvm_gc_collectors_old_collection_count')), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Old GC duration",
   "type": "timeseries",
   "description": "Время работы GC",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(derivative(seriesByTag('servertype=dpc-logs', 'name=http.jvm_gc_collectors_old_collection_time_in_millis')), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Young GC count",
   "type": "timeseries",
   "description": "Количество проходов Young GC",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(derivative(seriesByTag('servertype=dpc-logs', 'name=http.jvm_gc_collectors_young_collection_count')), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Young GC duration",
   "type": "timeseries",
   "description": "Время работы Young GC",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(derivative(seriesByTag('servertype=dpc-logs', 'name=http.jvm_gc_collectors_young_collection_time_in_millis')), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  { "title": "Keepalived", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Keepalived priorities",
   "type": "stat",
   "description": "Приоритеты по серверам",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('servertype=dpc-logs', 'name=exec_keepalived.data_base_priority'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Time from last status transition",
   "type": "stat",
   "description": "Время прошедшее с последней смены статуса на сервере",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(keepLastValue(scale(seriesByTag('servertype=dpc-logs', 'name=exec_keepalived.data_last_transition'), 1000, 0), 5), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Keepalived Errors",
   "type": "timeseries",
   "description": "Количество ошибок",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(groupByTags(seriesByTag('servertype=dpc-logs', 'name=~exec_keepalived.stats_(addr_list_err|advert_interval_err|auth_failure|packet_len_err|invalid_authtype|ip_ttl_err|invalid_type_rcvd)'), 'sum', 'host', 'name'), 'host', 'name'), '.unix.tensor.ru', ''), '.exec_keepalived.stats', '')"
    }
   ]
  },
  {
   "title": "LB CPU Usage",
   "type": "timeseries",
   "description": "загрузка CPU",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(exclude(aliasByTags(seriesByTag('servertype=dpc-logs', 'name=~system.cpu.usage_.*', 'host=~dpc-logs-lb.*'), 'host', 'name'), 'idle'), '.unix.tensor.ru.system.cpu.usage', '')"
    }
   ]
  },
  {
   "title": "LB Mem free",
   "type": "timeseries",
   "description": "memory free",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('servertype=dpc-logs', 'name=system.mem.available_percent', 'host=~dpc-logs-lb.*'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Incoming bytes real server and virtual server",
   "type": "timeseries",
   "description": "Трафик, принятый сервером",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('servertype=dpc-logs', 'name=~ipvs_(real|virtual)_server.bytes_in')), 'host', 'address', 'name'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Number of incoming packets",
   "type": "timeseries",
   "description": "Количество входящих пакетов",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('servertype=dpc-logs', 'name=~ipvs_(real|virtual)_server.pkts_in')), 'host', 'address', 'name'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Number of connections",
   "type": "timeseries",
   "description": "Количество коннектов",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('servertype=dpc-logs', 'name=~ipvs_(real|virtual)_server.connections')), 'host', 'address', 'name'), '.unix.tensor.ru', '')"
    }
   ]
  },
  { "title": "Opensearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "CPU Node",
   "type": "timeseries",
   "description": "Общее использование CPU нодой кластера.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('clustername=~${clustername:regex}', 'name=service.elastic.cpu_percent'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Использование памяти нодой кластера. В байтах.\nmax_value = 8589934592 b (8 gb)",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=~${clustername:regex}', 'name=service.elastic.mem_used_in_bytes'), 'host')"
    }
   ]
  },
  {
   "title": "FS Free",
   "type": "bargauge",
   "description": "Доступно байт от выделенных. Стоит понимать, что выделено может быть с общей хранилки и лимит фиктивный.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=~${clustername:regex}', 'name=service.elastic.total_free_in_bytes'), 'host')"
    }
   ]
  },
  {
   "title": "Indexing Rate /per sec",
   "type": "timeseries",
   "description": "Рейнтин индексирования - кол-во обрабатываемых индексов в секунду. В секунду.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('clustername=~${clustername:regex}', 'name=service.elastic.indexing_index_total')), 'host')"
    }
   ]
  },
  {
   "title": "Indices Search",
   "type": "graph",
   "description": "Время задержки поиска по индексу в секунду.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('clustername=~${clustername:regex}', 'name=service.elastic.search_query_time_in_millis')), 'host', 'name'), 'perSecond\\(', ''), 0, -1)"
    },
    {
     "target": "aliasByNode(aliasSub(aliasByTags(perSecond(seriesByTag('clustername=~${clustername:regex}', 'name=service.elastic.search_query_total')), 'host', 'name'), 'perSecond\\(', ''), 0, -1)"
    }
   ]
  },
  { "title": "Opensearch-dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Response time avg",
   "type": "timeseries",
   "description": "Response time avg ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=${clustername:regex}', 'service=kibana', 'name=kibana.response_time_avg_ms'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Requests per sec",
   "type": "timeseries",
   "description": "Requests per sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('clustername=${clustername:regex}', 'service=kibana', 'name=~kibana.requests_per_sec'), 'host', 'name')"
    }
   ]
  }
 ]
}