{
 "title": "Gitlab - dobrotest",
 "description": "Ответственный: Добровольский А.И. (АЦОД)",
 "tags": [ "telegraf" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "contur",
    "query": "tag_values(contur,servertype=gitlab-omnibus)"
   },
   {
    "name": "gitlabinstance",
    "query": "tag_values(gitlabinstance,servertype=gitlab-omnibus,contur=$contur)"
   }
  ]
 },
 "panels": [
  { "title": "Service status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service status over time",
   "type": "gauge",
   "description": "Процент времени безотказной работы службы",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(transformNull(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=up'), 3), 0), 'job'), true, false)"
    }
   ]
  },
  {
   "title": "Gitlab Version",
   "type": "stat",
   "description": "Gitlab версия",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('gitlabinstance=$gitlabinstance', 'job=gitaly', 'name=gitlab_build_info', 'version=~*'), 'version')"
    }
   ]
  },
  {
   "title": "Service status",
   "type": "timeseries",
   "description": "Доступность измеряет долю процессов компонента в службе, которые в настоящее время работоспособны и могут обрабатывать запросы. Чем ближе к 100%, тем лучше.",
   "gridPos": { "h": 10, "w": 8, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(transformNull(keepLastValue(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'name=gitlab_sli:job:availability:ratio'), 5), 0), '^.*job=', ''), '\\&.*', '')"
    }
   ]
  },
  {
   "title": "Service saturation",
   "type": "timeseries",
   "description": "\nНасыщенность — это мера наиболее насыщенного компонента услуги. Ниже - лучше.",
   "gridPos": { "h": 10, "w": 8, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'name=gitlab_sli:gitlab_service_saturation:ratio'), 'gitlab_sli:gitlab_service_saturation:ratio\\?component=', ''), '\\&.*', '')"
    }
   ]
  },
  {
   "title": "Service RPS",
   "type": "timeseries",
   "description": "Скорость работы — это сумма всех запросов, обрабатываемых для всех компонентов в рамках этой службы. Обратите внимание, что один запрос пользователя может привести к запросам к нескольким компонентам. Выше занято.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "movingAverage(alias(sum(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'name=gitlab_sli:code_method_route:workhorse_http_request_count:rate1m')), 'gitlab-workhorse'), '1min')"
    }
   ]
  },
  {
   "title": "Git Version",
   "type": "stat",
   "description": "Git версия",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'job=gitaly', 'name=gitlab_build_info', 'git_version=~*'), 'git_version')"
    }
   ]
  },
  {
   "title": "Docker container uptime",
   "type": "stat",
   "description": "Время работы контейнера Gitlbab",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "keepLastValue(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'name=docker_container_status.uptime_ns', 'container_name=gitlab'), 5)"
    }
   ]
  },
  { "title": "Host system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Docker - memory limit",
   "type": "stat",
   "description": "Память по контейнерам",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'name=docker.memory_total'), 'name')"
    },
    {
     "target": "aliasByTags(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'name=docker_container_mem.limit'), 'container_name')"
    }
   ]
  },
  {
   "title": "Docker Memory Usage",
   "type": "timeseries",
   "description": "Использование памяти по контейнерам",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(asPercent(keepLastValue(seriesByTag('name=docker_container_mem.usage', 'servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance'), 2), #B), 'mem usage')",
     "targetFull": "alias(asPercent(keepLastValue(seriesByTag('name=docker_container_mem.usage', 'servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance'), 2), keepLastValue(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'name=docker_container_mem.limit'), 2)), 'mem usage')"
    }
   ]
  },
  {
   "title": "Docker - cpu usage",
   "type": "timeseries",
   "description": "% использования процессора",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByTags(keepLastValue(seriesByTag('name=docker_container_cpu.usage_percent', 'servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance'), 5), 'container_name')"
    }
   ]
  },
  {
   "title": "Linux - Disk usage",
   "type": "bargauge",
   "description": "% занятого места",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=system.disk.used_percent', 'servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance'), 'path'), '-', '/')"
    }
   ]
  },
  {
   "title": "Linux - CPU Usage",
   "type": "timeseries",
   "description": "% использования ЦПУ",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "exclude(exclude(aliasByTags(keepLastValue(seriesByTag('name=~system.cpu.*', 'cpu=cpu-total', 'servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance'), 3), 'name'), 'idle'), 'active')"
    }
   ]
  },
  {
   "title": "Linux - network",
   "type": "timeseries",
   "description": "tcp_close - Начальное состояние узла. Фактически фиктивное\n\ntcp_lisnet - Сервер ожидает запросов установления соединения от клиента\n\ntcp_syn-sent - Клиент отправил запрос серверу на установление соединения и ожидает ответа\n\ntcp_syn-received - Сервер получил запрос на соединение, отправил ответный запрос и ожидает подтверждения\n\ntcp_established - Соединение установлено, идёт передача данных\n\ntcp_fin_wait1 - Одна из сторон (назовём её узел-1) завершает соединение, отправив сегмент с флагом FIN\n\ntcp_close_wait - Другая сторона (узел-2) переходит в это состояние, отправив, в свою очередь сегмент ACK и продолжает одностороннюю передачу\n\ntcp_fin_wait2 - Узел-1 получает ACK, продолжает чтение и ждёт получения сегмента с флагом FIN\n\ntcp_last_ack - Узел-2 заканчивает передачу и отправляет сегмент с флагом FIN\n\ntcp_time_wait - Узел-1 получил сегмент с флагом FIN, отправил сегмент с флагом ACK и ждёт 2*MSL секунд, перед окончательным закрытием соединения\n\ntcp_closing - Обе стороны инициировали закрытие соединения одновременно: после отправки сегмента с флагом FIN узел-1 также получает сегмент FIN, отправляет ACK и находится в ожидании сегмента ACK (подтверждения на свой запрос о разъединении)",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByMetric(aliasByTags(seriesByTag('name=~system.netstat.tcp_*', 'servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance'), 'name'))"
    }
   ]
  },
  {
   "title": "Node exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Available Memory",
     "type": "gauge",
     "description": "Доступная память узла",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "target": "divideSeries(keepLastValue(alias(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'job=node', 'name=node_memory_MemAvailable_bytes'), 'Available'), 2), #B)",
       "targetFull": "divideSeries(keepLastValue(alias(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'job=node', 'name=node_memory_MemAvailable_bytes'), 'Available'), 2), keepLastValue(alias(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'job=node', 'name=node_memory_MemTotal_bytes'), 'Total'), 2))"
      }
     ]
    },
    {
     "title": "Node Available Memory",
     "type": "timeseries",
     "description": "Доступная память узла",
     "gridPos": { "h": 6, "w": 6, "x": 4, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "target": "alias(keepLastValue(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'job=node', 'name=node_memory_MemAvailable_bytes'), 3), 'Available')"
      },
      {
       "target": "alias(keepLastValue(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'job=node', 'name=node_memory_MemTotal_bytes'), 3), 'Total')"
      }
     ]
    },
    {
     "title": "Process resident memory",
     "type": "timeseries",
     "description": "Резидентная память процесса",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "aliasByTags(keepLastValue(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'name=process_resident_memory_bytes'), 3), 'job')"
      }
     ]
    },
    {
     "title": "Process virtual memory",
     "type": "timeseries",
     "description": "Виртуальная память процесса",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "aliasByTags(keepLastValue(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'name=process_virtual_memory_bytes'), 3), 'job')"
      }
     ]
    },
    {
     "title": "Node CPU Load",
     "type": "gauge",
     "description": "Загрузка процессора узла",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "target": "offset(scale(keepLastValue(perSecond(avg(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'job=node', 'name=node_cpu_seconds_total', 'mode=idle'))), 2), -1, 0), 1)"
      }
     ]
    },
    {
     "title": "Node CPU Load",
     "type": "timeseries",
     "description": "Загрузка процессора узла",
     "gridPos": { "h": 7, "w": 6, "x": 4, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "target": "alias(offset(scale(perSecond(avg(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'job=node', 'name=node_cpu_seconds_total', 'mode=idle'))), -1), 1), 'cpu_load')"
      }
     ]
    },
    {
     "title": "Node Context switches",
     "type": "timeseries",
     "description": "Контекстные переключатели узла",
     "gridPos": { "h": 7, "w": 6, "x": 10, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "perSecond(keepLastValue(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'name=node_context_switches_total'), 3))"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "timeseries",
     "description": "Процессы",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "alias(keepLastValue(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'name=node_procs_running'), 2), 'Processes in runnable state')"
      },
      {
       "target": "alias(keepLastValue(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'name=node_procs_blocked'), 2), 'Processes blocked waiting for I/O to complete')"
      }
     ]
    },
    {
     "title": "Node Memory",
     "type": "timeseries",
     "description": "Память узла",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(keepLastValue(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'job=node', 'name=~node_memory_(MemTotal|MemAvailable|MemFree|Buffers|Chached)_bytes'), 3), 'name'), '(node_memory_|Mem|_bytes)', '')"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis Start",
     "type": "stat",
     "description": "Время запуска Redis",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "refCount": -1,
       "target": "scale(aliasByTags(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'job=redis', 'name=redis_start_time_seconds'), 'pg_postmaster_start_time_seconds'), 1000)"
      }
     ]
    },
    {
     "title": "Redis Items",
     "type": "timeseries",
     "description": "Элементы Redis",
     "gridPos": { "h": 12, "w": 7, "x": 3, "y": 55 },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'job=redis', 'name=redis_db_keys'), 'db')"
      }
     ]
    },
    {
     "title": "Redis Commands Calls",
     "type": "timeseries",
     "description": "Вызовы команд Redis",
     "gridPos": { "h": 12, "w": 7, "x": 10, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'job=redis', 'name=redis_commands_total', 'cmd=~*')), 'cmd')"
      }
     ]
    },
    {
     "title": "Redis Commands Executed",
     "type": "timeseries",
     "description": "Выполненные команды Redis",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "target": "perSecond(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'job=redis', 'name=redis_commands_processed_total'))"
      }
     ]
    },
    {
     "title": "Redis Clients",
     "type": "stat",
     "description": "Клиенты Redis",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "target": "keepLastValue(seriesByTag('servertype=gitlab-omnibus', 'gitlabinstance=$gitlabinstance', 'job=redis', 'name=redis_connected_clients'), 5)"
      }
     ]
    },
    {
     "title": "Redis Memory Usage",
     "type": "timeseries",
     "description": "Использование памяти Redis",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "alias(seriesByTag('gitlabinstance=$gitlabinstance', 'name=redis_memory_used_bytes'), 'UsedBytes')"
      },
      {
       "target": "alias(seriesByTag('gitlabinstance=$gitlabinstance', 'name=redis_config_maxmemory'), 'ConfigMax')"
      }
     ]
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postmaster Start",
     "type": "stat",
     "description": "Время работы Postmaster",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "refCount": -1,
       "target": "scale(aliasByTags(seriesByTag('gitlabinstance=$gitlabinstance', 'name=pg_postmaster_start_time_seconds'), 'pg_postmaster_start_time_seconds'), 1000)"
      }
     ]
    },
    {
     "title": "PG Connections",
     "type": "gauge",
     "description": "PG Соединения",
     "gridPos": { "h": 5, "w": 4, "x": 3, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "target": "divideSeries(keepLastValue(sum(seriesByTag('gitlabinstance=$gitlabinstance', 'name=pg_stat_activity_count')), 5), #B)",
       "targetFull": "divideSeries(keepLastValue(sum(seriesByTag('gitlabinstance=$gitlabinstance', 'name=pg_stat_activity_count')), 5), keepLastValue(sum(seriesByTag('gitlabinstance=$gitlabinstance', 'name=pg_settings_max_connections')), 5))"
      }
     ]
    },
    {
     "title": "PG Active Connections",
     "type": "gauge",
     "description": "PG Активные соединения",
     "gridPos": { "h": 5, "w": 4, "x": 7, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "target": "divideSeries(keepLastValue(sum(seriesByTag('gitlabinstance=$gitlabinstance', 'name=pg_stat_activity_count', 'state=active')), 5), #B)",
       "targetFull": "divideSeries(keepLastValue(sum(seriesByTag('gitlabinstance=$gitlabinstance', 'name=pg_stat_activity_count', 'state=active')), 5), keepLastValue(sum(seriesByTag('gitlabinstance=$gitlabinstance', 'name=pg_settings_max_connections')), 5))"
      }
     ]
    },
    {
     "title": "Postgres locks",
     "type": "timeseries",
     "description": "Блокировки Postgres",
     "gridPos": { "h": 8, "w": 5, "x": 11, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('gitlabinstance=$gitlabinstance', 'name=pg_locks_count', 'datname=gitlabhq_production'), 'mode')"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "description": "Транзакции",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(perSecond(seriesByTag('gitlabinstance=$gitlabinstance', 'name=pg_stat_database_xact_commit', 'datname=gitlabhq_production')), 'commit')"
      },
      {
       "target": "alias(perSecond(seriesByTag('gitlabinstance=$gitlabinstance', 'name=pg_stat_database_xact_rollback', 'datname=gitlabhq_production')), 'rollback')"
      }
     ]
    },
    {
     "title": "Postgres slow queries",
     "type": "timeseries",
     "description": "Медленные запросы в Postgres",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('gitlabinstance=$gitlabinstance', 'name=pg_slow_queries'), 'name')"
      }
     ]
    },
    {
     "type": "table",
     "description": "Статистика подключений",
     "gridPos": { "h": 3, "w": 8, "x": 3, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(keepLastValue(sum(seriesByTag('gitlabinstance=$gitlabinstance', 'name=pg_stat_activity_count', 'state=active')), 5), 'Active', false)"
      },
      {
       "target": "alias(keepLastValue(sum(seriesByTag('gitlabinstance=$gitlabinstance', 'name=pg_stat_activity_count')), 5), 'Total', false)"
      },
      {
       "target": "alias(keepLastValue(sum(seriesByTag('gitlabinstance=$gitlabinstance', 'name=pg_settings_max_connections')), 5), 'Max', false)"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nginx Latency",
     "type": "timeseries",
     "description": "Задержка Nginx",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "divideSeries(sum(perSecond(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=nginx_vts_upstream_request_seconds_total'), 3))), #B)",
       "targetFull": "divideSeries(sum(perSecond(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=nginx_vts_upstream_request_seconds_total'), 3))), sum(perSecond(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=nginx_vts_upstream_requests_total'), 3))))"
      }
     ]
    },
    {
     "title": "Nginx Server - Incoming/outgoing bytes (direction.host)",
     "type": "timeseries",
     "description": "Сервер Nginx - Входящие/исходящие байты (direction.host)",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(movingMax(perSecond(seriesByTag('gitlabinstance=$gitlabinstance', 'name=nginx_vts_server_bytes_total')), '1min'), 'direction', 'host'), '\\.-', '.*')"
      }
     ]
    },
    {
     "title": "Nginx Upstream - Incoming/outgoing bytes (direction.backend.upstream)",
     "type": "timeseries",
     "description": "Nginx Upstream - Входящие/исходящие байты (direction.backend.upstream)",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "target": "aliasByTags(movingMax(perSecond(seriesByTag('gitlabinstance=$gitlabinstance', 'name=nginx_vts_upstream_bytes_total')), '1min'), 'direction', 'backend', 'upstream')"
      }
     ]
    },
    {
     "title": "Nginx Server - Requests by HTTP Code (code.host)",
     "type": "timeseries",
     "description": "Сервер Nginx - Запросы по коду HTTP (code.host)",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(movingMax(perSecond(seriesByTag('gitlabinstance=$gitlabinstance', 'name=nginx_vts_server_requests_total')), '1min'), 'code', 'host'), '\\.-', '.*')"
      }
     ]
    },
    {
     "title": "Nginx Upstream - Requests by HTTP Code (code.backend.upstream)",
     "type": "timeseries",
     "description": "Nginx Upstream - Запросы по коду HTTP (code.backend.upstream)",
     "gridPos": { "h": 12, "w": 13, "x": 11, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "target": "aliasByTags(movingMax(perSecond(seriesByTag('gitlabinstance=$gitlabinstance', 'name=nginx_vts_upstream_requests_total')), '1min'), 'code', 'backend', 'upstream')"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus WAL Corruptions",
     "type": "stat",
     "description": "Prometheus WAL повреждения ",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "target": "keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=prometheus_tsdb_wal_corruptions_total'), 3)"
      }
     ]
    },
    {
     "title": "Prometheus Scrape Duration",
     "type": "timeseries",
     "description": "Prometheus Scrape Duration",
     "gridPos": { "h": 11, "w": 8, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "aliasByTags(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=scrape_duration_seconds'), 2), 'job')"
      }
     ]
    },
    {
     "title": "Prometheus Query Durations",
     "type": "timeseries",
     "description": "Длительность запросов Prometheus ",
     "gridPos": { "h": 11, "w": 10, "x": 14, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "aliasByTags(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=prometheus_engine_query_duration_seconds', 'quantile=0.99'), 2), 'slice')"
      }
     ]
    },
    {
     "title": "Prometheus Memory Profile",
     "type": "timeseries",
     "description": "Описание памяти Prometheus",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "alias(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=process_resident_memory_bytes', 'job=prometheus'), 2), 'resident memory')"
      },
      {
       "target": "alias(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=process_virtual_memory_bytes', 'job=prometheus'), 2), 'virtual memory')"
      }
     ]
    }
   ]
  },
  {
   "title": "Rails App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ruby Memory per Worker",
     "type": "timeseries",
     "description": "Память Ruby на один Worker",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "alias(avg(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=ruby_process_resident_memory_bytes'), 3)), 'Average')"
      },
      {
       "target": "alias(maxSeries(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=ruby_process_resident_memory_bytes'), 3)), 'Max')"
      },
      {
       "target": "alias(minSeries(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=ruby_process_resident_memory_bytes'), 3)), 'Min')"
      }
     ]
    },
    {
     "title": "Queued Requests",
     "type": "timeseries",
     "description": "Запросы в очереди",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(sum(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=puma_queued_connections'), 3)), 'Queued Requests')"
      }
     ]
    },
    {
     "title": "Ruby CPU per Worker",
     "type": "timeseries",
     "description": "Ruby CPU на один Worker",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(perSecond(avg(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=ruby_process_cpu_seconds_total'), 3))), 'Average')"
      },
      {
       "target": "alias(perSecond(maxSeries(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=ruby_process_cpu_seconds_total'), 3))), 'Max')"
      },
      {
       "target": "alias(perSecond(minSeries(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=ruby_process_cpu_seconds_total'), 3))), 'Min')"
      }
     ]
    },
    {
     "title": "Active Requests",
     "type": "timeseries",
     "description": "Активные запросы",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(sum(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=puma_active_connections'), 3)), 'Average')"
      },
      {
       "target": "alias(sum(keepLastValue(seriesByTag('gitlabinstance=$gitlabinstance', 'name=puma_max_threads'), 3)), 'Available Workers')"
      }
     ]
    }
   ]
  }
 ]
}