{
 "title": "GPU",
 "description": "Автоматическое  распознавание  изображений  документов. Ответственный: Карпов С.В. (Эксплуатация)",
 "tags": [
  "telegraf",
  "GPU",
  "nvidia",
  "system"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "host",
    "query": "tag_values(host,servertype=gpu)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory utilization, %",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'host=~${host:regex}', 'name=nvidia_smi.utilization_memory'), 'host')"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'host=~${host:regex}', 'name=nvidia_smi.memory_used'), 'host')"
    }
   ]
  },
  {
   "title": "Memory clocking",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'host=~${host:regex}', 'name=nvidia_smi.clocks_current_memory'), 'host')"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'host=~${host:regex}', 'name=nvidia_smi.utilization_gpu'), 'host')"
    }
   ]
  },
  {
   "title": "GPU Clocking",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'host=~${host:regex}', 'name=nvidia_smi.clocks_current_graphics'), 'host')"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'host=~${host:regex}', 'name=nvidia_smi.temperature_gpu'), 'host')"
    }
   ]
  },
  {
   "title": "PCI-E Link",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'host=~${host:regex}', 'name=nvidia_smi.pcie_link_width_current'), 'host')"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'host=~${host:regex}', 'name=nvidia_smi.fan_speed'), 'host')"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'host=~${host:regex}', 'name=nvidia_smi.power_draw'), 'host')"
    }
   ]
  },
  {
   "title": "Encoder utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'host=~${host:regex}', 'name=nvidia_smi.utilization_encoder'), 'host')"
    }
   ]
  },
  {
   "title": "Decoder utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=gpu', 'host=~${host:regex}', 'name=nvidia_smi.utilization_decoder'), 'host')"
    }
   ]
  }
 ]
}