{
 "title": "Harbor",
 "description": "Экран для мониторинга состояния Registry для контейнеров Harbor Ответственный: -",
 "tags": [
  "harbor",
  "service",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "contur",
    "query": "tag_values(contur,servertype=harbor)"
   },
   {
    "name": "registry",
    "query": "tag_values(registry,contur=$contur,servertype=harbor)"
   },
   {
    "name": "project",
    "query": "tag_values(project_name,registry=$registry)"
   }
  ]
 },
 "panels": [
  {
   "title": "Состояние системы и мастер хоста",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Статус харбора",
   "type": "stat",
   "description": "Общий статус харбора",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.harbor_health')"
    },
    {}
   ]
  },
  {
   "title": "Статус отдельных систем харбора",
   "type": "stat",
   "description": "Статус отдельных систем\n0 = Down, 1 = Up",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('servertype=harbor','contur=~$contur', 'registry=~${registry:regex}', 'name=prometheus.harbor_up'), 'component'), true, false)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Аптайм процесса харбора",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.process_start_time_seconds'), 1000)"
    }
   ]
  },
  {
   "title": "Harbor version",
   "type": "stat",
   "description": "Текущая версия Harbor",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.harbor_system_info'), 'harbor_version')"
    }
   ]
  },
  {
   "title": "CPU seconds total",
   "type": "stat",
   "description": "Пользовательское + системное время работы ЦПУ",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.process_cpu_seconds_total')"
    }
   ]
  },
  {
   "title": "Количество возвращаемых HTTP кодов",
   "type": "gauge",
   "description": "Статистика по http кодам. Показывает текущие счетчики по 200, 500 и 503 кодам",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.promhttp_metric_handler_requests_total'), 'code'), true)"
    }
   ]
  },
  {
   "title": "Количество проектов",
   "type": "stat",
   "description": "Количество проектов в Registry",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.harbor_project_total', 'public=true'), 'Public')"
    },
    {
     "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.harbor_project_total', 'public=false'), 'Private')"
    }
   ]
  },
  {
   "title": "Total quota usage",
   "type": "stat",
   "description": "Использованная квота по всем проектам",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aggregate(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.harbor_project_quota_usage_byte'), 'sum')"
    }
   ]
  },
  {
   "title": "Virtual memory usage",
   "type": "graph",
   "description": "Использование виртуальной памяти + квота (-1 - отсутствие квоты)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.process_virtual_memory_bytes'), 'Virtual memory usage')"
    },
    {
     "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.process_virtual_memory_max_bytes'), 'Virtual memory quota')"
    }
   ]
  },
  {
   "title": "RSS Memory usage",
   "type": "graph",
   "description": "Использование резидентной памяти на виртуальном сервере",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.process_resident_memory_bytes'), 'Resident memory usage')"
    }
   ]
  },
  {
   "title": "Task queue size",
   "type": "graph",
   "description": "Общее количество задач каждого типа в очереди",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.harbor_task_queue_size', 'type=GARBAGE_COLLECTION'), 'Garbage collection')"
    },
    {
     "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.harbor_task_queue_size', 'type=REPLICATION'), 'Replication')"
    },
    {
     "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.harbor_task_queue_size', 'type=SCHEDULER'), 'Scheduler')"
    }
   ]
  },
  {
   "title": "Task queue latency",
   "type": "graph",
   "description": "Время постановки задачи в очередь для каждого типа",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.harbor_task_queue_latency', 'type=GARBAGE_COLLECTION'), 'Garbage collection')"
    },
    {
     "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.harbor_task_queue_size', 'type=REPLICATION'), 'Replication')"
    },
    {
     "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.harbor_task_queue_latency', 'type=SCHEDULER'), 'Scheduler')"
    }
   ]
  },
  {
   "title": "Информация по проектам registry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Квоты по проекту ${project:regex}",
     "type": "timeseries",
     "description": "Объем, занятый файлами проекта и квота. -1 — отсутствие квоты",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.harbor_project_quota_usage_byte', 'project_name=$project'), '$project: Quota used')"
      },
      {
       "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.harbor_project_quota_byte', 'project_name=$project'), '$project, Quota')"
      }
     ]
    },
    {
     "title": "Статистика по проекту ${project:regex}",
     "type": "stat",
     "description": "Количество репозиториев в проекте, количество артифактов в проекте, количество пуллов артифактов",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'project_name=$project', 'name=prometheus.harbor_project_repo_total'), 'Repo Total')"
      },
      {
       "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'project_name=$project', 'name=prometheus.harbor_project_artifact_total'), 'Artifact total')"
      },
      {
       "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'project_name=$project', 'name=prometheus.harbor_artifact_pulled'), 'Artifact Pulled')"
      }
     ]
    }
   ]
  },
  {
   "title": "Актуальность баз Trivy DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Trivy database update time",
     "type": "stat",
     "description": "Время последнего обновления базы Trivy",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=file.Type'), 'UpdatedAt')"
      }
     ]
    },
    {
     "title": "Next Trivy database update time",
     "type": "stat",
     "description": "Время следующего обновления базы Trivy",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=file.Type'), 'NextUpdate')"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage collector info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open file descriptors",
     "type": "graph",
     "description": "Количество открытых файловых дескрипторов. \nВерхний предел — 1048576.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.process_open_fds'), 'Open File Descriptors')"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "description": "Количество активных параллельных потоков языка GO. \n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.go_goroutines'), 'Goroutines')"
      }
     ]
    },
    {
     "title": "Memstats",
     "type": "graph",
     "description": "Количество выделенной памяти. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.go_memstats_alloc_bytes'), 'Go allocated bytes')"
      },
      {
       "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.go_memstats_buck_hash_sys_bytes'), 'Profiling bucket hash table')"
      },
      {
       "target": "alias(seriesByTag('contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.go_memstats_gc_sys_bytes'), 'GC metadata')"
      },
      {
       "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.go_memstats_heap_alloc_bytes'), 'Heap allocated bytes')"
      },
      {
       "target": "alias(seriesByTag('contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.go_memstats_mcache_inuse_bytes'), 'mcache in use bytes')"
      },
      {
       "target": "alias(seriesByTag('contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.go_memstats_mspan_inuse_bytes'), 'mspan in use bytes')"
      },
      {
       "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.go_memstats_stack_inuse_bytes'), 'stack in use')"
      },
      {
       "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.go_memstats_sys_bytes'), 'obtained from system')"
      }
     ]
    },
    {
     "title": "Heap bytes before GC",
     "type": "graph",
     "description": "Количество байт в куче до ближайшего прохода сборщика мусора",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.go_memstats_next_gc_bytes'), 'Heap bytes before next GC')"
      }
     ]
    },
    {
     "title": "GC duration",
     "type": "graph",
     "description": "Длительность прохода сборщика мусора ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "target": "alias(derivative(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.go_gc_duration_seconds_sum')), 'GC duration')"
      }
     ]
    },
    {
     "title": "Last GC",
     "type": "timeseries",
     "description": "Время последнего прохода сборщика мусора",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "targets": [
      {
       "target": "alias(derivative(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.go_memstats_last_gc_time_seconds')), 'last GC')"
      }
     ]
    },
    {
     "title": "GC duration quantiles",
     "type": "graph",
     "description": "Длительность прохода сборщика мусора по квантилям",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(seriesByTag('servertype=harbor', 'contur=~${contur:regex}', 'registry=~${registry:regex}', 'name=prometheus.go_gc_duration_seconds'), 'quantile'), false)"
      }
     ]
    }
   ]
  }
 ]
}