{
 "title": "Hyper-V Cluster",
 "description": "Ответственный: Добровольский А.И. (АЦОД)",
 "tags": [
  "telegraf",
  "hyper-v",
  "Virtualization",
  "service"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "tag_values(cluster, servertype=hyper-v)"
   }
  ]
 },
 "panels": [
  {
   "title": "VMs OK",
   "type": "table-old",
   "description": "Количество виртуалок в нормальном состоянии",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Hyper-V_Virtual_Machine_Health_Summary', 'name=hyperv_vmhealth.Health_Ok', 'host=~*'), 'host')"
    },
    {
     "target": "alias(sumSeries(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Hyper-V_Virtual_Machine_Health_Summary', 'name=hyperv_vmhealth.Health_Ok'), 'host')), '_Total')"
    }
   ]
  },
  {
   "title": "VMs Critical",
   "type": "bargauge",
   "description": "Количество виртуалок в критическом состоянии",
   "gridPos": { "h": 8, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Hyper-V_Virtual_Machine_Health_Summary', 'name=hyperv_vmhealth.Health_Critical', 'host=~*'), 'host')"
    },
    {
     "target": "alias(sumSeries(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Hyper-V_Virtual_Machine_Health_Summary', 'name=hyperv_vmhealth.Health_Critical'), 'host')), '_Total')"
    }
   ]
  },
  {
   "title": "Mem Provisioned",
   "type": "bargauge",
   "description": "Выделено оперативной памяти",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(sumSeriesWithWildcards(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Hyper-V_Dynamic_Memory_VM', 'host=~*', 'name=hyperv_vmmemory.Physical_Memory'), 'host'), -1), '(sumSeriesWithWildcards\\(|\\))', '')"
    },
    {
     "target": "alias(sum(aliasSub(sumSeriesWithWildcards(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Hyper-V_Dynamic_Memory_VM', 'host=~*', 'name=hyperv_vmmemory.Physical_Memory'), 'host'), -1), '(sumSeriesWithWildcards\\(|\\))', '')), '_Total')"
    }
   ]
  },
  {
   "title": "CPU Provisioned",
   "type": "bargauge",
   "description": "Выделено ЦП",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Hyper-V_Hypervisor_Partition', 'name=hyperv_vmcpustatistics.Virtual_Processors', 'host=~*', 'instance=~_Total'), 'host'), true, false)"
    },
    {
     "target": "alias(sumSeries(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Hyper-V_Hypervisor_Partition', 'name=hyperv_vmcpustatistics.Virtual_Processors', 'instance=~_Total'), 'host')), '_Total')"
    }
   ]
  },
  {
   "title": "VM Memory Pressure",
   "type": "graph",
   "description": "Нехватка оперативной памяти на виртуалках",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(sortByName(aliasByTags(removeBelowValue(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'host=~*', 'objectname=Hyper-V_Dynamic_Memory_VM', 'name=hyperv_vmmemory.Current_Pressure', 'instance=~*'), 50), 'instance'), true, false), '(removeBelowValue\\(|\\)|, 50)', '')"
    }
   ]
  },
  {
   "title": "VM Virtual CPU Usage (Avg)",
   "type": "graph",
   "description": "Среднее количество ЦП на виртуалке",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByName(groupByNode(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'host=~*', 'objectname=Hyper-V_Hypervisor_Virtual_Processor', 'interval=10s', 'name=hyperv_hypervisorvp.Percent_Guest_Run_Time'), 'instance'), 0, 'avg'), true, false)"
    }
   ]
  },
  {
   "title": "VStorage Free Space",
   "type": "table-old",
   "description": "Свободное пространство на виртуальном хранилище",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "aliasSub(sortByName(aliasSub(averageSeriesWithWildcards(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'host=~*', 'objectname=dsbrief.json', 'name=ClusterCSVSpace.Free', 'Path=~*'), 'Path'), -1), '(averageSeriesWithWildcards\\(|\\))', ''), true, true), 'C:ClusterStorage', '')"
    }
   ]
  },
  {
   "title": "VStorage Free Space  Pct",
   "type": "table-old",
   "description": "Свободное пространство на виртуальном хранилище, в процентах",
   "gridPos": { "h": 9, "w": 6, "x": 5, "y": 8 },
   "targets": [
    {
     "target": "aliasSub(aliasSub(averageSeriesWithWildcards(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'host=~*', 'objectname=dsbrief.json', 'name=ClusterCSVSpace.FreePct', 'Path=~*'), 'Path'), -1), '(averageSeriesWithWildcards\\(|\\))', ''), 'C:ClusterStorage', '')"
    }
   ]
  },
  {
   "title": "Virtual CPU Hypervisor",
   "type": "graph",
   "description": "lost performance",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Hyper-V_Hypervisor_Virtual_Processor', 'instance=_Total', 'host=~*', 'name=hyperv_hypervisorvp.Percent_Hypervisor_Run_Time'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "description": "Свободно памяти",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Memory', 'host=~*', 'name=hyperv_hostmem.Available_Bytes'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Logical CPU",
   "type": "graph",
   "description": "Количество логических ЦП",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Hyper-V_Hypervisor_Logical_Processor', 'name=hyperv_hypervisorlp.Percent_Total_Run_Time', 'instance=_Total', 'host=~*'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Real Cores Avg",
   "type": "graph",
   "description": "Загрузка ядер ЦПУ, среднее (нагрузка на процессор, создаваемая виртуальными машинами + нагрузка на процессор, от самого гипервизора на обслуживание виртуальных машин)",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Hyper-V_Hypervisor_Logical_Processor', 'name=hyperv_hypervisorlp.Percent_Total_Run_Time', 'instance=~.*[0,2,4,6,8]$', 'host=~*'), 'avg', 'host'), 'host'), true, false)"
    },
    {
     "target": "alias(groupByTags(#A, 'avg', 'host'), '_Total')",
     "targetFull": "alias(groupByTags(sortByName(aliasByTags(groupByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Hyper-V_Hypervisor_Logical_Processor', 'name=hyperv_hypervisorlp.Percent_Total_Run_Time', 'instance=~.*[0,2,4,6,8]$', 'host=~*'), 'avg', 'host'), 'host'), true, false), 'avg', 'host'), '_Total')"
    }
   ]
  },
  {
   "title": "Virtual CPU",
   "type": "graph",
   "description": "Загрузка Виртуальных ЦП (нагрузка на процессор, создаваемая виртуальными машинами + нагрузка на процессор, от самого гипервизора на обслуживание виртуальных машин)",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Hyper-V_Hypervisor_Virtual_Processor', 'instance=_Total', 'host=~*', 'name=hyperv_hypervisorvp.Percent_Total_Run_Time'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "VMQ Available",
   "type": "table-old",
   "description": "Доступность сетевой очереди (Virtual Machine Queue)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'host=~*', 'objectname=vmq.json', 'name=HostNetworkVMQ.freevmq'), 'host')"
    }
   ]
  },
  {
   "title": "Virtual Switch",
   "type": "graph",
   "description": "Загрузка виртуального свича",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByNode(aliasSub(aliasSub(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Hyper-V_Virtual_Switch', 'host=~*', 'name=~hyperv_vswitch.Bytes_(Sent|Received)_persec'), 'host', 'instance', 'name'), 'Bytes_Received_persec', 'Received_Bps'), 'Bytes_Sent_persec', 'Sent_Bps'), 0, 1, -1), true, false)"
    }
   ]
  },
  {
   "title": "Vstorage Latency",
   "type": "graph",
   "description": "Задержка на виртуальном хранилище",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByNode(aliasSub(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Cluster_CSV_File_System', 'host=~*', 'name=~hyperv_clusterfilesystem.(Read|Write)_Latency'), 'host', 'instance', 'name'), '_Latency', ''), 0, 1, -1), true, false)"
    }
   ]
  },
  {
   "title": "Vstorage Average Latency",
   "type": "graph",
   "description": "Задержка на виртуальном хранилище, среднее",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasSub(averageSeriesWithWildcards(aliasByNode(aliasSub(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Cluster_CSV_File_System', 'host=~*', 'name=~hyperv_clusterfilesystem.(Read|Write)_Latency'), 'host', 'instance', 'name'), '_Latency', ''), 0, 1, -1), 0), '(averageSeriesWithWildcards\\(|\\))', ''), true, false)"
    }
   ]
  },
  {
   "title": "Vstorage Queue",
   "type": "graph",
   "description": "Очередь на виртуальном хранилище",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByNode(aliasSub(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Cluster_CSV_File_System', 'host=~*', 'name=~hyperv_clusterfilesystem.(Read|Write)_Queue_Length'), 'host', 'instance', 'name'), '_Length', ''), 0, 1, -1), true, false)"
    }
   ]
  },
  {
   "title": "Vstorage Average IOps",
   "type": "graph",
   "description": "Кол-во операций ввода\\вывода на виртуальном хранилище, среднее",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasSub(sumSeriesWithWildcards(aliasByNode(aliasSub(aliasByTags(seriesByTag('cluster=$cluster', 'contur=${contur:regex}', 'objectname=Cluster_CSV_File_System', 'host=~*', 'name=~hyperv_clusterfilesystem.(Writes_persec|Reads_persec|Metadata_IO_persec)'), 'host', 'instance', 'name'), '(s_persec|_IO_persec)', '_iops'), 0, 1, -1), 0), '(sumSeriesWithWildcards\\(|\\))', ''), true, false)"
    }
   ]
  },
  {
   "title": "Virtual DIsk IO",
   "type": "graph",
   "description": "Виртуальный диск ввод\\вывод (операции чтения+записи)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(exclude(seriesByTag('objectname=Hyper-V_Virtual_Storage_Device', 'name=~hyperv_vmvhdstats.(Read|Write)_Operations_persec', 'instance!=~--*', 'cluster=$cluster'), 'Idle|Total'), 'instance', 'name'), '(_Operations_persec|.hyperv_vmvhdstats)', '')"
    }
   ]
  }
 ]
}