{
 "title": "Hyper-V Datastores",
 "description": "Ответственный: Добровольский А.И. (АЦОД)",
 "tags": [
  "telegraf",
  "hyper-v",
  "Virtualization",
  "service"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "contur", "query": "prod,test" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "tag_values(cluster, servertype=hyper-v)"
   },
   {
    "name": "datastore",
    "label": "datastore",
    "query": "tag_values(Path, servertype=hyper-v, cluster=${cluster:regex}, objectname=dsbrief.json, name=ClusterCSVSpace.FreePct)"
   }
  ]
 },
 "panels": [
  {
   "title": "Free Space Pct",
   "type": "graph",
   "description": "Свободное пространство на виртуальном хранилище, в процентах",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(avg(seriesByTag('cluster=$cluster', 'servertype=hyper-v', 'objectname=dsbrief.json', 'name=ClusterCSVSpace.FreePct', 'Path=C:ClusterStorage$datastore')), 'Pct Free')"
    },
    {
     "target": "alias(avg(seriesByTag('cluster=$cluster', 'servertype=hyper-v', 'objectname=dsbrief.json', 'name=ClusterCSVSpace.Free', 'Path=C:ClusterStorage$datastore')), 'Free Mb')"
    },
    {
     "target": "alias(avg(seriesByTag('cluster=$cluster', 'servertype=hyper-v', 'objectname=dsbrief.json', 'name=ClusterCSVSpace.Size', 'Path=C:ClusterStorage$datastore')), 'Size Mb')"
    }
   ]
  },
  {
   "title": "Used Space",
   "type": "graph",
   "description": "Занятое пространство",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(offset(avg(seriesByTag('cluster=$cluster', 'servertype=hyper-v', 'objectname=dsbrief.json', 'name=ClusterCSVSpace.FreePct', 'Path=C:ClusterStorage$datastore')), -100), -1), 'Pct Used')"
    },
    {
     "target": "alias(avg(seriesByTag('cluster=$cluster', 'servertype=hyper-v', 'objectname=dsbrief.json', 'name=ClusterCSVSpace.Used', 'Path=C:ClusterStorage$datastore')), 'Used Mb')"
    },
    {
     "target": "alias(avg(seriesByTag('cluster=$cluster', 'servertype=hyper-v', 'objectname=dsbrief.json', 'name=ClusterCSVSpace.Size', 'Path=C:ClusterStorage$datastore')), 'Size Mb')"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "graph",
   "description": "Задержка чтения",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster=$cluster', 'servertype=hyper-v', 'objectname=Cluster_CSV_File_System', 'name=hyperv_clusterfilesystem.Read_Latency', 'host=~*', 'instance=$datastore'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "description": "Задержка записи",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster=$cluster', 'servertype=hyper-v', 'objectname=Cluster_CSV_File_System', 'name=hyperv_clusterfilesystem.IO_Write_Latency', 'host=~*', 'instance=$datastore'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Read Queue",
   "type": "graph",
   "description": "Очередь чтения",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster=$cluster', 'servertype=hyper-v', 'objectname=Cluster_CSV_File_System', 'name=hyperv_clusterfilesystem.Read_Queue_Length', 'host=~*', 'instance=$datastore'), 'host'), true, false)"
    }
   ]
  },
  {
   "title": "Write Queue",
   "type": "graph",
   "description": "Очередь записи",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('cluster=$cluster', 'servertype=hyper-v', 'objectname=Cluster_CSV_File_System', 'name=hyperv_clusterfilesystem.Write_Queue_Length', 'host=~*', 'instance=$datastore'), 'host'), true, false)"
    }
   ]
  }
 ]
}