{
 "title": "Hyper-V Host telegraf",
 "description": "Ответственный: Добровольский А.И. (АЦОД)",
 "tags": [
  "service",
  "telegraf",
  "hyper-v",
  "Virtualization"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "query": "prod,test" },
   {
    "name": "cluster",
    "query": "tag_values(cluster, servertype=hyper-v)"
   },
   {
    "name": "host",
    "query": "tag_values(host, servertype=hyper-v, cluster=${cluster:regex})"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Время работы с момента прошлой загрузки хоста",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=hyperv_systemstatistics.System_Up_Time')"
    }
   ]
  },
  {
   "title": "VM Virtual Processors",
   "type": "graph",
   "description": "Количество виртуальных ЦП",
   "gridPos": { "h": 9, "w": 4, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByTags(seriesByTag('host=$host', 'objectname=Hyper-V_Hypervisor_Partition', 'name=hyperv_vmcpustatistics.Virtual_Processors'), 'instance'), ':HvPt', ''), true, false)"
    }
   ]
  },
  {
   "title": "Guest visible memory",
   "type": "graph",
   "description": "Выделенная память для виртуалки",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'objectname=Hyper-V_Dynamic_Memory_VM', 'name=hyperv_vmmemory.Guest_Visible_Physical_Memory'), 'instance')"
    },
    {
     "target": "sortByName(alias(sumSeries(aliasByTags(seriesByTag('host=$host', 'objectname=Hyper-V_Dynamic_Memory_VM', 'name=hyperv_vmmemory.Guest_Visible_Physical_Memory'), 'instance')), '_Total'), true, false)"
    }
   ]
  },
  {
   "title": "Guest Memory Pressure %",
   "type": "graph",
   "description": "Нехватка гостевой памяти, в процентах",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "%" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'objectname=Hyper-V_Dynamic_Memory_VM', 'name=hyperv_vmmemory.Current_Pressure'), 'instance')"
    }
   ]
  },
  {
   "title": "Virtual processor Average",
   "type": "graph",
   "description": "Среднее количество виртуальных ЦП",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(averageSeriesWithWildcards(aliasSub(exclude(aliasByTags(seriesByTag('host=$host', 'objectname=Hyper-V_Hypervisor_Virtual_Processor', 'name=hyperv_hypervisorvp.Percent_Total_Run_Time'), 'instance'), '_Total'), ':Hv_VP_.*', ''), -1), '(averageSeriesWithWildcards\\(|\\))', '')"
    }
   ]
  },
  {
   "title": "VMs OK",
   "type": "stat",
   "description": "Количество виртуалок в нормальном состоянии",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Machine_Health_Summary', 'name=hyperv_vmhealth.Health_Ok')"
    }
   ]
  },
  {
   "title": "VMs Critical",
   "type": "stat",
   "description": "Количество виртуалок в критическом состоянии",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Machine_Health_Summary', 'name=hyperv_vmhealth.Health_Critical')"
    }
   ]
  },
  {
   "title": "Root Virtual processor",
   "type": "graph",
   "description": "Загрузка процессора на хостовой машине",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByTags(seriesByTag('host=$host', 'objectname=Hyper-V_Hypervisor_Root_Virtual_Processor', 'name=hyperv_hypervisorrootvp.Percent_Total_Run_Time'), 'instance'), 'Root_', ''), true, false)"
    }
   ]
  },
  {
   "title": "Logical processor",
   "type": "graph",
   "description": "Нагрузка на процессор в привязке к логическим процессорам (физические ядра процессора или вычислительные потоки)",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(sortByName(aliasByTags(seriesByTag('host=$host', 'objectname=Hyper-V_Hypervisor_Logical_Processor', 'name=hyperv_hypervisorlp.Percent_Total_Run_Time'), 'instance'), true, false), 'Hv_', '')"
    }
   ]
  },
  {
   "title": "Host memory stats",
   "type": "graph",
   "description": "Статистика по памяти хоста",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(seriesByTag('host=$host', 'objectname=Memory', 'name=~hyperv_hostmem.(Available|Cache|Committed|Pool_Nonpaged|Pool_Paged)_Bytes'), 'name', 'name'), -1), '_Bytes', '')"
    }
   ]
  },
  {
   "title": "Host CPU stats",
   "type": "graph",
   "description": "Статистика по ЦП хоста",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=$host', 'objectname=Hyper-V_Hypervisor_Root_Virtual_Processor', 'instance=_Total'), 'objectname', 'name'), '(Hyper-V_Hypervisor_|_Run_Time|Percent_|.hyperv_hypervisorrootvp|_Virtual_Processor)', '')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=$host', 'objectname=Hyper-V_Hypervisor_Logical_Processor', 'instance=_Total', 'name=hyperv_hypervisorlp.Percent_Total_Run_Time'), 'objectname', 'name'), 'Hyper-V_Hypervisor_Logical_Processor.hyperv_hypervisorlp.Percent_Total_Run_Time', 'Logical.Total')"
    },
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('host=$host', 'objectname=Hyper-V_Hypervisor_Virtual_Processor', 'instance=_Total', 'name=~hyperv_hypervisorvp.Percent_(Total|Hypervisor)_Run_Time'), 'objectname', 'name'), 'Hyper-V_Hypervisor_Virtual_Processor.hyperv_hypervisorvp.Percent_', 'Virtual.'), '_Run_Time', '')"
    }
   ]
  },
  {
   "title": "Host Net Queue",
   "type": "graph",
   "description": "Сетевая очередь хоста",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(aliasSub(seriesByTag('host=$host', 'objectname=Network_Interface', 'name=hyperv_hostnetinterface.Output_Queue_Length'), 'Broadcom_OneConnect_00AG542__PCI_Slot_1__Ethernet_NDIS_Miniport_Driver,Broadcom_00AG542', ''), 'instance'), '__PCI_Slot_1__Ethernet_NDIS_Miniport_Driver', '')"
    }
   ]
  },
  {
   "title": "Even logical processor",
   "type": "graph",
   "description": "Загрузка чётных логических процессоров (нагрузка на процессор, создаваемая виртуальными машинами + нагрузка на процессор, от самого гипервизора на обслуживание виртуальных машин)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "aliasSub(sortByName(aliasByTags(seriesByTag('host=$host', 'objectname=Hyper-V_Hypervisor_Logical_Processor', 'name=hyperv_hypervisorlp.Percent_Total_Run_Time', 'instance=~.*[0,2,4,6,8]$'), 'instance'), true, false), 'Hv_', '')"
    },
    {
     "target": "alias(groupByTags(#A, 'avg', 'host'), '_Total')",
     "targetFull": "alias(groupByTags(aliasSub(sortByName(aliasByTags(seriesByTag('host=$host', 'objectname=Hyper-V_Hypervisor_Logical_Processor', 'name=hyperv_hypervisorlp.Percent_Total_Run_Time', 'instance=~.*[0,2,4,6,8]$'), 'instance'), true, false), 'Hv_', ''), 'avg', 'host'), '_Total')"
    }
   ]
  },
  {
   "title": "Cluster CSV Space Usage",
   "type": "graph",
   "description": "Занятое пространство на общих хранилищах кластера",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('host=$host', 'objectname=dsbrief.json', 'name=ClusterCSVSpace.Free', 'Path=~*'), 'Path', 'name'), '.ClusterCSVSpace', ''), 'C:ClusterStorage', '')"
    }
   ]
  },
  {
   "title": "Cluster CSV free space %",
   "type": "graph",
   "description": "Свободное пространство на общих хранилищах кластера, в процентах",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasSub(aliasByTags(seriesByTag('host=$host', 'objectname=dsbrief.json', 'name=ClusterCSVSpace.FreePct', 'Path=~*'), 'Path', 'name'), 'C:ClusterStorage', ''), 0, -1)"
    }
   ]
  },
  {
   "title": "Host storage free space %",
   "type": "bargauge",
   "description": "Свободное пространство на хосте, в процентах",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'objectname=LogicalDisk', 'name=hyperv_hostlogicaldisk.Percent_Free_Space', 'instance!=~(HarddiskVolume*|_Total)'), 'instance')"
    }
   ]
  },
  {
   "title": "Host storage busy, %",
   "type": "graph",
   "description": "Занятое пространство на хосте, в процентах",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=LogicalDisk', 'name=~hyperv_hostlogicaldisk.Percent_Disk_(Read|Write)_Time', 'instance!=~(Harddisk*|_Total)'), 'Idle|Total'), 'instance', 'name'), 0, -1), '(Percent_Disk_|_Time)', '')"
    }
   ]
  },
  {
   "title": "Host storage free space %",
   "type": "graph",
   "description": "Свободное пространство на хосте, в процентах",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'objectname=LogicalDisk', 'name=hyperv_hostlogicaldisk.Free_Megabytes', 'instance!=~(HarddiskVolume*|_Total)'), 'instance')"
    }
   ]
  },
  {
   "title": "Logical Disk Latency",
   "type": "graph",
   "description": "Задержка логического диска",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=LogicalDisk', 'name=~hyperv_hostlogicaldisk.Avg._Disk_sec-(Read|Write)', 'instance!=~HarddiskVolume*'), 'Idle|Total'), 'instance', 'name'), 0, -1), '_Disk_sec-', '')"
    }
   ]
  },
  {
   "title": "Logical Disk IO",
   "type": "graph",
   "description": "Ввод\\вывод логического диска",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=LogicalDisk', 'name=~hyperv_hostlogicaldisk.(Disk_Reads|Disk_Writes|Split_IO)_persec', 'instance!=~HarddiskVolume*'), 'Idle|Total'), 'instance', 'name'), 0, -1), '(Disk_|_persec)', '')"
    }
   ]
  },
  {
   "title": "Logical Disk Throughput",
   "type": "graph",
   "description": "Пропускная способность локального диска",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=LogicalDisk', 'name=~hyperv_hostlogicaldisk.Disk_(Read|Write)_Bytes_persec', 'instance!=~HarddiskVolume*'), 'Idle|Total'), 'instance', 'name'), 0, -1), '(Disk_|_Bytes_persec)', '')"
    }
   ]
  },
  {
   "title": "Logical Disk Queue",
   "type": "graph",
   "description": "Очередь логического диска",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(seriesByTag('host=$host', 'objectname=LogicalDisk', 'name=~hyperv_hostlogicaldisk.Avg._Disk_(Read_Queue|Write_Queue|Queue)_Length', 'instance!=~(HarddiskVolume*|_Total)'), 'instance', 'name'), 0, -1), '(_Disk_|_Length)', '')"
    }
   ]
  },
  {
   "title": "Cluster storage latency",
   "type": "graph",
   "description": "Задержка хранилища кластера",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Cluster_CSV_File_System', 'name=~hyperv_clusterfilesystem.(Read|Write)_Latency'), 'Idle|Total'), 'instance', 'name'), 0, -1), '_Latency','')"
    }
   ]
  },
  {
   "title": "Cluster Storage IO",
   "type": "graph",
   "description": "Ввод\\вывод хранилища кластера",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Cluster_CSV_File_System', 'name=~hyperv_clusterfilesystem.(Writes|Reads|Metadata_IO|Flushes)_persec'), 'Idle|Total'), 'instance', 'name'), 0, -1), '_persec', '')"
    }
   ]
  },
  {
   "title": "Cluster Storage Throughput",
   "type": "graph",
   "description": "Пропускная способность хранилища кластера",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Cluster_CSV_File_System', 'name=~hyperv_clusterfilesystem.(IO|Redirected)_(Write|Read)_Bytes_persec'), 'Idle|Total'), 'instance', 'name'), 0, -1), '_Bytes_persec', '')"
    }
   ]
  },
  {
   "title": "Cluster Storage Queue",
   "type": "graph",
   "description": "Очередь хранилища кластера",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(seriesByTag('host=$host', 'objectname=Cluster_CSV_File_System', 'name=~hyperv_clusterfilesystem.(Read|Write)_Queue_Length'), 'instance', 'name'), 0, -1), '_Length', '')"
    }
   ]
  },
  {
   "title": "Virtual Disk Latency",
   "type": "graph",
   "description": "Задержка виртуального диска",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Storage_Device', 'name=hyperv_vmvhdstats.Latency', 'instance!=~--*'), 'Idle|Total'), 'instance')"
    }
   ]
  },
  {
   "title": "Virtual Disk IO",
   "type": "graph",
   "description": "Ввод\\вывод виртуального диска",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Storage_Device', 'name=~hyperv_vmvhdstats.(Read|Write)_Operations_persec', 'instance!=~--*'), 'Idle|Total'), 'instance', 'name'), '(_Operations_persec|.hyperv_vmvhdstats)', '')"
    }
   ]
  },
  {
   "title": "Virtual Disk Throughput",
   "type": "graph",
   "description": "Пропускная способность виртуального диска",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Storage_Device', 'name=~hyperv_vmvhdstats.(Write|Read)_Bytes_persec', 'instance!=~--*'), 'Idle|Total'), 'instance', 'name'), '(hyperv_vmvhdstats.|_Bytes_persec)', '')"
    }
   ]
  },
  {
   "title": "Virtual Disk Queue",
   "type": "graph",
   "description": "Очередь виртуального диска",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Storage_Device', 'name=~hyperv_vmvhdstats.Queue_Length', 'instance!=~--*'), 'instance')"
    }
   ]
  },
  {
   "title": "Virtual Switch bps",
   "type": "graph",
   "description": "Количество бит\\с виртуального свича",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Switch', 'name=~hyperv_vswitch.Bytes_(Received|Sent)_persec'), 'Idle|Total'), 'instance', 1), 0, -1)"
    }
   ]
  },
  {
   "title": "Virtual Switch Packets",
   "type": "graph",
   "description": "Количество пакетов виртуального свича",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Switch', 'name=~hyperv_vswitch.Dropped_Packets_(Incoming|Outgoing)_persec'), 'Idle|Total'), 'instance', 1), 0, -1), '(Packets_|_persec)', '')"
    },
    {
     "target": "aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Switch', 'name=~hyperv_vswitch.Packets_(Received|Sent)_persec'), 'Idle|Total'), 'instance', 1), 0, -1), '(Packets_|_persec)', '')"
    },
    {
     "target": "aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Switch', 'name=~hyperv_vswitch.(Broadcast|Multicast)_Packets_(Received|Sent)_persec'), 'Idle|Total'), 'instance', 1), 0, -1), '(Packets_|_persec)', '')"
    }
   ]
  },
  {
   "title": "VM Virtual Adapters bps",
   "type": "graph",
   "description": "Количество бит\\с виртуального адаптера ВМ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Network_Adapter', 'instance!=~(Broadcom*)', 'name=~hyperv_netadapters.Bytes_(Received|Sent)_persec', 'instance!=~__*', 'instance!=~vswitch*', 'instance!=~v[0-9]-*'), 'Idle|Total'), 'instance', 'name'), 0, -1), '_.*Bytes_', '_'), '_persec', '')"
    }
   ]
  },
  {
   "title": "VM Virtual Adapters packets",
   "type": "graph",
   "description": "Количество пакетов виртуального адаптера ВМ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Network_Adapter', 'instance!=~(Broadcom*)', 'name=~hyperv_netadapters.Packets_(Received|Sent)_persec', 'instance!=~__*', 'instance!=~vswitch*', 'instance!=~v[0-9]-*'), 'Idle|Total'), 'instance', 1), 0, -1), '_.*Packets_', '.'), '_persec', '')"
    },
    {
     "target": "aliasSub(aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Network_Adapter', 'instance!=~(Broadcom*)', 'name=~hyperv_netadapters.Dropped_Packets_(Incoming|Outgoing)_persec', 'instance!=~__*', 'instance!=~vswitch*', 'instance!=~v[0-9]-*'), 'Idle|Total'), 'instance', 1), 0, -1), '_.*Dropped_', '.Dropped_'), '(Packets_|_persec)', '')"
    }
   ]
  },
  {
   "title": "Host Virtual Adapters bps",
   "type": "graph",
   "description": "Количество бит\\с виртуального адаптера хоста",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Network_Adapter', 'name=~hyperv_netadapters.Bytes_(Received|Sent)_persec', 'instance=~(__*|vswitch*|v[0-9]-*|Broadcom*)'), 'Idle|Total'), 'instance', 1), 0, -1)"
    }
   ]
  },
  {
   "title": "Host Virtual Adapters packets",
   "type": "graph",
   "description": "Количество пакетов виртуального адаптера хоста",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Network_Adapter', 'name=~hyperv_netadapters.Packets_(Received|Sent)_persec', 'instance=~(__*|Broadcom*|v[0-9]-*|vswitch*|vEthernet*|.*_Сетевой|.*_Network)'), 'Idle|Total'), 'instance', 1), 0, -1), '(_Сетевой.*\\.|_Network.*\\.)', ''), 'Packets', '.Packets')"
    },
    {
     "target": "aliasSub(aliasSub(aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Hyper-V_Virtual_Network_Adapter', 'name=~hyperv_netadapters.Dropped_Packets_(Incoming|Outgoing)_persec', 'instance=~(__*|Broadcom*|v[0-9]-*|vswitch*|vEthernet*|.*_Сетевой|.*_Network)'), 'Idle|Total'), 'instance', 1), 0, -1), '(_Сетевой.*\\.|_Network.*\\.)', ''), 'Dropped', '.Dropped')"
    }
   ]
  },
  {
   "title": "Host Adapters bps",
   "type": "graph",
   "description": "Количество бит\\с хоста",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Network_Interface', 'name=~hyperv_hostnetinterface.Bytes_(Received|Sent)_persec'), 'Idle|Total|isatap'), 'instance', 1), 0, -1)"
    }
   ]
  },
  {
   "title": "Host Virtual Adapters packets",
   "type": "graph",
   "description": "Количество пакетов виртуального адаптера хоста",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(exclude(seriesByTag('host=$host', 'objectname=Network_Interface', 'name=~hyperv_hostnetinterface.Packets_(Received|Sent)_persec'), 'Idle|Total|isatap'), 'instance', 1), 0, -1)"
    }
   ]
  }
 ]
}