{
 "title": "IPAM",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "scripts",
  "system"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "tag_values(host,netbox_role=ipam)"
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active IP Count",
   "type": "graph",
   "description": "Количество активных ip-адресов в системе",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=exec_active_ip_count', 'netbox_role=ipam', 'host=${host:regex}'), 'host')"
    }
   ]
  },
  {
   "title": "Mac flap",
   "type": "graph",
   "description": "Количество обнаруженных ip-адресов, у которых регулярно меняется mac-адрес",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasSub(aliasByTags(seriesByTag('name=exec_unapproved_ip', 'netbox_role=ipam', 'host=~${host:regex}'), 'host', 'ip'), '_', '.'), '-(\\d+)', '/\\1'), '-', '.')"
    },
    {
     "target": "alias(sumSeries(seriesByTag('name=exec_unapproved_ip', 'netbox_role=ipam', 'host=~${host:regex}')), 'Sum')"
    }
   ]
  },
  {
   "title": "Max approve time expired for Prefixes",
   "type": "graph",
   "description": "Количество неподтвержденных подсетей в системе",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(aliasSub(aliasSub(aliasSub(seriesByTag('name=exec_unapproved_prefix', 'netbox_role=ipam', 'host=~${host:regex}'), '_', '.'), '-(\\d+)$', '/\\1'), '-', '.'), 'prefix')"
    },
    {
     "target": "alias(sumSeries(seriesByTag('name=exec_unapproved_prefix', 'netbox_role=ipam', 'host=~${host:regex}')), 'Sum')"
    }
   ]
  },
  {
   "title": "Max approve time expired for VRFs",
   "type": "graph",
   "description": "Количество неподтвержденных vrf в системе",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=exec_unapproved_vrf', 'netbox_role=ipam', 'host=~${host:regex}'), 'host', 'vrf'), '-([a-z]+)', '.\\1')"
    },
    {
     "target": "alias(sumSeries(seriesByTag('name=exec_unapproved_vrf', 'netbox_role=ipam', 'host=~${host:regex}')), 'Sum')"
    }
   ]
  },
  {
   "title": "Discovery job errors",
   "type": "graph",
   "description": "Ошибки скриптов автообнаружения объектов в системе",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=exec_job_result', 'netbox_role=ipam', 'host=~${host:regex}'), 'host', 'task'), '-', '.')"
    }
   ]
  },
  {
   "title": "Device with discovery errors",
   "type": "graph",
   "description": "Устройства, опрос которых завершился с ошибкой",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=exec_error_device', 'netbox_role=ipam', 'host=~${host:regex}'), 'device')"
    },
    {
     "target": "alias(sumSeries(seriesByTag('name=exec_error_device', 'netbox_role=ipam', 'host=~${host:regex}')), 'Sum')"
    }
   ]
  },
  {
   "title": "Discovery job duration exceeded",
   "type": "graph",
   "description": "Время последнего успешного запуска скрипта опроса устройств превышает заданный порог",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=exec_job_timestamp', 'netbox_role=ipam', 'host=~${host:regex}'), 'host', 'task'), '-', '.')"
    }
   ]
  },
  {
   "title": "Outdated report for CSR",
   "type": "graph",
   "description": "Наличие устаревших данных в отчете для cloud.sbis.ru",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=exec_csr_data_date', 'netbox_role=ipam', 'host=~${host:regex}'), 'host', 'report'), '-', '.')"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Утилизация CPU сервера netbox",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu!=cpu-total', 'host=~${host:regex}'), 'cpu')"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "description": "Утилизация RAM сервера netbox",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=${host:regex}', 'netbox_role=ipam', 'interval=5s', 'name=system.mem.used_percent'), 'name')"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "description": "Утилизация дискового пространства сервера netbox",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~${host:regex}', 'netbox_role=ipam', 'path=~(-$|-var-lib-pgsql)', 'name=system.disk.used_percent'), 'path'), '-', '/')"
    }
   ]
  }
 ]
}