{
 "title": "IPMI Sensor",
 "description": "Ответственный: Не назначен.",
 "tags": [
  "system",
  "telegraf"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Fans",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "seriesByTag('name=ipmi_sensor', '_name=~fan\\d', 'unit=rpm', 'host=monitor-collector-2.unix.tensor.ru')"
    }
   ]
  },
  {
   "title": "PS",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "target": "seriesByTag('host=monitor-collector-2.unix.tensor.ru', 'name=ipmi_sensor', '_name=~ps\\d_status')"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "target": "seriesByTag('host=monitor-collector-2.unix.tensor.ru', 'name=ipmi_sensor', '_name=~cpu_temp')"
    }
   ]
  }
 ]
}