{
 "title": "K8s - redis",
 "description": "Ответственный: Зубков А.С. (Эксплуатация)",
 "tags": [
  "k8s",
  "redis",
  "redis_k8s",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "tag_values(cluster,name=prometheus_remote_write.redis_up)"
   },
   {
    "name": "namespace",
    "query": "tag_values(namespace,name=prometheus_remote_write.redis_up,cluster=~${cluster:regex})"
   },
   {
    "name": "instance",
    "query": "tag_values(app_kubernetes_io_instance,name=prometheus_remote_write.redis_up,cluster=~${cluster:regex},namespace=~${namespace:regex})"
   },
   {
    "name": "node",
    "query": "tag_values(pod_name,name=prometheus_remote_write.redis_up,cluster=~${cluster:regex},namespace=~${namespace:regex},app_kubernetes_io_instance=~${instance:regex})"
   }
  ]
 },
 "panels": [
  {
   "title": "Statefulset Redis",
   "type": "table",
   "description": "Отображает соответствует ли количество работающих подов заданному в statefulset значению",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByTags(diffSeriesLists(seriesByTag('name=prometheus_remote_write.kube_statefulset_replicas', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'statefulset=~${instance:regex}.*'), seriesByTag('name=prometheus_remote_write.kube_statefulset_status_replicas_ready', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'statefulset=~${instance:regex}.*')),\"namespace\", \"statefulset\")"
    }
   ]
  },
  {
   "title": "Deployment Sentinel",
   "type": "table",
   "description": "Отображает соответствует ли количество работающих подов заданному в deployment значению",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=prometheus_remote_write.kube_deployment_status_replicas_unavailable', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'deployment=~${instance:regex}.*'),'namespace','deployment')"
    }
   ]
  },
  {
   "title": "Commands per second",
   "type": "graph",
   "description": "Суммарное количество всех выполняемых команд в секунду",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(keepLastValue(perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.redis_commands_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name')), 1), 'namespace', 'pod_name'), true, false)"
    }
   ]
  },
  {
   "title": "Connected clients",
   "type": "graph",
   "description": "Количество подключённых клиентов ",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(keepLastValue(groupByTags(seriesByTag('name=prometheus_remote_write.redis_connected_clients', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name'), 1), 'namespace', 'pod_name'), true, false)"
    }
   ]
  },
  {
   "title": "CPU Usage from K8s",
   "type": "graph",
   "description": "Использование CPU контейнерами redis кластера Redis, по данным k8s",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(keepLastValue(perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'pod=~${node:regex}', 'container=redis'), 'sum', 'namespace', 'pod')), 1), 'namespace', 'pod'), true, false)"
    }
   ]
  },
  {
   "title": "Used Memory from K8s",
   "type": "graph",
   "description": "Использование памяти контейнерами redis кластера Redis, по данным k8s",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(keepLastValue(groupByTags(seriesByTag('name=prometheus_remote_write.container_memory_usage_bytes', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'pod=~${node:regex}', 'container=redis'), 'sum', 'namespace', 'pod'), 1), 'namespace', 'pod'), true, false)"
    }
   ]
  },
  {
   "title": "Список нод Redis",
   "type": "table",
   "description": "Список подов кластера Redis",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "seriesByTag('name=prometheus_remote_write.redis_instance_info', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}')"
    },
    {
     "target": "seriesByTag('name=prometheus_remote_write.redis_uptime_in_seconds', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}')"
    }
   ]
  },
  {
   "title": "Адреса нод кластера",
   "type": "table",
   "description": "Адреса подов кластера Redis",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByTags(groupByTags(seriesByTag('name=prometheus_remote_write.redis_up', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name'), 'pod_name', 'app_kubernetes_io_instance', 'namespace', 'cluster'), '([^.]*).([^.]*).([^.]*).([^.]*)', '\\1.\\2-redis-nodes.\\3.svc.\\4.k8s.tensor.ru'), true, false)"
    }
   ]
  },
  {
   "title": "Нода с ролью master",
   "type": "graph",
   "description": "Имя пода являющегося мастером (значение 1) в кластере Redis",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(keepLastValue(groupByTags(seriesByTag('name=prometheus_remote_write.redis_instance_info', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}', 'role=master'), 'sum', 'namespace', 'pod_name'), 1), 'namespace', 'pod_name'), true)"
    }
   ]
  },
  {
   "title": "Адрес мастер сервиса",
   "type": "table",
   "description": "Адрес сервиса кластера Redis за которым всегда находится мастер",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByTags(groupByTags(seriesByTag('name=prometheus_remote_write.redis_up', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'app_kubernetes_io_instance'), 'app_kubernetes_io_instance', 'namespace', 'cluster'), '([^.]*).([^.]*).([^.]*)', '\\1-redis-master.\\2.svc.\\3.k8s.tensor.ru'), true, false)"
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Commands per second",
   "type": "graph",
   "description": "Суммарное количество всех выполняемых команд в секунду",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(keepLastValue(perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.redis_commands_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name')), 1), 'namespace', 'pod_name'), true, false)"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected clients",
     "type": "graph",
     "description": "Количество подключённых клиентов ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(groupByTags(seriesByTag('name=prometheus_remote_write.redis_connected_clients', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name'), 1), 'namespace', 'pod_name'), true, false)"
      },
      {
       "target": "sortByName(aliasSub(aliasByTags(keepLastValue(groupByTags(seriesByTag('name=prometheus_remote_write.redis_config_maxclients', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'app_tensor_ru_role=master'), 'sum', 'namespace', 'app_kubernetes_io_instance'), 1), 'namespace', 'app_kubernetes_io_instance'), '(.*)', 'maxclients | \\1'), true, false)"
      }
     ]
    },
    {
     "title": "Rejected connections per second",
     "type": "graph",
     "description": "Количество отклоненных подключений в секунду",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.redis_rejected_connections_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name')), 1), 'namespace', 'pod_name'), true, false)"
      }
     ]
    },
    {
     "title": "Blocked clients",
     "type": "graph",
     "description": "Количество заблокированных подключений",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(groupByTags(seriesByTag('name=prometheus_remote_write.redis_blocked_clients', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name'), 1), 'namespace', 'pod_name'), true, false)"
      }
     ]
    },
    {
     "title": "Masterlink last seconds ago",
     "type": "graph",
     "description": "Показывает сколько секунд прошло с момента последней синхронизации с мастером. Только у слейвов",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(groupByTags(seriesByTag('name=prometheus_remote_write.redis_master_last_io_seconds_ago', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name'), 1), 'namespace', 'pod_name'), true, false)"
      }
     ]
    }
   ]
  },
  {
   "title": "Keyspace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Keys total",
     "type": "graph",
     "description": "Общее количество ключей в базе",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(groupByTags(seriesByTag('name=prometheus_remote_write.redis_db_keys', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name'), 1), 'namespace', 'pod_name'), true, false)"
      }
     ]
    },
    {
     "title": "Keys expires",
     "type": "graph",
     "description": "Количество ключей со сроком жизни",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(groupByTags(seriesByTag('name=prometheus_remote_write.redis_db_keys_expiring', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name'), 1), 'namespace', 'pod_name'), true, false)"
      }
     ]
    },
    {
     "title": "Keys avg_ttl",
     "type": "graph",
     "description": "Среднее \"время жизни\" ключей",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(groupByTags(seriesByTag('name=prometheus_remote_write.redis_db_avg_ttl_seconds', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name'), 1), 'namespace', 'pod_name'), true, false)"
      }
     ]
    },
    {
     "title": "Keys evicted per second",
     "type": "graph",
     "description": "Количество вытесненных ключей в секунду",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.redis_evicted_keys_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name')), 1), 'namespace', 'pod_name'), true, false)"
      }
     ]
    },
    {
     "title": "Hit Rate",
     "type": "graph",
     "description": "Отношение числа запросов с попаданием к общему числу запросов (запросы с попаданием + запросы без попадания)",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(divideSeriesLists(groupByTags(seriesByTag('name=prometheus_remote_write.redis_keyspace_hits_total ', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name'), groupByTags(seriesByTag('name=~prometheus_remote_write.redis_keyspace_(hits|misses)_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name')),1), 'namespace', 'pod_name'), true, false)"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Sys+User Usage from Redis",
     "type": "graph",
     "description": "Суммарное sys+user потребление CPU, по данным Redis",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(perSecond(groupByTags(seriesByTag('name=~prometheus_remote_write.redis_cpu_(sys|user)_seconds_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name')), 1), 'namespace', 'pod_name'), true, false)"
      }
     ]
    },
    {
     "title": "CPU Children Sys+User Usage  from Redis",
     "type": "graph",
     "description": "Суммарное sys+user потребление CPU для дочерних процессов Redis, по данным Redis",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(perSecond(groupByTags(seriesByTag('name=~prometheus_remote_write.redis_cpu_(sys|user)_children_seconds_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name')), 1), 'namespace', 'pod_name'), true, false)"
      }
     ]
    },
    {
     "title": "CPU Usage from K8s",
     "type": "graph",
     "description": "Общее потребление CPU контейнерами кластера Redis, по данным k8s",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'pod=~${instance:regex}.*', 'container=~[^P]'), 'sum', 'namespace', 'pod', 'container')), 1), 'namespace', 'pod', 'container'), true, false)"
      }
     ]
    },
    {
     "title": "CPU Throttling from K8s",
     "type": "graph",
     "description": "Процент тротлинга по CPU контейнеров кластера Redis, по данным k8s",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasSub(keepLastValue(divideSeriesLists(summarize(seriesByTag('name=prometheus_remote_write.container_cpu_cfs_throttled_periods_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'pod=~${instance:regex}.*', 'container=~.+'), '2min', 'range', true), summarize(seriesByTag('name=prometheus_remote_write.container_cpu_cfs_periods_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'pod=~${instance:regex}.*', 'container=~.+'), '2min', 'range', true)),1),  '.*container=([a-zA-Z0-9-]*).*pod=([a-zA-Z0-9-]*).*', '\\2 :: \\1'), true, false)"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used Memory from Redis",
     "type": "graph",
     "description": "Использование памяти под данные, по данным Redis",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(groupByTags(seriesByTag('name=prometheus_remote_write.redis_memory_used_bytes', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name'), 1), 'namespace', 'pod_name'), true, false)"
      },
      {
       "target": "sortByName(aliasSub(aliasByTags(keepLastValue(groupByTags(seriesByTag('name=prometheus_remote_write.redis_config_maxmemory', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'app_tensor_ru_role=master'), 'sum', 'namespace', 'app_kubernetes_io_instance'), 1), 'namespace', 'app_kubernetes_io_instance'), '(.*)', 'maxmemory | \\1'), true, false)"
      }
     ]
    },
    {
     "title": "Memory fragmentation ratio from Redis",
     "type": "graph",
     "description": "Коэффициент фрагментация памяти Redis",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(groupByTags(seriesByTag('name=prometheus_remote_write.redis_mem_fragmentation_ratio', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name'), 1), 'namespace', 'pod_name'), true, false)"
      }
     ]
    },
    {
     "title": "Memory Usage from K8s",
     "type": "graph",
     "description": "Использование памяти контейнерами кластера Redis, по данным k8s",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(groupByTags(seriesByTag('name=prometheus_remote_write.container_memory_usage_bytes', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'pod=~${instance:regex}.*', 'container=~[^P]'), 'sum', 'namespace', 'pod', 'container'), 1), 'namespace', 'pod', 'container'), true, false)"
      }
     ]
    },
    {
     "title": "Memory Utilisation from K8s",
     "type": "graph",
     "description": "Утилизация памяти контейнерами кластера Redis, относительно лимитов, по данным k8s",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(divideSeriesLists(groupByTags(seriesByTag('name=prometheus_remote_write.container_memory_usage_bytes', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'pod=~${instance:regex}.*', 'container=~[^P]'), 'sum', 'namespace', 'pod', 'container'), groupByTags(seriesByTag('name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'pod=~${instance:regex}.*', 'container=~[^P]'), 'sum', 'namespace', 'pod', 'container')),1), 'namespace', 'pod', 'container'), true, false)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Input",
     "type": "graph",
     "description": "Объем входящего трафика",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.redis_net_input_bytes_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name')), 1), 'namespace', 'pod_name'), true, false)"
      }
     ]
    },
    {
     "title": "Network Output",
     "type": "graph",
     "description": "Объем исходящего трафика",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(keepLastValue(perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.redis_net_output_bytes_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=~${node:regex}'), 'sum', 'namespace', 'pod_name')), 1), 'namespace', 'pod_name'), true, false)"
      }
     ]
    }
   ]
  },
  {
   "title": "By commands for $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Commands per second by command for $node",
     "type": "graph",
     "description": "Количество конкретных команд в секунду",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.redis_commands_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=$node'), 'sum', 'cmd')), 'cmd'), true, false)"
      }
     ]
    },
    {
     "title": "Commands duration by command for $node",
     "type": "graph",
     "description": "Среднее время затраченное на выполнение команды в секунду",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 112 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "target": "aliasByTags(divideSeriesLists(perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.redis_commands_duration_seconds_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=$node'), 'sum', 'cmd')), perSecond(groupByTags(seriesByTag('name=prometheus_remote_write.redis_commands_total', 'cluster=~${cluster:regex}', 'namespace=~${namespace:regex}', 'app_kubernetes_io_instance=~${instance:regex}', 'pod_name=$node'), 'sum', 'cmd'))), 'cmd')"
      }
     ]
    }
   ]
  }
 ]
}