{
 "title": "K8s - Node pools",
 "description": "Ответственный:  Никулин А.Н. (Проектный отдел)",
 "tags": [ "telegraf" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "tag_values(cluster,name=prometheus_remote_write.up)"
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": "tag_values(pool,cluster=$cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "tag_values(node,name=prometheus_remote_write.kube_node_role,role=$pool,cluster=$cluster)"
   },
   { "name": "function", "label": "Function", "query": "Average,Max,Min" },
   { "name": "top", "label": "Top", "query": "5,10,25,50,ALL" }
  ]
 },
 "panels": [
  {
   "title": "Pool overview by CPU cores",
   "type": "graph",
   "description": "Суммарное использование нод в указанном пуле (Pool)\n* Max - суммарный объем ресурсов нод указанного пула\n* Requests - суммарный объем Requests всех подов указанного пула\n* Usage - суммарное фактическое потребление ресурсов подами из указанного пула",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(groupByTags(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_requests', 'resource=cpu', 'pool=$pool'), 'sum', 'cluster'), 'Requests')"
    },
    {
     "refCount": 1,
     "target": "alias(groupByTags(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_allocatable', 'resource=cpu', 'pool=$pool'), 'sum', 'cluster'), 'Max')"
    },
    {
     "refCount": 1,
     "target": "alias(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'node_name=~${node:regex}$', 'mode!=idle')), 'sum', 'cluster'), '10min'), 'Average'), '$function'), 'Usage')"
    },
    {
     "refCount": 1,
     "target": "alias(scale(#B, 0.8), 'Warn')",
     "targetFull": "alias(scale(alias(groupByTags(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_allocatable', 'resource=cpu', 'pool=$pool'), 'sum', 'cluster'), 'Max'), 0.8), 'Warn')"
    },
    {
     "refCount": 1,
     "target": "alias(scale(#B, 0.9), 'Crit')",
     "targetFull": "alias(scale(alias(groupByTags(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_allocatable', 'resource=cpu', 'pool=$pool'), 'sum', 'cluster'), 'Max'), 0.9), 'Crit')"
    },
    {
     "refCount": 1,
     "target": "alias(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'node_name=~${node:regex}$', 'mode!=idle')), 'sum', 'cluster'), '10min'), 'Max'), '$function'), 'Usage')"
    },
    {
     "refCount": 1,
     "target": "alias(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'node_name=~${node:regex}$', 'mode!=idle')), 'sum', 'cluster'), '10min'), 'Min'), '$function'), 'Usage')"
    }
   ]
  },
  {
   "title": "Pool overview by memory",
   "type": "graph",
   "description": "Суммарное использование нод в указанном пуле (Pool)\n* Max - суммарный объем ресурсов нод указанного пула\n* Requests - суммарный объем Requests всех подов указанного пула\n* Usage - суммарное фактическое потребление ресурсов подами из указанного пула",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "refCount": 3,
     "target": "alias(groupByTags(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_requests', 'resource=memory', 'pool=$pool'), 'sum', 'cluster'), 'Requests')"
    },
    {
     "refCount": 3,
     "target": "alias(groupByTags(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_allocatable', 'resource=memory', 'pool=$pool'), 'sum', 'cluster'), 'Max')"
    },
    {
     "refCount": 2,
     "target": "alias(groupByTags(sortByName(aliasByTags(grep(alias(movingAverage(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), #C), '5min'), 'Average'), '$function'), 'node_name'), true, false), 'sum', ''), 'Usage')",
     "targetFull": "alias(groupByTags(sortByName(aliasByTags(grep(alias(movingAverage(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemAvailable_bytes')), '5min'), 'Average'), '$function'), 'node_name'), true, false), 'sum', ''), 'Usage')"
    },
    {
     "refCount": 2,
     "target": "alias(scale(#B, 0.8), 'Warn')",
     "targetFull": "alias(scale(alias(groupByTags(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_allocatable', 'resource=memory', 'pool=$pool'), 'sum', 'cluster'), 'Max'), 0.8), 'Warn')"
    },
    {
     "refCount": 2,
     "target": "alias(scale(#B, 0.9), 'Crit')",
     "targetFull": "alias(scale(alias(groupByTags(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_allocatable', 'resource=memory', 'pool=$pool'), 'sum', 'cluster'), 'Max'), 0.9), 'Crit')"
    },
    {
     "refCount": 2,
     "target": "alias(groupByTags(sortByName(aliasByTags(grep(alias(movingMax(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), #C), '5min'), 'Max'), '$function'), 'node_name'), true, false), 'sum', ''), 'Usage')",
     "targetFull": "alias(groupByTags(sortByName(aliasByTags(grep(alias(movingMax(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemAvailable_bytes')), '5min'), 'Max'), '$function'), 'node_name'), true, false), 'sum', ''), 'Usage')"
    },
    {
     "refCount": 2,
     "target": "alias(groupByTags(sortByName(aliasByTags(grep(alias(movingMin(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), #C), '5min'), 'Min'), '$function'), 'node_name'), true, false), 'sum', ''), 'Usage')",
     "targetFull": "alias(groupByTags(sortByName(aliasByTags(grep(alias(movingMin(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemAvailable_bytes')), '5min'), 'Min'), '$function'), 'node_name'), true, false), 'sum', ''), 'Usage')"
    }
   ]
  },
  {
   "title": "Pool overview by pods",
   "type": "graph",
   "description": "Суммарное использование ресурсов нод в указанном пуле (Pool)\n* Max - максимальное допустимое количество подов для нод указанного пула\n* Usage - фактическое количество запущенных подов на нодах указанного пула",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(groupByTags(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_requests', 'resource=pods', 'pool=$pool'), 'sum', 'cluster'), 'Usage')"
    },
    {
     "target": "alias(groupByTags(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_allocatable', 'resource=pods', 'pool=$pool'), 'sum', 'cluster'), 'Max')"
    },
    {
     "refCount": 1,
     "target": "alias(scale(#B, 0.8), 'Warn')",
     "targetFull": "alias(scale(alias(groupByTags(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_allocatable', 'resource=pods', 'pool=$pool'), 'sum', 'cluster'), 'Max'), 0.8), 'Warn')"
    },
    {
     "target": "alias(scale(#B, 0.9), 'Crit')",
     "targetFull": "alias(scale(alias(groupByTags(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_allocatable', 'resource=pods', 'pool=$pool'), 'sum', 'cluster'), 'Max'), 0.9), 'Crit')"
    }
   ]
  },
  {
   "title": "Unrequested CPU cores on nodes",
   "type": "bargauge",
   "description": "Оставшийся объем для планирования CPU на ноды указанного пула (Pool)",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(diffSeriesLists(aliasByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_node_status_allocatable', 'resource=cpu', 'node=~${node:regex}$', 'cluster=$cluster'), 'node'), #A), 'node'), true, false)",
     "targetFull": "sortByName(aliasByTags(diffSeriesLists(aliasByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_node_status_allocatable', 'resource=cpu', 'node=~${node:regex}$', 'cluster=$cluster'), 'node'), groupByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=cpu', 'node=~${node:regex}$', 'cluster=$cluster'), 'sum', 'node')), 'node'), true, false)"
    }
   ]
  },
  {
   "title": "Top CPU core requesters",
   "type": "bargauge",
   "description": "Топ подов для которых выделены ресурсы CPU данного пула (в порядке убывания объема)",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highest(sortByMaxima(aliasByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=cpu', 'node=~${node:regex}$', 'cluster=$cluster'), 'pod')), $top)"
    },
    {
     "target": "sortByMaxima(aliasByTags(grep(alias(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=cpu', 'node=~${node:regex}$', 'cluster=$cluster'), 'ALL'), '$top'), 'pod'))"
    }
   ]
  },
  {
   "title": "Unrequested memory on nodes, GiB",
   "type": "bargauge",
   "description": "Оставшийся объем для планирования памяти на ноды указанного пула (Pool)",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(scale(diffSeriesLists(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_node_status_allocatable', 'resource=memory', 'node=~${node:regex}$', 'cluster=$cluster'), #A), 9.313225746154785e-10), 'node'), true, false)",
     "targetFull": "sortByName(aliasByTags(scale(diffSeriesLists(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_node_status_allocatable', 'resource=memory', 'node=~${node:regex}$', 'cluster=$cluster'), groupByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'node=~${node:regex}$', 'cluster=$cluster'), 'sum', 'node')), 9.313225746154785e-10), 'node'), true, false)"
    }
   ]
  },
  {
   "title": "Top memory requesters, GiB",
   "type": "bargauge",
   "description": "Топ подов для которых выделены ресурсы памяти данного пула (в порядке убывания объема)",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highest(sortByMaxima(aliasByTags(scale(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'node=~${node:regex}$', 'cluster=$cluster'), 9.313225746154785e-10), 'pod')), $top, 'average')"
    },
    {
     "target": "sortByMaxima(aliasByTags(grep(alias(scale(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'node=~${node:regex}$', 'cluster=$cluster'), 9.313225746154785e-10), 'ALL'), '$top'), 'pod'))"
    }
   ]
  },
  {
   "title": "Unrequested pods by nodes",
   "type": "bargauge",
   "description": "Оставшийся объем для планирования подов на ноды указанного пула (Pool)",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(diffSeriesLists(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_node_status_allocatable', 'resource=pods', 'node=~${node:regex}$', 'cluster=$cluster'), #A), 'node'), true, false)",
     "targetFull": "sortByName(aliasByTags(diffSeriesLists(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_node_status_allocatable', 'resource=pods', 'node=~${node:regex}$', 'cluster=$cluster'), groupByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_info', 'node=~${node:regex}$', 'cluster=$cluster'), 'sum', 'node')), 'node'), true, false)"
    }
   ]
  },
  {
   "title": "CPU cores usage",
   "type": "graph",
   "description": "Фактическое использование CPU на нодах из указанного пула (Pool)",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(movingAverage(divideSeriesLists(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'node_name=~${node:regex}$', 'mode!=idle')), 'sum', 'node_name'), #B), '5min'), 'Average'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(movingAverage(divideSeriesLists(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'node_name=~${node:regex}$', 'mode!=idle')), 'sum', 'node_name'), groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'node_name=~${node:regex}$')), 'sum', 'node_name')), '5min'), 'Average'), '$function'), 'node_name'), true, false)"
    },
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(movingMax(divideSeriesLists(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'node_name=~${node:regex}$', 'mode!=idle')), 'sum', 'node_name'), #B), '5min'), 'Max'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(movingMax(divideSeriesLists(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'node_name=~${node:regex}$', 'mode!=idle')), 'sum', 'node_name'), groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'node_name=~${node:regex}$')), 'sum', 'node_name')), '5min'), 'Max'), '$function'), 'node_name'), true, false)"
    },
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(movingMin(divideSeriesLists(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'node_name=~${node:regex}$', 'mode!=idle')), 'sum', 'node_name'), #B), '5min'), 'Min'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(movingMin(divideSeriesLists(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'node_name=~${node:regex}$', 'mode!=idle')), 'sum', 'node_name'), groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'node_name=~${node:regex}$')), 'sum', 'node_name')), '5min'), 'Min'), '$function'), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "description": "Фактическое использование памяти на нодах из указанного пула (Pool)",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(movingAverage(divideSeriesLists(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), #A), #C), '5min'), 'Average'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(movingAverage(divideSeriesLists(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemAvailable_bytes')), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes')), '5min'), 'Average'), '$function'), 'node_name'), true, false)"
    },
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(movingMax(divideSeriesLists(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), #A), #C), '5min'), 'Max'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(movingMax(divideSeriesLists(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemAvailable_bytes')), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes')), '5min'), 'Max'), '$function'), 'node_name'), true, false)"
    },
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(movingMin(divideSeriesLists(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), #A), #C), '5min'), 'Min'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(movingMin(divideSeriesLists(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemAvailable_bytes')), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes')), '5min'), 'Min'), '$function'), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "graph",
   "description": "Количество нод из указанного пула (Pool)",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_node_role', 'role=$pool'), 'sum', 'cluster'), 'Nodes')"
    }
   ]
  }
 ]
}