{
 "title": "K8s - Containers - VPA Requests",
 "description": "Ответственный: Никулин А.Н. (Проектный отдел)",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "tag_values(cluster,name=prometheus_remote_write.container_cpu_usage_seconds_total)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "tag_values(namespace,cluster=$cluster,name=prometheus_remote_write.container_cpu_usage_seconds_total)"
   },
   {
    "name": "target_kind",
    "label": "Kind",
    "query": "tag_values(owner_kind,namespace=$namespace,cluster=$cluster)"
   },
   {
    "name": "target_name",
    "label": "Name",
    "query": "tag_values(owner_name,namespace=${namespace:regex},owner_kind=${target_kind:regex},cluster=${cluster:regex})"
   },
   {
    "name": "pod",
    "label": " Pod",
    "query": "tag_values(pod,owner_kind=${target_kind:regex}, owner_name=${target_name:regex},namespace=${namespace:regex},cluster=${cluster:regex})"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "tag_values(container,pod=~${pod:regex},namespace=${namespace:regex},cluster=${cluster:regex})"
   },
   { "name": "function", "label": "Function", "query": "average,max,min" }
  ]
 },
 "panels": [
  {
   "type": "yesoreyeram-boomtable-panel",
   "description": "Описание namespace",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "refCount": 3,
     "target": "aliasSub(aliasByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_namespace_labels', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'namespace!=~personal.+'), 'namespace', 'label_k8s_tensor_ru_ns_type', 'label_app_tensor_ru_tenant', 'label_k8s_tensor_ru_owned_by', 'label_app_tensor_ru_stage', 'label_app_kubernetes_io_managed_by', 0), 'prometheus_remote_write', 'default')"
    },
    {
     "refCount": 2,
     "target": "aliasSub(#A, '$namespace$', 'tenant')",
     "targetFull": "aliasSub(aliasSub(aliasByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_namespace_labels', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'namespace!=~personal.+'), 'namespace', 'label_k8s_tensor_ru_ns_type', 'label_app_tensor_ru_tenant', 'label_k8s_tensor_ru_owned_by', 'label_app_tensor_ru_stage', 'label_app_kubernetes_io_managed_by', 0), 'prometheus_remote_write', 'default'), '$namespace$', 'tenant')"
    },
    {
     "refCount": 2,
     "target": "aliasSub(#A, '$namespace$', 'stage')",
     "targetFull": "aliasSub(aliasSub(aliasByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_namespace_labels', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'namespace!=~personal.+'), 'namespace', 'label_k8s_tensor_ru_ns_type', 'label_app_tensor_ru_tenant', 'label_k8s_tensor_ru_owned_by', 'label_app_tensor_ru_stage', 'label_app_kubernetes_io_managed_by', 0), 'prometheus_remote_write', 'default'), '$namespace$', 'stage')"
    },
    {
     "refCount": 2,
     "target": "aliasSub(#A, '$namespace$', 'owned_by')",
     "targetFull": "aliasSub(aliasSub(aliasByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_namespace_labels', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'namespace!=~personal.+'), 'namespace', 'label_k8s_tensor_ru_ns_type', 'label_app_tensor_ru_tenant', 'label_k8s_tensor_ru_owned_by', 'label_app_tensor_ru_stage', 'label_app_kubernetes_io_managed_by', 0), 'prometheus_remote_write', 'default'), '$namespace$', 'owned_by')"
    },
    {
     "refCount": 2,
     "target": "aliasSub(#A, '$namespace$', 'managed_by')",
     "targetFull": "aliasSub(aliasSub(aliasByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_namespace_labels', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'namespace!=~personal.+'), 'namespace', 'label_k8s_tensor_ru_ns_type', 'label_app_tensor_ru_tenant', 'label_k8s_tensor_ru_owned_by', 'label_app_tensor_ru_stage', 'label_app_kubernetes_io_managed_by', 0), 'prometheus_remote_write', 'default'), '$namespace$', 'managed_by')"
    },
    {
     "refCount": 3,
     "target": "aliasSub(aliasByTags(scale(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_namespace_labels', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'namespace!=~personal.+', 'label_k8s_tensor_ru_ns_type=application'), 2), 'namespace', 'label_k8s_tensor_ru_ns_type', 'label_app_tensor_ru_tenant', 'label_k8s_tensor_ru_owned_by', 'label_app_tensor_ru_stage', 'label_app_kubernetes_io_managed_by', 0), 'prometheus_remote_write', 'type')"
    },
    {
     "refCount": 3,
     "target": "aliasSub(aliasByTags(scale(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_namespace_labels', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'namespace!=~personal.+', 'label_k8s_tensor_ru_ns_type=system'), 3), 'namespace', 'label_k8s_tensor_ru_ns_type', 'label_app_tensor_ru_tenant', 'label_k8s_tensor_ru_owned_by', 'label_app_tensor_ru_stage', 'label_app_kubernetes_io_managed_by', 0), 'prometheus_remote_write', 'type')"
    },
    {
     "refCount": 3,
     "target": "aliasSub(aliasByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_namespace_labels', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'namespace!=~personal.+', 'label_k8s_tensor_ru_ns_type!=~(system|application)'), 'namespace', 'label_k8s_tensor_ru_ns_type', 'label_app_tensor_ru_tenant', 'label_k8s_tensor_ru_owned_by', 'label_app_tensor_ru_stage', 'label_app_kubernetes_io_managed_by', 0), 'prometheus_remote_write', 'type')"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Статистика использования CPU по отношению к выделенным лимитам и реквестам",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target', 'namespace=${namespace:regex}', 'target_kind=${target_kind:regex}', 'target_name=${target_name:regex}', 'container=${container:regex}', 'resource=cpu'), 'last', ''), 'Recommended Requests')"
    },
    {
     "target": "alias(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound', 'namespace=${namespace:regex}', 'target_kind=${target_kind:regex}', 'target_name=${target_name:regex}', 'container=${container:regex}', 'resource=cpu'), 'last', ''), 'Recommended Limits')"
    },
    {
     "target": "alias(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'container=${container:regex}', 'pod=~${pod:regex}', 'namespace=${namespace:regex}')), 'average', 'container'), '5min'), 'average'), '$function'), 'Usage')"
    },
    {
     "target": "alias(maxSeries(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'pod=~${pod:regex}', 'container=${container:regex}', 'resource=cpu')), 'Requests')"
    },
    {
     "target": "alias(maxSeries(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'pod=~${pod:regex}', 'container=${container:regex}', 'resource=cpu')), 'Limits')"
    },
    {
     "target": "alias(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'container=${container:regex}', 'pod=~${pod:regex}', 'namespace=${namespace:regex}')), 'max', 'container'), '5min'), 'max'), '$function'), 'Usage')"
    },
    {
     "target": "alias(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'container=${container:regex}', 'pod=~${pod:regex}', 'namespace=${namespace:regex}')), 'min', 'container'), '5min'), 'min'), '$function'), 'Usage')"
    }
   ]
  },
  {
   "title": "CPU Stat",
   "type": "piechart",
   "description": "Статистика использования CPU по отношению к выделенным лимитам и реквестам",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "refCount": 4,
     "target": "alias(aliasByTags(grep(alias(movingAverage(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), #B), 'average', 'container'), '5min'), 'average'), '$function'), 'container'), 'Usage')",
     "targetFull": "alias(aliasByTags(grep(alias(movingAverage(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), 'average', 'container'), '5min'), 'average'), '$function'), 'container'), 'Usage')"
    },
    {
     "refCount": 4,
     "target": "alias(aggregateLine(aliasByTags(grep(alias(movingMax(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), #B), 'max', 'container'), '5min'), 'max'), '$function'), 'container'), 'max', true), 'Usage', false)",
     "targetFull": "alias(aggregateLine(aliasByTags(grep(alias(movingMax(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), 'max', 'container'), '5min'), 'max'), '$function'), 'container'), 'max', true), 'Usage', false)"
    },
    {
     "refCount": 3,
     "target": "alias(aliasByTags(grep(alias(movingMin(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), #B), 'min', 'container'), '5min'), 'min'), '$function'), 'container'), 'Usage')",
     "targetFull": "alias(aliasByTags(grep(alias(movingMin(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), 'min', 'container'), '5min'), 'min'), '$function'), 'container'), 'Usage')"
    },
    {
     "refCount": 4,
     "target": "alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), #B), #C), 'min', true), 0), 0), 'max', false), '$function'), 'Requests', false)",
     "targetFull": "alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), alias(aggregateLine(aliasByTags(grep(alias(movingMax(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), 'max', 'container'), '5min'), 'max'), '$function'), 'container'), 'max', true), 'Usage', false)), 'min', true), 0), 0), 'max', false), '$function'), 'Requests', false)"
    },
    {
     "refCount": 4,
     "target": "alias(grep(alias(aggregateLine(diffSeriesLists(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), #B), #C), #F), 'min', true), 'max', false), '$function'), 'Limits', false)",
     "targetFull": "alias(grep(alias(aggregateLine(diffSeriesLists(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), alias(aggregateLine(aliasByTags(grep(alias(movingMax(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), 'max', 'container'), '5min'), 'max'), '$function'), 'container'), 'max', true), 'Usage', false)), alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), alias(aggregateLine(aliasByTags(grep(alias(movingMax(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), 'max', 'container'), '5min'), 'max'), '$function'), 'container'), 'max', true), 'Usage', false)), 'min', true), 0), 0), 'max', false), '$function'), 'Requests', false)), 'min', true), 'max', false), '$function'), 'Limits', false)"
    },
    {
     "refCount": 4,
     "target": "alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), #B), #A), 'min', true), 0), 0), 'average', false), '$function'), 'Requests', false)",
     "targetFull": "alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), alias(aliasByTags(grep(alias(movingAverage(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), 'average', 'container'), '5min'), 'average'), '$function'), 'container'), 'Usage')), 'min', true), 0), 0), 'average', false), '$function'), 'Requests', false)"
    },
    {
     "refCount": 3,
     "target": "alias(grep(alias(aggregateLine(diffSeriesLists(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), #B), #A), #G), 'min', true), 'average', false), '$function'), 'Limits', false)",
     "targetFull": "alias(grep(alias(aggregateLine(diffSeriesLists(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), alias(aliasByTags(grep(alias(movingAverage(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), 'average', 'container'), '5min'), 'average'), '$function'), 'container'), 'Usage')), alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), alias(aliasByTags(grep(alias(movingAverage(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), 'average', 'container'), '5min'), 'average'), '$function'), 'container'), 'Usage')), 'min', true), 0), 0), 'average', false), '$function'), 'Requests', false)), 'min', true), 'average', false), '$function'), 'Limits', false)"
    },
    {
     "refCount": 4,
     "target": "alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), #B), #D), 'min', true), 0), 0), 'min', false), '$function'), 'Requests', false)",
     "targetFull": "alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), alias(aliasByTags(grep(alias(movingMin(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), 'min', 'container'), '5min'), 'min'), '$function'), 'container'), 'Usage')), 'min', true), 0), 0), 'min', false), '$function'), 'Requests', false)"
    },
    {
     "refCount": 4,
     "target": "alias(grep(alias(aggregateLine(diffSeriesLists(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), #B), #D), #I), 'min', true), 'min', false), '$function'), 'Limits', false)",
     "targetFull": "alias(grep(alias(aggregateLine(diffSeriesLists(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), alias(aliasByTags(grep(alias(movingMin(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), 'min', 'container'), '5min'), 'min'), '$function'), 'container'), 'Usage')), alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=cpu', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), alias(aliasByTags(grep(alias(movingMin(groupByTags(divideSeriesLists(keepLastValue(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}')), 1), groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'pod=~${pod:regex}'), 'last', '')), 'min', 'container'), '5min'), 'min'), '$function'), 'container'), 'Usage')), 'min', true), 0), 0), 'min', false), '$function'), 'Requests', false)), 'min', true), 'min', false), '$function'), 'Limits', false)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Статистика использования памяти по отношению к выделенным лимитам и реквестам",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target', 'namespace=${namespace:regex}', 'target_kind=${target_kind:regex}', 'target_name=${target_name:regex}', 'container=${container:regex}', 'resource=memory'), 'last', ''), 'Recommended Requests')"
    },
    {
     "target": "alias(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound', 'namespace=${namespace:regex}', 'target_kind=${target_kind:regex}', 'target_name=${target_name:regex}', 'container=${container:regex}', 'resource=memory'), 'last', ''), 'Recommended Limits')"
    },
    {
     "target": "alias(grep(alias(movingAverage(groupByTags(seriesByTag('job=cAdvisor', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'pod=~${pod:regex}', 'container=${container:regex}', 'namespace=${namespace:regex}'), 'average', 'container'), '5min'), 'average'), '$function'), 'Usage')"
    },
    {
     "target": "alias(maxSeries(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'pod=~${pod:regex}', 'container=${container:regex}', 'resource=memory')), 'Requests')"
    },
    {
     "target": "alias(maxSeries(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'pod=~${pod:regex}', 'container=${container:regex}', 'resource=memory')), 'Limits')"
    },
    {
     "target": "alias(grep(alias(movingMax(groupByTags(seriesByTag('job=cAdvisor', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'pod=~${pod:regex}', 'container=${container:regex}', 'namespace=${namespace:regex}'), 'max', 'container'), '5min'), 'max'), '$function'), 'Usage')"
    },
    {
     "target": "alias(grep(alias(movingMin(groupByTags(seriesByTag('job=cAdvisor', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'pod=~${pod:regex}', 'container=${container:regex}', 'namespace=${namespace:regex}'), 'min', 'container'), '5min'), 'min'), '$function'), 'Usage')"
    }
   ]
  },
  {
   "title": "Memory Stat",
   "type": "piechart",
   "description": "Статистика использования памяти по отношению к выделенным лимитам и реквестам",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "refCount": 4,
     "target": "alias(aggregateLine(grep(alias(movingMax(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), #A), 'max', 'container'), '5min'), 'max'), '$function'), 'max', true), 'Usage')",
     "targetFull": "alias(aggregateLine(grep(alias(movingMax(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), 'max', 'container'), '5min'), 'max'), '$function'), 'max', true), 'Usage')"
    },
    {
     "refCount": 5,
     "target": "alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), #A), #B), 'min', true), 0), 0), 'max', false), '$function'), 'Requests', false)",
     "targetFull": "alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), alias(aggregateLine(grep(alias(movingMax(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), 'max', 'container'), '5min'), 'max'), '$function'), 'max', true), 'Usage')), 'min', true), 0), 0), 'max', false), '$function'), 'Requests', false)"
    },
    {
     "refCount": 5,
     "target": "alias(grep(alias(aggregateLine(diffSeriesLists(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), #A), #B), #C), 'min', true), 'max', false), '$function'),  'Limits', false)",
     "targetFull": "alias(grep(alias(aggregateLine(diffSeriesLists(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), alias(aggregateLine(grep(alias(movingMax(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), 'max', 'container'), '5min'), 'max'), '$function'), 'max', true), 'Usage')), alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), alias(aggregateLine(grep(alias(movingMax(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), 'max', 'container'), '5min'), 'max'), '$function'), 'max', true), 'Usage')), 'min', true), 0), 0), 'max', false), '$function'), 'Requests', false)), 'min', true), 'max', false), '$function'),  'Limits', false)"
    },
    {
     "refCount": 5,
     "target": "alias(grep(alias(movingAverage(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), #A), 'average', 'container'), '5min'), 'average'), '$function'), 'Usage')",
     "targetFull": "alias(grep(alias(movingAverage(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), 'average', 'container'), '5min'), 'average'), '$function'), 'Usage')"
    },
    {
     "refCount": 4,
     "target": "alias(grep(alias(movingMin(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), #A), 'min', 'container'), '5min'), 'min'), '$function'), 'Usage')",
     "targetFull": "alias(grep(alias(movingMin(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), 'min', 'container'), '5min'), 'min'), '$function'), 'Usage')"
    },
    {
     "refCount": 5,
     "target": "alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), #A), #E), 'min', true), 0), 0), 'average', false), '$function'), 'Requests', false)",
     "targetFull": "alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), alias(grep(alias(movingAverage(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), 'average', 'container'), '5min'), 'average'), '$function'), 'Usage')), 'min', true), 0), 0), 'average', false), '$function'), 'Requests', false)"
    },
    {
     "refCount": 4,
     "target": "alias(grep(alias(aggregateLine(diffSeriesLists(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), #A), #E), #G), 'min', true), 'average', false), '$function'),  'Limits', false)",
     "targetFull": "alias(grep(alias(aggregateLine(diffSeriesLists(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), alias(grep(alias(movingAverage(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), 'average', 'container'), '5min'), 'average'), '$function'), 'Usage')), alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), alias(grep(alias(movingAverage(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), 'average', 'container'), '5min'), 'average'), '$function'), 'Usage')), 'min', true), 0), 0), 'average', false), '$function'), 'Requests', false)), 'min', true), 'average', false), '$function'),  'Limits', false)"
    },
    {
     "refCount": 4,
     "target": "alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), #A), #F), 'min', true), 0), 0), 'min', false), '$function'), 'Requests', false)",
     "targetFull": "alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), alias(grep(alias(movingMin(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), 'min', 'container'), '5min'), 'min'), '$function'), 'Usage')), 'min', true), 0), 0), 'min', false), '$function'), 'Requests', false)"
    },
    {
     "refCount": 4,
     "target": "alias(grep(alias(aggregateLine(diffSeriesLists(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), #A), #F), #I), 'min', true), 'min', false), '$function'),  'Limits', false)",
     "targetFull": "alias(grep(alias(aggregateLine(diffSeriesLists(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), alias(grep(alias(movingMin(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), 'min', 'container'), '5min'), 'min'), '$function'), 'Usage')), alias(grep(alias(transformNull(removeBelowValue(aggregateLine(diffSeriesLists(divideSeriesLists(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'pod=~${pod:regex}'), 'last', ''), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), alias(grep(alias(movingMin(groupByTags(divideSeriesLists(keepLastValue(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 1), groupByTags(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=${cluster:regex}', 'namespace=${namespace:regex}', 'container=${container:regex}', 'pod=~${pod:regex}'), 'last', '')), 'min', 'container'), '5min'), 'min'), '$function'), 'Usage')), 'min', true), 0), 0), 'min', false), '$function'), 'Requests', false)), 'min', true), 'min', false), '$function'),  'Limits', false)"
    }
   ]
  }
 ]
}