{
 "title": "K8s - Nodes",
 "description": "Ответственный: Новиков А.В. (Эксплуатация)",
 "tags": [
  "k8s",
  "telegraf",
  "system"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "tag_values(cluster,name=prometheus_remote_write.up)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "tag_values(role,name=prometheus_remote_write.kube_node_role,cluster=$cluster)"
   },
   {
    "name": "node_name",
    "query": "tag_values(node,cluster=$cluster,role=~${role:regex})"
   },
   { "name": "function", "label": "Function", "query": "Average,Max,Min" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load Average, 1 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(grep(alias(movingAverage(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_load1'), '5min'), 'Average'), '$function'), 'node_name')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMax(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_load1'), '5min'), 'Max'), '$function'), 'node_name')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMin(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_load1'), '5min'), 'Min'), '$function'), 'node_name')"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(movingAverage(divideSeriesLists(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode!=idle', 'cluster=$cluster', 'node_name=~${node_name:regex}$')), 'sum', 'node_name'), #B), '5min'), 'Average'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(movingAverage(divideSeriesLists(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode!=idle', 'cluster=$cluster', 'node_name=~${node_name:regex}$')), 'sum', 'node_name'), groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$')), 'sum', 'node_name')), '5min'), 'Average'), '$function'), 'node_name'), true, false)"
    },
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(movingMax(divideSeriesLists(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode!=idle', 'cluster=$cluster', 'node_name=~${node_name:regex}$')), 'sum', 'node_name'), #B), '5min'), 'Max'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(movingMax(divideSeriesLists(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode!=idle', 'cluster=$cluster', 'node_name=~${node_name:regex}$')), 'sum', 'node_name'), groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$')), 'sum', 'node_name')), '5min'), 'Max'), '$function'), 'node_name'), true, false)"
    },
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(movingMin(divideSeriesLists(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode!=idle', 'cluster=$cluster', 'node_name=~${node_name:regex}$')), 'sum', 'node_name'), #B), '5min'), 'Min'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(movingMin(divideSeriesLists(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode!=idle', 'cluster=$cluster', 'node_name=~${node_name:regex}$')), 'sum', 'node_name'), groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$')), 'sum', 'node_name')), '5min'), 'Min'), '$function'), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "CPU load by cores, top 20",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByTags(highestMax(offset(scale(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.node_cpu_seconds_total', 'node_name=~${node_name:regex}$', 'mode=idle')), 'sum', 'node_name', 'cpu'), -1, 0), 1), 20), 'node_name', 'cpu')"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(grep(alias(movingAverage(perSecond(seriesByTag('job=node-exporter', 'cluster=${cluster:regex}', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_context_switches_total')), '5min'), 'Average'), '$function'), 'node_name')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMax(perSecond(seriesByTag('job=node-exporter', 'cluster=${cluster:regex}', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_context_switches_total')), '5min'), 'Max'), '$function'), 'node_name')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMin(perSecond(seriesByTag('job=node-exporter', 'cluster=${cluster:regex}', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_context_switches_total')), '5min'), 'Min'), '$function'), 'node_name')"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingAverage(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=~user|nice', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), #B), 'Average'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingAverage(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=~user|nice', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), perSecond(groupByTags(movingAverage(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name'))), 'Average'), '$function'), 'node_name'), true, false)"
    },
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMax(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=~user|nice', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), #D), 'Max'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMax(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=~user|nice', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), perSecond(groupByTags(movingMax(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name'))), 'Max'), '$function'), 'node_name'), true, false)"
    },
    {
     "refCount": 2,
     "target": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMin(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=~user|nice', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), #F), 'Min'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMin(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=~user|nice', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), perSecond(groupByTags(movingMin(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name'))), 'Min'), '$function'), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "CPU System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingAverage(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=system', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), #B), 'Average'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingAverage(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=system', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), perSecond(groupByTags(movingAverage(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name'))), 'Average'), '$function'), 'node_name'), true, false)"
    },
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMax(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=system', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), #D), 'Max'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMax(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=system', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), perSecond(groupByTags(movingMax(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name'))), 'Max'), '$function'), 'node_name'), true, false)"
    },
    {
     "refCount": 2,
     "target": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMin(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=system', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), #F), 'Min'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMin(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=system', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), perSecond(groupByTags(movingMin(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name'))), 'Min'), '$function'), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "CPU IOWait",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingAverage(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=iowait', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), #B), 'Average'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingAverage(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=iowait', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), perSecond(groupByTags(movingAverage(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name'))), 'Average'), '$function'), 'node_name'), true, false)"
    },
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMax(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=iowait', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), #D), 'Max'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMax(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=iowait', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), perSecond(groupByTags(movingMax(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name'))), 'Max'), '$function'), 'node_name'), true, false)"
    },
    {
     "refCount": 2,
     "target": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMin(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=iowait', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), #F), 'Min'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMin(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=iowait', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), perSecond(groupByTags(movingMin(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name'))), 'Min'), '$function'), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "CPU SoftIRQ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingAverage(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=softirq', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), #B), 'Average'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingAverage(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=softirq', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), perSecond(groupByTags(movingAverage(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name'))), 'Average'), '$function'), 'node_name'), true, false)"
    },
    {
     "refCount": 1,
     "target": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMax(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=softirq', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), #D), 'Max'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMax(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=softirq', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), perSecond(groupByTags(movingMax(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name'))), 'Max'), '$function'), 'node_name'), true, false)"
    },
    {
     "refCount": 2,
     "target": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMin(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=softirq', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), #F), 'Min'), '$function'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(grep(alias(divideSeriesLists(perSecond(groupByTags(movingMin(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode=softirq', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name')), perSecond(groupByTags(movingMin(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), '5min'), 'sum', 'node_name'))), 'Min'), '$function'), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "Count of cores",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(pow(seriesByTag('job=node-exporter', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.node_cpu_seconds_total', 'node_name=~${node_name:regex}$'), 0), 'sum', 'node_name'), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "Procs Running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(grep(alias(movingAverage(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_procs_running', 'cluster=${cluster:regex}', 'node_name=~${node_name:regex}$'), '5min'), 'Average'), '$function'), 'node_name')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMax(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_procs_running', 'cluster=${cluster:regex}', 'node_name=~${node_name:regex}$'), '5min'), 'Max'), '$function'), 'node_name')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMin(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_procs_running', 'cluster=${cluster:regex}', 'node_name=~${node_name:regex}$'), '5min'), 'Min'), '$function'), 'node_name')"
    }
   ]
  },
  {
   "title": "Procs Blocked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(movingMax(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_procs_blocked', 'cluster=${cluster:regex}', 'node_name=~${node_name:regex}$'), '5min'), 'node_name')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Memory Usage",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(offset(scale(divideSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemAvailable_bytes'), #B), -1), 1), 'node_name'), true, false)",
       "targetFull": "sortByName(aliasByTags(offset(scale(divideSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemAvailable_bytes'), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes')), -1), 1), 'node_name'), true, false)"
      }
     ]
    },
    {
     "title": "Memory Usage History",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "refCount": 1,
       "target": "aliasByTags(grep(alias(movingAverage(divideSeriesLists(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), #A), #C), '5min'), 'Average'), '$function'), 'node_name')",
       "targetFull": "aliasByTags(grep(alias(movingAverage(divideSeriesLists(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemAvailable_bytes')), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes')), '5min'), 'Average'), '$function'), 'node_name')"
      },
      {
       "refCount": 1,
       "target": "aliasByTags(grep(alias(movingMax(divideSeriesLists(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), #A), #C), '5min'), 'Max'), '$function'), 'node_name')",
       "targetFull": "aliasByTags(grep(alias(movingMax(divideSeriesLists(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemAvailable_bytes')), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes')), '5min'), 'Max'), '$function'), 'node_name')"
      },
      {
       "refCount": 1,
       "target": "aliasByTags(grep(alias(movingMin(divideSeriesLists(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), #A), #C), '5min'), 'Min'), '$function'), 'node_name')",
       "targetFull": "aliasByTags(grep(alias(movingMin(divideSeriesLists(diffSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes'), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemAvailable_bytes')), seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_memory_MemTotal_bytes')), '5min'), 'Min'), '$function'), 'node_name')"
      }
     ]
    },
    {
     "title": "VM PageFaults",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_vmstat_pgfault')), 'node_name')"
      }
     ]
    },
    {
     "title": "NUMA Transferred Pages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 14, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(grep(alias(movingAverage(perSecond(groupByTags(seriesByTag('job=node-exporter', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.node_zoneinfo_numa_other_total', 'node_name=~${node_name:regex}$'), 'sum', 'node_name')), '5min'), 'Average'), '$function'), 'node_name'), false)"
      },
      {
       "target": "sortByName(aliasByTags(grep(alias(movingMax(perSecond(groupByTags(seriesByTag('job=node-exporter', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.node_zoneinfo_numa_other_total', 'node_name=~${node_name:regex}$'), 'sum', 'node_name')), '5min'), 'Max'), '$function'), 'node_name'), false)"
      },
      {
       "target": "sortByName(aliasByTags(grep(alias(movingMin(perSecond(groupByTags(seriesByTag('job=node-exporter', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.node_zoneinfo_numa_other_total', 'node_name=~${node_name:regex}$'), 'sum', 'node_name')), '5min'), 'Min'), '$function'), 'node_name'), false)"
      }
     ]
    },
    {
     "title": "OOM Killer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(offsetToZero(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_vmstat_oom_kill', 'cluster=${cluster:regex}', 'node_name=~${node_name:regex}$')), 'node_name')"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Bonding Active",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_bonding_active'), 'node_name')"
    }
   ]
  },
  {
   "title": "Network Incoming Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_receive_bytes_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '120s'), 'Average'), '$function'), 'node_name'), true, false)"
    },
    {
     "target": "sortByName(aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_receive_bytes_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '120s'), 'Max'), '$function'), 'node_name'), true, false)"
    },
    {
     "target": "sortByName(aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_receive_bytes_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '120s'), 'Min'), '$function'), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "Network Incoming Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_receive_packets_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '5min'), 'Average'), '$function'), 'node_name'), true, false)"
    },
    {
     "target": "sortByName(aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_receive_packets_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '5min'), 'Max'), '$function'), 'node_name'), true, false)"
    },
    {
     "target": "sortByName(aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_receive_packets_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '5min'), 'Min'), '$function'), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "MTU Bytes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_mtu_bytes', 'device=~(bond0|ens192)', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), 'node_name', 'device')"
    }
   ]
  },
  {
   "title": "Network Outgoing Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_transmit_bytes_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '120s'), 'Average'), '$function'), 'node_name'), true, false)"
    },
    {
     "target": "sortByName(aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_transmit_bytes_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '120s'), 'Max'), '$function'), 'node_name'), true, false)"
    },
    {
     "target": "sortByName(aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_transmit_bytes_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '120s'), 'Min'), '$function'), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "Network Outgoing Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_transmit_packets_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '5min'), 'Average'), '$function'), 'node_name'), true, false)"
    },
    {
     "target": "sortByName(aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_transmit_packets_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '5min'), 'Max'), '$function'), 'node_name'), true, false)"
    },
    {
     "target": "sortByName(aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_transmit_packets_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'device=~(bond0ens192)')), 'sum', 'node_name'), '5min'), 'Min'), '$function'), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "FileSystem Usage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(offset(scale(divideSeriesLists(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_filesystem_avail_bytes', 'device=-dev-sda2', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), #B), -1), 1), 'node_name'), true, false)",
       "targetFull": "sortByName(aliasByTags(offset(scale(divideSeriesLists(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_filesystem_avail_bytes', 'device=-dev-sda2', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), aliasByTags(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_filesystem_size_bytes', 'device=-dev-sda2', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), 'instance', 'device')), -1), 1), 'node_name'), true, false)"
      }
     ]
    },
    {
     "title": "Disk Read",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(grep(alias(movingAverage(perSecond(groupByTags(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_disk_read_bytes_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), 'sum', 'node_name')), '5min'), 'Average'), '$function'), 'node_name'), true, false)"
      },
      {
       "target": "sortByName(aliasByTags(grep(alias(movingMax(perSecond(groupByTags(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_disk_read_bytes_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), 'sum', 'node_name')), '5min'), 'Max'), '$function'), 'node_name'), true, false)"
      },
      {
       "target": "sortByName(aliasByTags(grep(alias(movingMin(perSecond(groupByTags(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_disk_read_bytes_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), 'sum', 'node_name')), '5min'), 'Min'), '$function'), 'node_name'), true, false)"
      }
     ]
    },
    {
     "title": "Disk Read IOPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 9, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_reads_completed_total')), 'max', 'node_name', 'device'), '5min'), 'Average'), '$function'), 'node_name', 'device'), true, false)"
      },
      {
       "target": "sortByName(aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_reads_completed_total')), 'max', 'node_name', 'device'), '5min'), 'Max'), '$function'), 'node_name', 'device'), true, false)"
      },
      {
       "target": "sortByName(aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_reads_completed_total')), 'max', 'node_name', 'device'), '5min'), 'Min'), '$function'), 'node_name', 'device'), true, false)"
      }
     ]
    },
    {
     "title": "Disk Read Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "refCount": 1,
       "target": "aliasByTags(grep(alias(movingAverage(divideSeriesLists(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_read_time_seconds_total')), #B), '5min'), 'Average'), '$function'), 'node_name', 'device')",
       "targetFull": "aliasByTags(grep(alias(movingAverage(divideSeriesLists(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_read_time_seconds_total')), offset(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_reads_completed_total')), 0.0001)), '5min'), 'Average'), '$function'), 'node_name', 'device')"
      },
      {
       "refCount": 1,
       "target": "aliasByTags(grep(alias(movingMax(divideSeriesLists(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_read_time_seconds_total')), #B), '5min'), 'Max'), '$function'), 'node_name', 'device')",
       "targetFull": "aliasByTags(grep(alias(movingMax(divideSeriesLists(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_read_time_seconds_total')), offset(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_reads_completed_total')), 0.0001)), '5min'), 'Max'), '$function'), 'node_name', 'device')"
      },
      {
       "refCount": 1,
       "target": "aliasByTags(grep(alias(movingMin(divideSeriesLists(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_read_time_seconds_total')), #B), '5min'), 'Min'), '$function'), 'node_name', 'device')",
       "targetFull": "aliasByTags(grep(alias(movingMin(divideSeriesLists(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_read_time_seconds_total')), offset(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_reads_completed_total')), 0.0001)), '5min'), 'Min'), '$function'), 'node_name', 'device')"
      }
     ]
    },
    {
     "title": "Disk Busy",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_io_time_seconds_total')), 'max', 'node_name', 'device'), '5min'), 'Average'), '$function'), 'node_name', 'device'), true, false)"
      },
      {
       "target": "sortByName(aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_io_time_seconds_total')), 'max', 'node_name', 'device'), '5min'), 'Max'), '$function'), 'node_name', 'device'), true, false)"
      },
      {
       "target": "sortByName(aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_io_time_seconds_total')), 'max', 'node_name', 'device'), '5min'), 'Min'), '$function'), 'node_name', 'device'), true, false)"
      }
     ]
    },
    {
     "title": "Logs Size",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(groupByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.kubelet_container_log_filesystem_used_bytes'), 'sum', 'node_name'), 'node_name'), true, false)"
      }
     ]
    },
    {
     "title": "Disk Write",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(grep(alias(movingAverage(perSecond(groupByTags(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_disk_written_bytes_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), 'sum', 'node_name')), '120s'), 'Average'), '$function'), 'node_name'), true, false)"
      },
      {
       "target": "sortByName(aliasByTags(grep(alias(movingMax(perSecond(groupByTags(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_disk_written_bytes_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), 'sum', 'node_name')), '120s'), 'Max'), '$function'), 'node_name'), true, false)"
      },
      {
       "target": "sortByName(aliasByTags(grep(alias(movingMin(perSecond(groupByTags(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_disk_written_bytes_total', 'cluster=$cluster', 'node_name=~${node_name:regex}$'), 'sum', 'node_name')), '120s'), 'Min'), '$function'), 'node_name'), true, false)"
      }
     ]
    },
    {
     "title": "Disk Wite IOPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 9, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_writes_completed_total')), 'max', 'node_name', 'device'), '5min'), 'Average'), '$function'), 'node_name', 'device'), true, false)"
      },
      {
       "target": "sortByName(aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_writes_completed_total')), 'max', 'node_name', 'device'), '5min'), 'Max'), '$function'), 'node_name', 'device'), true, false)"
      },
      {
       "target": "sortByName(aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_writes_completed_total')), 'max', 'node_name', 'device'), '5min'), 'Min'), '$function'), 'node_name', 'device'), true, false)"
      }
     ]
    },
    {
     "title": "Disk Write Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "refCount": 1,
       "target": "aliasByTags(grep(alias(movingAverage(divideSeriesLists(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_write_time_seconds_total')), #B), '5min'), 'Average'), '$function'), 'node_name', 'device')",
       "targetFull": "aliasByTags(grep(alias(movingAverage(divideSeriesLists(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_write_time_seconds_total')), offset(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_writes_completed_total')), 0.0001)), '5min'), 'Average'), '$function'), 'node_name', 'device')"
      },
      {
       "refCount": 1,
       "target": "aliasByTags(grep(alias(movingMax(divideSeriesLists(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_write_time_seconds_total')), #B), '5min'), 'Max'), '$function'), 'node_name', 'device')",
       "targetFull": "aliasByTags(grep(alias(movingMax(divideSeriesLists(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_write_time_seconds_total')), offset(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_writes_completed_total')), 0.0001)), '5min'), 'Max'), '$function'), 'node_name', 'device')"
      },
      {
       "refCount": 1,
       "target": "aliasByTags(grep(alias(movingMin(divideSeriesLists(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_write_time_seconds_total')), #B), '5min'), 'Min'), '$function'), 'node_name', 'device')",
       "targetFull": "aliasByTags(grep(alias(movingMin(divideSeriesLists(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_write_time_seconds_total')), offset(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_disk_writes_completed_total')), 0.0001)), '5min'), 'Min'), '$function'), 'node_name', 'device')"
      }
     ]
    },
    {
     "title": "Processes Blocked by I/O",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 19, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByTags(grep(alias(movingAverage(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_procs_blocked'), '5min'), 'Average'), '$function'), 'node_name')"
      },
      {
       "target": "aliasByTags(grep(alias(movingMax(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_procs_blocked'), '5min'), 'Max'), '$function'), 'node_name')"
      },
      {
       "target": "aliasByTags(grep(alias(movingMin(seriesByTag('job=node-exporter', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.node_procs_blocked'), '5min'), 'Min'), '$function'), 'node_name')"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubelet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(groupByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_info', 'cluster=${cluster:regex}', 'node=~${node_name:regex}$'), 'sum', 'node'), 'node'), true, false)"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 4, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(groupByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_info', 'cluster=${cluster:regex}', 'node=~${node_name:regex}$'), 'sum', 'node'), 'node')"
      }
     ]
    },
    {
     "title": "Kubelet CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "aliasByTags(grep(alias(movingAverage(perSecond(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.process_cpu_seconds_total')), '5min'), 'Average'), '$function'), 'node_name')"
      },
      {
       "target": "aliasByTags(grep(alias(movingMax(perSecond(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.process_cpu_seconds_total')), '5min'), 'Max'), '$function'), 'node_name')"
      },
      {
       "target": "aliasByTags(grep(alias(movingMin(perSecond(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.process_cpu_seconds_total')), '5min'), 'Min'), '$function'), 'node_name')"
      }
     ]
    },
    {
     "title": "Kubelet Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.process_resident_memory_bytes'), 'node_name')"
      }
     ]
    },
    {
     "title": "Pods Running",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.kubelet_running_pods'), 'node_name'), true, false)"
      }
     ]
    },
    {
     "title": "Pods Running",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 4, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('job=kubernetes-nodes', 'name=prometheus_remote_write.kubelet_running_pods', 'cluster=${cluster:regex}', 'node_name=~${node_name:regex}$'), 'node_name')"
      }
     ]
    },
    {
     "title": "Runtime Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "op/s" } },
     "yaxes": [
      { "format": "op/s" }
     ],
     "targets": [
      {
       "target": "aliasByTags(perSecond(groupByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.kubelet_runtime_operations_total'), 'sum', 'node_name')), 'node_name')"
      }
     ]
    },
    {
     "title": "Runtime Operations Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "op/s" } },
     "yaxes": [
      { "format": "op/s" }
     ],
     "targets": [
      {
       "target": "aliasByTags(grep(alias(movingAverage(perSecond(groupByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.kubelet_runtime_operations_errors_total'), 'sum', 'node_name')), '5min'), 'Average'), '$function'), 'node_name')"
      },
      {
       "target": "aliasByTags(grep(alias(movingMax(perSecond(groupByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.kubelet_runtime_operations_errors_total'), 'sum', 'node_name')), '5min'), 'Max'), '$function'), 'node_name')"
      },
      {
       "target": "aliasByTags(grep(alias(movingMin(perSecond(groupByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.kubelet_runtime_operations_errors_total'), 'sum', 'node_name')), '5min'), 'Min'), '$function'), 'node_name')"
      }
     ]
    },
    {
     "title": "Containers Running",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.kubelet_running_containers', 'container_state=running'), 'node_name'), true, false)"
      }
     ]
    },
    {
     "title": "Containers Running",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 4, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('job=kubernetes-nodes', 'name=prometheus_remote_write.kubelet_running_containers', 'cluster=${cluster:regex}', 'node_name=~${node_name:regex}$'), 'node_name')"
      }
     ]
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unreachable Persistent Volumes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByTags(scale(groupByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.volume_manager_total_volumes', 'plugin_name=kubernetes.io-csi:block.csi.ibm.com'), 'diff', 'node_name'), -1), 'node_name')"
      }
     ]
    },
    {
     "title": "ConfigMaps",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.volume_manager_total_volumes', 'state=actual_state_of_world', 'plugin_name=kubernetes.io-configmap'), 'node_name'))"
      }
     ]
    },
    {
     "title": "EmptyDir",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.volume_manager_total_volumes', 'state=actual_state_of_world', 'plugin_name=kubernetes.io-empty-dir'), 'node_name'))"
      }
     ]
    },
    {
     "title": "HostPath",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.volume_manager_total_volumes', 'state=actual_state_of_world', 'plugin_name=kubernetes.io-host-path'), 'node_name'))"
      }
     ]
    },
    {
     "title": "Secrets",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.volume_manager_total_volumes', 'state=actual_state_of_world', 'plugin_name=kubernetes.io-secret'), 'node_name'))"
      }
     ]
    },
    {
     "title": "IBM CSI",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.volume_manager_total_volumes', 'state=actual_state_of_world', 'plugin_name=kubernetes.io-csi:block.csi.ibm.com'), 'node_name'))"
      }
     ]
    },
    {
     "title": "Storage Operation Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "op/s" } },
     "yaxes": [
      { "format": "op/s" }
     ],
     "targets": [
      {
       "target": "aliasByTags(grep(alias(movingAverage(perSecond(groupByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.storage_operation_errors_total'), 'sum', 'node_name')), '5min'), 'Average'), '$function'), 'node_name')"
      },
      {
       "target": "aliasByTags(grep(alias(movingMax(perSecond(groupByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.storage_operation_errors_total'), 'sum', 'node_name')), '5min'), 'Max'), '$function'), 'node_name')"
      },
      {
       "target": "aliasByTags(grep(alias(movingMin(perSecond(groupByTags(seriesByTag('job=kubernetes-nodes', 'cluster=$cluster', 'node_name=~${node_name:regex}$', 'name=prometheus_remote_write.storage_operation_errors_total'), 'sum', 'node_name')), '5min'), 'Min'), '$function'), 'node_name')"
      }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Pressure",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByTags(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'node_name=~${node_name:regex}', 'name=prometheus_remote_write.kube_node_status_condition', 'status=true', 'condition!=Ready'), 'sum', 'condition'), 'condition')"
      }
     ]
    },
    {
     "title": "Pending Pods",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByTags(currentAbove(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'node_name=~${node_name:regex}', 'name=prometheus_remote_write.kube_pod_status_phase', 'phase=Pending'), 1), 'pod')"
      }
     ]
    }
   ]
  }
 ]
}