{
 "title": "k8s - shell-operator",
 "description": "Ответственный: Зубков А.С. (Проектный отдел)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "tag_values(cluster,name=prometheus_remote_write.shell_operator_live_ticks)"
   },
   {
    "name": "operator",
    "query": "tag_values(app_kubernetes_io_instance,cluster=$cluster,name=prometheus_remote_write.shell_operator_live_ticks)"
   },
   {
    "name": "namespace",
    "query": "tag_values(namespace,cluster=$cluster,app_kubernetes_io_instance=$operator,name=prometheus_remote_write.shell_operator_live_ticks)"
   }
  ]
 },
 "panels": [
  { "title": "Хуки", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Время выполнения хуков по очередям",
   "type": "timeseries",
   "description": "Отображает время выполнения хука в момент его завершения\n\nНаименование: хук.очередь.привязка",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(consolidateBy(nonNegativeDerivative(groupByTags(seriesByTag('name=prometheus_remote_write.shell_operator_hook_run_seconds_sum', 'cluster=$cluster', 'app_kubernetes_io_instance=$operator'), 'sum', 'app_kubernetes_io_instance', 'hook', 'queue', 'binding')), 'max'), 'hook', 'queue', 'binding'), true, false)"
    }
   ]
  },
  {
   "title": "Количество задач в очереди",
   "type": "timeseries",
   "description": "Суммарное количество задач в очереди, в интервал времени",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(consolidateBy(groupByTags(seriesByTag('name=prometheus_remote_write.shell_operator_tasks_queue_length', 'cluster=~${cluster:regex}', 'app_kubernetes_io_instance=~${operator:regex}'), 'sum', 'app_kubernetes_io_instance', 'queue'), 'sum'), 'queue'), true, false)"
    }
   ]
  },
  {
   "title": "Количество хуков завершившихся с ошибкой",
   "type": "timeseries",
   "description": "Отображает суммарное количество хуков, в интервал времени, которые завершились с ненулевым кодом выхода\n\nНаименование: хук.привязка",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(consolidateBy(nonNegativeDerivative(groupByTags(seriesByTag('name=~prometheus_remote_write.shell_operator_hook_run(_allowed)?_errors_total', 'cluster=${cluster:regex}', 'app_kubernetes_io_instance=${operator:regex}'), 'sum', 'app_kubernetes_io_instance', 'hook', 'binding')), 'sum'), 'hook', 'binding'), true, false)"
    }
   ]
  },
  {
   "title": "Количество выполненных хуков",
   "type": "timeseries",
   "description": "Отображает суммарное количество хуков, в интервал времени, которые завершились с нулевым кодом выхода\n\nНаименование: хук.привязка",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(consolidateBy(nonNegativeDerivative(groupByTags(seriesByTag('name=prometheus_remote_write.shell_operator_hook_run_success_total', 'cluster=${cluster:regex}', 'app_kubernetes_io_instance=${operator:regex}'), 'sum', 'app_kubernetes_io_instance', 'hook', 'binding')), 'sum'), 'hook', 'binding'), true)"
    }
   ]
  },
  {
   "title": "Количество ошибок для хука helm_hook",
   "type": "timeseries",
   "description": "Отображает суммарное количество ошибок, в интервал времени, для хука helm_hook",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "target": "aliasByTags(consolidateBy(nonNegativeDerivative(groupByTags(seriesByTag('name=~prometheus_remote_write.shell_operator_helm_hook_errors_total', 'cluster=${cluster:regex}', 'app_kubernetes_io_instance=${operator:regex}'), 'sum', 'app_kubernetes_io_instance', 'hook')), 'sum'), 'hook')"
    }
   ]
  },
  {
   "title": "Ресурсы",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Использование ЦПУ, в милиядрах",
     "type": "timeseries",
     "description": "Использование ЦПУ контейнерами находящимися в неймспейсе оператора",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "mC" } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(consolidateBy(scale(perSecond(seriesByTag('name=prometheus_remote_write.container_cpu_usage_seconds_total', 'cluster=$cluster', 'namespace=$namespace')), 1000), 'max'), 'pod', 'container'), true, false)"
      }
     ]
    },
    {
     "title": "Троттлинг ЦПУ",
     "type": "timeseries",
     "description": "Троттлинг по ЦПУ контейнеров находящихся в неймспейсе оператора",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(consolidateBy(divideSeriesLists(nonNegativeDerivative(seriesByTag('name=prometheus_remote_write.container_cpu_cfs_throttled_periods_total', 'cluster=$cluster', 'namespace=$namespace')),nonNegativeDerivative(seriesByTag('name=prometheus_remote_write.container_cpu_cfs_periods_total', 'cluster=$cluster','namespace=$namespace'))), 'max'), 'pod', 'container'), true, false)"
      }
     ]
    },
    {
     "title": "Использование памяти",
     "type": "timeseries",
     "description": "Использование памяти контейнерами находящимися в неймспейсе оператора",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(consolidateBy(seriesByTag('name=prometheus_remote_write.container_memory_usage_bytes', 'cluster=$cluster', 'namespace=$namespace'), 'max'), 'pod', 'container'), true, false)"
      }
     ]
    },
    {
     "title": "Утилизация памяти",
     "type": "timeseries",
     "description": "Утилизация памяти, относительно лимита, контейнерами находящимися в неймспейсе оператора",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(consolidateBy(divideSeriesLists(seriesByTag('name=prometheus_remote_write.container_memory_usage_bytes', 'cluster=$cluster', 'namespace=$namespace'), seriesByTag('name=prometheus_remote_write.container_spec_memory_limit_bytes', 'cluster=$cluster', 'namespace=$namespace')), 'max'), 'pod', 'container'), true, false)"
      }
     ]
    }
   ]
  },
  {
   "title": "Кеш объектов Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество кешированных объектов k8s",
     "type": "timeseries",
     "description": "Количество кешированных объектов k8s по привязке\n\nНаименование: хук.привязка",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "target": "sortByName(aliasByTags(consolidateBy(groupByTags(seriesByTag('name=prometheus_remote_write.shell_operator_kube_snapshot_objects', 'cluster=${cluster:regex}', 'app_kubernetes_io_instance=${operator:regex}'), 'sum', 'app_kubernetes_io_instance', 'hook', 'binding'), 'max'), 'hook', 'binding'), true, false)"
      }
     ]
    },
    {
     "title": "Объем кэшированных объектов k8s",
     "type": "timeseries",
     "description": "Суммарный объем кешированных объектов k8s  по привязке\n\nНаименование: хук.привязка",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(consolidateBy(groupByTags(seriesByTag('name=prometheus_remote_write.shell_operator_kube_snapshot_bytes', 'cluster=${cluster:regex}', 'app_kubernetes_io_instance=${operator:regex}'), 'sum', 'app_kubernetes_io_instance', 'hook', 'binding'), 'max'), 'hook', 'binding'), true, false)"
      }
     ]
    }
   ]
  },
  {
   "title": "Мониторы событий Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Состояние мониторов событий",
     "type": "table",
     "description": "Отображает последнее состояние мониторов событий k8s по хукам",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 58 },
     "targets": [
      {
       "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=prometheus_remote_write.shell_operator_hook_enable_kubernetes_bindings_success', 'cluster=~${cluster:regex}', 'app_kubernetes_io_instance=~${operator:regex}'), 'sum', 'app_kubernetes_io_instance', 'hook'), 'hook'), true, false)"
      }
     ]
    },
    {
     "title": "Время запуска мониторов событий",
     "type": "table",
     "description": "Отображает последнее время запуска мониторов событий k8s по хукам",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 58 },
     "targets": [
      {
       "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=prometheus_remote_write.shell_operator_hook_enable_kubernetes_bindings_seconds', 'cluster=~${cluster:regex}', 'app_kubernetes_io_instance=~${operator:regex}'), 'sum', 'app_kubernetes_io_instance', 'hook'), 'hook'), true, false)"
      }
     ]
    },
    {
     "title": "Количество неудачных попыток запуска мониторов событий",
     "type": "timeseries",
     "description": "Отображает суммарное количество неудачных попыток запуска мониторов событий k8s, по хукам, в интервал времени",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 58 },
     "targets": [
      {
       "target": "sortByName(aliasByTags(consolidateBy(nonNegativeDerivative(groupByTags(seriesByTag('name=prometheus_remote_write.shell_operator_hook_enable_kubernetes_bindings_errors_total', 'cluster=${cluster:regex}', 'app_kubernetes_io_instance=${operator:regex}'), 'sum', 'app_kubernetes_io_instance', 'hook')), 'sum'), 'hook'), true, false)"
      }
     ]
    }
   ]
  },
  {
   "title": "Тайминги",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Тайминги фильтра jq",
     "type": "timeseries",
     "description": "Тайминги работы фильтра jq\n\nНаименование: хук.очередь.привязка",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(consolidateBy(nonNegativeDerivative(groupByTags(seriesByTag('name=prometheus_remote_write.shell_operator_kube_jq_filter_duration_seconds_sum', 'cluster=${cluster:regex}', 'app_kubernetes_io_instance=${operator:regex}'), 'sum', 'app_kubernetes_io_instance', 'hook', 'queue', 'binding')), 'max'), 'hook', 'queue', 'binding'), true)"
      }
     ]
    },
    {
     "title": "Тайминги обработки событий k8s",
     "type": "timeseries",
     "description": "Тайминги обработки событий k8s\n\nНаименование: хук.очередь.привзяка",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "sortByName(aliasByTags(consolidateBy(nonNegativeDerivative(groupByTags(seriesByTag('name=prometheus_remote_write.shell_operator_kube_event_duration_seconds_sum', 'cluster=~${cluster:regex}', 'app_kubernetes_io_instance=~${operator:regex}'), 'sum', 'app_kubernetes_io_instance', 'hook', 'queue', 'binding')), 'max'), 'hook', 'queue', 'binding'), true)"
      }
     ]
    }
   ]
  }
 ]
}