{
 "title": "K8s Docker-registry Harbor (image-store)",
 "description": "Ответственный: Жуков Д.А. (Проектный отдел)",
 "tags": [
  "service",
  "telegraf",
  "harbor",
  "k8s"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "store", "query": "image-store,dev-image-store" },
   {
    "name": "project",
    "query": "tag_values(project_name,url=https:--$store.tensor.ru-metrics,service=harbor)"
   },
   { "name": "storage", "query": "minio,  minio_s3_dev" }
  ]
 },
 "panels": [
  { "title": "Состояние сервиса", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Статус Harbor",
   "type": "stat",
   "description": "Общий статус харбора",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=prometheus.harbor_health', 'url=https:--$store.tensor.ru-metrics')"
    }
   ]
  },
  {
   "title": "Статус компонентов Harbor",
   "type": "stat",
   "description": "Статус отдельных систем\n0 = Down, 1 = Up",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=prometheus.harbor_up', 'url=https:--$store.tensor.ru-metrics'), 'component'), true, false)"
    }
   ]
  },
  {
   "title": "Total disk usage",
   "type": "stat",
   "description": "Объем используемого пространства",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aggregate(seriesByTag('name=prometheus.harbor_project_quota_usage_byte', 'url=https:--$store.tensor.ru-metrics'), 'sum')"
    }
   ]
  },
  {
   "title": "Projects total",
   "type": "stat",
   "description": "Количество проектов",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(aggregate(seriesByTag('name=prometheus.harbor_project_total', 'url=https:--$store.tensor.ru-metrics'), 'sum'), 'Public - ')"
    }
   ]
  },
  {
   "title": "Image Pull\\Push Rate (1 hour)",
   "type": "graph",
   "description": "Количество операций Pull и Push на весь реестр",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_artifact_pulled', 'url=https:--$store.tensor.ru-metrics'), 'sum', ''), #B), 'Pulled Image')",
     "targetFull": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_artifact_pulled', 'url=https:--$store.tensor.ru-metrics'), 'sum', ''), timeShift(groupByTags(seriesByTag('name=prometheus.harbor_artifact_pulled', 'url=https:--$store.tensor.ru-metrics'), 'sum', ''), '1m', false)), 'Pulled Image')"
    },
    {
     "refCount": 1,
     "target": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_project_artifact_total', 'url=https:--$store.tensor.ru-metrics'), 'sum', ''), #E), 'Pushed Image')",
     "targetFull": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_project_artifact_total', 'url=https:--$store.tensor.ru-metrics'), 'sum', ''), timeShift(groupByTags(seriesByTag('name=prometheus.harbor_project_artifact_total', 'url=https:--$store.tensor.ru-metrics'), 'sum', ''), '1m', false)), 'Pushed Image')"
    }
   ]
  },
  {
   "title": "Network Receive/Transmit Varnish",
   "type": "graph",
   "description": "Объем полезного входящего\\исходящего трафика",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "groupByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=~prometheus_remote_write.container_network_(transmit|receive)_bytes_total', 'pod=~.*(varnish)'), 1)), 'sum', 'name')"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "graph",
   "description": "Время ответа реестра",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('server=https:--$store.tensor.ru-', 'service_name=telegraf_other', 'name=http_response.response_time'), 'Response')"
    }
   ]
  },
  {
   "title": "Count HTTP code(>200)",
   "type": "stat",
   "description": "Количество HTTP ошибок",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aggregate(aliasByTags(exclude(seriesByTag('name=prometheus.promhttp_metric_handler_requests_total', 'url=https:--$store.tensor.ru-metrics'), '200'), 'code'), 'sum')"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Аптайм реестра(по процессам)",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(seriesByTag('name=prometheus.process_start_time_seconds', 'url=https:--$store.tensor.ru-metrics'), 1000)"
    }
   ]
  },
  {
   "title": "Artifact total",
   "type": "stat",
   "description": "Общее количество артефактов ",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "groupByTags(seriesByTag('name=prometheus.harbor_project_artifact_total', 'url=https:--$store.tensor.ru-metrics'), 'sum', '')"
    }
   ]
  },
  {
   "title": "Проекты",
   "type": "table",
   "description": "Список проектов с параметрами",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "seriesByTag('name=~prometheus.harbor_project_(artifact_total|repo_total|quota_byte|quota_usage_byte)', 'url=https:--$store.tensor.ru-metrics')"
    }
   ]
  },
  {
   "title": "Harbor components status",
   "type": "graph",
   "description": "Статусы компонентов в разрезе времени. И сам статус harbor\n> 1 - UP, 0 - DOWN",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=prometheus.harbor_up', 'url=https:--$store.tensor.ru-metrics'), 'component'), true, false)"
    },
    {
     "target": "alias(seriesByTag('name=prometheus.harbor_health', 'url=https:--$store.tensor.ru-metrics'), 'harbor')"
    }
   ]
  },
  {
   "title": "Ошибки проверки наличия prod-образов в dev-реестре",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Ошибки проверки наличия Prod образов в dev-реестре",
   "type": "table",
   "description": "Результаты проверки наличия Prod-образов в dev-реестре",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "seriesByTag('name=~image.avaliability_code')"
    }
   ]
  },
  {
   "title": "Информация по проекту ${project:regex}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Статистика по проекту ",
     "type": "stat",
     "description": "Количество пуллов артефактов, количество артефактов в проекте, репозиториев в проекте ",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "seriesByTag('project_name=$project', 'name=~prometheus.harbor_(project_repo_total|project_artifact_total|artifact_pulled)', 'url=https:--$store.tensor.ru-metrics')"
      }
     ]
    },
    {
     "title": "Image Pull\\Push Rate (1 hour)",
     "type": "graph",
     "description": "Количество операций Pull и Push на проект",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_artifact_pulled', 'url=https:--$store.tensor.ru-metrics', 'project_name=$project'), 'sum', ''), #B), 'Pulled Image')",
       "targetFull": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_artifact_pulled', 'url=https:--$store.tensor.ru-metrics', 'project_name=$project'), 'sum', ''), timeShift(groupByTags(seriesByTag('name=prometheus.harbor_artifact_pulled', 'url=https:--$store.tensor.ru-metrics', 'project_name=$project'), 'sum', ''), '1m', false)), 'Pulled Image')"
      },
      {
       "refCount": 1,
       "target": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_project_artifact_total', 'url=https:--$store.tensor.ru-metrics', 'project_name=$project'), 'sum', ''), #E), 'Pushed Image')",
       "targetFull": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_project_artifact_total', 'url=https:--$store.tensor.ru-metrics', 'project_name=$project'), 'sum', ''), timeShift(groupByTags(seriesByTag('name=prometheus.harbor_project_artifact_total', 'url=https:--$store.tensor.ru-metrics', 'project_name=$project'), 'sum', ''), '1m', false)), 'Pushed Image')"
      }
     ]
    },
    {
     "title": "Квоты по проекту",
     "type": "graph",
     "description": "Объем, занятый файлами проекта и квота. -1 — отсутствие квоты",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=~prometheus.harbor_project_(quota_byte|quota_usage_byte)', 'project_name=$project', 'url=https:--$store.tensor.ru-metrics'), 'project_name', 'name')"
      }
     ]
    }
   ]
  },
  {
   "title": "Метрики компонент Harbor ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Использование CPU суммарное(среднее) среди экземпляров одного компонента",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(groupByTags(perSecond(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_cpu_usage_seconds_total')), 'avg', 'container'), 'container'))"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Использование RAM суммарное(среднее) среди экземпляров одного компонента",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(groupByTags(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_memory_usage_bytes'), 'sum', 'container'), 'container'))"
      }
     ]
    },
    {
     "title": "Network Receive",
     "type": "graph",
     "description": "Объём входящего сетевого трафика по подам(стекированный)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_network_receive_bytes_total')), 'pod'))"
      }
     ]
    },
    {
     "title": "Network Transmit",
     "type": "graph",
     "description": "Объём исходящего сетевого трафика по подам(стекированный)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_network_transmit_bytes_total')), 'pod'))"
      }
     ]
    },
    {
     "title": "Virtual memory usage(Harbor Service)",
     "type": "graph",
     "description": "Использование виртуальной памяти + квота (-1 - отсутствие квоты)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('name=prometheus.process_virtual_memory_bytes', 'url=https:--$store.tensor.ru-metrics'), 'Virtual memory usage')"
      }
     ]
    },
    {
     "title": "RSS Memory usage(Harbor Service)",
     "type": "graph",
     "description": "Использование резидентной памяти на виртуальном сервере",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('name=prometheus.process_resident_memory_bytes', 'url=https:--$store.tensor.ru-metrics'), 'Resident memory usage')"
      }
     ]
    }
   ]
  },
  {
   "title": "Детализированные метрики компонент Harbor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core: CPU Usage ",
     "type": "graph",
     "description": "Использование CPU компонентом Core(по контейнерам)",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'container=core'), 1)), 'pod'))"
      }
     ]
    },
    {
     "title": "Core: Memory Usage",
     "type": "graph",
     "description": "Использование RAM компонентом Core(по контейнерам)",
     "gridPos": { "h": 9, "w": 8, "x": 9, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_memory_usage_bytes', 'container=core'), 1), 'pod'))"
      }
     ]
    },
    {
     "title": "Core: Network Receive\\Transmit",
     "type": "graph",
     "description": "Объем сетевого трафика компонента Core(по подам)",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=~prometheus_remote_write.container_network_(transmit_bytes_total|receive_bytes_total)', 'pod=~.*(core)'), 1)), 'pod', 1))"
      }
     ]
    },
    {
     "title": "Registry: CPU Usage",
     "type": "graph",
     "description": "Использование CPU компонентом Registry(по контейнерам)",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'container=registry'), 1)), 'pod'))"
      }
     ]
    },
    {
     "title": "Registry:  Memory Usage",
     "type": "graph",
     "description": "Использование RAM компонентом Registry(по контейнерам)",
     "gridPos": { "h": 9, "w": 8, "x": 9, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_memory_usage_bytes', 'container=registry'), 1), 'pod'))"
      }
     ]
    },
    {
     "title": "Registry\\RegistryCtl: Network Receive\\Transmit",
     "type": "graph",
     "description": "Объем сетевого трафика компонентов Registry\\RegistryCtl(по подам)",
     "gridPos": { "h": 18, "w": 7, "x": 17, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=~prometheus_remote_write.container_network_(transmit_bytes_total|receive_bytes_total)', 'pod=~.*(registry)'), 1)), 'pod', 1))"
      }
     ]
    },
    {
     "title": "RegistryCtl: CPU Usage",
     "type": "graph",
     "description": "Использование CPU компонентом RegistryCtl(по контейнерам)",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'container=registryctl'), 1)), 'pod'))"
      }
     ]
    },
    {
     "title": "RegistryCtl:  Memory Usage",
     "type": "graph",
     "description": "Использование RAM компонентом RegistryCtl(по контейнерам)",
     "gridPos": { "h": 9, "w": 8, "x": 9, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_memory_usage_bytes', 'container=registryctl'), 1), 'pod'))"
      }
     ]
    },
    {
     "title": "Varnish: CPU Usage",
     "type": "graph",
     "description": "Использование CPU компонентом Varnish(по контейнерам)",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'container=varnish-harbor'), 1)), 'pod'))"
      }
     ]
    },
    {
     "title": "Varnish:  Memory Usage",
     "type": "graph",
     "description": "Использование RAM компонентом Varnish(по контейнерам)",
     "gridPos": { "h": 9, "w": 8, "x": 9, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_memory_usage_bytes', 'container=varnish-harbor'), 1), 'pod'))"
      }
     ]
    },
    {
     "title": "Varnish\\Telegraf: Network Receive\\Transmit",
     "type": "graph",
     "description": "Объем сетевого трафика компонентов Varnish\\Telegraf(по подам)",
     "gridPos": { "h": 18, "w": 7, "x": 17, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=~prometheus_remote_write.container_network_(transmit_bytes_total|receive_bytes_total)', 'pod=~.*(varnish)'), 1)), 'pod', 1))"
      }
     ]
    },
    {
     "title": "Telegraf: CPU Usage",
     "type": "graph",
     "description": "Использование CPU компонентом Telegraf(по контейнерам)",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'container=telegraf'), 1)), 'pod'))"
      }
     ]
    },
    {
     "title": "Telegraf: Memory Usage",
     "type": "graph",
     "description": "Использование RAM компонентом Telegraf(по контейнерам)",
     "gridPos": { "h": 9, "w": 8, "x": 9, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_memory_usage_bytes', 'container=telegraf'), 1), 'pod'))"
      }
     ]
    },
    {
     "title": "JobService: CPU Usage",
     "type": "graph",
     "description": "Использование CPU компонентом JobService(по контейнерам)",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'container=jobservice'), 1)), 'pod'))"
      }
     ]
    },
    {
     "title": "JobService:  Memory Usage",
     "type": "graph",
     "description": "Использование RAM компонентом JobService(по контейнерам)",
     "gridPos": { "h": 9, "w": 8, "x": 9, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_memory_usage_bytes', 'container=jobservice'), 1), 'pod'))"
      }
     ]
    },
    {
     "title": "JobService: Network Receive\\Transmit",
     "type": "graph",
     "description": "Объем сетевого трафика компонента JobService(по подам)",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=~prometheus_remote_write.container_network_(transmit_bytes_total|receive_bytes_total)', 'pod=~.*(jobservice)'), 1)), 'pod', 1))"
      }
     ]
    },
    {
     "title": "Portal: CPU Usage",
     "type": "graph",
     "description": "Использование CPU компонентом Portal(по контейнерам)",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'container=portal'), 1)), 'pod'))"
      }
     ]
    },
    {
     "title": "Portal:  Memory Usage",
     "type": "graph",
     "description": "Использование RAM компонентом Portal(по контейнерам)",
     "gridPos": { "h": 9, "w": 8, "x": 9, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_memory_usage_bytes', 'container=portal'), 1), 'pod'))"
      }
     ]
    },
    {
     "title": "Portal: Network Receive\\Transmit",
     "type": "graph",
     "description": "Объем сетевого трафика компонента Portal(по подам)",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=~prometheus_remote_write.container_network_(transmit_bytes_total|receive_bytes_total)', 'pod=~.*(portal)'), 1)), 'pod', 1))"
      }
     ]
    },
    {
     "title": "Exporter: CPU Usage",
     "type": "graph",
     "description": "Использование CPU компонентом Exporter(по контейнерам)",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'container=exporter'), 1)), 'pod'))"
      }
     ]
    },
    {
     "title": "Exporter: Memory Usage",
     "type": "graph",
     "description": "Использование RAM компонентом Exporter(по контейнерам)",
     "gridPos": { "h": 9, "w": 8, "x": 9, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(keepLastValue(seriesByTag('namespace=$store', 'name=prometheus_remote_write.container_memory_usage_bytes', 'container=exporter'), 1), 'pod'))"
      }
     ]
    },
    {
     "title": "Exporter: Network Receive\\Transmit",
     "type": "graph",
     "description": "Объем сетевого трафика компонента Exporter(по подам)",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByTags(perSecond(keepLastValue(seriesByTag('namespace=$store', 'name=~prometheus_remote_write.container_network_(transmit_bytes_total|receive_bytes_total)', 'pod=~.*(exporter)'), 1)), 'pod', 1))"
      }
     ]
    }
   ]
  },
  {
   "title": "Varnish Cache ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Эффективность кэша",
     "type": "gauge",
     "description": "Соотношение попадания в кэш и суммы попаданий и промахов",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "movingAverage(divideSeries(aliasByMetric(aliasByTags(sumSeries(seriesByTag('name=varnish.cache_hit', 'harbor_namespace=$store')), 'name')), #A), '1h')",
       "targetFull": "movingAverage(divideSeries(aliasByMetric(aliasByTags(sumSeries(seriesByTag('name=varnish.cache_hit', 'harbor_namespace=$store')), 'name')), movingAverage(exclude(aliasByMetric(sumSeries(seriesByTag('name=~varnish.cache_(hit|miss)', 'harbor_namespace=$store'))), 'cache_hit_grace|cache_hitpass|cache_hitmiss'), '1h')), '1h')"
      }
     ]
    },
    {
     "title": "Попадание в кеш, hit/miss",
     "type": "graph",
     "description": "Соотношение попадания в кеш и промахов",
     "gridPos": { "h": 8, "w": 7, "x": 5, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "req/m" } },
     "yaxes": [
      { "format": "req/m" }
     ],
     "targets": [
      {
       "target": "smartSummarize(perSecond(keepLastValue(groupByTags(exclude(seriesByTag('name=~varnish.cache_(hit|miss)', 'harbor_namespace=$store'), 'hit_grace|hitmiss|hitpass'), 'sum', 'name'), 1)), '1m', 'sum', '1m')"
      }
     ]
    },
    {
     "title": "All Request stat",
     "type": "graph",
     "description": "Соотношение всех клиентских запросов и запросов ушедших на бекенд(сервис Harbor)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "target": "summarize(exclude(perSecond(groupByTags(keepLastValue(seriesByTag('name=~varnish.(backend_req|client_req)', 'harbor_namespace=$store'), 1), 'sum', 'name')), 'client_req_4'), '1m', 'sum', false)"
      }
     ]
    },
    {
     "title": "Попадание в кеш, hit/miss",
     "type": "graph",
     "description": "Соотношение попадания в кеш и промахов(стекированный)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(aliasByTags(groupByTags(perSecond(seriesByTag('name=~varnish.cache*')), 'sum', 'name'), 'name'))"
      }
     ]
    },
    {
     "title": "Varnish Cache Size",
     "type": "graph",
     "description": "Размер используемой памяти под кеш(по подам)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=varnish.s0.g_bytes', 'harbor_namespace=$store'), 'host')"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collector info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open file descriptors",
     "type": "graph",
     "description": "Количество открытых файловых дескрипторов. \nВерхний предел — 1048576.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('name=prometheus.process_open_fds', 'url=https:--$store.tensor.ru-metrics'), 'Open File Descriptors')"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "description": "Количество активных параллельных потоков языка GO. \n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('name=prometheus.go_goroutines', 'url=https:--$store.tensor.ru-metrics'), 'Goroutines')"
      }
     ]
    },
    {
     "title": "Memstats",
     "type": "graph",
     "description": "Количество выделенной памяти. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByTags(exclude(seriesByTag('name=~prometheus.go_memstats_(alloc_bytes|buck_hash_sys_bytes|sys_bytes|gc_sys_bytes|heap_alloc_bytes|mcache_inuse_bytes|stack_inuse_bytes|mspan_inuse_bytes)', 'url=https:--$store.tensor.ru-metrics'), 'alloc_bytes_total'), 'name')"
      }
     ]
    },
    {
     "title": "Heap bytes before GC",
     "type": "graph",
     "description": "Количество байт в куче до ближайшего прохода сборщика мусора",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(seriesByTag('name=prometheus.go_memstats_next_gc_bytes', 'url=https:--$store.tensor.ru-metrics'), 'Heap bytes before next GC')"
      }
     ]
    },
    {
     "title": "GC duration",
     "type": "graph",
     "description": "Длительность прохода сборщика мусора ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "target": "alias(perSecond(seriesByTag('name=prometheus.go_gc_duration_seconds_sum', 'url=https:--$store.tensor.ru-metrics')), 'GC duration')"
      }
     ]
    },
    {
     "title": "Last GC",
     "type": "timeseries",
     "description": "Время последнего прохода сборщика мусора",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "targets": [
      {
       "target": "alias(perSecond(seriesByTag('name=prometheus.go_memstats_last_gc_time_seconds', 'url=https:--$store.tensor.ru-metrics')), 'last GC')"
      }
     ]
    },
    {
     "title": "GC duration quantiles",
     "type": "graph",
     "description": "Длительность прохода сборщика мусора по квантилям",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "target": "sortByName(aliasByTags(seriesByTag('name=prometheus.go_gc_duration_seconds', 'url=https:--$store.tensor.ru-metrics'), 'quantile'), false)"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 storage by projects",
     "type": "graph",
     "description": "Выделенное кол-во дискового пространства по проектам",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=prometheus.harbor_project_quota_usage_byte', 'url=https:--$store.tensor.ru-metrics'), 'project_name')"
      }
     ]
    },
    {
     "title": "Number of objects per bucket",
     "type": "graph",
     "description": "Количество объектов по бакетам",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "exclude(aliasByTags(seriesByTag('name=prometheus.minio_bucket_usage_object_total', 'cluster=$storage', 'bucket=~.*-registry', 'server=~(csr-auto-s31.*|dev-s3-stor1.*)'), 'bucket'), 'gitlab-registry')"
      }
     ]
    },
    {
     "title": "Buckets data usage",
     "type": "graph",
     "description": "Вес каждого бакета по отдельности",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "exclude(aliasByTags(seriesByTag('name=prometheus.minio_bucket_usage_total_bytes', 'bucket=~[a-zA-Z]*-registry', 'cluster=$storage', 'server=~(csr-auto-s31.*|dev-s3-stor1.*)'), 'bucket'), 'gitlab-registry-storage')"
      }
     ]
    },
    {
     "title": "Total S3 traffic sent/received",
     "type": "graph",
     "description": "Общая сводка по полученному и отправленному S3 трафику",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "target": "perSecond(sum(seriesByTag('servertype=minio', 'name=prometheus.minio_s3_traffic_received_bytes', 'cluster=$storage'), server))",
       "timeField": "@timestamp"
      },
      {
       "target": "perSecond(sum(seriesByTag('servertype=minio', 'name=prometheus.minio_s3_traffic_sent_bytes', 'cluster=$storage'), server))"
      }
     ]
    },
    {
     "title": "SysCalls read/write total",
     "type": "graph",
     "description": "Сумма системных вызовов на чтение и запись по всем хостам кластера",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "perSecond(sumSeries(seriesByTag('servertype=minio', 'name=prometheus.minio_node_syscall_read_total', 'cluster=$storage'), server))"
      },
      {
       "target": "perSecond(sumSeries(seriesByTag('servertype=minio', 'name=prometheus.minio_node_syscall_write_total', 'cluster=$storage'), server))"
      }
     ]
    },
    {
     "title": "Internode traffic ",
     "type": "graph",
     "description": "Трафик между хостами в кластере",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "perSecond(sumSeries(seriesByTag('servertype=minio', 'name=prometheus.minio_inter_node_traffic_received_bytes', 'cluster=$storage'), name))"
      },
      {
       "target": "perSecond(sumSeries(seriesByTag('servertype=minio', 'name=prometheus.minio_inter_node_traffic_sent_bytes', 'cluster=$storage'), name))"
      }
     ]
    },
    {
     "title": "S3 total requests + error requests",
     "type": "graph",
     "description": "Количество всех S3 запросов и S3 запросов, закончившихся с ошибкой",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "derivative(sum(seriesByTag('servertype=minio', 'cluster=$storage', 'name=prometheus.minio_s3_requests_total'), name))"
      },
      {
       "target": "derivative(sum(seriesByTag('servertype=minio', 'cluster=$storage', 'name=prometheus.minio_s3_requests_errors_total'), name))"
      }
     ]
    },
    {
     "title": "read/write operations with FS + cache",
     "type": "graph",
     "description": "Сумма обращений к файловой системе на чтение и запись по всем хостам кластера",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "perSecond(sumSeries(seriesByTag('servertype=minio', 'name=prometheus.minio_node_io_rchar_bytes', 'cluster=$storage'), server))"
      },
      {
       "target": "perSecond(sumSeries(seriesByTag('servertype=minio', 'name=prometheus.minio_node_io_wchar_bytes', 'cluster=$storage'), server))"
      }
     ]
    }
   ]
  }
 ]
}