{
 "title": "K8s - Namespace quotas",
 "description": "Ответственный: Новиков А.В. (Эксплуатация)",
 "tags": [
  "system",
  "k8s",
  "telegraf"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "tag_values(cluster,name=prometheus_remote_write.up)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "tag_values(namespace,cluster=$cluster,name=prometheus_remote_write.kube_namespace_labels)"
   },
   { "name": "top", "label": "Top", "query": "5,10,25,50,ALL" }
  ]
 },
 "panels": [
  {
   "title": "Requests CPU cores",
   "type": "graph",
   "description": "* Current - суммарный объем Requests всех подов данного Namespace\n* Max - максимальный объем для суммарных Requests всех подов из указанного Namespace\n* Warning - уровень предупреждения, уведомляющий о истощении ресурсов указанного Namespace на 80%\n* Critical - уровень аварии, уведомляющий о истощении ресурсов указанного Namespace на 90%",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.cpu', 'type=hard', 'namespace=$namespace'), 'Max')"
    },
    {
     "refCount": 1,
     "target": "alias(groupByTags(seriesByTag('name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=cpu', 'namespace=$namespace', 'cluster=$cluster'), 'sum', 'namespace'), 'Current')"
    },
    {
     "target": "alias(scale(#B, 0.9), 'Critacal')",
     "targetFull": "alias(scale(alias(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.cpu', 'type=hard', 'namespace=$namespace'), 'Max'), 0.9), 'Critacal')"
    },
    {
     "target": "alias(scale(#B, 0.8), 'Warning')",
     "targetFull": "alias(scale(alias(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.cpu', 'type=hard', 'namespace=$namespace'), 'Max'), 0.8), 'Warning')"
    }
   ]
  },
  {
   "title": "TOP Requested CPU cores by Pods",
   "type": "bargauge",
   "description": "Топ подов для которых выделяются ресурсы CPU (в порядке убывания объема)",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highest(sortByMaxima(aliasByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=cpu', 'cluster=$cluster', 'namespace=$namespace'), 'pod')), $top)"
    }
   ]
  },
  {
   "title": "Requests Memory",
   "type": "graph",
   "description": "* Current - суммарный объем Requests всех подов данного Namespace\n* Max - максимальный объем для суммарных Requests всех подов из указанного Namespace\n* Warning - уровень предупреждения, уведомляющий о истощении ресурсов указанного Namespace на 80%\n* Critical - уровень аварии, уведомляющий о истощении ресурсов указанного Namespace на 90%",
   "gridPos": { "h": 11, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.memory', 'type=hard', 'namespace=~${namespace:regex}'), 'Max')"
    },
    {
     "refCount": 1,
     "target": "alias(groupByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'namespace=$namespace', 'cluster=$cluster'), 'sum', 'namespace'), 'Current')"
    },
    {
     "refCount": 1,
     "target": "alias(scale(#B, 0.9), 'Critacal')",
     "targetFull": "alias(scale(alias(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.memory', 'type=hard', 'namespace=~${namespace:regex}'), 'Max'), 0.9), 'Critacal')"
    },
    {
     "target": "alias(scale(#B, 0.8), 'Warning')",
     "targetFull": "alias(scale(alias(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.memory', 'type=hard', 'namespace=~${namespace:regex}'), 'Max'), 0.8), 'Warning')"
    }
   ]
  },
  {
   "title": "TOP Requested memory by Pods, GiB",
   "type": "bargauge",
   "description": "Топ подов для которых выделяются ресурсы памяти (в порядке убывания объема)",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highest(sortByMaxima(aliasByTags(scale(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'namespace=$namespace', 'cluster=$cluster'), 9.313225746154785e-10), 'pod')), $top, 'average')"
    },
    {
     "target": "sortByMaxima(aliasByTags(grep(alias(scale(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_requests', 'resource=memory', 'namespace=$namespace', 'cluster=$cluster'), 9.313225746154785e-10), 'ALL'), '$top'), 'pod'))"
    }
   ]
  },
  {
   "title": "Limits CPU cores",
   "type": "graph",
   "description": "* Current - суммарный объем Limits всех подов данного Namespace\n* Max - максимальный объем для суммарных Limits всех подов из указанного Namespace\n* Warning - уровень предупреждения, уведомляющий о истощении ресурсов указанного Namespace на 80%\n* Critical - уровень аварии, уведомляющий о истощении ресурсов указанного Namespace на 90%",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_resourcequota', 'resource=limits.cpu', 'type=hard', 'namespace=~${namespace:regex}'), 'Max')"
    },
    {
     "refCount": 1,
     "target": "alias(groupByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'namespace=$namespace', 'cluster=$cluster'), 'sum', 'namespace'), 'Current')"
    },
    {
     "refCount": 1,
     "target": "alias(scale(#A, 0.9), 'Critacal')",
     "targetFull": "alias(scale(alias(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_resourcequota', 'resource=limits.cpu', 'type=hard', 'namespace=~${namespace:regex}'), 'Max'), 0.9), 'Critacal')"
    },
    {
     "target": "alias(scale(#A, 0.8), 'Warning')",
     "targetFull": "alias(scale(alias(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_resourcequota', 'resource=limits.cpu', 'type=hard', 'namespace=~${namespace:regex}'), 'Max'), 0.8), 'Warning')"
    }
   ]
  },
  {
   "title": "TOP Limits CPU cores by Pods",
   "type": "bargauge",
   "description": "Топ подов с максимально возможным потреблением ресурсов CPU (в порядке убывания объема)",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highest(sortByMaxima(aliasByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'namespace=$namespace', 'cluster=$cluster'), 'pod')), $top)"
    },
    {
     "target": "sortByMaxima(aliasByTags(grep(alias(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=cpu', 'namespace=$namespace', 'cluster=$cluster'), 'ALL'), '$top'), 'pod'))"
    }
   ]
  },
  {
   "title": "Limits Memory ",
   "type": "graph",
   "description": "* Current - суммарный объем Limits всех подов данного Namespace\n* Max - максимальный объем для суммарных Limits всех подов из указанного Namespace\n* Warning - уровень предупреждения, уведомляющий о истощении ресурсов указанного Namespace на 80%\n* Critical - уровень аварии, уведомляющий о истощении ресурсов указанного Namespace на 90%",
   "gridPos": { "h": 11, "w": 8, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_resourcequota', 'resource=limits.memory', 'type=hard', 'namespace=~${namespace:regex}'), 'Max')"
    },
    {
     "refCount": 1,
     "target": "alias(groupByTags(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=memory', 'namespace=$namespace', 'cluster=$cluster'), 'sum', 'namespace'), 'Current')"
    },
    {
     "refCount": 1,
     "target": "alias(scale(#A, 0.9), 'Critacal')",
     "targetFull": "alias(scale(alias(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_resourcequota', 'resource=limits.memory', 'type=hard', 'namespace=~${namespace:regex}'), 'Max'), 0.9), 'Critacal')"
    },
    {
     "target": "alias(scale(#A, 0.8), 'Warning')",
     "targetFull": "alias(scale(alias(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_resourcequota', 'resource=limits.memory', 'type=hard', 'namespace=~${namespace:regex}'), 'Max'), 0.8), 'Warning')"
    }
   ]
  },
  {
   "title": "TOP Limits memory by Pods, GiB",
   "type": "bargauge",
   "description": "Топ подов с максимально возможным потреблением ресурсов памяти (в порядке убывания объема)",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "highest(sortByMaxima(aliasByTags(scale(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=memory', 'namespace=$namespace', 'cluster=$cluster'), 9.313225746154785e-10), 'pod')), $top, 'average')"
    },
    {
     "target": "sortByMaxima(aliasByTags(grep(alias(scale(seriesByTag('job=kube-state-metrics', 'name=prometheus_remote_write.kube_pod_container_resource_limits', 'resource=memory', 'namespace=$namespace', 'cluster=$cluster'), 9.313225746154785e-10), 'ALL'), '$top'), 'pod'))"
    }
   ]
  }
 ]
}