{
 "title": "K8s - Containers",
 "description": "Ответственный: Новиков А.В. (Эксплуатация)",
 "tags": [
  "k8s",
  "telegraf",
  "system"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "tag_values(cluster,name=prometheus_remote_write.up)"
   },
   {
    "name": "labeltype",
    "label": "Label Type",
    "query": "name,instance,component,part_of"
   },
   {
    "name": "label",
    "label": "Label",
    "query": "tag_values(label_app_kubernetes_io_${labeltype:regex},cluster=${cluster:regex})"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "tag_values(namespace,cluster=${cluster:regex},label_app_kubernetes_io_${labeltype:regex}=${label:regex})"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "tag_values(pod,cluster=${cluster:regex},label_app_kubernetes_io_${labeltype:regex}=${label:regex},namespace=${namespace:regex})"
   },
   { "name": "group", "label": "Group by", "query": "container,pod" },
   { "name": "function", "label": "Function", "query": "Average,Max,Min" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByTags(grep(alias(groupByTags(movingAverage(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'pod=~${pod:regex}', 'namespace=$namespace')), '5min'), 'sum', '$group'), 'Average'), '$function'), '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(groupByTags(movingMax(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'pod=~${pod:regex}', 'namespace=$namespace')), '5min'), 'sum', '$group'), 'Max'), '$function'), '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(groupByTags(movingMin(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'name=prometheus_remote_write.container_cpu_usage_seconds_total', 'pod=~${pod:regex}', 'namespace=$namespace')), '5min'), 'sum', '$group'), 'Min'), '$function'), '$group')"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByTags(grep(alias(groupByTags(divideSeriesLists(movingAverage(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_cpu_cfs_throttled_periods_total', 'namespace=$namespace', 'container=~.+')), '5min'), #B), 'sum', '$group'), 'Average'), '$function'), '$group')",
     "targetFull": "aliasByTags(grep(alias(groupByTags(divideSeriesLists(movingAverage(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_cpu_cfs_throttled_periods_total', 'namespace=$namespace', 'container=~.+')), '5min'), grep(alias(movingAverage(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_cpu_cfs_periods_total', 'namespace=$namespace')), '5min'), 'Average'), '$function')), 'sum', '$group'), 'Average'), '$function'), '$group')"
    },
    {
     "refCount": 1,
     "target": "aliasByTags(grep(alias(groupByTags(divideSeriesLists(movingMax(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_cpu_cfs_throttled_periods_total', 'namespace=$namespace', 'container=~.+')), '5min'), #D), 'sum', '$group'), 'Max'), '$function'), '$group')",
     "targetFull": "aliasByTags(grep(alias(groupByTags(divideSeriesLists(movingMax(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_cpu_cfs_throttled_periods_total', 'namespace=$namespace', 'container=~.+')), '5min'), grep(alias(movingMax(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_cpu_cfs_periods_total', 'namespace=$namespace')), '5min'), 'Max'), '$function')), 'sum', '$group'), 'Max'), '$function'), '$group')"
    },
    {
     "refCount": 2,
     "target": "aliasByTags(grep(alias(groupByTags(divideSeriesLists(movingMin(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_cpu_cfs_throttled_periods_total', 'namespace=$namespace', 'container=~.+')), '5min'), #F), 'sum', '$group'), 'Min'), '$function'), '$group')",
     "targetFull": "aliasByTags(grep(alias(groupByTags(divideSeriesLists(movingMin(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_cpu_cfs_throttled_periods_total', 'namespace=$namespace', 'container=~.+')), '5min'), grep(alias(movingMin(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_cpu_cfs_periods_total', 'namespace=$namespace')), '5min'), 'Min'), '$function')), 'sum', '$group'), 'Min'), '$function'), '$group')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(keepLastValue(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_memory_working_set_bytes'), 1), 'sum', '$group'), '$group')"
    }
   ]
  },
  {
   "title": "Files / Sockets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(keepLastValue(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_file_descriptors'), 1), 'sum', '$group'), 1, '$group')"
    },
    {
     "target": "aliasByTags(groupByTags(keepLastValue(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_sockets'), 1), 'sum', '$group'), 1, '$group')"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_network_receive_bytes_total')), 'sum', '$group'), '5min'), 'Average'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_network_transmit_bytes_total')), 'sum', '$group'), '5min'), 'Average'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_network_receive_bytes_total')), 'sum', '$group'), '5min'), 'Max'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_network_transmit_bytes_total')), 'sum', '$group'), '5min'), 'Max'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_network_receive_bytes_total')), 'sum', '$group'), '5min'), 'Min'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_network_transmit_bytes_total')), 'sum', '$group'), '5min'), 'Min'), '$function'), 1, '$group')"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_reads_total')), 'sum', '$group'), '5min'), 'Average'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_writes_total')), 'sum', '$group'), '5min'), 'Average'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_reads_total')), 'sum', '$group'), '5min'), 'Max'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_writes_total')), 'sum', '$group'), '5min'), 'Max'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_reads_total')), 'sum', '$group'), '5min'), 'Min'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_writes_total')), 'sum', '$group'), '5min'), 'Min'), '$function'), 1, '$group')"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_reads_bytes_total')), 'sum', '$group'), '5min'), 'Average'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_writes_bytes_total')), 'sum', '$group'), '5min'), 'Average'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_reads_bytes_total')), 'sum', '$group'), '5min'), 'Max'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_writes_bytes_total')), 'sum', '$group'), '5min'), 'Max'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_reads_bytes_total')), 'sum', '$group'), '5min'), 'Min'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_writes_bytes_total')), 'sum', '$group'), '5min'), 'Min'), '$function'), 1, '$group')"
    }
   ]
  },
  {
   "title": "Processes / Threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(keepLastValue(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_processes'), 1), 'sum', '$group'), 1, '$group')"
    },
    {
     "target": "aliasByTags(groupByTags(keepLastValue(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_threads'), 1), 'sum', '$group'), 1, '$group')"
    }
   ]
  },
  {
   "title": "Packets  RX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_network_receive_packets_total')), 'sum', '$group'), '5min'), 'Average'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_network_receive_packets_total')), 'sum', '$group'), '5min'), 'Max'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_network_receive_packets_total')), 'sum', '$group'), '5min'), 'Min'), '$function'), 1, '$group')"
    }
   ]
  },
  {
   "title": "Packets TX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(grep(alias(movingAverage(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_network_transmit_packets_total')), 'sum', '$group'), '5min'), 'Average'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMax(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_network_transmit_packets_total')), 'sum', '$group'), '5min'), 'Max'), '$function'), 1, '$group')"
    },
    {
     "target": "aliasByTags(grep(alias(movingMin(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_network_transmit_packets_total')), 'sum', '$group'), '5min'), 'Min'), '$function'), 1, '$group')"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(scale(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_start_time_seconds'), 1000), 'min', '$group'), 'pod')"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(scale(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'namespace=$namespace', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_start_time_seconds'), 1000), 'min', '$group'), 'pod')"
    }
   ]
  }
 ]
}