{
 "title": "K8s - Nodes - Usage by pods",
 "description": "Ответственный: Новиков А.В. (Эксплуатация)",
 "tags": [
  "k8s",
  "telegraf",
  "system"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "tag_values(cluster,name=prometheus_remote_write.up)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "tag_values(role,name=prometheus_remote_write.kube_node_role,cluster=${cluster:regex})"
   },
   {
    "name": "node_name",
    "label": "Node",
    "query": "tag_values(node,cluster=${cluster:regex},role=~${role:regex})"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "tag_values(pod,cluster=${cluster:regex},node_name=${node_name:regex})"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (Top 10)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByTags(highestAverage(movingAverage(transformNull(groupByTags(perSecond(seriesByTag('job=cAdvisor', 'pod=~${pod:regex}', 'cluster=$cluster', 'name=prometheus_remote_write.container_cpu_usage_seconds_total')), 'sum', 'pod'), 0), '5min'), 10), 'pod')"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "removeZeroSeries(aliasByTags(movingAverage(groupByTags(divideSeriesLists(transformNull(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'instance=$node_name', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_cpu_cfs_throttled_periods_total')), 0), #B), 'sum', 'pod'), '5min'), 'pod'))",
     "targetFull": "removeZeroSeries(aliasByTags(movingAverage(groupByTags(divideSeriesLists(transformNull(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'instance=$node_name', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_cpu_cfs_throttled_periods_total')), 0), transformNull(perSecond(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'instance=$node_name', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_cpu_cfs_periods_total')), 0)), 'sum', 'pod'), '5min'), 'pod'))"
    }
   ]
  },
  {
   "title": "Memory Usage (Top 10)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(highestMax(movingAverage(groupByTags(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'instance=$node_name', 'name=prometheus_remote_write.container_memory_working_set_bytes', 'pod=~${pod:regex}'), 'sum', 'pod'), '5min'), 10), 'pod')"
    }
   ]
  },
  {
   "title": "Network Bytes (Top 10)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(highestCurrent(movingAverage(groupByTags(transformNull(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_network_receive_bytes_total', 'pod=~${pod:regex}', 'cluster=$cluster', 'instance=$node_name', 'namespace!=~(kube-system|aci-containers-system|system-monitoring)')), 0), 'sum', 'pod'), '5min'), 10), 1, 'pod'), '.*receive[^.]*', 'RX')"
    },
    {
     "target": "aliasSub(aliasByTags(highestCurrent(movingAverage(groupByTags(transformNull(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_network_transmit_bytes_total', 'pod=~${pod:regex}', 'cluster=$cluster', 'instance=$node_name', 'namespace!=~(kube-system|aci-containers-system|system-monitoring)')), 0), 'sum', 'pod'), '5min'), 10), 1, 'pod'), '.*transmit[^.]*', 'TX')"
    }
   ]
  },
  {
   "title": "Network Packets (Top 10)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(highestCurrent(movingAverage(groupByTags(transformNull(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_network_receive_packets_total', 'pod=~${pod:regex}', 'cluster=$cluster', 'instance=$node_name', 'namespace!=~(kube-system|aci-containers-system|system-monitoring)')), 0), 'sum', 'pod'), '5min'), 10), 1, 'pod'), '.*receive[^.]*', 'RX')"
    },
    {
     "target": "aliasSub(aliasByTags(highestCurrent(movingAverage(groupByTags(transformNull(perSecond(seriesByTag('job=cAdvisor', 'name=prometheus_remote_write.container_network_transmit_packets_total', 'pod=~${pod:regex}', 'cluster=$cluster', 'instance=$node_name', 'namespace!=~(kube-system|aci-containers-system|system-monitoring)')), 0), 'sum', 'pod'), '5min'), 10), 1, 'pod'), '.*transmit[^.]*', 'TX')"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(removeZeroSeries(highestMax(movingAverage(perSecond(groupByTags(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'instance=$node_name', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_reads_total'), 'sum', 'pod')), '5min'), 10)), 1, 'pod'), '.*reads[^.]*', 'READ')"
    },
    {
     "target": "aliasSub(aliasByTags(removeZeroSeries(highestMax(movingAverage(perSecond(groupByTags(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'instance=$node_name', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_writes_total'), 'sum', 'pod')), '5min'), 10)), 1, 'pod'), '.*writes[^.]*', 'WRITE')"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(highestMax(removeZeroSeries(movingAverage(perSecond(groupByTags(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'instance=$node_name', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_reads_bytes_total'), 'sum', 'pod')), '5min')), 10), 1, 'pod'), '.*reads[^.]*', 'READ')"
    },
    {
     "target": "aliasSub(aliasByTags(highestMax(removeZeroSeries(movingAverage(perSecond(groupByTags(seriesByTag('job=cAdvisor', 'cluster=$cluster', 'instance=$node_name', 'pod=~${pod:regex}', 'name=prometheus_remote_write.container_fs_writes_bytes_total'), 'sum', 'pod')), '5min')), 10), 1, 'pod'), '.*writes[^.]*', 'WRITE')"
    }
   ]
  }
 ]
}