{
 "title": "K8s - NFS",
 "description": "Ответственный: Лошкарев Д.Г. (АЦОД)",
 "tags": [ "telegraf" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "tag_values(ha_cluster)" },
   {
    "name": "host",
    "query": "tag_values(host,ha_cluster=$cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Systemd Units",
   "type": "table",
   "description": "Отображает статус сервисов, отвечающих за работу HA кластера.\nСервис nfs-server в любой момент времени должен быть запущен только на одной из нод.",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "seriesByTag('name=node_systemd_unit_state.gauge', '_name=~((corosync|pacemaker|sbd|prometheus|nfs-server).*)', 'state=active', 'ha_cluster=$cluster')"
    }
   ]
  },
  {
   "title": "Active NFS Resources",
   "type": "stat",
   "description": "Состояние ресурсов NFS",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(divideSeriesLists(groupByTags(groupByTags(seriesByTag('name=ha_cluster_pacemaker_resources.gauge', 'ha_cluster=$cluster', 'status=active'), 'sum', 'resource', 'host'), 'max', 'resource'), #A), 'resource', 'node')",
     "targetFull": "aliasByTags(divideSeriesLists(groupByTags(groupByTags(seriesByTag('name=ha_cluster_pacemaker_resources.gauge', 'ha_cluster=$cluster', 'status=active'), 'sum', 'resource', 'host'), 'max', 'resource'), groupByTags(groupByTags(seriesByTag('name=ha_cluster_pacemaker_resources.gauge', 'ha_cluster=$cluster'), 'count', 'resource', 'node'), 'count', 'resource')), 'resource', 'node')"
    }
   ]
  },
  {
   "title": "Faulty Node Statuses",
   "type": "stat",
   "description": "Список \"плохих\" состояний нод NFS.\n\n0% - ни одна нода не находится в указанном состоянии\n\n50% - половина нод находится в указанном состоянии\n\n100% - все ноды находятся в указанном состоянии",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(divideSeriesLists(groupByTags(seriesByTag('name=ha_cluster_pacemaker_nodes.gauge', 'ha_cluster=$cluster', 'host=~${host:regex}', 'status!=~(dc|online|expected_up)'), 'sum', 'status'), #A), 'status')",
     "targetFull": "aliasByTags(divideSeriesLists(groupByTags(seriesByTag('name=ha_cluster_pacemaker_nodes.gauge', 'ha_cluster=$cluster', 'host=~${host:regex}', 'status!=~(dc|online|expected_up)'), 'sum', 'status'), groupByTags(seriesByTag('name=ha_cluster_pacemaker_nodes.gauge', 'ha_cluster=$cluster', 'host=~${host:regex}', 'status!=~(dc|online|expected_up)'), 'count', 'status')), 'status')"
    }
   ]
  },
  {
   "title": "NFS Share Disk Usage (EXT4/XFS)",
   "type": "bargauge",
   "description": "Утилизация диска, используемого для NFS Share",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('name=system.disk.used_percent', 'ha_cluster=$cluster', 'path!=-boot', 'path!=-', 'path!=~-var-lib.*'), 'max', ''), 'name')"
    }
   ]
  },
  {
   "title": "Basic Resource Usage",
   "type": "bargauge",
   "description": "Утилизация CPU, RAM,SWAP",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=system.cpu.usage_active', 'cpu=cpu-total', 'host=~${host:regex}'), 'host'), '.unix.tensor.ru', ' CPU')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=system.mem.used_percent', 'host=~${host:regex}'), 'host'), '.unix.tensor.ru', ' Memory')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=system.swap.used_percent', 'host=~${host:regex}'), 'host'), '.unix.tensor.ru', ' Swap')"
    }
   ]
  },
  {
   "title": "Disk Read Latency",
   "type": "graph",
   "description": "Задержки на чтение с диска",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "exclude(exclude(aliasSub(aliasByTags(divideSeriesLists(perSecond(seriesByTag('host=~${host:regex}', 'name=node_disk_read_time_seconds_total.counter')), #B), 'host', 'device'), '.unix.tensor.ru', ''), 'dm-.*'), 'sr.*')",
     "targetFull": "exclude(exclude(aliasSub(aliasByTags(divideSeriesLists(perSecond(seriesByTag('host=~${host:regex}', 'name=node_disk_read_time_seconds_total.counter')), offset(perSecond(seriesByTag('host=~${host:regex}', 'name=node_disk_reads_completed_total.counter')), 0.0001)), 'host', 'device'), '.unix.tensor.ru', ''), 'dm-.*'), 'sr.*')"
    }
   ]
  },
  {
   "title": "Disk Write Latency",
   "type": "graph",
   "description": "Задержки на запись на диск",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "exclude(exclude(aliasSub(aliasByTags(divideSeriesLists(perSecond(seriesByTag('host=~${host:regex}', 'name=node_disk_write_time_seconds_total.counter')), #B), 'host', 'device'), '.unix.tensor.ru', ''), 'dm-.*'), 'sr.*')",
     "targetFull": "exclude(exclude(aliasSub(aliasByTags(divideSeriesLists(perSecond(seriesByTag('host=~${host:regex}', 'name=node_disk_write_time_seconds_total.counter')), offset(perSecond(seriesByTag('host=~${host:regex}', 'name=node_disk_writes_completed_total.counter')), 0.0001)), 'host', 'device'), '.unix.tensor.ru', ''), 'dm-.*'), 'sr.*')"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "description": "Утилизация системы ",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=system.system.load1', 'host=~${host:regex}'), 'host'), 0)"
    }
   ]
  },
  {
   "title": "Network Traffic Bytes",
   "type": "graph",
   "description": "Утилизация сети в байтах",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(aliasByMetric(perSecond(seriesByTag('name=~system.net.bytes.*', 'host=~${host:regex}'))), 'host', 'name'), '.unix.tensor.ru.system.net.bytes_', '.')"
    }
   ]
  },
  {
   "title": "Network Traffic Packets",
   "type": "graph",
   "description": "Утилизация сети в пакетах",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 15 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(aliasByMetric(perSecond(seriesByTag('name=~system.net.packets_*', 'host=~${host:regex}'))), 'host', 'device', 'name'), '.unix.tensor.ru..system.net.packets_', '.')"
    }
   ]
  },
  { "title": "HA Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Faulty Corosync Rings",
   "type": "stat",
   "description": "-",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "groupByTags(seriesByTag('name=ha_cluster_corosync_ring_errors.gauge', 'ha_cluster=$cluster'), 'max', '')"
    }
   ]
  },
  {
   "title": "Node statuses over time",
   "type": "graph",
   "description": "Статус нод кластера",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(groupByTags(seriesByTag('name=ha_cluster_pacemaker_nodes.gauge', 'ha_cluster=$cluster'), 'sum', 'status', 'host'), 'max', 'status'), 'status')"
    }
   ]
  },
  {
   "title": "Resource statuses over time",
   "type": "graph",
   "description": "Статус ресурсов кластера",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(groupByTags(seriesByTag('name=ha_cluster_pacemaker_resources.gauge', 'ha_cluster=$cluster'), 'sum', 'status', 'host'), 'max', 'status'), 'status')"
    }
   ]
  },
  {
   "title": "NFS Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFSd Packets",
     "type": "graph",
     "description": "Количество передаваемых пакетов в NFS",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "pps", "label": "Packets" }
     ],
     "targets": [
      {
       "target": "aliasByTags(groupByTags(perSecond(seriesByTag('name=node_nfsd_packets_total.counter', 'ha_cluster=$cluster')), 'sum', 'proto'), 'proto')"
      }
     ]
    },
    {
     "title": "NFSd Disk Read / Write",
     "type": "graph",
     "description": "Количество операций NFS",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "target": "perSecond(groupByTags(seriesByTag('name=~node_nfsd_disk_bytes_(written|read)_total.counter', 'ha_cluster=$cluster'), 'sum', 'name'))"
      }
     ]
    },
    {
     "title": "NFSd RPC",
     "type": "graph",
     "description": "Количество вызванных процедур",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      {
       "format": "short",
       "label": "Counter errors (-) / success (+)"
      }
     ],
     "targets": [
      {
       "target": "alias(groupByTags(perSecond(seriesByTag('name=node_nfsd_server_rpcs_total.counter', 'ha_cluster=$cluster')), 'sum', ''), 'rpc')"
      },
      {
       "target": "aliasByTags(groupByTags(perSecond(seriesByTag('name=node_nfsd_rpc_errors_total.counter', 'ha_cluster=$cluster')), 'sum', 'error'), 'error')"
      }
     ]
    },
    {
     "title": "NFSd v3 NFSd Requests by Method",
     "type": "graph",
     "description": "Кол-во вызванных методов NFS",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "target": "aliasByTags(groupByTags(perSecond(seriesByTag('name=node_nfsd_requests_total.counter', 'ha_cluster=$cluster', 'proto=3')), 'sum', 'method'), 'method')"
      }
     ]
    }
   ]
  },
  {
   "title": "$host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "System Uptime",
     "type": "stat",
     "description": "Время жизни сервера ",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=system.system.uptime', 'host=$host'), 'host')"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "stat",
     "description": "Кол-во RAM",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('name=system.mem.total', 'host=$host'), 'host')"
      }
     ]
    },
    {
     "type": "bargauge",
     "description": "Общее состояние системы",
     "gridPos": { "h": 6, "w": 5, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias(seriesByTag('name=system.cpu.usage_active', 'cpu=cpu-total', 'host=$host'), 'CPU active')"
      },
      {
       "target": "alias(seriesByTag('name=system.mem.used_percent', 'host=$host'), 'Memory used')"
      },
      {
       "target": "alias(seriesByTag('name=system.swap.used_percent', 'host=$host'), 'Swap used')"
      }
     ]
    },
    {
     "title": "Disk Space Used Basic(EXT4/XFS)",
     "type": "bargauge",
     "description": "Количество занятого дискового пространства",
     "gridPos": { "h": 6, "w": 7, "x": 11, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('name=system.disk.used_percent', 'host=$host'), 'path'), '-', '/')"
      }
     ]
    },
    {
     "title": "Disk Space Used Basic(EXT4/XFS)",
     "type": "timeseries",
     "description": "Количество занятого дискового пространства",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('name=system.disk.used_percent', 'host=$host'), 'path'), '-', '/')"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Кол-во ядер на сервере ",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "seriesByTag('name=system.system.n_cpus', 'host=$host')"
      }
     ]
    },
    {
     "title": "CPU IOwait",
     "type": "stat",
     "description": "Загруженность CPU",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "seriesByTag('name=system.cpu.usage_iowait', 'cpu=cpu-total', 'host=$host')"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "description": "Загруженность системы",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasByTags(seriesByTag('name=system.system.load1', 'host=$host'), 'host'), 0)"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "description": "Утилизация CPU",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasByTags(groupByTags(exclude(seriesByTag('name=~system.cpu.*', 'cpu=cpu-total', 'host=$host'), 'idle|active'), 'sum', 'host'), 'host'), 0)"
      }
     ]
    },
    {
     "title": "Memory Usage History",
     "type": "graph",
     "description": "Утилизация RAM",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasByTags(divideSeries(diffSeries(seriesByTag('host=$host', 'name=system.mem.total'), #A), #C), 'host'), 0)",
       "targetFull": "aliasByNode(aliasByTags(divideSeries(diffSeries(seriesByTag('host=$host', 'name=system.mem.total'), aliasByMetric(seriesByTag('host=$host', 'name=system.mem.available'))), aliasByMetric(seriesByTag('host=$host', 'name=system.mem.total'))), 'host'), 0)"
      }
     ]
    },
    {
     "title": "Disk Read Latency",
     "type": "graph",
     "description": "Задержки на чтение с диска",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "target": "exclude(exclude(aliasByTags(divideSeriesLists(perSecond(seriesByTag('host=~${host:regex}', 'name=node_disk_read_time_seconds_total.counter')), #B), 'device'), 'dm-.*'), 'sr.*')",
       "targetFull": "exclude(exclude(aliasByTags(divideSeriesLists(perSecond(seriesByTag('host=~${host:regex}', 'name=node_disk_read_time_seconds_total.counter')), offset(perSecond(seriesByTag('host=~${host:regex}', 'name=node_disk_reads_completed_total.counter')), 0.0001)), 'device'), 'dm-.*'), 'sr.*')"
      }
     ]
    },
    {
     "title": "Disk Write Latency",
     "type": "graph",
     "description": "Задержки на запись на диск",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "target": "exclude(exclude(aliasByTags(divideSeriesLists(perSecond(seriesByTag('host=~${host:regex}', 'name=node_disk_write_time_seconds_total.counter')), #B), 'device'), 'dm-.*'), 'sr.*')",
       "targetFull": "exclude(exclude(aliasByTags(divideSeriesLists(perSecond(seriesByTag('host=~${host:regex}', 'name=node_disk_write_time_seconds_total.counter')), offset(perSecond(seriesByTag('host=~${host:regex}', 'name=node_disk_writes_completed_total.counter')), 0.0001)), 'device'), 'dm-.*'), 'sr.*')"
      }
     ]
    },
    {
     "title": "Disk Busy",
     "type": "graph",
     "description": "Загруженность дисковой системы",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('name=node_disk_io_time_seconds_total.counter', 'host=~${host:regex}', 'device!=~dm-.*')), 'host', 'device'), 4)"
      }
     ]
    },
    {
     "title": "Disk R/W IOps",
     "type": "graph",
     "description": "Кол-во операций ввода/вывода",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasByTags(groupByTags(perSecond(seriesByTag('name=~system.diskio.(reads|writes)', 'host=$host')), 'sum', 'name', 'host'), 'name', 'host'), 2)"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "graph",
     "description": "Кол-во операций ввода/вывода",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(aliasByTags(groupByTags(perSecond(seriesByTag('name=~system.diskio.io_time', 'host=$host')), 'sum', 'host'), 'host'), 0)"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "graph",
     "description": "Операции ввода/вывода в мегабайтах ",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "aliasByNode(perSecond(groupByTags(seriesByTag('name=~system.diskio.(read|write)_bytes', 'host=$host'), 'sum', 'name', 'host')), 2)"
      }
     ]
    },
    {
     "title": "Network Traffic Bytes",
     "type": "graph",
     "description": "Утилизация сети в байтах",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(perSecond(seriesByTag('name=~system.net.bytes.*', 'host=$host')))"
      }
     ]
    },
    {
     "title": "Network Traffic Packets",
     "type": "graph",
     "description": "Утилизация сети в пакетах",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(perSecond(seriesByTag('name=~system.net.packets_*', 'host=$host')))"
      }
     ]
    }
   ]
  }
 ]
}