{
 "title": "K8s - Cluster",
 "description": "Ответственный: Новиков А.В. (Эксплуатация)",
 "tags": [
  "bosun",
  "инциденты",
  "k8s",
  "system",
  "scripts"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "tag_values(cluster,name=prometheus_remote_write.up)"
   }
  ]
 },
 "panels": [
  {
   "title": "Control Plane Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sum(keepLastValue(seriesByTag('job=keepalived', 'cluster=$cluster', 'name=prometheus_remote_write.keepalived_up'), 5)), 'Keepalived')"
    },
    {
     "target": "alias(sum(keepLastValue(seriesByTag('job=haproxy', 'cluster=$cluster', 'name=prometheus_remote_write.up'), 5)), 'HA Proxy')"
    },
    {
     "target": "alias(sum(keepLastValue(seriesByTag('job=etcd', 'cluster=$cluster', 'name=prometheus_remote_write.up'), 5)), 'Etcd')"
    },
    {
     "target": "alias(sum(keepLastValue(seriesByTag('job=kubernetes-apiservers', 'cluster=$cluster', 'name=prometheus_remote_write.up'), 5)), 'Kube API Server')"
    },
    {
     "target": "alias(sum(keepLastValue(seriesByTag('job=kubernetes-controller-managers', 'cluster=$cluster', 'name=prometheus_remote_write.up'), 5)), 'Kube Controller Manager')"
    },
    {
     "target": "alias(sum(keepLastValue(seriesByTag('job=kubernetes-schedulers', 'cluster=$cluster', 'name=prometheus_remote_write.up'), 5)), 'Kube Scheduler')"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sum(keepLastValue(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_node_status_condition', 'condition=Ready', 'status!=true'), 1)), 'Unready')"
    },
    {
     "target": "aliasByTags(groupByTags(keepLastValue(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_node_status_condition', 'condition!=Ready', 'status=true'), 1), 'sum', 'condition'), 'condition')"
    },
    {
     "target": "alias(sum(keepLastValue(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.kube_node_spec_unschedulable'), 1)), 'Unschedulable')"
    }
   ]
  },
  {
   "title": "Pod - Phase",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_pod_status_phase', 'phase!=~(Running|Succeeded|Pending)'), 'sum', 'phase'), 'phase')"
    },
    {
     "target": "aliasByTags(groupByTags(movingMin(transformNull(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_pod_status_phase', 'phase=Pending'), 0), '5min'), 'sum', 'phase'), 'phase')"
    }
   ]
  },
  {
   "title": "API Delays",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(aliasSub(divideSeriesLists(perSecond(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_sum', 'subresource!=~(log|exec|attach)', 'verb=~(GET|LIST)')), #B), '\\)', ''), 'max', 'verb'), 'verb')",
     "targetFull": "aliasByTags(groupByTags(aliasSub(divideSeriesLists(perSecond(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_sum', 'subresource!=~(log|exec|attach)', 'verb=~(GET|LIST)')), perSecond(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_count', 'subresource!=~(log|exec|attach)', 'verb=~(GET|LIST)'))), '\\)', ''), 'max', 'verb'), 'verb')"
    }
   ]
  },
  {
   "title": "Инциденты",
   "type": "bosun-grafana7-panel",
   "gridPos": { "h": 11, "w": 11, "x": 12, "y": 0 },
   "targets": [
    { "requestFilter": "filter=hasTag:vision=*k8s*" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(divideSeriesLists(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode!=idle')), 'sum', 'node_name'), '5min'), #B), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(divideSeriesLists(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node', 'mode!=idle')), 'sum', 'node_name'), '5min'), movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_cpu_seconds_total_by_node')), 'sum', 'node_name'), '5min')), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(movingAverage(offset(scale(divideSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_memory_MemAvailable_bytes'), #B), -1), 1), '5min'), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(movingAverage(offset(scale(divideSeriesLists(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_memory_MemAvailable_bytes'), seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_memory_MemTotal_bytes')), -1), 1), '5min'), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "LA/core",
   "type": "graph",
   "description": "Load Average divided by count of CPU cores",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(divideSeriesLists(sortByName(aliasByTags(movingAverage(seriesByTag('job=node-exporter', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.node_load1'), '5min'), 'node_name'), true, false), #B), 'node_name')",
     "targetFull": "aliasByTags(divideSeriesLists(sortByName(aliasByTags(movingAverage(seriesByTag('job=node-exporter', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.node_load1'), '5min'), 'node_name'), true, false), sortByName(aliasByTags(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=${cluster:regex}', 'name=~prometheus_remote_write.kube_node_status_(allocatable|capacity)', 'resource=cpu'), 'max', 'node'), 'node'), true, false)), 'node_name')"
    }
   ]
  },
  {
   "title": "Pods Running/Capacity",
   "type": "graph",
   "description": "Pods running count divided by node's maximum pods value",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(divideSeriesLists(keepLastValue(seriesByTag('job=kubernetes-nodes', 'cluster=~${cluster:regex}', 'name=prometheus_remote_write.kubelet_running_pods'), 5), #B), 'node_name'), true, false)",
     "targetFull": "sortByName(aliasByTags(divideSeriesLists(keepLastValue(seriesByTag('job=kubernetes-nodes', 'cluster=~${cluster:regex}', 'name=prometheus_remote_write.kubelet_running_pods'), 5), aliasByTags(keepLastValue(seriesByTag('job=kube-state-metrics', 'cluster=~${cluster:regex}', 'name=prometheus_remote_write.kube_node_status_capacity', 'resource=pods'), 5), 'node')), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "Network Traffic (bytes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByTags(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_receive_bytes_total', 'cluster=$cluster', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '5min'), 1, 'node_name'), '.*receive[^.]*', 'RX'), true, false)"
    },
    {
     "target": "sortByName(aliasSub(aliasByTags(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_transmit_bytes_total', 'cluster=$cluster', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '5min'), 1, 'node_name'), '.*transmit[^.]*', 'TX'), true, false)"
    }
   ]
  },
  {
   "title": "Network Traffic (packets)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByTags(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_receive_packets_total', 'cluster=$cluster', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '5min'), 1, 'node_name'), '.*receive[^.]*', 'RX'), true, false)"
    },
    {
     "target": "sortByName(aliasSub(aliasByTags(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'name=prometheus_remote_write.node_network_transmit_packets_total', 'cluster=$cluster', 'device=~(bond0|ens192)')), 'sum', 'node_name'), '5min'), 1, 'node_name'), '.*transmit[^.]*', 'TX'), true, false)"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "yaxes": [
    { "format": "op/s" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(diffSeriesLists(movingAverage(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_disk_writes_completed_total')), '5min'), #B), 'max', 'node_name', 'device'), 'node_name', 'device'), true, false)",
     "targetFull": "sortByName(aliasByTags(groupByTags(diffSeriesLists(movingAverage(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_disk_writes_completed_total')), '5min'), scale(movingAverage(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_disk_reads_completed_total')), '5min'), -1)), 'max', 'node_name', 'device'), 'node_name', 'device'), true, false)"
    }
   ]
  },
  {
   "title": "Disk Busy",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(scale(movingAverage(groupByTags(perSecond(seriesByTag('job=node-exporter', 'cluster=$cluster', 'name=prometheus_remote_write.node_disk_io_time_seconds_total')), 'max', 'node_name', 'device'), '5min'), 100), 'node_name', 'device')"
    }
   ]
  },
  {
   "title": "Pool Resource Allocation",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 11 },
   "targets": [
    {
     "refCount": 3,
     "target": "aliasByTags(divideSeriesLists(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_requests', 'resource=cpu'), #B), 'pool', 'resource')",
     "targetFull": "aliasByTags(divideSeriesLists(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_requests', 'resource=cpu'), seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_allocatable', 'resource=cpu')), 'pool', 'resource')"
    },
    {
     "refCount": 3,
     "target": "aliasByTags(divideSeriesLists(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_requests', 'resource=memory'), #D), 'pool', 'resource')",
     "targetFull": "aliasByTags(divideSeriesLists(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_requests', 'resource=memory'), seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_allocatable', 'resource=memory')), 'pool', 'resource')"
    },
    {
     "refCount": 3,
     "target": "aliasByTags(divideSeriesLists(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_requests', 'resource=pods'), #F), 'pool', 'resource')",
     "targetFull": "aliasByTags(divideSeriesLists(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_requests', 'resource=pods'), seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_allocatable', 'resource=pods')), 'pool', 'resource')"
    },
    {
     "refCount": 3,
     "target": "aliasByTags(divideSeriesLists(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_requests', 'resource=ephemeral_storage'), #H, 0), 'pool', 'resource')",
     "targetFull": "aliasByTags(divideSeriesLists(seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_requests', 'resource=ephemeral_storage'), seriesByTag('cluster=$cluster', 'name=prometheus_remote_write.kube_pool_status_allocatable', 'resource=ephemeral_storage'), 0), 'pool', 'resource')"
    },
    {
     "refCount": 4,
     "target": "aliasByTags(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_node_role'), 'sum', 'role'), 'role', 1)"
    }
   ]
  },
  {
   "title": "Prometheus config status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=prometheus_remote_write.prometheus_config_last_reload_successful', 'cluster=${cluster:regex}'), 'service')"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "graph",
   "description": "Metrics per second sent to OSM",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(movingAverage(perSecond(seriesByTag('name=~internal_gather.metrics_gathered', 'host=~k8s-${cluster:regex}\\.cluster', 'input=http_listener_v2')), '5min'), 'sum', 'category'), 'category')"
    }
   ]
  },
  {
   "title": "NGINX Ingress HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByTags(movingAverage(divideSeriesLists(removeZeroSeries(perSecond(groupByTags(seriesByTag('job=ingress-nginx', 'cluster=$cluster', 'name=prometheus_remote_write.nginx_ingress_controller_requests', 'status=~([45]..)'), 'sum', 'status'))), #B), '5min'), 'status')",
     "targetFull": "aliasByTags(movingAverage(divideSeriesLists(removeZeroSeries(perSecond(groupByTags(seriesByTag('job=ingress-nginx', 'cluster=$cluster', 'name=prometheus_remote_write.nginx_ingress_controller_requests', 'status=~([45]..)'), 'sum', 'status'))), removeZeroSeries(perSecond(sum(seriesByTag('job=ingress-nginx', 'cluster=$cluster', 'name=prometheus_remote_write.nginx_ingress_controller_requests'))))), '5min'), 'status')"
    }
   ]
  },
  {
   "title": "Containers Restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasSub(aliasSub(aliasSub(aliasByTags(offsetToZero(groupByTags(seriesByTag('name=prometheus_remote_write.kube_pod_container_status_restarts_custom_total', 'cluster=$cluster', 'job=kube-state-metrics', 'label_k8s_tensor_ru_ns_type=~(system|application)'), 'sum', 'namespace', 'pod', 'node', 'container')), 'namespace', 'pod', 'container', 'node'), '^', 'NS:$1'), '^([^.]+).', '$1 POD:'), '^([^.]+).', '$1 CTR:'), '^([^.]+).', '$1 NODE:'), false)"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 17 },
   "targets": [
    {
     "refCount": 4,
     "target": "aliasByTags(offset(divideSeriesLists(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.cpu', 'type=used'), #B), 0.00001), 'namespace', 'resource')",
     "targetFull": "aliasByTags(offset(divideSeriesLists(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.cpu', 'type=used'), seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.cpu', 'type=hard')), 0.00001), 'namespace', 'resource')"
    },
    {
     "refCount": 4,
     "target": "aliasByTags(offset(divideSeriesLists(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.memory', 'type=used'), #D), 0.00001), 'namespace', 'resource')",
     "targetFull": "aliasByTags(offset(divideSeriesLists(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.memory', 'type=used'), seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.memory', 'type=hard')), 0.00001), 'namespace', 'resource')"
    },
    {
     "refCount": 4,
     "target": "aliasByTags(offset(divideSeriesLists(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=limits.cpu', 'type=used'), #F), 0.00001), 'namespace', 'resource')",
     "targetFull": "aliasByTags(offset(divideSeriesLists(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=limits.cpu', 'type=used'), seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=limits.cpu', 'type=hard')), 0.00001), 'namespace', 'resource')"
    },
    {
     "refCount": 4,
     "target": "aliasByTags(offset(divideSeriesLists(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=limits.memory', 'type=used'), #H), 0.00001), 'namespace', 'resource')",
     "targetFull": "aliasByTags(offset(divideSeriesLists(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=limits.memory', 'type=used'), seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=limits.memory', 'type=hard')), 0.00001), 'namespace', 'resource')"
    },
    {
     "refCount": 4,
     "target": "aliasByTags(offset(divideSeriesLists(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=persistentvolumeclaims', 'type=used'), #J), 0.00001), 'namespace', 'resource')",
     "targetFull": "aliasByTags(offset(divideSeriesLists(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=persistentvolumeclaims', 'type=used'), seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=persistentvolumeclaims', 'type=hard')), 0.00001), 'namespace', 'resource')"
    },
    {
     "refCount": 5,
     "target": "aliasByTags(offset(divideSeriesLists(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.storage', 'type=used'), #L), 0.00001), 'namespace', 'resource')",
     "targetFull": "aliasByTags(offset(divideSeriesLists(seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.storage', 'type=used'), seriesByTag('job=kube-state-metrics', 'cluster=$cluster', 'name=prometheus_remote_write.kube_resourcequota', 'resource=requests.storage', 'type=hard')), 0.00001), 'namespace', 'resource')"
    }
   ]
  }
 ]
}