{
 "title": "K8s - Cluster - Control plane",
 "description": "Ответственный: Новиков А.В. (Эксплуатация)",
 "tags": [
  "telegraf",
  "k8s",
  "system"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "tag_values(cluster,name=prometheus_remote_write.up)"
   }
  ]
 },
 "panels": [
  { "title": "Keepalived & HAProxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Keepalived Up",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sum(movingMax(seriesByTag('job=keepalived', 'name=prometheus_remote_write.keepalived_up', 'cluster=$Cluster'), '5min'))"
    }
   ]
  },
  {
   "title": "Keepalived Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByTags(sumSeries(keepLastValue(seriesByTag('job=keepalived', 'name=prometheus_remote_write.keepalived_up', 'node_name=~.+-m(aster)?1', 'cluster=$Cluster'), 5), #A), 'node_name')",
     "targetFull": "aliasByTags(sumSeries(keepLastValue(seriesByTag('job=keepalived', 'name=prometheus_remote_write.keepalived_up', 'node_name=~.+-m(aster)?1', 'cluster=$Cluster'), 5), groupByTags(keepLastValue(seriesByTag('job=keepalived', 'name=prometheus_remote_write.keepalived_vrrp_become_master', 'node_name=~.+-m(aster)?1', 'cluster=$Cluster', 'state=MASTER'), 5), 'last', 'node_name')), 'node_name')"
    },
    {
     "refCount": 1,
     "target": "aliasByTags(sumSeries(keepLastValue(seriesByTag('job=keepalived', 'name=prometheus_remote_write.keepalived_up', 'node_name=~.+-m(aster)?2', 'cluster=$Cluster'), 5), #B), 'node_name')",
     "targetFull": "aliasByTags(sumSeries(keepLastValue(seriesByTag('job=keepalived', 'name=prometheus_remote_write.keepalived_up', 'node_name=~.+-m(aster)?2', 'cluster=$Cluster'), 5), groupByTags(keepLastValue(seriesByTag('job=keepalived', 'name=prometheus_remote_write.keepalived_vrrp_become_master', 'node_name=~.+-m(aster)?2', 'cluster=$Cluster', 'state=MASTER'), 5), 'last', 'node_name')), 'node_name')"
    },
    {
     "refCount": 1,
     "target": "aliasByTags(sumSeries(keepLastValue(seriesByTag('job=keepalived', 'name=prometheus_remote_write.keepalived_up', 'node_name=~.+-m(aster)?3', 'cluster=$Cluster'), 5), #C), 'node_name')",
     "targetFull": "aliasByTags(sumSeries(keepLastValue(seriesByTag('job=keepalived', 'name=prometheus_remote_write.keepalived_up', 'node_name=~.+-m(aster)?3', 'cluster=$Cluster'), 5), groupByTags(keepLastValue(seriesByTag('job=keepalived', 'name=prometheus_remote_write.keepalived_vrrp_become_master', 'node_name=~.+-m(aster)?3', 'cluster=$Cluster', 'state=MASTER'), 5), 'last', 'node_name')), 'node_name')"
    }
   ]
  },
  {
   "title": "HAProxy Up",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sum(movingMax(seriesByTag('job=haproxy', 'proxy=k8s-api', 'name=prometheus_remote_write.haproxy_frontend_status', 'cluster=$Cluster'), '5min'))"
    }
   ]
  },
  {
   "title": "HAProxy Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(sum(seriesByTag('job=haproxy', 'name=prometheus_remote_write.haproxy_frontend_bytes_in_total', 'proxy=k8s-api', 'cluster=$Cluster'))), 'received')"
    },
    {
     "target": "alias(scale(perSecond(sum(seriesByTag('job=haproxy', 'name=prometheus_remote_write.haproxy_frontend_bytes_out_total', 'proxy=k8s-api', 'cluster=$Cluster'))), -1), 'sent')"
    }
   ]
  },
  {
   "title": "HAProxy Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('job=haproxy', 'name=prometheus_remote_write.haproxy_server_current_sessions', 'cluster=$Cluster'), 'sum', 'server'), 'server')"
    }
   ]
  },
  {
   "title": "HAProxy Connection Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(perSecond(seriesByTag('job=haproxy', 'name=prometheus_remote_write.haproxy_server_connection_attempts_total', 'cluster=$Cluster')), 'sum', 'server'), 'server')"
    }
   ]
  },
  { "title": "Etcd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Etcd Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=etcd', 'node_name=~.+-m(aster)?1', 'name=prometheus_remote_write.etcd_server_is_leader', 'cluster=$Cluster'), 5), 1), #D), 'last', 'node_name'), 'node_name')",
     "targetFull": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=etcd', 'node_name=~.+-m(aster)?1', 'name=prometheus_remote_write.etcd_server_is_leader', 'cluster=$Cluster'), 5), 1), keepLastValue(seriesByTag('job=etcd', 'node_name=~.+-m(aster)?1', 'name=prometheus_remote_write.up', 'cluster=$Cluster'), 5)), 'last', 'node_name'), 'node_name')"
    },
    {
     "refCount": 1,
     "target": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=etcd', 'node_name=~.+-m(aster)?2', 'name=prometheus_remote_write.etcd_server_is_leader', 'cluster=$Cluster'), 5), 1), #E), 'last', 'node_name'), 'node_name')",
     "targetFull": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=etcd', 'node_name=~.+-m(aster)?2', 'name=prometheus_remote_write.etcd_server_is_leader', 'cluster=$Cluster'), 5), 1), keepLastValue(seriesByTag('job=etcd', 'node_name=~.+-m(aster)?2', 'name=prometheus_remote_write.up', 'cluster=$Cluster'), 5)), 'last', 'node_name'), 'node_name')"
    },
    {
     "refCount": 1,
     "target": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=etcd', 'node_name=~.+-m(aster)?3', 'name=prometheus_remote_write.etcd_server_is_leader', 'cluster=$Cluster'), 5), 1), #F), 'last', 'node_name'), 'node_name')",
     "targetFull": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=etcd', 'node_name=~.+-m(aster)?3', 'name=prometheus_remote_write.etcd_server_is_leader', 'cluster=$Cluster'), 5), 1), keepLastValue(seriesByTag('job=etcd', 'node_name=~.+-m(aster)?3', 'name=prometheus_remote_write.up', 'cluster=$Cluster'), 5)), 'last', 'node_name'), 'node_name')"
    }
   ]
  },
  {
   "title": "Etcd DB Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('job=etcd', 'name=prometheus_remote_write.etcd_mvcc_db_total_size_in_bytes', 'cluster=$Cluster'), 'node_name')"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByTags(movingAverage(groupByTags(perSecond(seriesByTag('job=etcd', 'name=prometheus_remote_write.process_cpu_seconds_total', 'cluster=$Cluster')), 'sum', 'node_name'), '5min'), 'node_name')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('job=etcd', 'name=prometheus_remote_write.process_resident_memory_bytes', 'cluster=$Cluster'), 'node_name')"
    }
   ]
  },
  {
   "title": "Commit Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(movingAverage(divideSeriesLists(perSecond(seriesByTag('job=etcd', 'name=prometheus_remote_write.etcd_disk_backend_commit_duration_seconds_sum', 'cluster=$Cluster')), #B), '5min'), 'node_name')",
     "targetFull": "aliasByTags(movingAverage(divideSeriesLists(perSecond(seriesByTag('job=etcd', 'name=prometheus_remote_write.etcd_disk_backend_commit_duration_seconds_sum', 'cluster=$Cluster')), perSecond(seriesByTag('job=etcd', 'name=prometheus_remote_write.etcd_disk_backend_commit_duration_seconds_count', 'cluster=$Cluster'))), '5min'), 'node_name')"
    }
   ]
  },
  {
   "title": "Fsync Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(movingAverage(divideSeriesLists(perSecond(seriesByTag('job=etcd', 'name=prometheus_remote_write.etcd_disk_wal_fsync_duration_seconds_sum', 'cluster=$Cluster')), #B), '5min'), 'node_name')",
     "targetFull": "aliasByTags(movingAverage(divideSeriesLists(perSecond(seriesByTag('job=etcd', 'name=prometheus_remote_write.etcd_disk_wal_fsync_duration_seconds_sum', 'cluster=$Cluster')), perSecond(seriesByTag('job=etcd', 'name=prometheus_remote_write.etcd_disk_wal_fsync_duration_seconds_count', 'cluster=$Cluster'))), '5min'), 'node_name')"
    }
   ]
  },
  {
   "title": "Client Requests Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(perSecond(seriesByTag('job=etcd', 'name=prometheus_remote_write.etcd_server_client_requests_total', 'cluster=$Cluster')), 'sum', 'node_name'), 'node_name')"
    }
   ]
  },
  { "title": "API Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "API Server Up",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "sum(movingMax(seriesByTag('job=kubernetes-apiservers', 'name=prometheus_remote_write.up', 'cluster=$Cluster'), '5min'))"
    }
   ]
  },
  {
   "title": "API Server RPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(movingAverage(perSecond(groupByTags(seriesByTag('job=kubernetes-apiservers', 'name=prometheus_remote_write.apiserver_request_total', 'cluster=$Cluster'), 'sum', 'node_name')), '5min'), 'node_name'), true, false)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByTags(movingAverage(perSecond(seriesByTag('job=kubernetes-apiservers', 'name=prometheus_remote_write.process_cpu_seconds_total', 'cluster=$Cluster')), '1min'), 'node_name')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('job=kubernetes-apiservers', 'name=prometheus_remote_write.process_resident_memory_bytes', 'cluster=$Cluster'), 'node_name')"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(movingAverage(perSecond(seriesByTag('job=kubernetes-apiservers', 'name=prometheus_remote_write.apiserver_request_total', 'cluster=$Cluster')), '1min'), 'sum', 'node_name'), 'node_name')"
    }
   ]
  },
  {
   "title": "Current Inflight Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('job=kubernetes-apiservers', 'name=prometheus_remote_write.apiserver_current_inflight_requests', 'cluster=$Cluster'), 'sum', 'request_kind'), 'request_kind')"
    }
   ]
  },
  {
   "title": "Latency - Avg",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(divideSeries(perSecond(sum(seriesByTag('job=kubernetes-apiservers', 'name=prometheus_remote_write.apiserver_request_duration_seconds_sum', 'verb!=WATCH', 'verb!=CONNECT', 'cluster=$Cluster'))), #B), '5min'), 'latency')",
     "targetFull": "alias(movingAverage(divideSeries(perSecond(sum(seriesByTag('job=kubernetes-apiservers', 'name=prometheus_remote_write.apiserver_request_duration_seconds_sum', 'verb!=WATCH', 'verb!=CONNECT', 'cluster=$Cluster'))), perSecond(sum(seriesByTag('job=kubernetes-apiservers', 'name=prometheus_remote_write.apiserver_request_duration_seconds_count', 'verb!=WATCH', 'verb!=CONNECT', 'cluster=$Cluster')))), '5min'), 'latency')"
    }
   ]
  },
  {
   "title": "API Server Response Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(sum(perSecond(seriesByTag('job=kubernetes-apiservers', 'name=prometheus_remote_write.apiserver_request_duration_seconds_sum', 'verb!=~(CONNECT|WATCH)', 'cluster=$Cluster'))), '5min'), 'response duration')"
    }
   ]
  },
  {
   "title": "Watchers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('job=kubernetes-apiservers', 'name=prometheus_remote_write.apiserver_registered_watchers', 'cluster=$Cluster'), 'sum', 'node_name'), 'node_name')"
    }
   ]
  },
  {
   "title": "Watch Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(perSecond(seriesByTag('job=kubernetes-apiservers', 'name=prometheus_remote_write.apiserver_watch_events_total', 'cluster=$Cluster')), 'sum', 'node_name'), 'node_name')"
    }
   ]
  },
  {
   "title": "REST Client Request Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(movingAverage(perSecond(groupByTags(seriesByTag('job=kubernetes-apiservers', 'name=prometheus_remote_write.rest_client_requests_total', 'cluster=$Cluster'), 'sum', 'node_name')), '5min'), 'node_name')"
    }
   ]
  },
  {
   "title": "API Server Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(movingAverage(perSecond(groupByTags(seriesByTag('job=kubernetes-apiservers', 'code=~([45]..)', 'name=prometheus_remote_write.apiserver_request_total', 'cluster=$Cluster'), 'sum', 'code')), '5min'), 'code')"
    }
   ]
  },
  { "title": "Contoller Managers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Controller Manager Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=kubernetes-controller-managers', 'node_name=~.+-m(aster)?1', 'name=prometheus_remote_write.leader_election_master_status', 'cluster=$Cluster'), 5), 1), #D), 'last', 'node_name'), 'node_name')",
     "targetFull": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=kubernetes-controller-managers', 'node_name=~.+-m(aster)?1', 'name=prometheus_remote_write.leader_election_master_status', 'cluster=$Cluster'), 5), 1), keepLastValue(seriesByTag('job=kubernetes-controller-managers', 'node_name=~.+-m(aster)?1', 'name=prometheus_remote_write.up', 'cluster=$Cluster'), 5)), 'last', 'node_name'), 'node_name')"
    },
    {
     "refCount": 1,
     "target": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=kubernetes-controller-managers', 'node_name=~.+-m(aster)?2', 'name=prometheus_remote_write.leader_election_master_status', 'cluster=$Cluster'), 5), 1), #E), 'last', 'node_name'), 'node_name')",
     "targetFull": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=kubernetes-controller-managers', 'node_name=~.+-m(aster)?2', 'name=prometheus_remote_write.leader_election_master_status', 'cluster=$Cluster'), 5), 1), keepLastValue(seriesByTag('job=kubernetes-controller-managers', 'node_name=~.+-m(aster)?2', 'name=prometheus_remote_write.up', 'cluster=$Cluster'), 5)), 'last', 'node_name'), 'node_name')"
    },
    {
     "refCount": 1,
     "target": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=kubernetes-controller-managers', 'node_name=~.+-m(aster)?3', 'name=prometheus_remote_write.leader_election_master_status', 'cluster=$Cluster'), 5), 1), #F), 'last', 'node_name'), 'node_name')",
     "targetFull": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=kubernetes-controller-managers', 'node_name=~.+-m(aster)?3', 'name=prometheus_remote_write.leader_election_master_status', 'cluster=$Cluster'), 5), 1), keepLastValue(seriesByTag('job=kubernetes-controller-managers', 'node_name=~.+-m(aster)?3', 'name=prometheus_remote_write.up', 'cluster=$Cluster'), 5)), 'last', 'node_name'), 'node_name')"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByTags(movingAverage(perSecond(seriesByTag('job=kubernetes-controller-managers', 'name=prometheus_remote_write.process_cpu_seconds_total', 'cluster=$Cluster')), '1min'), 'node_name')"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(movingAverage(seriesByTag('job=kubernetes-controller-managers', 'name=prometheus_remote_write.process_resident_memory_bytes', 'cluster=$Cluster'), '1min'), 'node_name')"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(sum(seriesByTag('job=kubernetes-controller-managers', 'name=prometheus_remote_write.workqueue_depth', 'cluster=$Cluster')), '5min'), 'depth')"
    }
   ]
  },
  {
   "title": "Workqueue Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(perSecond(sum(seriesByTag('job=kubernetes-controller-managers', 'name=prometheus_remote_write.workqueue_adds_total', 'cluster=$Cluster'))), '5min'), 'rate')"
    }
   ]
  },
  {
   "title": "Workqueue Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(divideSeriesLists(sum(seriesByTag('job=kubernetes-controller-managers', 'name=prometheus_remote_write.workqueue_queue_duration_seconds_sum', 'cluster=$Cluster')), #B), '5min'), 'latency')",
     "targetFull": "alias(movingAverage(divideSeriesLists(sum(seriesByTag('job=kubernetes-controller-managers', 'name=prometheus_remote_write.workqueue_queue_duration_seconds_sum', 'cluster=$Cluster')), sum(seriesByTag('job=kubernetes-controller-managers', 'name=prometheus_remote_write.workqueue_queue_duration_seconds_count', 'cluster=$Cluster'))), '5min'), 'latency')"
    }
   ]
  },
  { "title": "Schedulers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Scheduler Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=kubernetes-schedulers', 'node_name=~.+-m(aster)?1', 'name=prometheus_remote_write.leader_election_master_status', 'cluster=$Cluster'), 5), 1), #D), 'last', 'node_name'), 'node_name')",
     "targetFull": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=kubernetes-schedulers', 'node_name=~.+-m(aster)?1', 'name=prometheus_remote_write.leader_election_master_status', 'cluster=$Cluster'), 5), 1), keepLastValue(seriesByTag('job=kubernetes-schedulers', 'node_name=~.+-m(aster)?1', 'name=prometheus_remote_write.up', 'cluster=$Cluster'), 5)), 'last', 'node_name'), 'node_name')"
    },
    {
     "refCount": 1,
     "target": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=kubernetes-schedulers', 'node_name=~.+-m(aster)?2', 'name=prometheus_remote_write.leader_election_master_status', 'cluster=$Cluster'), 5), 1), #E), 'last', 'node_name'), 'node_name')",
     "targetFull": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=kubernetes-schedulers', 'node_name=~.+-m(aster)?2', 'name=prometheus_remote_write.leader_election_master_status', 'cluster=$Cluster'), 5), 1), keepLastValue(seriesByTag('job=kubernetes-schedulers', 'node_name=~.+-m(aster)?2', 'name=prometheus_remote_write.up', 'cluster=$Cluster'), 5)), 'last', 'node_name'), 'node_name')"
    },
    {
     "refCount": 1,
     "target": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=kubernetes-schedulers', 'node_name=~.+-m(aster)?3', 'name=prometheus_remote_write.leader_election_master_status', 'cluster=$Cluster'), 5), 1), #F), 'last', 'node_name'), 'node_name')",
     "targetFull": "aliasByTags(groupByTags(multiplySeriesLists(offset(keepLastValue(seriesByTag('job=kubernetes-schedulers', 'node_name=~.+-m(aster)?3', 'name=prometheus_remote_write.leader_election_master_status', 'cluster=$Cluster'), 5), 1), keepLastValue(seriesByTag('job=kubernetes-schedulers', 'node_name=~.+-m(aster)?3', 'name=prometheus_remote_write.up', 'cluster=$Cluster'), 5)), 'last', 'node_name'), 'node_name')"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByTags(movingAverage(perSecond(seriesByTag('job=kubernetes-schedulers', 'name=prometheus_remote_write.process_cpu_seconds_total', 'cluster=$Cluster')), '1min'), 'node_name')"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(movingAverage(seriesByTag('job=kubernetes-schedulers', 'name=prometheus_remote_write.process_resident_memory_bytes', 'cluster=$Cluster'), '1min'), 'node_name')"
    }
   ]
  },
  {
   "title": "Scheduler Attempts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(perSecond(movingAverage(seriesByTag('job=kubernetes-schedulers', 'name=prometheus_remote_write.scheduler_schedule_attempts_total', 'cluster=$Cluster'), '1min')), 'sum', 'result'), 'result')"
    }
   ]
  },
  {
   "title": "Scheduler Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(divideSeriesLists(sum(perSecond(seriesByTag('job=kubernetes-schedulers', 'name=prometheus_remote_write.scheduler_e2e_scheduling_duration_seconds_sum', 'cluster=$Cluster'))), #B), '5min'), 'duration')"
    }
   ]
  },
  {
   "title": "PV Status",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=$Cluster', 'name=prometheus_remote_write.kube_persistentvolume_status_phase'), 'sum', 'phase'), 'phase'), false)"
    }
   ]
  },
  {
   "title": "PVC Status",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('job=kube-state-metrics', 'cluster=$Cluster', 'name=prometheus_remote_write.kube_persistentvolumeclaim_status_phase'), 'sum', 'phase'), 'phase'), false)"
    }
   ]
  }
 ]
}