{
 "title": "K8s Docker-registry(Bootstrap)",
 "description": "Ответственный:  Жуков Д.А. (Проектный отдел)",
 "tags": [
  "k8s",
  "docker-registry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "tag_values(project_name,servertype=k8s)"
   },
   {
    "name": "store",
    "query": "tag_values(host, servertype=k8s)"
   }
  ]
 },
 "panels": [
  { "title": "Состояние сервиса", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Статус Harbor",
   "type": "stat",
   "description": "Общий статус харбора",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=prometheus.harbor_health', 'servertype=k8s', 'host=$store')"
    }
   ]
  },
  {
   "title": "Статус компонентов Harbor",
   "type": "stat",
   "description": "Статус отдельных систем\n0 = Down, 1 = Up",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('servertype=k8s', 'name=prometheus.harbor_up', 'host=$store'), 'component'), true, false)"
    }
   ]
  },
  {
   "title": "Total disk usage",
   "type": "stat",
   "description": "Объем используемого пространства",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "groupByTags(seriesByTag('servertype=k8s', 'name=prometheus.harbor_project_quota_usage_byte', 'host=$store'), 'sum', 'contur')"
    }
   ]
  },
  {
   "title": "Projects total",
   "type": "stat",
   "description": "Общее количество проектов ",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(aggregate(seriesByTag('name=prometheus.harbor_project_total', 'servertype=k8s', 'host=$store', 'contur=prod'), 'sum'), 'Public - ')"
    }
   ]
  },
  {
   "title": "Image Pull\\Push Rate",
   "type": "graph",
   "description": "Количество операций Pull и Push на весь реестр",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_artifact_pulled', 'servertype=k8s', 'host=$store'), 'sum', ''), #B), 'Pulled Image')",
     "targetFull": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_artifact_pulled', 'servertype=k8s', 'host=$store'), 'sum', ''), timeShift(groupByTags(seriesByTag('name=prometheus.harbor_artifact_pulled', 'servertype=k8s', 'host=$store'), 'sum', ''), '1m', false)), 'Pulled Image')"
    },
    {
     "refCount": 1,
     "target": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_project_artifact_total', 'servertype=k8s', 'host=$store'), 'sum', ''), #E), 'Pushed Image')",
     "targetFull": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_project_artifact_total', 'servertype=k8s', 'host=$store'), 'sum', ''), timeShift(groupByTags(seriesByTag('name=prometheus.harbor_project_artifact_total', 'servertype=k8s', 'host=$store'), 'sum', ''), '1m', false)), 'Pushed Image')"
    }
   ]
  },
  {
   "title": "Проекты",
   "type": "table",
   "description": "Список проектов с параметрами",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "seriesByTag('name=prometheus.harbor_project_quota_usage_byte', 'servertype=k8s', 'host=$store')"
    },
    {
     "target": "seriesByTag('name=prometheus.harbor_project_quota_byte', 'servertype=k8s', 'host=$store')"
    },
    {
     "target": "seriesByTag('name=prometheus.harbor_project_repo_total', 'servertype=k8s', 'host=$store')"
    },
    {
     "target": "seriesByTag('name=prometheus.harbor_project_artifact_total', 'servertype=k8s', 'host=$store')"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "graph",
   "description": "Время ответа реестра",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=http_response.response_time', 'servertype=k8s', 'host=$store', 'contur=prod'), 'Response')"
    }
   ]
  },
  {
   "title": "Count HTTP code(>200)",
   "type": "stat",
   "description": "Количество HTTP ошибок",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aggregate(aliasByTags(exclude(seriesByTag('name=prometheus.promhttp_metric_handler_requests_total', 'servertype=k8s', 'host=$store', 'contur=prod'), '200'), 'code'), 'sum')"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Время запуска реестра",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(seriesByTag('name=prometheus.process_start_time_seconds', 'servertype=k8s', 'host=$store', 'contur=prod'), 1000)"
    }
   ]
  },
  {
   "title": "Artifact total",
   "type": "stat",
   "description": "Общее количество артифактов",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "groupByTags(seriesByTag('servertype=k8s', 'name=prometheus.harbor_project_artifact_total', 'host=$store', 'contur=prod'), 'sum', 'contur')"
    }
   ]
  },
  {
   "title": "Harbor components status",
   "type": "graph",
   "description": "Статусы компонентов в разрезе времени. И сам статус harbor\n> 1 - UP, 0 - DOWN",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=prometheus.harbor_up', 'servertype=k8s', 'host=$store'), 'component'), true, false)"
    },
    {
     "target": "alias(seriesByTag('name=prometheus.harbor_health', 'servertype=k8s', 'host=$store'), 'harbor')"
    }
   ]
  },
  {
   "title": "S3 storage by projects",
   "type": "graph",
   "description": "Выделенное кол-во дискового пространства по проектам",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=prometheus.harbor_project_quota_usage_byte', 'servertype=k8s', 'host=$store', 'contur=prod'), 'project_name')"
    }
   ]
  },
  { "title": "Состояние сервера", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "description": "Время работы сервера",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('servertype=k8s', 'name=system.system.uptime', 'host=$store', 'contur=prod')"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Количество ядер в системе",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(seriesByTag('servertype=k8s', 'name=system.cpu.usage_system', 'cpu!=cpu-total', 'host=$store'))"
    }
   ]
  },
  {
   "title": "CPU IOwait",
   "type": "stat",
   "description": "Доля процессорного времени в ожидании ввода-вывода",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('servertype=k8s', 'cpu=cpu-total', 'name=system.cpu.usage_iowait', 'host=$store', 'contur=prod')"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Общее количество используемой оперативной памяти",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('servertype=k8s', 'name=system.mem.total', 'host=$store', 'contur=prod')"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "stat",
   "description": "Общий объем диского пространства",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "groupByTags(seriesByTag('servertype=k8s', 'name=system.disk.total', 'host=$store'), 'sum', '')"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "stat",
   "description": "Количество свободного дискового пространства",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(groupByTags(seriesByTag('servertype=k8s', 'name=system.disk.free', 'host=$store'), 'sum', ''), 'FREE')"
    }
   ]
  },
  {
   "title": "Disk R\\W",
   "type": "graph",
   "description": "Скорость чтения/записи диска",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('servertype=k8s', 'name=system.diskio.write_bytes', '_name=sda2', 'host=$store', 'contur=prod')), 'Writes')"
    },
    {
     "target": "alias(perSecond(seriesByTag('servertype=k8s', 'name=system.diskio.read_bytes', '_name=sda2', 'host=$store', 'contur=prod')), 'Read')"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "Процент использования системных компонентов",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('servertype=k8s', 'cpu=cpu-total', 'name=system.cpu.usage_active', 'host=$store', 'contur=prod'), 'CPU active')"
    },
    {
     "target": "alias(seriesByTag('servertype=k8s', 'name=system.mem.used_percent', 'host=$store', 'contur=prod'), 'Memory used')"
    },
    {
     "target": "alias(seriesByTag('servertype=k8s', 'name=system.swap.used_percent', 'host=$store', 'contur=prod'), 'Swap used')"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "description": "LA за 1, 5, 15 минут",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('servertype=k8s', 'name=system.system.load1', 'host=$store', 'contur=prod'), 'LA1')"
    },
    {
     "target": "alias(seriesByTag('servertype=k8s', 'name=system.system.load5', 'host=$store', 'contur=prod'), 'LA5')"
    },
    {
     "target": "alias(seriesByTag('servertype=k8s', 'name=system.system.load15', 'host=$store', 'contur=prod'), 'LA15')"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "Процент времени использования CPU по системным компонентам",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "exclude(exclude(exclude(aliasByTags(seriesByTag('servertype=k8s', 'name=~system.cpu.*', 'cpu=cpu-total', 'host=$store', 'contur=prod'), 'name'), 'idle'), 'active'), 'time')"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Объем используемой оперативной памяти",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=k8s', 'name=system.mem.used', 'host=$store', 'contur=prod'), 'name')"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "description": "Объем сетевого трафика",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('servertype=k8s', 'name=system.net.bytes_sent', 'interface=~ens*', 'host=$store', 'contur=prod')), 'Sent')"
    },
    {
     "target": "alias(perSecond(seriesByTag('servertype=k8s', 'name=system.net.bytes_recv', 'interface=~ens*', 'host=$store', 'contur=prod')), 'Recv')"
    }
   ]
  },
  {
   "title": "Информация по проекту ${project:regex}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Статистика по проекту ",
   "type": "stat",
   "description": "Количество репозиториев в проекте, количество артифактов в проекте, количество пуллов артифактов",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('project_name=~${project:regex}', 'name=prometheus.harbor_project_repo_total', 'servertype=k8s', 'contur=prod', 'host=~${store:regex}'), 'Repo Total')"
    },
    {
     "target": "alias(groupByTags(seriesByTag('project_name=~${project:regex}', 'name=prometheus.harbor_project_artifact_total', 'servertype=k8s', 'contur=prod', 'host=~${store:regex}'), 'sum', ''), 'Artifact total')"
    },
    {
     "target": "alias(seriesByTag('project_name=~${project:regex}', 'name=prometheus.harbor_artifact_pulled', 'servertype=k8s', 'contur=prod', 'host=~${store:regex}'), 'Artifact Pulled')"
    }
   ]
  },
  {
   "title": "Image Pull\\Push Rate",
   "type": "graph",
   "description": "Количество операций Pull и Push на проект",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_artifact_pulled', 'servertype=k8s', 'project_name=${project:regex}', 'host=$store', 'contur=prod'), 'sum', ''), #B), 'Pulled Image')",
     "targetFull": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_artifact_pulled', 'servertype=k8s', 'project_name=${project:regex}', 'host=$store', 'contur=prod'), 'sum', ''), timeShift(groupByTags(seriesByTag('name=prometheus.harbor_artifact_pulled', 'servertype=k8s', 'project_name=${project:regex}', 'host=$store', 'contur=prod'), 'sum', ''), '1m', false)), 'Pulled Image')"
    },
    {
     "refCount": 1,
     "target": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_project_artifact_total', 'servertype=k8s', 'project_name=${project:regex}', 'host=$store', 'contur=prod'), 'sum', ''), #E), 'Pushed Image')",
     "targetFull": "alias(diffSeries(groupByTags(seriesByTag('name=prometheus.harbor_project_artifact_total', 'servertype=k8s', 'project_name=${project:regex}', 'host=$store', 'contur=prod'), 'sum', ''), timeShift(groupByTags(seriesByTag('name=prometheus.harbor_project_artifact_total', 'servertype=k8s', 'project_name=${project:regex}', 'host=$store', 'contur=prod'), 'sum', ''), '1m', false)), 'Pushed Image')"
    }
   ]
  },
  {
   "title": "Квоты по проекту",
   "type": "graph",
   "description": "Объем, занятый файлами проекта и квота. -1 — отсутствие квоты",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~prometheus.harbor_project_(quota_byte|quota_usage_byte)', 'project_name=~${project:regex}', 'servertype=k8s', 'host=$store', 'contur=prod'), 'project_name', 'name')"
    }
   ]
  },
  { "title": "Garbage Collector info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "description": "Количество открытых файловых дескрипторов. \nВерхний предел — 1048576.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=prometheus.process_open_fds', 'servertype=k8s', 'host=$store', 'contur=prod'), 'Open File Descriptors')"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "Количество активных параллельных потоков языка GO. \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=prometheus.go_goroutines', 'servertype=k8s', 'host=$store', 'contur=prod'), 'Goroutines')"
    }
   ]
  },
  {
   "title": "Memstats",
   "type": "graph",
   "description": "Количество выделенной памяти. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=prometheus.go_memstats_alloc_bytes', 'servertype=k8s', 'host=$store', 'contur=prod'), 'Go allocated bytes')"
    },
    {
     "target": "alias(seriesByTag('name=prometheus.go_memstats_buck_hash_sys_bytes', 'servertype=k8s', 'host=$store', 'contur=prod'), 'Profiling bucket hash table')"
    },
    {
     "target": "alias(seriesByTag('name=prometheus.go_memstats_gc_sys_bytes', 'servertype=k8s', 'host=$store', 'contur=prod'), 'GC metadata')"
    },
    {
     "target": "alias(seriesByTag('name=prometheus.go_memstats_heap_alloc_bytes', 'servertype=k8s', 'host=$store', 'contur=prod'), 'Heap allocated bytes')"
    },
    {
     "target": "alias(seriesByTag('name=prometheus.go_memstats_mcache_inuse_bytes', 'servertype=k8s', 'host=$store', 'contur=prod'), 'mcache in use bytes')"
    },
    {
     "target": "alias(seriesByTag('name=prometheus.go_memstats_mspan_inuse_bytes', 'servertype=k8s', 'host=$store', 'contur=prod'), 'mspan in use bytes')"
    },
    {
     "target": "alias(seriesByTag('name=prometheus.go_memstats_stack_inuse_bytes', 'servertype=k8s', 'host=$store', 'contur=prod'), 'stack in use')"
    },
    {
     "target": "alias(seriesByTag('name=prometheus.go_memstats_sys_bytes', 'servertype=k8s', 'host=$store', 'contur=prod'), 'obtained from system')"
    }
   ]
  },
  {
   "title": "Heap bytes before GC",
   "type": "graph",
   "description": "Количество байт в куче до ближайшего прохода сборщика мусора",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=prometheus.go_memstats_next_gc_bytes', 'servertype=k8s', 'host=$store', 'contur=prod'), 'Heap bytes before next GC')"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "graph",
   "description": "Длительность прохода сборщика мусора ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('name=prometheus.go_gc_duration_seconds_sum', 'servertype=k8s', 'host=$store', 'contur=prod')), 'GC duration')"
    }
   ]
  },
  {
   "title": "Last GC",
   "type": "timeseries",
   "description": "Время последнего прохода сборщика мусора",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('name=prometheus.go_memstats_last_gc_time_seconds', 'servertype=k8s', 'contur=prod', 'host=$store')), 'last GC')"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "description": "Длительность прохода сборщика мусора по квантилям",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=prometheus.go_gc_duration_seconds', 'servertype=k8s', 'contur=prod', 'host=$store'), 'quantile'), false)"
    }
   ]
  }
 ]
}