{
 "title": "K8s - Persistent Volumes",
 "description": "Ответственный: Новиков А.В. (Проектный отдел)",
 "tags": [ "telegraf" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Статус компонентов управления томами",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "stat",
   "description": "Статус провиженера NFS",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"system-storage-nfs\",pod=~\"nfs-subdir-external-provisioner-.+\",phase=\"Running\"})",
     "legendFormat": "NFS Provisioner"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace=\"system-storage-nfs\",pod=~\"nfs-subdir-external-provisioner-.+\"}[$__range]))",
     "legendFormat": "NFS Provisioner Restarts"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Статус провиженера IBM Block CSI",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"system-storage-ibm\",statefulset=\"ibm-block-csi-controller\"}",
     "legendFormat": "IBM Block CSI Controller"
    },
    {
     "expr": "kube_daemonset_status_number_unavailable{namespace=\"system-storage-ibm\",daemonset=\"ibm-block-csi-node\"}",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"system-storage-ibm\",phase=\"Running\"} * on(namespace, pod) group_left kube_pod_owner{namespace=\"system-storage-ibm\",owner_name=\"ibm-block-csi-node\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace=\"system-storage-ibm\",pod=~\"ibm-block-csi-controller-.*\"}[$__range]))",
     "legendFormat": "IBM Controller Restarts"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace=\"system-storage-ibm\",pod=~\"ibm-block-csi-node-.*\"}[$__range]))",
     "legendFormat": "IBM Block CSI Nodes Restarts"
    }
   ]
  },
  {
   "title": "PVC by Phase",
   "type": "timeseries",
   "description": "Количество объектов PVC в различных статусах",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "PV by Phase",
   "type": "timeseries",
   "description": "Количество объектов PV в различных статусах",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Динамика операций управления томами",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "PVC Activity",
   "type": "timeseries",
   "description": "Количество операций создания, обновления или удаления PVC за выбранный период",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(apiserver_request_total{verb!~\"WATCH|GET|LIST\", resource=\"persistentvolumeclaims\"}[5m])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "PV Activity",
   "type": "timeseries",
   "description": "Количество операций создания, обновления или удаления PV за выбранный период",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(apiserver_request_total{verb!~\"WATCH|GET|LIST\", resource=\"persistentvolumes\"}[5m])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Attach Activity",
   "type": "timeseries",
   "description": "Количество операций создания, обновления или удаления VolumeAttachments (отвечают за подключение томов к worker-нодам) за выбранный период.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(apiserver_request_total{verb!~\"WATCH|GET|LIST\", resource=\"volumeattachments\"}[5m])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Использование дискового пространства",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Утилизация StorageClass заявками (PVC)",
   "type": "table",
   "description": "Использование PVC и объемов дискового пространства в разрезе StorageClass",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_info) by (storageclass)",
     "legendFormat": "{{storageclass}}"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes * on (namespace,persistentvolumeclaim) group_left (storageclass) kube_persistentvolumeclaim_info) by (storageclass)",
     "legendFormat": "{{storageclass}}"
    },
    {
     "expr": "storageclass_capacity_bytes > 0"
    },
    {
     "expr": "(storageclass_capacity_bytes + on (location) group_left sum by (location) ((group by(storageclass, location) (storageclass_capacity_bytes) * on(storageclass) group_right(location) (sum(kube_persistentvolumeclaim_resource_requests_storage_bytes * on (namespace,persistentvolumeclaim) group_left (storageclass) kube_persistentvolumeclaim_info) by (storageclass))))) / storageclass_capacity_bytes - 1"
    },
    {
     "expr": "label_replace(storageclass_capacity_bytes, \"table_location\", \"$1\", \"location\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "Утилизация StorageClass томами (PV)",
   "type": "table",
   "description": "Использование PV и объемов дискового пространства в разрезе StorageClass",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_info) by (storageclass)",
     "legendFormat": "{{storageclass}}"
    },
    {
     "expr": "sum(kube_persistentvolume_capacity_bytes * on (persistentvolume) group_left (storageclass) kube_persistentvolume_info) by (storageclass)",
     "legendFormat": "{{storageclass}}"
    },
    {
     "expr": "storageclass_capacity_bytes > 0"
    },
    {
     "expr": "(storageclass_capacity_bytes + on (location) group_left sum by (location) ((group by(storageclass, location) (storageclass_capacity_bytes) * on(storageclass) group_right(location) (sum(kube_persistentvolume_capacity_bytes * on (persistentvolume) group_left (storageclass) kube_persistentvolume_info) by (storageclass))))) / storageclass_capacity_bytes - 1",
     "legendFormat": "{{location}}"
    },
    {
     "expr": "label_replace(storageclass_capacity_bytes, \"table_location\", \"$1\", \"location\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "Использование квот на Namespace и утилизация дискового пространства по Persistent Volume Claims",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Использование квот на PVC по Namespace",
     "type": "table",
     "description": "Использование объемов дискового пространства, количество PVC в различных статусах (Bound, Pending, Lost), а также утилизация квот в разрезе Namespace.\n\nSize - общий объем запрошенный PVC.\n\nPVC Count Quota - использование квоты на количество дисков для Namespace. \n\nStorage Quota - использование квоты на объем дисков для Namespace.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Lost\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(kube_resourcequota{resource=\"persistentvolumeclaims\",type=\"used\"}) by (namespace) / on (namespace) group_left sum(kube_resourcequota{resource=\"persistentvolumeclaims\",type=\"hard\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(kube_resourcequota{resource=\"requests.storage\",type=\"used\"}) by (namespace) / on (namespace) group_left sum(kube_resourcequota{resource=\"requests.storage\",type=\"hard\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Утилизация дискового пространства по PVC",
     "type": "table",
     "description": "Использование дискового пространства в разрезе Namespace и PVC",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{job=\"volume-exporter\"}) by (namespace,pvc)"
      },
      {
       "expr": "1-max(node_filesystem_avail_bytes{job=\"volume-exporter\"}) by (namespace,pvc) / on (namespace,pvc) group_left max(node_filesystem_size_bytes{job=\"volume-exporter\"}) by (namespace,pvc)"
      },
      {
       "expr": "max(node_filesystem_files{job=\"volume-exporter\"}) by (namespace,pvc)"
      },
      {
       "expr": "1-max(node_filesystem_files_free{job=\"volume-exporter\"}) by (namespace,pvc) / on (namespace,pvc) group_left max(node_filesystem_files{job=\"volume-exporter\"}) by (namespace,pvc)"
      }
     ]
    }
   ]
  },
  {
   "title": "IBM Block CSI Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"system-storage-ibm\",pod=~\"ibm-block-csi-controller-.*\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"system-storage-ibm\",pod=~\"ibm-block-csi-controller-.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IBM Block CSI Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"system-storage-ibm\",pod=~\"ibm-block-csi-node-.*\"}[5m])) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"system-storage-ibm\",pod=~\"ibm-block-csi-node-.*\"}) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS Provisioner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"system-storage-nfs\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"system-storage-nfs\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FibreChannel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "FC Words Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(rate(node_fibrechannel_rx_words_total[5m])) by (node_name)",
       "legendFormat": "RX.{{node_name}}"
      },
      {
       "expr": "-sum(rate(node_fibrechannel_tx_words_total[5m])) by (node_name)",
       "legendFormat": "TX.{{node_name}}"
      }
     ]
    },
    {
     "title": "FC Port State",
     "type": "table",
     "description": "Статус FC портов на worker-нодах K8s.\n\nHas Label - наличие на worker-ноде метки, разрешающей подключение томов FC.\n\nPort State - состояние FC порта.",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
     "targets": [
      {
       "expr": "node_fibrechannel_info * on (node_name) group_left (label_hw_tensor_ru_fc) kube_node_labels"
      }
     ]
    }
   ]
  },
  {
   "title": "Multipath",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Multipath State",
     "type": "table",
     "description": "Состояние multipath устройств на worker-нодах K8s.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "targets": [
      { "expr": "multipath_lun_path_count" }
     ]
    },
    {
     "title": "Статус multipathd",
     "type": "table",
     "description": "Статус сервиса multipathd",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "multipath_status{status=\"running\"}"
      }
     ]
    },
    {
     "title": "Multipath Info",
     "type": "table",
     "description": "Подробная информация о путях multipath устройств на worker-нодах K8s.\n\nchk_st - отражает готовность пути на multipath устройстве.",
     "gridPos": { "h": 11, "w": 16, "x": 8, "y": 33 },
     "targets": [
      { "expr": "multipath_lun_path_info" }
     ]
    }
   ]
  }
 ]
}