{
 "title": "K8s - API Delays",
 "description": "Ответственный: Никулин А.Н. (Проектный отдел)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "tag_values(cluster,name=prometheus_remote_write.up)"
   },
   {
    "name": "node_name",
    "label": "Node",
    "query": "tag_values(node_name,name=prometheus_remote_write.apiserver_request_duration_seconds_sum,cluster=$cluster)"
   },
   {
    "name": "verb",
    "label": "Verb",
    "query": "tag_values(verb,name=prometheus_remote_write.apiserver_request_duration_seconds_sum,cluster=$cluster,node_name=~${node_name:regex})"
   },
   {
    "name": "resource",
    "label": "Resource",
    "query": "tag_values(resource,name=prometheus_remote_write.apiserver_request_duration_seconds_sum,verb=~${verb:regex},cluster=$cluster,node_name=~${node_name:regex})"
   }
  ]
 },
 "panels": [
  {
   "title": "TOP 5 Requests Delays by Resources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "highestMax(aliasByTags(groupByTags(aliasSub(divideSeriesLists(perSecond(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_sum', 'verb=~${verb:regex}', 'subresource!=~(log|exec|attach)', 'resource=~${resource:regex}$', 'node_name=~${node_name:regex}$')), #B), ',1[)][)][)]', '$1'), 'max', 'verb', 'resource', 'subresource'), 'verb', 'resource', 'subresource'), 5)",
     "targetFull": "highestMax(aliasByTags(groupByTags(aliasSub(divideSeriesLists(perSecond(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_sum', 'verb=~${verb:regex}', 'subresource!=~(log|exec|attach)', 'resource=~${resource:regex}$', 'node_name=~${node_name:regex}$')), perSecond(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_count', 'verb=~${verb:regex}', 'subresource!=~(log|exec|attach)', 'resource=~${resource:regex}$', 'node_name=~${node_name:regex}$'))), ',1[)][)][)]', '$1'), 'max', 'verb', 'resource', 'subresource'), 'verb', 'resource', 'subresource'), 5)"
    }
   ]
  },
  {
   "title": "API Delays",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(aliasSub(divideSeriesLists(perSecond(keepLastValue(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_sum', 'verb=~(GET|LIST)', 'subresource!=~(log|exec|attach)', 'node_name=~${node_name:regex}$'), 1)), #B), ',1[)][)][)]', '$1'), 'max', 'verb'), 'verb')",
     "targetFull": "aliasByTags(groupByTags(aliasSub(divideSeriesLists(perSecond(keepLastValue(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_sum', 'verb=~(GET|LIST)', 'subresource!=~(log|exec|attach)', 'node_name=~${node_name:regex}$'), 1)), perSecond(keepLastValue(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_count', 'verb=~(GET|LIST)', 'subresource!=~(log|exec|attach)', 'node_name=~${node_name:regex}$'), 1))), ',1[)][)][)]', '$1'), 'max', 'verb'), 'verb')"
    }
   ]
  },
  {
   "title": "Other API Delays ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(divideSeriesLists(perSecond(keepLastValue(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_sum', 'verb!=~(WATCH|CONNECT)', 'subresource!=~(log|exec|attach)', 'verb=~(POST|DELETE|PATCH|PUT)', 'node_name=~${node_name:regex}$'), 1)), #B), 'max', 'verb'), 'verb')",
     "targetFull": "aliasByTags(groupByTags(divideSeriesLists(perSecond(keepLastValue(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_sum', 'verb!=~(WATCH|CONNECT)', 'subresource!=~(log|exec|attach)', 'verb=~(POST|DELETE|PATCH|PUT)', 'node_name=~${node_name:regex}$'), 1)), perSecond(keepLastValue(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_count', 'verb!=~(WATCH|CONNECT)', 'subresource!=~(log|exec|attach)', 'verb=~(POST|DELETE|PATCH|PUT)', 'node_name=~${node_name:regex}$'), 1))), 'max', 'verb'), 'verb')"
    }
   ]
  },
  {
   "title": "API Requests Delays by Resources",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(groupByTags(aliasSub(divideSeriesLists(perSecond(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_sum', 'verb=~${verb:regex}', 'subresource!=~(log|exec|attach)', 'resource=~${resource:regex}$', 'node_name=~${node_name:regex}$')), #B), ',1[)][)][)]', '$1'), 'max', 'verb', 'resource', 'subresource'), 'verb', 'resource', 'subresource'))",
     "targetFull": "sortByMaxima(aliasByTags(groupByTags(aliasSub(divideSeriesLists(perSecond(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_sum', 'verb=~${verb:regex}', 'subresource!=~(log|exec|attach)', 'resource=~${resource:regex}$', 'node_name=~${node_name:regex}$')), perSecond(seriesByTag('job=kubernetes-apiservers', 'cluster=${cluster:regex}', 'name=prometheus_remote_write.apiserver_request_duration_seconds_count', 'verb=~${verb:regex}', 'subresource!=~(log|exec|attach)', 'resource=~${resource:regex}$', 'node_name=~${node_name:regex}$'))), ',1[)][)][)]', '$1'), 'max', 'verb', 'resource', 'subresource'), 'verb', 'resource', 'subresource'))"
    }
   ]
  }
 ]
}