{
 "title": "LVS system coordinator",
 "description": "Балансировщик нагрузки. Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "lvs",
  "keepalived",
  "linux",
  "dts",
  "telegraf",
  "mv.konuhov",
  "system"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "Contur", "query": "prod" },
   {
    "name": "host",
    "label": "Host",
    "query": "tag_values(host,servertype=balancer,contur=$contur)"
   },
   {
    "name": "ipvs_service",
    "label": "IPVS service",
    "query": "tag_values(virtual_address,host=$host)"
   },
   {
    "name": "netif",
    "label": "Network interface",
    "query": "tag_values(interface,host=$host)"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "tag_values(_name,host=$host, name=~io)"
   },
   { "name": "mount_point", "label": "Mount point", "query": "tag_values(path,host=$host)" }
  ]
 },
 "panels": [
  { "title": "Quick", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Uptime",
   "type": "stat",
   "description": "Аптайс сервера (ОС)",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=system.system.uptime')"
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "stat",
   "description": "LA за 5 минут",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=system.system.load5')"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "description": "Количество процессов",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=system.processes.total')"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "Количество потоков",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=system.processes.total_threads')"
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "stat",
   "description": "Количество zombie-процессов",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=system.processes.zombies')"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "description": "Утилизация CPU",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=system.cpu.usage_active', 'cpu=cpu-total')"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "description": "Утилизация RAM",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=system.mem.used_percent')"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "gauge",
   "description": "Утилизация swap",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=system.swap.used_percent')"
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "gauge",
   "description": "Занятость дискового раздела",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=system.disk.used_percent', 'path=-')"
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "stat",
   "description": "Доля процессорного времени в ожидании ввода-вывода",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=system.cpu.usage_iowait', 'cpu=cpu-total')"
    }
   ]
  },
  {
   "title": "RAID state",
   "type": "stat",
   "description": "Состояние RAID-контроллера",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=$host', 'name=raid.vd.state'), 'adapter', 'vd'), '(\\d+)\\.(\\d+)', 'Adapter\\1 VD\\2')"
    }
   ]
  },
  {
   "title": "VRRP Instance State",
   "type": "stat",
   "description": "Роль VRRP в кластере",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'name=vrrpInstance.vrrpInstanceState'), 'vrrpInstanceName')"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "description": "Состояние основных systemd-сервисов",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'name=systemd.service.state'), '_name')"
    }
   ]
  },
  {
   "title": "Log errors",
   "type": "stat",
   "description": "Количество ошибок в логах сервиса управления балансировкой",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'name=coordinator_errors_total.counter'), 0)"
    }
   ]
  },
  {
   "title": "Bond state",
   "type": "stat",
   "description": "Состояние bond-интерфейсов",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'name=bond.status'), 'bond')"
    }
   ]
  },
  {
   "title": "Bond Slave state",
   "type": "stat",
   "description": "Состояние slave-интерфейсов bond",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'name=bond_slave.status'), 'bond', 'interface')"
    }
   ]
  },
  { "title": "LVS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active connections",
   "type": "graph",
   "description": "Количество активных соединений",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(seriesByTag('host=$host', 'name=system.ipvs.active_connections', 'virtual_address=~${ipvs_service:regex}')), '$host: active connections')"
    },
    {
     "target": "alias(timeShift(sumSeries(seriesByTag('host=$host', 'name=system.ipvs.active_connections', 'virtual_address=~${ipvs_service:regex}')), '7d', true), '$host: active connections 7days ago')"
    }
   ]
  },
  {
   "title": "Inactive connections",
   "type": "graph",
   "description": "Количество неактивных соединений",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(seriesByTag('host=$host', 'name=system.ipvs.inactive_connections', 'virtual_address=~${ipvs_service:regex}')), '$host: active connections')"
    },
    {
     "target": "alias(timeShift(sumSeries(seriesByTag('host=$host', 'name=system.ipvs.inactive_connections', 'virtual_address=~${ipvs_service:regex}')), '7d', true), '$host: active connections 7 days ago')"
    }
   ]
  },
  { "title": "LVS per sec", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "New connections per sec",
   "type": "graph",
   "description": "Количество новых соединений в секунду",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(seriesByTag('host=$host', 'name=system.ipvs.cps', 'virtual_address=~${ipvs_service:regex}')), 'new connections per sec')"
    },
    {
     "target": "alias(timeShift(sumSeries(seriesByTag('host=$host', 'name=system.ipvs.cps', 'virtual_address=~${ipvs_service:regex}')), '7d', true), 'new connections per sec 7 days ago')"
    }
   ]
  },
  { "title": "Cluster info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Coordinators status",
   "type": "graph",
   "description": "uptime координатора https://dpc-docs.tensor.ru:8443/pages/viewpage.action?pageId=32182879",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(transformNull(seriesByTag('name=coordinator.status', 'contur=prod', 'coordinator=~.*'), 0), 'coordinator')"
    }
   ]
  },
  {
   "title": "Coordinator uptime",
   "type": "graph",
   "description": "uptime координатора https://dpc-docs.tensor.ru:8443/pages/viewpage.action?pageId=32182879",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(transformNull(seriesByTag('name=coordinator.uptime', 'contur=prod', 'coordinator=~.*'), 0), 'coordinator')"
    }
   ]
  },
  {
   "title": "Balancers status",
   "type": "graph",
   "description": "uptime координатора https://dpc-docs.tensor.ru:8443/pages/viewpage.action?pageId=32182879",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(transformNull(seriesByTag('name=balancer.status', 'contur=prod', 'coordinator=~.*'), 0), 'coordinator', 'host')"
    }
   ]
  },
  {
   "title": "Network interface stats for $netif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "netif"
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "description": "Утилизация сетевого порта в битах/сек",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(aliasByTags(perSecond(seriesByTag('host=$host', 'interface=$netif', 'name=~system.net.bytes_(recv|sent)')), 'name'), 8), -1)"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "description": "Утилизация сетевого порта в пакетах/сек",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('host=$host', 'interface=$netif', 'name=~system.net.packets_(recv|sent)')), 'name'), -1)"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Load averages",
   "type": "graph",
   "description": "LA за 1, 5, 15 минут",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=$host', 'name=~system.system.load.*'), 'name'), -1)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "Утилизация CPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=$host', 'cpu=cpu-total', 'name=~system.cpu.usage_(system|user|softirq|user|iowait)'), 'name'), -1)"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "description": "Количество процессов по типам",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=$host', 'name=~system.processes.(running|blocked|sleeping)'), 'name'), -1)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "description": "Утилизация RAM",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=$host', 'name=~system.mem.(total|cached|used|free)$'), 'name'), -1)"
    }
   ]
  },
  {
   "title": "Swap I/O bytes",
   "type": "graph",
   "description": "Утилизация swap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=$host', 'name=~system.swap.(in|out)'), 'name'), -1)"
    }
   ]
  },
  {
   "title": "Swap usage (bytes)",
   "type": "graph",
   "description": "Утилизация swap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('host=$host', 'name=~system.swap.(total|used)$'), 'name'), -1)"
    }
   ]
  },
  { "title": "Kernel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Context switches",
   "type": "graph",
   "description": "Количество переключений контекста",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('host=$host', 'name=system.kernel.context_switches')), 'context switches')"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "description": "Количество форков процессов",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('host=$host', 'name=system.kernel.processes_forked')), 'forks')"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "description": "Количество новых файловых дескрипторов",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('host=$host', 'name=~system.linux_sysctl_fs.file-(max|nr)')), 'name'), -1)"
    }
   ]
  },
  { "title": "Interrupts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Interrupts",
   "type": "graph",
   "description": "Количество прерываний",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('host=$host', 'name=system.interrupts.total', 'irq=~(CAL|RES|LOC|MCP|PMI|NMI|TLB)')), 'irq')"
    }
   ]
  },
  { "title": "Disk IOPS for /dev/$disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 }, "repeat": "disk" },
  {
   "title": "Disk I/O requests for /dev/$disk",
   "type": "graph",
   "description": "Количество IOPS",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('host=$host', '_name=$disk', 'name=~system.diskio.(reads|writes)')), 'name'), -1)"
    }
   ]
  },
  {
   "title": "Disk I/O bytes for /dev/$disk",
   "type": "graph",
   "description": "Утилизация ввода-вывода в байтах",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 87 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(perSecond(seriesByTag('host=$host', '_name=$disk', 'name=~system.diskio.(read|write)_bytes')), 'name'), -1)"
    }
   ]
  },
  {
   "title": "Disk I/O time for /dev/$disk",
   "type": "graph",
   "description": "Время занятости диска",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 87 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(aliasByTags(perSecond(seriesByTag('host=$host', '_name=$disk', 'name=system.diskio.io_time')), 'name'), 0.1), -1)"
    }
   ]
  },
  {
   "title": "Disk space usage for $mount_point",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "repeat": "mount_point"
  },
  {
   "title": "Disk usage for $mount_point",
   "type": "graph",
   "description": "Утилизация ФС $mount_point",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(seriesByTag('host=$host', 'path=$mount_point', 'name=~system.disk.(total|used)$'), 'path', 'name'), 0, -1), '-.', '/ ')"
    }
   ]
  },
  {
   "title": "Disk inodes for $mount_point",
   "type": "graph",
   "description": "Количество inode",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 159 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(aliasByTags(seriesByTag('host=$host', 'path=$mount_point', 'name=~system.disk.inodes_(total|used)$'), 'path', 'name'), 0, -1), '-.', '/ ')"
    }
   ]
  }
 ]
}