{
 "title": "NetFlow: Kafka",
 "description": "Ответственный: -",
 "tags": [
  "dts",
  "netflow"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "tag_values(host, servertype=dts-netflow, name=~kafka.*)"
   }
  ]
 },
 "panels": [
  {
   "title": "Partitions",
   "type": "graph",
   "description": "Кол-во разделов",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('host=$server', 'name=kafka_replica_manager.PartitionCount.'), 'Partitions')"
    },
    {
     "target": "alias(seriesByTag('host=$server', 'name=kafka_replica_manager.UnderReplicatedPartitions.'), 'Under Replicated Partitions')"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Запросы на получение, выдачу",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('host=$server', 'name=kafka_topics.TotalFetchRequestsPerSec.Count')), 'Fetch')"
    },
    {
     "target": "alias(perSecond(seriesByTag('host=$server', 'name=kafka_topics.TotalProduceRequestsPerSec.Count')), 'Produce')"
    },
    {
     "target": "alias(perSecond(seriesByTag('host=$server', 'name=kafka_topics.FailedFetchRequestsPerSec.Count')), 'Failed Produce')"
    },
    {
     "target": "alias(perSecond(seriesByTag('host=$server', 'name=kafka_topics.FailedFetchRequestsPerSec.Count')), 'Failed Fetch')"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "description": "Трафик в байтах в секунду",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(scale(seriesByTag('host=$server', 'name=kafka_topics.BytesInPerSec.Count'), 8)), 'In')"
    },
    {
     "target": "alias(perSecond(scale(seriesByTag('host=$server', 'name=kafka_topics.BytesOutPerSec.Count'), 8)), 'Out')"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "graph",
   "description": "Кол-во сообщений в секунду",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "si:/s" } },
   "yaxes": [
    { "format": "si:/s" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('host=$server', 'name=kafka_topics.MessagesInPerSec.Count')), 'In')"
    }
   ]
  }
 ]
}