{
 "title": "NetFlow: сенсоры (ASR)",
 "description": "Ответственный: -",
 "tags": [
  "dts",
  "netflow"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sensor",
    "query": "tag_values(device, name=~flow_monitor.*)"
   },
   {
    "name": "monitor",
    "query": "tag_values(monitor, device=$sensor)"
   }
  ]
 },
 "panels": [
  {
   "title": "Утилизация кэша $monitor",
   "type": "graph",
   "description": "Текущая утилизация кэша:\n- **Total** - размер кэша\n- **Used** - текущее количество потоков в кэше.\n\nПри переполении кэша возможна потеря данных",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "repeat": "monitor",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('device=$sensor', 'monitor=~${monitor:regex}', 'name=~flow_monitor.cache_.*'), 1), 'cache_', '')"
    }
   ]
  },
  {
   "title": "Утилизация кэша $monitor",
   "type": "graph",
   "description": "Текущая утилизация кэша:\n- **Total** - размер кэша\n- **Used** - текущее количество потоков в кэше.\n\nПри переполении кэша возможна потеря данных",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('device=$sensor', 'monitor=~${monitor:regex}', 'name=~flow_monitor.cache_.*'), 1), 'cache_', '')"
    }
   ]
  },
  {
   "title": "Выгрузка потоков из кэша",
   "type": "graph",
   "description": "Статистика выгрузки потоков из кэша:\n- **Total** - все выгруженные потоки\n- **Active** - по абсолютному таймеру \n- **Inactive** - по таймеру неактивности\n- **Emergency** - при переполнении кэша. За этой метрикой нужно следить.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "si: flows/s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(groupByNodes(perSecond(seriesByTag('device=$sensor', 'monitor=~${monitor:regex}', 'name=~flow_monitor.flows_aged')), 'sum', 1), 1), 'flows_aged_', '')"
    }
   ]
  },
  {
   "title": "Заполнение кэша",
   "type": "graph",
   "description": "Статистики заполнения кэша потоками:\n- **Added** - потоки, попавшие в кэш\n- **Missed** - утерянные потоки.\n\nПотоки теряются при переполнении кэша",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "si: flows/s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(groupByNodes(perSecond(seriesByTag('device=$sensor', 'monitor=~${monitor:regex}', 'name=~flow_monitor.flows_(added|missed)')), 'sum', 1), 1), 'flows_', '')"
    }
   ]
  }
 ]
}