{
 "title": "NetFlow: Коллекторы",
 "description": "Ответственный: -",
 "tags": [
  "dts",
  "netflow"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "tag_values(host, name=~vflow.*)"
   },
   {
    "name": "proto",
    "query": "NetFlow : netflowv9, sFlow : sflow"
   }
  ]
 },
 "panels": [
  {
   "title": "UDP packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('host=$host', 'name=vflow.vflow_${proto}_udp_packets')), 'UDP packets')"
    }
   ]
  },
  {
   "title": "UDP queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('host=$host', 'name=vflow.vflow_${proto}_udp_queue'), 'UDP queue')"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('host=$host', 'name=vflow.vflow_${proto}_workers'), 'workers')"
    }
   ]
  },
  {
   "title": "Decoded packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('host=$host', 'name=vflow.vflow_${proto}_decoded_packets')), 'Decoded packets')"
    }
   ]
  },
  {
   "title": "Message queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('host=$host', 'name= vflow.vflow_${proto}_message_queue'), 'Message queue')"
    }
   ]
  },
  {
   "title": "MQ errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('host=$host', 'name=vflow.vflow_${proto}_mq_error')), 'MQ errors')"
    }
   ]
  }
 ]
}