{
 "title": "NetFlow: Обзор системы",
 "description": "Ответственный: -",
 "tags": [
  "dts",
  "netflow"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Схема системы",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('servertype=dts-netflow', 'name=systemd.service.state'), '_name', 'host')"
    }
   ]
  },
  {
   "title": "Всего потоков",
   "type": "graph",
   "description": "Кол-во потоков в секунду",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "si:/s" } },
   "yaxes": [
    { "format": "si:/s" }
   ],
   "targets": [
    {
     "target": "alias(limit(sortByMaxima(scale(sumSeries(seriesByTag('name=netflow.flows')), 0.0166666666666667)), 10), 'Flows per second')"
    }
   ]
  },
  {
   "title": "Топ экспортеров",
   "type": "table",
   "description": "Топ 10 экспортеров ",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "si:/s" } },
   "targets": [
    {
     "target": "limit(sortByMaxima(aliasByTags(scale(seriesByTag('name=netflow.flows'), 0.0166666666666667), 'sensor')), 10)"
    }
   ]
  },
  {
   "title": "Проблемы",
   "type": "bosun-grafana7-panel",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 13 },
   "targets": [
    { "requestFilter": "filter=hasTag:tag1=dts-nf-*" }
   ]
  },
  {
   "title": "Сенсоры",
   "type": "graph",
   "description": "- **Total**: количество сенсоров, от которых есть данных за период\n- **Unknown**: количество неизвестных сенсоров (в БД нет соответствия имени и IP сенсора)",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=netflow.total_sensors'), 'Total')"
    },
    {
     "target": "alias(seriesByTag('name=netflow.unknown_sensors'), 'Unknown')"
    }
   ]
  }
 ]
}