{
 "title": "Remote Access VPN / OpenVPN",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "telegraf",
  "vpn"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "tag_values(host, name=~.*openvpn.*,)"
   }
  ]
 },
 "panels": [
  {
   "title": "Утилизация CPU",
   "type": "timeseries",
   "description": "Утилизация ядра №1, на котором работает openvpn",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "substr(aliasByTags(seriesByTag('host=~${host:regex}', 'name=system.cpu.usage_active', 'cpu=cpu1'), 'host'), 0, 1)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "description": "Uptime юнитов, отвечающих за работу openvpn ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=~${host:regex}', 'name=systemd.service.uptime'), 'host', '_name'), '.unix.tensor.ru.|.prod.pcidss.saby.ru.', ': ')"
    }
   ]
  },
  {
   "title": "Трафик",
   "type": "timeseries",
   "description": "Трафик на интерфейсе tun0",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(scale(perSecond(seriesByTag('host=~${host:regex}', 'name=~system.net.bytes*', 'interface=tun0')), 8, 0), 'host', 'name'), '(unix.tensor.ru.|.prod.pcidss.saby.ru.)system.net.bytes_recv', ': out'), '(.unix.tensor.ru.|.prod.pcidss.saby.ru.)system.net.bytes_sent', ': in')"
    }
   ]
  },
  {
   "title": "Количество клиентов",
   "type": "timeseries",
   "description": "Количество подключенных клиентов к серверу",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "substr(aliasByTags(seriesByTag('host=~${host:regex}', 'name=openvpn.openvpn_server_connected_clients'), 'host'), 0, 1)"
    }
   ]
  },
  {
   "title": "Пакеты",
   "type": "timeseries",
   "description": "Пакеты на интерфейсе tun0 ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(perSecond(seriesByTag('host=~${host:regex}', 'name=~system.net.packets*', 'interface=tun0')), 'host', 'name'), '(.unix.tensor.ru.|.prod.pcidss.saby.ru.)system.net.packets_recv', ': out'), '(.unix.tensor.ru.|.prod.pcidss.saby.ru.)system.net.packets_sent', ': in')"
    }
   ]
  },
  {
   "title": "Ошибки в логах",
   "type": "timeseries",
   "description": "Количество ошибок в логах OPENVPN",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(nonNegativeDerivative(seriesByTag('host=~${host:regex}', 'name=~openvpn.openvpn_.*_total')), 'host', 'name'), '(.unix.tensor.ru.|.prod.pcidss.saby.ru.)openvpn.openvpn_', ': ')"
    }
   ]
  }
 ]
}