{
 "title": "Remote Access VPN / Статистика серверов ААА",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "auth",
  "radius",
  "vpn"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "tag_values(host, host!=~.*unix.*, name=~.*freeradius.otp.*,)"
   }
  ]
 },
 "panels": [
  {
   "title": "VRRP role",
   "type": "stat",
   "description": "Роль сервера",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "repeat": "host",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "substr(aliasByTags(seriesByTag('contur=corp', 'name=vrrpInstance.vrrpInstanceState', 'host=${host}'), 'host'), 0, 1)"
    }
   ]
  },
  {
   "title": "OTP Statistics on $host",
   "type": "timeseries",
   "description": "Статистика по Отправленным/Введенным* OTP-кодам \n*Прим: Мы не фиксируем число доставленных OTP-кодов, а лишь то, что пользователь успешно прошел двухфакторную аутентификацию ",
   "gridPos": { "h": 12, "w": 10, "x": 3, "y": 0 },
   "repeat": "host",
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(nonNegativeDerivative(seriesByTag('name=~freeradius.otp_*', 'contur=corp', 'host=$host')), 'name'), '.*sent', 'Отправлено'), '.*valid', 'Введенно')"
    }
   ]
  },
  {
   "title": "Rest fail on $host",
   "type": "timeseries",
   "description": "Ошибки, фиксирующие проблему работы второго фактора ",
   "gridPos": { "h": 12, "w": 10, "x": 13, "y": 0 },
   "repeat": "host",
   "targets": [
    {
     "target": "aliasSub(aliasByTags(nonNegativeDerivative(seriesByTag('name=~freeradius.ravpn_rest_fail', 'contur=corp', 'host=$host')), 'name'), '.*rest.*', 'Ошибки')"
    }
   ]
  }
 ]
}