{
 "title": "Remote Access VPN / Балансировщики",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "telegraf",
  "vpn"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Балансировщик",
    "query": "tag_values(host, host=~.*lb.*-ravpn)"
   },
   {
    "name": "address_vurtual",
    "label": "Виртуальный сервер",
    "query": "tag_values(address, host=${host}, name=~ipvs_virtual_server.connections)"
   }
  ]
 },
 "panels": [
  {
   "title": "VRRP role",
   "type": "stat",
   "description": "Роль сервера",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=${host}', 'name=~vrrpInstance.vrrpInstanceState'), 'host')"
    }
   ]
  },
  {
   "title": "Соединения (Виртуальный сервер)",
   "type": "timeseries",
   "description": "Количество подключений к виртуальному серверу",
   "gridPos": { "h": 7, "w": 11, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(sum(seriesByTag('host=${host}', 'name=~ipvs_real_server.inactive_connections', 'virtual_address=~${address_vurtual:regex}')), 'virtual_address')"
    }
   ]
  },
  {
   "title": "Соединения (Реальные серверы)",
   "type": "timeseries",
   "description": "Количество подключений к виртуальным серверам",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=${host}', 'name=~ipvs_real_server.inactive_connections', 'virtual_address=~${address_vurtual:regex}'), 'address')"
    }
   ]
  },
  {
   "title": "Трафик (Виртуальный сервер)",
   "type": "timeseries",
   "description": "Трафик виртуального сервера ",
   "gridPos": { "h": 7, "w": 11, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "aliasByTags(scale(perSecond(seriesByTag('host=${host}', 'name=ipvs_virtual_server.bytes_in', 'address=~${address_vurtual:regex}')), 8, 0), 'address')"
    }
   ]
  },
  {
   "title": "Трафик (Реальные серверы)",
   "type": "timeseries",
   "description": "Трафик виртуального сервера",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "aliasByTags(scale(perSecond(seriesByTag('host=${host}', 'name=ipvs_real_server.bytes_in', 'virtual_address=~${address_vurtual:regex}')), 8, 0), 'address')"
    }
   ]
  },
  {
   "title": "Пакеты (Виртуальный сервер)",
   "type": "timeseries",
   "description": "Отправленные пакеты",
   "gridPos": { "h": 7, "w": 11, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('host=${host}', 'name=ipvs_virtual_server.pkts_in', 'address=~${address_vurtual:regex}')), 'address')"
    }
   ]
  },
  {
   "title": "Пакеты (Реальные серверы)",
   "type": "timeseries",
   "description": "Отправленные пакеты",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('host=${host}', 'name=ipvs_real_server.pkts_in', 'virtual_address=~${address_vurtual:regex}')), 'address')"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Утилизация CPU выбранного сервера",
   "gridPos": { "h": 7, "w": 11, "x": 2, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(seriesByTag('host=${host}', 'name=system.cpu.usage_active', 'cpu=cpu-total'), 'CPU', false)"
    }
   ]
  }
 ]
}