{
 "title": "Remote Access VPN / IP pools",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "vpn",
  "dts",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pool",
    "label": "Пул",
    "query": "tag_values(pool_name,host=dts-db1-ravpn.mgmt.tensor.ru)"
   }
  ]
 },
 "panels": [
  {
   "title": "Использование пула",
   "type": "stat",
   "description": "Использование конкретного пула ",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('name=~ravpn.pool.*', 'contur=corp', 'pool_name=${pool:regex}'), 'name'), 'ravpn.pool.addresses_total', 'Всего'), 'ravpn.pool.addresses_used', 'Занято')"
    }
   ]
  },
  {
   "title": "Утилизация пула",
   "type": "timeseries",
   "description": "Статистика использования адресов",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  framedipaddress AS \"IP-адрес\",\n  pool_key AS \"UID\",\n  username AS \"Пользователь\",\n  expiry_time AS \"Аренда истекает\",\n  expiry_time AS \"Через\"\nFROM\n  radippool\nWHERE\n  pool_name = '[[pool]]'\n  AND username LIKE '[[user:csv]]'\n  AND host(framedipaddress) LIKE '[[ip:csv]]'\n  AND expiry_time > now()\nORDER BY expiry_time DESC",
     "target": "alias(seriesByTag('name=~ravpn.pool.addresses_used', 'contur=corp', 'pool_name=${pool:regex}'), 'Использовано', false)"
    },
    {
     "rawSql": "SELECT\n  framedipaddress AS \"IP-адрес\",\n  pool_key AS \"UID\",\n  username AS \"Пользователь\",\n  expiry_time AS \"Аренда истекает\",\n  expiry_time AS \"Через\"\nFROM\n  radippool\nWHERE\n  pool_name = '[[pool]]'\n  AND username LIKE '[[user:csv]]'\n  AND host(framedipaddress) LIKE '[[ip:csv]]'\n  AND expiry_time > now()\nORDER BY expiry_time DESC",
     "target": "alias(seriesByTag('name=~ravpn.pool.addresses_total', 'contur=corp', 'pool_name=${pool:regex}'), 'Всего', false)"
    }
   ]
  },
  {
   "title": "Использование пула %",
   "type": "gauge",
   "description": "Использование конкретного пула  в %",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(#A, #B)",
     "targetFull": "divideSeries(aliasByTags(seriesByTag('name=ravpn.pool.addresses_total', 'contur=corp', 'pool_name=${pool:regex}'), 'name'), aliasByTags(seriesByTag('name=ravpn.pool.addresses_used', 'contur=corp', 'pool_name=${pool:regex}'), 'name'))"
    }
   ]
  },
  {
   "title": "Утилизация пула в %",
   "type": "timeseries",
   "description": "Статистика использования адресов",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(scale(divideSeries(#A, #B), 100, 0), 'Использовано %', false)",
     "targetFull": "alias(scale(divideSeries(alias(seriesByTag('name=~ravpn.pool.addresses_used', 'contur=corp', 'pool_name=${pool:regex}'), 'Занято', false), alias(seriesByTag('name=~ravpn.pool.addresses_total', 'contur=corp', 'pool_name=${pool:regex}'), 'Всего', false)), 100, 0), 'Использовано %', false)"
    }
   ]
  }
 ]
}