{
 "title": "RHV - Storage Domains Inventory Dashboard",
 "description": "Экран мониторинга инвентаризации доменов хранилища включает список инвентаризации доменов хранилища и использование диска. Ответственный:  Альбещенко М.Н. (АЦОД)",
 "tags": [
  "RHV",
  "Virtualization",
  "system",
  "Warehouse",
  "scripts"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "show_deleted", "label": "Show Deleted Entities?", "query": "No,Yes" },
   {
    "name": "datacenter_id",
    "label": "Data Center",
    "query": "SELECT DISTINCT  CAST ( datacenter_id AS varchar ) AS __value, CASE     WHEN delete_date IS NULL  \t    THEN datacenter_name \twhen delete_date is not null  \t     then datacenter_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')' END AS __text FROM v4_4_configuration_history_datacenters WHERE      history_id          IN              (  \t            SELECT MAX ( a.history_id )  \t\t        FROM v4_4_configuration_history_datacenters a  \t\t        GROUP BY a.datacenter_id \t        ) \tAND datacenter_id  \t    IN \t\t\t( \t\t\t     SELECT DISTINCT datacenter_id \t\t\t\t FROM v4_4_map_history_datacenters_storage_domains \t\t\t) \tAND \t   CASE  \t       WHEN '$show_deleted'='Yes' \t           THEN 1=1 \t\t   WHEN '$show_deleted'='No' \t\t       THEN v4_4_configuration_history_datacenters.delete_date ISNULL \t   END  \t\t"
   },
   {
    "name": "storage_id",
    "label": "Storage Domain",
    "query": "SELECT DISTINCT   CAST ( storage_domain_id AS varchar ) AS __value, CASE     WHEN delete_date IS NULL  \t    THEN storage_domain_name \tWHEN delete_date is not null  \t     THEN storage_domain_name || ' (Detached on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')' END AS __text FROM      ( \t\tSELECT  \t\t    v4_4_configuration_history_storage_domains.*,  \t\t    v4_4_map_history_datacenters_storage_domains.datacenter_id \t\tFROM \t\t    v4_4_configuration_history_storage_domains             LEFT JOIN              v4_4_map_history_datacenters_storage_domains             USING (storage_domain_id) \t) AS b WHERE      history_id          IN              (  \t            SELECT MAX ( a.history_id )  \t\t        FROM v4_4_configuration_history_storage_domains a  \t\t        GROUP BY a.storage_domain_id \t        ) \tAND datacenter_id IN ($datacenter_id) \tAND \t   CASE  \t       WHEN '$show_deleted'='Yes' \t           THEN 1=1 \t\t   WHEN '$show_deleted'='No' \t\t       THEN delete_date ISNULL \t   END "
   },
   {
    "name": "domain_type",
    "label": "Domain Type",
    "query": "SELECT DISTINCT           value AS __text,           enum_key AS __value FROM       ( \t \t\tSELECT        \t\t    enum_translator.*,       \t\t    v4_4_configuration_history_storage_domains.storage_domain_id      \t\tFROM  \t     \t\t    enum_translator     \t\t    LEFT JOIN \t         \t\t    v4_4_configuration_history_storage_domains\t     \t\t    ON  \t         \t\t        (  \t\t\t     \t\t\t\t\tenum_translator.enum_key =  \t\t\t\t \t\t\t\t\tv4_4_configuration_history_storage_domains.storage_domain_type \t\t\t\t\tAND v4_4_configuration_history_storage_domains.history_id \t\t\t\t\t    IN \t\t\t\t\t        (  \t\t\t\t\t\t\t\tSELECT MAX (a.history_id) \t\t\t\t\t\t\t\tFROM v4_4_configuration_history_storage_domains a \t\t\t\t\t\t\t\tGROUP BY a.storage_domain_id \t\t\t\t\t\t\t) \t\t\t\t)  \t) AS b  WHERE language_code = 'en_US'       AND enum_type ='STORAGE_DOMAIN_TYPE' AND storage_domain_id IN ($storage_id)"
   }
  ]
 },
 "panels": [
  { "title": "Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage Domains Inventory (BR47)",
   "type": "table-old",
   "description": "This report displays a inventory list of all storage domains of the selected data center.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "--BR47 - This query returns for a specific datacenter, the storage domains list,\n-- along with their configuration details, available disk size, \n-- used disk size and total, up to an hour back.\n-- storage_domain_type and storage_type will be returned in localised session language.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT\n    storage_domain_name,\n    v4_4_configuration_history_storage_domains.storage_domain_id,\n    a.value AS storage_domain_type,\n    b.value AS storage_type,\n    available_disk_size_gb, \n    used_disk_size_gb,\n    ( available_disk_size_gb + used_disk_size_gb ) AS total_size,\n    create_date,\n    delete_date\nFROM \n    v4_4_configuration_history_storage_domains\n    INNER JOIN v4_4_map_history_datacenters_storage_domains\n        ON \n            (\n                v4_4_configuration_history_storage_domains.storage_domain_id =\n                v4_4_map_history_datacenters_storage_domains.storage_domain_id\n                -- Here we filter by the datacenter chosen by the user\n                AND v4_4_map_history_datacenters_storage_domains.datacenter_id IN ($datacenter_id)\n                -- Here we get the latest map\n                AND v4_4_map_history_datacenters_storage_domains.history_id \n                    IN \n                        (\n                            SELECT MAX ( a.history_id )\n                            FROM v4_4_map_history_datacenters_storage_domains a\n                            GROUP BY a.storage_domain_id, a.datacenter_id\n                        )\n            )\n    LEFT OUTER JOIN \n        (\n            SELECT\n                enum_translator.enum_type,\n                enum_translator.enum_key,\n                enum_translator.value\n            FROM enum_translator\n            WHERE language_code = 'en_US'\n        ) AS a\n        ON \n            (\n                storage_domain_type = a.enum_key\n                AND a.enum_type = 'STORAGE_DOMAIN_TYPE'\n            )\n    LEFT OUTER JOIN \n        (\n            SELECT\n                enum_translator.enum_type,\n                enum_translator.enum_key,\n                enum_translator.value\n            FROM enum_translator\n            WHERE language_code = 'en_US'\n        ) AS b\n        ON \n            (\n                storage_type = b.enum_key\n                AND b.enum_type = 'STORAGE_TYPE'\n            )\n    LEFT OUTER JOIN \n        (\n                SELECT history_datetime, storage_domain_id, history_id, available_disk_size_gb, used_disk_size_gb \n                FROM v4_4_statistics_storage_domains_resources_usage_samples\n        ) AS samples\n        ON \n            (\n                v4_4_configuration_history_storage_domains.storage_domain_id =\n                samples.storage_domain_id\n                AND samples.history_id \n                    IN \n                        (\n                            SELECT MAX ( a.history_id )\n                            FROM             \n                                (   \n                                    SELECT history_datetime, history_id, storage_domain_id \n                                    FROM v4_4_statistics_storage_domains_resources_usage_samples\n                                ) AS a    \n                            GROUP BY a.storage_domain_id\n                        )\n            )\nWHERE\n    -- Show data only when the selected period is up to 24 hours back \n    $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\n    AND v4_4_configuration_history_storage_domains.storage_domain_id IN ($storage_id)\n    -- Here we filter by the storage type chosen by the user\n    -- If \"All\" storage types were chosen by the user then the\n    -- parameter \"P_Storage_Type\" equals to -1\n    AND storage_domain_type IN ($domain_type)\n    -- Here we get the storage domain latest configurations\n    AND v4_4_configuration_history_storage_domains.history_id \n        IN \n            (\n                SELECT MAX ( a.history_id )\n                FROM v4_4_configuration_history_storage_domains AS a\n                GROUP BY a.storage_domain_id\n            )\n    -- This will determine where deleted entities will be included in the report,\n    -- according to the user selection for \"show_deleted\" parameter\n    AND\n        CASE\n          WHEN '$show_deleted'='Yes'\n              THEN 1=1\n          WHEN '$show_deleted'='No'\n              THEN delete_date isnull\n        END\nORDER BY storage_domain_name"
    },
    {
     "rawSql": "--BR47 - This query returns for a specific datacenter, the storage domains list,\n-- along with their configuration details, available disk size, \n-- used disk size and total, up to an hour back.\n-- storage_domain_type and storage_type will be returned in localised session language.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT\n    storage_domain_name,\n    v4_4_configuration_history_storage_domains.storage_domain_id,\n    a.value AS storage_domain_type,\n    b.value AS storage_type,\n    available_disk_size_gb, \n    used_disk_size_gb,\n    ( available_disk_size_gb + used_disk_size_gb ) AS total_size,\n    create_date,\n    delete_date\nFROM \n    v4_4_configuration_history_storage_domains\n    INNER JOIN v4_4_map_history_datacenters_storage_domains\n        ON \n            (\n                v4_4_configuration_history_storage_domains.storage_domain_id =\n                v4_4_map_history_datacenters_storage_domains.storage_domain_id\n                -- Here we filter by the datacenter chosen by the user\n                AND v4_4_map_history_datacenters_storage_domains.datacenter_id IN ($datacenter_id)\n                -- Here we get the latest map\n                AND v4_4_map_history_datacenters_storage_domains.history_id \n                    IN \n                        (\n                            SELECT MAX ( a.history_id )\n                            FROM v4_4_map_history_datacenters_storage_domains a\n                            GROUP BY a.storage_domain_id, a.datacenter_id\n                        )\n            )\n    LEFT OUTER JOIN \n        (\n            SELECT\n                enum_translator.enum_type,\n                enum_translator.enum_key,\n                enum_translator.value\n            FROM enum_translator\n            WHERE language_code = 'en_US'\n        ) AS a\n        ON \n            (\n                storage_domain_type = a.enum_key\n                AND a.enum_type = 'STORAGE_DOMAIN_TYPE'\n            )\n    LEFT OUTER JOIN \n        (\n            SELECT\n                enum_translator.enum_type,\n                enum_translator.enum_key,\n                enum_translator.value\n            FROM enum_translator\n            WHERE language_code = 'en_US'\n        ) AS b\n        ON \n            (\n                storage_type = b.enum_key\n                AND b.enum_type = 'STORAGE_TYPE'\n            )\n    LEFT OUTER JOIN \n        (\n                SELECT history_datetime, storage_domain_id, history_id, available_disk_size_gb, used_disk_size_gb \n                FROM v4_4_statistics_storage_domains_resources_usage_hourly\n            UNION\n                SELECT history_datetime, storage_domain_id, history_id, available_disk_size_gb, used_disk_size_gb \n                FROM v4_4_statistics_storage_domains_resources_usage_daily\n                WHERE\n                    history_datetime <\n                        (\n                            SELECT MIN ( history_datetime )\n                            FROM v4_4_statistics_storage_domains_resources_usage_hourly\n                        )\n        ) AS hourly_daily\n        ON \n            (\n                v4_4_configuration_history_storage_domains.storage_domain_id =\n                hourly_daily.storage_domain_id\n                AND hourly_daily.history_id \n                    IN \n                        (\n                            SELECT MAX ( a.history_id )\n                            FROM             \n                                (   \n                                        SELECT history_datetime, history_id, storage_domain_id \n                                        FROM v4_4_statistics_storage_domains_resources_usage_hourly\n                                    UNION\n                                        SELECT history_datetime, history_id, storage_domain_id \n                                        FROM v4_4_statistics_storage_domains_resources_usage_daily\n                                ) AS a    \n                            GROUP BY a.storage_domain_id\n                        )\n            )\nWHERE\n    -- Show data only when the selected period is more then 24 hours back\n    $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\n    AND v4_4_configuration_history_storage_domains.storage_domain_id IN ($storage_id)\n    -- Here we filter by the storage type chosen by the user\n    -- If \"All\" storage types were chosen by the user then the\n    -- parameter \"P_Storage_Type\" equals to -1\n    AND storage_domain_type IN ($domain_type)\n    -- Here we get the storage domain latest configurations\n    AND v4_4_configuration_history_storage_domains.history_id \n        IN \n            (\n                SELECT MAX ( a.history_id )\n                FROM v4_4_configuration_history_storage_domains AS a\n                GROUP BY a.storage_domain_id\n            )\n    -- This will determine where deleted entities will be included in the report,\n    -- according to the user selection for \"show_deleted\" parameter\n    AND\n        CASE\n          WHEN '$show_deleted'='Yes'\n              THEN 1=1\n          WHEN '$show_deleted'='No'\n              THEN delete_date isnull\n        END\nORDER BY storage_domain_name"
    }
   ]
  },
  {
   "title": "Storage Domain Available Size (over time) (BR21)",
   "type": "graph",
   "description": "This report displays average available disk size for the selected data center and storage domain over a selected period.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "-- BR21 - This query returns for a specific storage domain\n-- the average available disk size per hour over the chosen period.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT DISTINCT\n    $__time(sub_query.history_datetime),\n    COALESCE \n        (\n            storage_domain_name,\n            MAX ( storage_domain_name ) over ( partition BY 1 ),\n            ''\n        ) AS storage_domain_name,\n    available_disk_size\nFROM \n    (\n        SELECT\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime,\n            AVG ( available_disk_size_gb ) AS available_disk_size\n        FROM\n            (\n                SELECT history_datetime, available_disk_size_gb, storage_domain_id \n                FROM v4_4_statistics_storage_domains_resources_usage_samples\n            ) AS samples,\n            v4_4_configuration_history_storage_domains\n        WHERE\n            -- Here we join the storage domain configurations table with the statistics table\n            v4_4_configuration_history_storage_domains.storage_domain_id =\n            samples.storage_domain_id\n            -- Here we filter by the storage domain chosen by the user\n            AND samples.storage_domain_id IN ($storage_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest storage domain configurations\n            AND v4_4_configuration_history_storage_domains.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_4_configuration_history_storage_domains a\n                        GROUP BY a.storage_domain_id\n                    )\n        GROUP BY\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime\n    ) AS sub_query\n-- Show data only when the selected period is up to 24 hours back \nWHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\nORDER BY sub_query.history_datetime"
    },
    {
     "rawSql": "-- BR21 - This query returns for a specific storage domain\n-- the average available disk size per hour over the chosen period.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT DISTINCT\n    $__time(sub_query.history_datetime),\n    COALESCE \n        (\n            storage_domain_name,\n            MAX ( storage_domain_name ) over ( partition BY 1 ),\n            ''\n        ) AS storage_domain_name,\n    available_disk_size\nFROM \n    (\n        SELECT\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime,\n            AVG ( available_disk_size_gb ) AS available_disk_size\n        FROM\n            (\n                    SELECT history_datetime, available_disk_size_gb, storage_domain_id \n                    FROM v4_4_statistics_storage_domains_resources_usage_hourly\n                UNION\n                    SELECT history_datetime, available_disk_size_gb, storage_domain_id\n                    FROM v4_4_statistics_storage_domains_resources_usage_daily\n                    WHERE\n                        history_datetime <\n                            (\n                                SELECT MIN ( history_datetime )\n                                FROM v4_4_statistics_storage_domains_resources_usage_hourly\n                            )\n            ) AS hourly_daily,\n            v4_4_configuration_history_storage_domains\n        WHERE\n            -- Here we join the the storage domain configurations table with the statistics table\n            v4_4_configuration_history_storage_domains.storage_domain_id =\n            hourly_daily.storage_domain_id\n            -- Here we filter by the storage domain chosen by the user\n            AND hourly_daily.storage_domain_id IN ($storage_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest storage domain configurations\n            AND v4_4_configuration_history_storage_domains.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_4_configuration_history_storage_domains a\n                        GROUP BY a.storage_domain_id\n                    )\n        GROUP BY\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime\n    ) AS sub_query\n-- Show data only when the selected period is more then 24 hours back\nWHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\nORDER BY sub_query.history_datetime"
    }
   ]
  },
  {
   "title": "Storage Domain Used Size (over time) (BR21)",
   "type": "graph",
   "description": "This report displays average used disk size for the selected data center and storage domain over a selected period.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "-- BR21 - This query returns for a specific storage domain\n-- the average used disk size per hour for the chosen period.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT DISTINCT\n    $__time(sub_query.history_datetime),\n    COALESCE \n        (\n            storage_domain_name,\n            MAX ( storage_domain_name ) over ( partition BY 1 ),\n            ''\n        ) AS storage_domain_name,\n    used_disk_size\nFROM \n    (\n        SELECT\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime,\n            AVG ( used_disk_size_gb ) AS used_disk_size\n        FROM\n            (\n                SELECT history_datetime, used_disk_size_gb, storage_domain_id \n                FROM v4_4_statistics_storage_domains_resources_usage_samples\n            ) AS samples,\n            v4_4_configuration_history_storage_domains\n        WHERE\n            -- Here we join the the storage domain configurations table with the statistics table\n            v4_4_configuration_history_storage_domains.storage_domain_id =\n            samples.storage_domain_id\n            -- Here we filter by the storage domain chosen by the user\n            AND samples.storage_domain_id IN ($storage_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest storage domain configurations\n            AND v4_4_configuration_history_storage_domains.history_id \n                IN \n                    (\n                    SELECT MAX ( a.history_id )\n                    FROM v4_4_configuration_history_storage_domains a\n                    GROUP BY a.storage_domain_id\n                    )\n        GROUP BY\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime\n    ) AS sub_query\n-- Show data only when the selected period is up to 24 hours back \nWHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\nORDER BY sub_query.history_datetime"
    },
    {
     "rawSql": "-- BR21 - This query returns for a specific storage domain\n-- the average used disk size per hour for the chosen period.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT DISTINCT\n    $__time(sub_query.history_datetime),\n    COALESCE \n        (\n            storage_domain_name,\n            MAX ( storage_domain_name ) over ( partition BY 1 ),\n            ''\n        ) AS storage_domain_name,\n    used_disk_size\nFROM \n    (\n        SELECT\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime,\n            AVG ( used_disk_size_gb ) AS used_disk_size\n        FROM\n            (\n                    SELECT history_datetime, used_disk_size_gb, storage_domain_id \n                    FROM v4_4_statistics_storage_domains_resources_usage_hourly\n                UNION\n                    SELECT history_datetime, used_disk_size_gb, storage_domain_id\n                    FROM v4_4_statistics_storage_domains_resources_usage_daily\n                    WHERE\n                        history_datetime <\n                            (\n                                SELECT MIN ( history_datetime )\n                                FROM v4_4_statistics_storage_domains_resources_usage_hourly\n                            )\n            ) AS hourly_daily,\n            v4_4_configuration_history_storage_domains\n        WHERE\n            -- Here we join the the storage domain configurations table with the statistics table\n            v4_4_configuration_history_storage_domains.storage_domain_id =\n            hourly_daily.storage_domain_id\n            -- Here we filter by the storage domain chosen by the user\n            AND hourly_daily.storage_domain_id IN ($storage_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest storage domain configurations\n            AND v4_4_configuration_history_storage_domains.history_id \n                IN \n                    (\n                    SELECT MAX ( a.history_id )\n                    FROM v4_4_configuration_history_storage_domains a\n                    GROUP BY a.storage_domain_id\n                    )\n        GROUP BY\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime\n    ) AS sub_query\n-- Show data only when the selected period is more then 24 hours back\nWHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\nORDER BY sub_query.history_datetime"
    }
   ]
  },
  {
   "title": "Storage Domain Total Size (over time) (BR21)",
   "type": "graph",
   "description": "This report displays used disk size versus available disk size ( total disk size ) for the selected data center and storage domain over a selected period.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "-- BR21 - This query returns for a specific storage domain\n-- the available disk size versus used disk size ( total disk size ), \n-- per hour for the chosen period.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT DISTINCT\n    $__time(sub_query.history_datetime),\n    COALESCE \n        (\n            storage_domain_name,\n            MAX ( storage_domain_name ) over ( partition BY 1 ),\n            ''\n        ) AS storage_domain_name,\n    used_disk_size AS \"( Used disk size )\",\n    available_disk_size AS \"( Available disk size )\"\n    --,( available_disk_size + used_disk_size ) AS \"( Total disk size )\"\nFROM \n    (\n        SELECT\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime,\n            AVG ( available_disk_size_gb ) AS available_disk_size,\n            AVG ( used_disk_size_gb ) AS used_disk_size\n        FROM\n            (\n                SELECT history_datetime, available_disk_size_gb, used_disk_size_gb, storage_domain_id \n                FROM v4_4_statistics_storage_domains_resources_usage_samples\n            ) AS samples,\n            v4_4_configuration_history_storage_domains\n        WHERE\n            -- Here we join the the storage domain configurations table with the statistics table\n            v4_4_configuration_history_storage_domains.storage_domain_id =\n            samples.storage_domain_id\n            -- Here we filter by the storage domain chosen by the user\n            AND samples.storage_domain_id IN ($storage_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest storage domain configurations\n            AND v4_4_configuration_history_storage_domains.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_4_configuration_history_storage_domains a\n                        GROUP BY a.storage_domain_id\n                    )\n        GROUP BY\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime\n    ) AS sub_query\n    -- Show data only when the selected period is up to 24 hours back \n    WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\n    ORDER BY sub_query.history_datetime"
    },
    {
     "rawSql": "-- BR21 - This query returns for a specific storage domain\n-- the available disk size versus used disk size ( total disk size ), \n-- per hour for the chosen period.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT DISTINCT\n    $__time(sub_query.history_datetime),\n    COALESCE \n        (\n            storage_domain_name,\n            MAX ( storage_domain_name ) over ( partition BY 1 ),\n            ''\n        ) AS storage_domain_name,\n    used_disk_size AS \"( Used disk size )\",\n    available_disk_size AS \"( Available disk size )\"\n    --,( available_disk_size + used_disk_size ) AS \"( Total disk size )\"\nFROM \n    (\n        SELECT\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime,\n            AVG ( available_disk_size_gb ) AS available_disk_size,\n            AVG ( used_disk_size_gb ) AS used_disk_size\n        FROM\n            (\n                    SELECT history_datetime, available_disk_size_gb, used_disk_size_gb, storage_domain_id \n                    FROM v4_4_statistics_storage_domains_resources_usage_hourly\n                UNION\n                    SELECT history_datetime, available_disk_size_gb, used_disk_size_gb, storage_domain_id\n                    FROM v4_4_statistics_storage_domains_resources_usage_daily\n                    WHERE\n                        history_datetime <\n                            (\n                                SELECT MIN ( history_datetime )\n                                FROM v4_4_statistics_storage_domains_resources_usage_hourly\n                            )\n            ) AS hourly_daily,\n            v4_4_configuration_history_storage_domains\n        WHERE\n            -- Here we join the the storage domain configurations table with the statistics table\n            v4_4_configuration_history_storage_domains.storage_domain_id =\n            hourly_daily.storage_domain_id\n            -- Here we filter by the storage domain chosen by the user\n            AND hourly_daily.storage_domain_id IN ($storage_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest storage domain configurations\n            AND v4_4_configuration_history_storage_domains.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_4_configuration_history_storage_domains a\n                        GROUP BY a.storage_domain_id\n                    )\n        GROUP BY\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime\n    ) AS sub_query\n    -- Show data only when the selected period is more then 24 hours back\n    WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\n    ORDER BY sub_query.history_datetime"
    }
   ]
  },
  {
   "title": "Storage Domain Total Used Size (over time) (BR21)",
   "type": "graph",
   "description": "This report displays total used disk size for the selected data center and storage domain over a selected period.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "-- BR21 - This query returns for a specific storage domain\n-- the total used disk size per hour for the chosen period.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT DISTINCT\n    $__time(sub_query.history_datetime),\n    COALESCE \n        (\n            storage_domain_name,\n            MAX ( storage_domain_name ) over ( partition BY 1 ),\n            ''\n        ) AS storage_domain_name,\n    used_disk_size\nFROM \n    (\n        SELECT\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime,\n            AVG ( used_disk_size_gb ) AS used_disk_size\n        FROM\n            (\n                SELECT history_datetime, used_disk_size_gb, storage_domain_id \n                FROM v4_4_statistics_storage_domains_resources_usage_samples\n            ) AS samples,\n            v4_4_configuration_history_storage_domains\n        WHERE\n            -- Here we join the the storage domain configurations table with the statistics table\n            v4_4_configuration_history_storage_domains.storage_domain_id =\n            samples.storage_domain_id\n            -- Here we filter by the storage domain chosen by the user\n            AND samples.storage_domain_id IN ($storage_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest storage domain configurations\n            AND v4_4_configuration_history_storage_domains.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_4_configuration_history_storage_domains a\n                        GROUP BY a.storage_domain_id\n                    )\n        GROUP BY\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime\n    ) AS sub_query\n-- Show data only when the selected period is up to 24 hours back \nWHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\nORDER BY sub_query.history_datetime"
    },
    {
     "rawSql": "-- BR21 - This query returns for a specific storage domain\n-- the total used disk size per hour for the chosen period.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT DISTINCT\n    $__time(sub_query.history_datetime),\n    COALESCE \n        (\n            storage_domain_name,\n            MAX ( storage_domain_name ) over ( partition BY 1 ),\n            ''\n        ) AS storage_domain_name,\n    used_disk_size\nFROM \n    (\n        SELECT\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime,\n            AVG ( used_disk_size_gb ) AS used_disk_size\n        FROM\n            (\n                    SELECT history_datetime, used_disk_size_gb, storage_domain_id \n                    FROM v4_4_statistics_storage_domains_resources_usage_hourly\n                UNION\n                    SELECT history_datetime, used_disk_size_gb, storage_domain_id\n                    FROM v4_4_statistics_storage_domains_resources_usage_daily\n                    WHERE\n                        history_datetime <\n                            (\n                                SELECT MIN ( history_datetime )\n                                FROM v4_4_statistics_storage_domains_resources_usage_hourly\n                            )\n            ) AS hourly_daily,\n            v4_4_configuration_history_storage_domains\n        WHERE\n            -- Here we join the the storage domain configurations table with the statistics table\n            v4_4_configuration_history_storage_domains.storage_domain_id =\n            hourly_daily.storage_domain_id\n            -- Here we filter by the storage domain chosen by the user\n            AND hourly_daily.storage_domain_id IN ($storage_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest storage domain configurations\n            AND v4_4_configuration_history_storage_domains.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_4_configuration_history_storage_domains a\n                        GROUP BY a.storage_domain_id\n                    )\n        GROUP BY\n            v4_4_configuration_history_storage_domains.storage_domain_name,\n            history_datetime\n    ) AS sub_query\n-- Show data only when the selected period is more then 24 hours back\nWHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\nORDER BY sub_query.history_datetime"
    }
   ]
  }
 ]
}