{
 "title": "RHV - Inventory Dashboard",
 "description": "Панель мониторинга инвентаризации отображает отчеты с данными для каждого центра обработки данных ( хосты, настроенные виртуальные машины, процессор, память и использование диска). Ответственный:  Альбещенко М.Н. (АЦОД)",
 "tags": [
  "RHV",
  "Virtualization",
  "system",
  "Warehouse",
  "scripts"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datacenter_id",
    "label": "Data Center",
    "query": "SELECT  datacenter_name AS __text, datacenter_id AS __value FROM v4_4_latest_configuration_datacenters"
   }
  ]
 },
 "panels": [
  { "title": "Data Centers Inventory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Center Inventory (BR48)",
   "type": "table-old",
   "description": "This report displays for each data center the number of hosts and configured vms",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "-- BR48 - This query returns the\n-- average number of hosts and configured VMs \n-- in each data center\n\nSELECT\n    tag_name,\n    datacenter_name,\n    datacenter_description,\n    SUM ( number_of_hosts ) AS number_of_hosts,\n    SUM ( total_configured_vms ) AS total_configured_vms,\n    SUM ( num_of_running_vms ) AS num_of_running_vms \nFROM \n    (\n        SELECT\n            COALESCE ( tag_name, 'Unknown' ) AS tag_name,\n            datacenter_name,\n            datacenter_description,\n            COUNT( DISTINCT host_id ) AS number_of_hosts,\n            num_of_vms.num_of_running_vms,\n            num_of_vms.total_configured_vms\n        FROM  \n            v4_4_latest_configuration_datacenters\n            INNER JOIN v4_4_latest_configuration_clusters\n                ON \n                    (\n                        v4_4_latest_configuration_datacenters.datacenter_id =\n                        v4_4_latest_configuration_clusters.datacenter_id\n                    )\n            INNER JOIN v4_4_latest_configuration_hosts\n                ON \n                    (\n                        v4_4_latest_configuration_clusters.cluster_id =\n                        v4_4_latest_configuration_hosts.cluster_id\n                    )\n            LEFT OUTER JOIN v4_4_latest_tags_relations\n                ON \n                    (\n                        v4_4_latest_configuration_hosts.host_id =\n                        v4_4_latest_tags_relations.entity_id\n                        AND v4_4_latest_tags_relations.entity_type = 3\n                    )\n            LEFT OUTER JOIN v4_4_latest_tags_details\n                ON \n                    (\n                        v4_4_latest_tags_relations.parent_id =\n                        v4_4_latest_tags_details.tag_id\n                    )\n            LEFT OUTER JOIN \n            (\n                SELECT\n                    vm_count.cluster_id,\n                    SUM \n                        (\n                            CASE\n                                WHEN vm_count.vm_status = 1\n                                    THEN vm_count.num_of_vms\n                                ELSE 0\n                            END\n                        ) AS num_of_running_vms,\n                    SUM ( vm_count.num_of_vms ) AS total_configured_vms\n                FROM \n                    (\n                        SELECT\n                            a.cluster_id AS cluster_id,\n                            hourly_daily.vm_status AS vm_status,\n                            COUNT ( DISTINCT a.vm_id ) AS num_of_vms\n                        FROM \n                            (\n                                SELECT * FROM v4_4_statistics_vms_resources_usage_hourly\n                                UNION\n                                SELECT * FROM v4_4_statistics_vms_resources_usage_daily\n                            ) AS hourly_daily\n                            INNER JOIN v4_4_latest_configuration_vms a\n                                ON \n                                    (\n                                        a.vm_id =\n                                        hourly_daily.vm_id\n                                    )\n                        WHERE\n                            hourly_daily.history_id \n                                IN \n                                    (\n                                        SELECT MAX ( history_id )\n                                        FROM \n                                            (\n                                                SELECT * FROM v4_4_statistics_vms_resources_usage_hourly\n                                                UNION\n                                                SELECT * FROM v4_4_statistics_vms_resources_usage_daily\n                                            ) AS b\n                                        GROUP BY vm_id\n                                    )\n                        GROUP BY a.cluster_id, hourly_daily.vm_status\n                    ) AS vm_count\n                GROUP BY cluster_id\n            ) AS num_of_vms\n                ON \n                    (\n\t\t                num_of_vms.cluster_id =\n\t\t                v4_4_latest_configuration_clusters.cluster_id\n                    )\n        WHERE v4_4_latest_configuration_datacenters.datacenter_id IN ($datacenter_id)\n        GROUP BY\n            tag_name,\n            datacenter_name,\n            datacenter_description,\n            num_of_vms.num_of_running_vms,\n            num_of_vms.total_configured_vms\n    ) AS dc\nGROUP BY\n    tag_name,\n    datacenter_name,\n    datacenter_description"
    }
   ]
  },
  {
   "title": "CPU Usage and Overcommit (BR48)",
   "type": "table-old",
   "description": "This report displays CPU usage and overcommit for each data center. ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "-- BR48 - This query returns the\n-- average number of CPU Cores, Physical Memory and disk usage\n-- for the vms in each data center.\n\nSELECT\n    tag_name,\n    datacenter_name,\n    datacenter_description,\n    SUM ( total_hosts_num_of_cpus) AS total_hosts_num_of_cpus,\n    SUM ( total_vms_cpu_cores ) AS total_vms_cpu_cores,\n    SUM ( cpu_cores_running ) AS cpu_cores_running,\n    CASE\n        WHEN SUM ( total_hosts_num_of_cpus ) = 0 \n            THEN NULL\n        ELSE ( SUM ( total_vms_cpu_cores ) / SUM ( total_hosts_num_of_cpus ) )\n    END AS \"cpu_over_commit\",\n    CASE\n        WHEN SUM ( total_hosts_num_of_cpus ) = 0\n            THEN NULL\n        ELSE ( SUM ( cpu_cores_running ) / SUM ( total_hosts_num_of_cpus ) )\n    END AS \"cpu_usage_ratio\"\nFROM \n    (\n        SELECT\n            COALESCE ( tag_name, 'Unknown' ) AS tag_name,\n            datacenter_name,\n            datacenter_description,\n            SUM \n                ( \n                    COALESCE ( v4_4_latest_configuration_hosts.number_of_cores, 0 )\n                ) AS total_hosts_num_of_cpus,\n            cpu_memory_allocation.total_vms_cpu_cores,\n            cpu_memory_allocation.cpu_cores_running\n        FROM  \n            v4_4_latest_configuration_datacenters\n            INNER JOIN v4_4_latest_configuration_clusters\n                ON \n                    (\n                        v4_4_latest_configuration_datacenters.datacenter_id =\n                        v4_4_latest_configuration_clusters.datacenter_id\n                    )\n            INNER JOIN v4_4_latest_configuration_hosts\n                ON \n                    (\n                        v4_4_latest_configuration_clusters.cluster_id =\n                        v4_4_latest_configuration_hosts.cluster_id\n                    )\n            LEFT OUTER JOIN v4_4_latest_tags_relations\n                ON \n                    (\n                        v4_4_latest_configuration_hosts.host_id =\n                        v4_4_latest_tags_relations.entity_id\n                        AND v4_4_latest_tags_relations.entity_type = 3\n                    )\n            LEFT OUTER JOIN v4_4_latest_tags_details\n                ON \n                    (\n                        v4_4_latest_tags_relations.parent_id =\n                        v4_4_latest_tags_details.tag_id\n                    )\n            LEFT OUTER JOIN \n            (\n                SELECT\n                    a.cluster_id,\n                    SUM \n                        ( \n                            COALESCE ( v4_4_configuration_history_vms.cpu_per_socket, 0 ) *\n                            COALESCE ( v4_4_configuration_history_vms.number_of_sockets, 0 ) \n                        ) AS total_vms_cpu_cores,\n                    SUM \n                        (\n                            CASE\n                                WHEN hourly_daily.vm_status = 1\n                                    THEN COALESCE ( v4_4_configuration_history_vms.cpu_per_socket, 0 ) * COALESCE ( v4_4_configuration_history_vms.number_of_sockets, 0 )\n                                ELSE 0\n                            END\n                        ) AS cpu_cores_running\n                FROM\n                    ( \n                        SELECT * FROM v4_4_statistics_vms_resources_usage_hourly\n                        UNION\n                        SELECT * FROM v4_4_statistics_vms_resources_usage_daily\n                    ) AS hourly_daily\n                    INNER JOIN v4_4_configuration_history_vms\n                        ON \n                            (\n                                v4_4_configuration_history_vms.history_id =\n                                hourly_daily.vm_configuration_version\n                            )\n                    INNER JOIN v4_4_latest_configuration_vms a\n                        ON \n                            (\n                                a.vm_id =\n                                hourly_daily.vm_id\n                            )\n                WHERE\n                    hourly_daily.history_id \n                        IN \n                            (\n                                SELECT MAX ( history_id )\n                                FROM \n                                    (\n                                        SELECT * FROM v4_4_statistics_vms_resources_usage_hourly\n                                        UNION\n                                        SELECT * FROM v4_4_statistics_vms_resources_usage_daily\n                                    ) AS b\n                                GROUP BY vm_id\n                            )\n                GROUP BY a.cluster_id\n            ) AS cpu_memory_allocation\n                ON \n                    (\n                        cpu_memory_allocation.cluster_id =\n                        v4_4_latest_configuration_clusters.cluster_id\n                    )\n        WHERE v4_4_latest_configuration_datacenters.datacenter_id IN ($datacenter_id)\n        GROUP BY\n            tag_name,\n            datacenter_name,\n            datacenter_description,\n            cpu_memory_allocation.total_vms_cpu_cores,\n            cpu_memory_allocation.cpu_cores_running\n    ) AS dc\nGROUP BY\n    tag_name,\n    datacenter_name,\n    datacenter_description"
    }
   ]
  },
  {
   "title": "Memory Usage and Overcommit (BR48)",
   "type": "table-old",
   "description": "This report displays memory usage and overcommit for each data center. ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "-- BR48 - This query returns the\n-- average number of CPU Cores, Physical Memory and disk usage\n-- for the vms in each data center.\n\nSELECT\n    tag_name,\n    datacenter_name,\n    datacenter_description,\n    SUM ( total_hosts_mem ) AS total_hosts_mem,\n    SUM ( total_vms_mem ) AS total_vms_mem,\n    SUM ( mem_running ) AS mem_running,\n    CASE\n        WHEN SUM ( total_hosts_mem ) = 0\n            THEN NULL\n        ELSE ( SUM ( total_vms_mem ) / SUM ( total_hosts_mem ) )\n    END AS \"memory_over_commit\",\n    CASE\n        WHEN SUM ( total_hosts_mem ) = 0\n            THEN NULL\n        ELSE ( SUM ( mem_running ) / SUM ( total_hosts_mem ) ) \n    END AS \"memory_usage_ratio\"\nFROM \n    (\n        SELECT\n            COALESCE( tag_name, 'Unknown' ) AS tag_name,\n            datacenter_name,\n            datacenter_description,\n            ROUND ( CAST ( SUM ( COALESCE ( v4_4_latest_configuration_hosts.memory_size_mb, 0.00 ) ) AS FLOAT ) :: numeric / 1024, 2 ) AS total_hosts_mem,\n            cpu_memory_allocation.total_vms_mem,\n            cpu_memory_allocation.mem_running\n        FROM  \n            v4_4_latest_configuration_datacenters\n            INNER JOIN v4_4_latest_configuration_clusters\n                ON \n                    (\n                        v4_4_latest_configuration_datacenters.datacenter_id =\n                        v4_4_latest_configuration_clusters.datacenter_id\n                    )\n            INNER JOIN v4_4_latest_configuration_hosts\n                ON \n                    (\n                        v4_4_latest_configuration_clusters.cluster_id =\n                        v4_4_latest_configuration_hosts.cluster_id\n                    )\n            LEFT OUTER JOIN v4_4_latest_tags_relations\n                ON \n                    (\n                        v4_4_latest_configuration_hosts.host_id =\n                        v4_4_latest_tags_relations.entity_id\n                        AND v4_4_latest_tags_relations.entity_type = 3\n                    )\n            LEFT OUTER JOIN v4_4_latest_tags_details\n                ON \n                    (\n                        v4_4_latest_tags_relations.parent_id =\n                        v4_4_latest_tags_details.tag_id\n                    )\n            LEFT OUTER JOIN \n            (\n                SELECT\n                    a.cluster_id,\n                    ROUND ( CAST ( SUM ( COALESCE ( v4_4_configuration_history_vms.memory_size_mb, 0.00 ) )  AS FLOAT ) :: numeric / 1024, 2 ) AS total_vms_mem,\n                    ROUND ( CAST ( SUM \n                        (\n                            CASE\n                                WHEN hourly_daily.vm_status = 1\n                                    THEN COALESCE ( v4_4_configuration_history_vms.memory_size_mb, 0.00 )\n                                ELSE 0.00\n                            END \n                        ) AS FLOAT ) :: numeric / 1024, 2 ) AS mem_running\n                FROM\n                    ( \n                        SELECT * FROM v4_4_statistics_vms_resources_usage_hourly\n                        UNION\n                        SELECT * FROM v4_4_statistics_vms_resources_usage_daily\n                    ) AS hourly_daily\n                    INNER JOIN v4_4_configuration_history_vms\n                        ON \n                            (\n                                v4_4_configuration_history_vms.history_id =\n                                hourly_daily.vm_configuration_version\n                            )\n                    INNER JOIN v4_4_latest_configuration_vms a\n                        ON \n                            (\n                                a.vm_id =\n                                hourly_daily.vm_id\n                            )\n                WHERE\n                    hourly_daily.history_id \n                        IN \n                            (\n                                SELECT MAX ( history_id )\n                                FROM \n                                    ( \n                                        SELECT * FROM v4_4_statistics_vms_resources_usage_hourly\n                                        UNION\n                                        SELECT * FROM v4_4_statistics_vms_resources_usage_daily\n                                    ) AS b\n                                GROUP BY vm_id\n                            )\n                GROUP BY a.cluster_id\n            ) AS cpu_memory_allocation\n                ON \n                    (\n                        cpu_memory_allocation.cluster_id =\n                        v4_4_latest_configuration_clusters.cluster_id\n                    )\n        WHERE v4_4_latest_configuration_datacenters.datacenter_id IN ($datacenter_id)\n        GROUP BY\n            tag_name,\n            datacenter_name,\n            datacenter_description,\n            cpu_memory_allocation.total_vms_mem,\n            cpu_memory_allocation.mem_running\n    ) AS dc\nGROUP BY\n    tag_name,\n    datacenter_name,\n    datacenter_description"
    }
   ]
  },
  {
   "title": "Disk Usage and Overcommit (BR48)",
   "type": "table-old",
   "description": "This report displays disk usage and overcommit for each data center. ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "-- BR48 - This query returns the\n-- average number of CPU Cores, Physical Memory and disk usage\n-- for the vms in each data center.\n\nSELECT\n    tag_name,\n    datacenter_name,\n    datacenter_description,\n    dc_used_disk_size_gb,\n    dc_available_disk_size_gb ,\n    dc_total_disk_size_gb,\n    vms_allocated_disk_size_gb,\n    vm_disk_actual_size_gb,\n    CASE \n        WHEN dc_total_disk_size_gb = 0\n            THEN NULL\n        ELSE ( vms_allocated_disk_size_gb / dc_total_disk_size_gb ) \n    END AS \"disk_over_commit\",\n    CASE    \n        WHEN dc_total_disk_size_gb = 0\n            THEN NULL\n        ELSE ( vm_disk_actual_size_gb / dc_total_disk_size_gb ) \n    END AS \"disk_usage_ratio\"\nFROM \n    (\n        SELECT\n            COALESCE( tag_name, 'Unknown' ) AS tag_name,\n            datacenter_name,\n            datacenter_description,\n            dc_storage.dc_used_disk_size_gb,\n            dc_storage.dc_available_disk_size_gb,\n            dc_storage.dc_total_disk_size_gb,\n            ROUND ( CAST ( vms_storage.vms_allocated_disk_size_gb  AS float ):: numeric, 2 ) AS vms_allocated_disk_size_gb,\n            ROUND ( CAST ( vms_storage.vm_disk_actual_size_gb AS FLOAT ) :: numeric, 2 ) AS vm_disk_actual_size_gb\n        FROM  \n            v4_4_latest_configuration_datacenters\n            INNER JOIN v4_4_latest_configuration_clusters\n                ON \n                    (\n                        v4_4_latest_configuration_datacenters.datacenter_id =\n                        v4_4_latest_configuration_clusters.datacenter_id\n                    )\n            INNER JOIN v4_4_latest_configuration_hosts\n                ON \n                    (\n                        v4_4_latest_configuration_clusters.cluster_id =\n                        v4_4_latest_configuration_hosts.cluster_id\n                    )\n            LEFT OUTER JOIN v4_4_latest_tags_relations\n                ON \n                    (\n                        v4_4_latest_configuration_hosts.host_id =\n                        v4_4_latest_tags_relations.entity_id\n                        AND v4_4_latest_tags_relations.entity_type = 3\n                    )\n            LEFT OUTER JOIN v4_4_latest_tags_details\n                ON \n                    (\n                        v4_4_latest_tags_relations.parent_id =\n                        v4_4_latest_tags_details.tag_id\n                    )\n            LEFT OUTER JOIN \n            (\n                SELECT\n                    datacenter_id,\n                    SUM (hourly_daily.used_disk_size_gb) AS dc_used_disk_size_gb,\n                    SUM (hourly_daily.available_disk_size_gb) AS dc_available_disk_size_gb,\n                    SUM (hourly_daily.available_disk_size_gb + hourly_daily.used_disk_size_gb) AS dc_total_disk_size_gb\n                FROM \n                    v4_4_latest_configuration_storage_domains\n                    INNER JOIN v4_4_latest_map_datacenters_storage_domains\n                        ON \n                            (\n                                v4_4_latest_configuration_storage_domains.storage_domain_id =\n                                v4_4_latest_map_datacenters_storage_domains.storage_domain_id\n                            )\n                    LEFT OUTER JOIN \n                    (\n                        SELECT * FROM v4_4_statistics_storage_domains_resources_usage_hourly\n                        UNION\n                        SELECT * FROM v4_4_statistics_storage_domains_resources_usage_daily\n                    ) AS hourly_daily\n                        ON \n                            (\n                                v4_4_latest_configuration_storage_domains.storage_domain_id =\n                                hourly_daily.storage_domain_id\n                                AND hourly_daily.history_id \n                                    IN \n                                        (\n                                            SELECT MAX ( a.history_id )\n                                            FROM\n                                                (\n                                                    SELECT * FROM v4_4_statistics_storage_domains_resources_usage_hourly\n                                                    UNION\n                                                    SELECT * FROM v4_4_statistics_storage_domains_resources_usage_daily\n                                                ) AS a\n                                            GROUP BY a.storage_domain_id\n                                        )\n                            )\n                WHERE\n                    -- Here we filter by the \"Data\" storage type\n                    storage_domain_type IN ( 0, 1 )\n                GROUP BY datacenter_id\n            ) AS dc_storage\n                ON \n                    (\n                        dc_storage.datacenter_id =\n                        v4_4_latest_configuration_datacenters.datacenter_id\n                    )\n            LEFT OUTER JOIN \n            (\n                SELECT\n                    datacenter_id,\n                    SUM ( v4_4_latest_configuration_vms_disks.vm_disk_size_mb ) * 0.0009765625 AS vms_allocated_disk_size_gb,\n                    SUM ( hourly_daily.vm_disk_actual_size_mb ) * 0.0009765625 AS vm_disk_actual_size_gb\n                FROM \n                    v4_4_latest_configuration_storage_domains\n                    INNER JOIN v4_4_latest_map_datacenters_storage_domains\n                        ON \n                            (\n                                v4_4_latest_map_datacenters_storage_domains.storage_domain_id =\n                                v4_4_latest_configuration_storage_domains.storage_domain_id\n                            )\n                    INNER JOIN v4_4_latest_configuration_vms_disks\n                        ON \n                            (\n                                v4_4_latest_configuration_storage_domains.storage_domain_id =\n                                v4_4_latest_configuration_vms_disks.storage_domain_id\n                            )\n                    LEFT OUTER JOIN \n                    (\n                        SELECT * FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                        UNION\n                        SELECT * FROM v4_4_statistics_vms_disks_resources_usage_daily\n                    ) AS hourly_daily\n                        ON \n                            (\n                                v4_4_latest_configuration_vms_disks.vm_disk_id =\n                                hourly_daily.vm_disk_id\n                                AND hourly_daily.history_id \n                                    IN \n                                        (\n                                            SELECT MAX ( a.history_id )\n                                            FROM \n                                                (\n                                                    SELECT * FROM v4_4_statistics_vms_disks_resources_usage_hourly\n                                                    UNION\n                                                    SELECT * FROM v4_4_statistics_vms_disks_resources_usage_daily\n                                                ) AS a\n                                            GROUP BY a.vm_disk_id\n                                        )\n                            )\n                WHERE\n                    -- Here we filter by the \"Data\" storage type\n                    storage_domain_type IN ( 0, 1 )\n                GROUP BY datacenter_id\n            ) AS vms_storage\n                ON \n                    (\n                        vms_storage.datacenter_id =\n                        v4_4_latest_configuration_datacenters.datacenter_id\n                    )\n        WHERE v4_4_latest_configuration_datacenters.datacenter_id IN ($datacenter_id)\n        GROUP BY\n            tag_name,\n            datacenter_name,\n            datacenter_description,\n            dc_storage.dc_used_disk_size_gb,\n            dc_storage.dc_available_disk_size_gb,\n            dc_storage.dc_total_disk_size_gb,\n            vms_storage.vms_allocated_disk_size_gb,\n            vms_storage.vm_disk_actual_size_gb\n    ) AS dc\nGROUP BY\n    tag_name,\n    datacenter_name,\n    datacenter_description,\n    dc_used_disk_size_gb,\n    dc_available_disk_size_gb,\n    dc_total_disk_size_gb,\n    vms_allocated_disk_size_gb,\n    vm_disk_actual_size_gb"
    }
   ]
  }
 ]
}