{
 "title": "Satellite",
 "description": "Ответственный: Альбещенко М.Н.  и  Борбат Я.Д. (АЦОД)",
 "tags": [ "telegraf" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services Status",
   "type": "stat",
   "description": "Состояние всех systemd юнитов Satellite.\n",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "maxSeries(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'name=systemd_units.active_code', 'servertype=satellite'), '_name'))"
    }
   ]
  },
  {
   "title": "SPR Status",
   "type": "stat",
   "description": "Статус капсулей Satellite ",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~sat.status_components.smart_proxies.(|)'), 'name'), 'sat.status_components.smart_proxies.', '')"
    }
   ]
  },
  {
   "title": "Foreman DataBase Status",
   "type": "stat",
   "description": "Статус базы данных Satellite",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=sat.status_components.database')"
    }
   ]
  },
  {
   "title": "Compute Ressurse Status",
   "type": "stat",
   "description": "Статус вычислительных ресурсов Satellite.\nВычислительный ресурс в Satellite используется для определения информации о вашем поставщике вычислительных ресурсов, таком как RHEV, VMWare",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~sat.status_components.compute_resources.(|)'), 'name'), 'sat.status_components.compute_resources.', '')"
    }
   ]
  },
  {
   "title": "Katello Services Status",
   "type": "stat",
   "description": "Статус katello сервисов Satellite",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~sat.status_components.katello.(|)'), 'name'), 'sat.status_components.katello.', '')"
    }
   ]
  },
  {
   "title": "Satellite Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Hosts",
     "type": "stat",
     "description": "Число зарегистрированных хостов в Satellite",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=sat.hosts.count')"
      }
     ]
    },
    {
     "title": "Host Last Report > 1 mounth",
     "type": "stat",
     "description": "Число хостов в Satellite с последним репортом больше месяца",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=sat.last_report_host')"
      }
     ]
    },
    {
     "title": "Number of Host with OS",
     "type": "bargauge",
     "description": "Число хостов в Satellite по операционным системам",
     "gridPos": { "h": 20, "w": 5, "x": 8, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~sat.count_host_os.(|)'), 'name'), 'sat.count_host_os.', '')"
      }
     ]
    },
    {
     "title": "Number of Hosts in Capsule",
     "type": "bargauge",
     "description": "Число хостов в Satellite на капсуль",
     "gridPos": { "h": 12, "w": 5, "x": 13, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~sat.count_host_capsule.(|)'), 'name'), 'sat.count_host_capsule.', '')"
      }
     ]
    },
    {
     "title": "Last Sync Time",
     "type": "stat",
     "description": "Время последней синхронизации капсулей Satellite",
     "gridPos": { "h": 20, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(scale(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~status_sync_spr.last_sync_time.(|)'), 1000, 0), 'name'), 'status_sync_spr.last_sync_time.', '')"
      }
     ]
    },
    {
     "title": "Tasks running > 24h",
     "type": "stat",
     "description": "Число тасок, длящиеся больше 24 часов ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=sat_tasks_hung.count'), 'name')"
      }
     ]
    },
    {
     "title": "Tasks in State = Paused",
     "type": "stat",
     "description": "Число тасок, в состоянии паузы",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=sat_tasks_paused.count'), 'name')"
      }
     ]
    },
    {
     "title": "Tasks running > 24h Timeline",
     "type": "timeseries",
     "description": "Число тасок, длящиеся больше 24 часов ",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=sat_tasks_hung.count'), 'name')"
      }
     ]
    },
    {
     "title": "Number of Hosts in Lifecycle Env",
     "type": "bargauge",
     "description": "Число хостов в Satellite на Окружение",
     "gridPos": { "h": 8, "w": 5, "x": 13, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~sat.count_host_lifecycle_env'), 2)"
      }
     ]
    },
    {
     "title": "Tasks in State = Paused Timeline",
     "type": "timeseries",
     "description": "Число тасок, в состоянии паузы",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=sat_tasks_paused.count'), 'name')"
      }
     ]
    },
    {
     "title": "Last Failed Sync Tasks",
     "type": "bargauge",
     "description": "Последние таски синхронизации на капсуль в состоянии Failed ",
     "gridPos": { "h": 14, "w": 5, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~status_sync_spr.last_failed_sync_tasks.(|)'), 'name'), 'status_sync_spr.last_failed_sync_tasks.', '')"
      }
     ]
    },
    {
     "title": "Active Sync Tasks",
     "type": "bargauge",
     "description": "Таски синхронизации на капсуль в данное время ",
     "gridPos": { "h": 14, "w": 5, "x": 5, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~status_sync_spr.active_sync_tasks.(|)'), 'name'), 'status_sync_spr.active_sync_tasks.', '')"
      }
     ]
    },
    {
     "title": "Active Sync Tasks",
     "type": "timeseries",
     "description": "Таски синхронизации на капсуль в данное время ",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~status_sync_spr.active_sync_tasks.(|)'), 'name'), 'status_sync_spr.active_sync_tasks.', '')"
      }
     ]
    },
    {
     "title": "Last Failed Sync Tasks",
     "type": "timeseries",
     "description": "Последние таски синхронизации на капсуль в состоянии Failed ",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~status_sync_spr.last_failed_sync_tasks.(|)'), 'name'), 'status_sync_spr.last_failed_sync_tasks.', '')"
      }
     ]
    }
   ]
  },
  {
   "title": "Systemd Units",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Services Status",
     "type": "stat",
     "description": "Состояние всех systemd юнитов Satellite",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'name=systemd_units.active_code', 'servertype=satellite'), '_name')"
      }
     ]
    },
    {
     "title": "Services Status TImeLine",
     "type": "timeseries",
     "description": "Состояние всех systemd юнитов Satellite",
     "gridPos": { "h": 11, "w": 18, "x": 6, "y": 23 },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'name=systemd_units.active_code', 'servertype=satellite'), '_name')"
      }
     ]
    }
   ]
  },
  {
   "title": "System Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu-Total",
     "type": "timeseries",
     "description": "Статистика использования CPU",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'name=system.cpu.usage_active', 'cpu=cpu-total', 'servertype=satellite'), 'cpu')"
      },
      {
       "target": "aliasByMetric(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'name=~system.cpu.usage_(guest|iowait|irq|nice|softirq|steal|system|user)', 'cpu=cpu-total', 'servertype=satellite'))"
      }
     ]
    },
    {
     "title": "Cpu-Usage",
     "type": "timeseries",
     "description": "Процент использования каждого CPU",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'name=system.cpu.usage_active', 'servertype=satellite'), 'cpu')"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "description": "Средняя загрузка — среднее значение загрузки системы за последние 1, 5 и 15 минут.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
     "targets": [
      {
       "target": "aliasByMetric(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'name=~system.system.load(1|5|15)', 'servertype=satellite'))"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "Время работы системы с момента запуска.",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByMetric(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'name=~system.system.uptime', 'servertype=satellite'))"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "description": "Процент использованного места на диске",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=system.disk.used_percent'), 'path'), '-', '/')"
      }
     ]
    },
    {
     "title": "Disk await lag",
     "type": "timeseries",
     "description": "Эти значения подсчитывают количество миллисекунд ожидания запросов ввода-вывода на этом блочном устройстве. Если имеется несколько ожидающих запросов ввода-вывода, эти значения будут увеличиваться со скоростью, превышающей 1000 в секунду; например, если 60 запросов на чтение ждут в среднем 30 мс, поле read_time увеличится на 60*30 = 1800.\n(These values count the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, these values will increase at a rate greater than 1000/second; for example, if 60 read requests wait for an average of 30 ms, the read_time field will increase by 60*30 = 1800.)\n\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', '_name=~(sd|vd)', 'name=~system.diskio.(read_time|write_time)')), 'name', '_name')"
      }
     ]
    },
    {
     "title": "Disk Read/Write bytes",
     "type": "timeseries",
     "description": "Эти значения подсчитывают количество байтов, прочитанных или записанных на это блочное устройство.\n(These values count the number of bytes read from or written to this block device.)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', '_name=~(sd|vd)', 'name=~system.diskio.(read_bytes|write_bytes)')), 'name', '_name')"
      }
     ]
    },
    {
     "title": "Disk Read/Write i/o",
     "type": "timeseries",
     "description": "Количество операций ввода-вывода, выполняемых системой хранения данных, за одну секунду.\nЭти значения увеличиваются после завершения запроса ввода-вывода.\n(These values increment when an I/O request completes.)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', '_name=~(sd|vd)', 'name=~system.diskio.(reads|writes)')), 'name', '_name')"
      }
     ]
    },
    {
     "title": "Network Rx/Tx bps",
     "type": "timeseries",
     "description": "bytes_sent — общее количество байтов, отправленных интерфейсом.\n\nbytes_recv — общее количество байтов, полученных интерфейсом",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "target": "aliasByMetric(perSecond(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~system.net.bytes_(recv|sent)')))"
      }
     ]
    },
    {
     "title": "Network Rx/Tx pps",
     "type": "timeseries",
     "description": "packages_sent — общее количество пакетов, отправленных интерфейсом. \n\npackages_recv — общее количество пакетов, полученных интерфейсом.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "target": "aliasByMetric(perSecond(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~system.net.packets_(recv|sent)')))"
      }
     ]
    },
    {
     "title": "Network Rx/Tx package drops",
     "type": "timeseries",
     "description": "drop_in — общее количество полученных пакетов, отброшенных интерфейсом. \n\ndrop_out — общее количество переданных пакетов, отброшенных интерфейсом",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "target": "aliasByMetric(perSecond(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~system.net.drop_(in|out)')))"
      }
     ]
    },
    {
     "title": "Network Rx/Tx package errors",
     "type": "timeseries",
     "description": "err_in — общее количество ошибок приема, обнаруженных интерфейсом. \n\nerr_out — общее количество ошибок передачи, обнаруженных интерфейсом.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByMetric(perSecond(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~system.net.err_(in|out)')))"
      }
     ]
    },
    {
     "title": "Network connections (Netstat)",
     "type": "timeseries",
     "description": "Статистика по tcp-сокетам",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByMetric(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~system.netstat.tcp_(close_wait|established|listen|time_wait)'))"
      }
     ]
    },
    {
     "title": "Memory Usage %",
     "type": "timeseries",
     "description": "Использование оперативной памяти в системе",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=system.mem.available_percent'), 'name'), '.*', 'Free Mem')"
      },
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=system.mem.used_percent'), 'name'), '.*', 'Used Mem')"
      }
     ]
    },
    {
     "title": "Memory Dump",
     "type": "timeseries",
     "description": "dirty -  это память, представляющая данные на диске, которые были изменены, но еще не были записаны на диск.\n\nwriteback - Количество грязных страниц, подлежащих обратной записи\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasByMetric(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=system.mem.dirty'))"
      },
      {
       "target": "aliasSub(aliasByMetric(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=system.vmstat.nr_writeback')), 'nr_', '')"
      }
     ]
    },
    {
     "title": "Swap Usage",
     "type": "timeseries",
     "description": "Статистика по использованию swap",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasByMetric(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~system.mem.swap_(cached|free|total)'))"
      }
     ]
    },
    {
     "title": "Memory Usage All bytes",
     "type": "timeseries",
     "description": "Статистика по использование оперативной памяти в системе в байтах",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "aliasByMetric(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~system.mem.(buffered|cached|free|shared|slab|used|inactive)$'))"
      }
     ]
    },
    {
     "title": "Memory Activity",
     "type": "timeseries",
     "description": "Статистика виртуальной памяти, собираемая из /proc/vmstat.\nman vmstat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "aliasByMetric(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~system.vmstat.nr_(active_anon|active_file|inactive_anon|inactive_file|mapped|slab)'))"
      },
      {
       "target": "aliasByMetric(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~system.vmstat.balloon_(deflate|inflate|migrate)'))"
      }
     ]
    }
   ]
  }
 ]
}