{
 "title": "Satellite-Capsules",
 "description": "Ответственный: Альбещенко М.Н.  и  Борбат Я.Д. (АЦОД)",
 "tags": [ "telegraf" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Capsule",
    "query": "tag_values(host, servertype=satellite)"
   }
  ]
 },
 "panels": [
  { "title": "Systemd Units", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services Status",
   "type": "stat",
   "description": "Состояние всех systemd юнитов Satellite и ее капсулей",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "maxSeries(aliasByTags(seriesByTag('contur=prod', 'host=~${Capsule:regex}', 'name=systemd_units.active_code', 'servertype=satellite'), '_name'))"
    }
   ]
  },
  {
   "title": "Services Status",
   "type": "bargauge",
   "description": "Состояние всех systemd юнитов Satellite и ее капсулей",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'host=~${Capsule:regex}', 'name=systemd_units.active_code', 'servertype=satellite'), 'host', '_name')"
    }
   ]
  },
  {
   "title": "Services Status TImeLine",
   "type": "timeseries",
   "description": "Состояние всех systemd юнитов Satellite и ее капсулей",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'host=~${Capsule:regex}', 'name=systemd_units.active_code', 'servertype=satellite'), 'host', '_name')"
    }
   ]
  },
  { "title": "Cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cpu-Total",
   "type": "timeseries",
   "description": "Статистика использования CPU",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'host=~${Capsule:regex}', 'name=system.cpu.usage_active', 'cpu=cpu-total', 'servertype=satellite'), 'host', 'cpu')"
    },
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'name=~system.cpu.usage_(guest|iowait|irq|nice|softirq|steal|system|user)', 'cpu=cpu-total', 'servertype=satellite', 'host=~${Capsule:regex}'), 'host', 'name')"
    }
   ]
  },
  {
   "title": "Cpu-Usage",
   "type": "timeseries",
   "description": "Процент использования каждого CPU",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'name=system.cpu.usage_active', 'servertype=satellite', 'host=~${Capsule:regex}'), 'host', 'cpu')"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "description": "Load Average",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'name=~system.system.load(1|5|15)', 'servertype=satellite', 'host=~${Capsule:regex}'), 'host', 2)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Время работы системы с момента запуска.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('contur=prod', 'host=~${Capsule:regex}', 'name=~system.system.uptime', 'servertype=satellite'), 'host')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage %",
     "type": "timeseries",
     "description": "Использование оперативной памяти в системе",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=~${Capsule:regex}', 'servertype=satellite', 'name=~system.mem.(available|used)_percent'), 'host', 2)"
      }
     ]
    },
    {
     "title": "Memory Dump",
     "type": "timeseries",
     "description": "dirty -  это память, представляющая данные на диске, которые были изменены, но еще не были записаны на диск.\n\nwriteback - Количество грязных страниц, подлежащих обратной записи\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=~${Capsule:regex}', 'servertype=satellite', 'name=~system.(mem.dirty|vmstat.nr_writeback)$'), 'host', 2), 'nr_', '')"
      }
     ]
    },
    {
     "title": "Swap Usage",
     "type": "timeseries",
     "description": "Статистика по использованию swap",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=~${Capsule:regex}', 'servertype=satellite', 'name=~system.mem.swap_(cached|free|total)'), 'host', 2)"
      }
     ]
    },
    {
     "title": "Memory Usage All bytes",
     "type": "timeseries",
     "description": "Статистика по использование оперативной памяти в системе в байтах",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=~${Capsule:regex}', 'servertype=satellite', 'name=~system.mem.(buffered|cached|free|shared|slab|used|inactive)$'), 'host', 2)"
      }
     ]
    },
    {
     "title": "Memory Activity",
     "type": "timeseries",
     "description": "Статистика виртуальной памяти, собираемая из /proc/vmstat.\nman vmstat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=~${Capsule:regex}', 'servertype=satellite', 'name=~system.vmstat.nr_(active_anon|active_file|inactive_anon|inactive_file|mapped|slab)'), 'host', 2)"
      },
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=~${Capsule:regex}', 'servertype=satellite', 'name=~system.vmstat.balloon_(deflate|inflate|migrate)'), 'host', 2)"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "description": "Процент использованного места на диске",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'servertype=satellite', 'name=system.disk.used_percent', 'servertype=satellite', 'host=~${Capsule:regex}'), 'host', 'path'), '-', '/')"
      }
     ]
    },
    {
     "title": "Disk await lag",
     "type": "timeseries",
     "description": "Эти значения подсчитывают количество миллисекунд ожидания запросов ввода-вывода на этом блочном устройстве. Если имеется несколько ожидающих запросов ввода-вывода, эти значения будут увеличиваться со скоростью, превышающей 1000 в секунду; например, если 60 запросов на чтение ждут в среднем 30 мс, поле read_time увеличится на 60*30 = 1800.\n(These values count the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, these values will increase at a rate greater than 1000/second; for example, if 60 read requests wait for an average of 30 ms, the read_time field will increase by 60*30 = 1800.)\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('contur=prod', 'servertype=satellite', '_name=~(sd|vd)', 'name=~system.diskio.(read_time|write_time)', 'host=~${Capsule:regex}')), 'host', 'name', '_name')"
      }
     ]
    },
    {
     "title": "Disk Read/Write bytes",
     "type": "timeseries",
     "description": "Эти значения подсчитывают количество байтов, прочитанных или записанных на это блочное устройство.\n(These values count the number of bytes read from or written to this block device.)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('contur=prod', 'servertype=satellite', '_name=~(sd|vd)', 'name=~system.diskio.(read_bytes|write_bytes)', 'host=~${Capsule:regex}')), 'host', 'name', '_name')"
      }
     ]
    },
    {
     "title": "Disk Read/Write i/o",
     "type": "timeseries",
     "description": "Количество операций ввода-вывода, выполняемых системой хранения данных, за одну секунду.\nЭти значения увеличиваются после завершения запроса ввода-вывода.\n(These values increment when an I/O request completes.)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('contur=prod', 'servertype=satellite', '_name=~(sd|vd)', 'name=~system.diskio.(reads|writes)', 'host=~${Capsule:regex}')), 'host', 'name', '_name')"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Rx/Tx bps",
     "type": "timeseries",
     "description": "bytes_sent — общее количество байтов, отправленных интерфейсом.\n\nbytes_recv — общее количество байтов, полученных интерфейсом",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('contur=prod', 'servertype=satellite', 'name=~system.net.bytes_(recv|sent)', 'host=~${Capsule:regex}')), 'host', 2)"
      }
     ]
    },
    {
     "title": "Network Rx/Tx pps",
     "type": "timeseries",
     "description": "packages_sent — общее количество пакетов, отправленных интерфейсом.\n\npackages_recv — общее количество пакетов, полученных интерфейсом.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('contur=prod', 'servertype=satellite', 'name=~system.net.packets_(recv|sent)', 'host=~${Capsule:regex}')), 'host', 2)"
      }
     ]
    },
    {
     "title": "Network Rx/Tx package drops",
     "type": "timeseries",
     "description": "drop_in — общее количество полученных пакетов, отброшенных интерфейсом. \n\ndrop_out — общее количество переданных пакетов, отброшенных интерфейсом",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('contur=prod', 'host=~${Capsule:regex}', 'servertype=satellite', 'name=~system.net.drop_(in|out)')), 'host', 2)"
      }
     ]
    },
    {
     "title": "Network Rx/Tx package errors",
     "type": "timeseries",
     "description": "err_in — общее количество ошибок приема, обнаруженных интерфейсом. \n\nerr_out — общее количество ошибок передачи, обнаруженных интерфейсом.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByTags(perSecond(seriesByTag('contur=prod', 'host=~${Capsule:regex}', 'servertype=satellite', 'name=~system.net.err_(in|out)')), 'host', 2)"
      }
     ]
    },
    {
     "title": "Network connections (Netstat)",
     "type": "timeseries",
     "description": "Статистика по tcp-сокетам ",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('contur=prod', 'host=~${Capsule:regex}', 'servertype=satellite', 'name=~system.netstat.tcp_(close_wait|established|listen|time_wait)'), 'host', 2)"
      }
     ]
    }
   ]
  },
  {
   "title": "Satellite Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Sync Time",
     "type": "stat",
     "description": "Время последней синхронизации капсулей Satellite",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(scale(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~status_sync_spr.last_sync_time.${Capsule:regex}'), 1000, 0), 'name'), 'status_sync_spr.last_sync_time.', '')"
      }
     ]
    },
    {
     "title": "Last Failed Sync Tasks",
     "type": "bargauge",
     "description": "Последние таски синхронизации на капсуль в состоянии Failed ",
     "gridPos": { "h": 11, "w": 5, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~status_sync_spr.last_failed_sync_tasks.${Capsule:regex}'), 'name'), 'status_sync_spr.last_failed_sync_tasks.', '')"
      }
     ]
    },
    {
     "title": "Active Sync Tasks",
     "type": "bargauge",
     "description": "Таски синхронизации на капсуль в данное время ",
     "gridPos": { "h": 11, "w": 5, "x": 5, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~status_sync_spr.active_sync_tasks.${Capsule:regex}'), 'name'), 'status_sync_spr.active_sync_tasks.', '')"
      }
     ]
    },
    {
     "title": "Last Failed Sync Tasks",
     "type": "timeseries",
     "description": "Последние таски синхронизации на капсуль в состоянии Failed ",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~status_sync_spr.last_failed_sync_tasks.${Capsule:regex}'), 'name'), 'status_sync_spr.last_failed_sync_tasks.', '')"
      }
     ]
    },
    {
     "title": "Active Sync Tasks",
     "type": "timeseries",
     "description": "Таски синхронизации на капсуль в данное время ",
     "gridPos": { "h": 5, "w": 14, "x": 10, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasSub(aliasByTags(seriesByTag('contur=prod', 'host=sat.mgmt.tensor.ru', 'servertype=satellite', 'name=~status_sync_spr.active_sync_tasks.${Capsule:regex}'), 'name'), 'status_sync_spr.active_sync_tasks.', '')"
      }
     ]
    }
   ]
  }
 ]
}