{
 "title": "Systemd units by host",
 "description": "Ретрансляция видео- и аудиопотоков в рамках видеоконференций. Ответственный: Карпов С.В. (Эксплуатация), Кузнецов А.П. (Разработка)",
 "tags": [
  "telegraf",
  "service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "tag_values(host,systemd_unit=~.*)"
   },
   {
    "name": "systemd_unit",
    "query": "tag_values(systemd_unit,host=$host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit\\.service', 'name=~.*$systemd_unit\\.running'), 'host', 'systemd_unit')"
    }
   ]
  },
  {
   "title": "Major faults",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.major_faults'))"
    }
   ]
  },
  {
   "title": "Minor faults",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.minor_faults'))"
    }
   ]
  },
  {
   "title": "Child major faults",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.child_major_faults'))"
    }
   ]
  },
  {
   "title": "Child minor faults",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.child_minor_faults'))"
    }
   ]
  },
  {
   "title": "Threads number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.num_threads')"
    }
   ]
  },
  {
   "title": "PID count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.pid_count')"
    }
   ]
  },
  {
   "title": "Involuntary CS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.involuntary_context_switches'))"
    }
   ]
  },
  {
   "title": "Voluntary CS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.voluntary_context_switches'))"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(sortByMaxima(aliasByNode(perSecond(aliasByTags(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.cpu_time.*'), 'name')), -1)), 'cpu_time_', '')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasSub(aliasByNode(aliasByTags(seriesByTag('host=$host', 'systemd_unit=~$systemd_unit.service', 'name=~.*$systemd_unit\\.memory.*'), 'name'), -1), 'memory_', ''))"
    }
   ]
  },
  {
   "title": "Использование CPU на system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.cpu.usage_active', 'host=$host', 'cpu=cpu-total'), -2)"
    }
   ]
  },
  {
   "title": "Swap.used_percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.swap.used_percent', 'host=$host'), 1, 2)"
    }
   ]
  },
  {
   "title": "LA",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.system.load1', 'host=$host'), 1, 2)"
    }
   ]
  },
  {
   "title": "Использование разделов",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=$host', 'name=system.disk.used_percent'), 'path'), '-', '/')"
    }
   ]
  }
 ]
}