{
 "title": "Vcenter cluster status",
 "description": "Ответственный: Лыков Н.М. (АЦОД)",
 "tags": [
  "telegraf",
  "vmware",
  "Virtualization",
  "system"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "vcenter_tag", "label": "vcenter", "query": "tag_values(vcenter)" },
   {
    "name": "cluster_tag",
    "label": "Cluster",
    "query": "tag_values(clustername,vcenter=~${vcenter_tag})"
   },
   {
    "name": "esxi_tag",
    "label": "esxi",
    "query": "tag_values(esxhostname,clustername=~${cluster_tag})"
   },
   {
    "name": "datastore_tag",
    "label": "datastore",
    "query": "tag_values(dsname,clustername=~${cluster_tag})"
   },
   {
    "name": "cpu_tag",
    "label": "cpu",
    "query": "tag_values(cpu,esxhostname=~${esxi_tag})"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status - $cluster_tag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "Суммарный для вcех кластеров vcenter процент использования процессора, занятого «полезной работой» (средний за последние  20 сек)",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aggregate(seriesByTag('vcenter=$vcenter_tag', 'clustername=$cluster_tag', 'cpu=instance-total', 'name=service.vcenter.usage_average', 'interval=20s'), 'average')"
    }
   ]
  },
  {
   "title": "VM summary",
   "type": "stat",
   "description": "Суммарное количество виртуальных серверов vcenter всех кластеров",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "target": "aggregate($source.$cluster.*.*.*.*.*.*.$vcenter.*.interval-60s.usage_5Faverage, 'count')"
    }
   ]
  },
  {
   "title": "Cluster CPU usage %",
   "type": "graph",
   "description": "График динамики суммарного процента использования процессоров, занятого «полезной работой», всех кластеров vcenter",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "Usage Average %" }
   ],
   "targets": [
    {
     "target": "alias(aggregate(seriesByTag('vcenter=$vcenter_tag', 'clustername=$cluster_tag', 'cpu=instance-total', 'name=service.vcenter.usage_average', 'interval=20s'), 'average'), '$cluster_tag')"
    }
   ]
  },
  {
   "title": "Cluster MEM Usage %",
   "type": "graph",
   "description": "Суммарный процент использования оперативной памяти всех кластеров vcenter (средний за последние  20 сек)",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "Usage Average %" }
   ],
   "targets": [
    {
     "target": "alias(aggregate(seriesByTag('vcenter=$vcenter_tag', 'clustername=$cluster_tag', 'cpu!=~${cpu_tag:regex}', 'interface!=~*', 'name=service.vcenter.usage_average', 'interval=20s'), 'average'), '$cluster_tag')"
    }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "stat",
   "description": "График динамики суммарного процента использования оперативной памяти всех кластеров vcenter",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aggregate(seriesByTag('vcenter=$vcenter_tag', 'clustername=$cluster_tag', 'name=service.vcenter.usage_average', 'interval=20s', 'cpu!=~${cpu_tag:regex}', 'interface!=~*'), 'average')"
    }
   ]
  },
  {
   "title": "ESXi Summary",
   "type": "stat",
   "description": "Суммарное количество ESXi хостов vcenter всех кластеров",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "target": "aggregate(seriesByTag('vcenter=$vcenter_tag', 'clustername=$cluster_tag', 'cpu=instance-total', 'name=service.vcenter.usage_average', 'interval=20s'), 'count')"
    }
   ]
  },
  {
   "title": "Cluster Network Usage / Errors",
   "type": "graph",
   "description": "График динамики суммарного процента использования сети всех кластеров vcenter",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "KBs", "label": "Usage Network MBps" }
   ],
   "targets": [
    {
     "target": "alias(aggregate(seriesByTag('vcenter=$vcenter_tag', 'clustername=$cluster_tag', 'interface=~instance-total', 'name=service.vcenter.usage_average', 'interval=20s'), 'sum'), '$cluster_tag')"
    },
    {
     "target": "aliasSub(aliasSub(sortByMaxima(aliasByTags(seriesByTag('vcenter=$vcenter_tag', 'clustername=$cluster_tag', 'interface=~instance-total', 'name=~service.vcenter.errors.*_summation', 'interval=20s'), 'esxhostname', 'name')), 'corp.tensor.ru.service.vcenter.', ''), '_summation', '')"
    }
   ]
  },
  {
   "title": "Cluster Storage IOPS",
   "type": "graph",
   "description": "График динамики суммарного количества операций ввода/вывода дисковой подсистемы всех кластеров vcenter",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(aggregate(seriesByTag('vcenter=$vcenter_tag', 'clustername=$cluster_tag', 'name=service.vcenter.commandsAveraged_average'), 'sum'), '$cluster_tag')"
    }
   ]
  },
  { "title": "Datastore status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "$datastore_tag",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "repeat": "datastore_tag",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "asPercent(seriesByTag('vcenter=$vcenter_tag', 'dsname=~${datastore_tag:regex}', 'name=service.vcenter.used_latest', 'disk=instance-total'), #A)",
     "targetFull": "asPercent(seriesByTag('vcenter=$vcenter_tag', 'dsname=~${datastore_tag:regex}', 'name=service.vcenter.used_latest', 'disk=instance-total'), seriesByTag('vcenter=$vcenter_tag', 'dsname=~${datastore_tag:regex}', 'name=service.vcenter.capacity_latest', 'disk=instance-total'))"
    }
   ]
  },
  { "title": "Hypervisor Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Hypervisor CPU (Top 10)",
   "type": "graph",
   "description": "Топ 10 ESXi хостов по проценту использования процессора",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage Avg. %" }
   ],
   "targets": [
    {
     "target": "highestCurrent(aliasByTags(seriesByTag('vcenter=$vcenter_tag', 'clustername=$cluster_tag', 'cpu=instance-total', 'name=service.vcenter.usage_average', 'interval=20s'), 'esxhostname'), 10)"
    }
   ]
  },
  {
   "title": "Hypervisor Net Usage",
   "type": "graph",
   "description": "Топ 10 ESXi хостов по динамике использования сети (МБ/с)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByTags(highestCurrent(seriesByTag('vcenter=$vcenter_tag', 'clustername=$cluster_tag', 'interface=~instance-total', 'name=service.vcenter.usage_average', 'interval=20s'), 10), 'esxhostname')"
    }
   ]
  },
  {
   "title": "Hypervisor Memory",
   "type": "graph",
   "description": "Топ 10 ESXi хостов по проценту использования оперативной памяти",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "percent", "label": "Memory Usage Avg. %" }
   ],
   "targets": [
    {
     "target": "aliasByTags(highestCurrent(seriesByTag('vcenter=$vcenter_tag', 'clustername=$cluster_tag', 'name=service.vcenter.usage_average', 'interval=20s', 'cpu!=~${cpu_tag:regex}', 'interface!=~*'), 10), 'esxhostname')"
    }
   ]
  }
 ]
}