{
 "title": "Vcenter overwiev",
 "description": "Ответственный: Лыков Н.М. (АЦОД)",
 "tags": [
  "telegraf",
  "vmware",
  "Virtualization",
  "system"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "vcenter", "query": "tag_values(vcenter)" }
  ]
 },
 "panels": [
  {
   "title": "Hosts (Top 10)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host CPU Utilization (Top 10)",
     "type": "graph",
     "description": "Топ 10 ESXi хостов по проценту использования процессора",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent", "label": "%" }
     ],
     "targets": [
      {
       "target": "highestCurrent(aliasByTags(seriesByTag('vmname!=~*', 'cpu=instance-total', 'name=service.vcenter.usage_average', 'vcenter=$vcenter'), 'esxhostname'), 10)"
      }
     ]
    },
    {
     "title": "Host RAM Utilization (Top 10)",
     "type": "graph",
     "description": "Топ 10 ESXi хостов по проценту использования оперативной памяти",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "highestCurrent(aliasByTags(seriesByTag('vmname!=~*', 'cpu!=~*', 'name=service.vcenter.usage_average', 'vcenter=$vcenter', 'interface!=~*'), 'esxhostname'), 10)"
      }
     ]
    },
    {
     "title": "Host Net Utilization (Top 10)",
     "type": "graph",
     "description": "Топ 10 ESXi хостов по динамике  использования сети (МБ/c)",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "target": "highestCurrent(aliasByTags(seriesByTag('vmname!=~*', 'interface=instance-total', 'name=service.vcenter.usage_average', 'vcenter=$vcenter'), 'esxhostname'), 10)"
      }
     ]
    }
   ]
  },
  {
   "title": "VM (Top 10)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM CPU Utilization (Top 10)",
     "type": "graph",
     "description": "Топ 10 ВМ  по  использования процессора",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none", "label": "Mhz" }
     ],
     "targets": [
      {
       "target": "highestCurrent(aliasByTags(seriesByTag('vmname=~.*', 'cpu=instance-total', 'name=service.vcenter.usagemhz_average', 'vcenter=$vcenter'), 'vmname'), 10)"
      }
     ]
    },
    {
     "title": "VM RAM Utilization (Top 10)",
     "type": "graph",
     "description": "Топ 10 ВМ по проценту использования оперативной памяти",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "target": "highestCurrent(aliasByTags(seriesByTag('vmname=~*', 'cpu!=~*', 'name=service.vcenter.active_average', 'vcenter=$vcenter'), 'vmname'), 10)"
      }
     ]
    },
    {
     "title": "VM Net Utilization (Top 10)",
     "type": "graph",
     "description": "Топ 10 ВМ  по утилизации сетевых интерфейсов ВМ (МБ/с)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "target": "highestCurrent(aliasByTags(seriesByTag('vmname=~*', 'interface=~instance-total', 'name=service.vcenter.usage_average', 'vcenter=$vcenter'), 'vmname'), 10)"
      }
     ]
    },
    {
     "title": "VM Disk Write Latency (Top 10)",
     "type": "graph",
     "description": "Топ 10 ВМ по средней задержки при операциях записи на дисковую подсистем",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "highestCurrent(aliasByTags(seriesByTag('vmname=~*', 'disk=~*', 'name=service.vcenter.totalWriteLatency_average', 'vcenter=$vcenter'), 'vmname', 'disk'), 10)"
      }
     ]
    },
    {
     "title": "VM Disk Read IOPS (Top 10)",
     "type": "graph",
     "description": "Топ 10 ВМ по количеству операций чтения с дисковой подсистемы",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "highestCurrent(aliasByTags(seriesByTag('vmname=~*', 'disk=~*', 'name=service.vcenter.numberReadAveraged_average', 'vcenter=$vcenter'), 'vmname', 'disk'), 10)"
      }
     ]
    },
    {
     "title": "VM Disk Read Latency (Top 10)",
     "type": "graph",
     "description": "Топ 10 ВМ по средней задержки при операциях чтения на дисковую подсистем",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "highestCurrent(aliasByTags(seriesByTag('vmname=~*', 'disk=~*', 'name=service.vcenter.totalReadLatency_average', 'vcenter=$vcenter'), 'vmname', 'disk'), 10)"
      }
     ]
    },
    {
     "title": "VM Disk Write IOPS (Top 10)",
     "type": "graph",
     "description": "Топ 10 ВМ по количеству операций записи на дисковую подсистему",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "highestCurrent(aliasByTags(seriesByTag('vmname=~*', 'disk=~*', 'name=service.vcenter.numberWriteAveraged_average', 'vcenter=$vcenter'), 'vmname', 'disk'), 10)"
      }
     ]
    }
   ]
  },
  {
   "title": "Datastore (Top 10)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Datastore Write Latency (Top 10)",
     "type": "graph",
     "description": "Топ 10 Datastores по средней задержке при операциях записи на дисковую подсистем",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "highestCurrent(aliasByTags(seriesByTag('dsname=~.*vstor|VSTOR|vmfs', 'name=service.vcenter.totalWriteLatency_average', 'vcenter=$vcenter'), 'dsname'), 10)"
      }
     ]
    },
    {
     "title": "Datastore Read Latency (Top 10)",
     "type": "graph",
     "description": "Топ 10 Datastores по средней задержке при операциях чтения на дисковую подсистем",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "highestCurrent(aliasByTags(seriesByTag('dsname=~.*vstor|VSTOR', 'name=service.vcenter.totalReadLatency_average', 'vcenter=$vcenter'), 'dsname'), 10)"
      }
     ]
    },
    {
     "title": "Datastore Write IOPS (Top 10)",
     "type": "graph",
     "description": "Топ 10 Datastores по количеству операций записи на дисковую подсистему",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "highestCurrent(aliasByTags(seriesByTag('dsname=~.*vstor|VSTOR', 'name=service.vcenter.numberWriteAveraged_average', 'vcenter=$vcenter'), 'dsname'), 10)"
      }
     ]
    },
    {
     "title": "Datastore Read IOPS (Top 10)",
     "type": "graph",
     "description": "Топ 10 Datastores по количеству операций чтения с дисковой подсистемы",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "highestCurrent(aliasByTags(seriesByTag('dsname=~.*vstor|VSTOR', 'name=service.vcenter.numberReadAveraged_average', 'vcenter=$vcenter'), 'dsname'), 10)"
      }
     ]
    }
   ]
  }
 ]
}