{
 "title": "Vcenter VMs",
 "description": "Ответственный: Лыков Н.М. (АЦОД)",
 "tags": [
  "telegraf",
  "vmware",
  "Virtualization",
  "system"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "vm", "label": "vm", "query": "tag_values(vmname)" }
  ]
 },
 "panels": [
  { "title": "$vm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "esxi" },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Время работы ВМ",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "seriesByTag('vmname=$vm', 'name=service.vcenter.uptime_latest')"
    }
   ]
  },
  {
   "title": "CPU Usage Mhz",
   "type": "stat",
   "description": "Использование процессора ВМ, занятого «полезной работой» в Mhz",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('vmname=$vm', 'cpu=instance-total', 'name=service.vcenter.usagemhz_average')"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "Использование оперативной памяти ВМ в ГБ",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "seriesByTag('vmname=$vm', 'cpu!=~*', 'name=service.vcenter.active_average')"
    }
   ]
  },
  {
   "title": "CPU Utilization %",
   "type": "graph",
   "description": "График динамики использования процессора ВМ в %",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization %" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('vmname=$vm', 'cpu=instance-total', 'name=service.vcenter.usage_average'), 'CPU')"
    },
    {
     "target": "alias(seriesByTag('vmname=$vm', 'cpu=instance-total', 'name=service.vcenter.readiness_average'), 'CPU Ready')"
    }
   ]
  },
  {
   "title": "RAM Utilization %",
   "type": "graph",
   "description": "График динамики использования оперативной памяти ВМ в %",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "RAM Utilization %" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('vmname=$vm', 'cpu!=~*', 'name=service.vcenter.usage_average', 'interface!=~*', 'interval=60s'), 'RAM Utilization %')"
    }
   ]
  },
  {
   "title": "RAM Uage",
   "type": "graph",
   "description": "График динамики использования оперативной памяти ВМ в ГБ",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "deckbytes", "label": "RAM Uage" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('vmname=$vm', 'cpu!=~*', 'name=service.vcenter.active_average'), 'Active')"
    },
    {
     "target": "alias(seriesByTag('vmname=$vm', 'cpu!=~*', 'name=service.vcenter.granted_average'), 'Granted')"
    },
    {
     "target": "alias(seriesByTag('vmname=$vm', 'cpu!=~*', 'name=service.vcenter.vmmemctl_average'), 'Ballon')"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "stat",
   "description": "Процент использования процессора ВМ, занятого «полезной работой»  (средний за последние  20 сек)",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "seriesByTag('vmname=$vm', 'cpu=instance-total', 'name=service.vcenter.usage_average')"
    }
   ]
  },
  {
   "title": "RAM Usage %",
   "type": "stat",
   "description": "Процент использования оперативной памяти ВМ (средний за последние  20 сек)",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "seriesByTag('vmname=$vm', 'cpu!=~*', 'interface!=~*', 'name=service.vcenter.usage_average', 'interval=60s')"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "description": "График утилизации операций ввода/вывода по каждому диску ВМ (IOPS)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('vmname=$vm', 'disk=~*', 'name=service.vcenter.numberReadAveraged_average'), 'disk', 'name'), '.service.vcenter.numberReadAveraged_average', ' Read')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('vmname=$vm', 'disk=~*', 'name=service.vcenter.numberWriteAveraged_average'), 'disk', 'name'), '.service.vcenter.numberWriteAveraged_average', ' Write')"
    }
   ]
  },
  {
   "title": "Disk latency",
   "type": "graph",
   "description": "График задержек операций ввода/вывода по каждому диску ВМ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('vmname=$vm', 'disk=~*', 'name=service.vcenter.totalReadLatency_average'), 'disk', 'name'), '.service.vcenter.totalReadLatency_average', ' Read')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('vmname=$vm', 'disk=~*', 'name=service.vcenter.totalWriteLatency_average'), 'disk', 'name'), '.service.vcenter.totalWriteLatency_average', ' Write')"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "description": "График утилизации сетевых интерфейсов ВМ (МБ/с)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('vmname=$vm', 'interface=instance-total', 'name=service.vcenter.bytesRx_average'), 'vmname', 'name'), '.service.vcenter.bytesRx_average', ' Rx')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('vmname=$vm', 'interface=instance-total', 'name=service.vcenter.bytesTx_average'), 'vmname', 'name'), '.service.vcenter.bytesTx_average', ' Tx')"
    }
   ]
  },
  {
   "title": "Network Dropped",
   "type": "graph",
   "description": "График динамики числа ошибок на сетевых интерфейсах ВМ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('vmname=$vm', 'interface=instance-total', 'name=service.vcenter.droppedRx_summation'), 'vmname', 'name'), '.service.vcenter.droppedRx_summation', ' Dropped Rx')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('vmname=$vm', 'interface=instance-total', 'name=service.vcenter.droppedTx_summation'), 'vmname', 'name'), '.service.vcenter.droppedTx_summation', ' Dropped Tx')"
    }
   ]
  }
 ]
}