{
 "title": "Vcenter datastore",
 "description": "Ответственный: Лыков Н.М. (АЦОД)",
 "tags": [
  "telegraf",
  "vmware",
  "Virtualization",
  "system"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "vcenter", "query": "tag_values(vcenter)" },
   {
    "name": "dsname",
    "query": "tag_values(dsname, vcenter=~$vcenter)"
   }
  ]
 },
 "panels": [
  {
   "title": "Datastore Write Latency (Top 10)",
   "type": "graph",
   "description": "Топ 10 ESXi хостов по средней задержки при операциях записи на дисковую подсистем",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "highestCurrent(aliasByTags(groupByTags(seriesByTag('dsname=~${dsname:regex}', 'name=service.vcenter.totalWriteLatency_average', 'vcenter=$vcenter'), 'max', 'dsname'), 'dsname'), 10)"
    }
   ]
  },
  {
   "title": "Datastore Read Latency (Top 10)",
   "type": "graph",
   "description": "Топ 10 ESXi хостов по средней задержки при операциях чтения на дисковую подсистем",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "highestCurrent(aliasByTags(groupByTags(seriesByTag('dsname=~${dsname:regex}', 'name=service.vcenter.totalReadLatency_average', 'vcenter=$vcenter'), 'max', 'dsname'), 'dsname'), 10)"
    }
   ]
  },
  {
   "title": "Datastore Write IOPS (Top 10)",
   "type": "graph",
   "description": "Топ 10 ESXi хостов по количеству операций записи на дисковую подсистему",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "highestCurrent(aliasByTags(groupByTags(seriesByTag('dsname=~${dsname:regex}', 'name=service.vcenter.numberWriteAveraged_average', 'vcenter=$vcenter'), 'max', 'dsname'), 'dsname'), 10)"
    }
   ]
  },
  {
   "title": "Datastore Read IOPS (Top 10)",
   "type": "graph",
   "description": "Топ 10 ESXi хостов по количеству операций чтения с дисковой подсистемы",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "highestCurrent(aliasByTags(groupByTags(seriesByTag('dsname=~${dsname:regex}', 'name=service.vcenter.numberReadAveraged_average', 'vcenter=$vcenter'), 'max', 'dsname'), 'dsname'), 10)"
    }
   ]
  }
 ]
}