{
 "title": "VPN world кластер",
 "description": "Ответственный: Алексеев Е.А. , Жмуриков И.М. , Шутов И.А. (СПД)",
 "tags": [
  "dts",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Турция (dts-lb1-vpn-world)",
   "type": "stat",
   "description": "Состояние VPN канала",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=dts-mon-tf2.unix.tensor.ru', 'device=dts-lb1-vpn-world', 'interface=ovpn-out1', 'name=interface.status.oper')"
    }
   ]
  },
  {
   "title": "NordVPN (dts-r1-vpn-world)",
   "type": "stat",
   "description": "Состояние VPN канала",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=dts-mon-tf2.unix.tensor.ru', 'device=dts-r1-vpn-world', 'name=vpn_world_ipsec_peers.peer_state'), 'peer_name')"
    }
   ]
  },
  {
   "title": "SurfShark (dts-r2-vpn-world)",
   "type": "stat",
   "description": "Состояние VPN канала",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=dts-mon-tf2.unix.tensor.ru', 'device=dts-r2-vpn-world', 'name=vpn_world_ipsec_peers.peer_state'), 'peer_name')"
    }
   ]
  },
  {
   "title": "ExpressVPN (dts-r3-vpn-world)",
   "type": "stat",
   "description": "Состояние VPN канала",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=dts-mon-tf2.unix.tensor.ru', 'device=dts-r3-vpn-world', 'name=vpn_world_ipsec_peers.peer_state'), 'peer_name')"
    }
   ]
  },
  {
   "title": "Графики для dts-r1/2/3-vpn-world",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Трафик r1/2/3",
   "type": "graph",
   "description": "Утилизация порта в битах/сек",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(scale(seriesByTag('device=~dts-r(1|2|3)-vpn-world', 'interface=ether7', 'name=~interface\\.traffic\\.(in|out)_octets_rate'), 8), 'device', 2, 'interface'), '_octets', ''), '\\.', ' ')"
    }
   ]
  },
  {
   "title": "CPU r1/2/3",
   "type": "graph",
   "description": "Утилизация CPU в %",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('device=~dts-r(1|2|3)-vpn-world', 'name=system.cpu.usage_1m'), 'device')"
    }
   ]
  },
  { "title": "Графики для dts-lb1-vpn-world", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Трафик lb1",
   "type": "graph",
   "description": "Утилизация порта в битах/сек",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(scale(seriesByTag('device=dts-lb1-vpn-world', 'interface=~(ovpn-out1|bond0)', 'name=~interface\\.traffic\\.(in|out)_octets_rate'), 8), 'interface', 2), '_octets', ''), '\\.', ' ')"
    }
   ]
  },
  {
   "title": "CPU lb1",
   "type": "graph",
   "description": "Утилизация CPU в %",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('device=dts-lb1-vpn-world', 'name=system.cpu.usage_1m'), 'CPU 1min', false)"
    }
   ]
  }
 ]
}