{
 "title": "Виртуализация: Vcenter hosts",
 "description": "Ответственный: Лыков Н.М. (АЦОД)",
 "tags": [
  "telegraf",
  "vmware",
  "Virtualization",
  "system"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "vcenter", "query": "tag_values(vcenter)" },
   {
    "name": "cluster",
    "query": "tag_values(clustername,vcenter=~${vcenter})"
   },
   {
    "name": "esxihostname",
    "query": "tag_values(esxhostname,clustername=~${cluster:regex})"
   },
   {
    "name": "datastore",
    "query": "tag_values(dsname,esxhostname=~${esxihostname})"
   },
   {
    "name": "interface",
    "query": "tag_values(interface,esxhostname=~${esxihostname})"
   },
   {
    "name": "adapter",
    "query": "tag_values(adapter,esxhostname=~${esxihostname})"
   },
   {
    "name": "vm",
    "query": "tag_values(vmname,esxhostname=~${esxihostname})"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Время работы ESXi хоста",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "seriesByTag('esxhostname=$esxihostname', 'name=service.vcenter.uptime_latest', 'vmname!=~*')"
    }
   ]
  },
  {
   "title": "CPU Usage MHz",
   "type": "stat",
   "description": "Использование процессора ESXi хоста, занятого «полезной работой» в Mhz",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('esxhostname=$esxihostname', 'cpu=instance-total', 'name=service.vcenter.usagemhz_average', 'vmname!=~*')"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Общий объем оперативной памяти ESXi хоста",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('esxhostname=$esxihostname', 'name=service.vcenter.totalCapacity_average', 'cpu!=instance-total')"
    }
   ]
  },
  {
   "title": "VM List",
   "type": "table",
   "description": "Список ВМ на ESXi хосте",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('esxhostname=$esxihostname', 'vmname=~*', 'cpu=instance-total', 'name=service.vcenter.usagemhz_average'), 'vmname')"
    }
   ]
  },
  {
   "title": "CPU Utilization %",
   "type": "graph",
   "description": "График динамики использования процессора ESXi хоста, занятого «полезной работой»",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization %" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('esxhostname=$esxihostname', 'cpu=instance-total', 'name=service.vcenter.usage_average', 'vmname!=~*'), 'CPU')"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "description": "График динамики использования оперативной памяти ESXi хоста в ГБ ",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('esxhostname=$esxihostname', 'name=service.vcenter.active_average', 'vmname!=~*'), 'Active')"
    },
    {
     "target": "alias(seriesByTag('esxhostname=$esxihostname', 'name=service.vcenter.granted_average', 'vmname!=~*'), 'Granted')"
    },
    {
     "target": "alias(seriesByTag('esxhostname=$esxihostname', 'name=service.vcenter.vmmemctl_average', 'vmname!=~*'), 'Balloon')"
    },
    {
     "target": "alias(seriesByTag('esxhostname=$esxihostname', 'name=service.vcenter.consumed_average'), 'Consumed')"
    },
    {
     "target": "alias(seriesByTag('vcenter=$vcenter', 'clustername=~${cluster:regex}', 'esxhostname=$esxihostname', 'name=service.vcenter.swapused_average', 'interval=20s'), 'Swap')"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "stat",
   "description": "Процент использования процессора ESXi хоста, занятого «полезной работой»  (средний за последние  20 сек)",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('esxhostname=$esxihostname', 'cpu=instance-total', 'name=service.vcenter.usage_average', 'vmname!=~*')"
    }
   ]
  },
  {
   "title": "RAM Usage %",
   "type": "stat",
   "description": "Процент использования оперативной памяти ESXi хоста (средний за последние  20 сек)",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "seriesByTag('esxhostname=$esxihostname', 'name=service.vcenter.usage_average', 'cpu!=~*', 'interface!=~*', 'vmname!=~*')"
    }
   ]
  },
  {
   "title": "VM CPU Utilization (Top 10)",
   "type": "graph",
   "description": "График утилизации операций ввода/вывода по каждому LUN  ESXi хоста  (IOPS) ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Mhz" }
   ],
   "targets": [
    {
     "target": "highestCurrent(aliasByTags(seriesByTag('esxhostname=$esxihostname', 'vmname=~*', 'cpu=instance-total', 'name=service.vcenter.usagemhz_average'), 'vmname'), 10)"
    }
   ]
  },
  {
   "title": "VM RAM Utilization (Top 10)",
   "type": "graph",
   "description": "График задержек операций ввода/вывода по каждому сторадж адаптеру ESXi хоста ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "highestCurrent(aliasByTags(seriesByTag('esxhostname=$esxihostname', 'vmname=~*', 'cpu!=~*', 'name=service.vcenter.active_average'), 'vmname'), 10)"
    }
   ]
  },
  {
   "title": "Total Datstore Iops",
   "type": "graph",
   "description": "График утилизации сетевых интерфейсов ESXi хоста (МБ/с)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "iops", "label": "Disk Usage" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('esxhostname=$esxihostname', 'dsname=~${datastore:regex}', 'name=service.vcenter.numberReadAveraged_average'), 'dsname', 'name'), '.service.vcenter.numberReadAveraged_average', ' Read')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('esxhostname=$esxihostname', 'dsname=~${datastore:regex}', 'name=service.vcenter.numberWriteAveraged_average'), 'dsname', 'name'), '.service.vcenter.numberWriteAveraged_average', ' Write')"
    }
   ]
  },
  {
   "title": "Storage Adapter Latency",
   "type": "graph",
   "description": "График динамики числа ошибок на сетевых интерфейсах ESXi хоста",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms", "label": "Disk latency" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('esxhostname=$esxihostname', 'adapter=~${adapter:regex}', 'name=service.vcenter.totalReadLatency_average'), 'adapter', 'name'), '.service.vcenter.totalReadLatency_average', ' Read')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('esxhostname=$esxihostname', 'adapter=~${adapter:regex}', 'name=service.vcenter.totalWriteLatency_average'), 'adapter', 'name'), '.service.vcenter.totalWriteLatency_average', ' Write')"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "description": "Топ 10 ВМ на ESXi хосте по  использования процессора ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "KBs", "label": "Network Usage" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('esxhostname=$esxihostname', 'interface=~${interface:regex}', 'name=service.vcenter.bytesRx_average', 'vmname!=~*'), 'interface', 'name'), '.service.vcenter.bytesRx_average', ' Rx')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('esxhostname=$esxihostname', 'interface=~${interface:regex}', 'name=service.vcenter.bytesTx_average', 'vmname!=~*'), 'interface', 'name'), '.service.vcenter.bytesTx_average', ' Tx')"
    }
   ]
  },
  {
   "title": "Network interface error",
   "type": "graph",
   "description": "Топ 10 ВМ на ESXi хосте по проценту использования оперативной памяти ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "count " }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('esxhostname=$esxihostname', 'name=service.vcenter.errorsRx_summation'), 'interface', 'name'), '.service.vcenter.errorsRx_summation', ' error Rx')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('esxhostname=$esxihostname', 'name=service.vcenter.errorsTx_summation'), 'interface', 'name'), '.service.vcenter.errorsTx_summation', ' error Tx')"
    }
   ]
  },
  {
   "title": "VM Net Utilization (Top 10)",
   "type": "graph",
   "description": "Топ 10 ВМ на ESXi хосте по утилизации сетевых интерфейсов ВМ (МБ/с)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "KBs", "label": "Mhz" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(highestCurrent(aliasByTags(groupByTags(seriesByTag('esxhostname=$esxihostname', 'vmname=~*', 'name=~service.vcenter.bytesTx_average', 'interface=instance-total'), 'sum', 'vmname', 'name'), 'vmname', 'name'), 10), 'unix.tensor.ru.service.vcenter.bytes', ''), '_average', '')"
    },
    {
     "target": "aliasSub(aliasSub(highestCurrent(aliasByTags(groupByTags(seriesByTag('esxhostname=$esxihostname', 'vmname=~*', 'name=~service.vcenter.bytesRx_average', 'interface=instance-total'), 'sum', 'vmname', 'name'), 'vmname', 'name'), 10), 'unix.tensor.ru.service.vcenter.bytes', ''), '_average', '')"
    }
   ]
  }
 ]
}