{
 "title": "Доступность сайтов из интернет",
 "description": "Ответственный: Ледяев И.К. (Эксплуатация)",
 "tags": [
  "telegraf",
  "service",
  "sites",
  "internet"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Максимальное время получения страницы online.sbis.ru с трёх удалённых площадок",
   "type": "graph",
   "description": "Проверка доступности и время ответа главной страницы online.sbis.ru с внешних серверов",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(groupByTags(seriesByTag('name=response.time', 'unit=ext_english', 'route=outside'), 'max', 'site'), 'site'), 'https:--', ' '), '-$', '')"
    }
   ]
  },
  {
   "title": "Время получения HTTP статуса (10 самых медленных)",
   "type": "graph",
   "description": "Время ответа и доступность страниц /!ping/ для сайтов доступных снаружи, проверяется с внешних серверов мониторинга\n",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(highestMax(seriesByTag('name=http_response.response_time', 'host=~(monitor-remote-3.local|us.malysh|379475)'), 10), 'server', 'host'), 'https:--', ' '), '-\\_ping-', '')"
    }
   ]
  },
  {
   "title": "Время получения HTTP статуса (10 NODATA)",
   "type": "graph",
   "description": "Время ответа и доступность страниц /!ping/ для сайтов доступных снаружи, проверяется с внешних серверов мониторинга\n",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "lowestMax(aliasSub(aliasSub(aliasByTags(removeAboveValue(transformNull(seriesByTag('name=http_response.response_time', 'host=~(monitor-remote-3.local|us.malysh|379475)'), -1), 0), 'server', 'host'), 'https:--', ' '), '-\\_ping-', ''), 10)"
    }
   ]
  },
  {
   "title": "Аптайм / Доступность внешних площадок",
   "type": "graph",
   "description": "Для определения доступности потока метрик выведена метрика uptime сервера. Если выводит время - все ок. Если выводит -1 или не выводит ничего - значит данные недоступны с площадок и доступность сайтов вместе с ними не актуальна. \nТриггер: serv.site.external.response_nodata",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(transformNull(seriesByTag('name=system.system.uptime', 'host=~(monitor-remote-3.local|us.malysh|379475)'), -1), 'host')"
    }
   ]
  },
  {
   "title": "Доступность APPLE API",
   "type": "graph",
   "description": "Возвращает 1, если АПИ рабочее и 0 если нерабочее.\nПоставка скриптом  https://adm-git.tensor.ru/exp/monitoring-scripts/montools/-/blob/master/scripts/apple_sites_api_mon.py",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=apple_sites_api_response'), 'site')"
    }
   ]
  }
 ]
}