{
 "title": "Доступность портов СКУД",
 "description": "Ответственный: Фролов М.А. (АХО)",
 "tags": [
  "system",
  "telegraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "SecurosHost",
    "label": "Hosts with SecurOS",
    "query": "tag_values(server,service=SecurOS)"
   },
   {
    "name": "TrassirOSHost",
    "label": "Hosts with TrassirOS",
    "query": "tag_values(server,service=TrassirOS)"
   },
   {
    "name": "CentralServer",
    "label": "Hosts with TrassirOS",
    "query": "tag_values(server,service=Central_server)"
   }
  ]
 },
 "panels": [
  { "title": "SecurOS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SecurOS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=net_response.response_time', 'service=SecurOS', 'server=~${SecurosHost:regex}'), 'server')"
    }
   ]
  },
  { "title": "TrassirOS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "TrassirOS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=net_response.response_time', 'service=TrassirOS', 'server=~${TrassirOSHost:regex}'), 'server')"
    }
   ]
  },
  { "title": "СКУД", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Central Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=net_response.response_time', 'service=Central_server', 'server=~${CentralServer:regex}'), 'server')"
    }
   ]
  },
  {
   "title": "Integration module",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=net_response.response_time', 'service=Integration_module', 'server=~${CentralServer:regex}'), 'server')"
    }
   ]
  },
  {
   "title": "Survey core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=net_response.response_time', 'service=Survey_core', 'server=~${CentralServer:regex}'), 'server')"
    }
   ]
  }
 ]
}