{
 "title": "Климат У36. 3 этаж",
 "description": "Ответственный: Лебедев А.А. (АЦОД)",
 "tags": [
  "climate",
  "temperature",
  "humidity"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "План 3 этажа",
   "type": "agenty-flowcharting-panel",
   "description": "Температура и относительная влажность помещений 3 этажа У36\t",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-302-SENSOR'), '302temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-302-SENSOR'), '302hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-305-1-SENSOR'), '305-1temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-305-1-SENSOR'), '305-1hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-305-2-SENSOR'), '305-2temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-305-2-SENSOR'), '305-2hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-305-3-SENSOR'), '305-3temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-305-3-SENSOR'), '305-3hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-305-4-SENSOR'), '305-4temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-305-4-SENSOR'), '305-4hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-316-SENSOR'), '316temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-316-SENSOR'), '316hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-337-1-SENSOR'), '337-1temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-337-1-SENSOR'), '337-1hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-337_2-SENSOR'), '337-2temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-337_2-SENSOR'), '337-2hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-338-SENSOR'), '338temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-338-SENSOR'), '338hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-339-1-SENSOR'), '339-1temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-339-1-SENSOR'), '339-1hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-339-2-SENSOR'), '339-2temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-339-2-SENSOR'), '339-2hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-340-SENSOR'), '340temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-340-SENSOR'), '340hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-341-1-SENSOR'), '341-1temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-341-1-SENSOR'), '341-1hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-341-2-SENSOR'), '341-2temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-341-2-SENSOR'), '341-2hum')"
    }
   ]
  },
  {
   "title": "Температура",
   "type": "timeseries",
   "description": "Температура помещений 3 этажа У36",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-302-SENSOR'), '302')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-305-1-SENSOR'), '305-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-305-2-SENSOR'), '305-2')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-305-3-SENSOR'), '305-3')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-305-4-SENSOR'), '305-4')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-316-SENSOR'), '316')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-337-1-SENSOR'), '337-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-337_2-SENSOR'), '337-2')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-338-SENSOR'), '338')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-339-1-SENSOR'), '339-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-339-2-SENSOR'), '339-2')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-340-SENSOR'), '340')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-341-1-SENSOR'), '341-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-341-2-SENSOR'), '341-2')"
    }
   ]
  },
  {
   "title": "Относительная влажность",
   "type": "timeseries",
   "description": "Относительная влажность помещений 3 этажа У36\t",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-302-SENSOR'), '302')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-305-1-SENSOR'), '305-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-305-2-SENSOR'), '305-2')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-305-3-SENSOR'), '305-3')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-305-4-SENSOR'), '305-4')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-316-SENSOR'), '316')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-337-1-SENSOR'), '337-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-337_2-SENSOR'), '337-2')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-338-SENSOR'), '338')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-339-1-SENSOR'), '339-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-339-2-SENSOR'), '339-2')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-340-SENSOR'), '340')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-341-1-SENSOR'), '341-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-341-2-SENSOR'), '341-2')"
    }
   ]
  }
 ]
}