{
 "title": "Климат У36. 2 этаж",
 "description": "Ответственный: Лебедев А.А. (АЦОД)",
 "tags": [
  "climate",
  "temperature",
  "humidity"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "План этажа",
   "type": "agenty-flowcharting-panel",
   "description": "Температура и относительная влажность помещений 2 этажа У36\t",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-205-1-SENSOR'), '205-1temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-205-1-SENSOR'), '205-1hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-205-2-SENSOR'), '205-2temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-205-2-SENSOR'), '205-2hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-205-3-SENSOR'), '205-3temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-205-3-SENSOR'), '205-3hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-205-4-SENSOR'), '205-4temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-205-4-SENSOR'), '205-4hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-230-1-SENSOR'), '230-1temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-230-1-SENSOR'), '230-1hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-230-2-SENSOR'), '230-2temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-230-2-SENSOR'), '230-2hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-229-SENSOR'), '229temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-229-SENSOR'), '229hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-227-SENSOR'), '227temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-227-SENSOR'), '227hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-211-SENSOR'), '211temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-211-SENSOR'), '211hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-225-SENSOR'), '225temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-225-SENSOR'), '225hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-224-SENSOR'), '224temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-224-SENSOR'), '224hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-219-SENSOR'), '219temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-219-SENSOR'), '219hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-222-1-SENSOR'), '222-1temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-222-1-SENSOR'), '222-1hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-222-2-SENSOR'), '222-2temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-222-2-SENSOR'), '222-2hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-226-1-SENSOR'), '226-1temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-226-1-SENSOR'), '226-1hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-226-2-SENSOR'), '226-2temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-226-2-SENSOR'), '226-2hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-226-3-SENSOR'), '226-3temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-221-SENSOR'), '221temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-226-3-SENSOR'), '226-3hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-221-SENSOR'), '221hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-205-5-SENSOR'), '205-5temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-205-5-SENSOR'), '205-5hum')"
    }
   ]
  },
  {
   "title": "Температура",
   "type": "timeseries",
   "description": "Температура помещений 2 этажа У36",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-205-1-SENSOR'), '205-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-205-2-SENSOR'), '205-2')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-205-3-SENSOR'), '205-3')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-205-4-SENSOR'), '205-4')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-205-5-SENSOR'), '205-5')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-211-SENSOR'), '211')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-219-SENSOR'), '219')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-221-SENSOR'), '221')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-222-1-SENSOR'), '222-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-222-2-SENSOR'), '222-2')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-224-SENSOR'), '224')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-225-SENSOR'), '225')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-226-1-SENSOR'), '226-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-226-2-SENSOR'), '226-2')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-226-3-SENSOR'), '226-3')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-227-SENSOR'), '227')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-229-SENSOR'), '229')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-230-1-SENSOR'), '230-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-230-2-SENSOR'), '230-2')"
    }
   ]
  },
  {
   "title": "Относительная влажность",
   "type": "timeseries",
   "description": "Относительная влажность помещений 2 этажа У36",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-205-1-SENSOR'), '205-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-205-2-SENSOR'), '205-2')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-205-3-SENSOR'), '205-3')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-205-4-SENSOR'), '205-4')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-205-5-SENSOR'), '205-5')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-211-SENSOR'), '211')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-219-SENSOR'), '219')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-221-SENSOR'), '221')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-222-1-SENSOR'), '222-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-222-2-SENSOR'), '222-2')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-224-SENSOR'), '224')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-225-SENSOR'), '225')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-226-1-SENSOR'), '226-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-226-2-SENSOR'), '226-2')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-226-3-SENSOR'), '226-3')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-227-SENSOR'), '227')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-229-SENSOR'), '229')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-230-1-SENSOR'), '230-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-230-2-SENSOR'), '230-2')"
    }
   ]
  }
 ]
}