{
 "title": "Климат У36. 1 этаж",
 "description": "Ответственный: Лебедев А.А. (АЦОД)",
 "tags": [
  "climate",
  "temperature",
  "humidity"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "План этажа",
   "type": "agenty-flowcharting-panel",
   "description": "Температура и относительная влажность помещений 1 этажа У36",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-107-SENSOR'), '107temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-107-SENSOR'), '107hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-103-SENSOR'), '103temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-103-SENSOR'), '103hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-103-1-SENSOR'), '103-1temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-103-1-SENSOR'), '103-1hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-119-SENSOR'), '119temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-119-SENSOR'), '119hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-154-SENSOR'), '154temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-154-SENSOR'), '154hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-151-1-SENSOR'), '151-1temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-151-1-SENSOR'), '151-1hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-151-2-SENSOR'), '151-2temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-151-2-SENSOR'), '151-2hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-150-SENSOR'), '150temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-150-SENSOR'), '150hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-152-SENSOR'), '152temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-152-SENSOR'), '152hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-rest-1-SENSOR'), 'rest-1temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-rest-1-SENSOR'), 'rest-1hum')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-145-SENSOR'), '145temp')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-145-SENSOR'), '145hum')"
    }
   ]
  },
  {
   "title": "Температура",
   "type": "timeseries",
   "description": "Температура помещений 1 этажа У36",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-107-SENSOR'), '107')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-103-SENSOR'), '103')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-103-1-SENSOR'), '103-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-119-SENSOR'), '119')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-154-SENSOR'), '154')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-151-1-SENSOR'), '151-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-151-2-SENSOR'), '151-2')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-150-SENSOR'), '150')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-152-SENSOR'), '152')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-rest-1-SENSOR'), 'rest-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Temperature', 'topic=tele-145-SENSOR'), '145')"
    }
   ]
  },
  {
   "title": "Относительная влажность",
   "type": "timeseries",
   "description": "Относительная влажность помещений 1 этажа У36",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-103-1-SENSOR'), '103-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-103-SENSOR'), '103')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-rest-1-SENSOR'), 'rest-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-119-SENSOR'), '119')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-152-SENSOR'), '152')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-154-SENSOR'), '154')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-145-SENSOR'), '145')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-151-1-SENSOR'), '151-1')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-151-2-SENSOR'), '151-2')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-150-SENSOR'), '150')"
    },
    {
     "target": "alias(seriesByTag('name=~mqtt_consumer.SI7021_Humidity', 'topic=tele-107-SENSOR'), '107')"
    }
   ]
  }
 ]
}