{
 "title": "СБИС Диск - Ceph/swift network advanced TCP/IP statistics",
 "description": "Основные метрики описаны https://www.kernel.org/doc/html/latest/networking/snmp_counter.html Ответственный: Грошев А.Н. (Разработка)",
 "tags": [
  "sbisdisk",
  "ceph",
  "system",
  "telegraf",
  "swift"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "cluster",
    "query": "tag_values(cluster,servertype=~(swift|ceph))"
   },
   {
    "name": "host",
    "query": "tag_values(host,cluster=$cluster)"
   },
   { "name": "metric_name", "label": "metric name", "query": "tag_values(metric_name)" }
  ]
 },
 "panels": [
  {
   "title": "Errors (дельта)",
   "type": "graph",
   "description": "* IcmpInErrors - количество неправильных вхозящих ICMP пакетов (не правильная контрольная сумма или размер и т.п.)\n* IpInHdrErrors - количество отброщенных датаграмм из-за неправильного IP заголовка\n* TcpInErrs - количество не правильных TCP пакетов (не правильная контрольная сумма или размер и т.п.)\n* UdpInErrors - количество UDP датаграмм которые не удалось доставить, но не по причине отсутствия программы на порту\n* UdpRcvbufErrors - увеличивается когда под входящий UDP нехватает буфера\n\nОписание других метрик можно посмотреть здесь: \n* https://www.kernel.org/doc/html/latest/networking/snmp_counter.html\n* https://datatracker.ietf.org/doc/html/rfc1213\n* https://loicpefferkorn.net/2018/09/linux-network-statistics-reference/",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(derivative(seriesByTag('name=ceph_adv_network', 'metric_name=~.*Err.*', 'host=~${host:regex}', 'cluster=${cluster:regex}')), 'host', 'metric_name')"
    }
   ]
  },
  {
   "title": "Drops и прочие проблемы (дельта)",
   "type": "graph",
   "description": "* TcpExtListenDrops - количество отброшенных TCP пакеты например из-за полной очереди\n* TcpExtTCPBacklogDrop - количество отброшенных пакетов TCP из-за исчерпания backlog-а\n* TcpExtListenOverflows - количество отброшенных переполнений буфера приёма.\n* TcpExtTCPFastRetrans - cтек TCP хочет повторно передать пакет, и состояние управления перегрузкой не является «Потеря»????\n* TcpExtTCPForwardRetrans -\n* TcpExtTCPLostRetransmit - SACK указывает, что пакет повторной передачи снова потерян.\n* TcpExtTCPRetransFail - Стек TCP пытается повторно доставить пакет на уровень нижние, но нижний уровень возвращают ошибку.\n* TcpExtTCPSlowStartRetrans - Стек TCP хочет повторно передать пакет, а состояние управления перегрузкой - «Потеря».???\n* TcpExtTCPSynRetrans - Стек TCP повторно передает пакет SYN. \n* TcpRetransSegs - \n* TcpExtTCPReqQFullDoCookies - detecting where SYN cookies were used to mitigate a lack of SYN backlog space\n* TcpExtTCPReqQFullDrop - detecting where SYNs were dropped because SYN cookies were disabled and the SYN backlog was full\n* TcpExtListenOverflows - detecting when a TCP connection completed the 3-way handshake but the accept queue was full or when a SYN was received while the accept queue was full\n\n\nОписание других метрик можно посмотреть здесь: \n* https://www.kernel.org/doc/html/latest/networking/snmp_counter.html\n* https://datatracker.ietf.org/doc/html/rfc1213\n* https://loicpefferkorn.net/2018/09/linux-network-statistics-reference/\n* https://theojulienne.io/2020/07/03/scaling-linux-services-before-accepting-connections.html",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(derivative(seriesByTag('name=ceph_adv_network', 'metric_name=~.*(Drop|Overf|Retrans|Listen).*', 'host=~${host:regex}', 'cluster=${cluster:regex}')), 'host', 'metric_name')"
    }
   ]
  },
  { "title": "Все остальные метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Все метрики (выбираются через верхнюю переключалку, дельта)",
   "type": "graph",
   "description": "ВСЕ счетчики TCP/IP через nstat -a",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(derivative(seriesByTag('name=ceph_adv_network', 'metric_name=~${metric_name:regex}', 'host=~${host:regex}', 'cluster=${cluster:regex}')), 'host', 'metric_name')"
    }
   ]
  }
 ]
}