{
 "title": "СБИС Диск - Ceph/swift ethtool statistics",
 "description": "Основные метрики описаны https://www.kernel.org/doc/html/latest/networking/snmp_counter.html Ответственный: Грошев А.Н. (Разработка)",
 "tags": [
  "sbisdisk",
  "ceph",
  "system",
  "telegraf",
  "swift"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "tag_values(cluster,servertype=~(swift|ceph))"
   },
   {
    "name": "host",
    "query": "tag_values(host,cluster=$cluster)"
   },
   {
    "name": "interface",
    "query": "tag_values(interface,host=$host,cluster=$cluster)"
   },
   {
    "name": "metric",
    "query": "tag_values(name,interface=$interface,host=$host,cluster=$cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Ethtool errors (per second)",
   "type": "graph",
   "description": "Стистика ошибок через ethtool",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(perSecond(seriesByTag('host=~${host:regex}', 'cluster=${cluster:regex}', 'interface=${interface:regex}', 'name=~.*err.*')))"
    }
   ]
  },
  {
   "title": "Ethtool selected metrics (per second)",
   "type": "graph",
   "description": "Выбранная метрика из ethtool",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(perSecond(seriesByTag('host=~${host:regex}', 'cluster=${cluster:regex}', 'interface=${interface:regex}', 'name=~ethtool.${metric:regex}$')))"
    }
   ]
  },
  {
   "title": "Общее количество ошибок в кластере (получение)",
   "type": "graph",
   "description": "Общее количество ошибок во входящем потоке Ethernet на всех нодах кластера ",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(perSecond(seriesByTag('cluster=${cluster:regex}', 'name=~ethtool.rx_(stat_err|errors)')), 'sum', 'host'), 'host')"
    }
   ]
  },
  {
   "title": "Общее количество ошибок в кластере (отправка)",
   "type": "graph",
   "description": "Общее количество ошибок во исходящем потоке Ethernet на всех нодах кластера ",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(groupByTags(perSecond(seriesByTag('cluster=${cluster:regex}', 'name=~ethtool.tx_(stat_err|errors)')), 'sum', 'host'), 'host')"
    }
   ]
  }
 ]
}