{
 "title": "Сетевое оборудование: Network Device System 2",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "network",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "tag_values(device, net_segment=dc)"
   }
  ]
 },
 "panels": [
  { "title": "Бэкапы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Бэкап статус",
   "type": "stat",
   "description": "Состояние резервного копирования конфигурации сетевого устройства",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=backup.status', 'device=$device')"
    }
   ]
  },
  {
   "title": "Бэкап статус",
   "type": "graph",
   "description": "График изменения состояния резервного копирования конфигурации сетевого устройства",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=backup.status', 'device=$device'), '0 - ОК, 1 - Старый, -1 - Ошибка, -2 - Выключен')"
    }
   ]
  },
  {
   "title": "Конфиг",
   "type": "stat",
   "description": "Сохранена ли конфигурация сетевого устройства",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=backup.save_status', 'device=$device')"
    }
   ]
  },
  {
   "title": "Конфиг",
   "type": "graph",
   "description": "График изменения показателя сохраненности конфига",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=backup.save_status', 'device=$device'), '0 - Сохранен, 1 - Не сохранен')"
    }
   ]
  },
  { "title": "События из логов", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Событий в логах",
   "type": "stat",
   "description": "Количество ошибок в логах за выбранный в панели период",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=system.log.events', 'device=$device')"
    }
   ]
  },
  {
   "title": "Событий в логах",
   "type": "graph",
   "description": "График появления ошибок в логах",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=system.log.events', 'device=$device'), 'log events per 10 min')"
    }
   ]
  },
  {
   "title": "События из логов (только для коммутаторов)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Обнаружено BPDU",
   "type": "stat",
   "description": "Количество сработок BPDU guard за выбранный в панели период",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=switch.bpdu.events', 'device=$device')"
    }
   ]
  },
  {
   "title": "Обнаружено BPDU",
   "type": "graph",
   "description": "График сработок BPDU guard",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=switch.bpdu.events', 'device=$device'), 'BPDU events per 10 min')"
    }
   ]
  },
  {
   "title": "Обнаружено петель",
   "type": "stat",
   "description": "Количество обнаруженных петель за выбранный в панели период",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=switch.loop.events', 'device=$device')"
    }
   ]
  },
  {
   "title": "Обнаружено петель",
   "type": "graph",
   "description": "График обнаружения петель",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=switch.loop.events', 'device=$device'), 'LOOP events per 10 min')"
    }
   ]
  }
 ]
}