{
 "title": "Сетевое оборудование: Network Device ASA",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "network",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "device", "query": "tag_values(device, model=asa)" }
  ]
 },
 "panels": [
  {
   "title": "Failover state",
   "type": "stat",
   "description": "Состояние нод, линка и синхронизации кластера failover",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('device=$device', 'name=~failover.*'), 1)"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "description": "Общее количество коннекций на устройстве",
   "gridPos": { "h": 10, "w": 10, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('device=$device', 'name=system.conn.value'), 'connections')"
    },
    {
     "target": "aliasByTags(seriesByTag('device=$device', 'name=system.conn.limit'), 2)"
    }
   ]
  },
  {
   "title": "New connections per second",
   "type": "graph",
   "description": "Количество новых соединений в секунду",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('device=$device', 'name=system.connrate.value'), 'connections per second')"
    },
    {
     "target": "aliasByTags(seriesByTag('device=$device', 'name=system.connrate.limit'), 2)"
    }
   ]
  },
  {
   "title": "Статус AAA-серверов",
   "type": "table",
   "description": "Состояние связи с AAA-серверами",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "sortByName(aliasSub(aliasByTags(seriesByTag('device=$device', 'name=aaa.server.status', 'group!=LOCAL'), 'group', 'addr'), '([^.]+)\\.(\\S+)', '\\1: \\2'), false)"
    }
   ]
  },
  {
   "title": "VPN traffic",
   "type": "graph",
   "description": "Трафик VPN (если есть)",
   "gridPos": { "h": 10, "w": 10, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(scale(perSecond(seriesByTag('device=$device', 'name=~vpn\\.(ike|ipsec)\\.(in|out)_octets')), 8), '^.+(ike|ipsec).*(in|out)_octets.*$', '\\1 \\2')"
    }
   ]
  },
  {
   "title": "VPN tunnels",
   "type": "graph",
   "description": "Количество туннелей VPN (если есть)",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(seriesByTag('device=$device', 'name=~vpn\\.(ike|ipsec)\\.tunnels'), '^.+(ike|ipsec).+$', '\\1')"
    }
   ]
  }
 ]
}