{
 "title": "Сетевое оборудование: Суммарный трафик сегментов ЦОД",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "scripts",
  "network",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "PROD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ACI Prod (pod-1, У36)",
   "type": "timeseries",
   "description": "Суммарный входящий трафик на всех портах leaf",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "alias(scale(sum(seriesByTag('aci=ACI-200', 'name=aci_interface_in_bytes_total.value_rate', 'node=~leaf-\\d+$', 'description!=Fabric')), 8, 0), 'In bps', false)"
    },
    {
     "target": "alias(scale(sum(seriesByTag('aci=ACI-200', 'name=aci_interface_out_bytes_total.value_rate', 'node=~leaf-\\d+$', 'description!=Fabric')), 8, 0), 'Out bps', false)"
    },
    {
     "target": "alias(sum(seriesByTag('aci=ACI-200', 'name=aci_interface_in_pkts_total.value_rate', 'node=~leaf-\\d+$', 'description!=Fabric')), 'In pps', false)"
    },
    {
     "target": "alias(sum(seriesByTag('aci=ACI-200', 'name=aci_interface_out_pkts_total.value_rate', 'node=~leaf-\\d+$', 'description!=Fabric')), 'Out pps', false)"
    }
   ]
  },
  {
   "title": "Трафик между У36 и Технопарковой",
   "type": "timeseries",
   "description": "Трафик между подами прода",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "alias(sum(scale(seriesByTag('device=~dts-sw\\d-core-prod-u36', 'interface=port-channel15', 'name=interface.traffic.in_octets_rate'), 8)), 'Технопарковая -> У36 bps', false)"
    },
    {
     "target": "alias(sum(scale(seriesByTag('device=~dts-sw\\d-core-prod-u36', 'interface=port-channel15', 'name=interface.traffic.out_octets_rate'), 8)), 'У36 -> Технопарковая bps', false)"
    },
    {
     "target": "alias(sum(seriesByTag('device=~dts-ipn\\d-u36', 'interface=port-channel15', 'name=~interface.traffic.in_(uni|multi|broad)cast_pkts_rate')), 'Технопарковая -> У36 pps', false)"
    },
    {
     "target": "alias(sum(seriesByTag('device=~dts-ipn\\d-u36', 'interface=port-channel15', 'name=~interface.traffic.out_(uni|multi|broad)cast_pkts_rate')), 'У36 -> Технопарковая pps', false)"
    }
   ]
  },
  {
   "title": "ЦОД (Технопарковая)",
   "type": "timeseries",
   "description": "Суммарный входящий трафик на всех портах leaf",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "alias(scale(sum(seriesByTag('device=~dts-leaf-\\d+-pod2', 'name=interface.traffic.in_octets_rate', 'interface=~Ethernet.*')), 8, 0), 'In bps', false)"
    },
    {
     "target": "alias(scale(sum(seriesByTag('device=~dts-leaf-\\d+-pod2', 'name=interface.traffic.out_octets_rate', 'interface=~Ethernet.*')), 8, 0), 'Out bps', false)"
    },
    {
     "target": "alias(scale(sum(seriesByTag('device=~dts-leaf-\\d+-pod2', 'name=interface.traffic.in_unicast_pkts_rate', 'interface=~Ethernet.*')), 8, 0), 'In pps', false)"
    },
    {
     "target": "alias(scale(sum(seriesByTag('device=~dts-leaf-\\d+-pod2', 'name=interface.traffic.out_unicast_pkts_rate', 'interface=~Ethernet.*')), 8, 0), 'Out pps', false)"
    }
   ]
  },
  {
   "title": "Ядро ЦОД Продуктива",
   "type": "timeseries",
   "description": "Суммарный входящий трафик на всех портах кластера коммутаторов ядра сегмента.\n\nСамо по себе значение мало о чем говорит, полезно смотреть на тренд (насколько меняется нагрузка на внутреннюю сеть ЦОД в долгосрочной перспективе)",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "alias(scale(sum(seriesByTag('device=~dts-sw\\d-core-ea1', 'interface=~Ethernet.*', 'name=interface.traffic.in_octets_rate')), 8), 'In bps', false)"
    },
    {
     "target": "alias(sum(seriesByTag('device=~dts-sw\\d-core-ea1', 'interface=~Ethernet.*', 'name=~interface.traffic.in_(uni|multi|broad)cast_pkts_rate')), 'In pps', false)"
    }
   ]
  },
  { "title": "DEV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "ACI Dev (pod-1)",
   "type": "timeseries",
   "description": "Суммарный входящий трафик на всех портах leaf",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "alias(scale(sum(seriesByTag('aci=ACI-DEV-100', 'name=aci_interface_in_bytes_total.value_rate', 'node=~LEAF-\\d+$', 'description!=Fabric')), 8, 0), 'In bps', false)"
    },
    {
     "target": "alias(scale(sum(seriesByTag('aci=ACI-DEV-100', 'name=aci_interface_out_bytes_total.value_rate', 'node=~LEAF-\\d+$', 'description!=Fabric')), 8, 0), 'Out bps', false)"
    },
    {
     "target": "alias(sum(seriesByTag('aci=ACI-DEV-100', 'name=aci_interface_in_pkts_total.value_rate', 'node=~LEAF-\\d+$', 'description!=Fabric')), 'In pps', false)"
    },
    {
     "target": "alias(sum(seriesByTag('aci=ACI-DEV-100', 'name=aci_interface_out_pkts_total.value_rate', 'node=~LEAF-\\d+$', 'description!=Fabric')), 'Out pps', false)"
    }
   ]
  },
  {
   "title": "Ядро ЦОД Разработки",
   "type": "timeseries",
   "description": "Суммарный входящий трафик на всех портах кластера коммутаторов ядра сегмента.\n\nСамо по себе значение мало о чем говорит, полезно смотреть на тренд (насколько меняется нагрузка на внутреннюю сеть ЦОД в долгосрочной перспективе)",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "alias(scale(sum(seriesByTag('device=~dts-sw\\d-core-dev', 'interface=~Ethernet.*', 'name=interface.traffic.in_octets_rate')), 8), 'In bps', false)"
    },
    {
     "target": "alias(sum(seriesByTag('device=~dts-sw\\d-core-dev', 'interface=~Ethernet.*', 'name=~interface.traffic.in_(uni|multi|broad)cast_pkts_rate')), 'In pps', false)"
    }
   ]
  }
 ]
}