{
 "title": "Сетевое оборудование: Интернет-провайдеры DDoS-защита",
 "description": "Ответственный: Кралин А. Е. (СПД)",
 "tags": [
  "dts",
  "internet",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "isp",
    "query": "tag_values(description, type=isp)"
   }
  ]
 },
 "panels": [
  {
   "title": "DDoS-защита",
   "type": "stat",
   "description": "Состояние системы защиты на стороне провайдера. No data означает, что у этого провайдера отсутствует услуга защиты от DDoS",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=isp.ddos.status', 'isp=$isp')"
    }
   ]
  },
  {
   "title": "DDoS-защита",
   "type": "graph",
   "description": "Состояние системы защиты на стороне провайдера. No data означает, что у этого провайдера отсутствует услуга защиты от DDoS",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=isp.ddos.status', 'isp=$isp'), '0 - Нет атаки, 1 - Атака')"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "description": "Трафик через провайдера (в байтах). Измерен на порту пограничного маршрутизатора",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(scale(sum(seriesByTag('device=~dts-r\\d-border', 'name=interface.traffic.in_octets_rate', 'description=$isp')), 8), 'In')"
    },
    {
     "target": "alias(scale(sum(seriesByTag('device=~dts-r\\d-border', 'name=interface.traffic.out_octets_rate', 'description=$isp')), 8), 'Out')"
    },
    {
     "target": "alias(scale(maxSeries(seriesByTag('device=~dts-r\\d-border', 'name=interface.traffic.speed', 'description=$isp')), 1000000), 'Bandwidth')"
    }
   ]
  },
  {
   "title": "Инфо",
   "type": "text",
   "description": "Справочная информация и полезные ссылки по системе защиты от DdoS",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 6 },
   "options": {
    "content": "# Ссылки\n\n- [Инструкция для дежурного](https://dpc-docs.tensor.ru/pages/viewpage.action?pageId=63907132)\n- [Документация на систему](https://dpc-docs.tensor.ru/pages/viewpage.action?pageId=51980212)\n- [Как работает мониторинг](https://dpc-docs.tensor.ru/pages/viewpage.action?pageId=74882761)\n\n----\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Packet rate",
   "type": "timeseries",
   "description": "Трафик через провайдера (в пакетах). Измерен на порту пограничного маршрутизатора",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "target": "sortByMaxima(aliasSub(aliasSub(aliasByTags(seriesByTag('device=dts-r1-border', 'description=$isp', 'name=~interface\\.traffic\\.(in|out)_unicast_pkts_rate'), 2), '_', ' '), 'pkts', ''))"
    }
   ]
  }
 ]
}