{
 "title": "Сетевое оборудование: ACI QoS",
 "description": "Трафик. Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "telegraf",
  "dts",
  "aci",
  "system"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "fabric", "query": "tag_values(aci)" },
   {
    "name": "node",
    "query": "tag_values(node,aci=$fabric, interface!=)"
   },
   { "name": "class", "query": "tag_values(class,aci=$fabric)" }
  ]
 },
 "panels": [
  {
   "title": "Admit pps per QoS class",
   "type": "timeseries",
   "description": "Количество переданных входящих/исходящих пакетов каждого класса на интерфейсах узлов фабрики",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "target": "aliasSub(sortByMaxima(aliasSub(aliasByTags(seriesByTag('aci=${fabric:regex}', 'node=${node:regex}', 'name=aci_interface_qos_rx_admit_pps_total.value_rate', 'class=~${class:regex}'), 'interface', 'class'), '\\.', ' ')), '^', 'RX - ')"
    },
    {
     "target": "aliasSub(sortByMaxima(aliasSub(aliasByTags(scale(seriesByTag('aci=${fabric:regex}', 'node=${node:regex}', 'name=aci_interface_qos_tx_admit_pps_total.value_rate', 'class=~${class:regex}'), -1, 0), 'interface', 'class'), '\\.', ' ')), '^', 'TX - ')"
    }
   ]
  },
  {
   "title": "Admit bytes per QoS class",
   "type": "timeseries",
   "description": "Количество переданных входящих/исходящих байт каждого класса на интерфейсах узлов фабрики",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "aliasSub(sortByMaxima(aliasSub(aliasByTags(seriesByTag('aci=${fabric:regex}', 'node=${node:regex}', 'name=aci_interface_qos_rx_admit_bytes_total.value_rate', 'class=~${class:regex}'), 'interface', 'class'), '\\.', ' ')), '^', 'RX - ')"
    },
    {
     "target": "aliasSub(sortByMaxima(aliasSub(aliasByTags(scale(seriesByTag('aci=${fabric:regex}', 'node=${node:regex}', 'name=aci_interface_qos_tx_admit_bytes_total.value_rate', 'class=~${class:regex}'), -1, 0), 'interface', 'class'), '\\.', ' ')), '^', 'TX - ')"
    }
   ]
  },
  {
   "title": "Drop pps per QoS class",
   "type": "timeseries",
   "description": "Количество отброшенных входящих/исходящих пакетов каждого класса на интерфейсах узлов фабрики",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "target": "aliasSub(sortByMaxima(aliasSub(aliasByTags(seriesByTag('aci=${fabric:regex}', 'node=${node:regex}', 'name=aci_interface_qos_rx_drop_pps_total.value_rate', 'class=~${class:regex}'), 'interface', 'class'), '\\.', ' ')), '^', 'RX - ')"
    },
    {
     "target": "aliasSub(sortByMaxima(aliasSub(aliasByTags(scale(seriesByTag('aci=${fabric:regex}', 'node=${node:regex}', 'name=aci_interface_qos_tx_drop_pps_total.value_rate', 'class=~${class:regex}'), -1, 0), 'interface', 'class'), '\\.', ' ')), '^', 'TX - ')"
    }
   ]
  },
  {
   "title": "Drop bytes per QoS class",
   "type": "timeseries",
   "description": "Количество отброшенных входящих/исходящих байт каждого класса на интерфейсах узлов фабрики",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "aliasSub(sortByMaxima(aliasSub(aliasByTags(seriesByTag('aci=${fabric:regex}', 'node=${node:regex}', 'name=aci_interface_qos_rx_drop_bytes_total.value_rate', 'class=~${class:regex}'), 'interface', 'class'), '\\.', ' ')), '^', 'RX - ')"
    },
    {
     "target": "aliasSub(sortByMaxima(aliasSub(aliasByTags(scale(seriesByTag('aci=${fabric:regex}', 'node=${node:regex}', 'name=aci_interface_qos_tx_drop_bytes_total.value_rate', 'class=~${class:regex}'), -1, 0), 'interface', 'class'), '\\.', ' ')), '^', 'TX - ')"
    }
   ]
  }
 ]
}