{
 "title": "Сетевое оборудование: Авторизация доступа к управлению устройствами",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "auth",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "tag_values(host, servertype=dts-mgmt-auth)"
   }
  ]
 },
 "panels": [
  {
   "title": "Load Average 5",
   "type": "gauge",
   "description": "Load Average за 5 минут",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$server', 'name=system.system.load5')"
    }
   ]
  },
  {
   "title": "Состояние сервисов",
   "type": "agenty-flowcharting-panel",
   "description": "Общая схема системы",
   "gridPos": { "h": 15, "w": 12, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$server', 'name=systemd.service.state'), '_name', 'host')"
    },
    {
     "target": "aliasByTags(seriesByTag('host=$server', 'name=auth.test.status'), 'proto', 'host')"
    }
   ]
  },
  {
   "title": "Статистика сообщений авторизации",
   "type": "graph",
   "description": "Количество сообщений авторизации (в системе логирования",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=auth_events_delta', 'agent=$server'), 'Auth events per 10 min')"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "description": "Утилизация CPU сервера",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$server', 'name=system.cpu.usage_active', 'cpu=cpu-total')"
    }
   ]
  },
  {
   "title": "Статистика сообщений аккаунтинга",
   "type": "graph",
   "description": "Количество сообщений аккантинга (в системе логирования)",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=acct_events_delta', 'agent=$server'), 'Auth events per 10 min')"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "description": "Утилизация RAM сервера",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$server', 'name=system.mem.used_percent')"
    }
   ]
  },
  {
   "title": "Инциденты",
   "type": "bosun-incident-list",
   "description": "Список инцидентов по серверам системы",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 15 },
   "targets": [
    { "target": "Bosun Query" }
   ]
  },
  {
   "title": "Disk / used",
   "type": "gauge",
   "description": "Занятость дисковых разделов",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$server', 'name=system.disk.used_percent', 'path=-')"
    }
   ]
  }
 ]
}