{
 "title": "Сетевое оборудование: BGP peers",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "internet",
  "network",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "tag_values(device, device=~(dts-r[12]-(border|ea1-x5)|dts-rr1|dts-fw4-ea1)$)"
   },
   {
    "name": "peer",
    "query": "tag_values(_name, device=$device)"
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "description": "Состояние BGP-сессии с пиром",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('name=bgp.peer.state', 'device=$device', '_name=$peer'), 'State')"
    }
   ]
  },
  {
   "title": "State",
   "type": "graph",
   "description": "График изменения состояния BGP-сессии",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=bgp.peer.state', 'device=$device', '_name=$peer'), 'State: 0 - down, 1 - up, 2 - admin down')"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Время непрерывной работы BGP-сессии",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('name=bgp.peer.uptime', 'device=$device', '_name=$peer'), 'Uptime')"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "description": "График изменения uptime сессии",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=bgp.peer.uptime', 'device=$device', '_name=$peer'), 'Uptime')"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "description": "ОК означание, что пир отвечает на ICMP ping",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('name=isp.ping', '_name=$peer'), 'Ping')"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "description": "График наличия ответов на пинг пиром",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=isp.ping', '_name=$peer'), 'Ping: 1 - OK, 2 - unavail')"
    }
   ]
  }
 ]
}