{
 "title": "Сетевое оборудование: Качество связующих каналов связи",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "telegraf",
  "gnom"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "host", "query": "tag_values(host, name=~ping.*)" },
   {
    "name": "Interface",
    "query": "tag_values(interface, name=~ping.*, host=$host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Средние значения",
   "type": "table",
   "description": "Средние значения показателей качество до различных целей за выбранный период",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "seriesByTag('host=~${host:regex}', 'name=~ping.*', 'interface=$Interface')"
    }
   ]
  },
  {
   "title": "RTT",
   "type": "timeseries",
   "description": "График изменения задержки до различных целей",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~${host:regex}', 'name=ping.rtt', 'interface=$Interface'), 'url')"
    },
    {
     "target": "alias(constantLine(150), 'threshold', false)"
    }
   ]
  },
  {
   "title": "Packet loss",
   "type": "timeseries",
   "description": "График потерь пакетов до различных целей",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~${host:regex}', 'name=~ping.p_lost', 'interface=$Interface'), 'url')"
    },
    {
     "target": "alias(constantLine(100), 'threshold', false)"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "description": "График изменения джиттера до различных целей",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~${host:regex}', 'name=ping.jitter', 'interface=$Interface'), 'url')"
    },
    {
     "target": "alias(constantLine(25), 'threshold', false)"
    }
   ]
  }
 ]
}