{
 "title": "Сервер: отличие системного времени (chrony)",
 "description": "Ответственный: Митрофанов А.Н. (АЦОД)",
 "tags": [
  "telegraf",
  "time",
  "system"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "server",
    "query": "tag_values(host,name=system.chrony.frequency)"
   }
  ]
 },
 "panels": [
  {
   "title": "Frequency",
   "type": "graph",
   "description": "Частота, на которой часы системы будут работать неправильно, если хронограф не проведет коррекцию",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.chrony.frequency', 'contur=~${contur:regex}', 'host=$server'), 'host')"
    }
   ]
  },
  {
   "title": "System time",
   "type": "graph",
   "description": "Задержка системных часов от синхронизированного сервера",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.chrony.system_time', 'contur=~${contur:regex}', 'host=$server'), 'host')"
    }
   ]
  },
  {
   "title": "Last offset",
   "type": "graph",
   "description": "Расчетное смещение последнего обновления часов",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.chrony.last_offset', 'contur=~${contur:regex}', 'host=$server'), 'host')"
    }
   ]
  },
  {
   "title": "RMS offset",
   "type": "graph",
   "description": "Долгосрочное среднее арифметическое значения смещения",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.chrony.rms_offset', 'contur=~${contur:regex}', 'host=$server'), 'host')"
    }
   ]
  },
  {
   "title": "Root delay",
   "type": "graph",
   "description": "Суммарная задержка сетевого пути к опорному серверу, с которым синхронизируется компьютер",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.chrony.root_delay', 'contur=~${contur:regex}', 'host=$server'), 'host')"
    }
   ]
  },
  {
   "title": "Root dispersion",
   "type": "graph",
   "description": "Дисперсия, накопленная всеми узлами по пути до сервера stratum-1",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.chrony.root_dispersion', 'contur=~${contur:regex}', 'host=$server'), 'host')"
    }
   ]
  }
 ]
}