{
 "title": "Сетевое оборудование: ACI Tenant",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "aci",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "fabric", "query": "tag_values(aci)" }
  ]
 },
 "panels": [
  {
   "title": "Health score",
   "type": "table",
   "description": "Текущее значение показателей здоровья всех тенантов на фабрике",
   "gridPos": { "h": 22, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "sortByMinima(seriesByTag('name=aci_tenant_health', 'aci=$fabric', 'tenant!='))"
    }
   ]
  },
  {
   "title": "Использование квот",
   "type": "table",
   "description": "# Триггеры относительно уровня квот \n\n| Уровень | Порог |\n|---------|-------|\n| Warn    | 65%   |\n| Crit    | 85%   |",
   "gridPos": { "h": 22, "w": 11, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "seriesByTag('name=aci_tenant_res', 'aci=$fabric')"
    },
    {
     "target": "seriesByTag('name=aci_tenant_quote', 'aci=$fabric')"
    }
   ]
  },
  {
   "title": "Использование лимитов",
   "type": "table",
   "description": "# Ограничения на максимальное количество объектов в тенанте\n\n| Ресурс | Warn | Crit |\n|--------|------|------|\n| EPG    | 400  | 450  |\n| VRF    | 4    | 5    |\n| Subnet | 200  | 250  |",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=aci_tenant_res', 'aci=$fabric', 'type=~(fvAEPg|fvCtx|fvSubnet)'), 'type')"
    }
   ]
  },
  {
   "title": "Использование ExtEPG на L3Out",
   "type": "table",
   "description": "# Ограничения на максимальное количество объектов в l3out\n\n| Ресурс | Warn | Crit |\n|--------|------|------|\n| ExtEPG    | 187  | 225  |",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "seriesByTag('name=aci_l3out_ext_epgs', 'aci=$fabric', 'tenant!=')"
    }
   ]
  }
 ]
}