{
 "title": "Сетевое оборудование: Авторизация пользователей к сети (dot1x)",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "auth",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Состояние",
   "type": "agenty-flowcharting-panel",
   "description": "Общая схема сервиса",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~.*dot1x.*', 'name=systemd.service.state'), '_name', 'host')"
    },
    {
     "target": "aliasByTags(seriesByTag('host=~.*dot1x.*', 'name=auth.test.status'), 1, 'host')"
    }
   ]
  },
  {
   "title": "Access Requests",
   "type": "timeseries",
   "description": "Распределение ответов на запросы авторизации",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(groupByTags(perSecond(seriesByTag('host=~.*dot1x.*', 'name=~freeradius.freeradius_total_access_*')), 'sum', 'name'), 'name'), 'freeradius.freeradius_total_access_', '')"
    }
   ]
  },
  {
   "title": "Auth Requests",
   "type": "timeseries",
   "description": "Распределение результатов обработки запросов авторизации",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByMetric(groupByTags(perSecond(seriesByTag('host=~.*dot1x.*', 'name=~freeradius.freeradius_total_auth*')), 'sum', 'name')), 'freeradius_total_auth_', ''), '_', ' ')"
    }
   ]
  },
  {
   "title": "Unknown clients",
   "type": "timeseries",
   "description": "Подключения к RADIUS-серверам от неизвестных клиентов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(aliasByMetric(groupByTags(nonNegativeDerivative(seriesByTag('host=~.*dot1x.*', 'name=~freeradius.unknown_clients')), 'sum', 'name')), '_', ' ')"
    }
   ]
  }
 ]
}