{
 "title": "Сетевое оборудование: FreeRadius",
 "description": "https://online.sbis.ru/opendoc.html?guid=c406044d-6692-44e1-8985-4376a4f6e1c2 Ответственный: Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "radius"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "tag_values(host,name=~freeradius.*)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('name=freeradius.freeradius_up', 'host=~${host:regex}'), 'Status')"
    }
   ]
  },
  {
   "title": "Access stats",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~freeradius.freeradius_total_access', 'host=~${host:regex}')), 1), 'freeradius_total_access_', '')"
    }
   ]
  },
  {
   "title": "Auth stats",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~freeradius.freeradius_total_auth', 'host=~${host:regex}')), 1), 'freeradius_total_auth_', '')"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "diffSeriesLists(timeFunction('', 60), #A)",
     "targetFull": "diffSeriesLists(timeFunction('', 60), alias(seriesByTag('name=freeradius.freeradius_start_time', 'host=~${host:regex}'), 'Status'))"
    }
   ]
  },
  {
   "title": "Acct stats",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~freeradius.freeradius_total_acct', 'host=~${host:regex}')), 1), 'freeradius_total_acct_', '')"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~freeradius.freeradius_queue_len', 'host=~${host:regex}')), 1), 'freeradius_queue_len_', '')"
    }
   ]
  }
 ]
}