{
 "title": "Сервер: основные системные метрики",
 "description": "Ответственный: Нет ответственного",
 "tags": [
  "telegraf",
  "system"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   { "name": "servertype", "query": "tag_values(servertype)" },
   {
    "name": "hostname",
    "label": "Host",
    "query": "tag_values(host,contur=$contur,servertype=~${servertype:regex})"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=system.system.uptime', 'contur=~${contur:regex}', 'host=$hostname')"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=system.mem.total', 'contur=~${contur:regex}', 'host=$hostname')"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('name=system.cpu.usage_active', 'cpu=cpu-total', 'contur=~${contur:regex}', 'host=$hostname'), 'CPU active')"
    },
    {
     "target": "alias(seriesByTag('name=system.mem.used_percent', 'contur=~${contur:regex}', 'host=$hostname'), 'Memory used')"
    },
    {
     "target": "alias(seriesByTag('name=system.swap.used_percent', 'host=$hostname'), 'Swap used')"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic(EXT4/XFS)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=system.disk.used_percent', 'host=$hostname'), 'path'), '-', '/')"
    }
   ]
  },
  {
   "title": "Forks/Context switches(right)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(seriesByTag('name=system.kernel.context_switches', 'host=$hostname')), 'Context switches')"
    },
    {
     "target": "alias(perSecond(seriesByTag('name=system.kernel.processes_forked', 'host=$hostname')), 'Forks')"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=system.system.n_cpus', 'contur=${contur:regex}', 'host=$hostname')"
    }
   ]
  },
  {
   "title": "CPU IOwait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "seriesByTag('name=system.cpu.usage_iowait', 'cpu=cpu-total', 'contur=~${contur:regex}', 'host=$hostname')"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~system.system.load*', 'host=$hostname'), 'name')"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "exclude(exclude(aliasByTags(seriesByTag('name=~system.cpu.*', 'cpu=cpu-total', 'host=$hostname'), 'name'), 'idle'), 'active')"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "Bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~system.net.bytes.*', 'host=$hostname', 'interface=~e(ns|np|t0)*')), 'interface', 'name'), 'perSecond\\(system.net.bytes_', '')"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('name=system.disk.used_percent', 'host=$hostname'), 'path'), '-', '/')"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "exclude(aliasByTags(seriesByTag('name=~system.mem.*', 'host=$hostname'), 'name'), 'vmalloc')"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "graph",
   "description": "The time spent on I/O in the natural time of each second. (wall-clock time)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~system.diskio.(read_time|write_time)', 'host=$hostname')), '_name', 'name')"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(perSecond(seriesByTag('name=~system.diskio.(reads|writes)', 'host=$hostname')), '_name', 'name'), 'perSecond\\(system.diskio\\.', '')"
    }
   ]
  },
  {
   "title": "Disk wait, ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "ms", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasSub(aliasByTags(divideSeriesLists(perSecond(seriesByTag('name=system.diskio.read_time', 'host=$hostname')), #B), '_name', 'name'), 'system.diskio.read_time', 'read_lag')",
     "targetFull": "aliasSub(aliasByTags(divideSeriesLists(perSecond(seriesByTag('name=system.diskio.read_time', 'host=$hostname')), perSecond(seriesByTag('name=system.diskio.reads', 'host=$hostname'))), '_name', 'name'), 'system.diskio.read_time', 'read_lag')"
    },
    {
     "target": "aliasSub(aliasByTags(divideSeriesLists(perSecond(seriesByTag('name=system.diskio.write_time', 'host=$hostname')), #D), '_name', 'name'), 'system.diskio.write_time', 'write_lag')"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "target": "aliasByTags(perSecond(seriesByTag('name=~system.diskio.(read|write)_bytes', 'host=$hostname')), '_name', 'name')"
    }
   ]
  },
  {
   "title": "CPU active by cores",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "exclude(exclude(exclude(aliasByTags(seriesByTag('name=~system.cpu.usage_active', 'host=$hostname'), 'cpu'), 'idle'), 'active'), 'cpu-total')"
    }
   ]
  }
 ]
}