{
 "title": "Сервер: память (memory) - linux",
 "description": "Ответственный: Нет ответственного",
 "tags": [
  "linux",
  "system",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.linux.memory.*"
   },
   { "name": "domain", "label": "Домен", "query": "*.tensor.ru" },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  { "title": "$server (usage, activity)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.{slab,proc,buffers,free,cached,used}.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.$domain.*.mem.ram.{slab,proc,buffers,free,cached,used}, -2)"
    }
   ]
  },
  {
   "title": "$server: activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.{mapped,free,buffers,slab,active*,inactive*,hugepages,ballooned}.$aggr, -2), '_5F', '-')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.memory.$server.$domain.*.mem.ram.{mapped,free,buffers,slab,active*,inactive*,hugepages,ballooned}.$aggr, -2), '_5F', '-')"
    }
   ]
  },
  { "title": "$server (dump, mapped)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "server" },
  {
   "title": "$server: dump",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.{dirty,writeback}.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.$domain.*.mem.ram.{dirty,writeback}.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: mapped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.{mapped,shmem,slab,sreclaimable,sunreclaim,kernelstack}.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.$domain.*.mem.ram.{mapped,shmem,slab,sreclaimable,sunreclaim,kernelstack}.$aggr, -2)"
    }
   ]
  },
  { "title": "$server (base, page)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }, "repeat": "server" },
  {
   "title": "$server: base",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.{proc,free}.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.$domain.*.mem.ram.{proc,free}.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: page",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.page.*.$aggr, -2)"
    }
   ]
  },
  { "title": "swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 }, "repeat": "server" },
  {
   "title": "$server: swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.swap.used.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memTotal.$server.*.mem.swap.total.raw, -2)"
    }
   ]
  },
  {
   "title": "hugepages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.hugepages.*.$aggr, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.$domain.*.mem.ram.hugepages.*.$aggr, -2)"
    }
   ]
  }
 ]
}