{
 "title": "Сетевое оборудование: Резервное копирование",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "backup",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "tag_values(host,host=dts-ncms-backuper.mgmt.tensor.ru)"
   },
   { "name": "tenant", "query": "dc : prod , office : corp" }
  ]
 },
 "panels": [
  {
   "title": "Load Average 5",
   "type": "gauge",
   "description": "LA за 5 минут сервера бэкапов",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=~${server:regex}', 'name=system.system.load5')"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "description": "Утилизация CPU сервера бэкапов",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=~${server:regex}', 'name=system.cpu.usage_active', 'cpu=cpu-total')"
    }
   ]
  },
  {
   "title": "Состояние демонов",
   "type": "stat",
   "description": "Состояние systemd-сервисов (кроме контейнеров)",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~${server:regex}', 'name=systemd.service.state'), '_name')"
    }
   ]
  },
  {
   "title": "Состояние контейнеров",
   "type": "table",
   "description": "Uptime контейнеров системы",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "seriesByTag('host=~${server:regex}', 'name=docker_container_status.uptime_ns')"
    },
    {
     "target": "seriesByTag('host=~${server:regex}', 'name=docker_container_status.container_status')"
    }
   ]
  },
  {
   "title": "Инциденты",
   "type": "bosun-grafana7-panel",
   "description": "Список инцидентов по сиетеме резервного копирования",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "requestFilter": "filter=filter=filter=filter=filter=filter=hasTag:tag1=dts-ncms-backuper* OR name:sys.*.device.network.backup.*"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "description": "Утилизация RAM сервера бэкапов",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=~${server:regex}', 'name=system.mem.used_percent')"
    }
   ]
  },
  {
   "title": "Disk / used",
   "type": "gauge",
   "description": "Утилизация диска сервера бэкапов",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=~${server:regex}', 'name=system.disk.used_percent', 'path=-')"
    }
   ]
  },
  {
   "title": "Устройства ЦОД/Corp",
   "type": "stat",
   "description": "Количество устройств ЦОД в системе бэкапов",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(countSeries(seriesByTag('host=~${server:regex}', 'name=backup.status', 'contur=prod')), 'dc')"
    },
    {
     "target": "alias(countSeries(seriesByTag('host=~${server:regex}', 'name=backup.status', 'contur=corp')), 'office')"
    }
   ]
  },
  {
   "title": "Web-интерфейс",
   "type": "stat",
   "description": "Состояние web-интерфейсов системы (отвечает или нет)",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~${server:regex}', 'name=http_response.status'), 'instance')"
    }
   ]
  },
  {
   "title": "Проблемы с бэкапами",
   "type": "table",
   "description": "Список устройств с проблемами по снятию бэкапов",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=backup.status', 'contur=~${tenant:regex}'), 'device')"
    }
   ]
  },
  {
   "title": "Конфигурация не сохранена",
   "type": "table",
   "description": "Список устройств с несохраненной конфигурацией",
   "gridPos": { "h": 11, "w": 8, "x": 7, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "target": "aliasByTags(seriesByTag('name=backup.save_status', 'contur=~${tenant:regex}'), 'device')",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Устройства с отключенным бэкапом",
   "type": "table",
   "description": "В netbox у девайса отключено резервное копирование",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "target": "maximumBelow(seriesByTag('name=backup.status', 'contur=~${tenant:regex}'), -2)"
    }
   ]
  }
 ]
}