{
 "title": "Сетевое оборудование: ACI Fabric",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "aci",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "fabric", "query": "tag_values(aci)" }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "graph",
   "description": "Показатель здоровья фабрики в целом",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=aci_fabric_health', 'aci=$fabric'), 'Fabric')"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "description": "Текущее значение показателя здоровья фабрики",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('name=aci_fabric_health', 'aci=$fabric'), 'Fabric')"
    }
   ]
  },
  {
   "title": "Статусы лицензий",
   "type": "table",
   "description": "Состояние всех лицензий на выбранной фабрике",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=aci_license_item.authStatus', 'aci=$fabric'), '_name')"
    }
   ]
  },
  {
   "title": "Общий статус лицензирования фабрики",
   "type": "stat",
   "description": "Статус процесса проверки лицензий, регистрации на сервере лицензий",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~aci_license_fabric.*', 'aci=$fabric'), 1)"
    }
   ]
  },
  {
   "title": "Использование логических ресурсов фабрики",
   "type": "table",
   "description": "Фактическое использование ресурсов фабрики в % от лимита.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "seriesByTag('aci=$fabric', 'name=~aci_resource_.*')"
    }
   ]
  },
  {
   "title": "Статус кластера",
   "type": "table",
   "description": "Состояние контроллеров фабрики с точки зрения остальных контроллеров этой же фабрики",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "seriesByTag('aci=$fabric', 'name=~aci_controller_health.*', 'observer!=')"
    }
   ]
  }
 ]
}