{
 "title": "Сетевое оборудование: WiFi Clients",
 "description": "Статистика по подключенным клиентам к wifi. Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "tag_values(device, name=clients.traffic.rx_signal)"
   },
   {
    "name": "ssid",
    "query": "tag_values(ssid, ssid!=Commandant, device=$device)"
   },
   {
    "name": "client",
    "query": "tag_values(mac, ssid=$ssid, device=$device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Время работы Клиента",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('device=$device', 'ssid=$ssid', 'name=clients.traffic.uptime', 'mac=$client'), 'name'), 'clients.traffic.rx_signal', 'Signal')"
    }
   ]
  },
  {
   "title": "Traffic per second",
   "type": "timeseries",
   "description": "Трафик Клиента ",
   "gridPos": { "h": 11, "w": 11, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(perSecond(seriesByTag('device=$device', 'ssid=$ssid', 'name=~.*bytes', 'mac=$client')), 'name'), 'clients.traffic.rx_bytes', 'Out'), 'clients.traffic.tx_bytes', 'In')"
    }
   ]
  },
  {
   "title": "Packets Traffic per second",
   "type": "timeseries",
   "description": "Трафик Клиента (пакеты)",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(perSecond(seriesByTag('device=$device', 'ssid=$ssid', 'name=~.*packets', 'mac=$client')), 'name'), 'clients.traffic.rx_packets', 'Out'), 'clients.traffic.tx_packets', 'In')"
    }
   ]
  },
  {
   "title": "Rx Signal",
   "type": "timeseries",
   "description": "Уровень сигнала Клиента",
   "gridPos": { "h": 11, "w": 22, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('device=$device', 'ssid=$ssid', 'name=clients.traffic.rx_signal', 'mac=$client'), 'name'), 'clients.traffic.rx_signal', 'Signal')"
    }
   ]
  }
 ]
}