{
 "title": "Сетевое оборудование: ACI Node",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "aci",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "fabric", "query": "tag_values(aci)" },
   { "name": "node", "query": "tag_values(node,aci=$fabric)" }
  ]
 },
 "panels": [
  {
   "title": "Вычислительные ресурсы: CPU, Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Утилизация CPU узла фабрики в %",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('node=$node', 'name=aci_node_cpu', 'aci=$fabric'), 'CPU util')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Утилизация RAM узла фабрики в %",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('node=$node', 'name=aci_node_mem', 'aci=$fabric'), 'RAM util')"
    }
   ]
  },
  {
   "title": "Окружение: БП, вентиляторы, температурные сенсоры",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Температура",
   "type": "table",
   "description": "Показания датчиков температуры узла фабрики.\nТакже отображены пороги по каждому датчику и состояние (превышен ли порог).",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "seriesByTag('name=aci_node_temp_current_celsius', 'aci=$fabric', 'node=$node')"
    },
    {
     "target": "seriesByTag('name=aci_node_temp_thresh_celsius', 'aci=$fabric', 'node=$node')"
    },
    {
     "target": "seriesByTag('name=aci_node_temp_current_celsius.operSt', 'aci=$fabric', 'node=$node')"
    }
   ]
  },
  {
   "title": "FAN",
   "type": "table",
   "description": "Состояние вентиляторов охлаждения узла фабрики",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "seriesByTag('name=aci_node_fan_status.operSt', 'aci=$fabric', 'node=$node')"
    }
   ]
  },
  {
   "title": "PSU",
   "type": "table",
   "description": "Состояние блоков питания узла фабрики",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "seriesByTag('name=aci_node_psu_status.operSt', 'aci=$fabric', 'node=$node')"
    }
   ]
  }
 ]
}