{
 "title": "Сервер: основные систмные метрики (sbis3mon)",
 "description": "Ответственный: Стрига П.И. (Эксплуатация)",
 "tags": [
  "sbis3mon",
  "system",
  "server"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   { "name": "server", "label": "Сервер", "query": "sbis3mon.prod.linux.cpuTime.*" }
  ]
 },
 "panels": [
  {
   "title": "ЦПУ",
   "type": "stat",
   "description": "Кол-во ядер в системе",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(aliasByNode(sbis3mon.$contur.linux.core.$server.*.cpu.core.*.busy.avg, -4, -3))"
    }
   ]
  },
  {
   "title": "Память",
   "type": "stat",
   "description": "Кол-во памяти в системе",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "alias(aggregate(sbis3mon.$contur.linux.memory.$server.*.mem.ram.{cached,used,free}.avg, 'sum'), 'total')"
    }
   ]
  },
  {
   "title": "Система",
   "type": "bargauge",
   "description": "Общее состояние системы",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "refCount": 1,
     "target": "alias(aggregate(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.*.avg, 'sum'), 'CPU active')"
    },
    {
     "target": "alias(asPercent(sbis3mon.$contur.linux.memory.$server.*.mem.ram.used.avg, #B), 'Memory used percent')",
     "targetFull": "alias(asPercent(sbis3mon.$contur.linux.memory.$server.*.mem.ram.used.avg, aggregate(sbis3mon.$contur.linux.memory.$server.*.mem.ram.{cached,used,free}.avg, 'sum')), 'Memory used percent')"
    }
   ]
  },
  {
   "title": "Диски",
   "type": "bargauge",
   "description": "Состояние дисков",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.partition.$server.*.partition.volume.*.prc.raw, -3), '_2F', '/')"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Трафик",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "target": "exclude(aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.*.*.bps.avg, 'lo'), -3, -4), 'ratio')"
    }
   ]
  },
  {
   "title": "Сетевой стек",
   "type": "graph",
   "description": "Состояния сетевых сокетов",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.netstat.$server.*.net.total.connection.*.avg, -2), '_5F', ' ')"
    }
   ]
  },
  {
   "title": "LA",
   "type": "graph",
   "description": "LA 1 5 15",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(sbis3mon.$contur.linux.la.$server.interval-28sec.cpu.la.m01.avg, 'max'), 'la1')"
    },
    {
     "target": "alias(consolidateBy(sbis3mon.$contur.linux.la.$server.interval-28sec.cpu.la.m05.avg, 'max'), 'la5')"
    },
    {
     "target": "alias(consolidateBy(sbis3mon.$contur.linux.la.$server.interval-28sec.cpu.la.m15.avg, 'max'), 'la15')"
    },
    {
     "target": "alias(countSeries(sbis3mon.$contur.linux.core.$server.interval-28sec.cpu.core.*.busy.avg), 'CPU')"
    }
   ]
  },
  {
   "title": "Диски занято",
   "type": "graph",
   "description": "Занятость дисков",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.partition.$server.*.partition.volume.*.prc.raw, -3), '_2F', '/')"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "description": "Количество операций чтения/записи в секунду",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.io.rps.*.*.avg, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.io.rps.merged.*.*.avg, -3, -2)"
    }
   ]
  },
  {
   "title": "CPU IOWAIT",
   "type": "graph",
   "description": "Ожидание ЦПУ",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.iowait.avg, -2))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Использование ЦПУ",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.cpuTime.$server.*.cpu.{user,system,iowait,nice,softirq,irq,guest,steal}.avg, -2)"
    }
   ]
  },
  {
   "title": "Memory - использование",
   "type": "graph",
   "description": "Использование памяти",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.*.avg, -2)"
    }
   ]
  },
  {
   "title": "Context switches",
   "type": "graph",
   "description": "Переключение контекста",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.la.$server.*.cpu.contextSwitch.avg, -2)"
    }
   ]
  },
  {
   "title": "Память",
   "type": "graph",
   "description": "Использование памяти",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.memory.$server.*.mem.ram.avail.avg, -2)"
    },
    {
     "target": "alias(consolidateBy(aliasByNode(nonNegativeDerivative(sbis3mon.$contur.linux.memory.$server.*.mem.ram.avail.avg), -2), 'max'), 'avlder')"
    },
    {
     "target": "alias(aggregate(sbis3mon.$contur.linux.memory.$server.*.mem.ram.{cached,used,free}.avg, 'sum'), 'total')"
    }
   ]
  },
  {
   "title": "Диск чтение/запись",
   "type": "graph",
   "description": "Чтение/запись на диск в байтах в секунду",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.io.bps.*.*.avg, -3, -2)"
    }
   ]
  },
  {
   "title": "Inode занято",
   "type": "graph",
   "description": "Занятость Inode в процентах",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.partition.$server.*.partition.inode.*.prc.raw, 7, 8)"
    }
   ]
  },
  {
   "title": "Network Traffic Packets",
   "type": "graph",
   "description": "Сетевой трафик в пакетах",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "exclude(exclude(sbis3mon.$contur.linux.iface.$server.*.net.*.*.pps.avg, 'lo'), 'ratio')"
    }
   ]
  },
  {
   "title": "Network Error(s)",
   "type": "graph",
   "description": "Сетевые ошибки",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "exclude(aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.*.*.error.avg, 'lo'), -3, -4), 'ratio')"
    }
   ]
  },
  {
   "title": "Network Traffic Bytes",
   "type": "graph",
   "description": "Сетевой трафик в байтах",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "exclude(aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.*.*.bps.avg, 'lo'), -3, -4), 'ratio')"
    }
   ]
  },
  {
   "title": "TCP stats",
   "type": "graph",
   "description": "Состояние ТСП стека",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.netstat.$server.*.net.total.connection.*.avg, -2), '_5F', ' ')"
    }
   ]
  },
  {
   "title": "Network TCP CLOSE-WAIT",
   "type": "graph",
   "description": "Не закрытые TCP соединения",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.netstat.$server.*.net.total.connection.*.avg, -2), '_5F', ' ')"
    }
   ]
  },
  {
   "title": "Network TCP SYN",
   "type": "graph",
   "description": "Очередь SYN пакетов",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.netstat.$server.*.net.total.connection.*.avg, -2), '_5F', ' ')"
    }
   ]
  }
 ]
}