{
 "title": "Сетевое оборудование: Служебные серверы Linux",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "tag_values(host, host=~.*(dts|pcidss).*)"
   },
   {
    "name": "interface",
    "query": "tag_values(interface, host=$server, interface=~(eth|bond|en|tun))"
   }
  ]
 },
 "panels": [
  {
   "title": "Load average",
   "type": "graph",
   "description": "LA за 1, 5 и 15 минут",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('host=$server', 'name=~system\\.system\\.load\\d+'), 2), true)"
    },
    {
     "target": "alias(seriesByTag('host=$server', 'name=system.system.n_cpus'), 'CPUs')"
    }
   ]
  },
  {
   "title": "Agent",
   "type": "stat",
   "description": "Успешность пинга сервера",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('host=$server', 'name=system.ping'), 'ping')"
    }
   ]
  },
  {
   "title": "Состояние сервисов",
   "type": "table",
   "description": "Состояние основных systemd-сервисов на сервере",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$server', 'name=systemd.service.state'), '_name')"
    },
    {
     "target": "aliasByTags(seriesByTag('host=$server', 'name=~procstat\\..*\\.running'), 1)"
    }
   ]
  },
  {
   "title": "Disk capacity used",
   "type": "timeseries",
   "description": "Утилизация места на дисковых разделах",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(sortByName(aliasByTags(seriesByTag('host=$server', 'name=system.disk.used_percent'), 'path'), false), '-', '/')"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Аптайм сервера в целом (ОС)",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('host=$server', 'name=system.system.uptime'), 'uptime')"
    }
   ]
  },
  {
   "title": "Disk I/O time utilization",
   "type": "graph",
   "description": "Утилизация дисков (по времени)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(scale(perSecond(seriesByTag('host=$server', 'name=system.diskio.io_time')), 0.1), '_name'))"
    }
   ]
  },
  {
   "title": "Network traffic rate",
   "type": "graph",
   "description": "Утилизация сетевого порта (в битах/сек)",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(scale(perSecond(seriesByTag('host=$server', 'name=~system\\.net\\.bytes_.*', 'interface=$interface')), 8), '.*(sent|recv).*', '\\1')"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Утилизация CPU выбранного сервера",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('host=$server', 'name=system.cpu.usage_active', 'cpu=cpu-total'), 'CPU')"
    }
   ]
  },
  {
   "title": "Инциденты",
   "type": "bosun-grafana7-panel",
   "description": "Список активных инцидентов по серверу",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "targets": [
    { "requestFilter": "filter=hasTag:tag1=$server" }
   ]
  },
  {
   "title": "Network packet rate",
   "type": "graph",
   "description": "Утилизация сетевого порта (в пакетах/сек)",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasSub(perSecond(seriesByTag('host=$server', 'name=~system\\.net\\.packets_.*', 'interface=$interface')), '.*(sent|recv).*', '\\1')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Утилизация RAM",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(seriesByTag('host=$server', 'name=system.mem.used_percent'), 'RAM ')"
    },
    {
     "target": "alias(seriesByTag('host=$server', 'name=system.swap.used_percent'), 'swap')"
    }
   ]
  }
 ]
}