{
 "title": "Сервер: сеть (net) - linux (суммарно)",
 "description": "Ответственный:  Сидоренко П.В. (Эксплуатация) ",
 "tags": [
  "linux",
  "system",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.linux.cpuTime.*"
   },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" },
   { "name": "domain", "query": "*.tensor.ru" }
  ]
 },
 "panels": [
  { "title": " connection, stat listen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "connection",
   "type": "graph",
   "description": "Сетевые подключения",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(groupByNode(aliasByNode(sbis3mon.$contur.linux.netstat.$server.*.net.total.connection.*.$aggr, -2), 0, 'sum'), '_5F', '')"
    }
   ]
  },
  {
   "title": "stat listen",
   "type": "graph",
   "description": "Статистика прослушивания",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(aliasByNode(sbis3mon.$contur.linux.netstatCounter.$server.*.net.stat.listen.*.raw, -2), 0, 'sum')"
    }
   ]
  },
  { "title": "bps, pps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "net bps",
   "type": "graph",
   "description": "Байты в секунду",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "groupByNodes(aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.*.*.bps.$aggr, 'lo'), -3, -4), 'sum', 0, 1)"
    }
   ]
  },
  {
   "title": "net pps",
   "type": "graph",
   "description": "Пакеты в секунду",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "groupByNodes(aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.*.*.pps.$aggr, 'lo'), -3, -4), 'sum', 0, 1)"
    }
   ]
  },
  { "title": "errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "$server: net (pps, error)",
   "type": "graph",
   "description": "Кол-во ошибок",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "groupByNodes(aliasByTags(exclude(sbis3mon.$contur.linux.iface.$server.*.net.*.*.error.$aggr, 'lo'), -3, -4), 'sum', 0, 1)"
    }
   ]
  }
 ]
}