{
 "title": "Сервер: обзор - windows",
 "description": "Ответственный: Нет ответственного",
 "tags": [
  "windows",
  "system",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "sbis3mon.*" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.windows.configuration.*"
   },
   { "name": "aggr", "label": "Аггрегация", "query": "min, avg, max" }
  ]
 },
 "panels": [
  { "title": "$server (cpu busy, la)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: cpu busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByNode(sbis3mon.$contur.windows.cpu.$server.*.cpu.busy.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: cpu la",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.la.$server.*.cpu.la.*.$aggr, -2)"
    },
    {
     "target": "alias(countSeries(sbis3mon.$contur.windows.cpu.$server.*.cpu.core.*.busy.avg), 'core-number')"
    }
   ]
  },
  { "title": "$server (cpu busy, process)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "server" },
  {
   "title": "$server: cpu busy per core",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.cpu.$server.*.cpu.core.*.busy.avg, -3)"
    }
   ]
  },
  {
   "title": "$server: process context switch",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.la.$server.*.cpu.contextSwitch.$aggr, -2)"
    }
   ]
  },
  { "title": "$server net (bps, pps)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "server" },
  {
   "title": "$server: net bps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.network.$server.*.net.{r,t}x.*.bps.$aggr, -3, -4)"
    }
   ]
  },
  {
   "title": "$server: net pps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.network.$server.*.net.{t,r}x.*.{pps,error}.$aggr, -3, -2)"
    }
   ]
  },
  { "title": "$server mem (ram, swap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "server" },
  {
   "title": "$server: mem ram",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.memory.$server.*.mem.ram.*.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: mem swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.memory.$server.*.mem.page.swap*.$aggr, -2)"
    }
   ]
  },
  { "title": "$server storage (bps, rps)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }, "repeat": "server" },
  {
   "title": "$server: bps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(summarize(sbis3mon.$contur.windows.$server.$subdomain.tensor.ru.*.aggr-$aggr.storage.*.io.bps.*, '$interval', '$aggr', false)), -4,  -1)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.storage.$server.*.storage.io.bps.*.*.$aggr, -3, -2)"
    }
   ]
  },
  {
   "title": "$server: rps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.storage.$server.*.storage.io.rps.*.{read,write}.$aggr, -3, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.storage.$server.*.storage.io.rps.splitted.00.$aggr, -2, -3)"
    }
   ]
  },
  {
   "title": "$server partition (used %, used)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "repeat": "server"
  },
  {
   "title": "$server: partition used %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.partition.$server.*.partition.volume.*.pct.raw, -3)"
    }
   ]
  },
  {
   "title": "$server: partition used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.partition.$server.*.partition.volume.*.used.raw, -3)"
    }
   ]
  },
  { "title": "time diff", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "time diff",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sbis3mon.$contur.windows.timeDiff.$server.*.time.diff)"
    }
   ]
  }
 ]
}