{
 "title": "Сервер: память (memory) - windows",
 "description": "Ответственный: Нет ответственного",
 "tags": [
  "windows",
  "system",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.windows.configuration.*"
   },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  { "title": "$server (usage, activity)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.memory.$server.*.mem.ram.*.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(sbis3mon.$contur.windows.$server.$subdomain.tensor.ru.*.aggr-$aggr.mem.ram.free, '$interval', '$aggr', false), -1)"
    },
    {
     "target": "aliasByNode(summarize(sbis3mon.$contur.windows.$server.$subdomain.tensor.ru.*.aggr-$aggr.mem.ram.used, '$interval', '$aggr', false), -1)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.memory.$server.*.mem.ram.{free,used}.$aggr, -2)"
    }
   ]
  },
  { "title": "$server (swap, page)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "server" },
  {
   "title": "swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.memory.$server.*.mem.page.*.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: page",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(sbis3mon.$contur.windows.$server.$subdomain.tensor.ru.*.aggr-$aggr.mem.page.scan, '$interval', '$aggr', false), -1)"
    },
    {
     "target": "aliasByNode(summarize(sbis3mon.$contur.windows.$server.$subdomain.tensor.ru.*.aggr-$aggr.mem.page.stall, '$interval', '$aggr', false), -1)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.memory.$server.*.mem.page.*.$aggr, -2)"
    }
   ]
  }
 ]
}