{
 "title": "Сетевое оборудование: Качество доступа в интернет из сегмента сети",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "telegraf",
  "gnom"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "tag_values(host,host=~.*gnom1.*,host!=~.*(voip|isp).*)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Packet loss",
   "type": "timeseries",
   "description": "Средние потери на ${host:regex}",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('contur=corp', 'name=ping.p_lost', 'host=~${host:regex}'), 'avg', 'host'), 'host')"
    },
    {
     "target": "alias(constantLine(100), 'threshold', false)"
    }
   ]
  },
  {
   "title": "Average RTT",
   "type": "timeseries",
   "description": "Средняя задержка на ${host:regex}",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('contur=corp', 'name=ping.rtt', 'host=~${host:regex}'), 'avg', 'host'), 'host')"
    },
    {
     "target": "alias(constantLine(150), 'threshold', false)"
    }
   ]
  },
  {
   "title": "DNS Check resolv",
   "type": "stat",
   "description": "Проверка работоспособности DNS-серверов",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=~${host:regex}', 'name=check_dns.status'), 'dns_server')"
    }
   ]
  },
  {
   "title": "Average Jitter",
   "type": "timeseries",
   "description": "Среднее значение Джиттера на ${host:regex}",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('contur=corp', 'name=ping.jitter', 'host=~${host:regex}'), 'avg', 'host'), 'host')"
    },
    {
     "target": "alias(constantLine(25), 'threshold', false)"
    }
   ]
  }
 ]
}