{
 "title": "Сетевое оборудование: Network Device System",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "network",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "tag_values(device, device=~.*dts.*)"
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "stat",
   "description": "Время пинга интерфейса управления сетевым устройством и uptime",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.ping.ploss', 'device=$device'), 'name')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=system.ping.rtt', 'device=$device'), 'name')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=system.uptime', 'device=$device'), 'name')"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "description": "График изменения задержки пинга",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=system.ping.ploss', 'device=$device'), 'Packet loss')"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "description": "График изменения задержки пинга",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('name=system.ping.rtt', 'device=$device'), 'RTT')"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "description": "График изменения uptime",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "timeticks" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=system.uptime', 'device=$device'), 'name')"
    }
   ]
  },
  {
   "title": "CPU 1min",
   "type": "gauge",
   "description": "Утилизация CPU сетевого устройства",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('device=$device', 'name=system.cpu.usage_1m'), 'CPU 1min')"
    },
    {
     "target": "avg(aliasByTags(seriesByTag('device=$device', 'name=system.cpu_core.usage_1m', 'core!='), 'core'))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Утилизация CPU сетевого устройства",
   "gridPos": { "h": 8, "w": 18, "x": 5, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('device=$device', 'name=system.cpu.usage_1m'), 'CPU 1min')"
    },
    {
     "target": "sortByMaxima(aliasByTags(seriesByTag('device=$device', 'name=system.cpu_core.usage_1m', 'core!='), 'core'))"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "description": "Утилизация  RAM сетевого устройства",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('device=$device', 'name=system.mem.util')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Утилизация RAM сетевого устройства",
   "gridPos": { "h": 8, "w": 18, "x": 5, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('device=$device', 'name=system.mem.util'), 'Used')"
    }
   ]
  }
 ]
}