{
 "title": "Сервер: сеть (net) - linux",
 "description": "Ответственный: Нет ответственного",
 "tags": [
  "linux",
  "system",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.linux.cpuTime.*"
   },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" },
   { "name": "domain", "query": "*.tensor.ru" }
  ]
 },
 "panels": [
  {
   "title": "$server (connection, stat listen)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "server"
  },
  {
   "title": "$server: connection",
   "type": "graph",
   "description": "Сетевые подключения",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.netstat.$server.*.net.total.connection.*.$aggr, -2), '_5F', ' ')"
    },
    {
     "target": "aliasSub(aliasByNode(sbis3mon.$contur.linux.netstat.$server.$domain.*.net.total.connection.*.$aggr, -2), '_5F', ' ')"
    }
   ]
  },
  {
   "title": "$server: stat listen",
   "type": "graph",
   "description": "Статистика прослушивания",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.netstatCounter.$server.*.net.stat.listen.*.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.linux.netstatCounter.$server.$domain.*.net.stat.listen.*.raw, -2)"
    }
   ]
  },
  { "title": "$server (bps, pps)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "server" },
  {
   "title": "$server: net bps",
   "type": "graph",
   "description": "Байты в секунду",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.*.*.bps.$aggr, 'lo'), -3, -4)"
    },
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.$domain.*.net.*.*.bps.$aggr, 'lo'), -3, -4)"
    }
   ]
  },
  {
   "title": "$server: net pps",
   "type": "graph",
   "description": "Пакеты в секунду",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.*.*.pps.$aggr, 'lo'), -3, -4)"
    }
   ]
  },
  { "title": "$server (errors)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "server" },
  {
   "title": "$server: net (pps, error)",
   "type": "graph",
   "description": "Кол-во ошибок",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.*.net.*.*.error.$aggr, 'lo'), -3, -4)"
    },
    {
     "target": "aliasByNode(exclude(sbis3mon.$contur.linux.iface.$server.$domain.*.net.*.*.error.$aggr, 'lo'), -3, -4)"
    }
   ]
  }
 ]
}