{
 "title": "Сетевое оборудование: Network Device Mikrotik",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "network",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "tag_values(device, model=mikrotik)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active connections",
   "type": "graph",
   "description": "Общее количество соединений",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('device=$device', 'name=system.conn.value'), 'connections')"
    },
    {
     "target": "aliasByTags(seriesByTag('device=$device', 'name=system.conn.limit'), 2)"
    }
   ]
  },
  {
   "title": "BGP peers",
   "type": "table",
   "description": "Состояние BGP-сессий (если есть)",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 0 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('device=$device', 'name=bgp.peer.state'), '_name'), false)"
    }
   ]
  },
  {
   "title": "BGP routes",
   "type": "table",
   "description": "Список маршрутов, полученных по BGP",
   "gridPos": { "h": 9, "w": 6, "x": 17, "y": 0 },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('device=$device', 'name=bgp.route.status'), 'net'), '-', '/')"
    }
   ]
  },
  {
   "title": "Flash disk utilization",
   "type": "graph",
   "description": "Утилизация флеш-диска в %",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('device=$device', 'name=system.disk.util'), 'Disk used')"
    }
   ]
  },
  {
   "title": "CPU core utilization",
   "type": "graph",
   "description": "Индивидуальная утилизация ядер CPU в %",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('device=$device', 'name=system.cpu.core_usage_1m'), 'core'), '.*', 'core\\0')"
    }
   ]
  }
 ]
}