{
 "title": "Сетевое оборудование: Internet Route Reflector",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "internet",
  "network",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "tag_values(host, service=bird)" },
   {
    "name": "peer",
    "query": "tag_values(_name, service=bird, host=$host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Session: State",
   "type": "table",
   "description": "Состояние BGP-сессий",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('host=$host', '_name=~${peer:regex}', 'name=bgp.peer.state'), '_name'), false)"
    }
   ]
  },
  {
   "title": "Prefixes: imported",
   "type": "graph",
   "description": "Количество импортированных префиксов.",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(seriesByTag('host=$host', '_name=~${peer:regex}', 'name=bgp.peer.prefix_imported'), '_name'))"
    }
   ]
  },
  {
   "title": "Session: Uptime",
   "type": "table",
   "description": "Время работы BGP-сессий",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "sortByMinima(currentAbove(aliasByTags(seriesByTag('host=$host', '_name=~${peer:regex}', 'name=bgp.peer.uptime'), '_name'), 0))"
    }
   ]
  },
  {
   "title": "Prefixes: preferred",
   "type": "graph",
   "description": "Количество выбранных (в таблицу маршрутизации) префиксов",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(seriesByTag('host=$host', '_name=~${peer:regex}', 'name=bgp.peer.prefix_preferred'), '_name'))"
    }
   ]
  }
 ]
}