{
 "title": "Сетевое оборудование: состояние трансиверов",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [ "dts" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "tag_values(device, name=~sfp.*)"
   },
   {
    "name": "interface",
    "query": "tag_values(interface, name=~sfp.*, device=$device)"
   },
   {
    "name": "lane",
    "query": "tag_values(lane, name=~sfp.*, device=$device, interface=$interface)"
   }
  ]
 },
 "panels": [
  {
   "title": "Receive power",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(seriesByTag('name=~sfp_rx_power.*', 'device=$device', 'interface=$interface', 'lane=$lane'), 1, 0))"
    }
   ]
  },
  {
   "title": "Transmit power",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~sfp_tx_power.*', 'device=$device', 'interface=$interface', 'lane=$lane'), 1, 0)"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~sfp_voltage.*', 'device=$device', 'interface=$interface', 'lane=$lane'), 1, 0)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~sfp_temperature.*', 'device=$device', 'interface=$interface', 'lane=$lane'), 1, 0)"
    }
   ]
  },
  {
   "title": "Current value",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "mamp" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=~sfp_current.*', 'device=$device', 'interface=$interface', 'lane=$lane'), 1, 0)"
    }
   ]
  }
 ]
}