{
 "title": "Сетевое оборудование: Interface stats",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "network",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "tag_values(device, device=~dts-.*)"
   },
   {
    "name": "interface",
    "query": "tag_values(interface, device=$device)"
   },
   {
    "name": "description",
    "query": "tag_values(description, device=$device, interface=$interface)"
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "description": "Поле description порта. Как правило, содержит устройство, подключенное к этому порту",
   "options": { "content": "# $description" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "description": "Утилизация порта в битах/сек",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(scale(seriesByTag('device=$device', 'interface=$interface', 'name=~interface\\.traffic\\.(in|out)_octets_rate'), 8), 2), '_octets', '')"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Состояние порта (текущее, желаемое), метка последнего изменения состояния пора",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('device=$device', 'interface=$interface', 'name=interface.status.admin'), 'name')"
    },
    {
     "target": "aliasByTags(seriesByTag('device=$device', 'interface=$interface', 'name=interface.status.oper'), 'name')"
    },
    {
     "target": "aliasByTags(seriesByTag('device=$device', 'interface=$interface', 'name=interface.status.last_change'), 'name')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=system.uptime', 'device=$device'), 'name')"
    }
   ]
  },
  {
   "title": "Packet rate",
   "type": "graph",
   "description": "Утилизация порта в пакетах/сек",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByTags(seriesByTag('device=$device', 'interface=$interface', 'name=~interface\\.traffic\\.(in|out)_(uni|multi|broad)cast_pkts_rate'), 2), '_', ' '), 'pkts', '')"
    }
   ]
  },
  {
   "title": "Operational status",
   "type": "timeseries",
   "description": "График изменения состояния порта",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "offset(scale(aliasByTags(seriesByTag('device=$device', 'interface=$interface', 'name=interface.status.oper'), 'name'), -1), 2)"
    }
   ]
  },
  {
   "title": "Out Queue Length",
   "type": "graph",
   "description": "Длина очереди на порту. Считается устаревшей и на некоторых устройствах может всегда показывать 0",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "packets" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('device=$device', 'interface=$interface', 'name=~interface.status.out_qlen'), 'Out Queue Length')"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "description": "Ошибки разных видов (в шт/сек, иногда в битах/сек)",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('device=$device', 'interface=$interface', 'name=~interface\\.errors\\..*_rate', 'interval=60s'), 2), '_', ' ')"
    },
    {
     "target": "aliasSub(aliasByTags(seriesByTag('device=$device', 'interface=$interface', 'name=~interface\\.errors\\..*_rate', 'interval=600s'), 2), '_', ' ')"
    }
   ]
  }
 ]
}