{
 "title": "Сетевое оборудование: ACI Interface",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "aci",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "fabric", "query": "tag_values(aci)" },
   {
    "name": "node",
    "query": "tag_values(node,aci=$fabric, interface!=)"
   },
   {
    "name": "interface",
    "query": "tag_values(interface,aci=$fabric, node=$node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Описание порта",
   "type": "stat",
   "description": "Значение поля description сетевого порта. Как правило, это имя и порт устройства с другой стороны кабеля",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('aci=$fabric', 'node=$node', 'interface=$interface', 'name=aci_interface_status.adminSt')"
    }
   ]
  },
  {
   "title": "Трафик",
   "type": "graph",
   "description": "Утилизация порта в байтах/сек",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(scale(seriesByTag('aci=$fabric', 'node=$node', 'interface=$interface', 'name=~.*bytes.*'), 8), '.*_(in|out)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Состояние",
   "type": "stat",
   "description": "Текущее (oper) и желаемое (admin) состояние порта",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('aci=$fabric', 'node=$node', 'interface=$interface', 'name=aci_interface_status.adminSt'), 'admin status')"
    },
    {
     "target": "alias(seriesByTag('aci=$fabric', 'node=$node', 'interface=$interface', 'name=aci_interface_status.operSt'), 'oper status')"
    }
   ]
  },
  {
   "title": "Пакеты",
   "type": "graph",
   "description": "Утилизация порта в пакетах/сек",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasSub(seriesByTag('aci=$fabric', 'node=$node', 'interface=$interface', 'name=~.*pkts.*'), '.*_(in|out)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Параметры мониторинга",
   "type": "stat",
   "description": "## Load\nЗа какой период считать загрузку порта (зависит от префикса **hl/xhl** в описании порта)\n- normal - 5m\n- high - 4h\n- extrahigh - 1d\n\n## Trigger\nБудут ли срабатывать триггеры (зависит от префикса **nt|lt** в описании порта)\n- yes\n- no\n- low",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('aci=$fabric', 'node=$node', 'interface=$interface', 'name=aci_interface_status.adminSt'), 'admin status')"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "description": "Линейная скорость порта",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(seriesByTag('aci=$fabric', 'node=$node', 'interface=$interface', 'name=aci_interface_status.speed'), 'oper status')"
    }
   ]
  },
  {
   "title": "Ошибки",
   "type": "graph",
   "description": "Ошибки разных видов (в шт/сек)",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "target": "aliasSub(seriesByTag('aci=$fabric', 'node=$node', 'interface=$interface', 'name=~aci_interface_(in|out)_(errors|discards|crc)_total.*'), '.*_(in|out)_(errors|discards|crc)_.*', '\\1 \\2')"
    }
   ]
  },
  {
   "title": "Текущее состояние порта",
   "type": "timeseries",
   "description": "График изменения состояния порта",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "alias(seriesByTag('aci=$fabric', 'node=$node', 'interface=$interface', 'name=aci_interface_status.operSt'), 'oper status')"
    }
   ]
  }
 ]
}