{
 "title": "Сетевое оборудование: Статистика по Raspberry Pi",
 "description": "Особые метрики для малинки. Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "tag_values(host,host=~.*rpi.*)" }
  ]
 },
 "panels": [
  {
   "title": "CPU temp",
   "type": "timeseries",
   "description": "Температура процессора Raspberry Pi 4",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=$host', 'name=system.cpu_temp'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "CPU utill",
   "type": "timeseries",
   "description": "Загруженность процессора Raspberry Pi 4",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=$host', 'name=system.cpu.usage_active', 'cpu=cpu-total'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  },
  {
   "title": "Overlay on /",
   "type": "timeseries",
   "description": "Overlayfs used on Raspberry Pi 4",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(seriesByTag('host=$host', 'name=system.disk.used_percent', 'fstype=overlay'), 'host'), '.unix.tensor.ru', '')"
    }
   ]
  }
 ]
}