{
 "title": "Сервер: хранилища (storage) - linux",
 "description": "Ответственный: Нет ответственного",
 "tags": [
  "linux",
  "system",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.linux.storage.*"
   },
   {
    "name": "storage",
    "query": "sbis3mon.$contur.linux.storage.$server.*.storage.queue.*"
   },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  { "title": "$server (busy, lag)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(consolidateBy(sbis3mon.$contur.linux.storage.$server.*.storage.busy.$storage.$aggr, '$aggr'), -2, -3, -1)"
    }
   ]
  },
  {
   "title": "$server: await lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(consolidateBy(aliasByNode(sbis3mon.$contur.linux.storage.$server.*.storage.lag.$storage.*_5Fawait.$aggr, -3, -2), '$aggr'), 'r_.*', 'read'), 'w_.*', 'write')"
    }
   ]
  },
  { "title": "$server (bps, ops)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "server" },
  {
   "title": "$server: bps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(consolidateBy(sbis3mon.$contur.linux.storage.$server.*.storage.io.bps.$storage.*.$aggr, '$aggr'), -3, -2)"
    }
   ]
  },
  {
   "title": "$server: ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(consolidateBy(sbis3mon.$contur.linux.storage.$server.*.storage.io.rps.$storage.*.$aggr, '$aggr'), -3, -2)"
    },
    {
     "target": "aliasByNode(consolidateBy(sbis3mon.$contur.linux.storage.$server.*.storage.io.rps.merged.$storage.*.$aggr, '$aggr'), -3, -2)"
    }
   ]
  }
 ]
}