{
 "title": "Сервер: процессор (cpu) - windows",
 "description": "Ответственный: Нет ответственного",
 "tags": [
  "system",
  "windows",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "prod" },
   {
    "name": "server",
    "label": "Имя сервера",
    "query": "sbis3mon.$contur.windows.configuration.*"
   },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  { "title": "$server (time, time %)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "$server: time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.cpu.$server.*.cpu.{user,system,irq}.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: time %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.cpu.$server.*.cpu.{user,system,irq}.raw, -2)"
    }
   ]
  },
  { "title": "$server (busy, la)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "server" },
  {
   "title": "$server: busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.cpu.$server.*.cpu.busy.raw, -2)"
    }
   ]
  },
  {
   "title": "$server: la",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.la.$server.*.cpu.la.*.$aggr, -2)"
    }
   ]
  },
  { "title": "$server (context, core avg)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "server" },
  {
   "title": "$server: context",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.la.$server.*.cpu.contextSwitch.$aggr, -2)"
    }
   ]
  },
  {
   "title": "$server: core avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.cpu.$server.*.cpu.core.*.busy.avg, -3)"
    }
   ]
  },
  { "title": "$server (core busy, core %)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "server" },
  {
   "title": "$server: core busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.cpu.$server.*.cpu.core.*.busy.raw, -3)"
    }
   ]
  },
  {
   "title": "$server: core %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.windows.cpu.$server.*.cpu.core.*.busy.pct.raw, -3)"
    }
   ]
  }
 ]
}