{
 "title": "Сетевое оборудование: Система логирования",
 "description": "Ответственный: Кралин А.Е. (СПД)",
 "tags": [
  "dts",
  "log",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "tag_values(host, servertype=dts-log)"
   }
  ]
 },
 "panels": [
  {
   "title": "Load Average 5",
   "type": "gauge",
   "description": "LA за 5 минут",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$server', 'name=system.system.load5')"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "description": "Утилизация CPU выбранного сервера",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$server', 'name=system.cpu.usage_active', 'cpu=cpu-total')"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "description": "Утилизация RAM выбранного сервера",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$server', 'name=system.mem.used_percent')"
    }
   ]
  },
  {
   "title": "Состояние сервисов",
   "type": "agenty-flowcharting-panel",
   "description": "Общая схема системы и состояние ее сервисов",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$server', 'name=systemd.service.state'), '_name', 'host')"
    },
    {
     "target": "aliasByTags(seriesByTag('host=$server', 'name=syslog_test'), 'name')"
    },
    {
     "target": "aliasByTags(seriesByTag('host=$server', 'name=grafana_http_probe.status'), 'name')"
    }
   ]
  },
  {
   "title": "Disk / used",
   "type": "gauge",
   "description": "Занятость корневого раздела",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$server', 'name=system.disk.used_percent', 'path=-')"
    }
   ]
  },
  {
   "title": "Disk /var/lib/elasticsearch used",
   "type": "gauge",
   "description": "Занятость раздела с логами",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "seriesByTag('host=$server', 'name=system.disk.used_percent', 'path=-var-lib-elasticsearch')"
    }
   ]
  },
  {
   "title": "Инциденты",
   "type": "bosun-grafana7-panel",
   "description": "Список активных инцидентов по серверу логирования",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "requestFilter": "filter=hasTag:tag1=dts-log* OR hasTag:name=spd.log.*"
    }
   ]
  },
  {
   "title": "Статистика сообщений",
   "type": "graph",
   "description": "Статистика поступления сообщений Syslog",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('host=$server', 'name=syslog_msgs_delta'), 'Syslog messages per 10 min')"
    }
   ]
  }
 ]
}