{
 "title": "СРК Bareos PostgreSQL",
 "description": "Ответственный:  Гусев М.К. (АЦОД)",
 "tags": [
  "Bareos ",
  "telegraf",
  "PostgreSQL",
  "service"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "Database",
    "query": "tag_values(database, name=status_code.backup, contur=$contur)"
   }
  ]
 },
 "panels": [
  {
   "title": "Статистика",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(aggregate(seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py'), 'count'), 'Всего')"
    },
    {
     "target": "alias(aggregate(removeAboveValue(removeBelowValue(seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py'), 11), 11), 'count'), 'Подготовка в процессе')"
    },
    {
     "target": "alias(aggregate(removeAboveValue(removeBelowValue(seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py'), 13), 13), 'count'), 'Подготовка завершена успешно')"
    },
    {
     "target": "alias(aggregate(removeAboveValue(removeBelowValue(seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py'), 12), 12), 'count'), 'Подготовка завершена с ошибкой')"
    },
    {
     "target": "alias(aggregate(removeAboveValue(removeBelowValue(seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py'), 21), 21), 'count'), 'Бекап в процессе')"
    },
    {
     "target": "alias(aggregate(removeAboveValue(removeBelowValue(seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py'), 23), 23), 'count'), 'Бекап завершен успешно')"
    },
    {
     "target": "alias(aggregate(removeAboveValue(removeBelowValue(seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py'), 22), 22), 'count'), 'Бекап завершен с ошибкой')"
    },
    {
     "target": "alias(aggregate(removeAboveValue(removeBelowValue(seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py'), 31), 31), 'count'), 'Валидация в процессе')"
    },
    {
     "target": "alias(aggregate(removeBelowValue(seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py'), 33), 'count'), 'Валидация завершена успешно')"
    },
    {
     "target": "alias(aggregate(removeAboveValue(removeBelowValue(seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py'), 32), 32), 'count'), 'Валидация завершена с ошибкой')"
    }
   ]
  },
  {
   "title": "Подготовка",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "В процессе",
     "type": "table",
     "description": "11",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "targets": [
      {
       "target": "seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py')"
      }
     ]
    },
    {
     "title": "Завершено успешно",
     "type": "table",
     "description": "13",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "targets": [
      {
       "target": "seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py')"
      }
     ]
    },
    {
     "title": "Завершено с ошибкой",
     "type": "table",
     "description": "12",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "targets": [
      {
       "target": "seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py')"
      }
     ]
    }
   ]
  },
  {
   "title": "Бекап",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "В процессе",
     "type": "table",
     "description": "21",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "targets": [
      {
       "target": "seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py')"
      }
     ]
    },
    {
     "title": "Завершено успешно",
     "type": "table",
     "description": "23",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "targets": [
      {
       "target": "seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py')"
      }
     ]
    },
    {
     "title": "Завершено с ошибкой",
     "type": "table",
     "description": "22",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "targets": [
      {
       "target": "seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py')"
      }
     ]
    }
   ]
  },
  {
   "title": "Валидация",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "В процессе",
     "type": "table",
     "description": "31",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "target": "seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py')"
      }
     ]
    },
    {
     "title": "Завершено успешно",
     "type": "table",
     "description": "33",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "target": "seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py')"
      }
     ]
    },
    {
     "title": "Завершено с ошибкой",
     "type": "table",
     "description": "32",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "target": "seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py')"
      }
     ]
    }
   ]
  },
  { "title": "График", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Database: $Database",
   "type": "graph",
   "description": "11 - Подготовка бекапа в процессе\n\n12 - Подготовка бекапа завершилась с ошибкой\n\n13 - Подготовка бекапа завершилась успешно\n\n21 - Задание на бекап в процессе\n\n22 - Задание на бекап завершилось с ошибкой\n\n23 - Задание на бекап завершилось успешно\n\n31 - Валидация бекапа в процессе\n\n32 - Валидация бекапа завершилась с ошибкой\n\n33 - Валидация бекапа завершилась успешно",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Статус" }
   ],
   "targets": [
    {
     "target": "sortByMinima(aliasByTags(seriesByTag('name=status_code.backup', 'servertype=bareos', 'database=~${Database:regex}', 'script=backup_worker_py'), 'database'))"
    }
   ]
  },
  {
   "title": "Расшифровка статусов",
   "type": "text",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 8 },
   "options": {
    "content": "11 - Подготовка бекапа в процессе  \n12 - Подготовка бекапа завершилась с ошибкой  \n13 - Подготовка бекапа завершилась успешно  \n\n21 - Задание на бекап в процессе  \n22 - Задание на бекап завершилось с ошибкой  \n23 - Задание на бекап завершилось успешно  \n\n31 - Валидация бекапа в процессе  \n32 - Валидация бекапа завершилась с ошибкой  \n33 - Валидация бекапа завершилась успешно  "
   },
   "targets": [
    {}
   ]
  }
 ]
}