{
 "title": "СХД: MPIO Devices",
 "description": "Ответственный: Лошкарев Д.Г. (АЦОД)",
 "tags": [
  "system",
  "storage",
  "sbis3mon-kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "query": "sbis3mon.*" }
  ]
 },
 "panels": [
  {
   "title": "Normal state counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "maximumAbove(countSeries(sbis3mon.$contur.linux.multipath.*.*.multipath.paths.*.ready.raw), 0)"
    }
   ]
  },
  {
   "title": "Vcenter multipath errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(maximumBelow(asPercent(sbis3mon.$contur.vcenter.esxi.vc-cloud.vcenter.*.esxi.*.corp.tensor.ru.paths.raw, #A), 1), 8)",
     "targetFull": "aliasByTags(maximumBelow(asPercent(sbis3mon.$contur.vcenter.esxi.vc-cloud.vcenter.*.esxi.*.corp.tensor.ru.paths.raw, sbis3mon.$contur.vcenter.esxi.vc-cloud.vcenter.*.esxi.*.corp.tensor.ru.maxpaths.raw), 1), 8)"
    }
   ]
  },
  {
   "title": "Shaky devices",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maximumAbove(sbis3mon.$contur.linux.multipath.*.*.multipath.paths.*.shaky.raw, 0)"
    }
   ]
  },
  {
   "title": "Faulty devices",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maximumAbove(sbis3mon.$contur.linux.multipath.*.*.multipath.paths.*.faulty.raw, 0)"
    }
   ]
  }
 ]
}