{
 "title": "СХД: Xtremio:  статус кластера",
 "description": "Ответственный: Лошкарев Д.Г. (АЦОД)",
 "tags": [
  "xtremio",
  "storage",
  "sbis3mon-kafka",
  "system"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "contur", "query": "sbis3mon.*" },
   {
    "name": "system",
    "query": "sbis3mon.$contur.xtremio.cluster.*"
   },
   {
    "name": "cluster",
    "query": "sbis3mon.$contur.xtremio.alert.$system.*.cluster.alert.count.*"
   },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  { "title": "Cluster: $cluster (stats)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "Alert: critical",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "sbis3mon.$contur.xtremio.alert.$system.*.cluster.alert.count.$cluster.critical.raw"
    }
   ]
  },
  {
   "title": "Alert: major",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "sbis3mon.$contur.xtremio.alert.$system.*.cluster.alert.count.$cluster.major.raw"
    }
   ]
  },
  {
   "title": "Alert: minor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "sbis3mon.$contur.xtremio.alert.$system.*.cluster.alert.count.$cluster.minor.raw"
    }
   ]
  },
  {
   "title": "Alert: information",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "sbis3mon.$contur.xtremio.alert.$system.*.cluster.alert.count.$cluster.information.raw"
    }
   ]
  },
  {
   "title": "Space used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "sbis3mon.$contur.xtremio.cluster.$system.*.cluster.space.used.$cluster.raw"
    }
   ]
  },
  {
   "title": "Cluster: $cluster IO (bps, rps)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "cluster"
  },
  {
   "title": "Bps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.xtremio.cluster.$system.*.cluster.io.bps.$cluster.{read,write}.raw, -2)"
    },
    {
     "target": "alias(sbis3mon.$contur.xtremio.cluster.$system.*.cluster.io.bps.$cluster.raw, 'IO')"
    }
   ]
  },
  {
   "title": "Rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.xtremio.cluster.$system.*.cluster.io.bps.$cluster.{read,write}.raw, -2)"
    },
    {
     "target": "alias(sbis3mon.$contur.xtremio.cluster.$system.*.cluster.io.bps.$cluster.raw, 'IO')"
    }
   ]
  },
  { "title": "Cluster: $cluster (latency)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "cluster" },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.xtremio.cluster.$system.*.cluster.io.latency.$cluster.{read,write}.raw, -2)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.xtremio.cluster.$system.*.cluster.io.latency.$cluster.avg.raw, -5)"
    }
   ]
  }
 ]
}