{
 "title": "СХД: IBM XIV: тома",
 "description": "Ответственный: Лошкарев Д.Г. (АЦОД)",
 "tags": [
  "telegraf",
  "xiv",
  "snmp",
  "storage",
  "system"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "storage",
    "query": "tag_values(agent_host,name=xiv.cluster.FreeSpaceHard)"
   },
   {
    "name": "volume",
    "label": "LUN",
    "query": "tag_values(xivStatisticsVolumeName,agent_host=~$storage)"
   }
  ]
 },
 "panels": [
  {
   "title": "VolumeIOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=xiv.volume.VolumeIOPS', 'agent_host=$storage', 'xivStatisticsVolumeName=~${volume:regex}'), 'agent_host', 'xivStatisticsVolumeName'), 0, -1)"
    }
   ]
  },
  {
   "title": "VolumeLatency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=xiv.volume.VolumeLatency', 'agent_host=$storage', 'xivStatisticsVolumeName=~${volume:regex}'), 'agent_host', 'xivStatisticsVolumeName'), 0, -1)"
    }
   ]
  },
  {
   "title": "VolumeBW",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=xiv.volume.VolumeBW', 'agent_host=$storage', 'xivStatisticsVolumeName=~${volume:regex}'), 'agent_host', 'xivStatisticsVolumeName'), 0, -1)"
    }
   ]
  },
  {
   "title": "UtilizationHard",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=xiv.cluster.UtilizationHard', 'agent_host=$storage'), 'agent_host'), 0)"
    }
   ]
  }
 ]
}