{
 "title": "СХД: Xtremio: тома",
 "description": "Ответственный: Лошкарев Д.Г. (АЦОД)",
 "tags": [
  "xtremio",
  "storage",
  "sbis3mon-kafka",
  "system"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "system",
    "query": "sbis3mon.$contur.xtremio.volume.*"
   },
   {
    "name": "volume",
    "query": "sbis3mon.$contur.xtremio.volume.$system.*.volume.io.bps.*"
   }
  ]
 },
 "panels": [
  {
   "title": "IO bps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.xtremio.volume.$system.*.volume.io.bps.$volume.raw, -2, -4)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.xtremio.volume.$system.*.volume.io.bps.$volume.{read,write}.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "IO rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.xtremio.volume.$system.*.volume.io.rps.$volume.raw, -2, -4)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.xtremio.volume.$system.*.volume.io.rps.$volume.{read,write}.raw, -3, -2)"
    }
   ]
  },
  {
   "title": "IO latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.xtremio.volume.$system.*.volume.io.latency.$volume.avg.raw, -3, -5)"
    },
    {
     "target": "aliasByNode(sbis3mon.$contur.xtremio.volume.$system.*.volume.io.latency.$volume.{read,write}.raw, -3, -2)"
    }
   ]
  }
 ]
}