{
 "title": "СХД: Storwize: mdisk",
 "description": "Ответственный: Лошкарев Д.Г. (АЦОД)",
 "tags": [
  "storwize",
  "sbis3mon-kafka",
  "storage",
  "system"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "storage",
    "query": "sbis3mon.$contur.storwize.mdiskPool.*"
   },
   {
    "name": "mdisk",
    "query": "sbis3mon.$contur.storwize.mdiskPool.$storage.storwize.*.mdisk.io.bps.*"
   }
  ]
 },
 "panels": [
  { "title": "Volume: $mdisk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "mdisk" },
  {
   "title": "mdisk: $mdisk rps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.storwize.mdiskPool.$storage.storwize.*.mdisk.io.rps.$mdisk.*.raw, -2)"
    }
   ]
  },
  {
   "title": "mdisk: $mdisk bps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.storwize.mdiskPool.$storage.storwize.*.mdisk.io.bps.$mdisk.*.raw, -2)"
    }
   ]
  },
  {
   "title": "mdisk: $mdisk time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sbis3mon.$contur.storwize.mdiskPool.$storage.storwize.*.mdisk.io.time.$mdisk.*.raw, -2)"
    }
   ]
  }
 ]
}