{
 "title": "СХД: Xtremio: сводный",
 "description": "Ответственный: Лошкарев Д.Г. (АЦОД)",
 "tags": [
  "sbis3mon-kafka",
  "storage",
  "system",
  "xtremio"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "contur", "label": "Контур", "query": "sbis3mon.*" },
   {
    "name": "system",
    "query": "sbis3mon.$contur.xtremio.volume.*"
   },
   { "name": "xio", "query": "1,2" }
  ]
 },
 "panels": [
  {
   "title": "Задержки записи",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.xtremio.volume.$system.*.volume.io.latency.XIO{$xio}*.write.raw, 20), -3)"
    }
   ]
  },
  {
   "title": "Задержки чтения",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.xtremio.volume.$system.*.volume.io.latency.XIO{$xio}*.read.raw, 20), -3)"
    }
   ]
  },
  {
   "title": "Поток записи",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.xtremio.volume.$system.*.volume.io.bps.XIO{$xio}*.write.raw, 20), -3)"
    }
   ]
  },
  {
   "title": "Поток чтения",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.xtremio.volume.$system.*.volume.io.bps.XIO{$xio}*.read.raw, 20), -3)"
    }
   ]
  },
  {
   "title": "Операции записи",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.xtremio.volume.$system.*.volume.io.rps.XIO{$xio}*.write.raw, 20), -3)"
    }
   ]
  },
  {
   "title": "Операции чтения",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(sbis3mon.$contur.xtremio.volume.$system.*.volume.io.rps.XIO{$xio}*.read.raw, 20), -3)"
    }
   ]
  }
 ]
}