{
 "title": "СХД: HW Raid Controllers",
 "description": "Ответственный: Гломаздов А.Ю. (АЦОД)",
 "tags": [
  "storage",
  "system",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "tag_values(host,name=megaraid.healthy)"
   }
  ]
 },
 "panels": [
  {
   "title": "RAID Controller Status",
   "type": "stat",
   "description": "Состояние контролера",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('host=$host', 'name=megaraid.healthy'), 'controller')"
    }
   ]
  },
  {
   "title": "RAID Array Status",
   "type": "table",
   "description": "Состояние массивов",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=megaraid.vd_info')"
    }
   ]
  },
  { "title": "RAID Controller Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Panel Title",
   "type": "table",
   "description": "Общая информация о контролерах",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=~.*controller_info.*')"
    }
   ]
  },
  {
   "title": "General stats",
   "type": "table",
   "description": "Информация о батарейках",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=~.*battery.*|.*temp.*')"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "description": "Информация о массивах",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=megaraid.vd_info')"
    }
   ]
  },
  { "title": "Disk Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Controller 1",
   "type": "table",
   "description": "Информация о дисках",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=megaraid.pd_info', 'controller=1')"
    }
   ]
  },
  {
   "title": "Controller 0",
   "type": "table",
   "description": "Информация о дисках",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=megaraid.pd_info', 'controller=0')"
    },
    {}
   ]
  },
  {
   "title": "Disk Errors",
   "type": "table",
   "description": "Информация об ошибках на дисках",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "target": "seriesByTag('host=$host', 'name=~[.*errors.*|.*smart.*]')"
    }
   ]
  }
 ]
}