{
 "title": "СХД: Pure сводный",
 "description": "Ответственный: Лошкарев Д.Г. (АЦОД). Скрипт https://adm-git.tensor.ru/exp/monitoring-scripts/datastore/-/blob/master/scripts/ds_pure_monitoring.py",
 "tags": [
  "telegraf",
  "storage",
  "system",
  "pure"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "system",
    "query": "tag_values(source,contur=$contur,name=pure_rest_data)"
   }
  ]
 },
 "panels": [
  { "title": "Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Занято на $system",
   "type": "gauge",
   "description": "Отношение total_capacity к total_physical в процентах.\n\ntotal_physical - Занятое пространство на текущий момент (сколько реально занято), байты\n\ntotal_capacity - Сколько всего пространства на схд существует, байты",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "asPercent(#A, #B)",
     "targetFull": "asPercent(aliasByTags(seriesByTag('name=pure_rest_data', 'metric_name=total_physical', 'source=${system:regex}'), 'metric_name'), aliasByTags(seriesByTag('name=pure_rest_data', 'metric_name=capacity', 'source=${system:regex}'), 'metric_name'))"
    }
   ]
  },
  {
   "title": "Переподписка на $system",
   "type": "gauge",
   "description": "Отношение total_provisioned к total_capacity в процентах.\n\ntotal_provisioned - Выделенное пространство на текущий момент (сколько запрошено), байты \n\ntotal_capacity - Сколько всего пространства на схд существует, байты",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "asPercent(#A, #B)",
     "targetFull": "asPercent(aliasByTags(seriesByTag('name=pure_rest_data', 'metric_name=total_provisioned', 'source=${system:regex}'), 'metric_name'), aliasByTags(seriesByTag('name=pure_rest_data', 'metric_name=capacity', 'source=${system:regex}'), 'metric_name'))"
    }
   ]
  },
  {
   "title": "Занятое пространство на $system",
   "type": "graph",
   "description": "total_provisioned - Выделенное пространство на текущий момент (сколько запрошено), байты\n\ntotal_physical - Занятое пространство на текущий момент (сколько реально занято), байты\n\ntotal_capacity - Сколько всего пространства на схд существует, байты",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=pure_rest_data', 'metric_name=total_physical', 'source=${system:regex}'), 'metric_name')"
    },
    {
     "target": "aliasByTags(seriesByTag('name=pure_rest_data', 'metric_name=total_provisioned', 'source=${system:regex}'), 'metric_name')"
    },
    {
     "target": "alias(aliasByTags(seriesByTag('name=pure_rest_data', 'metric_name=capacity', 'source=${system:regex}'), 'metric_name'), 'total_capacity', false)"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Чтение на $system",
   "type": "graph",
   "description": "Пропускная способность на чтение (bwr) в секунду",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=pure_rest_data', 'metric_name=read_bytes_per_sec', 'source=${system:regex}'), 'metric_name')"
    }
   ]
  },
  {
   "title": "Запись на $system",
   "type": "graph",
   "description": "Пропускная способность на запись (bww) в секунду",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=pure_rest_data', 'metric_name=write_bytes_per_sec', 'source=${system:regex}'), 'metric_name')"
    }
   ]
  },
  {
   "title": "Задержки на чтение у $system",
   "type": "graph",
   "description": "Задержки на чтение (latency write), нужно разделить на 1000 или умножить на 0,001",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(scale(seriesByTag('name=pure_rest_data', 'metric_name=usec_per_read_op', 'source=${system:regex}'), 0.001, 0), 'metric_name')"
    }
   ]
  },
  {
   "title": "Задержки на запись у $system",
   "type": "graph",
   "description": "Задержки на запись в ms (latency write), нужно разделить на 1000 или умножить на 0,001",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(scale(seriesByTag('name=pure_rest_data', 'metric_name=usec_per_write_op', 'source=${system:regex}'), 0.001, 0), 'metric_name')"
    }
   ]
  },
  {
   "title": "Операций чтения в секунду у $system",
   "type": "graph",
   "description": "операций чтения в секунду (iops read)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=pure_rest_data', 'metric_name=reads_per_sec', 'source=${system:regex}'), 'metric_name')"
    }
   ]
  },
  {
   "title": "Операций записи в секунду у $system",
   "type": "graph",
   "description": "Операций записи в секунду (iops read)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=pure_rest_data', 'metric_name=writes_per_sec', 'source=${system:regex}'), 'metric_name')"
    }
   ]
  }
 ]
}