{
 "title": "СХД: Storwize (pool)",
 "description": "Ответственный: Лошкарев Д.Г. (АЦОД)",
 "tags": [
  "storwize",
  "storage",
  "sbis3mon-kafka",
  "system"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "storage",
    "query": "sbis3mon.$contur.storwize.volume.*"
   },
   {
    "name": "pool",
    "query": "sbis3mon.$contur.storwize.poolStatus.$storage.storwize.*.pool.storage.*"
   },
   { "name": "aggr", "label": "Агрегация", "query": "max, avg, min" }
  ]
 },
 "panels": [
  { "title": "Pool: $pool (bps, rps)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pool" },
  {
   "title": "pool: $pool bps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByNode(sbis3mon.$contur.storwize.mdiskPool.$storage.storwize.*.pool.io.bps.$pool.*.raw, -2), '$aggr')"
    }
   ]
  },
  {
   "title": "pool: $pool rps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByNode(sbis3mon.$contur.storwize.mdiskPool.$storage.storwize.*.pool.io.rps.$pool.*.raw, -2), '$aggr')"
    }
   ]
  },
  {
   "title": "pool: $pool time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "consolidateBy(aliasByNode(sbis3mon.$contur.storwize.mdiskPool.$storage.storwize.*.pool.io.time.$pool.*.raw, -2), '$aggr')"
    }
   ]
  }
 ]
}