{
 "title": "СХД: IBM XIV",
 "description": "Ответственный: Лошкарев Д.Г. (АЦОД)",
 "tags": [
  "telegraf",
  "xiv",
  "snmp",
  "storage",
  "system"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "system",
    "query": "tag_values(agent_host,contur=$contur)"
   }
  ]
 },
 "panels": [
  {
   "title": "FreeSpaceHard, Tb",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=xiv.cluster.FreeSpaceHard', 'contur=~${contur:regex}', 'agent_host=~${system:regex}'), 'agent_host'), 0)"
    }
   ]
  },
  {
   "title": "UtilizationHard, %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=xiv.cluster.UtilizationHard', 'contur=~${contur:regex}', 'agent_host=~${system:regex}'), 'agent_host'), 0)"
    }
   ]
  },
  {
   "title": "FailedDisks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=xiv.cluster.FailedDisks', 'contur=~${contur:regex}', 'agent_host=~${system:regex}'), 'agent_host'), 0)"
    }
   ]
  },
  {
   "title": "Interface IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(seriesByTag('name=xiv.cluster.InterfaceIOPS', 'contur=~${contur:regex}', 'index=~1.*', 'agent_host=~${system:regex}'), 'agent_host', 'index'), 0, -1)"
    }
   ]
  },
  {
   "title": "Hosts IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasSub(groupByNode(telegraf.$contur.xiv.cluster.{$system}*.*.interval-60s.HostIOPS, 4, 'sum'), '_2E', '.')"
    },
    {
     "target": "aliasByNode(aliasByTags(groupByTags(seriesByTag('name=xiv.cluster.HostIOPS', 'contur=~${contur:regex}', 'agent_host=~${system:regex}'), 'sum', 'agent_host'), 'agent_host'), 0)"
    }
   ]
  }
 ]
}