{
 "title": "СХД: XIV: сводный",
 "description": "Ответственный: Лошкарев Д.Г. (АЦОД)",
 "tags": [
  "telegraf",
  "storage",
  "system",
  "xiv"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "contur", "query": "prod" },
   {
    "name": "system",
    "query": "tag_values(agent_host,contur=$contur)"
   },
   {
    "name": "volume",
    "query": "tag_values(xivStatisticsVolumeName,agent_host=$system)"
   }
  ]
 },
 "panels": [
  {
   "title": "Задержки",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(highestMax(seriesByTag('name=xiv.volume.VolumeLatency', 'agent_host=~${system:regex}', 'xivStatisticsVolumeName=~${volume:regex}'), 20), 'agent_host', 'xivStatisticsVolumeName'), 0, -1)"
    }
   ]
  },
  {
   "title": "Поток данных",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(highestMax(seriesByTag('name=xiv.volume.VolumeBW', 'agent_host=~${system:regex}', 'xivStatisticsVolumeName=~${volume:regex}'), 20), 'agent_host', 'xivStatisticsVolumeName'), 0, -1)"
    }
   ]
  },
  {
   "title": "Кол-во операций",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasByTags(highestMax(seriesByTag('name=xiv.volume.VolumeIOPS', 'agent_host=~${system:regex}', 'xivStatisticsVolumeName=~${volume:regex}'), 20), 'agent_host', 'xivStatisticsVolumeName'), 0, -1)"
    }
   ]
  }
 ]
}